#+TITLE: "9月3日に裁判員裁判の初公判が始まり、同月18日判決が出ていた金沢片町ガールズバーの女性経営者殺害、能登町死体遺棄事件"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-10-03 22:23:47 +0900
FILE_NAME: 2019-10-03-222347_9月3日に裁判員裁判の初公判が始まり、同月18日判決が出ていた金沢片町ガールズバーの女性経営者殺害、能登町死体遺棄事件.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 能登町の遺体遺棄事件,能登町,旧柳田村,金沢地方裁判所,金沢地方検察庁,弁護団
記事タイトル名の文字数：59　保存ファイル名の文字数：81
#+STARTUP: showeverything


* 8人の弁護士が金沢地方裁判所に集結？　9月3日に裁判員裁判の初公判が始まり、同月18日判決が出ていた金沢片町ガールズバーの女性経営者殺害、能登町死体遺棄事件
  CLOCK: [2019-10-03 木 22:26]--[2019-10-04 金 03:24] =>  4:58

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 能登町の遺体遺棄事件,能登町,旧柳田村,金沢地方裁判所,金沢地方検察庁,弁護団

〉〉〉：Emacs： 2019-10-03（木曜日）22：26　 〉〉〉

　昨日だったと思いますが、テレビの石川県内ニュースで、主犯とされた被告が一人だけ控訴をしたということを知りました。この事件は起訴された後、報道がほとんどなくなり、ネットで調べてもずいぶん前の情報しかありませんでした。

　今年の春頃、何月だったか思い出せないですが、どうなっているのか気になってネットで調べたのですが、前の年の情報しか見つからなかったと記憶にあります。今夜見た判決のニュース記事では「昨年十月」とあります。

[link:]  首謀被告に懲役１７年 金沢地裁判決 他３人は１５～６年:北陸発:北陸中日新聞から:中日新聞(CHUNICHI Web) <https://www.chunichi.co.jp/hokuriku/article/news/CK2019091902000228.html>

　起訴されるまでは、ほぼ連日のように報道が続いていただけに、ぴたりと報道がなくなってまったく進展がわかりませんでした。昨日は、ミヤネ屋が終わった後の石川県内ニュースだったように思いますが、初公判も求刑も、判決もしらないまま、控訴したということを知りました。

　能登町の旧柳田村に遺体遺棄があり、同じ能登町出身者も一人関与があって逮捕されていたのですが、それ以外にもいろいろと気になり、参考になる事件でした。具体的には共犯関係と幇助になります。

　首謀者や主犯とされたのが29歳の被告で、判決が懲役17年、求刑が懲役20年とのことです。殺害の実行犯は45歳の一人だけのようですが、懲役15年、求刑が懲役18年となっています。共謀共同正犯という言葉はこのニュースで一度も見ていないのですが、そのようです。

　他2人は幇助犯とされていますが、一人は殺害方法を提案、もう一人は被害者を誘い出し指示で死体遺棄に使う車を用意したとあります。前者は懲役10年（求刑も同じ）、後者は懲役6年で求刑は懲役7年とあります。

　石川県では殺人事件自体が少なく年間数件かと思いますが、複数による殺害事件というのは10年ほど前に1件あったぐらいかと思います。白山市の自動車工場か運送会社の車のなかで遺体が発見された事件だったと思います。その事件も大阪の方で共犯者がいたように記憶にあります。

[link:]  車内に死体遺棄容疑、５人逮捕　３９歳男を指名手配：朝日新聞デジタル <https://www.asahi.com/articles/ASH483DCBH48PJLB001.html>

　Googleで検索するとすぐに情報が見つかりましたが、上記の記事は3日に遺体が見つかったとしながら、記事の配信と思われる時刻は2015年4月8日21時56分とあります。10年近く経っているような感覚だったので、この時期はちょっと驚きました。

[link:] » 白山市 遺体遺棄事件 - Google 検索 https://t.co/T9l4slPpmG

[link:] » 石川　白山遺体遺棄で懲役１３年判決　2016年06月06日 - 動画 Dailymotion https://t.co/CYkxmTKt47

　動画になっているニュースは6月6日という日付がみえますが、本文に去年4月とあります。実行犯と聞こえたように思いますが、他の共犯者も懲役9年から13年とあります。傷害致死なのかと思ったのですが、記事になっている部分を確認すると殺人と遺体遺棄とありました。

　田中聖浩裁判長とありますが、よくテレビニュースで見かけた記憶のある裁判長で、裁判長というにはずいぶん若く見えて、そのことも気になっていましたが、どちらかといえば厳しく重めの判決を出していたような印象が残っています。

　上記２つのニュース記事には見当たらず、埼玉県の被告はみましたが、この白山市の事件は、大阪の暴力団員が関与しているとテレビで報道を見ていたような気がします。具体的な話もテレビで見聞きしたように思いますが、内容はほとんど記憶にありません。

[link:] » 石川県白川市の死体遺棄事件 被害者は暴力団関係者とつながりか - ライブドアニュース https://t.co/48BfZF6ia8

　それらしいニュースも見つかりましたが、提供社の都合により削除とあるので、概要のみとなっています。私の記憶では大阪なのですが、能登町の遺体遺棄も関係者が大阪で仕事や生活をしていたとの報道でした。飲食店の経営で大阪に出店したのがそもそもの事件の原因だったようです。

　私が16歳ぐらいから19歳頃までよく一緒に遊んでいた連中も、大阪の方に仕事に出て共同生活をしたり、その後会社の社長にもなって今も大阪で生活していると聞きます。その辺りの始まりも、被告発人大網健二の兄OSNが、金沢で鳶職の仕事をするようになったきっかけと聞いています。

　それはちょうど、小木港の遠洋漁船に乗っていた友人知人が、漁師をやめて他の仕事をするようになった時期ともなっていました。彼らはよく「陸（おか）にあがる」という言い方をしていました。昭和59年から昭和63年ぐらいの間が多かったようにも思います。200海里の問題もありました。

　昭和59年は、宇出津の崎山でも借金苦での自殺や夜逃げが多発していると聞きましたし、地域の経済に対する影響も大きく、特に大工は失業や廃業が相次いでいると聞きました。珠洲市の若山から金沢市場輸送の大型運転手をするようになったYさんも大工をやっていたと聞きます。

　遠洋漁業で潤っていたのは小木と姫で、当時は小木が珠洲郡内浦町、隣接する姫が能都町でしたが、姫は住宅の新築率が石川県で一番だったとも聞きました。200海里問題や漁船の拿捕、操業禁止で急激に仕事が減って、立ち行かなくなったと聞きます。

　これは大事なポイントの１つですが、金沢市場輸送は小木港の遠洋漁船の元漁師が多かっただけではなく、当時の竹沢俊寿社長は、能登で金貸しをしていたと聞きます。被告発人安田敏がシンナーで錯乱し夫人の首を締め上げた夫の暴力団員も、昭和59年、社長室で見かけました。

　竹沢俊寿が能登で金貸しをしていたという話は、福井刑務所の受刑中に聞いたのですが、その話をしていた2人も元暴力団員で、金沢の片町でバーテンをしていた被告発人安田敏と付き合いがあったと聞きます。付き合いがあったという話は、出所後、被告発人安田敏本人に聞きました。

　被告発人安田敏本人は、シンナー中毒で死にかけたことなどを理由に関与を否定していましたが、被告発人安田敏が片町でバーテンをしていた関係者は薬物の密売で摘発されたらしく、新聞に割と大きな記事があったと記憶にあります。その報道のときに彼が打ち明けました。

　能登町の遺体遺棄事件はガールズバー女性経営者殺害事件などと報道されることが多かったのですが、バーのほとんどは女性の接客で、男性の方が珍しいのではと思いました。被告発人安田敏が片町でバーテンを初めた時期というのは、ちょうど男性による接客の店が出だした頃です。

　昭和62年か63年頃だと思うのですが、片町にサムライというディスコが出来ました。当時は黒服などとも呼ばれていたようですが、従業員のほとんどが男性ということで時代の変化を感じました。被告発人安田敏はそのディスコでしばらく仕事をしていたと聞きます。

　風の噂という感じでしたが、被告発人安田敏がサムライというディスコで仕事を初めたとか採用されたという話を聞きました。その後、一度だけ私は被告発人大網健二やKYNらとそのサムライというディスコに行ったのですが、被告発人安田敏が仕事をしているという飲み屋を探しました。

　場所は片町でもラブロの裏側で、店の名前が「ハートブレイク」と被告発人安田敏に聞いていました。大和デパートが今の香林坊のアトリオに移ったのは、その数年前で、前に大和デパートがあった場所がラブロだったと思います。考えてみるとラブロ恋路に似ています。

　百貨店にラブロという店名はどうかとも思うのですが、私の記憶ではラブロとなっています。屋上の方から飛び降り自殺があって客足が遠のき不振になったという話も聞いたことがありました。10日ほど前になりますか、富山県高岡市の大和デパートが閉店したというニュースもありました。

```
金沢の繁華街、片町に地場百貨店「大和」の本店として1934年（昭和9年）に開業して1986年（昭和61年）まで使用されていた［1］［5］。

その間10回ほど増改築を行って［1］1972年（昭和47年）に現在と同じ10階建てビルとなり［5］［6］、1986年（昭和61年）9月に同市内香林坊のアトリオに大和の店舗機能を移転後［2］、11月から専門店を中心とする「ラブロ片町」として開業した［2］［5］。

［source：］ラブロ片町 - Wikipedia https://ja.wikipedia.org/wiki/%E3%83%A9%E3%83%96%E3%83%AD%E7%89%87%E7%94%BA
```

　香林坊アトリオへの大和百貨店本店の移転は、昭和61年9月とあります。私が金沢市場輸送で初めての市内配達を初めたのは同年の8月20日過ぎのことで、香林坊アトリオも配達コースに含まれ、多くはなかったと思いますが、配達に行くことがありました。

　長男が生まれたのもその昭和61年の6月になりますが、生まれた後に片町の大和百貨店の屋上に行ったような記憶もかすかに残っています。屋上はちょっとした遊園地のようになっていました。香林坊アトリオの屋上もいくらか似たような場所にはなっていましたが、古さが違ったように思います。

　子どもの頃も、なんどか片町の大和デパートに行った記憶があり、屋上に近い階数にレストランがいくつかあって、そこでお子様ランチを食べたような記憶が残っています。金沢に親戚はなかったので、たぶん金沢ヘルスセンターに泊まったのではと思います。

　能登町の遺体遺棄現場ですが、私はその近くをその事件が起こる2ヶ月ほど前に通りかかっていました。こんな道路があったのかと少し驚いたのですが、ずっと気になっていた笹川という集落を通り抜けたところ、その遺体遺棄現場の近くの広い道路に出たのです。

　能登町の遺体遺棄事件は、テレビの各局が繰り返し報道をしていましたが、はっきり現場の場所がわかる地図入りの解説があったのは１つだけだったかもしれません。その１つの放送を見逃していていたらしらないままだったかもしれず、１つだけというのも不思議に思えました。

```
[186]  % pp -p|tac |grep 笹川  |tail -n 12
[link:] 2018-10-26_154844＿宇出津新港〜宇出津〜上田町〜宇加塚〜病院〜柳田温泉　笹川、川の上流の砂防ダム（余ノ井川）　上流側.jpg  http://hirono2014sk.blogspot.com/2018/11/2018110117152018-10-231205242018-10.html#20181026154844
[link:] 2018-10-03_163115＿病院と柳田温泉　振り返る神和住、笹川の道路案内標識.jpg  http://hirono2014sk.blogspot.com/2018/10/2018100410492018-09-251828352018-10.html#20181003163115
[link:] 2018-10-03_162625＿病院と柳田温泉　笹川　橋と笹川のバス停.jpg  http://hirono2014sk.blogspot.com/2018/10/2018100410492018-09-251828352018-10.html#20181003162625
[link:] 2018-10-03_162620＿病院と柳田温泉　笹川　橋を渡って右手.jpg  http://hirono2014sk.blogspot.com/2018/10/2018100410492018-09-251828352018-10.html#20181003162620
[link:] 2018-10-03_162617＿病院と柳田温泉　笹川　橋を渡って直進.jpg  http://hirono2014sk.blogspot.com/2018/10/2018100410492018-09-251828352018-10.html#20181003162617
[link:] 2018-09-17_003157＿柳田大祭　旧柳田村　笹川のバス停.jpg  http://hirono2014sk.blogspot.com/2018/09/2018092516272018-09-101818272018-09.html#20180917003157
[link:] 2018-09-03_184635＿上町の病院から柳田温泉　笹川のバス停.jpg  http://hirono2014sk.blogspot.com/2018/09/2018090510462018-09-011415212018-09.html#20180903184635
[link:] 2018-09-03_162653＿上町の病院から柳田温泉　旧柳田村笹川　川沿い　バス停方面.jpg  http://hirono2014sk.blogspot.com/2018/09/2018090510462018-09-011415212018-09.html#20180903162653
[link:] 2018-09-03_162645＿上町の病院から柳田温泉　旧柳田村笹川　川沿い.jpg  http://hirono2014sk.blogspot.com/2018/09/2018090510462018-09-011415212018-09.html#20180903162645
[link:] 2018-09-03_162519＿上町の病院から柳田温泉　旧柳田村　笹川のバス停付近.jpg  http://hirono2014sk.blogspot.com/2018/09/2018090510462018-09-011415212018-09.html#20180903162519
[link:] 2018-09-03_162516＿上町の病院から柳田温泉　旧柳田村　笹川のバス停前の道路.jpg  http://hirono2014sk.blogspot.com/2018/09/2018090510462018-09-011415212018-09.html#20180903162516
[link:] 2018-05-11_212211＿上町→桜峠→三井→輪島市内→高洲山→寝豚温泉＿笹川から上町・片側通行の信号待ち.jpg  http://hirono2014sk.blogspot.com/2018/05/2018051521032018-05-091329262018-05.html#20180511212211
```

　データベースに記録済みのもので笹川をファイル名に含むのは、昨年5月11日で高洲山に行ったときだとわかりました。輪島市の高洲山は奥能登で最も標高の高い山と聞きますが、それでも五百メートル台とのことです。道を間違えて輪島市に入って驚きました。

　笹川のバス停は割と立派で新しく見えるバス停となっていますが、小学生の低学年の頃に、時代劇に出てくるような古い掘っ立て小屋のようなバス停で、いらいらしながらバスが来るのを待っていたという記憶が断片的に残っています。

　結局なぜ小さいときに笹川のバス停にいたのかは謎のままなのですが、一つ考えられたのは、母親に連れられ、丘の上のような場所のいくらか西洋風にもみえた夫婦の家に遊びに行ったことです。テレビで見た満州の風景にも似ていました。

　その夫婦のこともぼんやりとしか記憶にないのですが、私の母親のことをずいぶんと熱烈に歓迎していました。それも戦争時代のドラマで見たような場面だったのですが、引き上げ船で命からがら日本に戻ってきた喜びを噛み締めているようにも見えました。

　笹川には、それと思われる丘のような場所はありませんでした。集落の間際に未開の割と大きな山がありました。あとは川沿いです。

　小高い丘の上で、小さい頃の記憶にある風景に似ていると思ったのは、消防署と公民館がある辺りの上町です。これはだいぶん前から感じていたのですが、バス停の後ろに田んぼが広がる上町のバス停で時間をつぶしたような記憶はまったく残っていません。

　笹川については、もう一つ記憶があって、昭和58年の9月だと思うのですが、川の橋を渡って笹川の集落に入り、同行者の知り合いと聞いた人の家にあがったことです。それも祭りのときだったと思います。被告発人大網健二が在所の祭りを巡って飲み食いし、神主だと言っていた頃のことです。

　柳田村の中心部では、まったく見ず知らずの家にあがりこんで飲み食いをしていました。「あんさまおるかね」の一言で飲み食いが出来るとも彼らは笑っていましたが、私は落ち着きもなく一緒にいるのがたまりませんでした。

　近年になって、祭りに知らない人を招いて飲み食いさせるのも、昔は地域の習慣だったと知ったのですが、当時はそういう知識もなく、非常識なふるまいにしか思えませんでした。祭りに友人知人を招いてごちそうを振る舞うのはいまでも普通のことで、よばれ、と呼ばれています。

　ただ、私の場合は、祭りのときも家に人を招くことはなく、余り詳しいこともしりません。それでも祭りに客人を招きもてなすのにかなりの借金をするという話は以前聞いたことがありました。

```
68件目 » 2018-10-03_162617＿病院と柳田温泉　笹川　橋を渡って直進.jpg

［link：］ 2018-10-03_162617＿病院と柳田温泉　笹川　橋を渡って直進.jpg <http：//hirono2014sk.blogspot.com/2018/10/2018100410492018-09-251828352018-10.html#20181003162617#20181003162617>

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： 2018年10月04日10：49記録＼法務検察・石川県警察宛＼写真資料：2018-09-25_182835〜2018-10-03_190824：104件 http://hirono2014sk.blogspot.com/2018/10/2018100410492018-09-251828352018-10.html#20181003162617
```

　昭和58年と思われる時期に笹川の集落に入ったのは夜でした。大きな街灯があったという記憶もなく、家の灯りのことがぼんやりと記憶に残っています。同じキリコ祭りでも、宇出津は私が子どもの頃からバッテリーの電球なのですが、柳田村は今でも蝋燭を灯しているようです。

　私が記憶にある範囲で初めて明るい時間に橋を渡って笹川の集落に入ったのは昨年2018年10月3日だったと確認しました。柳田の白山神社を初めて知ったのも、その年の8月ではなかったかと思います。道を間違えずに当目から来たときですが、キャッチボールの親子がいたので立ち寄りませんでした。

　少なくとも一月以上は間があいていたと思っていたのですが、笹川から通り抜けた広い道路に出て遺体遺棄現場の近くを通ったのは、遺体遺棄事件が起こったのと同じ10月だったようです。

[link:] » 山林に女性の遺体遺棄容疑　４４歳男逮捕、石川県警 - 産経ニュース https://t.co/23YxRaGt9x

　上記の記事は配信が2018年10月14日22時46分のようですが、14日に死体遺棄容疑で再逮捕、13日に1人、11日に2人を逮捕していたとあります。能登町の山林に遺体を埋めたのは9日ごろ、とされています。

　繰り返しますが、一月は間があるような感覚でした。同じ10月でも月末に近い頃と考えたのですが、11日に最初の逮捕があったとされています。このニュースを初めて知ったのもテレビだったと思いますが、前年3月の能登高校の女子高生殺害事件の記憶も蘇りました。

　被疑者が能登高校南のバス停で被害者を連れ去ってから、たしか1時間半ほどあとに、のと里山海道に入ってすぐ、対向車に飛び込んで自殺したという事件でした。殺害現場の民家には携帯電話と財布も残されていたという話です。

　この能登高校の女子高生殺害事件は、森友学園問題の報道と重なり、すぐに全国的な報道がなくなったのですが、後に出た石川県内のニュースでは、バス停にいた女子高生をいきなり角材で殴りつけ、頭蓋骨の骨折までさせたという話でした。

　状況から当初は性的ないたずらが目的だったと想像されますが、容態の急変で死なせてしまったと思ったのか、いずれにせよパニック状態になって車を走らせ自殺という結果になったようです。

　私の場合、いたずらが目的ではなく真意を確かめる目的で傷害・準強姦被告事件ということになったのですが、被害者の安藤文さんは、金沢西警察署に出頭したすぐあと、石川県立病院に向かう救急車内で意識を失い植物人間の状態になったと聞きます。

　金沢西警察署への出頭前に彼女が意識を失っていれば、出頭することなく一緒に心中を図っていた可能性が高いと思いますし、準強姦とされた行為の直後、彼女に「一緒に死ぬか」と声を掛け、このときだけは彼女らしいはっきりした口調で「いや」と言われたのです。

　嫌なら警察行くぞ、すぐに救急車を呼んでもらう、などと声を掛けたのですが、金沢西警察署に着いてから谷内孝志警部補に誰に殴られたと質問を受け、私の方を指差したと聞きます。その前に彼女は金石の海岸で、目が見えない、広野さん、私、目あいとる？、とも言い出していました。

　谷内孝志警部補に殴られた理由を尋ねられた彼女は、一言「わからん」と答えたということです。これも取り調べのときに谷内孝志警部補に話を聞きました。私が出頭してきた時の時刻を20時23分とも言い、なにかあれば時刻を確認するのが習慣とも話していました。

　能登高校女子高生殺害事件の被害者も同じ旧柳田村の天坂だったのですが、2017年の3月10日の夜に起きた事件で、最初にテレビで報道を見たのは翌11日の昼前の11時半から45分ごろだったと記憶にあります。

　翌年の1月の中頃だったと思います。宇出津の寒ブリまつりがあって、確かその前日にも捜索のヘリコプターが田ノ浦の上空を旋回していました。大規模な捜索は3日間で4日目からは、費用が家族の負担になるという話も聞きました。

　今度は能登高校の男子高校生が宇出津新港の堤防で行方不明となったのですが、それも旧柳田村で昔の村役場の近くに家があると聞きました。自殺を偽装した家出という見方もあったようですが、2ヶ月ほど後の3月中だったと思いますが、ナマコ引きの網で遺体があがったと聞きます。

　事故なのか自殺なのかという話でしたが、不可解なところはあったようです。1年ほどの間に他にも宇出津では宇出津新港と遠島山公園で2人が行方不明となり、そのまま見つかっていないようです。遠島山公園では、突然の病死という話もありますが、知っている人がもう一人亡くなっています。

　あれも2017年になるのかとも思いますが、小木港でも釣り人が行方不明となり、偽装工作という話も一部にあったのですが、2ヶ月ほどして、新潟県能町の底引き網から遺体が引き上げられたと聞きます。この遺体の発見は、いくらか不思議に思うほど小さなニュースでした。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-04 02:02／2018/01/25 23:37 URL： https://twitter.com/kk_hirono/status/1179803904675987456 https://twitter.com/hirono_hideki/status/956536468624654336
> 昨年の2016年は、能登町の海岸で3件の行方不明。小木港で転落した釣り人は、その後、新潟県の糸魚川市、たしか能町の底引き網で発見されたという。宇出津の2件は、いずれも発見されていないはず。1件は自殺の可能性。もう一件は宇出津新港で遊泳中ということになっていた。
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「能町」の検索結果 - Twilog https://t.co/wUdiVR0l97

　2018年1月25日のツイートに、昨年の2016年とあるのはおかしな話です。能町の検索結果が非公開のリツイート1件を含めて3件というのは意外に少ないものでした。昭和59年当時の金沢市場輸送の鮮魚の定期便では、国道8号線沿いの特に印象に残る風景に能町がありました。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-04 02:06／2018/01/25 23:32 URL： https://twitter.com/kk_hirono/status/1179805056423514112 https://twitter.com/hirono_hideki/status/956535149461565442
> 高１男子生徒が行方不明　石川・能登、下校途中に - 産経WEST https://t.co/wEXWybdoWJ 捜索打ち切りのニュースが見当たらないと確認。この件で、捜索は3日までは国か県の費用で、それ以降は、莫大な捜索費用がかかると聞いた。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-04 02:10／2017/05/08 12:46 URL： https://twitter.com/kk_hirono/status/1179806016487088130 https://twitter.com/hirono_hideki/status/861427082949050368
> 行方不明者の捜索願、という能登町の告知放送。70代らしい。
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「行方不明」の検索結果/Page 2 - Twilog https://t.co/0XGQW9M1xP

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-04 02:11／2017/02/05 21:29 URL： https://twitter.com/kk_hirono/status/1179806260645883905 https://twitter.com/hirono_hideki/status/828218927952044032
> 能登町で釣りの男性　行方不明 - NHK石川県のニュース https://t.co/k2JYW6qpic
▶▶▶　　　　　End　　　　　▶▶▶

　2017年2月5日にツイートをした「能登町で釣りの男性　行方不明」というNHK石川県内ニュースですが、私の記憶では最初に行方不明と知ったのは1月の最終日頃だったと思います。やはり2017年だったと確認しましたが、能登高校の女子高生殺害事件の一月ちょっと前だったようです。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-04 02:18／2018/10/14 21:08 URL： https://twitter.com/kk_hirono/status/1179807858445017088 https://twitter.com/hirono_hideki/status/1051444590417403905
> 山林に女性の遺体遺棄容疑、石川　４４歳男逮捕:社会:中日新聞(CHUNICHI Web) https://t.co/VeWIqzUMbo 岡本容疑者の逮捕容疑は９日ごろ、金沢市の喜多あき乃さんの遺体を能登町の山林に埋めた疑い。県警によると、容疑を認めている。
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「能登町 遺棄」の検索結果 - Twilog https://t.co/Wg1oS5356B

　私が最初に能登町の遺体遺棄事件をニュースで知ったのは、2018年10月14日のようです。21時のツイートというのも気になりますが、当日は日曜日とあるので、夕方に石川県内ニュースはなかったかもしれません。20時45分からはNHKで東海北陸のニュースなどがあります。

　2018年10月14日であれば、まだ1年に10日足らないので、すでにテレビ画面の撮影記録は習慣化していたかもしれません。

[link:] 2018-10-14-094637_「我、生還す-神となった死刑囚　袴田巖の52年-」（中京テレビ制作）を14日に放送する。.jpg  http://hirono2014sk.blogspot.com/2018/10/2018101511502018-10-08-1029002018-10-15.html#20181014094637

[link:] 2018-10-14_192732＿テレビの画面・NEWS７・元横綱　輪島さん　通夜　別れ惜しむ.jpg  http://hirono2014sk.blogspot.com/2018/10/2018102012382018-10-120729412018-10.html#20181014192732

[link:] 2018-10-14_195959＿テレビの画面・３０歳女性の遺体発見　男２人逮捕　金沢西警察署　能登町柳田死体遺棄.jpg  http://hirono2014sk.blogspot.com/2018/10/2018102012382018-10-120729412018-10.html#20181014195959

　都会の方だとどうかしらないですが、石川県のテレビでは19時59分59秒に県内ニュースというのは、ずいぶん珍しいことです。そういえば前に1,2度そういうことがあったような記憶はかすかに残っているのですが、遺体遺棄で逮捕というニュースとは記憶にありません。

　まだ写真を確認していないもののNHKの可能性が高いと考えています。民放でも石川県内ニュースは20時55分前後で、20時前には見ることがないような気がします。

```
122件目 » 2018-10-14_195820＿テレビの画面・３０歳女性の遺体発見　男２人逮捕　金沢西警察署　能登町柳田死体遺棄.jpg

［link：］ 2018-10-14_195820＿テレビの画面・３０歳女性の遺体発見　男２人逮捕　金沢西警察署　能登町柳田死体遺棄.jpg http：//hirono2014sk.blogspot.com/2018/10/2018102012382018-10-120729412018-10.html#20181014195959#20181014195820

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： 2018年10月20日12：38記録＼法務検察・石川県警察宛＼テレビの画面撮影資料：2018-10-12_072941〜2018-10-15_212449：292件 http://hirono2014sk.blogspot.com/2018/10/2018102012382018-10-120729412018-10.html#20181014195959
```

　臨時ニュースの扱いだったのかもしれないですが、「ダーウィンが来た！・だまし合う！托卵最前線　高度に進化！反撃の技」の放送直後、19時55分からニュースが始まったようです。

　金沢西警察署での記者会見の様子がありますが、わずか2分間のニュースだったようです。記録はないものの大河ドラマが終わった後と思われる20時45分のニュース番組の冒頭は、元横綱輪島さんの通夜が記録されていました。通夜ということで思い出すのも能登高校の事件です。

102件目 » 2018-10-13_221141＿テレビの画面・７DAYS・１６歳アイドル自殺の原因　パワハラと過重労働？.jpg

[link:] 2018-10-13_221141＿テレビの画面・７DAYS・１６歳アイドル自殺の原因　パワハラと過重労働？.jpg http://hirono2014sk.blogspot.com/2018/10/2018102012382018-10-120729412018-10.html#20181014195959#20181013221141

　離れた距離の映像でテレビ画面の撮影となっていますが、弁護士らの記者会見で、向かって右端に、このときも不自然にカメラを避けるように下を向いているのが向原栄大朗弁護士かと思います。あれからまだ1年経っていないというのは意外でした。

　記者会見の翌日辺りにたしか3人の弁護士が、愛媛県松山市の裁判所に入る映像があったと記憶にありますが、そこでの映像に中心的な立ち位置で出ていたのが望月弁護士ではなかったかと思います。

　そういえば10日から半月ほど、望月弁護士のTwitterのチェックも忘れていました。たしか7月の最終日近くに判決が延期され、検察の落ち度で無罪の可能性もあるなどとテレビで紹介されていた小嶺被告の弁護人です。その延期の報道で初めて弁護人だったと知りました。

　似たところがあるのは新井浩文被告の弁護人になっていたという趙誠峰弁護士です。高野隆弁護士の愛弟子のような存在感ですが、カルロス・ゴーン被告の刑事裁判もどうなっているのか、もう長い間、情報をみていません。弘中惇一郎弁護士の名前も聞くことはありません。

60件目 » 2018-10-12_204806＿テレビの画面・日本女性会議IN金沢　＃MeTooで議論　ジャーナリスト伊藤詩織さん.jpg

[link:] 2018-10-12_204806＿テレビの画面・日本女性会議IN金沢　＃MeTooで議論　ジャーナリスト伊藤詩織さん.jpg http://hirono2014sk.blogspot.com/2018/10/2018102012382018-10-120729412018-10.html#20181014195959#20181012204806

　伊藤詩織さんの民事裁判もどうなっているのか情報を見ていないですが、テレビに映像があったこともすっかり忘れていました。それも日本女性会議IN金沢とあります。

59件目 » 2018-10-12_204112＿テレビの画面・録画再生・NEWS７・最高裁が再審認める　33年前の殺人事件　松橋事件.jpg

[link:] 2018-10-12_204112＿テレビの画面・録画再生・NEWS７・最高裁が再審認める　33年前の殺人事件　松橋事件.jpg http://hirono2014sk.blogspot.com/2018/10/2018102012382018-10-120729412018-10.html#20181014195959#20181012204112

　あの松橋事件の再審のニュースも丸1年は経っていなかったようです。最高裁が再審認めるとあります。再審請求の決定ではなかったと思うので、再審の裁判が最高裁までもつれていたということになるのかもしれません。大崎事件とは明暗を分けた再審事件でもありました。

　たしか拳銃の所持は再審とは別だったのか有罪になったと報道があったと記憶にありますが、ネットでも疑問の声は見かけるこなく、受け入れられたという印象がありました。もともと詳しい内容を知る事件ではなく、大崎事件もそのまま再審無罪となっていれば、深く考えることもなかったと思います。

　「1件目 » 2018-10-12_072941＿テレビの画面・歌姫　テイラーさん　選挙に影響.jpg」まで下から遡って確認をしましたが、やはり2018年10月14日19時58分が能登町の遺体遺棄事件の最初の報道だったようです。それもいきなり金沢西警察署の記者会見から始まったようです。

　たしか主犯格とされた被疑者の住所が金沢市内の藤江で、それが理由で金沢西警察署の管轄になったとしか考えにくいです。被害者の住所は金沢市糸田一とあるので、金沢中警察署の管轄に間違いはなさそうに思います。殺害場所もその自宅前と今夜、確認しました。

　テレビでは何度も被害者の自宅前と思われる映像が出ていたのですが、すぐ近くに北陸本線の線路が見えました。その線路の辺りというのも、昔、車で通りかかっていたという記憶があります。平成15年1月に行ったKYNの会社事務所も、神田の陸橋の下辺りで、北陸本線が側にありました。

　殺害の事件現場や被害者の自宅住所が優先されるような感覚がありましたが、被疑者の住所地が管轄になったというのも考えるきっかけになりました。私の平成4年の傷害・準強姦被告事件も同じ金沢西警察署でしたが、住所地の東力二丁目は金沢中警察署の管轄だと思います。

　最近は殺人事件の公訴時効が撤廃されたためか、迷宮入りや宮入りという言葉も聞かなくなったのですが、新しくなった金沢西警察署の建物の横にも大野湊神社の鳥居があって、事件の報道のたびに映像に映り込むことが少なくないです。

〈〈〈：Emacs： 2019-10-04（金曜日）03：24 　〈〈〈

