#+TITLE: "首切断された韓国人女性　金沢地裁が殺意認めず　金沢市二俣町の山中"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-11-22 11:21:54 +0900
FILE_NAME: 2019-11-22-112154_首切断された韓国人女性　金沢地裁が殺意認めず　金沢市二俣町の山中.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 金沢地裁,金沢中警察署,マスコミ
記事タイトル名の文字数：32　保存ファイル名の文字数：54
#+STARTUP: showeverything


* 「遠くへ行きたい」金沢・小松の魅力と山海の幸を堪能！石川のルーツ探る旅：首切断された韓国人女性　金沢地裁が殺意認めず　金沢市二俣町の山中
  CLOCK: [2019-11-22 金 11:29]--[2019-11-22 金 14:54] =>  3:25

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 金沢地裁,金沢中警察署,マスコミ

〉〉〉：Emacs： 2019-11-22（金曜日）11：29　 〉〉〉

　２，３日前からガスコンロの点火が悪く、前にも一度経験があるのですが単一の乾電池を探したりばたばたとしていました。テレビのチャンネルのことも頭になかった状況で、始まったのが「「遠くへ行きたい」金沢・小松の魅力と山海の幸を堪能！石川のルーツ探る旅」の放送でした。

　２ヶ月ほど前にも同じようなことがあって、そのときは同じ「遠くへ行きたい」で輪島大祭や珠洲市三崎町の浜辺も番組に出ていました。個人的に縁のある風景だったので、それを突然テレビで見るというのも感慨深さがありました。

　いつもは気になるテレビ番組があるとTwitterでメモを残すようにしているのですが、いつも使っているYAHOOテレビは、番組の放送が終了するとデータも消えてしまうので、気がついたときには消えていて、別にGoogle検索で番組情報を調べました。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-22 11:39／2019/11/22 11:01 URL： https://twitter.com/kk_hirono/status/1197706165271986176 https://twitter.com/hirono_hideki/status/1197696589701120005
> 価格.com - 「遠くへ行きたい ～「金沢・小松の魅力と山海の幸を堪能！石川のルーツ探る旅」～」2019年11月10日（日）放送内容 | テレビ紹介情報 https://t.co/slwdcZpKcy
▶▶▶　　　　　End　　　　　▶▶▶

　前に同じ「遠くへ行きたい」の輪島市の回について調べたところ、一年ほど前の放送の再放送になっていてちょっと驚いたのですが、今回の金沢・小松は１２日前の１１月１０日に放送があったようです。この再放送ではない放送は石川県ではやっていないと思います。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-22 11:45／2019/09/06 10:31 URL： https://twitter.com/kk_hirono/status/1197707562172313601 https://twitter.com/hirono_hideki/status/1169785156351053824
> 遠くへ行きたい「片岡安祐美が石川・能登半島で秋を探す旅!大迫力の火祭り」 2019年9月6日（金）  10時25分～10時55分  の放送内容 https://t.co/gq6tueScaf
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-22 11:45／2019/06/28 10:32 URL： https://twitter.com/kk_hirono/status/1197707538315149313 https://twitter.com/hirono_hideki/status/1144418339755741184
> 遠くへ行きたい「鈴木ちなみ秋田の初夏…愛らしい秋田犬&amp;機関車の運転体験」  2019年6月28日（金）  10時25分～10時55分  の放送内容 https://t.co/agE5JKjTZU
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-22 11:44／2019/06/07 10:27 URL： https://twitter.com/kk_hirono/status/1197707505427574784 https://twitter.com/hirono_hideki/status/1136806979236589568
> 遠くへ行きたい「感動の連続!西村和彦が世界遺産・奈良のパワースポット巡り」  2019年6月7日（金）  10時25分～10時55分  の放送内容 https://t.co/FOrKHMm06w
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-22 11:44／2019/05/31 10:31 URL： https://twitter.com/kk_hirono/status/1197707464126296064 https://twitter.com/hirono_hideki/status/1134271090081984512
> 遠くへ行きたい「虻川美穂子が名湯“城崎温泉”&amp;念願の里山暮らしに大興奮」  2019年5月31日（金）  10時25分～10時55分  の放送内容 https://t.co/2yye4xgkk9
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-22 11:44／2019/05/17 10:29 URL： https://twitter.com/kk_hirono/status/1197707442135552001 https://twitter.com/hirono_hideki/status/1129197293557637120
> 遠くへ行きたい「前川泰之が大人の修学旅行!奈良の知られざる日本一を巡る」  2019年5月17日（金）  10時25分～10時55分  の放送内容 https://t.co/jpJ0lRGpTI
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-22 11:44／2019/04/26 10:54 URL： https://twitter.com/kk_hirono/status/1197707418311913477 https://twitter.com/hirono_hideki/status/1121593324786176000
> 遠くへ行きたい「ジャニーズ長谷川純が春の島根で初めて尽くしの大冒険!」  2019年4月26日（金）  10時25分～10時55分  の放送内容 https://t.co/7ngtJ6cbG9
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-22 11:44／2019/04/19 10:29 URL： https://twitter.com/kk_hirono/status/1197707390008754177 https://twitter.com/hirono_hideki/status/1119050396951957505
> 遠くへ行きたい「北国の春に牛走る!三倉佳奈が岩手で美味しい春の足音探し」  2019年4月19日（金）  10時25分～10時55分  の放送内容 https://t.co/vuyVd2IICO
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-22 11:44／2018/12/07 10:28 URL： https://twitter.com/kk_hirono/status/1197707366621315073 https://twitter.com/hirono_hideki/status/1070852451899568128
> 遠くへ行きたい「松尾諭が和歌山・熊野古道へ…美食&amp;温泉&amp;絶景の神秘旅」  2018年12月7日（金）  10時25分～10時55分  の放送内容 https://t.co/jHY4POorOd
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-22 11:44／2018/10/19 10:29 URL： https://twitter.com/kk_hirono/status/1197707334832668672 https://twitter.com/hirono_hideki/status/1053095645924323329
> 遠くへ行きたい「ますだおかだ増田が北海道・富良野“北の国から”聖地へ」  2018年10月19日（金）  10時25分～10時55分  の放送内容 https://t.co/TLIDj2rZ4F
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-22 11:44／2018/09/14 10:34 URL： https://twitter.com/kk_hirono/status/1197707297679503360 https://twitter.com/hirono_hideki/status/1040413381017006080
> 遠くへ行きたい「野々村真が山口県秋吉台～瀬戸内で涼しさたっぷりの夏休み」  2018年9月14日（金）  10時25分～10時55分  の放送内容 https://t.co/hJKy2N88II
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-22 11:43／2018/03/09 10:47 URL： https://twitter.com/kk_hirono/status/1197707246823600128 https://twitter.com/hirono_hideki/status/971925320549806080
> 遠くへ行きたい「眞島秀和が山形でふるさと再発見!雪国のごちそうめぐり旅」  2018年3月9日（金）  10時25分～10時55分  の放送内容 https://t.co/VU2VbzmDZb
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-22 11:43／2018/02/16 10:31 URL： https://twitter.com/kk_hirono/status/1197707207120318464 https://twitter.com/hirono_hideki/status/964311144679682048
> 遠くへ行きたい「パンダの楽園&amp;新鮮タチウオの刺身…和歌山・南紀」竹下景子  2018年2月16日（金）  10時25分～10時55分  の放送内容 https://t.co/Ogrk10HGg5
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-22 11:43／2017/09/15 10:31 URL： https://twitter.com/kk_hirono/status/1197707183003029504 https://twitter.com/hirono_hideki/status/908503440401272832
> 遠くへ行きたい「海がきれい!魚がうまい!山口で日本海満喫!石黒英雄」 2017年9月15日（金）  10時25分～10時55分  の放送内容 https://t.co/uAyLLQLuNA
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-22 11:43／2017/07/28 10:45 URL： https://twitter.com/kk_hirono/status/1197707163373686785 https://twitter.com/hirono_hideki/status/890749935955652610
> 遠くへ行きたい　的場浩司「北前船に夢をのせて!」青森～脇野沢～深浦 2017年7月28日（金）  10時25分～10時55分  の放送内容 https://t.co/0wng3p8aKt
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「遠くへ行きたい」の検索結果 - Twilog https://t.co/X0N63QDat7

　Twilogで「遠くへ行きたい」の放送を調べ、上記に奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)のツイートをリツイートしました。本当に忘れていた頃に見かける番組だったのですが、思いの外、数があって中には余り憶えのない放送もあります。

　放送内容の見出しだけでは思い出せないということで、最初に山形を見たときも、おやっと思ったのですが、続けて放送内容のツイートがあったので、子どもと地蔵のことを思い出しました。ツイートには「まわり地蔵」とありますが、記憶にあるのは、ロープで地蔵を引きずる場面です。

　山形県で「子ども」となると思い出すのは「山形マット死事件」のことで、弁護士らのその後の活動も異様なものがありましたが、主任検事として勾留延長をしなかったというのもモトケンこと矢部善朗弁護士（京都弁護士会）になります。

　すでに一通りのことは、告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)でも取り上げてきたように思います。消防署の救急車と落合洋司弁護士（東京弁護士会）のツイートのことは、ちょっと怪しい気もします。

[link:] » 告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)/「山形マット死」の検索結果 - Twilog https://t.co/0fR5GPFJtG

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中） 日時：2019-11-22 12:01／2016/03/04 17:57 URL： https://twitter.com/kk_hirono/status/1197711726789005312 https://twitter.com/kk_hirono/status/705678575660208128
> 「山形の植田裕弁護士・業務停止6月懲戒処分」というニュースは、この時初めて知ったものではなく、思い出して再度検索したものかと思います。見落としがちのニュースでしたが、確か小倉秀夫弁護士のツイートで山形マット死の事件との関連を知ることが出来、調べるきっかけになったと思います。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中） 日時：2019-11-22 12:00／2019/03/10 12:08 URL： https://twitter.com/kk_hirono/status/1197711491052400640 https://twitter.com/kk_hirono/status/1104579853129379840
> 過去に読んだ覚えのある落合洋司弁護士（東京弁護士会）のブログ記事です。はてなダイアリーからはてなブログに移行した記事だと思いますが、記事名は「山大生死亡:損賠訴訟　山形市長「適正な業務の範囲内」　救急車不出動で　／山形」が2012-08-24となっています。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中） 日時：2019-11-22 12:00／2019/03/10 12:15 URL： https://twitter.com/kk_hirono/status/1197711343429644289 https://twitter.com/kk_hirono/status/1104581393177145345
> 山大生死亡:損賠訴訟　山形市長「適正な業務の範囲内」　救急車不出動で　／山形 - 弁護士落合洋司（東京弁護士会）の日々是好日 https://t.co/dpfvhpqduf
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)/「山形 弁護士」の検索結果 - Twilog https://t.co/bJyrcSaimM

　時刻は１２時０２分です。テレビのバイキングはCMに入ったところですが、このあと木内みどり、さんについてお伝えします、という案内がありました。朝の他の情報番組でもみていたのですが、NHKの朝ドラのヒロインとそのドラマ名が全く記憶にないものだったのが、ちょっと驚きでした。

　広島だったと思いますが出張中の突然死であったようです。長い間、テレビで活躍をされたようですが、お名前に記憶がなかったので、情報番組と報道番組が中心になりますが、自分のテレビの視聴にも偏りがあるのかと考えました。バラエティもたまにみることはあります。

　訃報といえば、ニュース以外にみることがなかったのが、プロ野球で大記録をうちたてたとも聞く金田正一さんのことがあります。昭和５０年頃になると思いますが、週刊少年ジャンプにアストロ球団という漫画があって、一人だけ実在する人物が混じっているのがとても印象的でした。

　昭和５０年の４月、ちょうど藤波の辺田の浜から宇出津の小棚木に引っ越すときだったのですが、そのアストロ球団の漫画で、一試合を一年間掛けて描いていたことに気が付き、とても驚いたことを憶えています。超人的で現実離れした漫画で、とっても大仰でした。

　２００９年３月１５日に羽咋市から宇出津に戻るいくらか前だったと思いますが、天坂のシンザン能登店というパチンコ店で、アストロ球団のパチスロ機を見かけたような記憶があるのですが、ちょうどその頃に、同店では全敗で一度も勝ったことがないように考えていました。

　けっこうパチスロ機でコインが溜まったこともあるのですが、続けていると必ずなくなり、店に入った回数が多いのに、交換所に行ったのもほんのわずかであったように思います。ずいぶんと極端に感じていたので、客の顔を見て狙い撃ちにされているのかと勘ぐったことがありました。

　あるいは常連客が安定して勝ちやすいかトータルで大負けはしないという良心的なサービスの店であったのかもしれません。勝てる台が見つけやすければ、残りは負けやすいいわゆる回収台の可能性が高まります。

　休日に宇出津と羽咋市の往復に立ち寄ることが多かったですが、シンザン能登の隣には、もっと前からあるパーラーダイヤがあります。珠洲道路沿いで能登町天坂になります。パチンコ店の前にはラーメン店があって、今月は２回食事に行きました。

　ラーメン店はけっこう流行っていて、仕事中の車や作業服の客がいて、観光で能登に来たような人を見かけることもあったのですが、不思議とこれまで２つあるパチンコ店の客が、そのラーメン店に来ている、パチンコ店があるので店を構えたという発想はありませんでした。

　以前は、宇出津の駅前にあったラーメン店だと思いますが、そのときは一度ぐらいしか店に入ったことがなく、夜の時間帯でしたがその時の記憶が脳裏に焼き付いています。店の人のことは記憶になかったのですが、その前の昭和の時代は、能都町七見に店があったとも聞きます。

　宇出津駅前にラーメン店があった場所は、今も同じだと思いますが不動産会社になっています。祭礼委員の寄付金で訪問し、中を見たこともありましたが、以前ラーメン店であったような感じはしませんでした。横に細い道があって梶川沿いになるとも思います。

　２０１０年の２月頃になると思いますが、上町の母親の病院に行った後、パラーダイヤでパチスロをやっていて２万５千円ぐらい勝てたのですが、最終のバスに乗らず２３時の閉店までいたので、真冬の夜中に宇出津まで歩いて帰ったということもありました。１時間半ぐらいで帰れました。

　思い切って歩いたことで記憶にあるのは、金沢西警察署から香林坊１０９の書店までです。これは前に書いたことがあると思いますが、時期の特定やそのときの他の状況も思い出しがしづらくなっています。

　金沢市本多町の金沢中警察署に行ったのも、同じ日の可能性があるのですが、さきほど改めて考えていると、その金沢中警察署の中に入ったのは、その時が初めてだったと思われます。本多町と強調したのは、少なくとも昭和６１年の６月まで、金沢中警察署は別の場所にあったからです。

　考えてみると、運転免許の免許停止というのもその時以来ないと思いますが、免停明けに金沢中警察署に運転免許を取りに行きました。夜の遅い時間でしたが、これも改めて考えると、日付が変わった午前０時過ぎという可能性が高そうです。

　１５０日と９０日の免許停止を一度に受けました。山口県や兵庫県という県外での違反で処理が別々になったのですが、一度に来ていれば免許取り消しでした。今は免停の話を聞かないのでわからないことばかりですが、当時の免許停止の最長は１８０日だったと思います。

　金沢市本多町の金沢中警察署では、２階に相談室があったと思いますが、署内の一階は天井が高くて吹き抜けのようになっていたとも記憶します。デパートにありそうな部屋で完全な個室にはなっていなかったような記憶もあります。

　相談というか話の内容は、ほとんど思い出せず、その場の雰囲気をなんとなく憶えている程度です。福井刑務所に告訴か告発の調書作成に来た山岸警部補の名前を出したところ、それまでのふざけた感じの態度が改まり、力を込めた声で「殉職されました。」といわれました。

　印象での話なので、どうにでも書けてしまうし、その後に会ったこともなかったので全ては想像になりますが、金沢市場輸送や市場急配センターの内偵捜査の過程で、殺害された可能性があるのかもしれないという思いはあって、より慎重に制約を受けたところはあったと思います。

　山岸警部補についても、これまでに何度か取り上げていて、記憶にあったことはすべて書き出していると思います。これもTwilogで確認をしておきます。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中） 日時：2019-11-22 13:31／2018/02/18 18:00 URL： https://twitter.com/kk_hirono/status/1197734376823390208 https://twitter.com/kk_hirono/status/965149068233080832
> 役所のような建物には１階部分もあって、受刑者のエリアから入ってきて通路の右側の個室で、石川県警察本部の山岸警部補と告訴状のことで話をしたことがありました。刑務官の立会はなく二人っきりだったと思います。その場で、告訴調書を作成したようにも思います。
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)/「山岸警部補」の検索結果 - Twilog https://t.co/7PAEgQR9xi

　告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)で「山岸警部補」を含むツイートが２０１８年２月１８日の初出というのは意外でした。奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)の方も確認しておいた方がよさそうです。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-22 13:35／2018/01/08 18:54 URL： https://twitter.com/kk_hirono/status/1197735277722140673 https://twitter.com/hirono_hideki/status/950304670102126593
> テレビに元警察官だったという山岸という名前。けっこう長い時間字幕が出ていたがスマホの撮影に失敗。白山市左礫町の蕎麦屋らしい。テレビ金沢、となりのテレ金ちゃんの、たぶん「誉れがどこいく」というコーナー。自分の知る平成7年頃当時の石川県警察本部山岸警部補は殉職したと聞いた。
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「山岸警部補」の検索結果 - Twilog https://t.co/hhvvmhgtcg

　奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)も２０１８年１月８日が初出で、それも１件のみのツイートでした。白山市の元警察官の蕎麦屋のことが書いてあります。その元警察官の蕎麦屋の主人の名前も山岸警部補と同じ山岸とありますが、これは忘れていました。

　今日の「遠くへ行きたい」の放送ですが、ゴリという川魚が野生のタヌキのあとに出てきました。番組内では店の住所もみかなったのですが、「岩魚茶屋」で検索するとすぐに見つかりました。さきほどの「テレビ紹介情報」のページで見つけた情報からの検索です。

　岩魚というのはイワナのことだと思いますが、個人的に石川県としてほとんど情報を見かけなかった川魚です。長距離トラック運転手の仕事では国道沿いの店の看板などでも見けかることが多かったのですが、はっきり食べたという記憶もない川魚になります。

　国道２８６号線で、宮城県から山形県に入る手前、１０分ほど手前の辺りだったでしょうか、珍しい昼頃の時間に、妻子と食事をしたことがあり、その店がイワナをメインにしていたように思うのですが、イワナを食べたか、別に焼肉でも食べたのか憶えていません。山形方面に向かっていました。

　時間に余裕があったため油断をして、寝過ごしていたような記憶もあるのですが、そんな時間にその辺りにいて、金沢に向かっていたというのも珍しい運行だったので、よく憶えています。その店も普通の食堂ではなく、湯治場の旅館に近い雰囲気があったように思います。

　その国道２８６号線というのも山形自動車道が開通してからは通行することがなかったと思います。急な坂があったり、冬場は昼間でも路面凍結の心配があったので、冬場はやっかいな難所として記憶にあります。県境の笹谷トンネルは有料道路になっていました。

　有料道路の笹谷トンネルを使わない笹谷峠の旧道があるとベテランの運転手に話を聞いたこともありましたが、通行をしたことはありませんでした。

　国道２８６号線は、山形市側にも峠の茶屋のような食堂があって、私の人生において特別な思い出があるのですが、子ども２人だけを同乗させた宮城県女川町からの帰りという運行でした。この女川町についても書いておきたいことがいくつかあったのですが、中途半端になっていると思います。

[link:] » 笹谷トンネル - Google マップ https://t.co/OVlZNqeHC4

　複雑な模様のように見えたのですが、国道２８６号線が折れ曲がっているので上空からは道路がそう見えるようです。Googleマップで調べたのも今回が初めてではないと思いますが、ミステリーの地上絵にもみえる不思議な文様にみえます。

　笹谷という地名は、これまで山形県という認識でいたように思いますが、山形自動車道と思われる笹谷インターが宮城県側にあるので、宮城県の地名だったようです。そういえば、笹谷トンネルの料金所も、トンネルを抜けた宮城県側にあったような気もします。

　山形県側には関沢インターが見えますが、関沢という地名自体が余り記憶になかったもので、全然違った場所で見ていた地名という気もするぐらいです。具体的には新潟県内か福島県内ですが、同名の地名があったという可能性もあるかもしれません。

　山形市を航空写真の地図でみたのは今回が初めてという気もしたのですが、新庄市が山形市からけっこう離れてみえます。この山形県新庄市が山形マット死事件の場所としてニュースや記事で見てきたように思います。

　山形県新庄市についても前に調べていると思いますが、今回は最上川沿いに鶴岡市、酒田市につながる国道４７号線と、鳴子温泉を通って宮城県大崎市に出る道路が、こちらも国道４７号線だったのだと気が付きました。

〈〈〈：Emacs： 2019-11-22（金曜日）14：54 　〈〈〈

