#+TITLE: "「京都府警はマスコミとトレンドブログから金でも貰ってんの？」という2019年8月2日の匿名弁護士、刑裁サイ太のツイート"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-10-05 15:03:19 +0900
FILE_NAME: 2019-10-05-150319_「京都府警はマスコミとトレンドブログから金でも貰ってんの？」という2019年8月2日の匿名弁護士、刑裁サイ太のツイート.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 刑裁サイ太,京都府警,マスコミ,京アニ放火殺人事件
記事タイトル名の文字数：59　保存ファイル名の文字数：81
#+STARTUP: showeverything


* 「京都府警はマスコミとトレンドブログから金でも貰ってんの？」という2019年8月2日の匿名弁護士、刑裁サイ太のツイート
  CLOCK: [2019-10-05 土 15:05]--[2019-10-06 日 09:39] => 18:34

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 刑裁サイ太,京都府警,マスコミ,京アニ放火殺人事件

〉〉〉：Emacs： 2019-10-05（土曜日）15：05　 〉〉〉

　Twitterのトレンドに「死者36人」ではなかったかと思いますが、京アニ放火殺人事件関連のニュースがあって、ちょうどその時、ブラウザのタブで刑裁サイ太のツイートの検索をしていたので、「京アニ」「京都」とワードを変えて実行してみました。

　刑裁サイ太のTwitterの検索で京アニは見つからず、京都アニメーションを含む「京都」に検索ワードを変更したのですが、その中で見つけたのが、今回のエントリーに設定した次の刑裁サイ太のツイートになります。

uwaaaa ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW uwaaaa（サイ太） 日時：2019/08/02 16:23 URL： https://twitter.com/uwaaaa/status/1157190286541377538
> 京都府警はマスコミとトレンドブログから金でも貰ってんの？
▷▷▷　　　　　End　　　　　▷▷▷

　あえてそうしているのかと思いますが、刑裁サイ太のツイートは単発で前後の流れがつかみがたいものが多いという印象がかねてよりありました。今回もそのようになっているので、検索結果のツイートを１つ見ただけでは、京アニの事件との関わりを特定することも困難かと思います。

京都 (from：uwaaaa) - Twitter検索 / Twitter https://twitter.com/search?q=%E4%BA%AC%E9%83%BD%20(from%3Auwaaaa)&src=typed_query

京アニ (from：uwaaaa) - Twitter検索 / Twitter https://twitter.com/search?q=%E4%BA%AC%E3%82%A2%E3%83%8B%20(from%3Auwaaaa)&src=typed_query

noooooooorth (from：uwaaaa) - Twitter検索 / Twitter https://twitter.com/search?q=noooooooorth%20(from%3Auwaaaa)&src=typed_query

鬼 (from：uwaaaa) - Twitter検索 / Twitter https://twitter.com/search?q=%E9%AC%BC%20(from%3Auwaaaa)&src=typed_query

のような (from：uwaaaa) - Twitter検索 / Twitter https://twitter.com/search?q=%E3%81%AE%E3%82%88%E3%81%86%E3%81%AA%20(from%3Auwaaaa)&src=typed_query

臨 (from：uwaaaa) - Twitter検索 / Twitter https://twitter.com/search?q=%E8%87%A8%20(from%3Auwaaaa)&src=typed_query

厳しい (from：uwaaaa) - Twitter検索 / Twitter https://twitter.com/search?q=%E5%8E%B3%E3%81%97%E3%81%84%20(from%3Auwaaaa)&src=typed_query

伐折羅大将 (from：uwaaaa) - Twitter検索 / Twitter https://twitter.com/search?lang=ja&q=%E4%BC%90%E6%8A%98%E7%BE%85%E5%A4%A7%E5%B0%86%20(from%3Auwaaaa)&src=typed_query

uwaaaa ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW uwaaaa（サイ太） 日時：2017/08/18 16:08 URL： https://twitter.com/uwaaaa/status/898441519694135296
> #サークル名の由来を教えちゃう \n 「断罪法人　日本鬼法曹協会」 \n 鬼軍曹と，５００円切手の鬼神から着想を得て「鬼法曹」。ここからＮＨＫをパロって「日本鬼法曹協会」。さらに法人っぽくするために，財団法人をもじって「断罪法人」に。
▷▷▷　　　　　End　　　　　▷▷▷

切手の (from：uwaaaa) - Twitter検索 / Twitter https://twitter.com/search?q=%E5%88%87%E6%89%8B%E3%81%AE%20(from%3Auwaaaa)&src=typed_query

　ようやく探していた刑裁サイ太のツイートを発見しました。次のツイートです。

uwaaaa ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW uwaaaa（サイ太） 日時：2010/06/18 11:15 URL： https://twitter.com/uwaaaa/status/16434706070
> 500円切手の鬼のような厳しい態度で相手方に迫る「鬼法曹」になりたいです。
▷▷▷　　　　　End　　　　　▷▷▷

　鬼といえば、子どもの頃、賽の河原で幼子が積み上げた石を定期的にぶち壊しに来る、と聞いた憶えがあります。同じ頃、青森県の恐山のイタコについても本のようなもので読んでいたことを憶えています。

　この刑裁サイ太に代表される法クラとも自称他称するTwitterの弁護士らは、警察をまるで鬼のような疫病神として社会や世間に印象づけてきたという思いがあり、近年日増しに強い確信へ進むと同時に弁護士の危険生物性、地方病に類似した弁護士病の発見とも考察を深めるようになりました。

　深澤諭史弁護士と同様に登録がないと思いこんでいた刑裁サイ太のTwitterアカウントですが、確認するとTwilogの登録がありました。ただ、いつの登録かは不明であって、登録前のツイートは検索できないこともあるかと思います。

サイ太(@uwaaaa) - Twilog https://twilog.org/uwaaaa

　次が2019年8月2日の刑裁サイ太のTwilogになります。TwilogではリツイートのURLが、リツイートされた元のツイートのURLではなく、リツイートしたアカウントのURLになっているかと思います。私の知る限り、TwitterAPIの利用以外に取得の出来ないURLです。

uwaaaa ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW uwaaaa（サイ太） 日時：2019/08/02 11:19 URL： https://twitter.com/uwaaaa/status/1157113730397696002
> RT @kamatatylaw: 誤認逮捕された人が女子大学生だから捜査機関による執拗な自白強要にニュース性がでるのだろう。これがキモいおっさんだったら報道されることもなく、おっさんも執拗な自白強要に耐えられずに冤罪が生み出され結局泣き寝入りなのだろう。
▷▷▷　　　　　End　　　　　▷▷▷

　一見すると刑裁サイ太のツイートにみえるかと思います。しかし、URLを開くと高橋雄一郎弁護士のツイートが表示されるかと思います。

kamatatylaw ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW kamatatylaw（高橋雄一郎） 日時：2019/08/01 17:11 URL： https://twitter.com/kamatatylaw/status/1156839778521767936
> 誤認逮捕された人が女子大学生だから捜査機関による執拗な自白強要にニュース性がでるのだろう。これがキモいおっさんだったら報道されることもなく、おっさんも執拗な自白強要に耐えられずに冤罪が生み出され結局泣き寝入りなのだろう。
▷▷▷　　　　　End　　　　　▷▷▷

RT uwaaaa（サイ太）｜kamatatylaw（高橋雄一郎） 日時：2019/08/02 11:19／2019/08/01 17:11 URL： https://twitter.com/uwaaaa/status/1157113730397696002 https://twitter.com/kamatatylaw/status/1156839778521767936
> 誤認逮捕された人が女子大学生だから捜査機関による執拗な自白強要にニュース性がでるのだろう。これがキモいおっさんだったら報道されることもなく、おっさんも執拗な自白強要に耐えられずに冤罪が生み出され結局泣き寝入りなのだろう。

　水曜日に新たにインストールしたUbuntuの環境で、EmacsでツイートをインサートするF10のショートカットキーが使えていなかったのですが、日本語変換のキーボード設定にF10が割り当てられていて、それを解除したところ使えるようになりました。次から使っていきます。

RT uwaaaa（サイ太）｜asty_md（asty_md） 日時：2019/08/02 11:43／2019/08/02 11:37 URL： https://twitter.com/uwaaaa/status/1157119727338082307 https://twitter.com/asty_md/status/1157118208056287232
> "被害者遺族の感情が事件当初から変遷し、「死刑執行を求めない」としている場合、その意見を執行するかどうかの判断に反映してほしい" / 犯罪被害者団体、死刑執行前に被害者遺族の関与を求め要望書提出 https://t.co/YjKS4W5fpk

TW uwaaaa（サイ太） 日時： 2019/08/02 11:50 URL： https://twitter.com/uwaaaa/status/1157121508436692992
> 私も実は犯罪被害に遭った経験がありますが，犯罪被害対応で弁護士業務の時間を相当使わされたのが痛かったですね。やむを得ず分割で示談したら不起訴になりましたが，分割金はほぼ支払われずにバックレられました。八百選のネタになったので結果オーライでしたが，一般の方は大変でしょうね。

TW uwaaaa（サイ太） 日時： 2019/08/02 13:08 URL： https://twitter.com/uwaaaa/status/1157141001355399173
> 冤罪は遠い日の花火ではない

TW uwaaaa（サイ太） 日時： 2019/08/02 14:52 URL： https://twitter.com/uwaaaa/status/1157167288824373249
> 都会だと，評判もクソもないからこういう手法が蔓延してモラルハザードが起こりやすいですよね。 https://t.co/vmu2xed81b

RT uwaaaa（サイ太）｜o2441（弁護士大西洋一） 日時：2019/08/02 14:55／2019/08/02 14:54 URL： https://twitter.com/uwaaaa/status/1157167967076929536 https://twitter.com/o2441/status/1157167868988887040
> 交通事故訴訟やいじめ訴訟などでも、大半はまともな原告代理人だけど、たまに、これと似たようなことがあるな。全然取れる見込みないのにPTSD主張組み込んだりして訴額膨らませてくるんだよな。 https://t.co/0tAq1HKN6N

TW uwaaaa（サイ太） 日時： 2019/08/02 14:56 URL： https://twitter.com/uwaaaa/status/1157168263236710400
> ブランドに騙されて都会の弁護士に依頼して，その弁護士が安請け合いして結果が出なくて（解任ではなく）辞任した，みたいな事件の尻拭いを地方の弁護士はしています

　刑裁サイ太が東京都内ではない地方の弁護士だと自称しているツイートは見かけていますが、関東の弁護士であることも確認できる情報は見ておらず、身バレには相当慎重にも見えますが、コミケで大嘘判例などを直売しているらしいので、顔を知る人は少なくないはずです。

　その辺りも含め神出鬼没というのが刑裁サイ太の印象ですが、4,5年以上前になりますか、日弁連のPR動画があって、その動画に自分が出ていると刑裁サイ太がツイートをしていたので、特定は出来ないものの見ている顔の一つにはなっていたかもしれません。

TW uwaaaa（サイ太） 日時： 2019/08/02 14:57 URL： https://twitter.com/uwaaaa/status/1157168567185375233
> んで「前の弁護士に払ってしまったのでもうお金がないので，弁護士費用安くしてください」とか真顔で言われるんですが，こんな時どういう顔をすればいいのかわからないの

TW uwaaaa（サイ太） 日時： 2019/08/02 14:59 URL： https://twitter.com/uwaaaa/status/1157169058959089664
> メディアで積極的に誤情報を流している弁護士を肯定的に評価するの凄いな。 https://t.co/nszIx0UCxR

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Sakai_Takanori（酒井貴徳｜Holmes） 日時：2019-10-05 16:01／2019/08/02 11:53 URL： https://twitter.com/kk_hirono/status/1180377539610472448 https://twitter.com/Sakai_Takanori/status/1157122320147705857
> 視聴者としては、実際の相場がいくらかとか誰が本当に詳しいかとかは興味なくて、一番高い金額を書いた人に依頼しようとするんじゃないかな？  高い金額を取れる＝いい弁護士みたいな。  そうすると、メディア戦略として割り切って見れば佐藤弁… https://t.co/LeRvMKzGEC
▶▶▶　　　　　End　　　　　▶▶▶

　プロフィールに弁護士とあったものの余り見覚えのないアカウントと思いました。Twitterのプロフィールの名前は実名かと思います。やはり見覚えはないのですが、リストには登録済みでした。

　刑裁サイ太がURLを引用した上記の酒井貴徳弁護士のツイートは17件のツイート、42件のいいねと多めですが、ぶらさがる会話のツイートには佐藤大和弁護士の返信ツイートもあるのですが、リツイートが4件で2番目に多くなっています。10件とあるのが真下にある次のツイートです。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜koshikakebengo（弁護士 岩崎祥大（契約書サロン代表）） 日時：2019-10-05 16:08／2019/08/02 12:21 URL： https://twitter.com/kk_hirono/status/1180379100424232960 https://twitter.com/koshikakebengo/status/1157129389441576961
> @Sakai_Takanori この画像に映ってる方みなさんレイ法律事務所（佐藤弁護士が代表の事務所）の所属弁護士なので、  そもそも佐藤弁護士のメディア戦略の賜物ですね  映像は見れていないので文脈分からないですが メディア戦略… https://t.co/wLHsXHXbOQ
▶▶▶　　　　　End　　　　　▶▶▶

　直接、URLを引用した刑裁サイ太のツイートではわからなかったですが、「メディアで積極的に誤情報を流している弁護士を肯定的に評価するの凄いな。」と指摘しているのは佐藤大和弁護士の可能性がありそうです。これはちょっと意外な関係性でした。

TW uwaaaa（サイ太） 日時： 2019/08/02 15:02 URL： https://twitter.com/uwaaaa/status/1157169794405130240
> 国選について，「起訴後にしかつかない」とか「一部の罪名でしか被疑者国選はつかない」とか誤情報を掲載して私選に誘導する事務所と何が違うの？　こういう人はそういう事務所も肯定するの？

TW uwaaaa（サイ太） 日時： 2019/08/02 16:10 URL： https://twitter.com/uwaaaa/status/1157186922017509377
> ぶん殴りに行こうとしてしまったが，コミケ前なので自重します

RT uwaaaa（サイ太）｜luckymangan（リーチ一発ツモ裏１） 日時：2019/08/02 16:23／2019/08/02 15:43 URL： https://twitter.com/uwaaaa/status/1157190137119301632 https://twitter.com/luckymangan/status/1157180145309868032
> 「京都府警は「実名を拒否されている方については、引き続き実名公表について説明を行いご理解いただけるよう努力していく」とした」 すげえな。京都府警は拒否してる御遺族にさえ、実名公表を更に迫ってるのか…誤認逮捕の女子大生に自白迫るノリ… https://t.co/Z1K5zz9GXe

TW uwaaaa（サイ太） 日時： 2019/08/02 16:23 URL： https://twitter.com/uwaaaa/status/1157190286541377538
> 京都府警はマスコミとトレンドブログから金でも貰ってんの？

　「ぶん殴り」というツイートが8月2日16時10分。リーチ一発ツモ裏１の「すげえな。京都府警は拒否してる御遺族にさえ」というツイートのリツイートが16時23分、「京都府警はマスコミとトレンドブログから金でも貰ってんの？」のツイートが16時23分となっています。

　Twilogで並んだツイートをぱっとみるとわかりにくく誤解もありそうなのですが、ぶん殴りの刑裁サイ太のツイートは、京都府警のツイートの前に投稿されていたようです。順番が逆だと、京都府警やマスコミへの憤りなのかと推測してしまいそうです。

　このリーチ一発ツモ裏１というアカウントも匿名の弁護士の可能性が高いと思いますが、深澤諭史弁護士のタイムラインでリツイートとして見かけることが多いとも思います。一つまとめ記事を作成しておきましょう。

[link:] 2019年10月05日16時21分の登録： REGEXP：”@luckymangan”／深澤諭史（@fukazawas）の検索（2014-03-06〜2019-08-19／2019年10月05日16時21分の記録227件） http://hirono2014sk.blogspot.com/2019/10/regexpluckymanganfukazawas2014-03.html

　まだ投稿したばかりのまとめ記事を開いていませんが、弁護士鉄道の記録資料としてなかなかの内容になっていると思います。

▶（227／227） RT fukazawas（深澤諭史）｜luckymangan（リーチ一発ツモ裏１） 日時：2019-08-19 15:01:00 +0900／2019-03-02 22:05:00 +0900 URL： https://twitter.com/fukazawas/status/1163330105671733250 https://twitter.com/luckymangan/status/1101830843624972294
{% tweet 1163330105671733250 %}
> 「実は」反対なんて言ってる輩ははだしのゲンの町内会長だろ。本当に反対の人はハナから反対と言ってる。 https://t.co/I1upy2RT0f

▶（220／227） RT fukazawas（深澤諭史）｜luckymangan（リーチ一発ツモ裏１） 日時：2019-07-10 09:22:00 +0900／2019-05-10 11:08:00 +0900 URL： https://twitter.com/fukazawas/status/1148749305278156800 https://twitter.com/luckymangan/status/1126670421099606017
{% tweet 1148749305278156800 %}
> 「わたしの婚約者は祖国を守るため法テラスに赴いて、現在はどこの法テラスにもいません。先生、あなたはどこにいます？成仏を賛美なさるあなたはどこにいます？」 \n \n #司法英雄伝説

　次のツイートは、返信先にリーチ一発ツモ裏１のメンションが含まれています。

▶（216／227） TW fukazawas（深澤諭史） 日時： 2019-05-23 13:30:00 +0900 URL： https://twitter.com/fukazawas/status/1131417173342113792
{% tweet 1131417173342113792 %}
> @OneByeTaishoku @luckymangan ブロックは自由ですが、利用者に期待させる内容と異なる役務、あるいは違法な役務を提供する自由はないので、その可能性を潰すべく再検討を強くお勧めします。 \n また「適法性に疑問を呈… https://t.co/FdLcIEq9GL

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜OneByeTaishoku（退職代行ONE-BYE） 日時：2019-10-05 16:30／2019/09/24 17:31 URL： https://twitter.com/kk_hirono/status/1180384868494000130 https://twitter.com/OneByeTaishoku/status/1176413910041157632
> 退職代行ONE-BYEは、税込1万円でご利用者様の退職を代行させていただきます！追加料金は一切いただきません。 テレビ番組で特集していただいた際に、Yahoo!ニュースに掲載していただきましたので、是非ご一読ください！ https://t.co/HkUca8ZsUL
▶▶▶　　　　　End　　　　　▶▶▶

　やはりと深澤諭史弁護士が批判の矛先を向けていたアカウントを確認しましたが、アカウントが現在もそのままになっていて、上記にリツイートをしたツイートが固定されたツイートとなっています。9月24日ですが、ここでタイムラインを開いたのは数カ月ぶりかと思います。

　深澤諭史弁護士は「はだしのゲンの町内会長」に格別のこだわりを持っているらしく、まとめ記事も作成済みとして状況認識をしています。歴史的な意味合いもあるかと思う参考資料です。

```
[649]  % dp -p|grep 町内会長
[link:] 2017年11月11日21時09分の登録： ＼いわぽん　@yiwapon　RT：　@fukazawas＼「はだしのゲンの町内会長」現象として，数年前から予言しています。 \n （・∀・） http://hirono2014sk.blogspot.com/2017/11/yiwaponrtfukazawas.html
[link:] 2018年01月31日11時54分の登録： REGEXP：”はだしのゲンの町内会長”／データベース登録済みツイート：2018年01月31日11時53分の記録：ユーザ・投稿：13／32件 http://hirono2014sk.blogspot.com/2018/01/regexp2018013111531332.html
[link:] 2018年03月11日13時55分の登録： REGEXP：”町内会長”／深澤諭史（@fukazawas）の検索（2015-07-01〜2018-03-11／2018年03月11日13時55分の記録30件） http://hirono2014sk.blogspot.com/2018/03/regexpfukazawas2015-07-012018-03.html
[link:] 2018年03月15日10時12分の登録： ＼深澤諭史　@fukazawas＼テレビを付けていたら，はだしのゲンが実写化されて，町内会長の登場シーンかな？っておもったら，ただのニュースだった。 紛らわしいな（・∀・ http://hirono2014sk.blogspot.com/2018/03/fukazawas_25.html
[link:] 2018年07月22日14時23分の登録： REGEXP：”町内会長”／深澤諭史（@fukazawas）の検索（2015-07-01〜2018-07-07／2018年07月22日14時23分の記録36件） http://hirono2014sk.blogspot.com/2018/07/regexpfukazawas2015-07-012018-07.html
[link:] 2018年10月03日20時41分の登録： REGEXP：”町内会長”／深澤諭史（@fukazawas）の検索（2015-07-01〜2018-07-07／2018年10月03日20時40分の記録36件） http://hirono2014sk.blogspot.com/2018/10/regexpfukazawas2015-07-012018-07.html
[link:] 2018年12月09日11時24分の登録： REGEXP：”町内会長”／深澤諭史（@fukazawas）の検索（2015-07-01〜2018-12-09／2018年12月09日11時24分の記録37件） http://hirono2014sk.blogspot.com/2018/12/regexpfukazawas2015-07-012018-12.html
[link:] 2019年03月02日23時13分の登録： ＼リーチ一発ツモ裏１　@luckymangan＼「実は」反対なんて言ってる輩ははだしのゲンの町内会長だろ。本当に反対の人はハナから反対と言ってる。 http://hirono2014sk.blogspot.com/2019/03/luckymangan.html
[link:] 2019年08月19日15時40分の登録： ＼裁判員制度はいらないインコ　@nosaibaninko＼「俺は最初から失敗すると思ってたよ」という町内会長も。 http://hirono2014sk.blogspot.com/2019/08/nosaibaninko_19.html
[link:] 2019年08月19日16時06分の登録： REGEXP：”はだしのゲンの町内会長”／データベース登録済みツイート：2019年08月19日16時05分の記録：ユーザ・投稿：15／47件 http://hirono2014sk.blogspot.com/2019/08/regexp2019081916051547.html
```

　深澤諭史弁護士のツイート自体は記録が少なかったようです。

　「dp -p|grep 町内会長|grep 2019年10月05日|wc -l」というコマンドの実行で確認をしましたが、13件の記録追加を行ったことになるかと思います。歴史民俗資料館のような資料性としても貴重であると思料するので、あとで別のエントリーとして記録したいと思います。

　つい最近、自宅でもスマホでTwitterをみることが多くなったのですが、京アニと弁護士の組み合わせで検索を行い、検索結果のタイムラインをみていたところ、意外な発見がありました。

　京アニ放火殺人事件の事象についてほぼ同時進行でしたが、刑裁サイ太のTwitterから見るのとは、まったく別にも映る世界観でした。刑裁サイ太は弁護士以外にコミケのクリエーターとしても生計をたてている様子なので、準プロのような表現力も併せ持つのかもしれません。

　刑裁サイ太が身バレをせずにTwitterを続けているのも日弁連や弁護士会が関知せず、放任している事実なのだと思いますが、この辺りも弁護士の自由度の高さを思い知らせてくれる具体例です。

　私がこれまで将棋の飛車角のようだと指摘してきたのが、刑裁サイ太と並ぶローカスこと三浦義隆弁護士です。数年前は刑裁サイ太と同じローカスという匿名がほとんどだったのですが、だいぶん前から実名の方を優先し、顔出しや家族の写真も投稿されています。

　これまでにも折りに触れて取り上げたことはあったと思いますが、そのローカスこと三浦義隆弁護士の警察を愚弄する漫画のようなツイートを改めて、ここでご紹介しておきたいと思います。

[link:] 2017年12月13日23時17分の登録： ＼ystk　@lawkus＼「警察官は法律の素人です」 「認めれば不起訴にしてやる 認めれば執行猶予がある 黙秘すれば認めたのと同じになる 詳しくは言えないが動かぬ証拠を http://hirono2014sk.blogspot.com/2017/12/ystklawkus_22.html

[link:] 2018年06月19日04時20分の登録： ＼ystk　@lawkus＼\n\n警察に聞いたというのはつまり素人に聞いたということ。\n\nystkさんが追加\n http://hirono2014sk.blogspot.com/2018/06/ystklawkus-ystk.html

[link:] 2018年06月19日14時49分の登録： ＼ystk　@lawkus＼ちなみに警察官は刑法や刑事訴訟法もほとんど知らないのが通常です。警察官は法律を一切知らないという前提で接しておいた方が無難。 http://hirono2014sk.blogspot.com/2018/06/ystklawkus_76.html

[link:] 2018年12月01日19時37分の登録： ＼ystk　@lawkus＼警察官の偽証を片端から立件していくと警察官いなくなっちゃうんじゃねえのと思うくらい警察官は息を吐くように偽証する。 http://hirono2014sk.blogspot.com/2018/12/ystklawkus.html

[link:] 2019年01月31日20時15分の登録： ＼ystk　@lawkus＼このように情報をどんどん出す役人がいて、それを垂れ流すマスコミがいるという構図には少し興味ある。警察の大本営発表が真実のように拡散されてゆく事 http://hirono2014sk.blogspot.com/2019/01/ystklawkus_31.html

[link:] 2019年08月08日19時21分の登録： ＼ystk　@lawkus＼「警察は息を吐くように嘘をつく」という常識すら知らないから、この経緯を見て津田氏が嘘を言っていると決めつけるという間抜けな判断に至るのだろう。 http://hirono2014sk.blogspot.com/2019/08/ystklawkus_61.html

[link:] 2019年08月08日19時22分の登録： ＼弁護士 吉峯耕平（「カンママル」撲滅委員会）　@kyoshimine＼@lawkus 警察官はよく嘘をつくけど、違法捜査が問題になった場合とか、メンツがかかって引き返せ http://hirono2014sk.blogspot.com/2019/08/kyoshiminelawkus.html

　ローカスこと三浦義隆弁護士は、法律事務所の所在地が千葉県流山市となっているのですが、この千葉県流山市には国立民俗資料館のようなものがあって、宇出津のあばれ祭りが常設展示されていると地元で情報を見かけてきました。

　羽咋市の目立たない場所に公園があって、金沢地方検察庁の検面調書などをデジカメで撮影するため、その公園の中に入ったことがありました。室内で撮影すると日光が足らずにピンぼけしてしまう場合があり、連番として撮影する場合は、後の処理でも面倒が出ていました。

　よく車で通る道路沿いに公園はあったのですが、公園があるのも気づきにくかったと思います。撮影が終わった後だったと思いますが、公園の中に縄文時代の住居の模型の展示があって、それを見たのも印象的でした。なおその時撮影した写真は、所在が不明のままです。

　Nテックでの不動産のチラシなども撮影したはずですが、そのN・K興産株式会社の建物の一部を曲がりしていた不動産会社の名前も思い出せなくなっています。社長の家が金沢港の大野にあるとも被告発人大網健二は話していました。

　ちょっと思い出したのですが、西宅建で、N・K興産株式会社と同じく株式会社になっていたと思います。従業員はおらず、夫婦二人でやっているようなことを被告発人大網健二は話していたように思いますが、事務所で夫人の姿を見たことは記憶に残っていないと思います。

[link:] » 吉崎・次場弥生公園 - Google マップ https://t.co/0FAs1koYdd

　公園の名前は見た記憶もなかったのですが、上記の「吉崎・次場弥生公園」に間違いはないと思います。スーパーからアパートの帰り道によく通っていました。スーパーに行くときは、余り利用しない道路だったような気もします。目印もほとんどなく割とややこしい裏道でした。

　国立歴史民俗博物館・宇出津あばれ祭りの展示を考える \n  暴れる神輿からフェティシズムへの連想 \n 山田 彩加* \n （2018/08/07 公開） https://t.co/ODfaxBlIqK

　国立民俗資料館と思っていたのですが、国立歴史民俗博物館が正しいようです。場所も流山市ではなく佐倉市とありますが、能登町役場の下に下がる横断幕には、たしかに流山市とあったと記憶にあります。

　宇出津のあばれ祭りも見る人で違いも大きいのかと思いますが、物心着いた頃から最後に八坂神社で置き松明に投げ込まれ神輿が宮入りするまでの道中はカンノジと聞いてきました。神の路のようなイメージが漠然とあったのですが、近年になって観音寺が訛ったものだとしりました。

[link:] » 0000000600.pdf https://t.co/1pgetb0S9M

　上記のページもPDFファイルとなっていて、そのままページタイトルの取得が出来ないですが、Googleの検索結果には「[PDF]あばれ祭 - 能登町役場」と表示されています。平成25年から千葉県佐倉市の国立歴史民俗博物館に常設展示とあります。

　羽咋市から戻った平成21年ころから能登町役場の横断幕で見かけていたと思っていたのですが、平成25年というのは比較的最近のことだと思いました。しかし、なぜ自分が佐倉市を流山市と取り違えたまま今日まで疑いもなく思い込んでいたのか不思議です。

[link:] » 能登町の姉妹都市｜お知らせ｜能登町役場 https://t.co/M1JTIPRKgB \n 能登町では、千葉県流山市、宮崎県小林市の２市と姉妹都市の関係を結んでいます。

　調べたところ、やはり流山市は能登町と姉妹都市となっていて、これも能登町役場の横断幕にあったように思いますが、国立歴史民俗博物館の常設展示と混同をしていたようです。

```
能登町とのかかわり
　能登町合併前の旧内浦町では、能登杜氏として多くの方々が日本各地へ酒造りに出かけられ、流山市内の酒造会社に杜氏として勤められたのが縁で、流山市へ移住する方が多く、昭和初期に遡ります。長年友好的な交流を続けておりましたが、更に親交を深めるため、平成24年1月17日に姉妹都市の盟約を締結しました。

［source：］能登町の姉妹都市｜お知らせ｜能登町役場 http://www.town.noto.lg.jp/www/info/detail.jsp?common_id=7363
```

　能登町が千葉県流山市と姉妹都市になったかかわりを初めて知りましたが、酒造りの能登杜氏が縁であったとのことです。千葉県の野田市は醤油で有名ですが、千葉県で酒造りというのは聞いたことがないとも思いました。

〈〈〈：Emacs： 2019-10-06（日曜日）09：39 　〈〈〈


