#+TITLE: "「女性弁護士の自殺が多いというよりも、女性弁護士には自殺と隣り合わせの自営業が多い、というだけなのかもしれないけどね。」←高橋雄一郎弁護士"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-10-01 21:38:45 +0900
FILE_NAME: 2019-10-01-213845_「女性弁護士の自殺が多いというよりも、女性弁護士には自殺と隣り合わせの自営業が多い、というだけなのかもしれないけどね。」←高橋雄一郎弁護士.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 高橋雄一郎弁護士,弁護士の自殺,女性弁護士
記事タイトル名の文字数：69　保存ファイル名の文字数：91
#+STARTUP: showeverything


* 「女性弁護士の自殺が多いというよりも、女性弁護士には自殺と隣り合わせの自営業が多い、というだけなのかもしれないけどね。」←高橋雄一郎弁護士
  :LOGBOOK:
  CLOCK: [2019-10-01 火 21:40]--[2019-10-02 水 04:26] =>  6:46
  :END:

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 高橋雄一郎弁護士,弁護士の自殺,女性弁護士

〉〉〉：Emacs： 2019-10-01（火曜日）21：40　 〉〉〉

　夕方に見かけたジャーナリストの江川紹子氏の朝のツイートで、滋賀県の女性元看護助手の再審事件について思い出し、いろいろと考えていたのですが、それと類似点を感じている大阪の養女強姦再審無罪事件で、法クラの批判を浴びた女性検事のことを思い出していました。

　私のなかで滋賀県の弁護士といえば、滋賀県高島市の野田隼人弁護士になるのですが、滋賀県の再審事件のニュースについて触れたものはないかとタイムラインを見ていたところ、URLを引用されたツイートとしてやや久しぶりに高橋雄一郎弁護士のツイートを見かけました。

　予定では昼に続き、そのジャーナリストの江川紹子氏の滋賀県の再審事件を取り上げるつもりでいたのですが、弁護士の業界全体に考察の対象を広げる意味で、かねて注目している弁護士の一人、高橋雄一郎弁護士を登場させご紹介しておきたいと思いました。

　弁護士の自殺については、高橋雄一郎弁護士のタイムラインをみる少し前にも別のタイムラインで話題を見かけていたのですが、たぶん野田隼人弁護士のタイムラインだったと思います。弁護士業界における熾烈な生存競争のようなものも感じました。気を引き締めて取り組みますので。

　まずは、これまでのところのスクリーンショットの記録からご紹介をいたしたいと思います。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-10-01 21:57／2019/10/01 21:57 URL： https://twitter.com/kk_hirono/status/1179017563725942784 https://twitter.com/s_hirono/status/1179017436349124608
> 2019-10-01-213639_高橋雄一郎さんがリツイートモトケン@motoken_tw·9月29日フォロワーが増えてくると、フォロワーの中にもけっこうあれな人がいるということが見えてく.jpg https://t.co/215sdaUZHU
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-10-01 21:57／2019/10/01 21:56 URL： https://twitter.com/kk_hirono/status/1179017546726428672 https://twitter.com/s_hirono/status/1179017363657637888
> 2019-10-01-213550_高橋雄一郎@kamatatylaw·9月30日女性弁護士の自殺者は男性弁護士の自殺者数の15％だが、女性弁護士数は男性弁護士数の18％だから、女性弁護士の.jpg https://t.co/1DzKedgubl
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-10-01 21:57／2019/10/01 21:32 URL： https://twitter.com/kk_hirono/status/1179017501142704128 https://twitter.com/s_hirono/status/1179011092938293248
> 2019-10-01-212759_弁護士　野田隼人@nodahayato·10h平均よりだいぶ高い状態は変わらないんだけど，弁護士数の伸び率ほどは増えていないので，弁護士側のメンタリティに.jpg https://t.co/DBbgz2Bcac
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-10-01 21:57／2019/10/01 21:31 URL： https://twitter.com/kk_hirono/status/1179017431668232192 https://twitter.com/s_hirono/status/1179011020737499136
> 2019-10-01-212553_弁護士　野田隼人さんはTwitterを使っています：　「@teefjdee　@fukazawas　@gvashunyamamoto　バンコクですか？遊びに.jpg https://t.co/xYPQaBwwS7
▶▶▶　　　　　End　　　　　▶▶▶

　高橋雄一郎弁護士がモトケンこと矢部善朗弁護士（京都弁護士会）のツイートをリツイートしているのも珍しく感じましたが、モトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインでは見落としていた内容のツイートでした。

　高橋雄一郎弁護士もなにか思うところがあってモトケンこと矢部善朗弁護士（京都弁護士会）のツイートをリツイートしたのだと思いますが、賛同なのか否かを含め、これまで高橋雄一郎弁護士のツイートをみてきた範囲では推測も困難です。

nodahayato ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW nodahayato（弁護士　野田隼人） 日時：2019/10/01 10:48 URL： https://twitter.com/nodahayato/status/1178849026550067200
> 平均よりだいぶ高い状態は変わらないんだけど，弁護士数の伸び率ほどは増えていないので，弁護士側のメンタリティに変化を生じているのだと思っている。 https://t.co/AJN35u9d0J
▷▷▷　　　　　End　　　　　▷▷▷

kamatatylaw ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW kamatatylaw（高橋雄一郎） 日時：2019/09/30 14:26 URL： https://twitter.com/kamatatylaw/status/1178541719861641216
> 女性弁護士の自殺が多いというよりも、女性弁護士には自殺と隣り合わせの自営業が多い、というだけなのかもしれないけどね。
▷▷▷　　　　　End　　　　　▷▷▷

　野田隼人弁護士の方は間違いないと思っていましたが、高橋雄一郎弁護士の方でも告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)のアカウントがブロックされていることを確認しました。

```
[3684]  % dp -p|grep kamatatylaw|grep 検事
[link:] 2019年01月08日18時43分の登録： ＼高橋雄一郎　@kamatatylaw＼山吉彩子検事は「捜査研究2018年11月号」に「強制わいせつ罪等」に関する実務論考を発表されている。この分野のエキスパートだよ http://hirono2014sk.blogspot.com/2019/01/kamatatylaw201811.html
[link:] 2019年01月08日19時30分の登録： ＼高橋雄一郎　@kamatatylaw＼山吉彩子検事、俺と同期同クラスなんだ。模擬裁判で相手方だった。優秀で常識と人望があって教官に向いている人だよ。「潔白を主張する男性 http://hirono2014sk.blogspot.com/2019/01/kamatatylaw_8.html
```

　山吉彩子検事とあります。この名前もなかなか憶えられないのですが、Twitterで見かけたのも一時期のことで、大阪の強姦再審無罪事件の国賠訴訟がきっかけでした。数年前、刑事事件の再審請求でも注目されテレビのミヤネ屋などでも取り上げられていたかと思います。

　国賠請求は敗訴となっていましたが、刑事裁判の再審請求では知ることの出来なかった事実関係が国賠請求で不思議なぐらいネット上で明らかになっていました。

```
[3685]  % dp -p|grep 山吉
[link:] 2019年01月08日18時43分の登録： ＼高橋雄一郎　@kamatatylaw＼山吉彩子検事は「捜査研究2018年11月号」に「強制わいせつ罪等」に関する実務論考を発表されている。この分野のエキスパートだよ http://hirono2014sk.blogspot.com/2019/01/kamatatylaw201811.html
[link:] 2019年01月08日19時30分の登録： ＼高橋雄一郎　@kamatatylaw＼山吉彩子検事、俺と同期同クラスなんだ。模擬裁判で相手方だった。優秀で常識と人望があって教官に向いている人だよ。「潔白を主張する男性 http://hirono2014sk.blogspot.com/2019/01/kamatatylaw_8.html
[link:] 2019年01月10日01時03分の登録： ＼弁護士　山中理司　@yamanaka_osaka＼５６期の山吉彩子（やまよしさいこ）検事の任官後の経歴を掲載しました。 http://hirono2014sk.blogspot.com/2019/01/yamanakaosaka.html
[link:] 2019年01月12日09時28分の登録： REGEXP：”山吉彩子検事”／データベース登録済みツイート：2019年01月12日09時26分の記録：ユーザ・投稿：43／80件 http://hirono2014sk.blogspot.com/2019/01/regexp2019011209264380.html
[link:] 2019年01月12日12時06分の登録： ％@okumuraosaka　強制わいせつ/準強姦/買春/児童ポルノ/児童福祉法/青少年条例弁護人弁護士奥村徹(大阪弁護士会)％山吉彩子検事（56期 http://hirono2014sk.blogspot.com/2019/01/okumuraosaka56.html
[link:] 2019年05月27日12時03分の登録： REGEXP：”山吉彩子検事”／データベース登録済みツイート：2019年05月27日12時01分の記録：ユーザ・投稿：48／97件 http://hirono2014sk.blogspot.com/2019/05/regexp2019052712014897.html
```

```
アカウント名	ツイート数	リツイート数
奉納＼さらば弁護士鉄道・泥棒神社の物語（hirono_hideki）	6	0
弁護士あだちあだちけいたけいた（keita_adachi）	1	3
TｰTAKA（TGN54）	0	1
らめーん（shouwayoroyoro）	0	3
フミン（IcyFumin）	0	1
tochi0428（Mr_Bluegoat）	0	1
リーチ一発ツモ裏１（luckymangan）	0	3
!omikuji !dama ほりぐち（mstk_Horiguchi）	1	1
渡辺輝人（nabeteru1Q78）	0	1
えきなんローヤー?（ekinan_lawyer）	0	4
三毛猫B（poorpartner）	0	4
カロ（calowyer）	0	1
阿胡ノ海（agonoumi）	0	1
中村元弥（1961kumachin）	0	2
河﨑健一郎（kappamark）	0	1
高橋雄一郎（kamatatylaw）	3	0
1313（Kurosiro1313）	0	1
アリアンデルの猫（laparkadejapon）	0	2
皮下注（hirohika777）	0	2
サイ太（uwaaaa）	0	2
ワーキングプア弁護士（sokudokubengosi）	0	1
微笑みのロイヤー（smile_spirits）	0	1
けっす（keskil_）	0	1
当職ぴっぴ@梅吉（emeth_pippi）	0	1
井上雄樹（yinoue1975）	0	2
強制わいせつ/準強姦/買春/児童ポルノ/児童福祉法/青少年条例弁護人弁護士奥村徹(大阪弁護士会)（okumuraosaka）	1	0
弁護士 星　正秀（hoshimasahide）	0	1
鳩屋（haya_rt）	0	2
吉田哲也（yosidatetuya）	0	1
蛇毒（bigbrother939）	0	1
非常上告-最高検察庁御中_ツイッター（s_hirono）	9	0
霞 司郎（kasumi_shiro）	0	1
弁護士　山中理司（yamanaka_osaka）	0	9
yuji kigami　木上雄二（39801）	0	2
toujin（tou_jin）	0	1
山。（standing_Mt）	0	1
ちばまこと（makomayu1）	0	1
問題解決のお手伝い業者（okinawabengoshi）	0	1
けーぞ伯爵?（kzo_tan）	0	1
中野 俊徳（kanonjilawfirm）	0	2
玉井克哉（Katsuya TAMAI）（tamai1961）	0	5
田中・鈴木・木村（tanakasuzukikim）	0	1
ささきりょう（ssk_ryo）	0	1
中村剛（take-five）（take___five）	0	1
なべきょう＠過眠症（wata_nabekyo_ko）	0	1
浜ちゃん（lawer_hamachan）	0	1
たろう teacher（tomo_law_）	0	1
深澤諭史（fukazawas）	0	1


［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”山吉彩子検事”／データベース登録済みツイート：2019年05月27日12時01分の記録：ユーザ・投稿：48／97件 http://hirono2014sk.blogspot.com/2019/05/regexp2019052712014897.html
```

▶（01／97） TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2019-01-08 07:17:00 +0900 URL： https://twitter.com/hirono_hideki/status/1082400831863808000
{% tweet 1082400831863808000 %}
> 弁護側は、捜査・公判を通じて虚偽の被害証言が見逃された原因を明らかにするために男性を取り調べた山吉彩子検事らの証人尋問を求めるも、芦高源（あしたかみなもと）裁判長は退けている。 https://t.co/KZohZNx5T0

▶（02／97） TW keita_adachi（弁護士あだちあだちけいたけいた） 日時： 2019-01-08 14:13:00 +0900 URL： https://twitter.com/keita_adachi/status/1082505494105706496
{% tweet 1082505494105706496 %}
> ＞捜査段階で男性を取り調べた山吉彩子検事（2017年4月から司法研修所の検察教官）は、潔白を主張する男性に「絶対許さない」と言い放ち、全く取り合おうとしなかった。 \n \n 性的被害を受けたというウソの証言で約6年も身柄拘束　人が人を裁… https://t.co/yeCxLAjw0M

keita_adachi ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW keita_adachi（弁護士あだちけいた @100％の晴れ男） 日時：2019/01/08 14:13 URL： https://twitter.com/keita_adachi/status/1082505494105706496
> ＞捜査段階で男性を取り調べた山吉彩子検事（2017年4月から司法研修所の検察教官）は、潔白を主張する男性に「絶対許さない」と言い放ち、全く取り合おうとしなかった。  \n  \n 性的被害を受けたというウソの証言で約6年も身柄拘束　人が人を裁… https://t.co/yeCxLAjw0M
▷▷▷　　　　　End　　　　　▷▷▷

▶（10／97） TW mstk_Horiguchi（!omikuji !dama ほりぐち） 日時： 2019-01-08 14:56:00 +0900 URL： https://twitter.com/mstk_Horiguchi/status/1082516400999022592
{% tweet 1082516400999022592 %}
> 山吉彩子検事はあだちさんと同期か。つまり有名ツイッタラー弁護士の面々と同期なんだな

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜mstk_Horiguchi（ほりぐちです） 日時：2019-10-01 22:24／2019/01/08 14:56 URL： https://twitter.com/kk_hirono/status/1179024339938603008 https://twitter.com/mstk_Horiguchi/status/1082516400999022592
> 山吉彩子検事はあだちさんと同期か。つまり有名ツイッタラー弁護士の面々と同期なんだな
▶▶▶　　　　　End　　　　　▶▶▶

▶（23／97） TW kamatatylaw（高橋雄一郎） 日時： 2019-01-08 15:43:00 +0900 URL： https://twitter.com/kamatatylaw/status/1082528211882336256
{% tweet 1082528211882336256 %}
> 山吉彩子検事は「捜査研究2018年11月号」に「強制わいせつ罪等」に関する実務論考を発表されている。この分野のエキスパートだよ。https://t.co/mxyLAOevZD

　ざっとまとめ記事に目を通しましたが、高橋雄一郎弁護士と足立啓太弁護士のツイートのリツイートがほとんどでした。「山吉彩子検事はあだちさんと同期か」という堀口弁護士のツイートもあるので、足立啓太弁護士も同期なのかもしれません。これは記憶になかったです。

　この堀口弁護士は、ネットで調べると実名や事務所名、顔写真も出てきますが、以前、ジャーナリストの江川紹子氏との間に衝突のようなものがあり、なにでもめたのかも忘れていますが、ジャーナリストの江川紹子氏が堀口弁護士を偽弁護士扱いしたことが怒りとなったようです。

```
ほりぐちです
@mstk_Horiguchi
ネタツイートが多く一部では偽弁護士と呼ばれています。
虚数時間のディラックの海2011年5月からTwitterを利用しています
1,896 フォロー中
4,314 フォロワー

［source：］ほりぐちです（@mstk_Horiguchi）さん / Twitter https://twitter.com/mstk_Horiguchi?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1082516400999022592&ref_url=http%3A%2F%2Fhirono2014sk.blogspot.com%2F2019%2F05%2Fregexp2019052712014897.html
```

　堀口弁護士のTwitterアカウントのプロフィールの写真ですが、拡大表示をしてみると、普通に生ビールのジョッキを口にしているということに気が付きました。バーテンダーがカクテルの味見をしているイメージが強く、それ以上深く考えずにいました。

　堀口弁護士には、どことなく高橋雄一郎弁護士との共通点も感じています。以前調べた堀口弁護士の法律事務所の所在地が、高橋雄一郎弁護士の蒲田に近かったのかもしれません。

　確認のためGoogleの画像検索から見覚えのある顔写真で調べたところ、事務所の所在は東京都千代田区となっていたので、蒲田とは無関係でした。

```
高橋雄一郎
@kamatatylaw
弁理士兼技術系の若手（）弁護士（マイノリティ），ほぼ特許事件だけで生活しています。法律書を読むことと準備書面起案が趣味，ツイートは思考実験です。酒屋兼営のJSAソムリエ。東京弁護士会所属
東京都大田区蒲田blogs.yahoo.co.jp/kamatatylaw2009年3月からTwitterを利用しています
8 フォロー中
1.7万 フォロワー

［source：］高橋雄一郎（@kamatatylaw）さん / Twitter https://twitter.com/kamatatylaw?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1082769095043366912&ref_url=http%3A%2F%2Fhirono2014sk.blogspot.com%2F2019%2F05%2Fregexp2019052712014897.html
```

　そういえばと高橋雄一郎弁護士のTwitterアカウントのプロフィールをみて気がついたのですが、「酒屋兼営のJSAソムリエ」とあります。厳密に言えばソムリエとバーテンダーは違うということかと思いますが、個人的なイメージとしてはかなり似通った気がします。

　特許といえば、以前法律の勉強をしていた時の知識で弁護士よりは弁理士というイメージが強いのですが、プロフィールに弁理士という資格は見当たりません。税理士の場合は弁護士資格に含まれるような話も過去に見かけていますが、弁理士は違ったように思います。

[link:] » 「弁護士」と「弁理士」の違いって？ 両資格を持つ先生に聞いた【高校生なう】｜【スタディサプリ進路】高校生に関するニュースを配信 https://t.co/H1tA1slbKN

```
弁護士資格を持てば、登録できる資格
裁判書類の作成や法律相談業務、刑事裁判の弁護人、民事裁判の代理人など、弁護士は法律に関するすべての業務を独占的に認められています。資格の汎用性は非常に高く、ほかの士業業務の兼任、および他資格の登録もこれひとつで可能です。

以下は、弁護士の資格取得によって登録できる資格の種類です。

弁理士
税理士
社会保険労務士
行政書士
海事補佐人
なお資格登録する際は、弁理士は日本弁理士会、税理士は日本税理士連合会、行政書士は日本行政書士連合会、社会保険労務士は全国社会保険労務士会連合会、海事補佐人は国土交通省海難審判所に登録申請することになります。それぞれの登録には登録費用がかかる点も押せておく必要があります。

［source：］弁護士資格を取れば、税理士や社労士など他の資格も得られる！？ - 司法試験 予備試験対策のスマホ通信講座 https://studying.jp/shihou/about-more/other-capacity.html
```

　どうも弁護士資格を有することで弁理士の資格登録もできるようです。登録できない資格としては、公認会計士、土地家屋調査士があげられています。弁理士も税理士も登録に必要な審査などについては触れられていないようです。審査があるのかないのかも不明です。

　食い詰める弁護士が少なくないとは聞きますが、税理士や弁理士の登録でそちらに専門を移し専念した弁護士の話というのは、今までのところ見かけたことがありません。

　社会では「つぶしがきく仕事」という話を聞いたことがありますが、弁護士については聞いたことがありません。特定の仕事で自殺率がデータ化されたのも弁護士以外には見かけたことがないのですが、今回はその男女比についても見かけたことになります。自殺率は数年前から見ています。

　そういえば、元弁護士という女性ライターのことも久しぶりに思い出しました。今年の2月か3月頃に法クラの間のツイートでよく見かけた時期がありました。別れさせ屋という探偵社のホームページにもその元弁護士の女性の紹介がありました。

　この女性弁護士の場合、専業主婦のような一面もあったようなので、必ずしも仕事をしなければ生活が成り立たない事情はないのかもしれません。ピリカというペンネームであったようにも思います。丸っきり情報を見かけなくなっていたので、すっかり忘れていました。

```
ぴりか

元弁護士の経験を活かして、法律記事を中心にライターとして活動。法律事務所様や法律系ポータルサイト様などから受注が多いです。交通事故、刑事事件、労働トラブル、企業法務、離婚、相続、不動産などほとんどどのような分野にも対応可能です。一般ライターとは違い専門的な内容にも対応でき、SEOに対する理解もあるので効果的に集客アップのサポートができます。お気軽にご相談下さい。

［source：］元弁護士・ライターのプロフィール | 元弁護士・ライターぴりかの法律blog https://legalharuka.com/339
```

```
元弁護士ライター　福谷　陽子（Facebook）

※ 現在弁護士会への登録を行っていないため「元」弁護士と表記しております。

［source：］元弁護士ライター　福谷　陽子 https://www.syakkin-g.com/expert/fukutani-youko
```

　Google検索の他の候補にも名前が出てきたのですが、見覚えのない名前だと思いました。しかし、検索に出てきた顔写真には見覚えがあって、上記のページには顔写真入りの大阪弁護士会の身分証明書があります。弁護士会の身分証明書というのも初めて知った気がします。

```
元弁護士　 福谷陽子
司法修習期57期
京都大学法学部卒（現役）。在学中に司法試験に合格。その後1年ほど海外旅行などをして過ごし、弁護士登録をする。
その後、陽花法律事務所を7年間経営。
現在は経営アドバイス、代表者向けの各種のカウンセリング業などを行っている。

 

別れさせ屋アドバイザーコラム
「別れさせ工作」が「合法」と判断された裁判例の解説
別れさせ屋株式会社の法的遵守・コンプライアンス体制について

［source：］別れさせ屋経営顧問のご紹介 - 別れさせ屋株式会社の別れさせ工作(公式) http://xn--48jm9l298kivk.jp/about/ceo_adviser.html
```

　以前見かけた憶えのあるホームページですが、取得したページタイトルをみると「別れさせ屋経営顧問のご紹介」とあります。弁護士会への登録、会費の支払いをせずに元弁護士という肩書を使っているため、法クラの弁護士らの批判を受けていましたが、いつのまにか見かけなくなっていました。

　元弁護士といえば思い出すのは佐田元弁護士かと思いますが、元弁護士ではなくややこしくなっていました。これもジャーナリストの江川紹子氏と関連があって、こちらはジャーナリストの江川紹子氏の強い支持がありました。

```
佐田元眞己弁護士が懲戒請求で業務停止は一年で実は契約が佐田元弁護士が履行する気がないというのを調べた人がいて発覚して、佐田元弁護士は調べて弁護士会へ報告する人がいることを知るいい教訓になったと思う。

［source：］オウム真理教の宗教活動を佐田元眞己弁護士が語る | なんでもない日々 - 楽天ブログ https://plaza.rakuten.co.jp/sinagawa1992/diary/201904010000/
```

　今年の4月2日の記事となっていますが、これは初めて知りました。佐田元弁護士のGoogle検索で上位に出ていました。

```
MBS　ニュース
引用先
http：//www.mbs.jp/news/kansai/20170123/00000051.shtml
 
成年後見人として管理している口座の金などあわせて約570万円を横領したとして、大阪弁護士会の弁護士が業務停止の懲戒処分を受けました。1年間の業務停止処分を受けたのは大阪弁護士会の佐田元眞己弁護士（56）です。弁護士会によりますと、佐田弁護士は男性の依頼者から預かった約105万円をおととし3月ころから約20回にわたり着服。さらにこの穴埋めをするため、自らが成年後見人として管理している口座から38回にわたり現金を引き出すなどして会わせて約570万円を横領したということです。
去年1月自らが裁判所に申告をして横領が発覚し弁済したということです。
佐田元弁護士は4年前、取り調べの録音映像をNHKに提供し、目的外使用にあたると指摘される問題を起こしていました。
 

［source：］佐田元眞已弁護士（大阪）懲戒処分の要旨 – 弁護士自治を考える会 https://jlfmt.com/2017/05/30/31314/
```

　佐田元弁護士についても以前調べまくったと思うのですが、2017年5月30日の記事に56歳とあるのは、イメージとは違って分別のありそうな年齢でした。

[link:] » 佐田元真己弁護士（大阪弁護士会）が大阪地検に懲戒請求された問題で、大阪弁 護士会は１５日、懲戒処分をしないと決定した。 | 告発-金沢地方検察庁御中_2013 https://t.co/D5Ii6lOmSz

```
アカウント名	ツイート数	リツイート数
児童買春/ポルノ/わいせつ/淫行弁護人（okumuraosaka）	1	0
奉納＼さらば弁護士鉄道・泥棒神社の物語（hirono_hideki）	6	2
ほりぐち（mstk_Horiguchi）	1	0
Shoko Egawa（amneris84）	2	0
非常上告-最高検察庁御中_ツイッター（s_hirono）	1	0


［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”佐田元（眞己）？弁護士”／データベース登録済みツイート：2017年11月23日11時53分の記録：ユーザ・投稿：5／13件 http://hirono2014sk.blogspot.com/2017/11/regexp201711231153513.html
```

▶（02／13） TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2013-06-17 00:40:00 +0900 URL： https://twitter.com/hirono_hideki/status/346291274317443072
> 【裁判記録は誰のものか】「これは国民の知る権利の問題です」(江川 紹子) - 個人 - Yahoo!ニュース http://t.co/guflGisvon target="_blank">http://t.co/guflGisvon 佐田元真己弁護士というのは佐田元という姓らしく佐田元弁護士という表記が多くて、弁護士を辞めた人かと思った。

▶（06／13） TW mstk_Horiguchi（ほりぐち） 日時： 2014-01-08 12:29:00 +0900 URL： https://twitter.com/mstk_Horiguchi/status/420759088218120192
> ふーむ。江川さんのブログが朝からにぎわっているけど判決文を読んだ方がいいと思います >同業者各位。判決は平成23年7月22日大阪地裁です。判決文によると問題とされているPSの任意性は肯定されているんですね。そして信用性判断は佐田元弁護士がいうところではないところで行われている。

　堀口弁護士のツイートが記録されていましたが、これ１つをみても内容がわかりません。判決文を読んだ方がいい、とありますが、今年の3月の性犯罪無罪判決が連続した問題のときも、なにか似たようなツイートがあったことを思い出しました。

▶（10／13） TW amneris84（Shoko Egawa） 日時： 2014-03-18 19:04:00 +0900 URL： https://twitter.com/amneris84/status/445863187699601409
> 大阪弁護士会でしむぽ「証拠は誰のものか？〜DVD提供事件を契機に「目的外使用禁止規定」を考える〜」にゃう。経過報告する佐田元弁護士 http://t.co/25RGmITXzM 

　佐田元弁護士の名前を思い出したあとも気が付かなかったのですが、この大阪弁護士会が検察の懲戒請求を不処分とした問題の肝心要は「証拠の目的外使用」でした。もうずいぶんと長い間、ネットでもTwitterでも見かけることがないので、実感が薄れていました。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-01 23:54／2014/01/08 09:13 URL： https://twitter.com/kk_hirono/status/1179046886960816130 https://twitter.com/hirono_hideki/status/420709816924127232
> 代理人の一人で、刑事弁護のプロとして名高い後藤貞人弁護士は、次のように熱く佐田元弁護士を弁護した。 http://t.co/1sg9ZoB46e
▶▶▶　　　　　End　　　　　▶▶▶

　自分の書いたものに間違いはないと思いますが、すっかり忘れていたもので、同じ大阪の弁護士ではあったと思いますが、佐田元弁護士と後藤貞人弁護士が一緒に出てきて、ちょっと驚きました。高野隆弁護士と並んで刑事弁護の神様のような評価を受けていた弁護士であります。

　後藤貞人弁護士の名前もすっかり見かけないので忘れかけていましたが、忘れてはいないものの高野隆弁護士や弘中惇一郎弁護士の名前も見かけることがなくなっていて、時折思い出しながらも調べるようなことはしていませんでした。

　テレビのニュースzeroに、ブログが国会図書館に保存されたとありました。時刻は23時59分でした。

[link:] » ブログ 国会図書館 - Google 検索 https://t.co/AgrdrihvmK

[link:] » 小林麻央さんなど42人のAmebaブログ、国会図書館が保存　「後世に伝える意義が大きい」 - ITmedia NEWS https://t.co/q0wtUOaeeo

```
ネット上の情報は更新・改廃がされやすく、Webサイト自体が消滅してしまう可能性もあり、17年には小林さん、近藤さんのブログが「後世の研究者、一般社会のために貴重な記録」として、米スタンフォード大学東アジア図書館のWebアーカイブコレクションに保存されていた。

　サイバーエージェントは「ブログはネットで書く日記のような役割を担っていたが、最近では発信される内容が多岐にわたり、テレビやメディアでの報道の情報源になったり、コンテンツとしてドラマ化や書籍化されたりするなど、ブログがきっかけで世の中の注目を集める話題が生まれることも多く見受けられる」と説明。ブログを保存する取り組みは「後世の人類や研究者にとって、貴重な資料になることが予測される」としている。

［source：］小林麻央さんなど42人のAmebaブログ、国会図書館が保存　「後世に伝える意義が大きい」 - ITmedia NEWS https://www.itmedia.co.jp/news/articles/1910/01/news104.html
```

[link:] » 「Ameba」42人のブログ、国立国会図書館に保存　市川海老蔵、小林麻央さん、近藤麻理恵ら | ORICON NEWS https://t.co/MdxjICXuh5

　上記のページには「■保存ブログ一覧（※あいうえお順）」とありますが、見たことのない名前やペンネームがほとんどです。弁護士と思われるものはありません。

　ジャーナリストの江川紹子氏の佐田元弁護士に関する記事こそ、歴史的な保存価値があると考えていたタイミングで、ニュースzeroの放送があったので、さらに意義深く感じました。

[link:] » 「品位」を問われるべきはどちらか～証拠の「目的外使用」で弁護士会の審尋開かれる(江川紹子) - 個人 - Yahoo!ニュース https://t.co/Co4Ntx9qDe

　Yahooといえば、比較的最近Yahooブログのサービスが廃止になっていたと思いますが、このYahooニュース個人というのもずいぶん久しぶりに見たように思います。Yahooニュースは記事がリンク切れになるのも早いですが、最近はそのリンク自体も見かけていない気がします。

　佐田元弁護士の証拠の目的外使用の件は、NHKの放送のことでも問題となっていましたが、延期の上で放送はされたように思います。ただ、自分が放送をみたかどうかは記憶にありません。佐田元弁護士をテレビで見た記憶はないので、見ていないような気はします。

　「佐田元弁護士は、自宅での兄弟げんかの際に弟が死亡した事件で、傷害致死で起訴された兄Aさんの弁護を担当。Aさんに弟の命を奪うような故意はなく、事件は不幸な事故だった、と無罪を主張した。」とありますが、それに近い時期、能登町小木でも似たような事件がありました。

　ジャーナリストの江川紹子氏の記事は2014年1月7日という記載がありますが、本文に傷害致死事件の発生時期は出ていないようです。

　石川県でも姉が粗暴な弟を刺殺したという事件があって、弁護士らがずいぶんと熱心に姉の弁護をしていると報道がありましたが、死人に口なしともいえる被害者の名誉が必要以上に傷つけられているのではないかと疑問に思ったこともありました。弁護士らに軽薄さを感じてのことです。

　この姉の刺殺事件も数年後に思うところがあって調べたのですが、テレビの報道などで白山市の山に近い辺りの住宅地と想像していたものが、実際は比較的海に近い辺りで、白山市ではなかったかもしれません。まず金沢市内ではなかったと思います。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-02 00:25／2011/01/20 10:53 URL： https://twitter.com/kk_hirono/status/1179054821610946561 https://twitter.com/hirono_hideki/status/27906612995825664
> [刑事弁護]昨夜23時頃になって、北陸中日新聞の記事を読みました。新聞に出ていた飯盛和彦弁護士のコメントは出ていないようです。 / 能美の弟刺殺：姉に懲役３年、執行猶予５年　裁判員ら、悩みに悩んだ判決　／石川 - 毎日ｊｐ(毎日新聞) http://htn.to/jiiF18
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「姉 弟 刺殺」の検索結果 - Twilog https://t.co/gwS3HTCr9K

　Twilogでの検索結果は1件のみでしたが、判決を伝えるニュースのツイートは2011年1月20日となっています。事件自体が自分の記憶の感覚よりはいくらか古いものとなっていました。リンクの毎日新聞の記事もリンク切れとなっています。

　能美とあるので能美市なのでしょう。以前は能美郡でしたが2011年であれば能美市になっていたはずかと思います。能美と記事あって、日本語の変換も同様にありますが、能登の能に美川の美の二文字なのだとあらためて気が付きました。そういえばという気もしましたが、珍しく感じました。

[link:] » 能美市 - Google マップ https://t.co/H4PFvDtEIA

　Googleマップで確認しましたが、やはり美川は能美市ではなく現在は白山市となっています。1,2年ほど前に美川が能美ではなかったと知って少し驚いたのですが、以前は野々市町と同じ石川郡だったようです。石川郡というのは白山麗のイメージが強く、海沿いは意外でした。

　たしか野々市町以外の石川郡と松任市が合併して白山市になったということだったと思います。野々市町は野々市市となっていますが、新しい市町村としては最近のことで、2011年だと野々市市にはなっていなかったように思います。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hokuriku_mai（毎日新聞北陸総局） 日時：2019-10-02 00:41／2011/01/18 17:16 URL： https://twitter.com/kk_hirono/status/1179058743448760320 https://twitter.com/hokuriku_mai/status/27278184584060928
> 能美市の弟刺殺事件で、水上三奈子被告(34)に対し、懲役３年、執行猶予５年(求刑・懲役７年)の有罪判決。 #ishikawa
▶▶▶　　　　　End　　　　　▶▶▶

　前に見ているはずと思いますが、懲役7年の求刑が執行猶予付きの懲役3年になったようです。大きく事実関係が争点となった事件ではなかったように思いますが、検察の求刑を基準にしてこれだけの減刑となったのは、全国的にも珍しく、弁護士らの大活躍にも映ります。

　改めて事件の現場の住所地で調べると、近くに能美根上というインターがあるらしいと気が付きました。そのインターのすぐ側に、積水樹脂石川工場とありますが、金沢市場輸送で一時期、何度か仙台まで梱包用のバンドを巻き付けたような荷物を運んだことがありました。

　荷物の見た目は、同じく紙で包むように梱包された七輪にも似ていたので、余計に強く印象に残っています。雑貨の定期便でも同じ荷物があったように思います。仙台での卸先は、給油するガソリンスタンドの近くであったとも思います。仙台市内での給油は1箇所だけでした。

　能美市の弟刺殺事件と同じ時だったと思いますが、もっと前の事件になっていて少ししか報道を見ていなかった事件になりますが、露天商による縁日での無差別殺傷事件についても調べたと記憶にあります。

[link:] » 石川県　露天商　殺人 - Google 検索 https://t.co/SOG8bQ9pqJ

[link:] » 石川県白山市の秋祭りで襲撃事件、7人死傷 - ウィキニュース https://t.co/I7duXzFLvz

[link:] » 祭りの露天商、カマで切りつけ１人死亡６人けが…石川・白山 (あんしんあんぜんトピックス) https://t.co/r0aU0n2oXr

　こちらは2008年9月13日に発生した事件のようです。テレビのニュース報道を少し見た程度だったと思います。現場の映像や写真も出ていたのかもしれないですが、そういうことは一切記憶に残っていません。

　「境内には事件当時、約３０人がいたという。桑島神社は、北陸鉄道石川線の 四十万 ( しじま ) 駅の西約１・５キロの住宅街。」と上記の記事にありますが、四十万は金沢市内になると思いますので、金沢市にかなり近いところと思われます。

　桑島神社の場所も以前、Googleマップで調べたことがありました。他にテレビ番組で、この白山市の桑島という地区は、手取川ダムのダム工事で湖底に沈んだ村の人が、移り住んだという話を見たように思います。

```
新井被告は２００８年、白山市鶴来桑島町の秋祭り会場で、１人を殺害、６人に重軽傷を負わせ、
金沢地裁は３月、懲役３０年の実刑を言い渡した。
判決では「新井被告が心神こう弱状態だった」とする弁護側の主張を認めたが、
検察側はこの認定を「覆すのは難しい」として控訴しなかった。
一方、新井被告本人も控訴期限となる７日までに手続きを行っておらず、
懲役３０年の実刑判決が確定した。

［source：］【石川】白山の無差別殺傷事件、新井敏明被告に懲役３０年の実刑確定 https://toki.5ch.net/test/read.cgi/dqnplus/1302270276/
```

　この懲役30年という判決も前に見ている可能性がありますが、第一印象でずいぶん重いと感じました。弁護士が心神耗弱などと主張していたらしいことは記憶にあったのですが、その弁護側の主張を認めた上での懲役30年のようです。

　懲役30年というのは、刑法の改正後に有期懲役刑の上限になったように思います。少なくとも懲役30年を超える有期懲役刑というのは見たことがありません。その上となると無期懲役刑の選択になりそうに思います。

　被疑者の顔写真も見た記憶がないので、文字情報以上のイメージもわかないのですが、2011年4月の時点で45歳とあります。8年前となるので現在は53歳ぐらいになりそうですが、ほぼ私と同年代、少し年下だったのだと今回気が付きました。

　露天商として子供向けの玩具を売っていたような情報もさきほど見かけました。今回は情報としてみかけていませんが、からかわれたとあるのも、幻聴や被害妄想の可能性があると前に調べたときに見ていました。判決でも弁護士の主張として心神耗弱が認められたとのことです。

　1人が死亡した無差別的な殺傷事件ですが、心神耗弱が認められた上での懲役30年という判決も、前例がなさそうな気がしました。そもそも心神耗弱が認められるのは相当ハードルが高かったと思いますし、認めた場合は医療や治療を優先した措置であるように思います。

　神坂尚裁判長が判決を言い渡したらしいと他の記事に情報がありました。名前は見覚えのある金沢地方裁判所の裁判長ですが、テレビで顔を見たという記憶は残っていない裁判官です。神坂という地名が金沢市の鳴和の近くにあったような気がしますし、当時もそう考えたように思います。

　あるいは同じ金沢市内で鳴和の近くでも、神谷内と小坂町が合体したイメージだったのかもしれません。どちらも金沢地方裁判所の前から森本に通じる広い国道で、交差点にその地名がありました。神谷内の方は少し違っていたかもしれません。

[link:] » 小坂町 - Google マップ https://t.co/LtLZ1LE4J6

[link:] » 神谷内町 - Google マップ https://t.co/W3EaBquRjl

　意外なことに金沢市の小坂町と神谷内町は隣接しているようです。国道359号線となっていますが、国道159号線が離れた場所に新しい道路としてあるので、旧の159号線になるものと思います。

　Googleマップで取り消し線のようなものを見たのは初めてですが、やはり金沢市に神坂という地名は存在しないようです。

[link:] » 原発を止めた裁判官 / 井戸謙一/神坂さんの任官拒否を考える市民の会 - 紀伊國屋書店ウェブストア https://t.co/H41naBx1om


　神坂という2011年4月当時の金沢地方裁判所の裁判長の顔を見ておきたいと調べたところ、井戸謙一弁護士の名前が一緒に出てきたので驚きました。井戸謙一弁護士の方は、名古屋高裁金沢支部の裁判長ではなかったかと思います。滋賀の再審事件を現実のものとして弁護士です。

[link:] » 神坂氏任官拒否訴訟判決が指し示す司法制度改革の行方 https://t.co/QoqwKYZFbY

　どうも神坂氏というのは元金沢地方裁判所の裁判長で懲役30年の判決を出した人物とは別人のようです。同じ金沢の裁判所で裁判官をしていた井戸謙一弁護士の名前と一緒に本のサブタイトルのようなものがあったので、早とちりをしたようです。

```
被告は一貫して事件への関与を否認。弁護側は、被告が事件の夜は別の男性らと会っていたとして無罪を主張していた。神坂裁判長は「被告の供述は、あまりにも不自然で到底信用できない」と退け、「犯した罪から目を背け続け、反省の態度は見られない。残りの人生のすべてで罪を償わせるのが相当」とした。

［source：］NHK元委託カメラマンに無期懲役　主婦強盗殺人で金沢地裁　　：日本経済新聞 https://www.nikkei.com/article/DGXNASDG02029_S2A300C1CC1000/
```

　2012年3月2日付の記事となっていますが、この大きく報道されていたNHK元委託カメラマンの主婦殺害事件も神坂尚裁判長が無期懲役の判決を出していたようです。「残りの人生のすべてで罪を償わせるのが相当」というのも他に見たことのない厳しい断罪です。

　このNHK元委託カメラマンの主婦殺害事件も異様さが印象に残るもので、自分の後頭部を何かで刺したとかで逮捕前に自殺未遂を図り、逮捕されたときは車椅子に乗った状態の映像が出ていたのですが、正気とは思えない様子でした。

　数年前、同じ石川県内ニュースでも大きなニュースではなかったですが、石川県警察本部の警部補が、仕事に行きたくないという理由で、自分のお腹を刃物で突き刺し、強盗被害の狂言だったというニュースがありました。どちらも短い報道内容で不可解さは残りました。

```
福田さんは6日夜、家族に「（若生容疑者に）お金を返してもらいに行く」と言い残して外出したまま行方が分からなくなった。家族からの捜索願を受け、県警が若生容疑者から任意で事情聴取。同容疑者は翌日の18日、金沢市の実家で刃物で後頭部を刺して自殺を図り、入院していた。〔共同〕

［source：］金沢主婦遺体、カメラマン逮捕　死体遺棄容疑　　：日本経済新聞 https://www.nikkei.com/article/DGXNASDG2802M_Y1A220C1CC1000/
```

```
［読売新聞］2007年6月2日　（11：59）
　
　金沢市鞍月で先月２３日、石川県警警備課の向出智之警部補（４４）が自室玄関で腹にナイフが刺さった状態で見つかった事件で、県警の調べに対し、向出警部補が自分で腹を刺したと話していることが２日、わかった。
　「能登半島地震で仕事が忙しく疲労がたまったため、仕事に行きたくなかった」
　と供述しているといい、県警は「男に襲われた」とする警部補の説明が作り話だったとして、軽犯罪法違反（虚偽申告）の疑いで追及している。

［source：］石川警部補刺傷事件「仕事に行きたくなかった」（自作自演の人々） - お寺さんぽ　Ｖｅｒ．０３ https://blog.goo.ne.jp/hideru_a/e/5a4d022643efdcadbbfff077b512f5f8
```

　腹にナイフが刺さった状態で見つかったとありますが、これは忘れていました。それも出勤が遅いと訪ねてきた同僚に発見されたとのことです。約2週間の怪我とあるので大事はなかったのかもしれないですが、自分で救急車も呼ばずに痛いのを我慢していたのかと不思議な事件です。

　同じ頃の事件として記憶にあるのですが、現職の志賀町町長が石川県警察本部の取り調べを受け、その厳しさを苦に自殺未遂をしたというニュースがあって、金沢か富山の大学教授が警察を批判する抗議をしていたというのも印象的でした。

```
2月19日15時24分配信 毎日新聞

　石川県志賀町の細川義雄町長（７３）が１８日未明に同町の自宅で睡眠薬を飲んで自殺を図り、病院に運ばれていたことが１９日、分かった。命に別条はなく、意識もあるという。細川町長は前日、県警から同町発注工事の談合事件で任意の事情聴取を受けており、助役あての遺書で潔白を主張していたという。

［source：］＜自殺未遂＞石川・志賀町長が自宅で　談合聴取を苦に？ ： デラシネ日乗 https://deracine69.exblog.jp/4642915/
```

　こちらも調べてみると、あっさり情報がみつかりました。記事の日付が2007年2月19日となっています。自宅で睡眠薬というのは記憶にありませんでした。最近は睡眠薬の服用での自殺というのは聞かないのですが、以前は少なからずあったような気がしないではありません。

```
2007年02月19日 12：49
めちゃ！大変!!
今朝の北国新聞一面トップに掲載されちゃいましたぁ～

談合問題でかなり警察からの取り締まりがきつかったのかしら。。。
マスコミが殺到し、志賀町は今大変な状態らしいです(＞＜)

［source：］［mixi］志賀町町長自殺未遂??? - 志賀町 | mixiコミュニティ https://mixi.jp/view_bbs.pl?comm_id=207903&id=15462632
```

　2007年の2月19日に、どの派遣の仕事をしていたかはすぐに思い出せないですが、志賀町の隣の羽咋市のアパートに住んでいたのははっきりしています。あるいはちょうど派遣の仕事が切れて宇出津の自宅に戻っていた時期かもしれません。

　そうだとすれば、前年の12月の下旬にインドネシアで大津波がありました。志賀町の電子部品の工場でインドネシア人の若者と一緒に仕事をしていたので、当時のことはよく憶えています。

```
2004年スマトラ島沖地震（スマトラとうおきじしん）は、2004年12月26日、インドネシア西部時間7時58分53秒（UTC0時58分）にインドネシア西部、スマトラ島北西沖のインド洋で発生したマグニチュード9.1［1］の地震である。単に「スマトラ島沖地震」といった場合、この地震を指すことが多々ある。

［source：］スマトラ島沖地震 (2004年) - Wikipedia https://ja.wikipedia.org/wiki/%E3%82%B9%E3%83%9E%E3%83%88%E3%83%A9%E5%B3%B6%E6%B2%96%E5%9C%B0%E9%9C%87_(2004%E5%B9%B4)
```

　インドネシアの大津波は2004年の12月でした。二ヶ月ちょっと派遣の仕事が切れて、2月に入ってから羽咋市の鋳物工場が派遣先となりました。社員になることをすすめられた時期もあったのですが、一時、派遣を切られて、七尾市の派遣先に行ってから戻った時期もありました。

　あとで知ったのですが、派遣の契約で正社員にしないためのそういうことがあるとテレビで知りました。本当のところは聞いても教えてもらえることはなかったと思いますが、モトケンこと矢部善朗弁護士（京都弁護士会）のブログのことが悪影響していると考えた時期もありました。

　七尾市の派遣先に通ったのは2,3週間だったと思います。そちらも1月か2月の冬の時期だったような気がするのですが、七尾市への通勤に雪道を走ったという記憶はないので、春先だったような気もします。今はこういう時期も特定しづらくなっています。

　七尾市と言っても、羽咋市から向かうと七尾市内の入り口のようなところでした。周りの風景というのもけっこう記憶には残っているのですが、はっきりした場所はおぼえておらず、仕事の内容というのも漠然としたものとしか思い出せなくなっています。

　もう一つ時期を確認しておきたいことがあります。これまでに何度か調べているのですが、内容は憶えているものの、時期というのが特定しづらく、すぐに忘れるようです。

[link:] » 押野　弁護士　自殺 - Google 検索 https://t.co/RvhdDDDTaY

```
石川県内の弁護士でつくる金沢弁護士会は２日、依頼を受けた案件２件を放置し、着手金計約２３０万円の速やかな返還を怠ったとして、同会所属の押野毅（たけし）弁護士（５７）を１日付で業務停止２か月の懲戒処分としたと発表した。

　押野弁護士は１日夜、金沢市の自宅で首をつって死亡しているのが見つかり、県警が自殺とみて調べている。

［source：］弁護士が自殺か…着手金返還怠り、業務停止処分 - 医療裁判傍聴記 https://blog.goo.ne.jp/katuo_rakkasei/e/a9fb3ae23b55154a8a2a3760317ddcf8
```

　記事の日付は2015年9月2日となっています。よく見ると記事の下の部分に「2015年09月02日21時18分　読売新聞」というのが確認できました。確定的とは思いませんが2015年9月の初めに間違いはなさそうです。思ったよりずいぶん最近こと、というのが第一印象でした。

　2015年というのは、個人的に最近のこととして思えるのですが、よく考えると9月ということで4年ちょっと前になります。4年前として考えるとけっこうな事件の経過を感じます。それでも2007年や2011年と比較すれば、やはり最近のことになるかとは思います。

　この金沢弁護士会の自殺した押野毅弁護士については、なにかで名前だけは記憶にありました。金沢市の野々市町の近くには押野という地名があったので、覚えやすい名前でもありました。死亡時の年齢が57歳とありますが、40代の弁護士として認識をしてきたように思います。

　たしか懲戒事由となった弁済を済ませた上での自殺であったとも思います。他に理由や動機があったように思えるのは、さきほどの石川県警察の警部補の狂言事件とも共通しています。将来をはかなんだうえでの自殺だった可能性もありますが、報道のことしか知りようはないです。

　「依頼を受けた案件２件を放置し、着手金計約２３０万円の速やかな返還を怠ったとして、同会所属の押野毅（たけし）弁護士（５７）を１日付で業務停止２か月の懲戒処分としたと発表した。」という内容ですが、これもほとんど記憶には残っていませんでした。

　前に見てきたのは別の記事やニュースだったと思いますが、2件の放置で着手金230万円の返還を怠ったとあります。この事件放置で判決文の偽造までやらかす弁護士が、これまでに何人かいたのですが、自殺したという話はありません。

　同じ石川県でももっとすごいことをやって懲戒処分になった弁護士がいたのですが、転落は人権活動に熱心に取り組みすぎたという情報も見かけました。金沢市ではなく小松市の弁護士です。

[link:] » 小松市　弁護士　懲戒 - Google 検索 https://t.co/Afznu7nB8H

　上記の検索方法で情報はみつかりませんでした。小松市と地域を指定してあるのでヒントぐらいは見つかるだろうと見込んだのですが、かすりもしませんでした。

[link:] » 小松市　金沢弁護士会　懲戒 - Google 検索 https://t.co/aRoY8hYV9k

　検索結果はさらに減って1ページでおさまっています。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「小松 弁護士」の検索結果 - Twilog https://t.co/GEzDN8ydy2


　上記のTwilogでの検索結果も1ページにおさまっていますが、手掛かりすらつかめませんでした。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-02 03:29／2013/04/11 01:09 URL： https://twitter.com/kk_hirono/status/1179101116702703616 https://twitter.com/hirono_hideki/status/322018543191347201
> （引用→）ここまでやっても2年。除名や退会命令は出さなかった金沢弁護士会  もし山口弁護士の逮捕が先なら弁護士会はダンマリになる 刑事被告人となり有罪となれば自動的に弁護士資格はく奪 弁護士会は懲戒処分なんかしなくてもよい http://t.co/XmLrSKD75D
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「金沢弁護士会 懲戒」の検索結果 - Twilog https://t.co/WITvLusK48

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-02 03:32／2018/02/15 17:16 URL： https://twitter.com/kk_hirono/status/1179101719327735808 https://twitter.com/hirono_hideki/status/964050853085642752
> 山口民雄弁護士（金沢）3回目の懲戒は業務停止2年！ ( 事件 ) - 弁護士自治を考える会 - Yahoo!ブログ https://t.co/RPBFcIUyCM
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-02 03:31／2010/11/17 21:01 URL： https://twitter.com/kk_hirono/status/1179101616823160832 https://twitter.com/hirono_hideki/status/4866660544548864
> [弁護士]山口で検索入れてみました。この説明はどうかと思いました。→　処分理由の要旨	 仕事受任し放置虚偽報告　多数 / 弁護士懲戒処分情報データベース http://htn.to/29NuXP
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「山口 懲戒」の検索結果 - Twilog https://t.co/YAHsUZ5E39

　ここまで調べるのに難儀しましたが、山口民雄弁護士が探していた弁護士名になるかと思います。これでどういう結果が出るのかGoogleで検索してみます。

[link:] » 金沢弁護士会　山口民雄 - Google 検索 https://t.co/UALGD5fb2H

[link:] » [B!] 山口民雄弁護士（金沢）3回目の懲戒は業務停止2年！ ( 事件 ) - 弁護士自治を考える会 - Yahoo!ブログ https://t.co/JHCiAFPN6Y

[link:] » 人権派「山口民雄元弁護士」横領で懲役３年６ヵ月の実刑判決: NEWS RAGTAG | 告発-金沢地方検察庁御中_2013 https://t.co/R4J1pySAQM

```
金沢弁護士会に所属していた'06年、管理を依頼されていた1300万円の生命保険金を着服したとして業務上横領罪などに問われた山口民雄元弁護士（40歳）に、きょう金沢地裁は懲役３年６ヵ月（求刑懲役４年）の実刑判決を言い渡した。

福井の元弁護士に実刑判決　依頼人の１３００万円横領　〔共同通信〕

山口元弁護士は若手の人権派として知られていたが、'09年には虚偽説明をして依頼人から80万円を受け取ったとして、金沢弁護士会から業務停止２年の懲戒処分を受けるとともに、同問題で金沢地検に詐欺の疑いで刑事告発されていた。

弁護士の金銭トラブルでは、きのう愛知県弁護士会が同会所属の森下敦夫弁護士（63歳）が、約6586万円を着服したとする事由の懲戒請求があったことを発表している。処分が決定する前に、弁護士会が懲戒請求の内容を公表するのは異例だ。また、この件では森下弁護士を選任した名古屋家裁が、業務上横領の疑いで刑事告発することを検討しているという。

＜懲戒請求＞弁護士６５８６万円着服　地位悪用し　愛知　〔毎日新聞〕

弁護士に非行があれば、自浄作用に期待できない弁護士会の自治に処罰をゆだねず、積極的に刑事告発していくべきだ。

［source：］人権派「山口民雄元弁護士」横領で懲役３年６ヵ月の実刑判決： NEWS RAGTAG http://news-tag.cocolog-nifty.com/blog/2010/03/post-6298.html
```

　山口民雄弁護士が刑事事件で実刑判決を受けていたというのもすっかり記憶がなかったのですが、1300万円の着服で懲役3年6月（求刑4年）というのは、ずいぶんと量刑が重く感じました。

```
1 ： ◆SCHearTCPU ＠胸のときめき▲φ ★：2009/12/07(月) 22：41：07 ID：???0 ?PLT(12556)
石川県の男性らから請け負っていた相続事案で生命保険金１３００万円を横領したとして、
金沢地検は７日、業務上横領容疑で、元弁護士山口民雄容疑者（３９）＝福井県勝山市、
業務上横領罪などで起訴＝を再逮捕した。地検によると、容疑を認めているという。

逮捕容疑は２００６年８月、男性が相続した生命保険金の一部、１３００万円を
着服し、自分の業務に関する支払いに充てるため、別の口座に送金した疑い。

［source：］【社会】保険金１３００万円を横領…元弁護士を再逮捕 － 金沢地検 https://tsushima.5ch.net/test/read.cgi/newsplus/1260193267/-100
```

```
講演録
「有事法制、国民保護法と憲法」
講師 ： 山口民雄　弁護士

［source：］「有事法制、国民保護法と憲法」 | 石川県平和運動センター https://i-peace-ishikawa.com/%E3%80%8C%E6%9C%89%E4%BA%8B%E6%B3%95%E5%88%B6%E3%80%81%E5%9B%BD%E6%B0%91%E4%BF%9D%E8%AD%B7%E6%B3%95%E3%81%A8%E6%86%B2%E6%B3%95%E3%80%8D/
```

```
この他、石川県では片町という繁華街で防犯カメラが据え付けられています。他の県でも同じようになっているのではないかと思いますが、必要以上に自分たちの生活を監視するような動きがあります。これが表向きは、たとえば不審者が出るからこどもの学校の送り迎えをしなければならないとか、いまの日本の治安は決して芳しくない、とにかく危ない、だからいろんな工夫をして自分たちの身の安全を守らなければならない、そんな理由で住民側からむしろ積極的に進めていくべきだというトーンで語られています。
安心して暮らせる社会といえば響きはいいですが、見方を変えればお互いがお互いを監視する社会であり、大前提として人間不信を前提としてそういう体制が作られていくわけです。

［source：］「有事法制、国民保護法と憲法」 | 石川県平和運動センター https://i-peace-ishikawa.com/%E3%80%8C%E6%9C%89%E4%BA%8B%E6%B3%95%E5%88%B6%E3%80%81%E5%9B%BD%E6%B0%91%E4%BF%9D%E8%AD%B7%E6%B3%95%E3%81%A8%E6%86%B2%E6%B3%95%E3%80%8D/
```

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-10-02 03:50／2019/10/02 03:49 URL： https://twitter.com/kk_hirono/status/1179106327265570818 https://twitter.com/s_hirono/status/1179105951187472384
> 2019-10-02-034751_「有事法制、国民保護法と憲法」　｜　石川県平和運動センター.jpg https://t.co/91uRmhmERd
▶▶▶　　　　　End　　　　　▶▶▶

　講演のレジュメのような記事がずいぶん長いものとなっていましたが、掲載されたホームページには背景画像として、爆発大破した福島原発の写真があります。「石川県平和運動センター」というホームページのようです。

```
労働組合とPEACEﾈｯﾄ会員で構成し 議員 市民団体とも連携する平和団体 2000.9連帯労組会議の後継として誕生 平和憲法を活かし 反戦･平和 反核 脱原発 教育 人権など取組む 画像は改憲 戦争法 共謀罪などに反対する大衆行動 米軍のＢ52･Ｂ1戦略爆撃機 爆弾は民衆の頭上に！ 小松Ｆ15戦闘機と米軍との一体化！ 絵は抽象画の熊谷守一作品 枝葉を捨象し本質に迫る紫陽花、蟻･･ 背景は“忘れない3.11” 政府 企業 御用学者による高･低線量被ばくの実験場 許せない！ 団結して社会を変えよう！

［source：］「有事法制、国民保護法と憲法」 | 石川県平和運動センター https://i-peace-ishikawa.com/%E3%80%8C%E6%9C%89%E4%BA%8B%E6%B3%95%E5%88%B6%E3%80%81%E5%9B%BD%E6%B0%91%E4%BF%9D%E8%AD%B7%E6%B3%95%E3%81%A8%E6%86%B2%E6%B3%95%E3%80%8D/
```
```
役割･役員・構成団体・活動方針の紹介

■ 石川県平和運動センターの役割
■ 石川県平和運動センター構成団体

２０１９年度役員名簿（2018.9.26）

代　　表　　赤玉　善匡　　石川県教職員組合

代　　表　　南　  弘樹　　北陸鉄道労働組合

代　　表　　本田　良成　　全国一般石川地方労働組合

代　　表　　新明　　宏　　石川県高等学校教職員組合

事務局長　　中村　照夫　　専従（自治労･県職労ＯＢ）

運営委員　　新谷  勝春　　全農林労働組合石川分会

運営委員　　西田　　寛　　北日本観光自動車労働組合

運営委員　　高木　正宏　　ＪＲ総連石川県協議会

運営委員　　近藤　伸恵　　青年・女性部（全国一般）

運営委員　　尾崎　彰信  　金沢地区平和センター（全国一般）

運営委員　　谷口  　洋一  　七鹿地区平和センター（県教組七尾）

運営委員　　吉田　大輔  　小松能美平和センター（県教組小松）

会計監査    　森　　暢一  　石川県高等学校教職員組合

会計監査    　町端  伸幸  　北陸交通労働組合

 

［source：］石川県平和運動センターとは？ | 石川県平和運動センター https://i-peace-ishikawa.com/aboutcn/
```

```
理事長メッセージ
石川県社会法律センターが活動を続けて間もなく40年になります。設立当初、いくつかの県で社会法律センターと同じような組織ができましたが、常設機関として事務局を設置して対応しているのは全国的にも石川県だけになりました。

財政的基盤をもって長期の活動を継続してきたというのは特筆すべきことで、人的な面でも支えてもらったそれぞれの組織と組合員のおかげだと感謝しています。もう一つは弁護団の充実であり、弁護士会の約一割の弁護士が弁護団を組んで法律センターを作っているところは他に見られません。

最近は新しい事務局員の努力もあり、年々相談件数が増えていて、今では創設期をしのぐ件数になってきました。一時はあと３年で終わるかという議論のあったことがウソのようです。

４０年間続けてきて、既に定着した組織体として存続してきているという実感があります。これを継続して、さらに拡大していくことが私達の任務であり頑張りどころです。

この間の訴訟活動を振り返って、やはり志賀原発２号機の差止訴訟が出たことが大きいと思います。
安倍政権になってからも、マイナンバー訴訟を始め市役所前広場訴訟など多くの訴訟事件を抱えるようになりました。これも構成団体から様々な面での賛同を得ながらしっかりと対応していきます。

石川県社会法律センター
理事長 岩淵 正明  

［source：］理事長メッセージ – 石川県社会法律センター http://ipslawc.com/message/
```

　石川県平和運動センターのホームページにリンクがあった石川県社会法律センターですが、これは初めて見る変わった名称だと思いました。理事長という人物の顔写真がありますが、岩渕正明という名前は金沢弁護士会の弁護士として、どこかで名前を見かけているように思いました。

[link:] » 弁護士のご紹介：岩淵　正明 | 北尾法律事務所 ::: 石川県金沢市の弁護士事務所 https://t.co/KqZWMlDMMr

　出身地が富山県砺波市とあります。前に少し書いたことがあると思いますが、もう死んでしまったと聞く被告発人長谷川紘之弁護士は、その富山県砺波市辺りの有名な神社の息子だという話でした。九十九湾に夜釣りに来ていた人に聞いた話です。

　北尾法律事務所は奥村回弁護士が所属する法律事務所として、これまで何度か見かけてきたものでした。岩渕正明という名前はそのときに見かけていたようですが、石川県社会法律センターという団体の理事長であるとはまったく知らなかったと思います。

　奥村回弁護士も数年前に金沢弁護士会の会長をしていましたが、そもそもこの北尾法律事務所というのは、平成5年から平成6年頃に、北尾という弁護士の名前として何かで見かけていたような記憶があります。

```
平成30年4月1日現在

出身等	福井県坂井郡三国町（現・坂井市）生まれ
学歴	
1959（昭和34）年
福井県立三国高校卒
1962（昭和37）年
司法試験合格
1963（昭和38）年
金沢大学法文学部卒
職歴等	
1965（昭和40）年
弁護士登録
司法修習17期
1981（昭和56）年
日本弁護士連合会常務理事
金沢弁護士会会長
石川調停協会会長
金沢調停協会会長
2010（平成22）年
旭日小綬章受章
元福井県人会会長
現職	石川県都市計画審議会委員
主な取扱事件	
小松基地騒音訴訟
七尾火電訴訟
北陸トンネル列車火災刑事事件（無罪判決）
富来町大工殺人事件（一審無罪）
小松市長公職選挙法違反（経歴詐称）事件（無罪判決）
富来町長選挙無効請求事件（勝訴）

［source：］弁護士のご紹介：北尾 強也 | 北尾法律事務所 ：：： 石川県金沢市の弁護士事務所 http://www.kitaolaw.jp/lawyers-kitaok.html
```

　最上位に筆頭のような場所で名前があったものの、余り見覚えのない名前だったので、北尾という先代の弁護士の後継者ではと思っていました。今回確認したところ、昭和34年に高校卒業とあるので、現在は70代半ば過ぎの年齢ではないかと推定されます。

　弁護士の法律事務所は個人名を使う場合、2,3人の名前を並べて共同経営のようなものや、個人名をそのまま使うものがほとんどではと思います。被告発人木梨松嗣も以前は木梨松嗣法律事務所でしたが、その後は「木梨・米田法律事務所」などとなっています。

[link:] » 木梨 松嗣弁護士(木梨・米田法律事務所)に法律相談 - 石川県金沢市、北陸鉄道浅野川線 北鉄金沢駅 | Legalus https://t.co/SGRVjJkMuY

　今確認のため調べた情報ですが、いつのまにか米田となっていました。前は違う名前だったと思います。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-02 04:22／2018/12/31 11:36 URL： https://twitter.com/kk_hirono/status/1179114349777915904 https://twitter.com/hirono_hideki/status/1079566985938124800
> 木梨松嗣 弁護士(木梨・長原法律事務所) - 石川県金沢市 - 弁護士ジャパン https://t.co/tvFdgtTE7w
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「木梨 事務所」の検索結果 - Twilog https://t.co/Bvjns73w3o

　2018年12月31日のツイートとして情報が見つかりましたが、昨年の大晦日の午前11時36分に、被告発人木梨松嗣弁護士のことを調べていたようです。こういう情報も定期的に記録しておきべきかと思いました。いつ変更があるかわかりませんので。

〈〈〈：Emacs： 2019-10-02（水曜日）04：26 　〈〈〈

