#+TITLE: "「冤罪を生む「ムラ社会」の論理　法曹一元、証拠全面開示が改革のカギ」という木谷明弁護士の記事"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-09-26 13:06:48 +0900
FILE_NAME: 2019-09-26-130648_「冤罪を生む「ムラ社会」の論理　法曹一元、証拠全面開示が改革のカギ」という木谷明弁護士の記事.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: workspace,市川寛弁護士,深澤諭史弁護士,木谷明弁護士,今市小１女児殺害事件,栃木小１女児殺害事件,大崎事件
記事タイトル名の文字数：46　保存ファイル名の文字数：68
#+STARTUP: showeverything

* 「冤罪を生む「ムラ社会」の論理　法曹一元、証拠全面開示が改革のカギ」という木谷明弁護士の記事
  :LOGBOOK:
  CLOCK: [2019-09-27 金 13:38]--[2019-09-27 金 13:42] =>  0:04
  CLOCK: [2019-09-26 木 13:10]--[2019-09-26 木 13:12] =>  0:02
  :END:

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 市川寛弁護士,深澤諭史弁護士,木谷明弁護士,今市小１女児殺害事件,栃木小１女児殺害事件,大崎事件

〉〉〉：Emacs： 2019-09-26（木曜日）13：10　 〉〉〉

　深澤諭史弁護士のタイムラインで、市川寛弁護士のツイートのリツイートとして見かけたものです。かなり長文の記事で読むのもそれなりに時間がかかりました。

〈〈〈：Emacs： 2019-09-26（木曜日）13：12 　〈〈〈

〉〉〉　：Ａｔｏｍ： 2019-09-27 10:56 　〉〉〉

　気になるところがあって、Emacsでいろいろやっていたのですが、使い勝手に満足ができず、Ａｔｏｍエディタに編集環境を変更しました。それもいろいろとトラブルが多く、ようやく設定もうまくいって落ち着いたところです。

　予定よりほぼ一日遅れになるかと思いますが、昨日記録したスクリーンショットからご紹介したいと思います。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-27 11:28／2019/09/26 18:42 URL： https://twitter.com/kk_hirono/status/1177409707037745152 https://twitter.com/s_hirono/status/1177156447701876736
> 2019-09-26-120459_書面審理だけしかしない最高裁の５人の裁判官が、あたかも自分たちが神様にでもなったような感じで、ろくな理由づけもしないまま、１・２審の決定は誤.jpg https://t.co/hhbYl91HTD
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-27 11:28／2019/09/26 18:42 URL： https://twitter.com/kk_hirono/status/1177409678273175553 https://twitter.com/s_hirono/status/1177156375522107392
> 2019-09-26-113654_「ムラ社会の生贄」.jpg https://t.co/9QQSUakxqz
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-27 11:28／2019/09/26 18:41 URL： https://twitter.com/kk_hirono/status/1177409659268820992 https://twitter.com/s_hirono/status/1177156303749148672
> 2019-09-26-113622_エコノミストOnline：刑事司法対談（拡大版）　周防正行×木谷明　冤罪を生む「ムラ社会」の論理　法曹一元、証拠全面開示が改革のカギ　｜　週刊エコノミスト.jpg https://t.co/ymeQFM5QeL
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-27 11:28／2019/09/26 18:41 URL： https://twitter.com/kk_hirono/status/1177409631783542784 https://twitter.com/s_hirono/status/1177156231691063296
> 2019-09-26-112823_エコノミストOnline：刑事司法対談（拡大版）　周防正行×木谷明　冤罪を生む「ムラ社会」の論理　法曹一元、証拠全面開示が改革のカギ　｜　週刊エコノミスト.jpg https://t.co/DzauuXGZFO
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-27 11:28／2019/09/26 18:40 URL： https://twitter.com/kk_hirono/status/1177409569011580928 https://twitter.com/s_hirono/status/1177156015936000001
> 2019-09-26-111412_深澤諭史さんがリツイート弁護士市川寛@imarockcaster42·17h冤罪を生む「ムラ社会」の論理　法曹一元、証拠全面開示が改革のカギOnline.jpg https://t.co/khfFhKxgTQ
▶▶▶　　　　　End　　　　　▶▶▶

　次に奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)での記録の方も見ておきたいと思います。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-09-27 12:02／2019/09/26 12:52 URL： https://twitter.com/kk_hirono/status/1177418160175140864 https://twitter.com/hirono_hideki/status/1177068407952269313
> 2019年09月26日11時13分の登録： ＼弁護士 市川 寛　@imarockcaster42＼冤罪を生む「ムラ社会」の論理　法曹一元、証拠全面開示が改革のカギ  Online  https://t.co/H6Pfidac1R
▶▶▶　　　　　End　　　　　▶▶▶

　ざっとみたので見落としがあったかもしれないですが、関連したツイートは、市川寛弁護士のまとめ記事のみでした。パソコンの設定がうまくいかなかったりしてバタバタとしていたのですが、やっていると思っていたことをやっていなかったというのは、ちょいちょいあることです。

[link:] » エコノミストOnline：刑事司法対談（拡大版)　周防正行×木谷明　冤罪を生む「ムラ社会」の論理　法曹一元、証拠全面開示が改革のカギ | 週刊エコノミスト Online https:
//t.co/cYIJbTR9kw

￼ エコノミストOnlineというのはニュースサイトかと思いますが、昨日最初に見たときに、余り見かけないと感じました。引用をしようと思ったのですが、javascriptの操作を無効化する設定がなされているのかもしれず、いつもの方法で取得が出来ませんでした。

　いろいろと思うところのあった記事ですが、javascriptで引用コピーができないのは残念です。パソコンの環境が変わってから余りやっていなかったのですが、TwitterＡＰＩの検索からまとめ記事を作成するコマンドをやっておこうと思います。繰り返しますが精度はよくないです。

2019年09月27日12時32分の実行記録 \n twitterAPI-search-lawList-mydql-add.rb "冤罪を生む「ムラ社会」の論理" \n ツイート数：9/1513 リツイート数：12/1513 トータル：149… https://t.co/KU3IB8DHG2

```
アカウント名	ツイート数	リツイート数
伊藤和子 #なぜそれが無罪なのか？！（ディスカヴァー携書）発売中（KazukoIto_Law）	1	0
Kenji Takeuchi（KPf_M）	1	0
MIDORI Daisuke（midoridisc）	0	1
弁護士 中原潤一（lawyernakahara）	1	0
仏樹房 東蝕（qnOsaZLBGyht6vJ）	0	1
弁護士 市川 寛（imarockcaster42）	1	0
なかじ（h_nakaji）	0	1
カール=レーフラー（hirohika777）	0	1
中村元弥（1961kumachin）	0	1
浜ちゃん（lawer_hamachan）	0	1
リーチ一発ツモ裏１（luckymangan）	0	1
惇兄（tongu）	0	1
芳賀淳（jjjhaga）	1	0
toujin（tou_jin）	0	1
黒田法律事務所 弁護士黒田厚志（kurodalawoffice）	0	1
奉納＼さらば弁護士鉄道・泥棒神社の物語（hirono_hideki）	1	0
arima（arima_yukimi）	0	1
非常上告-最高検察庁御中_ツイッター（s_hirono）	3	0


［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”冤罪を生む「ムラ社会」の論理”／データベース登録済みツイート：2019年09月27日12時35分の記録：ユーザ・投稿：18／20件 http://hirono2014sk.blogspot.com/2019/09/regexp2019092712351820.html
```

　どうもあるはずの市川寛弁護士のツイートの深澤諭史弁護士のリツイートが見当たらないようです。ここは大事なところでもあるので、直接、探して記録をしておきます。

RT fukazawas（深澤諭史）｜imarockcaster42（弁護士 市川 寛） 日時：2019-09-26 10:42／2019-09-25 17:57 URL： https://twitter.com/fukazawas/status/1177035708998901760 https://twitter.com/imarockcaster42/status/1176782823681773568

　なぜだかjavascriptでの引用コピーができないので、社会的に考えさせられ気になる部分をピックアップでツイートしておきたいと思います。

「郵便不正事件」で逮捕された元厚生労働省局長の村木厚子さんは164日間、オリンパス粉飾決算事件で有罪となった元野村証券社員の横尾宣政さんに至っては実に966日間勾留された。 https://t.co/cYIJbTR9kw

木谷　しかし、郵便不正事件で証拠を捏造した検事をかばったとして逮捕・勾留された大阪地検の大坪弘道・元特捜部長は、著書『勾留百二十日』で、「これを人質司法と言う」とはっきりと認めている。否認する被疑者をいつまでも閉じ込めておいて、簡… https://t.co/RN62ZGnjkL

周防　特別部会に出席していた裁判官は、長期間の勾留で人の自由を奪うことに対する想像力がゼロだった。村木さんの長期勾留について、休み時間に一人の裁判官に詰め寄ったが、「今思えば、無罪だったから、あなたは行き過ぎだというかもしれないが… https://t.co/R7j2Y38KNS

周防　特信状況は、映画製作のための取材開始直後に知った「悪魔の法律」だ。例えば、自分が事件の主犯だが、取り調べの時に、「彼がやりました」と他人に罪をなすりつけたとする。その後、後悔の念から、本当は自分が主導しましたと法廷で証言して… https://t.co/LM0bFvuNPU

――　海外の弁護士などから、日本の刑事司法には、「Due Process of Law（適法手続き）がない」との批判さえある。なぜ、憲法や刑事訴訟法を逸脱するような捜査を警察や検察が行い、裁判所がそれをチェックすることができないの… https://t.co/lcMdRcuDaB

周防　この問題は法律論ではなくて、日本の「ムラ社会性」に起因すると思う。誰かを「犯人だ」と決めないと、社会秩序を保てない。真犯人かどうかは関係なく、その後のムラ社会の秩序を保つために、被疑者をまるで生贄のように捧げている。そうした… https://t.co/DmyllXHusm

[link:] » エコノミストOnline：刑事司法対談（拡大版)　周防正行×木谷明　冤罪を生む「ムラ社会」の論理　法曹一元、証拠全面開示が改革のカギ | 週刊エコノミスト　木谷　警察は検事を馬鹿にする。検事は裁判所を馬鹿にする。だから、警察が… https://t.co/YHgbz1XZ5F

[link:] » エコノミストOnline：刑事司法対談（拡大版)　周防正行×木谷明　冤罪を生む「ムラ社会」の論理　法曹一元、証拠全面開示が改革のカギ | 週刊エコノミスト Online　木谷　それだけに、裁判員制度を台無しにしてしまいかねない… https://t.co/WIWeklcyLU

周防　私は劇映画を撮っている。全部、うそ、フィクションだ。それでも、見た人は笑い、泣き、感動する。映像は本当に強い影響力を伴う。その特性を利用して、作り話を描くのが映画だ。 https://t.co/cYIJbTR9kw

２０１０年以降、足利事件、東電ＯＬ殺人事件、布川事件、松橋事件で再審無罪が確定し、そのほかにも、袴田事件などで再審開始が決定した。こうした中、今年５月に「再審法改正をめざす市民の会」が結成され、木谷さんと周防さんは共同代表を務めて… https://t.co/HyorNgIctC

木谷　それにしても、大崎事件の最高裁決定はひどい。１・２審で充実した審理の末再審開始決定を積み重ねてきた。なのに、書面審理だけしかしない最高裁の５人の裁判官が、あたかも自分たちが神様にでもなったような感じで、ろくな理由づけもしない… https://t.co/U6bI3sGMFC

〈〈〈　：Ａｔｏｍ： 2019-09-27 13:30 　〈〈〈

〉〉〉：Emacs： 2019-09-27（金曜日）13：38　 〉〉〉

　AtomエディタでTwitterに投稿を行いました。慣れていないこともありますが、Emacsでは日本語変換もインライン表示となるので日本語の扱いが使いやすいです。

〈〈〈：Emacs： 2019-09-27（金曜日）13：42 　〈〈〈

