#+TITLE: "升永英俊弁護士＋久保利英明弁護士＋伊藤真弁護士による、恐怖新聞に擬えられた上告理由書"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-10-19 11:52:39 +0900
FILE_NAME: 2019-10-19-115239_升永英俊弁護士＋久保利英明弁護士＋伊藤真弁護士による、恐怖新聞に擬えられた上告理由書.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 久保利英明弁護士,升永英俊弁護士,伊藤真弁護士,岡口基一裁判官,中村真弁護士,漫画,最高裁
記事タイトル名の文字数：42　保存ファイル名の文字数：64
#+STARTUP: showeverything


* 伊藤真弁護士と深澤諭史弁護士：升永英俊弁護士＋久保利英明弁護士＋伊藤真弁護士による、恐怖新聞に擬えられた上告理由書
  CLOCK: [2019-10-19 土 11:56]--[2019-10-19 土 16:31] =>  4:35

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 久保利英明弁護士,升永英俊弁護士,伊藤真弁護士,岡口基一裁判官,中村真弁護士,漫画,最高裁,深澤諭史弁護士,伊藤塾

〉〉〉：Emacs： 2019-10-19（土曜日）11：56　 〉〉〉

　いろいろと後回しにして、最近の深澤諭史弁護士のツイートから取り上げたいと思います。気になる内容で、調べたのですが、確認は出来ませんでした。このあとまとめ記事を作成し、その結果を見ながら記録作成の作業を進めたいと思います。

```
[1280]  % dp -p|grep ゼミ |tail -n 10
[link:] 2019年03月24日12時17分の登録： ＼東京大学教養学部 川人ゼミ 公式アカウント　@kawahitoseminar＼川人ゼミは、今年で28年目を迎えた川人博弁護士によるゼミで、社会の現場に赴いて社会問題を考 http://hirono2014sk.blogspot.com/2019/03/kawahitoseminar28.html
[link:] 2019年04月26日15時53分の登録： ＼tomoy@ono　@ono_tomoya＼うちのゼミの卒業生です。ゼミの卒業生で、「私も！」「僕も！」という人がいれば連絡ください。載せてもらえるようお願いしてみます http://hirono2014sk.blogspot.com/2019/04/tomoyonoonotomoya.html
[link:] 2019年07月07日22時22分の登録： ＼ほりぐちです　@mstk_Horiguchi＼安井先生(元会長)とは自分が大学の時にAクラスゼミで教えてもらって以来の30年のお付き合いですが、まあ40期代以上の都会で http://hirono2014sk.blogspot.com/2019/07/mstkhoriguchia3040.html
[link:] 2019年07月15日23時15分の登録： ＼ぱうぜ　@kfpause＼なお、非常に熱心に質問をしてくれた学部生から、「あのゴミクルーンさんのゼミの先生がいらっしゃると聞いてたのしみにしてました！」と満面の笑みで教 http://hirono2014sk.blogspot.com/2019/07/kfpause_15.html
[link:] 2019年09月20日21時36分の登録： ＼ʇɐɯɐɹnɯʞ　@kmuramatsu＼刑法ゼミで、組織のミスについて誰か個人に刑事責任を問うのはやはり相当難しいんじゃないか。みたいな話をしてた２０年前。\n個人主義 http://hirono2014sk.blogspot.com/2019/09/nkmuramatsu.html
[link:] 2019年10月10日23時02分の登録： ＼深澤諭史　@fukazawas＼出身ゼミが，司法試験の合格実績で無双している。さすがだ・・・。 http://hirono2014sk.blogspot.com/2019/10/fukazawas_29.html
[link:] 2019年10月10日23時11分の登録： REGEXP：”ゼミ”／深澤諭史（@fukazawas）の検索（2014-01-18〜2019-10-10／2019年10月10日23時11分の記録60件） http://hirono2014sk.blogspot.com/2019/10/regexpfukazawas2014-01-182019-10.html
[link:] 2019年10月10日23時17分の登録： ％@fukazawas　深澤諭史％やったー。もう一つの大学のゼミでも，「つぶ犯」がテキストに採用です！\nやったね！（・∀・）ｖ http://hirono2014sk.blogspot.com/2019/10/fukazawasn_10.html
[link:] 2019年10月10日23時17分の登録： ％@fukazawas　深澤諭史％\n\nんー，なんか，最近，某大学法学部の某ゼミ生とそのＯＢとの間で，私のＴｗｉｔｔｅｒアカウントが有名になっているとのこと。\n\n心当たりある人は，リプライしなさい（・∀・） http://hirono2014sk.blogspot.com/2019/10/fukazawasnnnn.html
[link:] 2019年10月10日23時22分の登録： REGEXP：”神山ゼミ”／データベース登録済みツイート：2019年10月10日23時22分の記録：ユーザ・投稿：7／16件 http://hirono2014sk.blogspot.com/2019/10/regexp201910102322716.html
```

　「% dp -p|grep ゼミ |wc -l」というコマンドの実行結果は34です。つまり34件あるうちの10件を上記に掲載しました。全て時間順で古いものから並んでいるはずなので、最新の10件ということになります。

　検索結果の最新は「神山ゼミ」となっていますが、これはちょっと忘れていたもので、先程から頭で描いていたゼミのイメージを修正したくなるものです。この神山ゼミは、数年前からちょこちょこと見かけるものですが、詳しく調べたことはないので実態も不明です。

　私個人のゼミに対するイメージや理解のことですが、大学や予備校での講義のようなものをイメージしていました。それも試験対策という意味合いの強いものです。

　司法試験の試験対策で有名なのが伊藤真弁護士の伊藤塾ですが、深澤諭史弁護士のツイートなど見ていると、彼らが常に批判を続けている司法制度改革も、伊藤塾のような試験対策のための経営から利権を守るため、というようなことがツイートされていたかと思います。

fukazawas ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW fukazawas（深澤諭史） 日時：2019/10/10 22:34 URL： https://twitter.com/fukazawas/status/1182288296098988032
> 出身ゼミが，司法試験の合格実績で無双している。さすがだ・・・。
▷▷▷　　　　　End　　　　　▷▷▷

　あらためて確認をすると上記の深澤諭史弁護士のツイートは、今月10月10日の投稿でした。台風19号が大きな被害となったのは12日だったと思います。日本全体で大きな被害が予想されていたので、その前後というのもこれまでにちょっと経験がないような社会の雰囲気がありました。

　司法試験のゼミで知られた名前はなかったのですが、すぐに伊藤塾のことが思い浮かび、深澤諭史弁護士が伊藤塾の出身なのかどうか調べてみました。結果は未確認で終わったと思います。それがゼミをキーワードにしたまとめ記事ですが、伊藤塾としては作成していなかったと思います。

```
[1283]  % dp -p|grep fukazawas |grep 伊藤
[link:] 2019年06月22日23時08分の登録： ＼深澤諭史　@fukazawas＼伊藤真先生の「伊藤真の法学入門」もいいのではないかと思います。\n両先生とも法律を教えることにかけては、日本最高の先生なので、間違いはない http://hirono2014sk.blogspot.com/2019/06/fukazawas_323.html
[link:] 2019年10月10日23時11分の登録： REGEXP：”伊藤塾”／深澤諭史（@fukazawas）の検索（2015-10-07〜2018-03-02／2019年10月10日23時11分の記録9件） http://hirono2014sk.blogspot.com/2019/10/regexpfukazawas2015-10-072018-03.html
```

　10日ほど前のことになりますが、すでに記憶違いをしていたようです。伊藤塾のまとめ記事は、2019年10月10日23時11分の登録として確認しました。ただ、台風のことも気になり集中できていなかったためか、伊藤真弁護士を含めるような調べ方はやっていなかったようです。

[link:] 2019年10月19日12時24分の登録： REGEXP：”伊藤真”／深澤諭史（@fukazawas）の検索（2015-10-07〜2019-06-22／2019年10月19日12時24分の記録13件） http://hirono2014sk.blogspot.com/2019/10/regexpfukazawas2015-10-072019-06.html

[link:] 2019年10月19日12時25分の登録： REGEXP：”伊藤”／深澤諭史（@fukazawas）の検索（2015-10-07〜2019-06-22／2019年10月19日12時25分の記録47件） http://hirono2014sk.blogspot.com/2019/10/regexpfukazawas2015-10-072019-06_19.html

　まだタイトル名の結果部分しか見ていないですが、13件と57件というのは、だいぶん開きがあります。伊藤というのはよくある名前ですが、伊藤真弁護士以外に伊藤をキーワードに含むツイートが何なのか気になっています。

　さきほど伊藤という名前で久しぶりに思い出したのが、伊藤栄樹、伊藤英樹のどちらか、前者だったと思いますが、有名な検事総長がいました。何か本を出していて文庫本として読んだ記憶があります。歴代の検事総長では最も有名かもしれません。団藤重光最高裁長官に似た存在感です。

　指揮権の発動というのもずいぶん久しぶりに思い出しましたが、法律としては有効なままかと思いますが、まったく話題になるのも見かけなくなり、ずいぶん経つように思います。

[link:] » 人は死ねばゴミになる (小学館文庫) | 伊藤 栄樹 |本 | 通販 | Amazon https://t.co/jfS4g894NY

　Googleのサジェストの第一候補に出てきましたが、そのままのタイトルの本が出ていたとは驚きました。

　時刻は13時08分です。台所で洗い物をしていました。昼食は、昨夜の残りの冷や飯に、同じく味噌汁を温め直し、卵を１つ追加したものをかけて済ませました。味噌汁というのも玉ねぎとじゃがいも、糸コンニャクでした。

　洗い物を始める前に思い出していたのですが、深澤諭史弁護士のツイートに多く含まれていると思われるのは、伊藤和子弁護士のことです。春の性犯罪無罪判決のときは、法クラで批判的な話題にされていましたが、近頃は話題も見かけなくなっています。

[link:] » (3) 弁護士 太田啓子（@katepanda2）さん / Twitter https://t.co/3ll0td1STE

　Googleで「おおた　べんごし」と検索するとすぐに見つかったのですが、告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)でブロックされていました。これは気が付かなかったです。

　ずいぶん前のことになるので、正確ではないかもしれないのですが、奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)ではブロックされていたものが、その後解除されていました。それもずいぶんと前のことかと思います。

　太田か大田か結構迷ったのですが、今朝は東京都の大田区で大きな発見がありました。少年時代に漫画で知ったように思いますが、お金持ちの高級住宅地で有名な田園調布が、大田区としって驚いたのです。

　先日の台風19合の被害の頃から薄々とは感じていたのですが、私は東京都の調布市と田園調布を混同を一緒くたで考えていたようです。しかし、大田区は大田市場に仕事でよく行っていましたが、海に近く田園とは無縁というイメージが強く、正反対で物事を考えていたようです。

　その田園調布の実際の場所についてもまだ調べていたいのですが、同じく神原元弁護士のイメージが強かった武蔵小杉が神奈川県の川崎市だと知って、けっこう驚きました。

　もしやと思い確認したところ、奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)のアカウントも太田啓子弁護士にブロックされていました。どちらもスクリーンショットは記録済みです。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-10-19 13:28／2019/10/19 13:15 URL： https://twitter.com/kk_hirono/status/1185412296933134337 https://twitter.com/s_hirono/status/1185409127335358464
> 2019-10-19-131453_弁護士　太田啓子@katepanda2ブロックされています@katepanda2さんのフォローやツイートの表示はできません。詳細はこちら.jpg https://t.co/IVt0Pb33QC
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-10-19 13:28／2019/10/19 13:26 URL： https://twitter.com/kk_hirono/status/1185412276972470274 https://twitter.com/s_hirono/status/1185411763681914881
> 2019-10-19-132548_弁護士　太田啓子@katepanda2ブロックされています@katepanda2さんのフォローやツイートの表示はできません。詳細はこちら.jpg https://t.co/XK6RAbJWtW
▶▶▶　　　　　End　　　　　▶▶▶

　太田啓子弁護士といえば、最近になって「憲法カフェへようこそ」の一人だったらしいと気が付きました。同名の本が出版されているようですが、一月ほど前になりますか、その本を宇出津の図書館で見かけていました。Twitterのアカウントはだいぶん前に見ています。

　太田啓子弁護士が、3日ほど前からTwitterで話題となっているのは、日本赤十字社の献血ポスターのことです。同じ日だったと思うのですが、14時台のテレビの情報番組で、避難所の内部が撮影されていて珍しいと思いながら見ていたところ、赤十字奉仕団という字幕が出てきました。

　初めて見聞きにしたように思ったので、すぐにネットで調べたところ石川県や能登町にもあると知って驚きました。それまで見聞きしなかったのがとても不思議に思えたからです。見かけていても気が付かなかっただけということは十分にありうるとは思います。

katepanda2 ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW katepanda2（弁護士 太田啓子） 日時：2017/11/03 01:47 URL： https://twitter.com/katepanda2/status/926128708926062592
> 【憲法クイズ】Q. 憲法というルールを守らなければならない人をすべて選べ \n １．天皇 \n ２．国務大臣 \n ３．国会議員 \n ４．裁判官 \n ５．弁護士 \n ６．国民 \n →答えは次ツイで \n #檻の中のライオン
▷▷▷　　　　　End　　　　　▷▷▷

　ブロックされていない状態で太田啓子弁護士のTwitterを開いたところ、上記のツイートが固定されたツイートとなっていました。2017年11月3日とけっこう前のツイートです。憲法を守らなくてもよい人が、いると考える人がいるという前提での設問となっているように感じました。

　これまで滅多に見ることのなかった太田啓子弁護士のTwitterタイムラインですが、どこのアカウントのタイムラインなのかと戸惑うほどのリツイートだらけです。実名弁護士アカウントの傾向としても珍しく感じました。

katepanda2 ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW katepanda2（弁護士 太田啓子） 日時：2019/10/18 10:13 URL： https://twitter.com/katepanda2/status/1185000809089527808
> 是非 \n 「つまり、植松被告もインターネットなどを通じて世の中に散らばる悪意をフィルタリングすることなく「学習」して、彼自身がその悪意を体現してしまったというか、植松被告がAIやBOTのようなものと近いのではないかとも考えられる指摘で… https://t.co/Jsx67x7PZU
▷▷▷　　　　　End　　　　　▷▷▷

　ちょっと気になる内容の太田啓子弁護士のツイートです。次のネット記事のようなツイートを公式引用しています。括弧書きにある女性の名前は見覚えがあって、一頃話題になっていたようにも思いますが、内容は思い出せません。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜HuffPostJapan（ハフポスト日本版） 日時：2019-10-19 13:47／2019/10/18 08:34 URL： https://twitter.com/kk_hirono/status/1185417210941980672 https://twitter.com/HuffPostJapan/status/1184975895938977796
> 女性にわざとぶつかる男、抱っこ紐のバックルを外す人…。  私たち一人ひとりが、この10年、20年くらいで自分がどれだけ殺伐として冷酷になったのかを考える必要があると思う。（雨宮処凛）  https://t.co/9BvV3gsEk1
▶▶▶　　　　　End　　　　　▶▶▶

　ツイートのテキストだけだとわからなかったのですが、女性の顔写真付きの記事の要約版があって、そこに「相模原市の障害者施設で45人を殺傷した・・・」と出ています。女性の背景が気になるもので、宗教画と学芸会の飾りのようなものが入り混じったように見えます。

［link：］ 「なぜ、弱者を叩く社会になったのか？」相模原事件から考えた、不寛容な時代 | ハフポスト https://www.huffingtonpost.jp/entry/story_jp_5da51997e4b01c76560b90c6?ncid=tweetlnkjphpmg00000001

　「先日の台風19号の際にも、ホームレスの人たちが避難所への入所を断られ、この言葉がまた話題になっている。」とありました。今月の15日の記事となっていたので、なぜこのタイミング、他に話題は見かけていないと思っていたのですが、ここに付会があったようです。

　太田啓子弁護士は、ツイートで次の部分を引用していたようです。

```
そして、批評家で元障害者ヘルパーの杉田俊介さんと「べてるの家」の理事・向谷地生良さんが同じ出来事を指摘していたことも驚きでした。その指摘とは、相模原事件が起きたのと同じ年の3月に、マイクロソフトが開発したAI(人工知能)の実験で、インターネットにAIを接続したら勝手に学習して、ユダヤ人のホロコーストを否定したり、ヒトラーを礼賛するような発言をするようになったというニュース。

つまり、植松被告もインターネットなどを通じて世の中に散らばる悪意をフィルタリングすることなく「学習」して、彼自身がその悪意を体現してしまったというか、植松被告がAIやBOTのようなものと近いのではないかとも考えられる指摘です。この視点はこの本を作るまで私の中になかったものなので、とても衝撃でした。

［source：］「なぜ、弱者を叩く社会になったのか？」相模原事件から考えた、不寛容な時代 | ハフポスト https://www.huffingtonpost.jp/entry/story_jp_5da51997e4b01c76560b90c6?ncid=tweetlnkjphpmg00000001
```

　途中から飛ばし読みになりましたが、最後に画像で本の紹介がありました。「この国の不寛容の果てに　相模原事件と私たちの時代」。相模原事件の部分はサブタイトルのようです。雨宮という女性がどんな人なのか、この記事では確認ができませんでした。

　深入りしないで引き返そうか迷ったのですが、名前と顔以外に思い出せることが何もなかったので、Twilogで調べてみました。すると、思いがけない発見がありました。リツイートしていたツイートです。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-19 14:09／2017/10/07 13:07 URL： https://twitter.com/kk_hirono/status/1185422765794287621 https://twitter.com/hirono_hideki/status/916515215067422720
> 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中: ＼雨宮処凛　@karin_amamiya＼菅直人さん、共産党山下さん、福島みずほさん登場。 https://t.co/VACHLowJoJ
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-19 14:09／2018/03/23 10:27 URL： https://twitter.com/kk_hirono/status/1185422680045916160 https://twitter.com/hirono_hideki/status/976993910286311427
> 第440回：獄中半世紀の袴田巌さんに会った!!　〜冤罪青春グラフィティ「獄友」も観た〜の巻（雨宮処凛） | マガジン9 https://t.co/R4hSZgAGmm
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-19 14:09／2018/06/06 00:30 URL： https://twitter.com/kk_hirono/status/1185422606976991233 https://twitter.com/hirono_hideki/status/1004022779396571136
> 「オウム事件真相究明の会」立ち上げ記者会見まとめ - Togetter https://t.co/zfO9VLLzpL ■呼びかけ人 青木理（ジャーナリスト） 雨宮処凛（作家） 大谷昭宏（ジャーナリスト） 香山リカ（精神科医、評論家）
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜karin_amamiya（雨宮処凛） 日時：2019-10-19 14:08／2018/03/21 18:56 URL： https://twitter.com/kk_hirono/status/1185422390982922241 https://twitter.com/karin_amamiya/status/976397087850971136
> 第441回：金沢市役所の刺傷事件と、生活保護打ち切り。の巻（雨宮処凛） https://t.co/LgJafWGoHY #maga9
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「雨宮処凛」の検索結果 - Twilog https://t.co/NBbu1nXhC1

　「オウム事件真相究明の会」のことは記憶にありますが、そのメンバーの一人だったとはツイートしたときも気が付かなかったのかもしれません。一つ上に青木理というビックネームがあるからです。しかし、これもすっかり完全に忘れていました。

　金沢市役所の刺傷事件ですが、地元石川県の事件だったのでテレビの情報も多かったと思いますが、今となってはあっけなく忘れ去られている感があります。死者が出ていればまた違ったかもしれないですが、死者が出なかったのが不思議な事件でした。

　被疑者が金沢市のみどり団地に住んでいたということで、個人的にはいろいろと過去を思い出しながら考えたこともありました。いくらか書いていることもあるかもしれないですが、あれもこれも書いていくと、それだけでも馬鹿にならない情報量と時間の消費となります。

　そういえば、昨日の夕方、18時台、金曜日なので「花のテレ金ちゃん」という番組名ですが、金沢小景という久しぶりにみたコーナーで、諸江団地が出ていました。少し名前は聞いた気がしたのですが、金沢市内のどの辺りにあるのか見当がつきませんでした。

　数日前にも諸江については取り上げていますが、近くに住んでいたこともあり、仕事でもよく通るところだったのですが、諸江団地がどこにあるのか謎でした。建物は同じ金沢市内の平和団地とよく似ているようでした。

　その平和団地というのも近くを通る野田専光寺線以外は、ほとんど足を踏み入れたことがなかったのですが、被告発人梅野博之が住んでいたという住所で、一度どんなところなのか、Googleのストリートビューで見たことがありました。割と最近で数ヶ月前と思います。

▶（1／9） TW fukazawas（深澤諭史） 日時：2015-10-07 18:44:00 +0900 URL： https://twitter.com/fukazawas/status/651694677289078784
{% tweet 651694677289078784 %}
> 伊藤塾のシケタイばかり猛プッシュしているんで，回し者かなにかと思われていそう。 \n ですが，１円も頂戴していませんですよ。特別，塾に知り合いもいなかったはず。

　前にも目にしているはずのツイートかと思いますが、深澤諭史弁護士が伊藤塾とは知り合いもいないはず、と語っているので、これをみると深澤諭史弁護士が伊藤塾の塾生だった余地はなさそうです。

　「シケタイ」という言葉の意味がわかりません。シイタケをイメージしたのですが、よくみると試験対策の可能性がありそうです。隠語のようにも見えますが、こんなカタカナの使い方は他で見ていないと思います。

▶（4／9） RT fukazawas（深澤諭史）｜motoetaichiro（参議院議員 元榮太一郎（もとえ）） 日時：2017-01-17 22:34:00 +0900／2017-01-17 22:27:00 +0900 URL： https://twitter.com/fukazawas/status/821349873303703556 https://twitter.com/motoetaichiro/status/821348125545615360
{% tweet 821349873303703556 %}
> 伊藤塾、東京校【明日の法律家講座】で講師を務めました。弁護士としての経験と弁護士ドットコム株式会社を起業した経緯、そして参議院議員となった今、政治家として日々感じる想いをお話させて頂きました… #自民党 #千葉県… https://t.co/6nMo4OQB0a

　深澤諭史弁護士のツイートは、モトケンこと矢部善朗弁護士（京都弁護士会）、小倉秀夫弁護士の3人を特別なものとし、無条件に全てのツイートをデータベースに記録しています。そこで記録されていたのかとも考えますが、上記のリツイートにある元のツイートは記憶にないものです。

　元のツイートが2017年1月17日となっています。この弁護士ドットコムの起業者という元榮太一郎弁護士は、日弁連のシンポジウムで、深澤諭史弁護士と二人同じブースで講演したということが強く印象にあるのですが、それは10月ぐらいの秋の時期だったと記憶にあります。

　最近は名前もほとんど見かけることのない元榮太一郎弁護士ですが、心なしか、弁護士ドットコムの記事というのも法クラのタイムラインで、見かける機会が少なくなっているように思います。

▶（6／9） RT fukazawas（深澤諭史）｜KshAb76（ちゃんおに） 日時：2017-09-01 11:04:00 +0900／2017-09-01 01:22:00 +0900 URL： https://twitter.com/fukazawas/status/903438332041953280 https://twitter.com/KshAb76/status/903291854245863424
{% tweet 903438332041953280 %}
> 「伊藤塾」の伊藤真塾長は「学生も社会人も優秀な人ほど予備試験狙い。法科大学院は滑り止めにすぎない」と話す \n \n 法科大学院、半数が撤退　甘い目算、乱立で質低下：日本経済新聞 https://t.co/1ZY0dgJtH7

　この予備試験というのも法クラのツイート以外に見かけることはなく、それ以前に司法試験の合格発表もここ1,2年は全くテレビニュースになっていない気がします。司法修習生の給付金の復活がニュースになっていなかったのは、さすがにどうなのかと頭を抱えたくなりました。

▶（9／9） RT fukazawas（深澤諭史）｜Miyako_Koji（都 行志） 日時：2018-03-02 08:49:00 +0900／2018-03-01 22:18:00 +0900 URL： https://twitter.com/fukazawas/status/969358883616509952 https://twitter.com/Miyako_Koji/status/969200208222408706
{% tweet 969358883616509952 %}
> 体調を崩されて業務停止された茨城の弁護士の方、伊藤塾のインタビューを読む限り、善人だったと思う。善人であればあるほど、採算度外視で事件を受けたりしてしまうから、経営の面で悩みを抱えられていたのかもしれない...

　善人は弁護士に向いていないとも読めるようなツイートです。そういえば、この都行志弁護士のツイートも、最近は法クラのタイムラインで見かけることが少なくなっている気がしました。最も重点的に観察しているのは、深澤諭史弁護士のタイムラインになります。

```
弁護士 都  行志
@Miyako_Koji
高崎の若手弁護士／銀座、高崎等に4拠点／税理士／群馬弁護士会所属／元テレビ局報道記者・ディレクター／カリフォルニア州LAに5年／2017年群馬県高崎市で独立
群馬県 高崎市miyakosougou-law.com2012年5月からTwitterを利用しています
1,008 フォロー中
4,849 フォロワー

［source：］(3) 弁護士 都 行志（@Miyako_Koji）さん / Twitter https://twitter.com/Miyako_Koji
```

　群馬県の高崎市に弁護士事務所を開設したというイメージが強く、他にも拠点があるような情報は見覚えがあったのですが、今回、銀座とプロフィールにあるのを見て、印象がずいぶん変わった気がします。

　私は長距離トラック運転手の経験があるので、地名を見ると過去の体験や記憶に結びつけて考える傾向があります。群馬県の高崎市というのは国道17号と18号が交わり、分岐するところで、すぐ近くには県庁所在地の前橋市もあって、なかなか特徴的なところだと思います。

　また、過去の事件や裁判と土地を結びつけて考えることも多いです。小さい頃の記憶ですが、大久保清という昭和の犯罪史に残るような人物がいて、それも高崎市に繋がっています。警察が留置場を寂しい場所に移したところ自白につながったという話も印象に残っています。

　そういえば、神戸市の小学校での教師間のいじめ問題で、昨日辺りみたネット記事の見出しに「土地柄」という言葉が含まれていたのも、これまでにないものを感じました。東須磨小学校だったと思います。

　時刻は15時04分で、朝は7時30分から起きていますが、今日はまだ一度もテレビをつけずにいます。東須磨小学校の問題はテレビでの注目度も高いようですが、私は個人的に、裏方のような弁護士の存在を気にかけており、恐怖新聞の漫画の現象に近いものを手探りしています。

　「弁護士時代」や「弁護士新聞」という言葉も、今週はしきりに頭に浮かんできました。社会学的な考察でもあると思っています。また、問題の解決のも重要な要素として、分析、記録等の作業を進めています。

▶（01／47） TW fukazawas（深澤諭史） 日時：2015-10-07 18:39:00 +0900 URL： https://twitter.com/fukazawas/status/651693420868583424
{% tweet 651693420868583424 %}
> @k_sawmen 伊藤真実務法律基礎講座「労働法」。薄いし軽いので移動時間に読破出来ます。

　伊藤真弁護士は、憲法と司法試験の塾長というイメージしかなかったので、労働法が出てきたのは意外です。まとめ記事は古いものから並んでいるはずですが、1番目に関わらず、2015年10月7日というのは、ずいぶん最近のことのように感じます。

　私が伊藤真弁護士のことを知ったのも、たぶんここ10年内で、2010年4月にTwitterを始めた後だったとも思うのですが、比較的早い段階の情報として、伊藤真弁護士はジャーナリストの江川紹子氏との関わりを見ていたという記憶があります。

　まとめ記事も作成してあるかもしれません。ジャーナリストの江川紹子氏のツイートで、伊藤真弁護士をキーワードに含むツイートのまとめです。ある時期を境に、ぴたりとなくなった様子だったので、それもなぜなのかと気になっていました。

```
[1320]  % dp -p | grep amneris84|grep 伊藤
[link:] 2018年03月31日16時26分の登録： REGEXP：”伊藤真（弁護士）？”／Shoko Egawa（@amneris84）の検索（2010-05-02〜2015-09-25／2018年03月31日16時26分の記録8件） http://hirono2014sk.blogspot.com/2018/03/regexpshoko-egawaamneris842010-05.html
[link:] 2019年03月02日03時01分の登録： REGEXP：”伊藤真（弁護士）？”／Shoko Egawa（@amneris84）の検索（2010-05-02〜2015-09-25／2019年03月02日03時01分の記録8件） http://hirono2014sk.blogspot.com/2019/03/regexpshoko-egawaamneris842010-05.html
[link:] 2019年03月04日09時36分の登録： ＼Shoko Egawa　@amneris84＼伊藤詩織さんのケースも、同じ構図では？ http://hirono2014sk.blogspot.com/2019/03/shoko-egawaamneris84_4.html
```

　ここで思い出したのですが、伊藤といえば「伊藤詩織」さんのことをすっかり忘れていました。存在自体は忘れることはなく、つい最近もTwitterで名前を見かけたように思います。どこで見かけたのか、見た内容も憶えていないですが、ほんの数日前のことと思います。

　気になったことは、確認をしておきたいと思います。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-19 15:22／2019/07/19 19:04 URL： https://twitter.com/kk_hirono/status/1185441131238055938 https://twitter.com/hirono_hideki/status/1152157137939791873
> 「伊藤詩織さん」vs.「官邸ベッタリ記者」の法廷対決（2/2） 7月8日、山口敬之元TBSワシントン支局長（53）と、彼にレイプされたと訴える伊藤詩織さん（30）が民事法廷で対決した。1100万円の損害賠償を求めた詩織さんに対し、… https://t.co/WtQjFisgDC
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hyodo_masatoshi（兵頭正俊） 日時：2019-10-19 15:22／2017/11/15 21:17 URL： https://twitter.com/kk_hirono/status/1185441102137982976 https://twitter.com/hyodo_masatoshi/status/930771807325405184
> 伊藤詩織のレイプ事件はおれがやる。それは山本太郎しかないでしょう。山本、頼むよ。彼女は野党からもメディアからも突き放されて、外国メディアと一緒に闘っている。こんなひどい姿はない。山本、頼むよ。それから枝野、まっとうに頼むよ。https://t.co/RAuw9A2Imx
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜J_Iwasaki2（Jun＠恋愛・婚活応援ブログ） 日時：2019-10-19 15:22／2017/11/16 20:24 URL： https://twitter.com/kk_hirono/status/1185441075290243072 https://twitter.com/J_Iwasaki2/status/931120843580522496
> @hyodo_masatoshi 伊藤詩織さんの案件は、山本太郎議員が国会で追及するそうだ。期待しよう。リンク先の記事タイトル：「アベ友が起こしたレイプ事件をマスコミが報道しないのはナゼか？」https://t.co/wPtHuYHVM1
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「伊藤詩織」の検索結果 - Twilog https://t.co/sdy6jUC1Bh

　自分でリツイートをしていたことは間違いないと思いますが、山本太郎議員と伊藤詩織さんの関係性というのは、記憶になかったもので、意外な情報と感じました。伊藤詩織さんのことは数日前にも見たと思うのですが、メモのようなかたちには残していなかったようです。

　この機会なので、昨日に告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)のアカウントでの利用を再開したTogetterでまとめ記事を作成しておこうと思います。再開と言っても前は1回だけで、舞鶴女子殺害事件に関するものでした。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-19 15:22／2019/07/19 19:04 URL： https://twitter.com/kk_hirono/status/1185441131238055938 https://twitter.com/hirono_hideki/status/1152157137939791873
> 「伊藤詩織さん」vs.「官邸ベッタリ記者」の法廷対決（2/2） 7月8日、山口敬之元TBSワシントン支局長（53）と、彼にレイプされたと訴える伊藤詩織さん（30）が民事法廷で対決した。1100万円の損害賠償を求めた詩織さんに対し、… https://t.co/WtQjFisgDC
▶▶▶　　　　　End　　　　　▶▶▶

　自分でリツイートをしていたことは間違いないと思いますが、山本太郎議員と伊藤詩織さんの関係性というのは、記憶になかったもので、意外な情報と感じました。伊藤詩織さんのことは数日前にも見たと思うのですが、メモのようなかたちには残していなかったようです。

　この機会なので、昨日に告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)のアカウントでの利用を再開したTogetterでまとめ記事を作成しておこうと思います。再開と言っても前は1回だけで、舞鶴女子殺害事件に関するものでした。

「伊藤詩織さんの近況について調べたツイートをまとめました（2019年10月19日）」をトゥギャりました。 https://t.co/tujBFGbNTm

▶（07／47） RT fukazawas（深澤諭史）｜uwaaaa（サイ太） 日時：2016-02-20 17:16:00 +0900／2016-02-19 20:13:00 +0900 URL： https://twitter.com/fukazawas/status/700957125762154496 https://twitter.com/uwaaaa/status/700639226543509505
{% tweet 700957125762154496 %}
> 伊藤真先生は司法試験予備校で様々な分野から司法試験を目指す人を見てきた。鎌田薫先生は法学部でしか教えていないから，法学部を出て司法試験を目指す人しか見てこなかった。だからああいう発言になるのだと。

　上記の深澤諭史弁護士がリツイートした刑裁サイ太のツイートによると、伊藤真弁護士の伊藤塾は司法試験予備校ということになるようです。現役や浪人というのは昭和52年頃に東大一直線という漫画で初めて知りましたが、予備校というのは浪人生のイメージばかりありました。

▶（11／47） RT fukazawas（深澤諭史）｜redipsjp（Masahiro Ito/伊藤雅浩） 日時：2016-03-11 22:30:00 +0900／2016-03-11 22:28:00 +0900 URL： https://twitter.com/fukazawas/status/708284027241766912 https://twitter.com/redipsjp/status/708283373609877505
{% tweet 708284027241766912 %}
> 実は今日初めて伊藤たけるさん　@itotakeru と深澤先生 @fukazawas ，萱野先生　@yuikayano とあいさつさせてもらった。

　もう一つ、伊藤たける、という名前が出てきて思い出しましたが、伊藤たける、という弁護士も司法試験の講師のような立場で、憲法の分野に精通をしているようです。しかし、以前、ジャーナリストの江川紹子氏にボコボコのように批判をされていました。

▶（20／47） TW fukazawas（深澤諭史） 日時：2017-01-09 23:09:00 +0900 URL： https://twitter.com/fukazawas/status/818459572578852864
{% tweet 818459572578852864 %}
> ご協力ありがとうございました。 \n なお私の場合ですが、参考まで \n 憲法：伊藤真試験対策講座 \n 行政法：伊藤真試験対策講座 \n 民法：伊藤真試験対策講座 \n 刑法：伊藤真試験対策講座 \n 商法：伊藤真試験対策講座 \n 民訴法：伊藤真試験対策講座 \n 刑訴法：… https://t.co/sJqBIOr8J8

　さきほど伊藤塾とは知り合いもいないはずとツイートがあった深澤諭史弁護士ですが、憲法、行政法、民法、刑法、商法、民訴法、刑訴法で「伊藤真試験対策講座」を使ったように紹介しています。追伸講座のような感じになっていますが、伊藤塾の通信講座は情報を見ていないです。

　深澤諭史弁護士については、公開している経歴に、明治大学の卒業と東京大学大学院があります。この明治大学の法学部については、以前、会話で夜間学校として通学していたという話を聞いたことがあり、ここ一月以内にも同じような話をネットで見かけたことがありました。

　知名度の高い明治大学がすべて夜間学校とは考えにくいのですが、少し調べて確認をしておきたいと思います。なるべくなら法学部に絞るつもりです。

[link:] » 明治大学 夜間 - Google 検索 https://t.co/KIJpJs2Lha

[link:] » バブル期受験生の駆け込み寺！？現在は廃止された有名大学の二部（夜間）学部！！ (page 2) - Middle Edge（ミドルエッジ） https://t.co/VP4iRzzpWQ

　私が個人的に明治大学法学部の夜間の話を聞いたのは、平成8年頃のことで、その話をしていた人は、その時、70代かあるいは80代になっていたと思います。バブルの時代の話ではありません。

▶（23／47） RT fukazawas（深澤諭史）｜Hideo_Ogura（小倉秀夫） 日時：2017-01-17 16:11:00 +0900／2017-01-17 16:09:00 +0900 URL： https://twitter.com/fukazawas/status/821253486272618496 https://twitter.com/Hideo_Ogura/status/821253067450421248
{% tweet 821253486272618496 %}
> 良い悪いではなく、よく予備校系のテキスト中心で退屈にならなかったなあという感想を持ってしまう。RT @fukazawas: なお私の場合ですが、参考まで 憲法：伊藤真試験対策講座 行政法：伊藤真試験対策講座 民法：伊藤真試験対策講座 刑法：

　そういえば、小倉秀夫弁護士の自己紹介に、明治大学の講師というのもあったかと思います。中央大学の講師の方が期間も長かったのか印象が強くありましたが、明治大学もあったように思います。首都大学というのもありましたが、採用されたという知らせから終わりが早かったように記憶します。

▶（25／47） RT fukazawas（深澤諭史）｜legalnews_jp（Legal News（リーガルニュース）） 日時：2017-01-26 21:54:00 +0900／2017-01-25 23:57:00 +0900 URL： https://twitter.com/fukazawas/status/824601502324912128 https://twitter.com/legalnews_jp/status/824269975737077760
{% tweet 824601502324912128 %}
> 基本憲法I 基本的人権 　木下 智史 (著), 伊藤 建 (著) https://t.co/DtKrNuSD6r 憲法事例問題を解くために最も実践的なテキスト、遂に完成! 『事例研究 憲法』の木下教授と、大人気ブログ「憲法の流儀」の伊藤弁護士の最強コラボ

　伊藤たける弁護士については、何度か調べたことがあり、滋賀県での弁護士会登録から富山県への弁護士会登録など、神出鬼没な謎のような存在感があり、神話上の人物なのか日本武尊とイメージが重なることもあったのですが、伊藤建が本名のようです。

　日本武尊という人物は名前は有名ですが、何をした人なのかよく知らず、銅像に鳩の糞がつかないという話をテレビで見かけたことがありました。ちょっと調べて確認をしておきます。

[link:] » 日本武尊　鳩 - Google 検索 https://t.co/4VrlKd8kHL

[link:] » 金沢・兼六園 日本武尊像にはなぜ鳥が寄り付かないのか〜ハトに嫌われた銅像〜 | 金沢徒然日記 https://t.co/3TwovscGc9

　余り記憶に自信がなかったので書かずにいましたが、やはり金沢の銅像でした。しかし、兼六園とは思っておらず、違った公園か神社なのかと思っていました。写真を見ると大きな銅像に見えますが、兼六園には宇出津小学校の小学校の修学旅行に行っていますが、見た記憶がないです。

　そういえば、前に日本武尊の銅像を見たときも感じたことですが、服装などがまるで恐怖新聞と同じ作者の「うしろの百太郎」の守護霊のようです。

　テレビの公園などで鳩というのはときどき見かけてきましたが、実生活で鳩を見たという記憶は余りなく、能都中学校の修学旅行で京都、奈良、箱根、東京に行ったときは鳩を見たような気はするのですが、金沢で鳩を見たという記憶はないと思っています。

　兼六園には鳩がいる可能性があるようですが、テレビでよく見る兼六園内の映像で鳩を見た記憶はなく、兼六園というのも平成に入ってからは一度も足を踏み入れていないように思います。昭和56年の終わり頃に撮影したと思われる写真をみると、記憶にはない大きな門の前で撮影していました。

　伊藤たける弁護士は、以前Twitterでアイコンを顔写真にしていましたが、ツイートの内容も教義的で何かの伝道師というイメージがありました。専門は憲法になっていたと思います。教え方が上手というのがあるのかと考えました。

▶（27／47） RT fukazawas（深澤諭史）｜rippy08（りっぴぃ） 日時：2017-03-14 07:12:00 +0900／2017-03-13 15:59:00 +0900 URL： https://twitter.com/fukazawas/status/841411592621236224 https://twitter.com/rippy08/status/841181959791435776
{% tweet 841411592621236224 %}
> 「自由と正義」は労働関係の記事は読むようにしてますよ！あとは刑事系もわりと読んでます。 \n 北先生，野田先生，深澤先生，伊藤先生等々の特集が載った号なんてまだ置いてありますよ！ｗ

　北周士弁護士、野田隼人弁護士、深澤諭史弁護士のことだと思います。ただ深澤という弁護士は調べたところ他にもいるようです。伊藤先生とあるのは、伊藤和子弁護士とも考えられなくはないですが、多くの法クラからは異端者のような扱いを受けている印象があります。

▶（35／47） RT fukazawas（深澤諭史）｜chopitarou（隣のはよせなさん） 日時：2017-09-12 23:13:00 +0900／2017-09-12 22:40:00 +0900 URL： https://twitter.com/fukazawas/status/907608207450763265 https://twitter.com/chopitarou/status/907599710369628160
{% tweet 907608207450763265 %}
> 伊藤のまこちゃん、うさんくさくてあんまりすきやないねんけど、僕が落ちたときに直接頂いたこの言葉だけは強く印象に残ってる。 \n 「はよせなくん、人生において過去の事実は変えようないけど、過去の事実の意味は変えることができますよ。辛い経験は実務に出てから絶対に活きます。頑張ってください」

▶（40／47） RT fukazawas（深澤諭史）｜okuboka（大窪和久） 日時：2018-01-10 17:31:00 +0900／2018-01-10 17:14:00 +0900 URL： https://twitter.com/fukazawas/status/951008598569631744 https://twitter.com/okuboka/status/951004401052745728
{% tweet 951008598569631744 %}
> 先日伊藤塾で行いました明日の法律家講座の講演内容をマガジン９にて記事にしていただきました。　弁護士過疎地域での業務と課題～自分の経験から皆さま方に伝えたいこと　講師：大窪和久氏 https://t.co/uGLnfW7Iy0 #maga9

▶（41／47） RT fukazawas（深澤諭史）｜kfpause（ぱうぜ） 日時：2018-02-07 18:53:00 +0900／2018-02-06 17:42:00 +0900 URL： https://twitter.com/fukazawas/status/961176082245287938 https://twitter.com/kfpause/status/960795794390437888
{% tweet 961176082245287938 %}
> これはすごい内容･･･伊藤建弁護士（行訴の攻撃防御方法）、大島義則弁護士（憲法訴訟）、安井飛鳥弁護士（司法福祉連携）、土橋央征弁護士（少年事件）という充実のラインナップ。 / “金沢大学法科大学院　弁護士特別講義・特別講演会のお…” https://t.co/oUrkZra5g3

▶（47／47） TW fukazawas（深澤諭史） 日時：2019-06-22 22:53:00 +0900 URL： https://twitter.com/fukazawas/status/1142430419792490501
{% tweet 1142430419792490501 %}
> @dareka3 柴田孝之先生の「S式生講義 入門民法1 」がおススメです。民法は、日常に関係する法律ですので。 \n また、読んだことはないですが、伊藤真先生の「伊藤真の法学入門」もいいのではないかと思います。 \n 両先生とも法律を教える… https://t.co/bxTXzmtXlZ

〈〈〈：Emacs： 2019-10-19（土曜日）16：31 　〈〈〈

