#+TITLE: "井戸謙一弁護士の検索から河合弘之弁護士、そして久保利英明弁護士について発見したこと"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-10-16 20:58:40 +0900
FILE_NAME: 2019-10-16-205840_井戸謙一弁護士の検索から河合弘之弁護士、そして久保利英明弁護士について発見したこと.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 久保利英明弁護士,河合弘之弁護士,井戸謙一弁護士
記事タイトル名の文字数：41　保存ファイル名の文字数：63
#+STARTUP: showeverything


* 思い出した丸源ビルの刑事事件、「ヤメ検が20日間で5000万円と言ってきた」：井戸謙一弁護士の検索から河合弘之弁護士、そして久保利英明弁護士について発見したこと
  CLOCK: [2019-10-16 水 21:02]--[2019-10-16 水 22:53] =>  1:51

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 久保利英明弁護士,河合弘之弁護士,井戸謙一弁護士,ヤメ検

〉〉〉：Emacs： 2019-10-16（水曜日）21：02　 〉〉〉

　ちょうどこのエントリーファイルを作成したタイミングで閃くように思い出したのですが、けっこうしっかりと眠っていた記憶でした。今夜は他にも思い出したことが幾つかあります。このファイルで最初に取り上げようと思った吉田拓郎氏の金沢事件のこともそうでした。

[link:]  日刊ゲンダイ|丸源ビル会長が弁護士に要求された金額　「ヤメ検が２０日間で５０００万円と言ってきた」 | 告発-金沢地方検察庁御中_2014 https://hirono2014k.wordpress.com/2014/11/19/%E6%97%A5%E5%88%8A%E3%82%B2%E3%83%B3%E3%83%80%E3%82%A4%E4%B8%B8%E6%BA%90%E3%83%93%E3%83%AB%E4%BC%9A%E9%95%B7%E3%81%8C%E5%BC%81%E8%AD%B7%E5%A3%AB%E3%81%AB%E8%A6%81%E6%B1%82%E3%81%95%E3%82%8C%E3%81%9F/

　上記は、スクリーンショットの画像つきのブログ記事になります。URLに2014年11月19日という情報が見えます。やはりこれが記事の投稿日となっています。時刻の方は情報が見当たりません。WordPressのテーマで、そうなっているのかと思います。

　リンクの元記事を開こうとすると、「gendai.net のサーバーの IP アドレスが見つかりませんでした。」というエラーが出ました。ドメインが廃止となっているようです。日刊ゲンダイの記事となっているので、変更されたドメインは見つけることが出来るかもしれません。

[link:] » 日刊ゲンダイDIGITAL https://t.co/RqohtdBFEh

[link:] » 日刊ゲンダイ 丸源 - Google 検索 https://t.co/zfbVcJGrWv

　ドメインが変わっただけではなく、記事は存在しなくなっているようです。それらしいタイトルがありましたが、よく見ると先程の、過去の自分のWordPressの記事でした。検索結果の1ページ目に、他にそれらしい情報は見当たりません。ネット上から消え去った情報だったようです。

```
「検察は許せん」丸源ビル ８１歳 川本源司郎が上げた怪気炎
http：//gendai.net/articles/view/syakai/141671
2013年3月29日　日刊ゲンダイ


　豊富な資金をバックに検察批判本も出版へ

　検察はまた手ごわい相手を敵に回したのではないか。５億円を払って保釈された「丸源ビル」の川本源司郎オーナー（８１）が２８日、会見を開き、２時間にわたり怪気炎を上げた。そのほとんどが東京地検特捜部と東京国税局の批判。拘置所暮らしの詳細をブチまけた。

［source：］「検察は許せん」丸源ビル ８１歳 川本源司郎が上げた怪気炎 （日刊ゲンダイ）　 赤かぶ http://www.asyura2.com/13/senkyo145/msg/738.html
```

　同じ日刊ゲンダイの前のドメインの記事を引用されていますが、2013年3月29日がその記事の配信日のようです。6年以上になりますが、2013年3月の時点で81歳だったということのようです。

　まだ1年は経っていないという気もするのですが、ふと思い出して丸源ビルの刑事裁判について調べたところ、まだ判決は確定していないという情報を見たように思います。テレビに取り上げられているのを見た記憶もあるのですが、それも2,3年以内であったような気がします。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜jjjhaga（芳賀淳） 日時：2019-10-16 21:28／2013/06/15 21:10 URL： https://twitter.com/kk_hirono/status/1184446118970572806 https://twitter.com/jjjhaga/status/345875901587795968
> 丸源ビル会長が弁護士に要求された金額http://t.co/XAYACIA7wx 私はまあ、１日１０万円として、２０日間（の勾留）でせいぜい、２００万～３００万円と考えていたのだが、『１０００万円』を要求されましたよ。翌日、恩師という元東京高検検事長のヤメ検弁護士と２人で接見に
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-16 21:27／2013/06/16 03:44 URL： https://twitter.com/kk_hirono/status/1184445692091043840 https://twitter.com/hirono_hideki/status/345975186941693952
> ゲンダイネット http://t.co/iAzk5O1xsT 丸源ビル会長が弁護士に要求された金額
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Hideo_Ogura（小倉秀夫） 日時：2019-10-16 21:27／2013/06/15 20:07 URL： https://twitter.com/kk_hirono/status/1184445642040471553 https://twitter.com/Hideo_Ogura/status/345860005045620736
> 大物ヤメケンに頼むと、生粋の弁護士より桁が２つ違うことはよくある。RT @kappamark: ひゃー。。／「丸源ビル会長が弁護士に要求された金額」ゲンダイネット http://t.co/jQ2GaFnZHK
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「丸源」の検索結果 - Twilog https://t.co/mSMZz8Lvao

　1個の餃子のように見えるアイコンだったのですが、拡大してもそのままでした。アイコンよりも実名のような3文字の名前に見覚えがあったのですが、プロフィールに東京弁護士会の弁護士とあります。弁護士としては記憶になかったのですが、リストのは登録済みでした。

　Twilogの検索結果で、私の過去のリツイートとして見つけたツイートです。

```
芳賀淳
@jjjhaga
東京の弁護士です(東京弁護士会)。司法修習42期。早大法学部卒。司法試験、司法修習、弁護士会の広報、中学・高校の司法に関する教育、囲碁、野球などに興味があります。RT：いいねは、賛意の有無とは別です。
東京都港区2010年6月からTwitterを利用しています
794 フォロー中
1,228 フォロワー

［source：］(11) 芳賀淳（@jjjhaga）さん / Twitter https://twitter.com/jjjhaga
```

　ずいぶん久しぶりに見かけたアカウントだと思いますが、他の法クラのタイムラインでリツイートを見かけていない、ということが大きいと思います。ただ、検索のまとめ記事でも見かけていないので、それも少し気になりました。ツイート数が6,7万件と少なくはないからです。

　これもちょっとした縁、あるいはコックリさんのような導きかもしれないので、仮に神様の意思であれば、その流れに沿うかたちで、タイムラインをみながら、気になったツイートをリツイートしておきたいと思います。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜laparkadejapon（アリアンデルの猫） 日時：2019-10-16 22:10／2019/10/10 15:02 URL： https://twitter.com/kk_hirono/status/1184456685940703234 https://twitter.com/laparkadejapon/status/1182174506627952640
> 弁護団組まなくてもできる活動かなって気はしますね。 抗議文出したり学校と面談したりとかなので。 https://t.co/FMXZofNHdT
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜laparkadejapon（アリアンデルの猫） 日時：2019-10-16 22:10／2019/10/10 15:05 URL： https://twitter.com/kk_hirono/status/1184456643091656704 https://twitter.com/laparkadejapon/status/1182175263926276096
> というか、組み体操以外で実際やったことあるんですけどね。 事故発生前での弁護活動なので、モンスターペアレンツだと思われないように動くの大事です。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜jjjhaga（芳賀淳） 日時：2019-10-16 22:10／2019/10/10 15:31 URL： https://twitter.com/kk_hirono/status/1184456465509019649 https://twitter.com/jjjhaga/status/1182181736890847233
> ブラック校則　まずは公開、それから議論を　各地で見直しの動き - 毎日新聞 https://t.co/pwdYbOKiVA
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜jjjhaga（芳賀淳） 日時：2019-10-16 22:09／2019/10/10 15:31 URL： https://twitter.com/kk_hirono/status/1184456439391117312 https://twitter.com/jjjhaga/status/1182181883410407424
> "東京都世田谷区は今秋から区立中学校の校則を学校のホームページで公開する。昨年、区議会で桃野芳文議員が一部の校則を問題視したことがきっかけだった。「肌着、下着は白」「防寒着として、セーターは許可、カーディガンは禁止」「給食中は牛乳… https://t.co/LeKclbvlfX
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hiroloosaki（osakihiroko） 日時：2019-10-16 22:09／2019/10/10 15:56 URL： https://twitter.com/kk_hirono/status/1184456313918480384 https://twitter.com/hiroloosaki/status/1182188016984416257
> 戦時中 焼夷爆弾を落とされ、火災になった時のために、雨水をトイから溜めとくように 天水桶がありました、そこが蚊の発生地、ボウフラがいっぱいでした。ボウフラの発生地 夕方には七輪の上に葉っぱを乗せて 団扇であおいで蚊を追い払う。そし… https://t.co/EIHXSoUOKt
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜laparkadejapon（アリアンデルの猫） 日時：2019-10-16 22:08／2019/10/10 15:46 URL： https://twitter.com/kk_hirono/status/1184456114017955840 https://twitter.com/laparkadejapon/status/1182185606685716481
> 運動会の強制参加的側面が、安全配慮義務違反を高める方向に機能するとは一般に言われるところです。 児童生徒の身体能力に大きなバラつきがあるです。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜iwasisannmasaba（いわしさんまさば） 日時：2019-10-16 22:07／2019/10/11 16:45 URL： https://twitter.com/kk_hirono/status/1184455829996490753 https://twitter.com/iwasisannmasaba/status/1182562904001744896
> 料金を法テラスと比較してくる相談者の多いことよ。法テラスの値段を持ち出してくる時点で，これは駄目だな，と思う。あの値段では受任できません。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜photograshiori（Shiori Ito） 日時：2019-10-16 22:07／2019/10/11 10:14 URL： https://twitter.com/kk_hirono/status/1184455771813101568 https://twitter.com/photograshiori/status/1182464561804275712
> 10/7に結審がありました。ここまで一緒に走ってくれた弁護団、友人と家族、そして支援団体Open the Black Boxを通し支えてくださった皆さまに感謝です。ひとりではここまでくることができませんでした。 判決は12/18日… https://t.co/Ivqbtz0rU8
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜jjjhaga（芳賀淳） 日時：2019-10-16 22:06／2019/10/11 17:59 URL： https://twitter.com/kk_hirono/status/1184455691760615426 https://twitter.com/jjjhaga/status/1182581511112904704
> ”各種事案のなかで「体罰」の件数は圧倒的に多く、6865件に達する。だがそのなかで懲戒免職に該当する件数は1件にとどまっている。暴行により子どもが骨折しようが、その鼓膜が破れようが、過去にも体罰で処分歴があろうが、免職になることは… https://t.co/m82N4V2beL
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜jjjhaga（芳賀淳） 日時：2019-10-16 22:06／2019/10/11 18:00 URL： https://twitter.com/kk_hirono/status/1184455637087834113 https://twitter.com/jjjhaga/status/1182581643439005696
> ”懲戒処分等の件数に占める懲戒免職の割合をみると、その状況はより明確に浮かび上がる。たとえば車の飲酒運転は処分292件のうち154件が懲戒免職（52.7%）、わいせつは処分1070件のうち599件が懲戒免職（56.0%）の処分が下… https://t.co/3HEXb4t2LP
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜1961kumachin（中村元弥） 日時：2019-10-16 22:05／2019/10/11 15:21 URL： https://twitter.com/kk_hirono/status/1184455259470450688 https://twitter.com/1961kumachin/status/1182541691758137350
> 「五・七・五」の神山・若手座談会読んで思うけど、昔の刑事裁判官ってホントに怖かったんだぜ。乙号証なんか不同意にした日には「任意性を争うおつもりか‼️(任意性についての具体的主張をしろよ、ボケ‼️　信用性争うだけなら同意しろ、クソボケ‼️)」と大喝されたんだから
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜YusukeTaira（平　裕介） 日時：2019-10-16 22:05／2019/10/12 21:36 URL： https://twitter.com/kk_hirono/status/1184455205682704384 https://twitter.com/YusukeTaira/status/1182998447357485056
> すごい。とても真似できない……  「小学２年の時に両親が病死し、祖父母に育てられた。新聞配達をして家計を助けた」 「貧富の格差が広がっている現状をなんとかしたい。若者に夢を持ち続けてもらいたい。こうした行動を起こすことで、弁護士仲… https://t.co/5CP5GsyJyG
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜mt_tkms（M T） 日時：2019-10-16 22:04／2019/10/13 00:21 URL： https://twitter.com/kk_hirono/status/1184455144722710528 https://twitter.com/mt_tkms/status/1183039951245438978
> 台風一過の #渋谷センター街 人はいないがネズミだらけ🐀 https://t.co/BAXefsxSwL
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜yasumasa218（新谷泰真） 日時：2019-10-16 22:04／2019/10/12 17:26 URL： https://twitter.com/kk_hirono/status/1184454974496886785 https://twitter.com/yasumasa218/status/1182935646542819328
> 南西諸島の某支部で、建物収去土地明渡請求訴訟が、台風通過後に土地明渡請求訴訟に請求の変更がなされたという逸話を思い出した。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜ohnuki_tsuyoshi（大貫剛） 日時：2019-10-16 22:03／2019/10/13 10:21 URL： https://twitter.com/kk_hirono/status/1184454847916994560 https://twitter.com/ohnuki_tsuyoshi/status/1183190912387579904
> もしかすると、ダムに少しずつ水没していく故郷を毎日見に来ていた人もいたのではないか。一夜にして水没してしまった「奇跡」に、心を痛めているかもしれない。 https://t.co/ZvhBnGl9Rz
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2019-10-16 22:03／2019/10/13 10:30 URL： https://twitter.com/kk_hirono/status/1184454723270668289 https://twitter.com/amneris84/status/1183193310371803136
> デマ情報を流布して名誉毀損を引き起こした件。福岡地検小倉支部が再捜査へ　→東名あおり運転ネットデマ　小倉検察審査会が「起訴相当」 - 毎日新聞 https://t.co/8GWlZwTmn9
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜nextstage_002（こた2） 日時：2019-10-16 22:02／2019/10/13 08:10 URL： https://twitter.com/kk_hirono/status/1184454586804789248 https://twitter.com/nextstage_002/status/1183158065337532416
> 大量のイノシシが増水した利根川から避難してた！！ #台風 #利根川 #堤防 #イノシシ https://t.co/VoHa2yCpW0
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜nextstage_002（こた2） 日時：2019-10-16 22:02／2019/10/13 08:36 URL： https://twitter.com/kk_hirono/status/1184454488536403968 https://twitter.com/nextstage_002/status/1183164469632884738
> 見つけた時はまさかイノシシの大群だとは思わなかった https://t.co/rlQzELBpAu
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜nextstage_002（こた2） 日時：2019-10-16 22:01／2019/10/13 09:05 URL： https://twitter.com/kk_hirono/status/1184454406076370946 https://twitter.com/nextstage_002/status/1183171874739458048
> 親子のイノシシもいた。これまでほとんど見かけたことがなかったのが不思議。こんなにいたのか。 https://t.co/PifMSWYQRo
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kPysyR1lGqu0b7X（ぽてむ） 日時：2019-10-16 21:59／2019/10/13 00:34 URL： https://twitter.com/kk_hirono/status/1184453906539008001 https://twitter.com/kPysyR1lGqu0b7X/status/1183043271544565761
> このツイートをした人が裁判官ならば信憑性は高いが、内心は見えない。  単独事件の右陪席に『部長から今月事件を落とすように言われてて、なんとしても和解してくれませんか？』と泣きつかれたという話を聞いたことあり、なんとも。 ただ、出世… https://t.co/OtLXS8jp4Y
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜tako_ashi（小田嶋隆） 日時：2019-10-16 21:59／2019/10/12 10:20 URL： https://twitter.com/kk_hirono/status/1184453777220235264 https://twitter.com/tako_ashi/status/1182828424550699008
> 台風による公共交通機関の停止ならびに店舗の休業を受けて、ふだん顔を合わせることの少ない家族が一日中狭い部屋の中で過ごすリスクが高まっています。不要な家族喧嘩の勃発や不必要な罵詈雑言の発信に十分気をつけて、命を守る行動に徹してください。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜shouwayoroyoro（らめーん） 日時：2019-10-16 21:59／2019/10/13 03:14 URL： https://twitter.com/kk_hirono/status/1184453688179343361 https://twitter.com/shouwayoroyoro/status/1183083545910079488
> ↓これ、冗談めかしているけど、マジだから。盆暮れ正月に親族間殺人が起こるのと同じ理屈だから。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜which0623（Which） 日時：2019-10-16 21:58／2019/10/13 17:03 URL： https://twitter.com/kk_hirono/status/1184453598580592641 https://twitter.com/which0623/status/1183292249175515138
> 専門部で裁判官が交代したら部の取扱いが変わるというのは普通のこと。 地方の本庁や支部の裁判官は破産や執行は片手間仕事なのであまり口出ししてこないけど、未済が溜まってるときなどに裁判官交代などをきっかけに思いつきを言われることがある。 https://t.co/Og44E9vuY6
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜jjjhaga（芳賀淳） 日時：2019-10-16 21:57／2019/10/14 12:56 URL： https://twitter.com/kk_hirono/status/1184453264789557249 https://twitter.com/jjjhaga/status/1183592369221853184
> 原発事故の除染ゴミが川に流出、保管場浸水　福島・田村：朝日新聞デジタル https://t.co/JnEGnMqTda #台風１９号
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜inst_bio_dgf（雪蛉） 日時：2019-10-16 21:55／2019/10/13 22:41 URL： https://twitter.com/kk_hirono/status/1184452882306744320 https://twitter.com/inst_bio_dgf/status/1183377337355620352
> 八ツ場ダムが脚光浴びてますが、今回の台風で超活躍した人工調水施設の1つが、新潟県・信濃川の大河津分水路(赤丸)。信濃川本流の水を可動堰によって分流し、水を日本海に捨てています。中流は氾濫危険水位(黄色)なのに、下流域の水位は保たれ… https://t.co/vOk968xfPp
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜jjjhaga（芳賀淳） 日時：2019-10-16 21:55／2019/10/14 16:24 URL： https://twitter.com/kk_hirono/status/1184452814107332608 https://twitter.com/jjjhaga/status/1183644815029719040
> 台風避け長野へ「疎開」した記者　想定外の避難と油断：朝日新聞デジタル https://t.co/XzgemjXEak #台風１９号
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜jjjhaga（芳賀淳） 日時：2019-10-16 21:55／2019/10/14 16:25 URL： https://twitter.com/kk_hirono/status/1184452705504264192 https://twitter.com/jjjhaga/status/1183645073365299200
> ”今回、メディアの注目はもっぱら「首都圏直撃」だった印象が強い。つい最近、千葉で台風の猛風によって大きな被害が出ただけに、雨よりも「６０メートル級」など風の強さに私の関心が引っ張られていたのも否めない。台風の進路の左側にある長野県… https://t.co/PBJmIXPYyY
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜shouwayoroyoro（らめーん） 日時：2019-10-16 21:54／2019/10/14 10:33 URL： https://twitter.com/kk_hirono/status/1184452549899739136 https://twitter.com/shouwayoroyoro/status/1183556360652251137
> 修習生のころ、元イソ弁先に「ここで働かせてください」と言った。憧れの弁護士から「机を置く場所がないからねえ」と言われ、お話していただけたことで舞い上がり「ゴザでいいです！イソ弁、ノキ弁ではなく、ゴザ弁！いかがでしょうか⁈」と返した。今考えると、あれ、断られていたんだなあ。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Nasu0327Info（那須雪崩事故遺族･被害者の会） 日時：2019-10-16 21:53／2019/10/14 16:10 URL： https://twitter.com/kk_hirono/status/1184452381615878144 https://twitter.com/Nasu0327Info/status/1183641139468914691
> 学校に事故の慰霊碑をつくる話をされた。 しかし内容があまりにひどい。  ・碑に死亡した者の名前は記さない ・大田原高校は被害者なので事故の反省は記さない ・負の遺産にはしたくないので前向きな誓いだけを記す  なんのための慰霊碑か？… https://t.co/d9DFaYhjEY
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜KazuFujiki（弁護士藤木和子（大人になったきょうだい児・聞こえる兄弟姉妹＝SODAソーダ）） 日時：2019-10-16 21:53／2019/10/13 07:31 URL： https://twitter.com/kk_hirono/status/1184452205455167488 https://twitter.com/KazuFujiki/status/1183148256399724544
> 私は、弁護士になり、結婚してようやく人並みになれたと思ったし（マイナスからゼロに）。きょうだいの活動で良い出会いがあってようやくプラスを感じられるようになったわ。だからって、他人から #きょうだい児 で良かったねと言われるのは嫌で… https://t.co/dh9bAobnTe
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜jmjhjmwtad（弁護士7286） 日時：2019-10-16 21:52／2019/10/14 18:44 URL： https://twitter.com/kk_hirono/status/1184452123938811904 https://twitter.com/jmjhjmwtad/status/1183680078049247232
> ロー卒が法曹の多くを占めるようになってきたのでローをディスっても意味ないという言説は、戦争を知らない世代が大半になってきたので、戦争が悲惨だと言っても共感を得られない、と大して変わらんわね。あの改革、個人の感想抜きに政策としては間違いない失政なんで永久に批判せんとあかんと思うよ。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kankimura（Kan Kimura） 日時：2019-10-16 21:51／2019/10/14 21:24 URL： https://twitter.com/kk_hirono/status/1184451894665568256 https://twitter.com/kankimura/status/1183720238304526336
> 「いだてん」録画視聴。終戦前後の満州の状況についての描写はかなり真に迫っていた。とはいえ、大連の状況はもっと緊迫していた筈であり、とりわけ日本軍や日本社会や日本人女性を犠牲にした話はもっと過酷だった、と理解している。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kankimura（Kan Kimura） 日時：2019-10-16 21:51／2019/10/14 21:47 URL： https://twitter.com/kk_hirono/status/1184451802005028864 https://twitter.com/kankimura/status/1183726094320467968
> 朝鮮にしても台湾にして「日本軍が逃げてしまった後の日本人居留民」は本当に悲惨で、様々な経験が残されている。そういう意味では、この経験を「日本人の側から描いた」ドラマは結構貴重かも。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜mayukotaniguchi（まゆこ） 日時：2019-10-16 21:50／2019/10/15 00:59 URL： https://twitter.com/kk_hirono/status/1184451662083002369 https://twitter.com/mayukotaniguchi/status/1183774405685497856
> 修習生で妊娠したとき、「どんなに細々とでも仕事を続けなさい。でないと、二度と戻れなくなるから」と言ってくれた検察教官(女性)に心から感謝しています。 https://t.co/fHpKWIYr4l
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜miura_hideyuki（三浦英之　「牙」が本屋大賞ノミネート） 日時：2019-10-16 21:50／2019/10/13 17:28 URL： https://twitter.com/kk_hirono/status/1184451447867396097 https://twitter.com/miura_hideyuki/status/1183298534935846913
> 福島県田村市、原発事故の除せん廃棄物を詰めたフレコンバッグが流出した現場です*1 https://t.co/Z2WMogZzPu
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hayano（ryugo hayano） 日時：2019-10-16 21:47／2019/10/15 05:34 URL： https://twitter.com/kk_hirono/status/1184450733866807296 https://twitter.com/hayano/status/1183843552402522119
> （日経ビジネス）教育劣化どこまで　社会に出て「引き算」を習う大人たち  https://t.co/CIWkTthZAs  日本の競争力はついに世界30位まで転落 https://t.co/RIrbcjBr9I
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜asahi_school（朝日新聞教育班） 日時：2019-10-16 21:46／2019/10/15 08:51 URL： https://twitter.com/kk_hirono/status/1184450620817756161 https://twitter.com/asahi_school/status/1183893127293108224
> 台風１９号で、文部科学省が把握できているだけで全国１０県の学校６７８校に被害が出ています。１５日は少なくとも２３５校が休校になる模様です。#台風１９号　#休校　#学校被害https://t.co/lJSnisZV3g
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜shizuben（静岡県弁護士会【公式】） 日時：2019-10-16 21:45／2019/10/15 16:30 URL： https://twitter.com/kk_hirono/status/1184450368270299136 https://twitter.com/shizuben/status/1184008578400583688
> 🔔台風19号の被害に遭われた皆様へ、よくあるＱ＆Ａや支援制度をまとめた「静岡県弁護士会ニュース台風19号水害編」を作成しました。印刷配布自由ですのでご活用ください。今般の被害に関する弁護士会へのご相談も無料で受け付けております。法… https://t.co/BItZJtP39h
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜sho_ya（shoya） 日時：2019-10-16 21:45／2019/10/15 18:50 URL： https://twitter.com/kk_hirono/status/1184450321596071936 https://twitter.com/sho_ya/status/1184043946550288384
> 刑事弁護にご興味がおありの方は、カルロス・ゴーンさんの弁護人である高野隆先生の対談『ゴーンさんの保釈はどのように獲得したのか』（季刊刑事弁護100号144頁以下）をお読みになると有益かと存じます。東京地検特捜部ご出身の弁護人の対応の問題点、実際の書面内容等が記されています。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜nabeteru1Q78（渡辺輝人） 日時：2019-10-16 21:45／2019/10/13 18:11 URL： https://twitter.com/kk_hirono/status/1184450214188371969 https://twitter.com/nabeteru1Q78/status/1183309253194350593
> 安倍首相が災害の早い時期にテレビの前に顔を出さないのは、アドリブが効かなくて炎上するのを防ぐのと、特定の災害と自分のイメージが重なるのを防ぐためでは。あれだけプロンプターの原稿読みと、仕込み質問が大好きな人だから、アドリブが効かないのは自覚あるだろう。けだしメデイア対策政権。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜koudachinaoki（神立尚紀） 日時：2019-10-16 21:44／2019/10/16 01:34 URL： https://twitter.com/kk_hirono/status/1184449980985012224 https://twitter.com/koudachinaoki/status/1184145532614131718
> 東條英機を激怒させた「竹槍事件」で知られる毎日新聞の新名丈夫記者には身寄りがなく、遺品の多くは親交のあった元一航艦副官門司親徳主計少佐が預かり、門司さん没後は私のところにあるのだけど、貴重すぎてなかなか整理ができない。高木惣吉少将… https://t.co/tXaxspO6yp
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜1961kumachin（中村元弥） 日時：2019-10-16 21:43／2019/10/16 12:56 URL： https://twitter.com/kk_hirono/status/1184449740970217472 https://twitter.com/1961kumachin/status/1184317066817363968
> 地方は、増員して都会にあぶれたから田舎に行く、という人材を否定はしないが、本当に欲しいのは積極的に来たい、将来その会を牛耳りたいくらいの変わり者 https://t.co/3ZFycgC6WV
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜okinahimeji（櫻井光政） 日時：2019-10-16 21:43／2019/10/16 17:26 URL： https://twitter.com/kk_hirono/status/1184449713099001856 https://twitter.com/okinahimeji/status/1184384998440198146
> @1961kumachin 裁判官を辞めて地方会に弁護士登録して、過疎解消の音頭取りをして、その会の会長になるような人材でしょうか。皮肉でなく、同感です。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜nhk_news（NHKニュース） 日時：2019-10-16 21:42／2019/10/16 19:52 URL： https://twitter.com/kk_hirono/status/1184449616583876608 https://twitter.com/nhk_news/status/1184421739767296000
> 【速報 JUST IN 】東京五輪 マラソン・競歩「札幌での実施を検討」ＩＯＣ発表 #nhk_news https://t.co/1vtO2Jny0z
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜RyuichiYoneyama（米山　隆一） 日時：2019-10-16 21:42／2019/10/16 10:41 URL： https://twitter.com/kk_hirono/status/1184449578755452930 https://twitter.com/RyuichiYoneyama/status/1184283142292557824
> 今どき「恩赦」なんて要りますかね？「天皇陛下の御威光を示す」的な極めて前時代的で無意味な行為に見えます。象徴天皇制の現代においては即位における恩赦はしないとした方が、私はいいと思います。 https://t.co/yzsrxpv4wq
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜wakatelaw（若手弁護士Ｂ） 日時：2019-10-16 21:42／2019/10/16 13:32 URL： https://twitter.com/kk_hirono/status/1184449553560301569 https://twitter.com/wakatelaw/status/1184326143337328640
> 最近、無意識で、面倒そうな相談者に「色んな考え方があると思うので、別の弁護士さんに聞いてみても良いのでは…」と言ってクローズしていた。独立当時は「逃すか」「絶対受任」という気持ちで言うはずなかったけど、受けたら受けたで大変で…まさに「お金の問題ではない」ことに気付いた。
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 早野龍五事務所 https://t.co/fJ3kYBwd7V

[link:] » 早野龍五 プロフィール https://t.co/FYx7f8mxcE \n 早野龍五プロフィール \n 名前　　　早野龍五（はやのりゅうご） \n 生年月日　1952年1月3日 \n 本籍地　　岐阜県大垣市 \n 住所　　　東京都渋谷区 \n 現職　　　合同会社 早野龍五事務所代表社員

　告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)でログインした状態だったので、ブロックされているアカウントのツイートはリツイートされていても、表示がなかったと思います。

　最後にリツイートをしたツイートは、次の深澤諭史弁護士のツイートを公式引用していました。けっこう印象的で強い問題意識を感じた深澤諭史弁護士のツイートだったのですが、すっかり忘れていました。10月10日午後2時58分のツイートとなっています。

fukazawas ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW fukazawas（深澤諭史） 日時：2019/10/10 14:58 URL： https://twitter.com/fukazawas/status/1182173612721065984
> 「組体操弁護団」とかできたらいいかも。 \n 保護者・児童生徒を代理して中止を求めるとか。 \n （・∀・；）
▷▷▷　　　　　End　　　　　▷▷▷

　この組み体操の問題で、「子どもが好きな神様」を含むエントリーを作成したように思いますが、その点はまだ手付かずだったかと思います。今年の3月の終わり頃のことになりますが、この3月は、性犯罪の無罪判決が集中し、法クラの弁護士らが活況を呈していました。

[link:] » 丸源ビル　裁判 - Google 検索 https://t.co/MWxWrXpFo1

　上記のGoogle検索は、オプションで1年以内を指定しています。2019年のページが見当たらないのですが、次の１つだけが2019年1月6日となっているようです。

[link:] » 「銀座の不動産王」丸源ビルのオーナー・川本源司郎氏に起きたこと | 再エネ投資ナビ https://t.co/wjQANIy4xS

　2018年11月20日に懲役4年・罰金2億4000万円が東京地裁で出たとのことです。初公判からおよそ5年とありますが、近年ではかなり珍しい長期裁判のように思われます。高裁の判決が出ているのかと思っていたのですが、控訴にも触れずに記事は終わっているようです。

　控訴審の場合、即日結審というのも多いと聞きます。裁判の引き伸ばしが被告人と弁護士の目的にも思えるのですが、控訴審のニュースがないのであれば、それもなぜかと気になるところです。今の時代、一審だけで5年の審理というのは、それだけでもずいぶん異例のことかと思われます。

[link:] » 丸源　控訴 - Google 検索 https://t.co/974StjmasX

[link:] » 法人税法違反：「丸源ビル」オーナーが控訴 - 毎日新聞 https://t.co/GXLcZE9yyX

　同じく1年以内の検索です。控訴は2018年11月30日で、上記の毎日新聞の有料記事もその日の配信となっています。86歳ともあります。懲役4年であれば3年ほどで社会に戻ってこれそうな気もしますが、服役が遅くなれば、社会に戻ってこれないまま人生を終える可能性が高まりそうです。

　さきほどの一審の記事でも、弁護人の弁護士が何度か変わったような情報を見かけたように思いますが、弁護士の名前というのは一度も見かけたことのない裁判です。最初から裁判を長引かせないで入れば、量刑が短くなっていた可能性もあり、懲役4年でも今頃は社会に戻っていたかもしれません。

　判決を確定させず服役もしないまま天寿をまっとうするというのが被告人の望みなのかもしれず、だとすれば金に糸目も付けずに弁護士に依存する可能性もありそうです。マスコミに報道をしないように働きかけているとは考えにくいですが、どんなものかと深く考えます。

　つい数日前も、モトケンこと矢部善朗弁護士（京都弁護士会）がマスコミを厳しく批判するようなツイートをしていたように思います。新規のまとめ記事とともに、ちょっと取り上げておこうと思います。

〈〈〈：Emacs： 2019-10-16（水曜日）22：53 　〈〈〈

* 「マスコミ」と「報道」をキーワードにしたモトケンこと矢部善朗弁護士（京都弁護士会）のツイートの記録（期間指定なしと過去30日以内）
  CLOCK: [2019-10-16 水 23:18]--[2019-10-17 木 02:47] =>  3:29

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: モトケンこと矢部善朗弁護士（京都弁護士会）,マスコミ,報道,まとめ記事

〉〉〉：Emacs： 2019-10-16（水曜日）23：18　 〉〉〉

[link:] 2019年10月16日22時55分の登録： REGEXP：”マスコミ”／モトケン（@motoken_tw）の検索（2010-03-02〜2019-10-09／2019年10月16日22時55分の記録953件） http://hirono2014sk.blogspot.com/2019/10/regexpmotokentw2010-03-022019-10.html

[link:] 2019年10月16日22時55分の登録： REGEXP：”報道”／モトケン（@motoken_tw）の検索（2008-12-13〜2019-10-15／2019年10月16日22時55分の記録1147件） http://hirono2014sk.blogspot.com/2019/10/regexpmotokentw2008-12-132019-10.html

[link:] 2019年10月16日22時56分の登録： REGEXP：”報道”／モトケン（@motoken_tw）の検索（2019-09-20〜2019-10-15／2019年10月16日22時56分の記録11件） http://hirono2014sk.blogspot.com/2019/10/regexpmotokentw2019-09-202019-10.html

[link:] 2019年10月16日22時56分の登録： REGEXP：”マスコミ”／モトケン（@motoken_tw）の検索（2019-09-24〜2019-10-09／2019年10月16日22時56分の記録2件） http://hirono2014sk.blogspot.com/2019/10/regexpmotokentw2019-09-242019-10.html

　上記4件のまとめ記事を作成中か作成した直後になりますが、テレビの報道ステーションで、これまでのマスコミや報道の概念を揺るがすようなニュースを２つ続けて見ました。1つ目は割とありがちな問題ではありましたが、表面化した経緯が気になるものでした。

　2つ目は、性犯罪と時効に関するニュースで、夕方だったと思いますがニュースとして記事を１つ読んでいました。きっかけも弁護士のツイートだったように思いますが、普段以上にあちこちのツイートを見ていたので、どこで見たものか思い出せなくなっています。

　なお、報道ステーションでは時効についてはほとんど触れていなかったかもしれません。有罪判決の報道だけならさほど驚くことはなかったのですが、性犯罪の被害者が顔出しに近い状態で、家の中や子どもの姿が撮影され、音声の加工はなかったと思うので、見る人がみれば特定できるものでした。

　マスクをしていましたが、裁判所から出てきた、被告人と思われる男性も撮影されていました。2,3人の弁護士が同行しているようにも見える映像でしたが、実名が出ていたので、見る人がみれば被害者やその家族も特定されそうな情報でした。

　記録を作成中ですが、ネットのニュース記事では、時効のことをより重視しているような内容となっていました。弁護士らは免訴を求めていたとのことですが、公訴時効を左右する最後の犯行日が特定されないままの有罪判決となったようです。

　モトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインのツイートは、3時間前の午後7時49分のツイートで止まっています。公訴時効の認定も刑事弁護士としては大きな問題かと思いますが、報道のやり方や報道に関する考えが真逆の方向性とも思えます。黙っているのか注目です。

▶（1／2） TW motoken_tw（モトケン） 日時：2019-09-24 06:41:00 +0900 URL： https://twitter.com/motoken_tw/status/1176250219098329088
{% tweet 1176250219098329088 %}
> 日本の大臣というのは（外国の実情は知らんけど）、所管事項に関する知識とか理解とか見識とか政策とかが何もなくても総理大臣が任命すればなれてしまう。 \n こういうところはマスコミが（自分自身が言ってるように）きちんと批判しなければいけないのだが、マスコミ自体に何もないから無理かな。

　モトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインのツイートは、ほとんど目を通しているつもりでしたが、上記の9月24日のツイートは、見ていなかったように思います。日本の大臣を厳しく論いながら、マスコミを挑発するような物言いであります。

▶（2／2） TW motoken_tw（モトケン） 日時：2019-10-09 12:36:00 +0900 URL： https://twitter.com/motoken_tw/status/1181775541143134208
{% tweet 1181775541143134208 %}
> @okinahimeji @KotaroTanabe @wata_nabekyo_ko @o2441 （一般向けです。） \n 検察庁内部ではもちろん、マスコミ関係でも「高検長」という言葉は聞いたことも見たこともありません。 \n 「検事長」… https://t.co/LtWA8tO61s

　中途半端に取り上げていた問題のツイートの１つです。10月9日12時36分のツイートですが、これもすっかり忘れていました。埋め込みツイートでは櫻井光政弁護士のツイートの返信として表示されていますが、４つのアカウントを返信先としています。

［link：］ なべきょう＠過眠症(@wata_nabekyo_ko) - Twilog https://twilog.org/wata_nabekyo_ko

　深澤諭史弁護士と同じくTwilogの登録がありませんでした。この女性弁護士も高検長の問題で刺激的な返信をしていましたが、法務省か何かの合同庁舎に通報の連絡をしたようなツイートもしていました。施設内をみだりに撮影したということのようでした。

　時刻は10月17日の0時5分となっていて、日付が変わったので一昨日ということになりますが、この「なべきょう＠過眠症」というアカウントが、以前、法律事務所の紹介ページで顔写真まで載せていた女性弁護士だったと知り、けっこう驚きました。

　なべきょう、というのも変わったハンドル名ですが、女性弁護士であることに疑問はなかったと思います。Twitterのアイコンが、朱肉で押した判子のようになっているので、それだけでも特徴的で目立つアカウントでした。

　当日に奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)のアカウントで確認をしましたが、そちらはやはりブロックを受けていました。告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)はされていなかったかもしれません。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜wata_nabekyo_ko（なべきょう＠過眠症） 日時：2019-10-17 00:11／2019/10/15 11:55 URL： https://twitter.com/kk_hirono/status/1184486994396598272 https://twitter.com/wata_nabekyo_ko/status/1183939372627836928
> 【長野県で被災された方へ】長野県弁護士会でも相談窓口の準備中です。数日お待ちください。 どうしても緊急の方、ＤＭいただければ対応しますのでご連絡ください。メールにつき最低限のご対応になることをご了承ください。 丘の上ながの法律事務所　弁護士渡邉恭子
▶▶▶　　　　　End　　　　　▶▶▶

　やはり現時点で告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)のアカウントは、ブロックをされていませんでしたが、上記にリツイートしたツイートは、固定されたツイートです。

　同じ日の、夕方だったと思うのですが、確か静岡県の、実名弁護士で、お祭りの山車をTwitterのヘッダ画像の写真にした、顔出しアイコンのアカウントで、そちらも同じく被災関係の弁護士会の広報のようなツイートだったのですが、リツイートに失敗しました。

　奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)のアカウントでしたが、やはりブロックをされていました。そちらの方は、ブロックされるような心当たりもなくて、真面目そうな弁護士だったので、いくらかショックを受けましたが、それも現実として受け止めました。

　固定されたツイートを別にすると、次のリツイートが「なべきょう」の最新ツイートとなっていますが、この「くまえもん」というアカウントは、しっかりブロックされていることの心当たりがあるアカウントの１つです。問題性を感じるツイートも少なくありません。

kumaemon9 ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW kumaemon9（くまえもん） 日時：2019/10/16 20:04 URL： https://twitter.com/kumaemon9/status/1184424926578499584
> ようやくIOCが俺に追いついたか https://t.co/0j7BMH8weA
▷▷▷　　　　　End　　　　　▷▷▷

　自分の過去のツイートを公式引用しています。Twilogの登録もしていなそうな垂れ流し系の弁護士アカウントというイメージがあるのですが、2018年2月10日ツイートとなっています。Twilogはこのあと確認します。

kumaemon9 ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW kumaemon9（くまえもん） 日時：2018/02/10 10:44 URL： https://twitter.com/kumaemon9/status/962140122379468800
> 今からでも遅くない。東京五輪のマラソンは札幌市に土下座してお願いするか、午前3時スタートにすべき。
▷▷▷　　　　　End　　　　　▷▷▷

```
このユーザーはTwilogに登録されていません

最新100件のツイートのみを表示しています。
自動的にツイートを記録するには、こちらから新規登録してください。
現在表示されているツイートは、取得してから1時間だけTwilogのサーバに保持されます。最新のツイートを取得したいときは、右上の「最新の情報に更新する」ボタンを押してください。

［source：］くまえもん(@kumaemon9) - Twilog https://twilog.org/kumaemon9
```

　やはり、深澤諭史弁護士、なべきょう、とともにTwilogの登録はありませんでした。

```
くまえもん
@kumaemon9
自称弁護士／ #倒産メモ ／ #プリコネR 全95キャラコンプ勢／ #DQウォーク
1ばつ100かいだてのいえ2010年5月からTwitterを利用しています
1,356 フォロー中
2,509 フォロワー

［source：］くまえもん（@kumaemon9）さんの返信があるツイート / Twitter https://twitter.com/kumaemon9/with_replies
```

　Twitterのプロフィールに自称弁護士としていますが、次のツイートを固定ツイートとしています。弁護士というだけではなく、倒産事件処理のエキスパートをにおわすような内容のツイートです。

kumaemon9 ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW kumaemon9（くまえもん） 日時：2019/09/18 14:08 URL： https://twitter.com/kumaemon9/status/1174188364226076673
> #倒産メモ は、弁護士による倒産事件処理に関して、盲点になりがちな知識やあまり知られていないノウハウなどを不定期でツイートすることにします。みなさんもどうぞ。
▷▷▷　　　　　End　　　　　▷▷▷

　次は、くまえもんのTwitterで、おすすめツイートとして出てきた３つのアカウントの１つです。これも確実にブロックされている系の弁護士アカウントです。よく見るとプロフィールには「田舎者」と書いてあるだけですが、弁護士らしいツイートが多いかと思います。けっこう記録済みです。

GUv4i6 ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW GUv4i6（北白川） 日時：2019/10/16 22:14 URL： https://twitter.com/GUv4i6/status/1184457675905495043
> ゼルダの伝説夢を見る島を、娘と一緒に少しずつやってたんだけど、今日、全クリした（落語によくある夢オチ）んだけど、娘なんか寝る前に思い出して泣き出しちゃった。ヒロインとか全部主人公の夢で消えてなくなったとおもったら悲しくなったらしい
▷▷▷　　　　　End　　　　　▷▷▷

　このような子煩悩な弁護士のツイートというのもときどき見かけます。家族のために頑張って仕事をしているのかと思いますが、弁護士という仕事の今後について、もっと現実に向き合った方がよさそうな気がします。私はそのための情報提供、情報公開をしている一面があります。

［link：］ 北白川(@GUv4i6) - Twilog https://twilog.org/GUv4i6

　こちらの北白川というアカウントもTwilogの登録がありませんでした。深澤諭史弁護士ほど社会に影響を与えかねないツイートを沢山、垂れ流していなければ、別段Twilogの登録は必要ないかとも思いますが、その場その場のツイートの垂れ流しというのは、弁護士という職業として疑問です。

　Twitterの検索で探すツイートが見つかることもありますが、検索の精度がずいぶんと悪い上、Twilogに比較すると時期を特定して探すのも困難で、何かと非効率を強いられます。過去にどのような発言をしてきたアカウントなのか確認するのも困難、不十分となります。

　自分の都合しか考えないところが、まったく弁護士らしい認知行動パターンとは思います。

▶（01／11） TW motoken_tw（モトケン） 日時：2019-09-20 15:25:00 +0900 URL： https://twitter.com/motoken_tw/status/1174932617919004672
{% tweet 1174932617919004672 %}
> @yotajirosan 個人的には、報道された情報に基づくものですが、有罪になってもいい、と思ってました。 \n ただし、現在の過失犯論では無罪だろうなとも。 \n 訴因構成を知らないのですが、断片的な判決報道から憶測して、訴因構成が適切だったのかな、という疑問があります。

　見覚えのある内容のツイートでしたが、「有罪になってもいい」としながら、なんの裁判のことなのか検討がつきませんでした。上記のツイートを個別に開くと、流れの上に、アンケート結果が気になりながら忘れていたツイートを発見しました。東電元経営陣の無罪判決でした。

motoken_tw ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW motoken_tw（モトケン） 日時：2019/09/20 10:52 URL： https://twitter.com/motoken_tw/status/1174863784361353221
> 東電元経営陣に対する裁判で、有罪判決を予測していた法律家はどれくらいいるかな？ \n ツイッターの法クラアカウントに判決前の予測についてアンケートをとってみる。 \n ご意見のある方はリプ欄に。 \n 法クラ限定でお願いします。
▷▷▷　　　　　End　　　　　▷▷▷

　法クラ限定としているモトケンこと矢部善朗弁護士（京都弁護士会）のアンケート付きツイートですが、172票が最終結果となっています。リツイートは18件、いいねは11件です。

　ご意見の方は法クラ限定とはしていないように読めます。172票というのは少ないと感じましたが、弁護士や法律家が172人と考えると、けっこうな数です。

　0時58分で日付は変わっていますが、今朝は用事があって7時にアラームで起きていました。寝た時間も遅かったのか、夕方には疲れも出て眠かったのですが、だんだんと疲れも消えて眠気もなくなりました。気分の切替もあるので、今夜は早めに寝るつもりでした。

　用事というのは松明のことだったのですが、いろいろとどのように伝え、記録を残していこうかと判断に迷うところもあります。それでも今回の用事が終わったことは、一段落なのでけっこう大きいです。

　このあと、用事ではないですが予定があります。そのあとに書いておきたいこともいくつかあります。そちらも一つの区切りや節目になると思います。

▶（02／11） TW motoken_tw（モトケン） 日時：2019-09-21 15:17:00 +0900 URL： https://twitter.com/motoken_tw/status/1175292865452240896
{% tweet 1175292865452240896 %}
> @silvergriffin18 判決以前に、起訴の内容が妥当だったかどうかが気になっております。 \n 報道を見る限り、はっきり言って（検察官役の弁護士が）無罪にしてくれと言ってるような印象を受けてます。起訴状を読んでませんけどね。

　そういえば、ここ数年、起訴状をネットで見たことがないですが、起訴状というのは、おそらく一般の人が想像できないような簡潔なものだと思います。それでも公訴事実という記載はあったかもしれないですし、関係者が多ければ、それなりに長文となっている可能性はありそうです。

　起訴状については、元検事でもあるモトケンこと矢部善朗弁護士（京都弁護士会）がよく知っているはずですが、何故、起訴状としたのか、起訴状は公開されて読めるものなのか疑問に感じました。弁護人である弁護士が起訴状を公開したというのも見たことがないように思いました。

▶（03／11） TW motoken_tw（モトケン） 日時：2019-09-26 11:11:00 +0900 URL： https://twitter.com/motoken_tw/status/1177042903903793152
{% tweet 1177042903903793152 %}
> 証拠隠滅の原因になりかねない報道だな。 https://t.co/tWkg5nEimw

　次のツイートを公式引用しています。この事件も一時期過熱気味の報道があったものの、ピタリとやんで、すっかり忘れていました。謎の多いドラマのような殺人事件として報道がされていました。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Sankei_news（産経ニュース） 日時：2019-10-17 01:17／2019/09/26 11:02 URL： https://twitter.com/kk_hirono/status/1184503564191723520 https://twitter.com/Sankei_news/status/1177040643303981057
> 【茨城殺傷事件】 「襲ったのは男」と長男 https://t.co/rwfsABEwla  　→両足と腕を切られて重傷を負った中学１年の長男（１３）が、背格好から、襲ったのは「男だった」と話している 　→敷地内では、家族の靴以外による足跡も見つかっている
▶▶▶　　　　　End　　　　　▶▶▶

　確かに、このような目撃証言が覆されて無罪となるのはドラマで見たことがあります。日曜劇場『99.9－刑事専門弁護士－』もそうだったと思いますが、服装の色が違って見えたとか、弁護士が追求をするやつです。

　この茨城の民家での殺人事件は、現場の状況がかなり特異なもので、報道により地域住民の不安も解消されつつあるという印象でしたが、防犯設備の薄い場所を狙った押し込み強盗のような見立ても当初はされていたと思います。

　この事件の報道で何より印象的だったのは、事件から早い段階の報道で被害者の家族が関わりを持たずそっとしてくれと言ったような報道でした。これは1回、１つだけたまたま見たように思うテレビのニュースだったと思います。

　この茨城の殺人事件では、父親と母親が侵入者に殺害され、2階にいた子どもが2人、怪我をさせられたとなっていたと思います。確か21歳の長女、が一人1階で寝ていて無事だったという報道は繰り返しなされていました。

　いきなりの侵入者に両親を殺害された3人の子どもが、ショックを受け取材を受けたくないという気持ちは理解が出来ましたが、事件の早期解明がなによりの不安の解消にもなるのではと思いました。つまりしゃしゃり出てきた弁護士が、報道の主導権を握ろうと、入れ知恵をしてきた可能性を想定しました。

　中学1年の長男の話というのは、長男がマスコミに話したものなのか、聞き取りをした警察官がマスコミに伝えたはなしだったのかよくわからなかったですが、これをいきなり証拠隠滅の原因などと難癖をつけるのも、万事につけ主導権を握り、操作したくなる弁護士の野獣のような習性と感じます。

▶（05／11） TW motoken_tw（モトケン） 日時：2019-09-30 10:31:00 +0900 URL： https://twitter.com/motoken_tw/status/1178482417935323136
{% tweet 1178482417935323136 %}
> 「歴史の事実に目を背ける者に、未来は語れない。」 \n \n 「過去の反省なしには、未来を論じることはできない。」 \n \n 結局、歴史問題を理由とする反日報道になるんじゃないのかな？ https://t.co/dOBdisAP7K

　ポエムのようなモトケンこと矢部善朗弁護士（京都弁護士会）のツイートですが、公式引用してあるツイートに引用された記事の内容の一説のようでもあります。「」で括ってある部分は、たぶんそうなのでしょう。

▶（06／11） TW motoken_tw（モトケン） 日時：2019-10-08 07:00:00 +0900 URL： https://twitter.com/motoken_tw/status/1181328548411269120
{% tweet 1181328548411269120 %}
> @prewarwrestler @popohito @AbeShinzo もしも萎縮しているのなら、劣化しているのは報道機関。

　これもモトケンこと矢部善朗弁護士（京都弁護士会）らしさ前回の、煽り系、挑発系のツイートと感じました。返信を入れているのは、おそらく菅野完という森友学園問題で脚光を浴びた人物の実名をもじっていますし、その人物の顔写真も使っているようです。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜prewarwrestler（菅野感） 日時：2019-10-17 01:45／2019/09/29 10:42 URL： https://twitter.com/kk_hirono/status/1184510609460617216 https://twitter.com/prewarwrestler/status/1178122796620107776
> 先ほどメルマガを一本送信しております。 タイトルは「劇薬に手を出したらそりゃ体は壊れますわな号」  今回の内閣改造で目立つ「警察官僚の重用」についての考察です。おそらくこの人事で、いろんな意味で「死ぬ」人が増えるでしょうなぁ。… https://t.co/ijgKF8l2kC
▶▶▶　　　　　End　　　　　▶▶▶

　前回は確認も不十分だったのですが、プロフィールには「うーん。なかなか菅野感あるよねぇ〜。」とだけあるので、菅野完氏本人ではなさそうです。しかし、上記にリツイートしたツイートは固定されたツイートで、菅野完氏本人のメルマガか記事を紹介しているようです。

　このような本人なのか間際らしいアカウントは、岡口基一裁判官のなりすましアカウントと似ていますが、そちらは本人であることをプロフィールで否定し、岡口基一裁判官本人のFacebookの投稿をそのまま転載していると断り書きがありました。

　モトケンこと矢部善朗弁護士（京都弁護士会）の返信のツイートの内容をみると、菅野完氏本人のツイートを前提にしているように読めます。知らない人が多いと思いますが、菅野完氏はTwitterから他に例を見ないほどの完全凍結を受けた経緯があり名前をそのまま使えない可能性は高いと思います。

　何があったのかわからないですが、菅野完氏らしい名前や顔写真をネットでみたのもずいぶん久しぶりのことでした。菅野完氏のメルマガから転載をしているなどとプロフィールに断りがあればまだしも、本人と無関係であれば、本人にも悪影響が出そうな気がします。

　著名人のなりすましアカウントというのは、かなりの数があると数年前に情報を見かけたことがありましたが、最近はTwitterの規制が厳しくなって強制的なアカウントの削除が行われているのかもしれないですが、なりすましを疑うものは見かけなくなっていたので、けっこう戸惑いました。

[link:] » Twitter永久凍結の常連 菅野完氏 6日で永久凍結(再開未定) ネットの反応 - Togetter https://t.co/mB4EhWwXxW

　調べると、「菅野完 ツイッター 凍結 2019」がGoogleの検索の候補に出て、上記のTogetterが見つかりました。

```
菅野観察日記わんだ @suganoniki
菅野完氏アカウント続報

ハーバービジネスオンライン
【再開は未定です。当アカウントから再開の告知がない限り、「新しいアカウント」などを名乗るのは全てフェイク、なりすましだとお考えください】

永久凍結者の再登録は禁止されてますので…
本人でもstaffでもなりすましでも永久凍結の対象です pic.twitter.com/RcW87iSi2r
  

［source：］Twitter永久凍結の常連 菅野完氏 6日で永久凍結(再開未定) ネットの反応 - Togetter https://togetter.com/li/1341354
```

　上記に引用したように、とてもわかりやすい説明がありました。「永久凍結者の再登録は禁止されてますので」、「本人でもstaffでもなりすましでも永久凍結の対象」、「などを名乗るのは全てフェイク、なりすましだとお考えください」などとあります。

　モトケンこと矢部善朗弁護士（京都弁護士会）のツイートに付いている返信をみても、菅野完氏本人を疑問視するものは見当たらないので、モトケンこと矢部善朗弁護士（京都弁護士会）も菅野完氏のメルマガの文言として、論評をしたのかもしれません。

　菅野完のメルマガの内容と確認できる情報は見当たらないので、やはり誤解は与えそうです。菅野感という間際らしいアカウントのフォロワー数をみると2万となっていました。フォロー数は４です。これを見るとややこしく見通しの悪さはありますが、菅野完氏の影響力はけっこうありそうです。

　言い方を変えると、フォローして読むに値する情報と考えているアカウントがおよそ２万人いるということなのでしょう。Twitter社に永久凍結され、不当な表現規制を受けていると考えている人も相当数いるのかもしれません。

▶（07／11） TW motoken_tw（モトケン） 日時：2019-10-08 07:10:00 +0900 URL： https://twitter.com/motoken_tw/status/1181330954247266304
{% tweet 1181330954247266304 %}
> @prewarwrestler 報道機関とDV被害者を同列に並べて、なんかの反論になっていると考える論理性はすごいな。

　菅野感というアカウントからもモトケンこと矢部善朗弁護士（京都弁護士会）のツイートを公式引用した次のツイートがあって、そちらに対するモトケンこと矢部善朗弁護士（京都弁護士会）の返信のようです。DVの喩え話は、深澤諭史弁護士のタイムラインで法クラのツイートとしても見かけていました。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜prewarwrestler（菅野感） 日時：2019-10-17 02:23／2019/10/08 07:07 URL： https://twitter.com/kk_hirono/status/1184520346935775232 https://twitter.com/prewarwrestler/status/1181330294340587520
> 「そうだよな。DVも、暴力夫から逃げない女房が劣化してるからだもんな。普通の女房なら逃げるもんなぁ」  みたいな理屈、ほんと素晴らしいですね いやぁすごいすごい。 https://t.co/5cJRGOfgxd
▶▶▶　　　　　End　　　　　▶▶▶

　菅野完氏のメルマガを転載しているアカウントが、菅野完氏本人の考えをモトケンこと矢部善朗弁護士（京都弁護士会）に投げているとは考えられないですが、モトケンこと矢部善朗弁護士（京都弁護士会）の方は菅野完氏と、議論でがっぷり四つに組んだ感があります。

　モトケンこと矢部善朗弁護士（京都弁護士会）が菅野完氏に対して、どのような認識なのかもわからなくなってきましたが、森友学園問題であれだけ注目を集めた人物なので、取り違えや勘違いというのはないように思われます。その辺りを含めあとで調べる予定です。

▶（08／11） TW motoken_tw（モトケン） 日時：2019-10-08 07:30:00 +0900 URL： https://twitter.com/motoken_tw/status/1181336047940034560
{% tweet 1181336047940034560 %}
> @prewarwrestler 菅野氏によれば、日本の報道機関は、日々夫の暴力に怯えて夫の言いなりになっているDV被害者と同じようなものらしい。 \n 似非ジャーナリストではない本当の報道機関のみなさんは、自分たちがDV被害者と同列に並… https://t.co/px3oIBngZV

　モトケンこと矢部善朗弁護士（京都弁護士会）も菅野完氏がTwitter社に永久凍結されていることは知っていると思われ、規制をかいくぐるために感の漢字に置き換えていると思っているのかもしれません。アイコンが本人の顔写真の可能性が高いので、理屈としては通りそうな気もします。

　「菅野氏によれば・・・ 似非ジャーナリストではない本当の報道機関のみなさん」と菅野完氏を似非ジャーナリストとしているようにも読めますが、フォロワーが２万と多いので、漁場としての価値を狙って、とぼけた便乗弁護士商売をしているようにも思えてきました。

▶（09／11） TW motoken_tw（モトケン） 日時：2019-10-08 07:35:00 +0900 URL： https://twitter.com/motoken_tw/status/1181337285872078848
{% tweet 1181337285872078848 %}
> @prewarwrestler 「DV被害者は「それが正常な状態」と考え、で、周囲が「被害者に落ち度がある」ということで、固定化します。」 \n この人、そもそもDV問題を何も理解してないね。 \n 報道期間の萎縮の問題についてDVを持ち出すことだけで詭弁なのだが。

▶（10／11） TW motoken_tw（モトケン） 日時：2019-10-08 08:23:00 +0900 URL： https://twitter.com/motoken_tw/status/1181349300111998976
{% tweet 1181349300111998976 %}
> @hibinaya @prewarwrestler @popohito @AbeShinzo 権力が自分に都合の悪い報道に圧力をかけようとするのは当たり前。 \n そういう権力に対して、権力を批判するのが報道機関の使命だ、と言うなら、圧… https://t.co/72SpZnvGAM

　この「権力が自分に都合の悪い報道に圧力をかけようとするのは当たり前」というモトケンこと矢部善朗弁護士（京都弁護士会）のメッセージ性の強さ、またかという感じがしていましたが、これも流れを辿ると、菅野完氏と紛らわしいアカウントのツイートを足場の土台に築いていました。

▶（11／11） TW motoken_tw（モトケン） 日時：2019-10-15 10:55:00 +0900 URL： https://twitter.com/motoken_tw/status/1183924305127563265
{% tweet 1183924305127563265 %}
> 「本物のホームレス」というのがどんなホームレスか概ね想像できるけど、台東区の件は住所が書けなかったの拒否したという報道があるだけで、不潔だから拒否したかどうかは分からない。 \n ホームレスもいろいろ。 \n 道でビッグイシューを売ってる人も… https://t.co/a8vXu1FoDi

　これもいちいち取り上げて置くべきか、かなり迷ったのですが、犯罪者と同じくホームレスも、弁護士商売の出汁に使っているとしか思えないものでした。これも深澤諭史弁護士のタイムラインで法クラの間で、飛び火をしている感がありました。個人的な立場で軽視できない問題でもあります。

〈〈〈：Emacs： 2019-10-17（木曜日）02：47 　〈〈〈

