#+TITLE: "素人との知識の差こそが我々の飯のタネだよね？素人に知識がないことに文句言ってどうすんの？と。"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-10-09 13:28:52 +0900
FILE_NAME: 2019-10-09-132852_素人との知識の差こそが我々の飯のタネだよね？素人に知識がないことに文句言ってどうすんの？と。.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: ローカスこと三浦義隆弁護士,素人,法律相談
記事タイトル名の文字数：46　保存ファイル名の文字数：68
#+STARTUP: showeverything


* 「揶揄する法クラのツイート」、「素人との知識の差こそが我々の飯のタネだよね？素人に知識がないことに文句言ってどうすんの？と。」という三浦義隆弁護士のツイート
  CLOCK: [2019-10-09 水 13:32]--[2019-10-09 水 14:09] =>  0:37

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: ローカスこと三浦義隆弁護士,素人,法律相談

〉〉〉：Emacs： 2019-10-09（水曜日）13：32　 〉〉〉

lawkus ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW lawkus（ystk） 日時：2019/10/09 00:45 URL： https://twitter.com/lawkus/status/1181596412741439488
> この点、「弁護士から見ると法律問題ではない相談を持ってくる相談者」を揶揄する法クラのツイートたまに流れてくるけど、いささか無思慮に過ぎると思う。 \n 素人との知識の差こそが我々の飯のタネだよね？素人に知識がないことに文句言ってどうすんの？と。
▷▷▷　　　　　End　　　　　▷▷▷

TW lawkus（ystk） 日時： 2019/10/09 00:31 URL： https://twitter.com/lawkus/status/1181592986741657600
> これは本当そう。相談者の悩みが法律問題であるか否か自体、法専門家でなければわからないことが多いので、とりあえず相談してもらうしかない。 https://t.co/KAT56V35QT

　上記のローカスこと三浦義隆弁護士のツイートは、次のツイートを公式引用しています。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜futeras（風テラス相談窓口） 日時：2019-10-09 13:37／2019/10/07 18:03 URL： https://twitter.com/kk_hirono/status/1181790768609951745 https://twitter.com/futeras/status/1181132974927953920
> 「弁護士に相談した方がいい案件なのか、よく分からない」という状況でのご相談、大歓迎です。  「弁護士に相談すべき案件か否か」については、「法律に詳しい知人」とかに聞くのではなく、直接弁護士に聞くのが一番確実です。
▶▶▶　　　　　End　　　　　▶▶▶

　上記のツイートには次の返信が付いています。これもときどき見かけてきた匿名の弁護士アカウントかと思います。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜TGN54（TｰTAKA） 日時：2019-10-09 13:39／2019/10/07 18:10 URL： https://twitter.com/kk_hirono/status/1181791144046235648 https://twitter.com/TGN54/status/1181134596701736960
> @futeras これはもう本当に大賛成です！！来てもらって、法律的な問題でなかったら、それは結果オーライですよね。  あと、風テラスさんは社会福祉士さんも同席されているので、弁護士単独より遥かに多くの解決策を提示でき、とてもいいと思います！！
▶▶▶　　　　　End　　　　　▶▶▶

　次が上記のツイートに対する元のツイートのアカウントの返信ツイートです。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜futeras（風テラス相談窓口） 日時：2019-10-09 13:40／2019/10/07 18:24 URL： https://twitter.com/kk_hirono/status/1181791396430106625 https://twitter.com/futeras/status/1181138318123134976
> @TGN54 ありがとうございます！  コロンブスの卵みたいな話ですが、弁護士さんに聞くのが一番確実ですよね😁
▶▶▶　　　　　End　　　　　▶▶▶

　風テラス相談窓口というプロフィールの名前ですが、プロフィールの内容を見て以前見かけたことがあるように思いました。弁護士とは明示されていないようですが、弁護士を含む団体のようです。

```
風テラス相談窓口
@futeras
風俗のお仕事をしている人たちのための無料生活・法律相談窓口です。お金・住まい・家族・子ども・ホスト・税金・お店とのトラブルなど、どんな相談でもOK。全国どこからでもご利用頂けます。

ご相談予約はDM、LINE（futeras）、インスタ（futeras_org）メール（info@futeras.org）#風テラス
futeras.org2017年3月からTwitterを利用しています
755 フォロー中
2,640 フォロワー

［source：］風テラス相談窓口（@futeras）さん / Twitter https://twitter.com/futeras
```

　無料生活と法律相談窓口が一緒になっています。ホストとあるので女性限定ではないのかもしれません。法律相談窓口としながら弁護士を明示していないのであれば、非弁というのも問題になりそうですが、ホームページのリンクがあるので、そちらに弁護士名があるのかもしれません。

```
弁護士とソーシャルワーカー（社会福祉士・精神保健福祉士）が、あなたの相談に丁寧にお答えします。
風俗の世界で働く女性の方々が、現在抱えている悩みや困難（借金、離婚、障害、病気、介護、育児、ＤＶなどの問題）を
風俗で働いているという事実を隠さずに、安心して相談できる機会を作ることを目的にしています。
風テラスは、風俗店で働いている（働いていた）方であれば、どなたでもご利用頂けます。
全国どこからでも相談可能です。相談内容は、どんなささいなことでも構いません。
LINE・メールでの相談予約も可能です。

［source：］風テラス – 風テラスは、風俗ではたらく人のための無料生活・法律相談サービスです。 https://futeras.org/
```

　けっこう需要もありそうですが、トラブルがあればそれもネット上に流れそうです。時代劇の駆け込み寺というのを思い出しますが、まるでドラマの中の物語のようにも思えます。無料生活で活動が成り立つとも考えにくいですが、篤志家の援助もあるのかもしれません。

　ローカスこと三浦義隆弁護士のツイートは、その風テラス相談窓口のツイートを公式引用したものですが、その１つ、２つ手前のローカスこと三浦義隆弁護士のツイートも内容が気になるもので、トラブルに近いものを感じます。

TW lawkus（ystk） 日時： 2019/10/09 00:13 URL： https://twitter.com/lawkus/status/1181588548983508995
> 「妻はあなたと会いたくない。できれば顔すら見たくない」この前提でなお子との面会を模索する必要があるが、非監護親である相手方が我儘なガキなので、自分に加害意識がないからといって上記の前提すら受け入れず、「そもそも妻が俺に会いたくない理由はない」とか言い出して収拾つかない地獄とかな。

TW lawkus（ystk） 日時： 2019/10/08 23:54 URL： https://twitter.com/lawkus/status/1181583665458892800
> 子が幼いため面会に監護親も立ち会う他ないのをいいことに、毎回直接交渉してくる、聞きつけた監護親代理人弁護士が何度抗議してもやめない、みたいなクズ非監護親普通にいるもんな。 \n 俺は元々面会交流には積極的な部類だと思うけど、行政がもっと関与してくれないと協力するにも限界あるわとは思う。

　数年前に比較すればローカスこと三浦義隆弁護士のツイートもずいぶん穏当になったと感じていますが、挑発的に罵倒するものなど数々を目にしてきました。それでも弁護士として活動し、支店まで増やしているようです。

　素人というのも、モトケンこと矢部善朗弁護士（京都弁護士会）がよく使うもので、そちらは「素人さん」と小馬鹿にしたような挑発的な表現が多いものです。

　このローカスこと三浦義隆弁護士のツイートに出てくる看護親というのは、共同親権についての弁護士のツイートにも出てきたものかと思いますが、とにかく根底よりろくでなしやクズと決めつけ罵倒するものが多いです。

　たしかに問題のある訴訟の相手方や依頼者というのは存在するのだと思いますが、実態の程度をはるかに超えているか、弁護士そのものの病的な部分が発露しているようにも思えてなりません。端的に揉め事を大きくしているように思えるのですが、実態は掴み難くもあります。

〈〈〈：Emacs： 2019-10-09（水曜日）14：09 　〈〈〈

* 「困難当事者の案件で裁判所に辞任をほのめかすと手の平返したように理解を示してきます」という北周士弁護士のツイートを公式引用したローカスこと三浦義隆弁護士のツイート
  CLOCK: [2019-10-09 水 15:06]--[2019-10-09 水 15:20] =>  0:14

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: ローカスこと三浦義隆弁護士,北周士弁護士

〉〉〉：Emacs： 2019-10-09（水曜日）15：06　 〉〉〉

lawkus ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW lawkus（ystk） 日時：2019/10/08 17:52 URL： https://twitter.com/lawkus/status/1181492439053299712
> これ、裁判官も事実認識として「コントロールできるだろう」と誤解しているわけではないと思うんですよね。その証拠に、困難当事者の案件で裁判所に辞任をほのめかすと手の平返したように理解を示してきますからね。本人訴訟にされても困ると思う程… https://t.co/X9V1cfygjQ
▷▷▷　　　　　End　　　　　▷▷▷

　上記のローカスこと三浦義隆弁護士のツイートは、次の北周士弁護士のツイートを公式引用しています。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜noooooooorth（ノースライム） 日時：2019-10-09 15:08／2019/10/08 13:52 URL： https://twitter.com/kk_hirono/status/1181813712744665088 https://twitter.com/noooooooorth/status/1181432074353414144
> 裁判所は弁護士が依頼者をコントロールできるものと思っているようだけど、依頼者には依頼者の考えや人生があるのでそんなにコントロールできるものではありませんよ。裁判官も法律事務所で他職経験をしてみるとその一端がわかると思うな。
▶▶▶　　　　　End　　　　　▶▶▶

　ちょっと意外だったのですが、告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)で北周士弁護士のツイートがリツイート出来たようです。こちらもブロックされているものと思っていました。

　次の返信ツイートがあります。鹿児島の弁護士というTwitterアカウントはいくつか見てきたのですが、名前に見覚えがなかったのですがリストのは登録済みでした。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kagoshimaaozora（鹿児島あおぞら法律事務所🍀弁護士 犬童正樹） 日時：2019-10-09 15:12／2019/10/08 14:55 URL： https://twitter.com/kk_hirono/status/1181814578939715584 https://twitter.com/kagoshimaaozora/status/1181447909109166080
> @noooooooorth 依頼者への説得が依頼者にとって利益だとしても、依頼者の感じ方一つで、解任や懲戒請求のリスクがありますからね
▶▶▶　　　　　End　　　　　▶▶▶

　どこまで本当なのか、これも弁護士以外の素人には確認ができないのですが、弁護士が辞任をほのめかすと裁判官が手のひら返しで理解を示すとあります。本人訴訟になると裁判官も困るということで、厄介さを裁判官が理解しているとあります。

　本人訴訟ということなので民事裁判に間違いはなさそうです。刑事裁判でも弁護人を変えると裁判官の心証を悪くするという話は聞いたことがあり、それも国選に決まっていた被告発人岡田進弁護士のことで、被告発人木梨松嗣弁護士が私の母親に説明したという話でした。

　弁護士の優位性を強く感じるのもローカスこと三浦義隆弁護士のツイートの特徴ですが、これが警察官を法律の素人と罵倒しつつTwitterで公言するものとなると、看過は出来ず、重大深刻な問題として把握しておいてもらいたいところです。

〈〈〈：Emacs： 2019-10-09（水曜日）15：20 　〈〈〈

