#+TITLE: "自らに対し名誉毀損の訴えを呼びかける三浦義隆弁護士のツイート、がきっかけの発見"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-11-14 22:46:47 +0900
FILE_NAME: 2019-11-14-224647_自らに対し名誉毀損の訴えを呼びかける三浦義隆弁護士のツイート、がきっかけの発見.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: ローカスこと三浦義隆弁護士,名誉毀損
記事タイトル名の文字数：39　保存ファイル名の文字数：61
#+STARTUP: showeverything


* 記録的な法クラ率かもしれない「貴殿は私の訴訟に耐えられるかな？」という記録：自らに対し名誉毀損の訴えを呼びかける三浦義隆弁護士のツイート、がきっかけの発見
  CLOCK: [2019-11-14 木 22:49]--[2019-11-14 木 23:38] =>  0:49

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: ローカスこと三浦義隆弁護士,名誉毀損,法クラ

〉〉〉：Emacs： 2019-11-14（木曜日）22：49　 〉〉〉

　今夜は食べ過ぎで集中力を書いていますが、何かその気分にならないので１６時過ぎにテレビを消してから今のところ付けてもいません。さほど大食いをしたことはなく、残り物が中心でしたがお腹が一杯になっています。

[link:] 2019年11月14日21時21分の登録： REGEXP：”三浦．＊示談の条件”／データベース登録済みツイート：2019年11月14日21時21分の記録：ユーザ・投稿：21／31件 http://hirono2014sk.blogspot.com/2019/11/regexp2019111421212131.html

　上記のまとめ記事を作成するため、APIではなく通常のブラウザでTwitter検索をしたのですが、これも記録的なヒット数がありました。Twitterの検索はスペースを挟むことで一応の絞り込みが出来るので「三浦 示談の条件」として実行しました。

　Twitterの検索は、正規表現を使った高度な検索よりも、柔軟に対応した、時にはおせっかいとも感じることのある幅の広いヒット率もあるかと思います。明確な規則は確認していないですが、経験上になります。通常の正規表現では難しい、出現の前後の違いもカバーするようです。

　ずっと前から、「すべての責任を負った三浦に対し、車の主、暴力団員谷岡に言い渡された示談の条件とは」を基本形とし、アレンジしたものを見かけてきたフレーズにある三浦が、三浦義隆弁護士を指すものなのか確認したのですが、確認は出来ず、その可能性は低そうでした。

　予想外の結果だったのは、全体的なTwitterの検索では、あれほどヒットが多かったのに、過去のツイートの取得に大きな限界はあるものの、それを差し引いても２１アカウントの３１件というのは、見かけた記憶が多かっただけに、ずいぶんと意外な結果でした。

　Twitterの検索の精度は経験上まったく信頼がないですが、Twitterの検索でスペースキーでの追加読み込みを連打で繰り返し続けたところ、行き着く最後になったのが次のツイートで、その時系列の並びにも信頼はおけないのですが、もっとも古い投稿として確認したものであります。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜bokkionsen（勃起温泉@E-18bでおてつだいさんします） 日時：2019-11-14 23:08／2010/03/29 21:50 URL： https://twitter.com/kk_hirono/status/1194980306274512898 https://twitter.com/bokkionsen/status/11247208533
> @R_E_D_R_U_M_187 すべての責任を負った三浦に対し、車の主、暴力団員谷岡に言い渡された示談の条件とは・・・。
▶▶▶　　　　　End　　　　　▶▶▶

　２０１０年３月２９日のツイートです。９年半ほど前になるので、キーワードを指定したTwitterの検索でも、投稿日時の範囲の指定をしていないので、その９年半の機会が対象となったはずです。

　一方の「貴殿は私の訴訟に耐えられるかな？」をキーワードに指定したツイートの検索は、自作のコマンドでTwitterAPIを利用した検索になります。何度かご説明をしてきたと思いますが、予め指定したアカウントのリストと突き合わせ、マッチしたものを自動でデータベースに登録しています。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-14 23:13／2019/11/14 22:26 URL： https://twitter.com/kk_hirono/status/1194981586636177411 https://twitter.com/hirono_hideki/status/1194969803955392514
> 2019年11月14日22時24分の登録： REGEXP：”貴殿は私の訴訟に耐えられるかな？”／データベース登録済みツイート：2019年11月14日22時20分の記録：ユーザ・投稿：97／212件 https://t.co/TTOKFCwyrX
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-14 23:14／2019/11/14 22:15 URL： https://twitter.com/kk_hirono/status/1194981907756249089 https://twitter.com/hirono_hideki/status/1194967061627195396
> 2019年11月14日22時15分の実行記録 twitterAPI-search-lawList-mydql-add.rb "貴殿は私の訴訟に耐えられるかな？" ツイート数：58/1594 リツイート数：160/1594 トータル… https://t.co/od8mgEwswI
▶▶▶　　　　　End　　　　　▶▶▶

　一つ間違えてリツイートをしましたが、APIで取得しきれなかったツイートの全文は次になります。

```
2019年11月14日22時15分の実行記録
twitterAPI-search-lawList-mydql-add.rb "貴殿は私の訴訟に耐えられるかな？"
ツイート数：58/1594 リツイート数：160/1594 トータル：3302
hirono_hideki 2／0件
kk_hirono 0／0件
s_hirono 1／0件
```

　1594というのが、マッチングに利用したリストに登録済みのTwitterアカウント数になります。正確に把握はしていないですが、弁護士や法律家の可能性の高いアカウントが9割を超えていると思います。他はジャーナリストや政治家のアカウントも社会的な影響力のある発言として加えています。

　"貴殿は私の訴訟に耐えられるかな？"という文言を含むツイートは、おそらく前例のないものと思います。

［link：］ 貴殿は私の訴訟に耐えられるかな？ - Twitter検索 / Twitter https://twitter.com/search?q=%E8%B2%B4%E6%AE%BF%E3%81%AF%E7%A7%81%E3%81%AE%E8%A8%B4%E8%A8%9F%E3%81%AB%E8%80%90%E3%81%88%E3%82%89%E3%82%8C%E3%82%8B%E3%81%8B%E3%81%AA%EF%BC%9F&src=typed_query

　今度は、キーボードのEndキーを連打しましたが、最終的な位置に表示されたのが次のツイートになります。このあと確認しますが、同じ11月13日となっているものの、大元の竹田恒泰氏のツイートよりは、後の投稿ではと思います。それと思われるツイートは下から16番目ぐらいの位置にあります。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜_96co（くろこ） 日時：2019-11-14 23:26／2019/11/13 09:19 URL： https://twitter.com/kk_hirono/status/1194985014355562496 https://twitter.com/_96co/status/1194409332084883456
> 『貴殿は私の訴訟に耐えられるかな？』これすき
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜takenoma（竹田恒泰） 日時：2019-11-14 23:27／2019/11/13 08:55 URL： https://twitter.com/kk_hirono/status/1194985156739649536 https://twitter.com/takenoma/status/1194403436936101888
> 言論の自由はその通り。しかし、その結果、損害が生じたら損害賠償の責任が生じます。「自由」とはそういうものです。貴殿は私の訴訟に耐えられるかな？ https://t.co/lJLG6ZP7Ew
▶▶▶　　　　　End　　　　　▶▶▶

　大元と思われる竹田恒泰氏のツイートが、11月13日8時55分という投稿時刻、Twitterの検索で最終位置に出てきたツイートが同日9時19分のツイートであると確認しました。

　次が記録的と思われた検索結果のまとめ記事になります。

[link:] 2019年11月14日22時24分の登録： REGEXP：”貴殿は私の訴訟に耐えられるかな？”／データベース登録済みツイート：2019年11月14日22時20分の記録：ユーザ・投稿：97／212件 http://hirono2014sk.blogspot.com/2019/11/regexp20191114222097212.html

　97／212件は、97アカウントで212件の該当ツイートを意味します。アカウントの数としてはかなり多い方ですが、ツイートの数はさほど多くはありません。ただし、その対象期間がおよそ一日半というところに、これまでにない尋常でない反応を感じました。

　次が、法クラのツイートのヒット率ですが、これはツイートの検索結果に占める割合として記録的なものだと思いました。

　「ツイート数：58/1594 リツイート数：160/1594 トータル：3302」、トータルが3302件で、そのうちリストに該当するアカウントのツイートが58件、同じくリツイートが160件とあります。

〈〈〈：Emacs： 2019-11-14（木曜日）23：38 　〈〈〈

* 2019年11月14日午前9時40分のツイートで見かけた、「学部生よりも憲法が苦手な竹田恒泰氏」という2017年7月1日付けの三浦義隆弁護士のブログ記事
  CLOCK: [2019-11-14 木 23:45]--[2019-11-15 金 03:58] =>  4:13

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 三浦義隆弁護士,痴漢冤罪,懲戒請求,憲法

〉〉〉：Emacs： 2019-11-14（木曜日）23：45　 〉〉〉

　これが何より大きな発見でした。過去のツイートのリツイートではなく本日付のツイートのなかにブログ記事の紹介があったので、三浦義隆弁護士がブログを更新したのかと勇み立ったのですが、驚いたことにブログは2017年12月3日の記事から更新されないままで、それより古い記事の紹介でした。

　三浦義隆弁護士がなぜブログを更新しないのか、それもずっと謎のままでした。ブログの放置というのはありがちかと思いますが、2019年11月14日に、2017年12月から更新していないブログの2017年7月1日の記事をツイートで紹介したというのは、意表を衝かれた驚きでした。

　ミステリーな現象といっても過言はないぐらいで、三浦義隆弁護士その人が何かの意思、何かの力に動かされたのではという想像も巡らしました。その三浦義隆弁護士は、そのブログの開始も電撃的なもので、本人によれば記録的なアクセス数にもなったということだったと記憶します。

```
2017年4月に開設した本ブログ、2か月目の5月はちょっと頑張って26回も更新した。

その結果、PVは100万を超えた。はてなブログ本体と、同じ内容が転載されているBLOGOSを合わせての数字だが。

本体のPVが85万強。BLOGOSが19万強。

［source：］5月のブログ運営を振り返ってみる(PV100万超、ブクマ増加数1位など) - 弁護士三浦義隆のブログ http://miurayoshitaka.hatenablog.com/entry/2017/06/01/5%E6%9C%88%E3%81%AE%E3%83%96%E3%83%AD%E3%82%B0%E9%81%8B%E5%96%B6%E3%82%92%E6%8C%AF%E3%82%8A%E8%BF%94%E3%81%A3%E3%81%A6%E3%81%BF%E3%82%8B%28PV100%E4%B8%87%E8%B6%85%E3%80%81%E3%83%96%E3%82%AF
```

```
はてなブログの月間被ブクマ増加数ランキングでは1位だった。

2位にほぼトリプルスコアの差をつけていたので驚いた。

［source：］5月のブログ運営を振り返ってみる(PV100万超、ブクマ増加数1位など) - 弁護士三浦義隆のブログ http://miurayoshitaka.hatenablog.com/entry/2017/06/01/5%E6%9C%88%E3%81%AE%E3%83%96%E3%83%AD%E3%82%B0%E9%81%8B%E5%96%B6%E3%82%92%E6%8C%AF%E3%82%8A%E8%BF%94%E3%81%A3%E3%81%A6%E3%81%BF%E3%82%8B%28PV100%E4%B8%87%E8%B6%85%E3%80%81%E3%83%96%E3%82%AF
```

```
はてなブログの月間読者増加数ランキングは2位。

1位は聞いたことのないブログ。ブクマもあまりされてないが読者数だけは沢山増えたようで、ちょっと不思議だった。

ブクマはされないが読者数は増えるブログとか、その逆とか、一定の傾向があるのだろうか。初心者だからよくわからない。

［source：］5月のブログ運営を振り返ってみる(PV100万超、ブクマ増加数1位など) - 弁護士三浦義隆のブログ http://miurayoshitaka.hatenablog.com/entry/2017/06/01/5%E6%9C%88%E3%81%AE%E3%83%96%E3%83%AD%E3%82%B0%E9%81%8B%E5%96%B6%E3%82%92%E6%8C%AF%E3%82%8A%E8%BF%94%E3%81%A3%E3%81%A6%E3%81%BF%E3%82%8B%28PV100%E4%B8%87%E8%B6%85%E3%80%81%E3%83%96%E3%82%AF
```

```
BLOGOSのブロガーランキングというのをさっき初めて見てみたら、閲覧数ランキングで12位だった。

上位にいる人は私を除き有名な方ばかりだったので、こんなに高いのかと少し驚いた。

BLOGOSは、私がはてなブログに投稿したものが時間差で転載されているだけだから、あまりPVの集まりやすい環境ではなさそうに思えるが。

［source：］5月のブログ運営を振り返ってみる(PV100万超、ブクマ増加数1位など) - 弁護士三浦義隆のブログ http://miurayoshitaka.hatenablog.com/entry/2017/06/01/5%E6%9C%88%E3%81%AE%E3%83%96%E3%83%AD%E3%82%B0%E9%81%8B%E5%96%B6%E3%82%92%E6%8C%AF%E3%82%8A%E8%BF%94%E3%81%A3%E3%81%A6%E3%81%BF%E3%82%8B%28PV100%E4%B8%87%E8%B6%85%E3%80%81%E3%83%96%E3%82%AF
```

```
痴漢関連の一連のエントリをきっかけに、以下のメディアから取材を受けたり出演したりした。(その他、断ったものもいくつか。)

・フジテレビ「ノンストップ！」(VTR出演)

・毎日新聞 (取材に応答)

・AbemaTV 「AbemaPrime」(生出演)

・東京FM「クロノス」(電話で生出演)

毎日新聞以外は少しだけだが出演料を頂いたりしているので、間接的な収益はあったことになる。小遣い程度だけど。

［source：］5月のブログ運営を振り返ってみる(PV100万超、ブクマ増加数1位など) - 弁護士三浦義隆のブログ http://miurayoshitaka.hatenablog.com/entry/2017/06/01/5%E6%9C%88%E3%81%AE%E3%83%96%E3%83%AD%E3%82%B0%E9%81%8B%E5%96%B6%E3%82%92%E6%8C%AF%E3%82%8A%E8%BF%94%E3%81%A3%E3%81%A6%E3%81%BF%E3%82%8B%28PV100%E4%B8%87%E8%B6%85%E3%80%81%E3%83%96%E3%82%AF
```

```
書籍化のお話を2社からいただいている。うち1社と進めて行くことになりそう。

［source：］5月のブログ運営を振り返ってみる(PV100万超、ブクマ増加数1位など) - 弁護士三浦義隆のブログ http://miurayoshitaka.hatenablog.com/entry/2017/06/01/5%E6%9C%88%E3%81%AE%E3%83%96%E3%83%AD%E3%82%B0%E9%81%8B%E5%96%B6%E3%82%92%E6%8C%AF%E3%82%8A%E8%BF%94%E3%81%A3%E3%81%A6%E3%81%BF%E3%82%8B%28PV100%E4%B8%87%E8%B6%85%E3%80%81%E3%83%96%E3%82%AF
```

```
理由は上記のとおり。   開始した4月は10回だけ更新して13万PVくらいだったので、5月は50万くらい行けばいいかなという気持ちでいた。 それが実際には100万。   ここまで伸びたのはさすがに予想外だった。   本ブログのネタは専門性に依存しているから、たくさん書いていくうちにネタが尽きるというか、一般の方に必要とされないような細かい知識になってゆかざるを得ないと思う。 だからいつまで続くかはわからないが、現時点ではまだまだ書きたいこと・書くべきことがあるので、当分の間は積極的に更新していきたい。  

［source：］5月のブログ運営を振り返ってみる(PV100万超、ブクマ増加数1位など) - 弁護士三浦義隆のブログ http://miurayoshitaka.hatenablog.com/entry/2017/06/01/5%E6%9C%88%E3%81%AE%E3%83%96%E3%83%AD%E3%82%B0%E9%81%8B%E5%96%B6%E3%82%92%E6%8C%AF%E3%82%8A%E8%BF%94%E3%81%A3%E3%81%A6%E3%81%BF%E3%82%8B%28PV100%E4%B8%87%E8%B6%85%E3%80%81%E3%83%96%E3%82%AF
```

　上記の引用はすべて同一記事・同一ページからの部分引用となります。実際はスクリーンショットの画像などの掲載もあるのですが、にわかに信じがたいような話でもあるので、情報の正確性を担保するため多めの引用とさせて頂きました。

　上記の「5月のブログ運営を振り返ってみる(PV100万超、ブクマ増加数1位など)」という記事の日付は、2017年6月1日となっています。

　10日から2週間ぐらいだったと思いますが、その2017年の5月の半ばから、確か27日ぐらいまで、私は宇出津病院に入院していました。その入院中は体の状態は悪かったのですが、スマホでネットの情報をみることが多く、特に印象に強く残っているのは、痴漢冤罪の三浦義隆弁護士の発言です。

　三浦義隆弁護士はもともとローカスというハンドル名で、ローカス先生と呼ばれていることも多かったのですが、少し調べれば、広告的な法律事務所のホームページなどからすぐに実名はわかったのですが、Twitterでは自ら実名を明かすこともなかったように思います。

　三浦義隆弁護士が積極的に実名を明かし、専門家としての見解を示すようになったのも、痴漢冤罪の社会問題とブログの開始が始まりだったように記憶しています。鉄道の線路を使った危険な逃走が相次いでいた時期であったとも思いますが、一つのピークのような状況であったと振り返ります。

　ビルとビルの間から転落死した冤罪の可能性のある置換事件というのも私としては強く印象に残っている記事があるのですが、それに対する法クラのコメントというのは見た憶えがありません。入院中であれば、体調も優れず集中力を欠き、情報収集が極端に少ない時期ではあったかと思います。

[link:] » JR上野駅「痴漢転落死」は超一流ホテルの支配人だった（週刊現代） | 現代ビジネス | 講談社（1/4） https://t.co/laeBCS6YGC

　たぶん上記のニュースだったと思うのですが、同じ記事を読んだのか正確には思い出せません。上記の記事は2017年6月12日となっています。本文に転落死は5月11日深夜とみえるので、その間に、他の報道や記事もあったものと考えます。

　本当の冤罪なのに、冤罪の疑いでパニックとなり転落死となったのであれば、遺族を含めさぞや無念があったことと察します。一流ホテルの支配人とありますが、一流ホテルの料理人として間違ったまま記憶していた気もします。このニュースと三浦義隆弁護士の発言をよく突き合わせて考えていました。

　やがて2年半近くも前のことなので、細かく正確に思い出すことは出来ず、心の中、頭の中でもぼやけた風景となっていますが、痴漢冤罪に関する三浦義隆弁護士の発言とは強く結びついて記憶と心の中にありました。

```
そもそも、もし仮に「手に触れる」という行為があったとしても、それが痴漢になるのか。

痴漢行為の線引きについて、元検事で痴漢事件に詳しい弁護士の中村勉氏はこう指摘する。

「電車内で手を触っただけでは、痴漢はなかなか成立しにくいと思われます。痴漢は、公衆の面前で性的羞恥心を生じさせるというのが、行為の構成要件です。

ですから通常であれば、胸や臀部、太ももを触った場合ということになるでしょう。手を触るという行為だけでは、強制わいせつにもあたらないと思います。

ただし、手の触り方にもよります。単に握手するような触り方だったのか、それとも手を撫で回すような感じの触り方なのか。痴漢であるか否かは、性的に恥ずかしい思いをさせたかどうかがポイントです。

［source：］JR上野駅「痴漢転落死」は超一流ホテルの支配人だった（週刊現代） | 現代ビジネス | 講談社（2/4） https://gendai.ismedia.jp/articles/-/51959?page=2
```

　上記に引用した部分は記憶になかったのですが、痴漢の疑いで逃走したにせよ、その行為は女性の手を握ったという疑いであったようです。もう一度、引用部分を読み直すと、手を握ったではなく、手を触ったとありました。

　ここで思い出した事件があるのですが、探し出すのも困難かもしれません。印象的な事件で、あるいは逮捕もされる事件にはなっていないかもしれないですが、弁護士が電車の中で長時間、女性の手を握り続けたというものであったように思います。場所は大阪から神戸の間だったと思います。

```
逮捕容疑は、4日午後10時半～5日午前0時頃、阪神梅田発山陽姫路行き直通特急の車内で、隣に座っていた同県姫路市の女性会社員(21)の下半身を触ったとされる。

　宮崎容疑者は2人掛けの椅子で女性の左隣に座っていたが、よほどムラムラしたのか、女性の下半身に手を伸ばしてしまった。

　女性は午前0時頃に、姫路市の大塩駅で降りたが、宮崎容疑者が後を付いてきたため、駅員に被害を申告。駅の外に逃走した宮崎容疑者を、同駅に停車中の普通電車の車掌が約50メートル先で取り押さえ、駆け付けた同署員に引き渡した。

　宮崎容疑者は「富良野・凛と法律事務所」(北海道富良野市日の出町)に勤務していたが、独立のため、昨年7月末で同事務所を退所。その後、地元の関西に戻って、兵庫県西宮市高松町で「宮崎法律事務所」を開設。得意分野は金銭貸借・保証、高齢者・障害者問題、労働事件(被用者側)としている。

［source：］電車内で女性の下半身をお触り…独立開業したばかり兵庫の29歳弁護士がナゼ (2013年3月8日) - エキサイトニュース https://www.excite.co.jp/news/article/Real_Live_13243/
```

　漠然と記憶にあったものとは、記事を読んで印象も異なりますが、たぶんこの事件のことを記憶していたのだと思います。上記の記事に説明はないですが、「4日午後10時半～5日午前0時頃」という記載があります。長時間触り続けたとはありませんが、その可能性はありそうです。

　どうも弁護士は、午前0時に途中下車してまで、女性の後を追い逮捕となったようです。記事の事実経過をみてもわかりにくさがありますが、弁護士は本来、降車するはずだった駅を降りずに、女性の体を触り続けた可能性もあり、すっかりその気にさせられた上での、逮捕にも見えなくはありません。

　2013年の上記の記事に、3月5日に逮捕とあるので2013年3月5日の事件なのでしょう。こういう年月日はいちいち正確に記憶が出来ないですが、宇都宮市の弁護士が出所か釈放された、弁護を担当した女性を迎えに行き、一晩、法律事務所に留めて懲戒処分となった案件と時期が近い気もします。

[link:] » 弁護士紹介 – 旭川‐富良野‐あい弁護士法人 富良野・凛と 法律事務所 https://t.co/PxdafgfUGj

　現在も注目を続け、記録の作成も行っている足立啓太弁護士の法律事務所でした。そういえばという気もしないではないですが、2013年3月であれば、まだ足立啓太弁護士に注目する前であったという可能性も一応はありそうです。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-15 00:58／2016/09/06 15:13 URL： https://twitter.com/kk_hirono/status/1195008192532467712 https://twitter.com/hirono_hideki/status/773041450057658368
> 奉納＼弁護士妖怪大泥棒神社・金沢地方検察庁御中: 足立啓太弁護士のツイートの記録：”裁判官に合わせない弁護人を間抜け扱いは所詮傍聴席からしか見てない傍聴芸人の限界”の前 https://t.co/2fqlrISeew
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「足立啓太」の検索結果 - Twilog https://t.co/UYJ7O2tTIv

　一つ文字化けの文字が含まれていたので削除をしました。縦型のひし形で、黒字に白で？マークのある文字です。足立啓太で検索をすると、2016年9月6日が該当の最初のものとなっていて、これはずいぶん意外な結果でした。ちょっと納得が行かないので少し調べてみます。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-15 01:04／2013/08/25 14:59 URL： https://twitter.com/kk_hirono/status/1195009538509787137 https://twitter.com/hirono_hideki/status/371512151699365888
> 弁護士あだちけいた (keita_adachi)さんはTwitterを使っています http://t.co/eaLobjfibe リツイートしようと思ったのですが、この実名弁護士さんにもブロックされいるようです。
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「あだちけいた」の検索結果 - Twilog https://t.co/QbfCYFe0Dz

　今度は、2013年8月25日の時点でブロックされていることを確認したというツイートを発見したのですが、ずいぶん前からブロックされていたものだと思いました。

［link：］ 過激なツイートが目の毒だろうからブロックしてあげるのもひとつの愛情だと考える／（弁護士あだちけいた） | 告発-金沢地方検察庁御中_2015 https://hirono2015k.wordpress.com/2015/09/21/%e9%81%8e%e6%bf%80%e3%81%aa%e3%83%84%e3%82%a4%e3%83%bc%e3%83%88%e3%81%8c%e7%9b%ae%e3%81%ae%e6%af%92%e3%81%a0%e3%82%8d%e3%81%86%e3%81%8b%e3%82%89%e3%83%96%e3%83%ad%e3%83%83%e3%82%af%e3%81%97%e3%81%a6/

keita_adachi ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW keita_adachi（弁護士あだちけいた @11月1週目は裁判員） 日時：2015/09/21 05:13 URL： https://twitter.com/keita_adachi/status/645692369824710656
> 過激なツイートが目の毒だろうからブロックしてあげるのもひとつの愛情だと考える
▷▷▷　　　　　End　　　　　▷▷▷

　記憶にはなかったですが、足立啓太弁護士には、そのようなツイートもあったのかと思わぬ発見になりました。2015年の9月だと、まだ前後199件のツイートをまとめ記事にするスクリプトは使っていなかったものと思われますし、前後のツイートが全く見えないもの残念です。

［link：］ 弁護した女性と一晩過ごした国選弁護人…懲戒 - 消費者保護。東日本大震災・津波避難・福島原発。子供安全。冤罪。警察不祥事。労働者権利。相川哲弥ブログ https://blog.goo.ne.jp/jp280/e/efe48a07a1681b2386fcc8e6275fb426

　わかりやすく簡潔な記事のタイトルになっていますが、2013年4月4日が記事の投稿日のようです。さきほどの姫路市で逮捕されたという弁護士の痴漢事件は2013年3月5日となっていたので、ちょうど一月ほど後になりそうです。

```
5 白黒(芋) 2013/03/05(火) 11：56：17 ID：gtXHorEA0
いま大阪のニュースで、一時間以上も女のパンツの中に手入れてたって言ってるwww
女が何回か逝かされて、賢人タイムに入ってしまったってことかなw

［source：］「この人、痴漢です！！」自称弁護士 宮崎宏彰（２９）が電車で女性の下半身さわり逮捕　兵庫県警 - 2ちゃんねる勢い速報まとめ ［板：ニュース速報 スレ：1362451366］ https://2ch.live/cache/view/news/1362451366
```

　乗客が長椅子のような座席で向かい合う電車内だと、1時間以上も女性のパンツに手を入れることは不可能に近いと考えられるので、指定席に近いような列車の座席だったと考えられます。高速バスも似たような座席が多いかと思いますが、ここでも思い出した裁判官の事件があります。

［link：］ 福岡高裁裁判官バス車内で猥褻行為 - YouTube https://www.youtube.com/watch?v=94EMkixjCdw

　同じ事件のテレビニュースが５つほど連続でまとめられていました。記憶にあったのは熊本県人吉市で、逮捕されたのは宮崎県都城市だったとのことです。福岡高裁宮崎支部の判事ということも今回初めて知ったようで驚きました。

　別冊ジュリストに欺罔で自殺に追い込んだ殺人罪があって、それが福岡高裁宮崎支部の判例となっていたのでとりわけ印象深い裁判所であったのです。動画にあるニュースの映像には1枚のたぶん同じ映像が使われていましたが、以前写真で見た被疑者の裁判官の印象とは別人に見えました。

　以前、写真で見た被疑者の裁判官の印象というのは、柔道家のような胸板の厚い体格で、現役時代の横綱、貴乃花にも似ているという印象がありました。ニュースにある少し動いて見えた映像は、かなり普通のサラリーマンに近いという飲酒ですが、とても真面目そうに見えました。

　準強制わいせつで逮捕された福岡高裁宮崎支部の判事は、容疑を否認しているという一律のニュースでしたが、私がその事件を知った時点では、容疑を認めていたのか、否認しているという情報は記憶にも残ってはいなかったです。

```
この裁判官、福岡地裁でも

会ったことがあるような

ないような現職判事の

逮捕はロリコンと法廷で

断罪された村木保裕氏

以来ではなかろうか。

令状逮捕ではないので、

逮捕した警察署も職質を

やってさぞビックリのはず

京都に続いて、宮崎の

裁判所内での混乱もさぞ

ひどかろうと思われる

［source：］一木泰造裁判官、わいせつ罪で逮捕 | 福岡若手弁護士のblog https://ameblo.jp/fben/entry-10205440003.html
```

　向原栄大朗弁護士の昔のブログと思ったのですが、しばらくしてから、それとわかるものとは違うと気が付きました。向原栄大朗弁護士のブログは「家電弁護士」などとなっていたかと思います。上記の記事も2009年2月9日とありますが、同じ頃によく見かけていたかと思います。

　同じ時期に京都でも裁判所を騒がす出来事があったようですが、刑事事件として思い出すものはなく、１つ記憶に残るのは、民事裁判だったと思いますが、タクシー運転手かタクシー会社に対する「雲助」発言でした。

[link:] » 「タクシー運転手は雲助」京都裁判長の蛮勇判決 : 1999-11-04｜書誌詳細｜国立国会図書館サーチ https://t.co/qJrssHF6mR

```
１０月１８日、京都地方裁判所で、元タクシー運転手の強盗殺人に関する民事事件の判決があった。事案は、タクシー運転手に金銭目的で殺害された乗客の遺族が、元運転手とタクシー会社に損害賠償を求めた訴訟につき、民法７１５条に基づく被告会社の使用者責任を認め、請求金額を連帯して支払うよう命じたものである。

判決理由中、被告会社の民法７１５条但書に基づく免責の主張を退ける判断の中に、「一般論でいえば、タクシー乗務員には雲助（蜘蛛助）まがいの者や賭事等で借財を抱えた者がまま見受けられること（顕著な事実といってよいかと思われる。）」との部分がある。これは、この判決を下した裁判官が、この表現により叙述された事実が、証明を要しない社会常識であるとの認識を持っていることを示したものである。

［source：］京都地裁裁判官の職業差別について https://www.eda-jp.com/satsuki/991025.html
```

　さきほど別の記事で、強盗殺人の刑事裁判だったのかと思ったのですが、やはりかすかな記憶どおりに民事裁判だったようです。しかし、強盗殺人とは全く記憶には残っていなくて、民法715条但し書きに基づく免責を退ける判断の中、とありました。これはタクシー会社も当事者性が高そうです。

　1999年10月25日という記事の日付で、10月18日の京都地裁とありますが、平成11年の10月となると、私は金沢刑務所の拘置所の独居房で生活をしていたので、なぜ雲助のことを知ったのか不思議です。当時は所持金も乏しかったので、週刊誌の購入もほとんどなかったはずです。

　金沢刑務所の場合、再犯刑務所でもあるので拘置所でもラジオのニュースは初犯刑務所の福井刑務所に比較し多くなかったと思いますが、たまたまラジオ放送で聞いていたのかもしれません。そういえば活字として記事を見たという記憶もないことに気が付きました。

```
今から２０年ほど前、大分地方裁判所にいたある裁判官は、週に１回大分本庁から中津支部に車で通勤していましたが、中津で飲み会があると酒を飲んで飲酒運転で大分の官舎まで帰っていたとのこと。これは裁判所内では結構有名な話です。この裁判官、酒を飲むと口が悪くなるので有名な御仁。ある時、酒を飲んでタクシーに乗り、タクシーの運転手に相当悪態をついたものと思います。タクシーの運転手から、かなり激しい暴行を受け、タクシーから放り出されたことがありました。その後、この裁判官は京都地方裁判所に転勤になり、あるタクシー運転手が被告人となった刑事裁判の判決の中で、「タクシー運転手は雲助である。」という判決を書いたものだから大問題になり、結局、裁判官をクビになってしまいました。

［source：］とぼけた裁判官|弁護士法人古庄総合法律事務所｜大分 https://kosholaw.com/teikoku-76.htm
```

　大分地裁の飲酒運転の裁判官の話が、京都地裁の雲助発言の裁判官のこととは意外な話ですが、どこまで本当なのかと疑問も感じつつ、裁判官をクビになったという結末の部分は、本当らしいと感じてしまいました。個人的に弁護士の話は、どれも眉唾です。

```
このような、「功成り名を遂げた」大弁護士達が「一票の格差」訴訟のようないわゆる「金にならない事件」（おそらく、ほとんど「手出し」と思われます）に粉骨砕身するのは何故なのか。「金になる事件に飽いた」「歴史に名を残したい」「最高裁判例を作りたい」「国会議員に任せておけない」など色々な想いはあると考えられますが、根底を流れるのは「法律家としての誇り」なのではないでしょうか。自分の目の前で小さな子どもが苛められていたらそれを止めるのと同じように、自分の目の前で「法の下の平等」が侵されており、被害者の大半がそれを是正する術を知らないのであれば、それを知っている「法律家」として見て見ぬふりはできないのです。その侵害行為を是正するために、「法的知識・法的経験」という武器を使って戦っているのです。彼らの活動は、弁護士という職業が崇高であることを思い出させてくれました。
　自分の「趣味」で仕事をやれて羨ましいとの声も聞こえてきますが・・・。

［source：］金にならない事件|弁護士法人古庄総合法律事務所｜大分 https://kosholaw.com/teikoku-77.htm
```

　次の記事の見出しが「金にならない事件」とあったので、興味をおぼえたものの、最後の方だけ目を通したのですが、一票の格差訴訟のことでした。金になる事件に飽きた、とか歴史に名を残したいなどとありますが、これが認められれば選挙のやり直しで国が傾く負担が出ると聞いたことがあります。

```
ところで、この「一票の格差」訴訟を進めてきたのは２つの弁護士グループです。Ｙ弁護士率いるＡグループは、Ｙ弁護士が４０年以上前から「自分のライフワーク」であると言って、コツコツと続けていました。
　これに対し、Ｍ弁護士率いるＢグループは１０年ぐらい前から活動を始めたようですが、それこそいずれも日本を代表する超○金弁護士の集団です。いわゆる「金持ちの依頼者層」を掴み、主として「金になる事件」をやり、所属事務所は「ブランド事務所」の弁護士達の集団です。特に、代表のＭ弁護士は青色発光ダイオードを発明し今般ノーベル賞を受賞した中村修二氏の代理人となり会社に対して２００億円の特許権侵害訴訟を起こした方です。

［source：］金にならない事件|弁護士法人古庄総合法律事務所｜大分 https://kosholaw.com/teikoku-77.htm
```

　最初から記事を読み直しましたが、一票の格差訴訟は２つの弁護士グループがあり、Y弁護士の率いるAグループは、Y弁護士が40年以上前からコツコツと続けてきたとあります。もう一つがM弁護士が率いるBグループとあります。どちらも久保利英明弁護士のイニシャルは見えません。

```
升永 英俊（ますなが ひでとし、1942年（昭和17年）［1］［2］7月12日［1］ - ）は、日本の弁護士（第一東京弁護士会）・弁理士。米国のコロンビア特別区及びニューヨーク州弁護士。TMI総合法律事務所シニアパートナー。元東京永和法律事務所代表兼東京永和特許事務所顧問。

［source：］升永英俊 - Wikipedia https://ja.wikipedia.org/wiki/%E5%8D%87%E6%B0%B8%E8%8B%B1%E4%BF%8A
```

　「代表のＭ弁護士は青色発光ダイオードを発明し今般ノーベル賞を受賞した中村修二氏の代理人」という部分から調べたところ、見覚えのある升永英俊という弁護士が出てきました。TMI総合法律事務所ともあります。

［link：］ 弁護士プロフィール|弁護士法人古庄総合法律事務所｜大分 https://kosholaw.com/plof.htm

　ホームページだけではなく初めて見る法律事務所名だと思っていたのですが、件名の記載がないものの杵築支部、別府支部とあるので大分県の弁護士事務所のようです。Uターン者の村八分で弁護士会が勧告を出したとかニュースになっていましたが、その後のことは見かけないでいます。

[link:] » 大分　黙秘権 - Google 検索 https://t.co/V81UuhAaAb

[link:] » 黙秘の男性、争う構え　大分女性転落死の損賠訴訟｜【西日本新聞ニュース】 https://t.co/ZgTHX1D0Q4

　検索ですぐに情報が見つかりましたが、2019年1月25日の西日本新聞とあるので、以前読んでいる記事かと思います。愛知県の漫画喫茶店員女性の遺体と不起訴のことも記事中に見えましたが、この黙秘権の問題を見ていてしばらくしてから、3月に4件という性犯罪の無罪判決がありました。

　この2019年3月は、弁護士脳生物が最も活発に蠢いた時期でもありました。春先の木の芽時ということがあったのかは不明です。木の芽時は5月頃と聞いたような気もします。

lawkus ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW lawkus（ystk） 日時：2019/03/29 15:46 URL： https://twitter.com/lawkus/status/1111519997719773185
> つまり自称被害者の言い分を言ったまま認定するのが裁判所の仕事ということね。一方の主張を鵜呑みにするだけなら裁判所は必要ないから裁判制度は廃止して、警察が独断で処罰する制度にしたらいいね。 https://t.co/9VMC9YWDlO
▷▷▷　　　　　End　　　　　▷▷▷

　少し検索をすると、次のまとめ記事になっていましたが、上記の三浦義隆弁護士のツイートも見つかりました。これも余り記憶と印象にはなかったツイートですが、個別にまとめ記事を作成しているので、記録すべきという判断があったことは確かだと思います。

[link:] 2019年03月29日15時51分の登録： ＼ystk　@lawkus＼つまり自称被害者の言い分を言ったまま認定するのが裁判所の仕事ということね。一方の主張を鵜呑みにするだけなら裁判所は必要ないから裁判制度は廃止し http://hirono2014sk.blogspot.com/2019/03/ystklawkus_91.html

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜ok_urtcd（YUKImama） 日時：2019-11-15 02:52／2019/03/29 14:06 URL： https://twitter.com/kk_hirono/status/1195036673559547906 https://twitter.com/ok_urtcd/status/1111494884383297536
> いや少女の言い分とそれを認定しないことは明らかになってるので、ここまで訴えても無罪なり他の事例でも不起訴になるなんてもう無理だわ、万一被害にあってもやられ損だわってことが衝撃なんです https://t.co/k56xhv0Xiw
▶▶▶　　　　　End　　　　　▶▶▶

　上記の三浦義隆弁護士のツイートが公式引用したツイートになりますが、上記にリツイートしたツイートも次の三浦義隆弁護士のツイートを公式引用しています。

lawkus ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW lawkus（ystk） 日時：2019/03/29 12:10 URL： https://twitter.com/lawkus/status/1111465583139119104
> いや内容もわからないのに無罪判決を非難するんだから、（少なくとも一定の類型の事件については）なんでもかんでも有罪にせよという考えが前提にあるとしか解釈しようがないだろ。 https://t.co/c0B2yUQsWg
▷▷▷　　　　　End　　　　　▷▷▷

　返信のない単独のツイートとして表示されていますが、その上記の三浦義隆弁護士のツイートも次のツイートを公式引用していて、久しぶりに見る女性の名前のアカウントですが認証マークがついています。ずいぶんと久しぶりに見かけた気がしますし、どんな人かも思い出すことはないです。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜ikeuchi_saori（池内さおり Saori Ikeuchi） 日時：2019-11-15 02:56／2019/03/29 02:04 URL： https://twitter.com/kk_hirono/status/1195037872308416512 https://twitter.com/ikeuchi_saori/status/1111313161628454914
> なんでもかんでも「有罪にせよ」などと、  言   う   は   ず   が   な   い。  そんなこと一言も求めていない。 裁判や捜査の過程で、  正   義   が  果 たされるよう、  社会を構成する全ての人たちが努力をすべきだ。そのことを、私は問題にしている。
▶▶▶　　　　　End　　　　　▶▶▶

　プロフィールには、日本共産党、前衆議院議員などとありました。「安倍政権の暴走」などとも記載があります。

　「木の芽時」についても確認のため調べたのですが、木の芽が出る季節、春先などとあるだけで、何月ごろという特定は見当たりませんでした。桜前線と同じで地域で違いはあるのだと思いますが、タラの芽の天ぷらがスーパーの惣菜に並ぶ頃と考えても、何月か思い出せません。春でも早い気はします。

　時刻は3時22分です。久しぶりに眠りにつくのが午前4時頃になりそうです。いくらか弁護士脳の毒素を記録として吐き出すことが出来たので、けっこうすっきり感があるのですが、結局、今夜は一度もテレビをつけませんでした。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜tbs_news（TBS NEWS） 日時：2019-11-15 03:24／2019/11/14 19:45 URL： https://twitter.com/kk_hirono/status/1195044785674846209 https://twitter.com/tbs_news/status/1194929277218635776
> 日大アメフト前監督と選手ら３人、“悪質タックル”不起訴へ https://t.co/S1A66WNAHU #tbs #tbs_news #japan #news
▶▶▶　　　　　End　　　　　▶▶▶

　今頃、いきなり不起訴というニュースが出てもしっくり来ないのですが、上記のTBSのニュースのツイートもさきほど落合洋司弁護士（東京弁護士会）のタイムラインでリツイートとして見かけたものです。ツイートが７ｈとして表示されているので、今夜のニュースとなるのでしょう。

［link：］ 日大アメフト前監督と選手ら３人、“悪質タックル”不起訴へ TBS NEWS http://news.tbs.co.jp/newseye/tbs_newseye3830434.html

　リンクを開いて、文字数の少ない記事だと思いましたが、簡潔でよくまとまっているという印象を受けました。落合洋司弁護士（東京弁護士会）のブログ記事では見当たらず、あるいは気が付かなかったのですが、実行犯ともいえる宮川選手本人も不起訴処分というのは意外でした。

　記事の見出しにも「不起訴処分へ」とありますが、本文にも方針を固めた、とあって、このような事前の報道というのも近年は増えてきたという思いを新たにしました。固めた方針が一転したという話は聞かないですが、世論の反応を慎重に確認したいという意図があるようにも思えます。

　さきほど読んだ落合洋司弁護士（東京弁護士会）の記事にも、色々と思うところがありました。同じブログといってもはてなダイアリーからはてなブログへの移行は、サービスの廃止にともなってありますが、共謀罪の反対を落合洋司弁護士（東京弁護士会）の言葉として何度も見かけてきました。

　落合洋司弁護士（東京弁護士会）のツイート全般に対するリツイートの少なさというのも気になっています。数年前のリツイート数は思い出せないですが、今ほど少ないことはなかったように思えますし、それに関わらずフォロワー数に大きな変動がないのも不思議です。

yjochi ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW yjochi（🌸弁護士 落合洋司 https://www.kouenirai.com/profile/8994/） 日時：2019/11/13 21:08 URL： https://twitter.com/yjochi/status/1194587739183702016
> あべちゃんや仲間たちが何をやっても、警察も検察庁も取り締まらないから、やりたい放題だよね。
▷▷▷　　　　　End　　　　　▷▷▷

　上記の落合洋司弁護士（東京弁護士会）のツイートは、リツイートの数が多めの15件となっていますが、内容に見合うだけの根拠がどこにあるのか不思議ですし、言葉の信頼が重要となりそうな弁護士の業務、経営に支障がないのかも気になるし、不思議です。火の車が走っているのかと考えることも。

　日大の危険タックル問題は、さきほどニュースの見出しに「悪質タックル」とあることに気が付きました。当初の報道は悪質タックルで、そのあとに危険タックルという見出しが多かったように思います。火の玉が再び燃え上がったようで、燃え尽きる弁護士業界の行く末をみるようです。

〈〈〈：Emacs： 2019-11-15（金曜日）03：58 　〈〈〈

