#+TITLE: "Windows１０のディスクイメージ（ISOファイル）"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-11-20 09:51:16 +0900
FILE_NAME: 2019-11-20-095116_Windows１０のディスクイメージ（ISOファイル）.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: Linux（Ubuntu）,Windows１０,インストール
記事タイトル名の文字数：27　保存ファイル名の文字数：49
#+STARTUP: showeverything


* 試行のインストールが失敗したもののブートレコードの情報が変わってしまいLinuxが起動できなくなり、一時はファイル全滅の危機：Windows１０のディスクイメージ（ISOファイル）
  CLOCK: [2019-11-20 水 09:59]--[2019-11-20 水 10:46] =>  0:47

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: Linux（Ubuntu）,Windows１０,インストール

〉〉〉：Emacs： 2019-11-20（水曜日）09：59　 〉〉〉

　Windows10のISOファイルのインストールは昨夜の19時40分過ぎから始めた痕跡が残っていますが、いつものLinux（Ubuntu）の環境に戻れたのは深夜の1時40分を過ぎていたと思います。まずい失敗が重なったことで事態を悪化させました。

　Linuxのパーティションは無傷だったのでいずれデータの取り出しは可能と思っていましたが、GRUBの再インストールを試みて、とある情報に従い/boot以下のファイルを全削除したので、一時はレスキューモードでの起動も出来なくなりました。

　レスキューモードでの起動が出来るまでにもいろいろあってトラブルが続きました。別にブートマネージャーをインストールするため異なるパーティションにUbuntuをUSBでインストールしましたが、EFIシステムに絡んでエラーが出たり、BIOSでUSBからの起動も出来なくなりました。

　ブートマネージャーのインストール後も起動に失敗しレスキューモードに入っていたのは、/boot/efiのUUIDが変わっていたためのようでした。久しぶりの大きなトラブルで、今回は最悪だと思いましたが生還ができて本当によかったです。

　Windows10は、試行でハードディスクのパーティションにインストールするつもりでした。以前、Linuxの環境にWindows10をデュアルブートでインストールするのは無理という情報をみたことがありました。

　Windows10のEFI起動は無効にすることもできたはずですが、Windows10をインストールしたあとの設定でしか出来ない可能性があり、インストール時の選択はなかったです。

　もともとWindows10は、別にSSDを買ってそこにインストールする予定でした。しかし、Windows10をメインに使うつもりはないので、いろいろと悩ましい選択肢があります。Windows10のSATAではない外付けUSBからの起動は、出来る情報と出来ない情報がありました。

　Windows10パソコンのことで人に相談を受けたりすると、やはりWindows10の環境が必要だと思い、DSP版の価格について調べたのですが、2ヶ月ほど前とはずいぶん情報が変わっていて、パッケージ版との価格差がなくなったという情報もありました。

　Windows10がISOファイルの配布（ダウンロード）をしていると知ったときは驚きました。Linuxではずっとこの方法でインストールをしてきましたが、Windows10ではパッケージからのDVDインストールかバックアップからのリカバリしか方法がないものと思い込んでいました。

　自分の情報不足も痛感しましたが、ISOファイルからアップデートや再インストールが出来るということは実に画期的、個人的には革命的とも言える、Microsoft社の舵取りです。いつから出来るようになったのかは調べていませんが、情報を見かけなかったのも不思議です。

[link:] » windows10 iso 開始 - Google 検索 https://t.co/aBlRjZgdsQ

　上記の検索結果は2019年つまり今年の情報ばかりです。それ以前の情報はみあたらず、Windows10のバージョンが201909というものからISOファイルが提供開始となった可能性がありそうです。

〈〈〈：Emacs： 2019-11-20（水曜日）10：46 　〈〈〈

