#+TITLE: "布川事件国賠訴訟・警察と検察の違法行為が冤罪を招いたと認める判決"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-11-13 15:23:05 +0900
FILE_NAME: 2019-11-13-152305_布川事件国賠訴訟・警察と検察の違法行為が冤罪を招いたと認める判決.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: ジャーナリストの江川紹子氏,再審,冤罪,国賠
記事タイトル名の文字数：32　保存ファイル名の文字数：54
#+STARTUP: showeverything


* ジャーナリストの江川紹子氏の記事と、その紹介と思われる多数の返信ツイート：布川事件国賠訴訟・警察と検察の違法行為が冤罪を招いたと認める判決
  CLOCK: [2019-11-13 水 15:25]--[2019-11-13 水 18:10] =>  2:45

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: ジャーナリストの江川紹子氏,再審,冤罪,国賠

〉〉〉：Emacs： 2019-11-13（水曜日）15：25　 〉〉〉

```
TW amneris84（Shoko Egawa） 日時： 2019-05-27 17：24 URL： https：//twitter.com/amneris84/status/1132925565743259648
> 画期的な判決。 →布川事件、国と県に賠償命令　「違法捜査で有罪に」訴え https：//t.co/1JJO058drJ

TW amneris84（Shoko Egawa） 日時： 2019-05-27 17：53 URL： https：//twitter.com/amneris84/status/1132932819041177601
> ざっと要旨を読んでみたが、ほんとに画期的。警察官の偽証と検察官の証拠隠しによって、誤った裁判に導かれたことが、明確にされている。この内容、どのくらい丁寧に報じられるかな。 https：//t.co/2K0Ap6SJ6k

TW amneris84（Shoko Egawa） 日時： 2019-05-27 22：45 URL： https：//twitter.com/amneris84/status/1133006264483557377
> 画期的なこの判決の内容を細かく紹介しました　→布川事件国賠訴訟・警察と検察の違法行為が冤罪を招いたと認める判決(江川紹子) - Y!ニュース https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-27 23：10 URL： https：//twitter.com/amneris84/status/1133012568128098304
> @minihakusai1 あ、すみません。「反射的」です。ご指摘ありがとうございます。

TW amneris84（Shoko Egawa） 日時： 2019-05-28 00：00 URL： https：//twitter.com/amneris84/status/1133025298826399745
> @uBYE1devwRZM0gS https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 00：01 URL： https：//twitter.com/amneris84/status/1133025341520302081
> @AkiCrear https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 00：01 URL： https：//twitter.com/amneris84/status/1133025402203516930
> @nekolibe https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 00：01 URL： https：//twitter.com/amneris84/status/1133025471417933824
> @Zi_no0812 https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 00：01 URL： https：//twitter.com/amneris84/status/1133025523896946688
> @3jytuBro https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 00：01 URL： https：//twitter.com/amneris84/status/1133025558692913152
> @vif_bancho https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 00：02 URL： https：//twitter.com/amneris84/status/1133025606994616321
> @kinzo_que https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 00：02 URL： https：//twitter.com/amneris84/status/1133025641727553536
> @lunch_recipe https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 00：02 URL： https：//twitter.com/amneris84/status/1133025684207460354
> @johnkgalbraith https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 00：03 URL： https：//twitter.com/amneris84/status/1133026012545990661
> @ahq2006sp2 https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 00：06 URL： https：//twitter.com/amneris84/status/1133026602164449287
> @fuchikoma1977 https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 00：06 URL： https：//twitter.com/amneris84/status/1133026698516033536
> @zorazora10 https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 00：12 URL： https：//twitter.com/amneris84/status/1133028117126082566
> @ryoukisugi2 https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 00：12 URL： https：//twitter.com/amneris84/status/1133028167394873344
> @troisheures_ https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 00：12 URL： https：//twitter.com/amneris84/status/1133028267278028801
> @gururi https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 00：14 URL： https：//twitter.com/amneris84/status/1133028645017083904
> @riux_riux https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 00：14 URL： https：//twitter.com/amneris84/status/1133028773249466369
> @games_1299s https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 00：14 URL： https：//twitter.com/amneris84/status/1133028812495548416
> @mo09774336 https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 00：24 URL： https：//twitter.com/amneris84/status/1133031247981076481
> @saorititi https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 00：24 URL： https：//twitter.com/amneris84/status/1133031313429032960
> @alohaishi @saorititi https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 00：25 URL： https：//twitter.com/amneris84/status/1133031385097052166
> @goriragorirag16 @ya_ru_14 https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 00：25 URL： https：//twitter.com/amneris84/status/1133031530278711296
> @alsnova https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 00：26 URL： https：//twitter.com/amneris84/status/1133031647572504578
> @EF61501 https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 00：39 URL： https：//twitter.com/amneris84/status/1133034881737469953
> @chaochaochao12 https：//t.co/x4ZoVe0GXe

TW amneris84（Shoko Egawa） 日時： 2019-05-28 00：39 URL： https：//twitter.com/amneris84/status/1133034965313118209
> @kyana16180 https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 00：39 URL： https：//twitter.com/amneris84/status/1133035054072860672
> @AUCHAN_J https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 00：41 URL： https：//twitter.com/amneris84/status/1133035423557488640
> @NaRrEwkwqjlbTdJ https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 07：51 URL： https：//twitter.com/amneris84/status/1133143736857186305
> おはよございますにゃん。

RT amneris84（Shoko Egawa）｜iy0kahn（Smith目） 日時：2019-05-28 07：55／2019-05-28 06：57 URL： https：//twitter.com/amneris84/status/1133144612313296896 https：//twitter.com/iy0kahn/status/1133130174717784066
> いろいろと画期的な判決だったんやなー。 \n \n 布川事件国賠訴訟・警察と検察の違法行為が冤罪を招いたと認める判決(江川紹子) - Y!ニュース https：//t.co/yZ4JLkkylK

TW amneris84（Shoko Egawa） 日時： 2019-05-28 08：01 URL： https：//twitter.com/amneris84/status/1133146263128424449
> @TqKOQtsyEVnMLlV https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 08：01 URL： https：//twitter.com/amneris84/status/1133146346037235713
> @Kouji7777x https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 08：02 URL： https：//twitter.com/amneris84/status/1133146455256981504
> @7wbxbET8cDUr6SR https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 08：02 URL： https：//twitter.com/amneris84/status/1133146552636076032
> @tyabaken114 https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 08：03 URL： https：//twitter.com/amneris84/status/1133146711310782464
> @runshiwa @high_kick_coun https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 08：03 URL： https：//twitter.com/amneris84/status/1133146792319602693
> @asakaze_hakata https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 08：04 URL： https：//twitter.com/amneris84/status/1133146887907733504
> @ESKwEGj4tUuU27s https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 08：04 URL： https：//twitter.com/amneris84/status/1133147008082907137
> @kelog21 https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 08：05 URL： https：//twitter.com/amneris84/status/1133147176677257216
> @yatch8416 https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 08：06 URL： https：//twitter.com/amneris84/status/1133147373616582656
> @anti_jcp https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 08：06 URL： https：//twitter.com/amneris84/status/1133147532429631488
> @fuji500hg https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 08：12 URL： https：//twitter.com/amneris84/status/1133149085169401856
> 令和初の国賓おもてなしは「安倍―トランプ選挙互助会」の発動だった(田中良紹) - Y!ニュース https：//t.co/crqONrqVdN 安倍氏は自分の選挙のためにトランプ氏の選挙に協力することを約し、その結果、貿易交渉は… https：//t.co/zlXJqma4MN

RT amneris84（Shoko Egawa）｜LifeCounterX（みうら） 日時：2019-05-28 08：19／2019-05-28 08：07 URL： https：//twitter.com/amneris84/status/1133150746814308352 https：//twitter.com/LifeCounterX/status/1133147760205520896
> こういう、冤罪被害者に寄り添うような判決を出してくれるのはいいね。これが当たり前になってほしい \n \n 布川事件国賠訴訟・警察と検察の違法行為が冤罪を招いたと認める判決(江川紹子) - Y!ニュース https：//t.co/3cwhsuBVF6

TW amneris84（Shoko Egawa） 日時： 2019-05-28 10：08 URL： https：//twitter.com/amneris84/status/1133178093533712384
> @tamai1961 (=^x^=)/

RT amneris84（Shoko Egawa）｜jimihen_70（じみへん） 日時：2019-05-28 10：11／2019-05-28 09：52 URL： https：//twitter.com/amneris84/status/1133178946051121152 https：//twitter.com/jimihen_70/status/1133174183955816448
> 布川事件国賠訴訟・警察と検察の違法行為が冤罪を招いたと認める判決(江川紹子) - Y!ニュース https：//t.co/JOmXnfS58Q　ここまで明確に警察と検察の違法性を指摘したのって聞いたことない。まぁ、そんな主張を唯々諾々と認めて来たこれまでの裁判所も同罪だけどね。

TW amneris84（Shoko Egawa） 日時： 2019-05-28 14：22 URL： https：//twitter.com/amneris84/status/1133242240015273984
> 「長期間にわたる立法不作為に過失がある」と述べ、法改正手続きを放置した責任を認めた、と。真っ当な判決 →最高裁国民審査、海外在住者が参加不可能な現行制度は違憲　東京地裁 - 毎日新聞 https：//t.co/6hu3jPXzGr

RT amneris84（Shoko Egawa）｜gmen0208（G-men） 日時：2019-05-28 18：24／2019-05-28 10：54 URL： https：//twitter.com/amneris84/status/1133303013349527555 https：//twitter.com/gmen0208/status/1133189765153452032
> 検察が不利（被告に有利）となる証拠を開示請求されているのにも拘わらず開示しない、複数の警察官が偽証する・・・こんな理不尽な裁判があるのか、そして結果として真犯人は逃している \n https：//t.co/HZSyeUtEX8

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：27 URL： https：//twitter.com/amneris84/status/1133303737617747968
> @339825tj @fjedpo https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：27 URL： https：//twitter.com/amneris84/status/1133303841439379456
> @fhKrqPFgDA4xJIA https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：28 URL： https：//twitter.com/amneris84/status/1133303955956543488
> @chouzethu777 https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：28 URL： https：//twitter.com/amneris84/status/1133304097438879745
> @speedman737 https：//t.co/x4ZoVe0GXe

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：29 URL： https：//twitter.com/amneris84/status/1133304172097429505
> @kotagucchiguchi https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：29 URL： https：//twitter.com/amneris84/status/1133304277017931777
> @haruka_azan https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：30 URL： https：//twitter.com/amneris84/status/1133304531188473856
> @kisaragi6458 https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：31 URL： https：//twitter.com/amneris84/status/1133304656145162240
> @013Yct0YzzCbo1A @kait8823 @sorafune55 https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：31 URL： https：//twitter.com/amneris84/status/1133304766212108288
> @bluefac45067700 @mainichiphoto https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：31 URL： https：//twitter.com/amneris84/status/1133304861829713920
> @DVMJ1 @GUNHEDun507 https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：32 URL： https：//twitter.com/amneris84/status/1133304939181035520
> @QL8xPGHWNH6EPjO https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：32 URL： https：//twitter.com/amneris84/status/1133305052771209216
> @chiichanyukicha https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：32 URL： https：//twitter.com/amneris84/status/1133305128365150208
> @rhrnjj https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：33 URL： https：//twitter.com/amneris84/status/1133305239816159233
> @silverbridge https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：33 URL： https：//twitter.com/amneris84/status/1133305372309987329
> @chigasakiyt https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：34 URL： https：//twitter.com/amneris84/status/1133305517428727809
> @bCqKgKeVWrTXxHk https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：34 URL： https：//twitter.com/amneris84/status/1133305623624294400
> @chikachika02271 https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：35 URL： https：//twitter.com/amneris84/status/1133305726842036225
> @touchi_0083 https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：35 URL： https：//twitter.com/amneris84/status/1133305788854759424
> @6QQdiooXIgJdrat https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：35 URL： https：//twitter.com/amneris84/status/1133305849932177410
> @oncrazy8823 https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：36 URL： https：//twitter.com/amneris84/status/1133306055226580992
> @wa4no10chi https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：36 URL： https：//twitter.com/amneris84/status/1133306127557353472
> @okonomimarutaka https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：37 URL： https：//twitter.com/amneris84/status/1133306258092462080
> @balibalihoo https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：37 URL： https：//twitter.com/amneris84/status/1133306357833056257
> @karasudo19 https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：38 URL： https：//twitter.com/amneris84/status/1133306433603158016
> @oziozi5151 @nyandora222 @netouyo38 https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：39 URL： https：//twitter.com/amneris84/status/1133306808498397184
> @twimaru2134 https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：39 URL： https：//twitter.com/amneris84/status/1133306896398442496
> @e_paoh https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：40 URL： https：//twitter.com/amneris84/status/1133306949527715840
> @mizuho17459715 https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：56 URL： https：//twitter.com/amneris84/status/1133311167797981184
> ほんとに理不尽な事件だからこそ、〈社会はあなたの命を軽視していないし、死んでほしいと思っている人間など1人もいない、という強いメッセージを発していくべき時〉と。 →川崎殺傷事件「死にたいなら一人で死ぬべき」という非難は控えてほしい… https：//t.co/fEPTHXYFD0

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：57 URL： https：//twitter.com/amneris84/status/1133311344520749058
> @jacaranda0719 https：//t.co/x4ZoVeihOM

TW amneris84（Shoko Egawa） 日時： 2019-05-28 18：57 URL： https：//twitter.com/amneris84/status/1133311413177397248
> @http_bingo https：//t.co/x4ZoVeihOM


［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： @amneris84（Shoko　Egawa）のツイート　”．＊”　3229／3229：2019-03-21_1145〜2019-11-13_1202　2019年11月13日15時06分の記録 https://hirono2014sk.blogspot.com/2019/11/amneris84shokoegawa322932292019-03.html
```

　https：//t.co/x4ZoVeihOM という短縮URLを、上記のページでページ内検索すると、結果は67件となっていました。全てではないと思いますが、そのほとんどは1つから3つのメンションのみを指定した返信ツイートになります。

　先日、ジャーナリストの江川紹子氏のTwitterタイムラインをずっと遡っていたときも、延々と同じTwitterカードの表示があったのですが、これほどの数とは思っておらず、20件から多くて30件程度と思っていました。

　Twitterカードというのは、今調べて確認した用語ですが、以前はブログカードとして情報を見たようにも思います。調べないと出てくる情報ではないので、この用語を知っている人は少なそうですが、Twitterの利用では、日々、ごく普通に見かけているものだと思います。

```
Twitterカードとは、ツイートに貼り付けられた記事へのリンクを魅力的に見せる機能のことです。具体的にはツイートの中に「アイキャッチ画像」や「記事のタイトル」などが表示されるようになります。

［source：］【2019年版】Twitterカードとは？使い方と設定方法まとめ https://saruwakakun.com/html-css/reference/twitter-card
```

　67件と確認した上記の短縮URLは、次の記事へのリンクとなっており、その記事にTwitterカードの設定があるのでツイートに表示がされているのではと考えます。ちなみに、はてなブログではembed記法とかで、同様の表示が実現できたかと思います。

　embedはHTMLタグにもあって、以前調べたところ埋め込みという意味のようでした。JavaScriptを使った表示になるのかと思いますので、JavaScriptの使用が出来ないブログでは、そのままHTMLのタグのソースが表示されるのかもしれません。

布川事件国賠訴訟・警察と検察の違法行為が冤罪を招いたと認める判決(江川紹子) - 個人 - Yahoo!ニュース https://news.yahoo.co.jp/byline/egawashoko/20190527-00127594/

　記事の配信時刻は5月27日22時44分のようです。配信時刻と思われる部分に年はないですが、URLに20190527-00127594とあります。年月日の部分はそのまま合っているようですが、時刻の部分に一致はみられず、数字の羅列の意味は不明です。

　先日、この記事を見たか、読んだ後、余り読んだ記憶のない記事だと思ったのですが、Twilogで確認をしたところ記事のタイトルとURLのツイートがあったので、その場でリンクを開き、読んでいた可能性は高いと思います。

　3日か4日前の発見だったと思いますが、すでに記憶がはっきりしなくなっているので、スクリーンショットの記録で正確な時系列を確認しておきたいと思います。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-13 15:57／2019/11/10 15:55 URL： https://twitter.com/kk_hirono/status/1194509457998237696 https://twitter.com/hirono_hideki/status/1193421949965176832
> 2019年11月10日11時32分の登録： REGEXP：”布川事件国賠訴訟・警察と検察の違法行為が冤罪を招いたと認める判決”／データベース登録済みツイート：2019年11月10日11時31分の記録：ユーザ・投稿：14／22件 https://t.co/PwQpIHg8AA
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「布川」の検索結果 - Twilog https://t.co/Xul2b1lyn5

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2019年11月10日 - Twilog https://t.co/HsqtopXoSp

[link:] » 非常上告-最高検察庁御中_ツイッター(@s_hirono)/2019年11月10日 - Twilog https://t.co/FyTWzwf3bb

[link:] » 非常上告-最高検察庁御中_ツイッター(@s_hirono)/2019年11月11日 - Twilog https://t.co/jT7a2B8wVh

　どうもスクリーンショットの作成というのは実行していなかったようです。他により意識が集中していたということも考えられますが、記録の必要性を強く感じていなかったことは間違いなさそうです。

　11月10日より前に「布川」をキーワードに含むツイートは、Twilogで8月29日となっているので、ジャーナリストの江川紹子氏のTwilogで布川事件に関するツイートを見たのも11月10日間違いありません。

　11月10日に「布川」をキーワードに含むツイートは、ジャーナリストの江川紹子氏のツイートのリツイートが1件の他、5件のツイートがありますが、これは布川事件の国賠訴訟に関する最新情報を探していた時の痕跡と記録です。

　探して確認したかったのは、布川事件の国賠で7600万円という賠償命令の判決を受けた国と県が、控訴をしたか否かという情報でしたが、確認できる情報は見つからず、未だに確認は出来ていません。これこそ賠償命令の一審判決以上に大きな大発見だと思いました。

　ツイートにある産経ニュースの見出しを見ると、判決は東京地裁となっています。これは検察が相手で国が当事者なのでそうなのかと理解しますが、この国賠訴訟で県とあるのは、茨城県警の茨城県に違いはないと考えます。この布川事件の布川も茨城県の地名となっていたはずです。

　もっとも私の知る範囲で、再審請求で地名以外の名前が事件名となっているのは、吉田巌窟王事件と呼ばれたずいぶん古い再審事件と、静岡県清水市（現在は静岡市清水区）の袴田巌さんの袴田事件のみです。入念に調べれば他にも出てくるかもしれないですが、今のところこの２つです。

　間際らしいものとしては松山事件というのがあって、テレビでも情報を見かけたことがなく余り知られていない事件だと思いますが、愛媛県松山市と考えそうなところ、調べると宮城県の事件でした、旧古川市となっていたように思いますが、現在は大崎市となっていて、大崎事件と混同しそうです。

```
松山事件（まつやまじけん）は、1955年（昭和30年）10月18日に、宮城県志田郡松山町（現大崎市）にて発生した放火殺人事件と、それに伴った冤罪事件である。四大死刑冤罪事件の一つ（免田事件、財田川事件、松山事件、島田事件）。日本弁護士連合会が支援していた。

［source：］松山事件 - Wikipedia https://ja.wikipedia.org/wiki/%E6%9D%BE%E5%B1%B1%E4%BA%8B%E4%BB%B6
```

　確認のため調べたところ、旧古川市ではなく宮城県志田郡松山町となっていましたが、現在は大崎市となっていて、これは古川市と同じだと思います。なお、私が宮城県に土地勘があるのは金沢市場輸送の長距離トラック運転手の仕事で一番多かったのが、石巻・塩釜の東北便だったからです。

　ざっと記事に目を通していたところ、示談の成立している傷害事件を別件とあって思い出したのですが、昨日、愛知県瀬戸市で冷蔵庫から母親の白骨遺体が発見されたという事件で、スーパーで何かを1個盗んだ容疑で家宅捜索と昼から報道があったのですが、夜のテレビの字幕に「おととし」とありました。

　字幕の表示が間違えていたのかとも思えてきたのですが、それでなくても家宅捜査のための別件逮捕になりそうです。こういう別件逮捕を問題視する声は薬物以外に弁護士からあがってくるのは不思議と見かけないのですが、ドライバーのことで気になる記事を前田恒彦元検事が書いていました。

　マイナスドライバーの所持で逮捕というネットの小さなニュースでしたが、最初に石川県警察の逮捕ということで関心を持っていました。法クラのツイートで少し見かけていたものだと思いますが、これもしばらく間をおいてから、前田恒彦元検事が出処らしいと知るに至りました。

　現場が金沢市内の野球場の駐車場となっていましたが、県立野球場のことかと思いました。昭和62年頃と同じ場所であれば、国道8号線沿いに一光のガソリンスタンドがありました。すぐ側に野球場があることも知っていたのですが、車が出入りする様子は見たことがなく、不思議に思っていました。

```
金沢市内にある野球場の駐車場で車の中にマイナスドライバーを隠し持っていたとして、71歳の男が現行犯逮捕されたと、石川県のローカルテレビ局の石川テレビ、FNNプライムオンラインが報じている。しかし、このニュースが今ネット上で物議を醸しているようだ。

［source：］マイナスドライバー所持で逮捕？ネットで警察への批判の声が殺到 - まぐまぐニュース！ https://www.mag2.com/p/news/423334
```

　石川県内ニュースとしてテレビで見た記憶はないのですが、野球場の住所を確認したいと調べたところ、上記の記事がGoogle検索のトップ近くに出てきました。ツイートのまとめサイトのようにもなっていますが、石川県警察本部の看板と、上級国民というワードが見えます。

```
未明という時間帯や場所、男性が無職であるうえ、その時間・場所で規制の対象となるマイナスドライバーを隠匿携帯している合理性がないこと、男性は「ガスライターの火力を調整するために持っていた」と供述しているものの、火力調整部分と適合しないなどその説明が不自然であることなどから、警察は「業務その他正当な理由による場合」には当たらないと判断した。

　むしろ、おそらくは付近で夜間の事務所荒らしなどが相次いでおり、警察官がパトカーで警戒中に男性の車両を発見したとか、パトカーの無線で男性の前歴照会をした結果、石川やその周辺でマイナスドライバーなどを使った事務所荒らしの前歴が判明したといった事情があったのではなかろうか。今後は、侵入窃盗の余罪掘り起こしが捜査のポイントとなるだろう。（了）

［source：］マイナスドライバーを1本持っていただけで現行犯逮捕　そのワケとは？(前田恒彦) - 個人 - Yahoo!ニュース https://news.yahoo.co.jp/byline/maedatsunehiko/20191111-00150358/
```

　「おそらくは付近で夜間の事務所荒らしなどが相次いでおり、警察官がパトカーで警戒中に男性の車両を発見したとか、パトカーの無線で男性の前歴照会をした結果、石川やその周辺で」などとかなり踏み込んだ推測が記述してあると思った前田恒彦元検事の記事になります。

　憶測などと他の法クラ弁護士から批判を受けそうな感想を持っていたのですが、しばらくして肯定的な評価として見かけるようになったのがモトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインを中心にした池袋暴走母子死亡事件に関する前田恒彦元検事の記事でした。

　マイナスドライバーの大きさは不明ですが、用法上の凶器というわけではなさそうです。よく見ると前田恒彦元検事の記事に「男性の逮捕容疑は「特殊開錠用具の所持の禁止等に関する法律違反」だった。」とありました。

[link:] » 石川県立野球場 - Wikipedia https://t.co/Rzn41zhf3r \n 石川県立野球場（いしかわけんりつやきゅうじょう）は、石川県金沢市の西部緑地公園にある野球場。

　調べたところ、石川県立野球場は想像していたのと全く違った場所にありました。産業展示館と同じ敷地に野球場があるというのも今回始めて知ったのですが、金沢西インターの近くで、陸上競技場があるらしいことはテレビで見て知っていました。

[link:] » 金沢市民野球場 - Google マップ https://t.co/t4kEETbIVK

　私が石川県立野球場と取り違えて勘違いしていたのは、調べたところ上記の金沢市民野球場でした。Googleマップには写真も表示されていて、外野席は観戦席もなく網のネットにでもなっているようです。住所が金沢市磯部町となっていて、少し思い出した気分になりましたが、海から離れているのに。

　Googleマップの航空写真でみたところ、磯部町の辺りは現在でも田畑が多いようです。石川県立病院の横と裏手にも田畑が見えますが、平成の初め頃に比較し、ずいぶんと住宅地が増えているのだと思いました。

```
署によると、食品店で万引した疑いがあるとして窃盗の疑いで、この家に住む無職の男（５８）を逮捕し、家宅捜索していた。冷蔵庫内の遺体にはタオルが掛けられていた。

　男は父母と暮らしていたが、いずれも数年前に死亡。母親の火葬は確認されておらず、男の妹とも連絡が取れないという。

（中日新聞）

［source：］瀬戸の民家で冷蔵庫から遺体発見　窃盗容疑の家宅捜索中：社会：中日新聞(CHUNICHI Web) https://www.chunichi.co.jp/s/article/2019111290135309.html
```

　本当に「おととし」だったのか確認のため調べたのですが、妹とも連絡が取れないというのは、テレビの報道で見ていない情報だと思います。姉かと理解していたのですが、仲が悪く口喧嘩をしていたということは付近住民の話として出ていたものがあり、関連性に疑問を感じていました。

```
瀬戸市内の商業施設でカップ麺１個を盗んだとして逮捕し、その後の家宅捜索で遺体を見つけました。

［source：］住宅の冷蔵庫から白骨遺体　家宅捜索の警察官が発見　愛知・瀬戸市 ： 中京テレビＮＥＷＳ https://www2.ctv.co.jp/news/2019/11/12/71249/
```

　やはりカップ麺1個でした。上記の記事に商業施設とありますが、テレビではそのスーパーの映像が出ていて、バローの店舗でした。ネットでは岐阜県に本社があるという情報も見かけたことがありますが、平成14年の時点で羽咋市内にもバローの店舗がありました。

```
１２日午前９時１５分ごろ、愛知県瀬戸市東山町１丁目の住宅を家宅捜索していた愛知県警の警察官が、業務用の冷凍庫に性別不明の遺体が入っているのを見つけた。県警は死体遺棄事件として調べている。

　瀬戸署によると、この日、２０１７年に瀬戸市内のスーパーでカップ麺を万引きしたという窃盗容疑で無職の男（５８）を逮捕し、男の自宅を捜索していた。遺体は、冷凍庫の中でひざを折った格好で入っており、服は着ておらず、タオルが掛かっていたという。

［source：］カップ麺の万引き容疑で家宅捜索→業務用冷凍庫から遺体：朝日新聞デジタル https://www.asahi.com/articles/ASMCD5CVHMCDOIPE019.html
```

　一昨年ではなかったですが、2017年という時期を特定した記事が見つかりました。記事の見出しを見て思い出したのですが、昨日のテレビでの１つの放送だけ、業務用の冷蔵庫と報道をしていました。現物なのか疑問でしたが、ずいぶん大きな業務用冷蔵庫がテレビに出ていたとも思います。

　この万引き容疑での家宅捜索のニュースに意識が集中したのは、先日の元タレント、田代まさし、の宮城県警の逮捕があったからで、それをいくらか批判的に問題視し無罪の可能性もあるかのように取り上げていたのも、前田恒彦元検事ではなかったかと思います。これもざっと確認します。

```
そのうえで、清掃係の供述や清掃後に作成するチェック表などに基づき、直前の宿泊客が部屋を出た後、机の引き出しの中や浴室、ゴミ箱などを含めて室内を徹底的に清掃しており、その段階では覚せい剤や注射器など存在しなかったという事実を立証しなければならない。

　もちろん、田代氏の前に宿泊した複数の宿泊客らからも、覚せい剤や注射器などには身に覚えがないという供述を得ておく必要がある。

　ただ、ベッドと壁の隙間やベッドの下から覚せい剤が発見されたということだと、清掃係が毎回そこまで完璧に清掃しているかは微妙だから、いつ誰が持ち込んだのか特定できないといった事態になるかもしれない。

　警察が8月に(1)の容疑を察知したあと、すぐに逮捕せずに11月に至ったのは、(1)の証拠がやや弱く、覚せい剤も微量だったことなどから否認が予想されたため、新たに覚せい剤を入手したといった情報が得られるまでの間、田代氏を泳がせていたからではなかろうか。

　(2)のように本人の自宅や所持品から覚せい剤が発見されれば、所持罪で現行犯逮捕することが可能となる一方、本人も申し開きなどできなくなるからだ。

［source：］田代まさし氏、5度目の逮捕　同種前科があっても難しい捜査、今後の焦点は？(前田恒彦) - 個人 - Yahoo!ニュース https://news.yahoo.co.jp/byline/maedatsunehiko/20191109-00150085/
```

　記事の配信時刻と思われる記載は11月9日7時30分となっているので、私がそれ以前にこの記事を目にしたことはあり得ないことになりますが、一連３つの気になる前田恒彦元検事のYahooニュースの記事を目にしたのは、これが最初だったかもしれません。一週間ほどでずいぶん集中しています。

　前田恒彦元検事の記事というのは、これまでにもいくつか見かけて読んで来ましたが、けっこう間があって、忘れていた頃という感覚もともなっていたように思います。いずれ近いうちにテレビで姿を見ることもあるのかもしれません。

　この前田恒彦元検事については、だいぶん前になりますが、ジャーナリストの江川紹子氏が吐き捨てるようなツイートで全面否定していると印象を受けたことがありました。あいまいな記憶となっていますが、これもTwitter検索で調べて確認をしておきます。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2019-11-13 17:53／2010/09/23 15:03 URL： https://twitter.com/kk_hirono/status/1194538672516812800 https://twitter.com/amneris84/status/25283284572
> ついでがあったので確認しました。弘中弁護士、噂を聞いて大笑い。「１００％ありえない。それじゃマッチポンプになっちゃう」と。納得した？ RT @tetsumura @iwakamiyasumi @ozyszm: .@amneris84 “前田検事当人が敵役の弘中さん指名で可視化要求
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2019-11-13 17:52／2010/09/28 17:44 URL： https://twitter.com/kk_hirono/status/1194538610441121792 https://twitter.com/amneris84/status/25767688610
> 前田検事を偽証罪で告発でせうRT @neokota: 保釈申請するのかなRT @amneris84: おお、いよいよですかRT @yjochi: しかし、被告発人が大阪拘置所在監中、職業 検事、なんていう告発状を書くことになるとは思わなかったたな。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2019-11-13 17:52／2010/10/03 13:09 URL： https://twitter.com/kk_hirono/status/1194538495714291712 https://twitter.com/amneris84/status/26235836532
> 逮捕された前田検事の取り調べ状況、最高検から朝日にダダ漏れ状態の観あり。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2019-11-13 17:51／2010/10/13 17:11 URL： https://twitter.com/kk_hirono/status/1194538382027710464 https://twitter.com/amneris84/status/27222193891
> 前田検事が手がけた事件の洗い直しの件。「弁護士などから、意見書でも上申書でも、この事件がおかしいから点検してくれないかと指摘をされた件からやっていく。具体的に、ここが問題と言われないと、事件も多いしなかなか難しい」と。物的証拠のみならず、供述証拠も対象にするとのこと
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2019-11-13 17:51／2010/10/15 08:53 URL： https://twitter.com/kk_hirono/status/1194538308656746498 https://twitter.com/amneris84/status/27388820162
> 命名、フロッピー前田 RT @sssfukuma  自分達の事、自分で調べて、それが客観的調査と言えるのだろうか？　まるで最高検がフロッピー前田を取り調べると同じ事ではないか。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2019-11-13 17:51／2010/11/02 09:57 URL： https://twitter.com/kk_hirono/status/1194538265904238593 https://twitter.com/amneris84/status/29423782182
> 拝読しました RT @shiminnokai21前田恒彦元大阪地方検察庁特捜部検事を、 本日、特別公務員職権濫用罪(刑法第194条)にて刑事告発いたしました．告発状は http://bit.ly/9p3dI1
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2019-11-13 17:51／2010/12/09 09:02 URL： https://twitter.com/kk_hirono/status/1194538219708149761 https://twitter.com/amneris84/status/12658277921849344
> （続）無実の人を組織を挙げて犯罪者に仕立てようとしたことについての発言は、誰からもなかった。FD改ざんとそれ以外のこと（無理な取り調べで事実に反する調書を作成したことや、FD改ざんを知りつつ裁判を続けたことなど）を分離して考え、前田元検事の個人的な不祥事として考えているのでは？
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2019-11-13 17:51／2010/12/16 08:06 URL： https://twitter.com/kk_hirono/status/1194538179157614592 https://twitter.com/amneris84/status/15180989428928512
> よっぽど深い仲なのかにゃ？ RT @nobuyoyagi 朝日はなんでも一番最初に知っているのが素敵ですね RT @crusing21: 最高検は、前田元検事について、公務員職権濫用罪での告発について不起訴とする方針を決めたとの報道。http://bit.ly/h89ZAE
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2019-11-13 17:50／2011/02/07 18:58 URL： https://twitter.com/kk_hirono/status/1194538066410524673 https://twitter.com/amneris84/status/34551624466694144
> 前田元検事は、完全密室で時に号泣するなど種々の不可解な言動を重ねたうえ、、小沢氏の逮捕や同氏宅の捜索を行わない見返りに検察側の筋書き通りの自白をするよう大久保元秘書に迫った、と。検察側もさすがに前田元検事の調書の証拠請求は撤回したが、特捜部ではこういう取り調べが横行しているのか…
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2019-11-13 17:49／2014/06/02 00:22 URL： https://twitter.com/kk_hirono/status/1194537637064794112 https://twitter.com/amneris84/status/473122350058074112
> .@hKodama 村木さんも家族も何ら謝罪を受けていない…ということでは、不足ですか。なぜ謝罪をしないのかは、私にではなく、ご自身で前田元検事に聞いてみたらどうでしょう。ツイッターやFacebookをやっておられるようですから
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2019-11-13 17:48／2012/01/13 20:43 URL： https://twitter.com/kk_hirono/status/1194537458110611457 https://twitter.com/amneris84/status/157789786223017985
> 物証の改ざんをするのはハードル高いけど、捜査報告書をでっち上げちゃうのは、それほどでもないの鴨。前田元検事の改ざんが発覚した後、大阪で検事が公判前整理手続き中に、警察の捜査報告書から、被疑者のアリバイ主張を書いた部分を消させるなどの改ざんやったの発覚したし。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2019-11-13 17:48／2014/06/01 20:55 URL： https://twitter.com/kk_hirono/status/1194537399973318656 https://twitter.com/amneris84/status/473070400654417921
> 前田元検事、村木さんにただの一度も詫びてないのに、「改めておわび」とは、これいかに　→＜証拠は誰のものか？＞前田元検事が取り調べ可視化訴える（毎日新聞） - Y!ニュース http://t.co/Om2Jd6YtW1
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2019-11-13 17:47／2012/02/08 09:14 URL： https://twitter.com/kk_hirono/status/1194537321544073218 https://twitter.com/amneris84/status/167038531502485504
> 前田元検事の証言、そして今回の証拠リストの開示拒否…検察庁が、被疑者に有利な証拠は隠し不利な証拠のみを検審に送ることで議決を操作した疑惑は、いよいよ濃厚になってきた、と言うべきだろう。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2019-11-13 17:47／2011/12/16 18:14 URL： https://twitter.com/kk_hirono/status/1194537253437001728 https://twitter.com/amneris84/status/147605598056357888
> 前田元検事は応援で呼ばれ、東京地検に行った時、木村主任検事から、「この件は特捜部と小沢との全面戦争だ。小沢を挙げられなかったら、特捜部の負けだ。恥ずかしい話だが、東京には割り屋がいない。大阪の割り屋に頼ることになった」と言われた、と証言。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2019-11-13 17:47／2011/12/16 12:23 URL： https://twitter.com/kk_hirono/status/1194537188827877377 https://twitter.com/amneris84/status/147517186452361216
> 前田元検事、当時の佐久間東京地検特捜部長が、４億円の原資はすべて建設会社からの裏献金という見立てをしていたことを「夢物語」「妄想」とバッサリ。積極的だったのは佐久間部長、木村主任、それに最高検の大鶴検事くらいで、現場はすっかり厭戦ムードだったと証言した。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2019-11-13 17:46／2011/12/16 15:31 URL： https://twitter.com/kk_hirono/status/1194537115637301248 https://twitter.com/amneris84/status/147564446229868545
> 午後も続く前田独演会。「私が裁判長なら、小沢さんは無罪です」。ＦＤ偽造発覚後、上司のみしじで作成した嘘の筋書きの上申書が話題になり、弁護人が示そうとするも指定弁護士が前田の人格配慮して反対、裁判長も示さず尋問するよう指示するのに対し、「示した方がいいと思いますよ」と。法廷内爆笑
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » (7) 前田 (from:amneris84) - Twitter検索 / Twitter https://t.co/8hgX9Lt4FK

　思いの外、検索結果のツイートが多かったということもあり、ざっと目を通し、気になったものをリツイートしましたが、前田恒彦元検事と陸山会事件の関係というのも記憶にはなく、それらしい情報があったかもしれないと思い出す程度でした。

　前田恒彦元検事が刑事告発されていたという話も、あったかもしれないと思い出す程度です。ジャーナリストの江川紹子氏は、決定的に前田恒彦元検事を罪人と断罪しているようですが、フロッピーディスクの偽造と村木厚子さんの無罪判決の関連性というの、布川事件の国賠の控訴と同じく未確認です。

　本来は犯罪成立の証明が不十分ということで、再審請求を後押しする印象が強いジャーナリストの江川紹子氏ですが、職務に圧殺された苦し紛れに、ふとした出来心で、立証の整合性を保つために証拠品のフロッピーディスクに手を加えた可能性はどうなのかと、ずっと前から考えがありました。

　この構図は、森友加計問題での省庁の対応に当て嵌まるとも考えながら、連日のテレビの報道を見ていた時期がありました。ここ数日もその再来とも思える「桜を見る会」の問題が勃発しており、さきほどの夕方のニュースでは、来年の「桜を見る会」が中止に決まったという報道がありました。

　省庁の名前は思い出せないですが、佐川という人が集中砲火、艦砲射撃の的になっているようで凄まじかったです。その再来とも思えたのが、池袋暴走母子死亡事件の被疑者ですが、これも上級国民と理屈が合体し、異様な様相を感じてきました。

〈〈〈：Emacs： 2019-11-13（水曜日）18：10 　〈〈〈


