#+TITLE: "７月９日以降見当たらない、大崎事件の最高裁決定に関するジャーナリストのツイート、ネット記事の記録"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-10-01 10:37:24 +0900
FILE_NAME: 2019-10-01-103724_７月９日以降見当たらない、大崎事件の最高裁決定に関するジャーナリストのツイート、ネット記事の記録.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: ジャーナリストの江川紹子氏,大崎事件,最高裁
記事タイトル名の文字数：48　保存ファイル名の文字数：70
#+STARTUP: showeverything


* ７月９日以降見当たらない、大崎事件の最高裁決定に関するジャーナリストのツイート、ネット記事の記録
  :LOGBOOK:
  CLOCK: [2019-10-01 火 10:39]--[2019-10-01 火 12:13] =>  1:34
  :END:

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: ジャーナリストの江川紹子氏,大崎事件,最高裁

〉〉〉：Emacs： 2019-10-01（火曜日）10：39　 〉〉〉

　まずは、３，４日ほど前に改良を加えたtu4という自作スクリプトで作成したツイートのまとめ記事からスクリプトのご説明をまじえてご紹介したいと思います。

[link:] » 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中: @amneris84（Shoko　Egawa）のツイート　”大崎事件”　22／3227：2019-02-09_2151〜2019-10-01_0914　2019年10… https://t.co/FO9RWFlbyW

　このまとめ記事は「tu4 amneris84 大崎事件」という自作コマンドの実行で作成しました。このスクリプトでは記事の内容の生成に続き投稿するという自動化の処理までは行っておらず、クリップボードに投稿用の文字列をコピーし、貼り付けることで実行できるようにしています。

　次が実際のクリップボードのテキストであり、実行する自作コマンドになります。

arg-bpost.py "@amneris84（Shoko　Egawa）のツイート　”大崎事件”　22／3227：2019-02-09_2151〜2019-10-01_0914　2019年10月01日10時20分の記録　：embed"

　arg-bpost.pyというコマンドに文字列のテキストを引数として１つ渡しているだけですが、これがBloggerのブログへの投稿時のタイトル指定になります。

　次がスクリプトでのプログラムのコードになります。

```
title = "@#{u.screen_name}（#{u.name}）のツイート　”#{keyword}”　#{mcount}／#{@tweets.size}：#{@tweets.last[/.+日時：[ ]?([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}).+/, 1].to_s.gsub(/ /,'_').gsub(/:/,'')}〜#{@tweets.first[/.+日時：[ ]?([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}).+/, 1].to_s.gsub(/ /,'_').gsub(/:/,'')} #{create_date}の記録　：embed"
```

　”＠｛Twitterユーザ名｝　（Twitterプロフィールの名前）　”｛検索ワード｝　｛該当件数｝／｛検索対象の総件数｝：｛検索範囲の最初の日時｝〜｛検索範囲の終わりの日時｝　｛スクリプトの実行時の日時｝の記録”

　概ね上記のような書式指定となっています。私自身さきほど勘違いしたのですが、見つかった検索の最初と終わりの日時とは違います。総件数としましたが、これはTwitterAPIのタイムラインで取得できるおそらく最大数です。16のオフセットで３２００件前後です。

　「user_timeline」というのがTwitterAPIで利用するメソッド名になります。つまり、私の他の自作スクリプトに多い自作データベースからのデータの抽出ではなく、Twitter社が提供するAPIから指定したアカウントの最新のツイートを取得しています。

　データベースとの違いは、仮に削除されたツイートがあった場合、検索結果には出てこないはずです。データベースに登録したツイートはデータ取得時の情報のみになりますが、TwitterAPIとは取得時以降のつながりがないので、削除されたという影響を受けることはありません。

　頻繁にツイートを削除するというアカウントもだいたいは決まっていますが、私が見てきたところ、その代表格が市川寛弁護士になります。こちらも再審や冤罪の救済のために社会的な活動をされているらしく、主張の方向性もジャーナリストの江川紹子氏とかなり似ていると思います。

```
real    0m10.430s
user    0m0.738s
sys     0m0.169s
```

　上記はtimeという処理の時間計測を付けた実行結果になります。市川寛弁護士とジャーナリストの江川紹子氏の最新ツイートをブログ記事として作成、投稿したのですが、上記の計測時間は２回目のジャーナリストの江川紹子氏の方の処理結果になります。

　12秒ほどで処理が終わっていますが、SSDが壊れた後の古いハードディスクなので、全般的なパソコンのパフォーマンスは作業に支障を感じるほど著しく低下しています。

[link:] 2019年10月01日11時08分の登録： ＃弁護士 市川 寛　@imarockcaster42＃のツイート／2019-03-27_1749〜2019-09-30_2349／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年10月01日11時08分 http://hirono2014sk.blogspot.com/2019/10/imarockcaster422019-03-2717492019-09.html

[link:] 2019年10月01日11時10分の登録： ＃Shoko Egawa　@amneris84＃のツイート／2019-09-19_0824〜2019-10-01_0914／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年10月01日11時10分 http://hirono2014sk.blogspot.com/2019/10/shoko-egawaamneris842019-09-1908242019.html

　上記のまとめ記事も同じ「user_timeline」というのがTwitterAPIのメソッドを利用していますが、オフセットは１つだけになります。このオフセットは一度に取得できるツイートの数で200件となっているようですが、199件のことも多かったので、199件と指定しています。

　TwitterAPIには使用回数の上限としてリミットというものがあり、15分でリセットされるのですが、1件のツイートを取得するのも200件を取得するのも同じ処理で、消費されるリミットの回数も同じとなっています。

imarockcaster42 ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW imarockcaster42（弁護士 市川 寛） 日時：2019/09/17 17:03 URL： https://twitter.com/imarockcaster42/status/1173869998596448256
> 日弁連、徳島で来月人権大会　冤罪で対談　江川紹子さんら　／徳島 - 毎日新聞 https://t.co/L80rfCIhaK 有料記事ですが...第３分科会「えん罪被害救済へ向けて　～今こそ再審法の改正を～」←これのパネルディスカッションにパネリストとして登壇します
▷▷▷　　　　　End　　　　　▷▷▷

　上記のツイートもTwitterAPIから取得をしていますが、ツイートのIDをしていして、こちらはstatusというメソッドの利用になります。いずれも「Twitter::REST::Client」のインスタンスに含まれるメソッドを呼び出して利用していることになります。

　条件式を使って市川寛弁護士の指定したツイートを取得していますが、告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)のアカウントでの実行は、ブロックされているということでエラーが返っています。

　もう15年ほど前の平成15年以来、傷害・準強姦被告事件の再審請求の手続きはやっておらず、非常上告へと方針転換をしておいますが、ネットで専門的な文献をみても、再審制度と非常上告は同じ不当裁判の救済制度という位置づけになっています。ただ、ごく僅かな情報です。

　司法救済という目的は同じでも、私は弁護士らが支配する再審制度に疑問と不信をいだき、非常上告への途を選択しました。これは全くのオリジナル性に近い独自の見解であって、憲法問題にも熱心な弁護士らに見向きもされていないことは、ブロックやミュートされている現実が物語っています。

　「えん罪被害救済へ向けて　～今こそ再審法の改正を～」などと掲げられていますが、こういう主張者はおしなべて警察や裁判所を批判し、不信感を訴えかけています。弁護士ではないですが、ジャーナリストの江川紹子氏こそその代表格と言えるでしょう。

　さて、そのジャーナリストの江川紹子氏ですが、まとめ記事の作成で確認したところ、7月9日から大崎事件をキーワードに含むツイートの投稿が途絶えています。最高裁決定が出たのが6月25日で、弁護団に決定の連絡が届き報道が始まったのは翌日の6月26日のはずです。

　6月26日から7月9日というのは、数えると13日間なので、上訴期限の14日に近いものがありますが、この期間における趣意書のようなジャーナリストの江川紹子氏の大崎事件における最高裁批判は、記事の見出しを見ただけでもずいぶんと過激で強固な決意表明と感じるものです。

```
RT amneris84（Shoko Egawa）｜biz_journal（biz-journal） 日時：2019-07-09 18：31／2019-07-09 18：16 URL： https：//twitter.com/amneris84/status/1148525158753161216 https：//twitter.com/biz_journal/status/1148521355551358976
> 江川紹子による考察…「大崎事件再審棄却」から見えた「人権救済を阻む砦」と化す最高裁への危惧 https：//t.co/K2awjfsAH6 https：//t.co/TyOejqzqrh

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： @amneris84（Shoko　Egawa）のツイート　”大崎事件”　22／3227：2019-02-09_2151〜2019-10-01_0914　2019年10月01日10時20分の記録　：embed https://hirono2014sk.blogspot.com/2019/10/amneris84shokoegawa2232272019-02.html
```

　まとめ記事を作成し最終的なジャーナリストの江川紹子氏のツイートを確認したときには気が付かなかったのですが、ジャーナリストの江川紹子氏が寄稿したと思われるビジネスジャーナルのツイートのリツイートとして、ジャーナリストの江川紹子氏の記事が紹介されていました。

　さらにリンクの記事を開いて確認したところ、このビジネスジャーナルの記事の配信日と思われる日付が同じ2019年7月9にのようです。時刻の記載はありません。見出しの上の記事の最初のような部分に「2019.07.09」という記載があるだけです。

　「…」というのも引用部分の中略などに使われるものかと思いますが、記事の見出し自体に含まれて使われているものだと気が付きました。つまり「江川紹子による考察…「大崎事件再審棄却」から見えた「人権救済を阻む砦」と化す最高裁への危惧」がそのまま見出しです。

　これまでも何度か見かけてきたことですが、ジャーナリストの江川紹子氏のツイートは、自らのネット記事をよくあるタイトル名＋URLという形式で紹介する場合と、なぜかそれをせずに、記事の情報が掲載されたツイートのリツイートのみを行う場合があるようです。

　本人の考えなので真意は測りかねますが、自身のツイートとした場合、返信や反論というのもツイートに付随することになります。一方でビジネスジャーナルのツイートのリツイートの場合は、そちらでの返信や反論はあり得ますが、ブロックを含め管理外という客観性は保てそうです。

　つまり自身のツイートの場合は、気に入らない返信や反論を付けてくるアカウントをブロックすれば相手のツイートが表示されなくなるので駆除、駆逐というかたちにもなるのではと思います。実際に私はそれでモトケンこと矢部善朗弁護士（京都弁護士会）や深澤諭史弁護士に返信不能です。

〈〈〈：Emacs： 2019-10-01（火曜日）12：13 　〈〈〈

