#+TITLE: "ジャーナリストの江川紹子氏のTwitterタイムライン（2019年11月分）"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-11-16 14:15:38 +0900
FILE_NAME: 2019-11-16-141538_ジャーナリストの江川紹子氏のTwitterタイムライン（2019年11月分）.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: ジャーナリストの江川紹子氏,Twitterタイムライン
記事タイトル名の文字数：38　保存ファイル名の文字数：60
#+STARTUP: showeverything


* 銀河鉄道９９９の作者、「漫画家の松本零士さん、イタリアで倒れ重体　脳卒中か」という芝原章吾弁護士のツイート：ジャーナリストの江川紹子氏のTwitterタイムライン（2019年11月分）
  CLOCK: [2019-11-16 土 14:27]--[2019-11-17 日 00:34] => 10:07

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: ジャーナリストの江川紹子氏,Twitterタイムライン

〉〉〉：Emacs： 2019-11-16（土曜日）14：27　 〉〉〉

　ジャーナリストの江川紹子氏のタイムラインで芝原章吾弁護士のツイートは２時間前として表示されていますが、初めて知るニュースで、Twitterのトレンドに見逃しがあったのかと確認したところ、トレンドの表示はありませんでした。

　日大の悪質タックル不起訴のジャーナリストの江川紹子氏のツイートを探すつもりで、ジャーナリストの江川紹子氏のタイムラインを開いたのですが、思わぬニュースが、思わぬかたちで飛びこんできて驚いています。

　まだニュースの記事はリンクも開いておらず、内容を読んでいませんが、Twitterカードに要約はあります。松本零士さんの８１歳という年齢もそこで確認をしましたが、脳卒中で重体といっても、早期に回復する例もあれば、亡くなってしまうこともあるので気がかりです。

　宇出津でも数年前に身近なところで、脳出血から金沢市の病院までの搬送中に亡くなったと聞いた人がいたのですが、いくつか年上だったので、ちょうど現在の自分ぐらいの年になるのかもしれません。

　宇出津の三番町に、看板も何も出ていない民家の古本屋があって、小学生の頃は何度かその店に行っていたのですが、その店で読んだ本として、松本零士氏の「スタンレーの魔女」という作品のことがずっと記憶に残っています。昭和４０年代の終わり頃のことのように思います。

[link:] » 戦場まんがシリーズ - Wikipedia https://t.co/1x7O0JCdae

　上記のページに「スタンレーの魔女」は、「『週刊少年サンデー』1973年47号」とあります。私が読んだと記憶にあるのは単行本で短編集になっていたようにも思います。「戦場まんがシリーズ」というのは余りしらなかったのですが、ずいぶん沢山の作品があったのだと知りました。

　松本零士氏については、以前に調べていろいろと情報を読んだことがありますが、そもそものきっかけは、１０年以上前の山口貴士弁護士のブログ記事でした。これは何度か取り上げてことがあると思いますが、日曜劇場「99．9−刑事専門弁護士−SEASONII」で松本氏の姿もみています。

　今年の何月か思い出せないですが、珠洲道路にある食堂に初めて入って焼肉丼を食べたときのこと、ずいぶん古いテレビがカウンター席の端にあって、画面が真四角に近いものでワイドに対応しておらず、両端の一部が表示されていないという状態でした。

　店内も２０年ほど前に時間が止まったような雰囲気で、タイムスリップをしたような感覚もあったのですが、そこでバイキングの放送に、松本零士氏のことが取り上げられいました。ネットでは知っていたニュースでしたが、テレビで取り上げられているのを見たのは、その時限りだったかもしれません。

　その食堂は、工場にも隣接しているらしい和菓子店の販売所のような敷地内になるのですが、その敷地内に足を踏み入れたのも、その数日前が初めてでした。珠洲道路の目立つ場所にその店はあり、ずっと前からあるのも知っていましたが、立ち寄ることも一度もありませんでした。

　その店というのは、宇出津の宇出津小学校のすぐ近くで、私が物心ついたころから同じ場所にありますが、「いも菓子」が名物となっています。「いも菓子」は珠洲市飯田の方が能登の名産品としての知名度があるかと思います。

　小学生の頃は、よく「いも菓子」を食べる機会があったのですが、中に入っている白あんが嫌いで、皮の部分だけを向いて食べていたという思い出もあります。あんこ全般が好きではなかったのですが、金沢市の名産である「あんころ餅」だけは、美味しいと思いながら食べていました。

　宇出津小学校の前というのは宇出津の新町通りからの中心部の道路で、平成に入ってからは別にバイパスが出来ているので、今は違っているのかもしれないですが、それまでは国道２４９号線でした。私が昭和５０年まで住んでいた辺田の浜の家も同じ国道沿いになります。

[link:] » いもがし - Google 検索 https://t.co/e5NPYeY0Jc

　検索をすると、地図付きで店舗が２つだけ出てきました。宇出津の店は出ていないようです。

　「（株）いわずみ 神和住店 能登のいも iWAFFLE」と「泉谷菓子舗」になります。後者が珠洲市飯田町になりますが、この店の人が珠洲市の市長だと聞いています。最近はテレビで見かけていないですが、市長が変わったという話は聞いていないので、現在も同じではないかと思います。

　かれこれ２０年近くは経つように思いますが、ずいぶん若く市長になったことで話題にもなっていました。それに近い時期には、珠洲市を二分した原発誘致と反対の問題があって、けっこう長く続いていたと思いますが、誘致は実現しませんでした。

　原発の誘致の問題のずっと後になってから、魚釣りの関係で知ったのですが、原発の建設が予定されたのは高屋だったようです。珠洲市の海岸線でも外浦になり、冬場は特に海が荒れて波の高いところです。富山湾に面した内浦とは比較になりません。

```
電力3社が共同で運営を予定していた原子力発電所で、中部電力側が珠洲市三崎町寺家地点で、北陸・関西両電力が珠洲市高屋地点（関西側が主導）で発電施設を共同開発するものであった。

2か所で合わせて135万kWクラスの原子炉2基を設けて、2014年（平成26年）に運用を開始する計画を立てていた。

計画から28年間、地元からの反対運動や産業構造の変化や景気低迷に伴い、電力会社側の判断により計画が凍結されることとなった。

［source：］珠洲原子力発電所 - Wikipedia https://ja.wikipedia.org/wiki/%E7%8F%A0%E6%B4%B2%E5%8E%9F%E5%AD%90%E5%8A%9B%E7%99%BA%E9%9B%BB%E6%89%80
```

　確認の必要もあると思い調べたのですが、珠洲市でも２箇所で原発の建設が予定されていたようです。高屋が間違いないことは確認しましたが、もう一つが珠洲市三崎町寺家とあります。三崎町というのは余り聞いたことがなかったので、三崎という地区名のことかと思っていました。

　珠洲市は、狼煙に禄剛埼灯台があって、その左側が外浦、右側が内浦になると聞いたことがあります。内浦方面の珠洲市は、能登町の恋路海岸と珠洲市の宗玄が境になりますが、ちょうど恋路から三崎町寺家の間は、長く緩やかな砂浜の海岸線が続きます。

　珠洲市三崎町寺家も、秋にはアオリイカ釣りに行くことがあるので海岸線の地形もだいたい頭にあるのですが、寺家から狼煙の間にも岩場はけっこうあります。同じ珠洲市三崎町でも寺家の手前側の砂浜の方は、内浦で波も穏やかそうですが、岩場の方は、けっこう荒れそうです。

　この珠洲市の原発誘致の問題は、夕方などにテレビをつけていると石川県内ニュースで度々取り上げられていましたが、海が荒れるとか波が荒いという理由での反対は、一度も見聞きしたことがありませんでした。

　今年の５月か６月に山形県沖の大きな地震があって、能登にも津波注意報が出て、宇出津でも実際に高台に避難した人がけっこういたという話を聞いたのですが、その時のテレビの解説で、津波は水深の浅い沿岸部を目がけて進むので、より大きな被害の危険があると聞きました。

　具体的には輪島市の沿岸になりますが、沿岸の水深が浅いのは珠洲市の外浦も同じかと思いました。山形からだと輪島市内の手前にもなるので、津波の勢いが強いままより被害が大きくなるのではとも想像しました。

```
山形県沖地震（やまがたけんおきじしん）は、2019年（令和元年）6月18日22時22分 (JST) に山形県沖（日本海）［注 1］で発生したMj6.7［4］ (Mw6.4［3］) の地震［N 2］である。新潟県村上市府屋で震度6強を観測した［1］ほか、観測史上初めて山形県内で震度6以上の揺れを記録した［5］。

［source：］山形県沖地震 - Wikipedia https://ja.wikipedia.org/wiki/%E5%B1%B1%E5%BD%A2%E7%9C%8C%E6%B2%96%E5%9C%B0%E9%9C%87
```

　過去には同じ名前の地震がありそうに思ったのですが、上記の『ウィキペディア（Wikipedia）』には、令和元年６月１８日２２時２２分とあります。この時刻をみて思い出したのですが、NHKでジャーナリストの江川紹子氏が出演している番組の視聴中の地震で、放送は中断で終わりました。

　再放送が数日後にあって、そちらで中断された後の部分を含めて視聴をしたのですが、番組のテーマがなんだったのか思い出せません。高井弁護士が一緒に出ていて、ジャーナリストの江川紹子氏の発言の後に、笑顔で返していたのが、含みの有りそうな態度に見えて気になっていました。

　高井弁護士は、高井康行という名前だったでしょうか。顔はよく憶えているのですが名前がはっきり思い出せません。Twitterでの法クラのツイートでは評判の悪い感じの弁護士で、元検事の弁護士だったと思います。最近はしばらくテレビで姿を見ていないように気が付きました。

　時刻は１６時０１分です。ブラウザのTwitterに目をやると、トレンドで「松本零士さん」が37,009件となっていました。０２分にウィンドウが下に隠れた端末をみると、２つ目のまとめ記事の投稿処理が完了していました。

[link:] 2019年11月16日15時57分の登録： REGEXP：”高井弁護士”／データベース登録済みツイート：2019年11月16日15時57分の記録：ユーザ・投稿：9／9件 http://hirono2014sk.blogspot.com/2019/11/regexp20191116155799.html
[link:] 2019年11月16日16時01分の登録： REGEXP：”高井康行”／データベース登録済みツイート：2019年11月16日15時58分の記録：ユーザ・投稿：81／163件 http://hirono2014sk.blogspot.com/2019/11/regexp20191116155881163.html

　事前にデータベースへの追加処理はしていませんが、高井弁護士の検索では９ユーザの９件だったのが、高井康行でやり直すと、８１ユーザの１６３件となっていて、結果がまったく違っていました。ユーザ数が多いとプロフィール情報を読み込むので処理に時間が掛かります。

▶（001／163） TW amneris84（Shoko Egawa） 日時： 2012-03-20 12:54:00 +0900 URL： https://twitter.com/amneris84/status/181951889338929153
{% tweet 181951889338929153 %}
> 「裁判所が（池田調書の）信用性を認めれば、石川知裕衆院議員も小沢代表に同程度の報告をしていたのではないかとの推論が働くだろうし、裁判所の判断はやや有罪に傾くのではないか」元東京高検検事の高井康行弁護士（日刊スポーツ）←堀江貴文さんの元弁護人。

　最も古いツイートとして出てきたのが上記のツイートになりますが、ジャーナリストの江川紹子氏のツイートで、「←堀江貴文さんの元弁護人」とあります。ホリエモンこと堀江貴文氏の弁護人については、話題を見た記憶がありますが、高井康行弁護士の名前はすごく意外に感じました。

▶（162／163） TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2019-07-03 02:44:00 +0900 URL： https://twitter.com/hirono_hideki/status/1146112333275549696
{% tweet 1146112333275549696 %}
> 2019年07月03日02時38分の登録： ＼二宮淳悟　@jungo321＼高井康行弁護士（元検事）の大崎事件決定のコメントの酷さよ。 https://t.co/L5KAlaTVio

　二宮といえば、宇出津小学校の旧校舎で石炭置き場に銅像があったことでも印象深い二宮尊徳が有名ですが、「二宮淳悟」という名前は全く記憶にありませんでした。ツイートの内容は記憶にあったものですが、リンクを開くと一般的なユーザという印象で、非公開設定になっていました。

　まったく記憶にないことがなにより気になって、名前の部分を範囲選択し右クリックから検索を実行したところ、新潟県弁護士会所属として、それと思われる名前が出てきました。新潟合同法律事務所ともあります。

　Googleの検索結果にもTwitterのアカウントがあってので、そちらのリンクを開くと、Googleの要約部分と同じで、「新潟の弁護士です」がプロフィールになっていました。Twitterの利用は２０１１年２月から、とあります。

　Googleの検索を画像に切り替えると、「二宮淳悟　新潟合同法律事務所」などとして、明らかに異なる人物の写真が６つは出ています。一人は女性のようですが、同じホームページが画像の発見場所となっているようです。

[link:] » 二宮淳悟 - 新潟合同法律事務所（新潟県弁護士会所属） https://t.co/DBYjVf1rll

　上記のページにある胸から上辺りの顔写真が二宮淳悟弁護士本人に間違いなさそうです。左手に大きな帯状で弁護士二宮淳悟とありますが、「よく出来ましたマーク」とも「菊の御紋」とも見えたものが、どうも弁護士バッヂの絵柄のようです。

　新潟で思い出したのですが、昨夜はTwitterのトレンドに最初「新潟駅」とあって、気になってリンクを開くと、女性が新潟駅の近くで刺されて重体、というニュースで。金曜の夜で遅い時間帯の放送だったテレビのzeroでは、番組の終わりの方で、死亡が確認されたと速報を伝えていました。

　テレビを消したのは１１時前だったと思いますが、今もつけてはおらず、お昼のニュースも見ていません。三人組の男が待ち伏せをし逃走中というニュースは昨夜に出ていたと思いますが、Twitterのトレンドにも出ていないので、逮捕されたというニュースはなさそうです。

　新潟市といえば、ご当地アイドルの襲撃事件でも、その後のゴタゴタがよくテレビに取り上げられていました。女児の殺害事件の初公判も数日前、テレビで情報番組に裁判所前の中継を含めて報道されていましたが、Twitterのトレンドで話題を見かけることはありませんでした。

　昨日は、バイキングとグッディの放送で、福岡県小郡市の警察官の家族３人殺害事件の公判を取り上げると知り、バイキングの放送を録画して母親のいる病院に向かいました。夜の遅い時間に再生をしていたのですが、早送りから該当部分を見ていたところ、そのまま寝てしまったようです。

　布団に入って寝たのは１時半ぐらいだったとも思うので、長い時間ではなかったと思いますが、寒さで目が覚めたように思います。公判のある質問で被告人の元警察官が泣き出したという話のところは憶えているのですが、そのあと麻酔でも効いたようにすぐに寝落ちていたようです。

　初公判のときは、通常のニュースの短い報道だけで、情報番組が中継をするようなこともなかったと思いますし、いつもは罪状の認否もあるので最も注目され、中継を交えた報道が多いのも初公判だと思っていました。集中審理だと何回目の公判になるのか不明ですが、それも珍しく感じました。

　考えてみると、そちらの福岡県小郡市の警察官の家族３人殺害事件の公判も、ネットでは情報を見ておらず、新潟地裁の公判と同じくTwitterのトレンドは見ていなかったと思います。

　なお、Twitterのトレンドですが、同じ時間でもブラウザとログインしているアカウントが違うと、トレンドの内容がけっこう違っています。Twitterに異なるアカウントでログインするために、ブラウザを複数立ち上げていることも多いです。

[link:] » 弁護士のご紹介 - 新潟合同法律事務所（新潟県弁護士会所属） https://t.co/I5xbPgIQlz

　上記のページには、９人の弁護士の顔写真があって、これがGoogleの画像検索でまぎわらしい結果表示の原因となっていたようです。新潟市の人口が金沢市よりずいぶん多いことは記憶にあるのですが、新潟県の人口や新潟県弁護士会の会員数というのは見ていないと思いました。

　１，２年前になるかと思いますが、テレビのバラエティー番組で、江戸時代の終わりか明治の初期か正確なことは忘れましたが、当時の江戸や東京より人口が多かったという話を聞きました。生まれて５０年以上経ってから初めて知ったのですが、その方が不思議に感じました。

　個人的に違和感がずっと残っていて、おそらく知っている人も少ないと思うのですが、新潟県は東京高裁の管轄になるとのことです。実際の刑事裁判で新潟地裁の判決が、東京高裁の控訴審になったという話は聞いた覚えはないのですが、特に富山県境は、不便がないのかと不思議です。

　そういえば２日ほど前にも大分県の法律事務所のホームページで見かけた弁護士団体による一票の格差問題ですが、新潟県でも糸魚川市の辺りに住んでいて、東京高裁で控訴審となれば、事実上控訴を断念せざるを得ない場合もありそうで、それが全く問題にされないのが不思議です。

　控訴審の負担というのは北海道の弁護士の不満として見かけたことがありますが、それとは別に札幌高裁での控訴審の即日結審の割合が異常に高いというニュースは、ネットで見かけたことがありました。小さなニュースでしたが、検索で探し出せそうに思います。

```
全国に8つある高等裁判所のうち札幌高裁の刑事事件の控訴審では、初公判で結審して判決を言い渡す「即日判決」の割合が9割を超える。他の7高裁では1割にも満たず、群を抜いて高い。地元弁護士会からは「慎重に審理していないとの疑いを招きかねない」と批判の声が上がっている。

［source：］札幌高裁、「即日判決」9割超　突出と弁護士ら批判　　：日本経済新聞 https://www.nikkei.com/article/DGXLASDG25H4J_V20C17A2000000/
```

　同じ記事か似たような記事を読んでいたはずですが、９割超とは記憶になく多くて８割程度と予想していました。上記の記事は２０１７年２月２５日の日付があります。地元弁護士会の批判や不満が強く強調されていますが、公判の回数が増えれば、負担が大きくなるのも弁護士のはずです。

　札幌市の近郊であれば控訴審の負担は全国平均のはずですが、広い北海道の端の方になればなるほど、交通費や所要時間の負担が大きくなると想像されますが、北海道の弁護士の個別のツイート以外に情報を見たことはありません。特に冬場は負担が増大する上、命の危険もあると聞きます。

```
北海道の場合
札幌高裁は、今は、支部を設置していません。「今は」というのは、かつて函館に札幌高等裁判所函館支部があったからです。

既に４０年以上前に函館支部は廃止されましたが、その際に函館弁護士会は猛反対したのでした。歴史的に見ても道内の控訴裁判所の起源は函館にあり、札幌には後で移転したに過ぎないのですから、当然の反応でしょう。ところが、札幌弁護士会は反対しなかったので、函館弁護士会が道弁連から脱退しようとする騒動があったようです。

北海道は余りに広大ですから、１個くらいは高裁支部を復活させても良いのかもしれません。もっとも、今は道内４会仲良くやっているとはいえ、どこに作るかとなればモメるかもしれませんが…。

［source：］高裁支部の適正配置 | 弁護士法人岩田法律事務所 http://iwata-lawoffice.com/archives/347
```

　途中で、北海道にも高裁の支部があるのではと考え、誤った情報の拡散防止のため前のツイート部分の削除まで考えたのですが、北海道には高裁の支部がないということを岩田圭只弁護士のホームページで確認することになりました。

　そもそも、刑事裁判の控訴審で拘置所が高裁もしくは高裁支部の所在地に移送されることの問題、同じく控訴審の弁護人が接見のために移動しなければならないという問題をネットで見たことがほとんどありません。弁護士の接見のことは少し見かけたことがあって、それで私も気が付きました。

　もともと上告審の最高裁であれば、地方の被告人と東京の国選弁護人の接見などほとんどないはずで、それを問題にした情報というのもこれまで一度も目にしたことがないので、違いはなさそうにも見えますが、法律審である最高裁と、事実審でもある高裁では、裁判の仕組みは全く違います。

　なかにはあるのかもしれないですが、決定で公訴棄却となった話は一度も聞いたことがありません。逆に判決がごく稀に出るのが最高裁ですが、書面審理のみと口頭弁論を経た判断の手続き上の違いであると専門書で読みました。皆無ではないですが、これもテレビやネットでは滅多に見かけない情報です。

　時刻は１７時４４分です。４２分だったと思いますがテレビをつけたところ高輪駅が出てきました。ニュースのようだったのでリモコンのデータボタンで確認したところ、北陸朝日放送で、「ゆうどきLIVE」という番組名になっていました。初めて見たような番組名です。

　ニュースというより話題という感じの高輪駅の報道でしたが、その直後に出たのが、新潟駅近くの女性刺殺のニュースで被疑者を指名手配、顔写真が出た後に、母親に自殺をほのめかしたという解説があって、さらに出てきたのが埼玉県の上尾警察署の映像か写真でした。

　新しくかなり大きな警察署の建物だと思った埼玉県の上尾警察署ですが、上尾警察署の建物を見たのもこれが初めてだと思いますが、すぐに思い出したのが桶川ストーカー殺人事件でした。出てくる頻度は、調べた情報量の大きさもあって少なかったと思いますが、上尾警察署が管轄になっていたはずです。

　指名手配の若い男性の写真がとても大きく表示されていたのも珍しく感じたのですが、ホスト風の若い男性で、そのまま水商売の顔見せ写真のようでした。そのあとに画面右下にそれも珍しく小さく表示されたのが死亡した被害者女性の顔写真でしたが、対照的にかなり地味に見えました。

　テレビを付けたのが１７時４２分で、事件報道は終わっているものと考え、気がつくのが遅かったとも思ったのですが、偶然なのかと不思議に感じるタイミングでした。

　別の番組が始まって、ちょっとしてからチャンネルをNHKに変えると、女優の沢尻エリカが合成麻薬所持で逮捕というニュースをやっていました。これは大きなニュースと思ったのですが、テレビに表示の時刻が６時２分のうちに、新潟の女性刺殺のニュースに変わり、３分の頃には終わっていました。

　全国指名手配という顔写真に新潟県警察提供とありましたが、母親に自殺をほのめかしたことや埼玉県の上尾警察署のことはまったく出ていなかったと思います。被害者の女性は、繁華街の飲食店の従業員だったようです。地味に見えた写真は、北陸朝日放送のものと同じに見えました。

　チャンネルを変えると、報道特集で、なぜか余りみることのない番組なのですが、北陸放送の番組なのだと確認しました。前に、銭湯のテレビで、恵庭OL殺害事件や木谷明弁護士の特集をみたことを取り上げたと思いますが、そのような特集は気になるものの、事前に調べたこともありません。

　桶川ストーカー殺人事件のときは、調査報道という言葉もあったようですが、これまでに何度か書いているとおり、ネットで調べた情報では、私が金沢刑務所の拘置所にいるときの事件で、加熱した報道をテレビで見たという記憶はなく、過去の事件を振り返る番組では少し見たかもしれない程度です。

　１８時２０分、報道特集が終わったところです。こんな時間に番組が終わるのも知らなかったですが、番組中でもこのあと世界野球の日韓戦と紹介していたので、あるいは放送時間の変更なのかもしれません。

　その報道特集の最後に、沢尻エリカの逮捕前夜の映像が出ていたのですが、「これだ、これだ」というような声の後に、不安そうに後ろを振り返る沢尻エリカという映像の姿が、かなり異様なものに映り、ストーカーに狙われた若い女性がリアルに映し出せれているように見えました。

　ずいぶん人通りのなさそうな場所での撮影でした。近く逮捕されるという事前情報を得た上での、待ち構えた撮影のようでした。沢尻エリカといえば、会見での不貞腐れたような態度でずいぶんと叩かれていた時期もありましたが、あの付け狙われた不安そうな表情は、衝撃的だったと思います。

　１８時３１分現在、Twitterのトレンドは、「沢尻エリカ」が254,615件となっています。田代まさし、の逮捕が予想したほど大きく長い報道にはならなかったのですが、政治問題の報道にもいくらか影響がありそうで、田代まさしのときにはみかけなかった政権のための陰謀論も気になります。

　チャンネルをNHKに戻したところ、さきほど１８時のニュースの後みかけていた時代劇のドラマ名に遊里とあることに気が付きました。よく見ると「大富豪同心」がドラマ名で４回目の放送のタイトルが「遊里の旋風（かぜ）」となっているようです。

　遊里という言葉をNHKの放送で見かけたので気になったのですが、遊郭のことかと思いながら里とあるので、この言葉の組み合わせが気になってきました。旋風に括弧書きで「かぜ」としているのも気になりましたが、ちょうど番組は終わりになるらしく、エンディング曲が流れています。

[link:] » 遊里(ユウリ)とは - コトバンク https://t.co/i4BiDghvgn

　気になったので少し調べたところ、やはり遊郭と同じ意味とされながら「色里」も同じ意味になるようです。色里は余り見かけた覚えもないですが、能登に住んでいると里は「のと里山海道」などでよく見かける言葉です。

[link:] » (7) 『花宵道中』予告編 - YouTube https://t.co/VCjCOAhfXj

　テレビの情報番組の映画紹介で、沢尻エリカが花魁か遊女役をしているのを見かけたような記憶があって調べたのですが、上記の「花宵道中」という映画は、安達祐実が花魁役の主演で、出演者に沢尻エリカの名前はありません。なにか記憶違いをしていたのかもしれません。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜MomentsJapan（Twitter モーメント） 日時：2019-11-16 19:06／2019/11/16 16:34 URL： https://twitter.com/kk_hirono/status/1195644311276179456 https://twitter.com/MomentsJapan/status/1195606120020135936
> 沢尻エリカ容疑者が合成麻薬所持の疑いで逮捕されました https://t.co/6HuTu20Qh4
▶▶▶　　　　　End　　　　　▶▶▶

　さきほどテレビで見た映像が、Twitterモーメントのツイートになっていました。先程のNEWS７では、映画の演技で受賞をしていたという報道もありましたが、演技には定評のある女優だと聞いていました。顔が引きつっているようにも見えますが、強く怯えているようにもみえます。

　映像として撮影したマスコミからは、まさに獲物のようなターゲットなのかと想像しますが、それだけにさらに異様に映る映像です。

　リツイートはしませんが、Twitterモーメントのツイートの返信欄をみていると、「安倍総理がヤバくなると芸能人が逮捕される説」というツイートがありました。

　時刻は１９時２２分です。NEWS７で新潟の事件に関するニュースが終わったところですが、埼玉県上尾警察署の対応が問題になっているようです。

　１９時２４分です。いろいろあって忘れていた、松本零士氏のニュースがNEWS７にありましたが、容態は深刻とのことです。銀河鉄道９９９の上映会のあと、「あと」とテレビから聞こえたように思います。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜livedoornews（ライブドアニュース） 日時：2019-11-16 19:27／2019/11/16 18:10 URL： https://twitter.com/kk_hirono/status/1195649664780881920 https://twitter.com/livedoornews/status/1195630132725047297
> 【入院】松本零士さん、命に別条なし 集中治療室で治療  https://t.co/QVfkI7D9ll  関係者によると命に別条はないという。現地紙は「ホテルで脳卒中を患った後、非常に深刻な状態で入院している」などと報じている。 https://t.co/SICQ0obqvE
▶▶▶　　　　　End　　　　　▶▶▶

　Twitterで検索をすると、NHKのNEWS７とは違った情報が出てきました。

　時刻は２０時５８分です。深澤諭史弁護士のタイムラインに、松本零士氏のニュースのツイートが２つありました。世代が違いそうにも思ったのですが、関心は高いようです。

　今のところまだ記述したことはないかもしれないのですが、深澤諭史弁護士の考えや生き方そのものが、松本零士氏の代表作の１つ、銀河鉄道９９９のストーリー、機械の体を手にするための宇宙への旅立ちに重ね見るところがあり、これも「さらば弁護士鉄道」の重要なファクターとなっています。

　テレビの世界野球日韓戦ですが、日本が７点で大量リードしていたのが、勘違いでフィギュアスケートの番組にチャンネルを合わせていたところ、１時間差の勘違いに気が付きチャンネルを戻したところ、７対６になっていて、そのあとノーアウト満塁というピンチになっていました。

　世界野球で思い出すのはキューバで、世界最強とされる時代が長く続いていたと記憶しますが、今回の世界野球ではまったくキューバの話題を見かけていません。

　思えば、テレビで高校野球の甲子園大会以外をみるのもずいぶん久しぶりですが、以前は週に３回は、プロ野球の中継放送があったように思います。野球の選手の名前も知らない名前ばかりです。ずいぶん時代が変わったという気もしました。

　芝原章吾弁護士について書くのを忘れていましたが、名前を見ると芝浦ということで品川区あたりの東京都が頭に浮かんで毎回のように勘違いをしそうになるのですが、プロフィールに記載があるので鹿児島市の弁護士ということがすぐに確認できます。

　Twitterのアイコンは、だいぶん前から頭部以外が毛の長いゴリラのような写真となっています。空想上の仙人の姿にも見えなくはないですが、ゴリラの種別はわかりません。

　芝原章吾弁護士のTwitterのヘッダー写真も、気になるもので庭に地蔵か仏のようなたぶんヤカンのあって、近くに青い色のアジサイの花がみえます。能登町にはあじさい寺とも呼ばれる平等寺があって、今夜は、紅葉が県内ニュースで紹介されていましたが、見たことのないような赤色でした。

　能登半島は最も高い山でも標高が５００m台で、宝達志水町の宝達山に次いで高いのが輪島市の高洲山と聞きますが、５００m台の山でも真っ赤な紅葉はないものと思っていました。平等寺にはブナの木もあるとのことでしたが、高洲山の山頂付近にブナの木があるとは情報で見ていました。

　高洲山の山頂に行ったのが、去年なのか今年なのかはっきり思い出せないのですが、諸獄山だったと思いますが、戻ってからインターネットで調べたところ、「女人救済」という情報が出てきました。

[link:] » 諸獄山 女人救済 - Google 検索 https://t.co/bKWDaFmSxD \n 次の検索結果を表示しています: 諸嶽山 女人救済 \n 元の検索キーワード: 諸獄山 女人救済

　漢字に間違いがあったようですが、Googleが間違いの指摘をした上で、正しい検索をしてくれたようです。

```
今から約七百年前の元享元年（一三二一）に常済大師・瑩山禅師によって開創された曹洞宗大本山總持寺には、それ以前より「諸嶽観音堂」の本尊として千有余年の歴史を持ち老松の間に建つ、幽玄な古堂に観世音菩薩が祀られています。これが慈雲閣で、当本山最古の建築物です。行基菩薩の建立とされ、「鳥巣不懸（ちょうそうふけん）」の縁起伝説を持つ観音堂といわれています。
　本尊の観世音菩薩は「禅定印」を結び僧衣を着用した僧形の観世音で、我国希有の存在と尊崇され、古より奥能登の観音霊場として遠国まで名高く、女人救済・安産祈願・諸災消除・諸願成就等あらたかな観音菩薩です。
　当山は元享二年、後醍醐天皇より勅願所と定められ、以後曹洞宗の大本山として寺運の隆盛をきわめ、七十余棟の伽藍を有していましたが、現在は祖院として多くの文化財と旧蹟を保存し、その史影は観音霊場の聖地として大本山の風格をみせています。

禅修業の根本道場

［source：］北陸三十三ヵ所観音霊場巡り　第十五番　諸嶽山　大本山總持寺祖院 http://www.hokurikukannonreijyoukai.jp/reisho/15.html
```

　以前調べたときも同じ情報を読んでいるように思いますが、観世音菩薩が本尊というのは新たに知ったような感覚があります。總持寺は横浜市に本山が移っていると聞きますが大きな寺院で、観世音菩薩は悟りを開く前の仏の姿と聞いているので、いくらか違和感を感じます。

　昨日、病院で見た母親は、ずいぶん久しぶりにずいぶんとおだやかな様子で、弁護士脳の毒素を記録としていくらか吐き出すことが出来たことで、心置きのない成仏に近づけたのかもしれないという思いにもなりました。

[link:] » 2014_06-02.pdf https://t.co/bTs6aeyAKx \n 瑩山の女人済度思想について \n 愛知学院大学教養部准教授 河合泰弘

　PDFファイルでまともな日本語タイトルが取得できたことはないように思うのですが、コピペで日本語の文字化けが起きなかったのは幸いでした。女人済度とありますが、昨日は病院に向かう時に、衆生済度の「汗かき地蔵」に立ち寄り、スマホで写真の撮影もしていました。　

[link:] » 石川県能登町中又　鳳林寺の汗かき地蔵様は霊験あらたからしい – 金沢歴活 https://t.co/IGhpgDlpLS

　「汗かき地蔵」のことを知ったのはポケモンGOがきっかけで、輪島市民まつり、の帰りであったように思います。たぶん、その数日後に輪島市金蔵の農業用貯水池から転落した車と老夫婦の遺体が発見されたニュースがあったのですが、ガードレールの僅かな隙間で、とても不思議な死亡事故でした。

　今年もバイクで輪島市民まつり、の花火大会を見に行ったのですが、帰りと帰った後に不思議なことはなかったものの、花火大会までの時間調整もあって立ち寄っていた猿山岬灯台では、得難い不思議な体験がありました。皆月の望楼跡に行ったのもそのときであったように思います。

　前に、輪島の市民まつり、から戻ったときには、テレビにモハメッド・アリの訃報のニュースがあって、会場のステージではアントニオ猪木本人かと勘違いした人物の登場がありました。また、横になって寝ていると、ネズミがパンの袋の中で暴れた音で目が覚め、まるで日本昔ばなしのようでした。

　輪島市門前町の暮坂に行ったのも、皆月の望楼跡に行ったときが２度目でしたが、初めて行ったときも猿山岬の娑婆捨峠に近づいたタイミングで、夕陽が重なり偶然とは思えないような光景でした。娑婆捨峠は初めに行ったときから強い何かを感じ、すぐにプロフィールの写真にも使っています。

　芝原章吾弁護士ですが、芝原総合法律事務所とあるものの、調べた範囲で一人弁護士でした。これは中村剛弁護士の中村総合法律事務所にも共通していそうです。なお、中村憲昭弁護士と取り違えそうになったのですが、そちらのホームページには女性弁護士の名前と顔写真がありました。

　鹿児島市にはもう一人、個人経営で活躍されている弁護士がいて、前に取り上げたこともあると思うのですが、名前はさっぱり思い出せません。なにかの弁護団の中心でもあったようです。同じ鹿児島市の鴨志田裕美弁護士も大崎事件で活躍をされていますが、弁護団長は別になっています。

```
原告側弁護団の野平康博事務局長は、今回の裁判を通じて「十分な嫌疑がないまま、捜査を着手し継続したのは違法」との主張が認められなかった点を挙げて「上告理由はある」と指摘。その上で「原告の負担を考えるとやむを得ない」とした。

　事件では、公選法違反の罪で起訴された住民１３人のうち、公判中に亡くなった１人を除く全員の無罪が確定。公判などを通じて違法捜査が判明した。無罪の住民らが国と県に賠償を求めた訴訟では、計約６千万円の賠償を命じる判決が確定している。

［source：］志布志事件訴訟、終結へ　賠償判決、住民も上告せず　「原告の負担を考えるとやむを得ない」と弁護団 - 産経WEST https://www.sankei.com/west/news/160817/wst1608170076-n1.html
```

　発掘作業をする鑑定団のような感覚ですが、上記の記事に志布志事件訴訟の原告側弁護団事務局長となっている野平康博弁護士に間違いはないと思います。

[link:] » 野平法律事務所に法律相談 - 鹿児島県鹿児島市、鹿児島市電１系統 朝日通駅 | Legalus https://t.co/7ryCSWFlAd

　上記のページの在籍弁護士一覧で、野平康博弁護士の名前のみがあります。こちらも個人経営の弁護士事務所と思われますが、総合とないのは自然ですが、フルネームでないのがいくらか珍しく感じました。野平という名前は他に見たことがないですが、人名よりは地名にありそうという印象があります。

　次の戸舘圭之弁護士の名前を加えておきたいところですが、個人経営の弁護士なのかこれから確認します。以前調べた時の記憶は個人経営と思われましたが、３，４ヶ月ぐらいの間はあるように思いますし、これもずばりと確認できる情報は簡単に見つからなかったように思います。

```
弁護士　戸舘圭之
@todateyoshiyuki
弁護士 戸舘圭之（第二東京弁護士会）袴田事件弁護団、ブラック企業被害対策弁護団副代表、青法協弁学合同部会副議長、ホームレス総合相談ネットワーク、東洋経済オンラインレギュラー執筆者、日本労働弁護団、静岡大学出身（渕野貴生ゼミ）https：//bengo4.com/tokyo/a_13101/l_112740/…
東京 千代田区todatelaw.jp2010年10月からTwitterを利用しています
1,203 フォロー中
3,797 フォロワー

［source：］(2) 弁護士　戸舘圭之（@todateyoshiyuki）さんの返信があるツイート / Twitter https://twitter.com/todateyoshiyuki/with_replies
```

　上記が現時点でのTwitterのプロフィール情報になります。ずっと前から際立って目に付くのが「袴田事件弁護団」になります。ヘッダ写真は、プロレスのようなリングにあがるスーツ姿の一団です。おそらくは弁護士の集まりなのだと思います。なぜリングの上なのか、それは解けない謎のままです。

　２，３日前に羽咋市で五重塔がある妙成寺について書きましたが、その少し前にはテレビで奉納プロレスのCMを繰り返し見ていたように思います。

[link:] » 妙成寺　奉納プロレス - Google 検索 https://t.co/8RoZe1WtLO

```
昨年に引き続き、2019年8月25日(日)午後6時より、羽咋市滝谷町の日蓮宗本山妙成寺(みょうじょうじ)×初代タイガーマスク後援会＝奉納プロレスが開催されます。

昨年は本堂前に特設リングが設けられ、約500名の観客がプロレスを楽しみ、ご当地プロレスラー(!?)の宇宙人「サンダーくん」も登場したそうですよ。



［source：］妙成寺で奉納プロレス！初代タイガーマスクがやって来/ロイヤルホテル 能登のブログ - 宿泊予約は＜じゃらん＞ https://www.jalan.net/yad313418/blog/entry0005096920.html
```

　私が羽咋市の妙成寺に行ったのは５月５日で、上半身の裸が普通のプロレスを寒い時期の寒い時間帯にするのは疑問に思ったのですが、上記の情報には２０１９年８月２５日午後６時より、とあります。夜の暗い時間というイメージもあったのですが、唐戸山の神事相撲と混同があったのかもしれないです。

```
相撲好きであったといわれる羽咋神社の祭神・磐衝別命(いわつくわけのみこと)の遺徳をしのんで、毎年、命日の9月25日に行われている相撲です。

［source：］唐戸山神事相撲の概要／羽咋市公式ホームページ https://www.city.hakui.lg.jp/kankou/gyoujiichiran/4751.html
```

　終わった後の石川県内ニュースで見かけることがほとんどだったと思うのですが、時期を調べたところ毎年９月２５日とありました。テレビでの唐戸山神事相撲の映像は夜ですが、９月２５日の夜といえば、かなり寒いと思われます。８月の２５日頃でも夜はバイクで走行すると寒いことがあります。

　テレビで、沢尻エリカは、日本人とアルジェリア系フランス人のハーフと言っていましたが、これまでにハーフと考えたこともなかったものの、言われてみるとそれらしく思えてきたのが不思議です。アルジェリアはアフリカ大陸ではなかったかと思います。

　Googleで検索をすると、やはりアフリカ大陸で、確認するとすぐに「ここは地の果てアルジェリア」という歌詞の曲があったことを思い出しました。かなり古い曲だったと思います。「カスバの女」が曲名のようです。

[link:] » (7) 藤圭子♥カスバの女 - YouTube https://t.co/ujmGJp3xN1

　Googleで検索するとトップに出てきたのが上記の藤圭子の歌でした。元歌は藤圭子ではなかったように思いますが、藤圭子の声とともに、昭和４０年代の時代感を強く感じました。連合赤軍の浅間山荘事件のニュースなどもあった時代です。

[link:] » カスバの女 - Wikipedia https://t.co/41jIGAdcvs \n カスバの女（かすばのおんな）は、エト邦枝が1955年（昭和30年）に発表した楽曲である。

　前にも何かがきっかけで調べたことがあったように思います。日本人を含む人質事件だったかもしれません。思っていたよりかなり古く、昭和３０年に発表した曲とあります。

　アルジェリアは地中海の対岸にフランスがあったように思いますが、久しぶりに思い出した曲があります。平成１１年の秋、金沢刑務所の拘置所で、一時期繰り返し流れていた曲です。テレビを含めGoogleの検索以外では耳にした曲ではなく、知らない人が多そうです。

[link:] » 新谷のり子／フランシーヌの場合 　（1969年） - YouTube https://t.co/VjuKjbbE7b

　こちらは１９６９年５月発売という情報があります。やはり作曲編曲ともに日本人の名前ですが、編曲者の名前は苗字だけが日本の名前となっているので、外国人の可能性もあるのかもしれません。日本で暴力的な学生運動があったのもその頃のように思いますが、現在進行で香港で起きているようです。

```
東大安田講堂事件（とうだいやすだこうどうじけん）は、全学共闘会議（全共闘）および新左翼の学生が、東京大学本郷キャンパス安田講堂を占拠していた事件と、大学から依頼を受けた警視庁が1969年1月18日から1月19日に封鎖解除を行った事件である。東大安田講堂攻防戦ともいう。

［source：］東大安田講堂事件 - Wikipedia https://ja.wikipedia.org/wiki/%E6%9D%B1%E5%A4%A7%E5%AE%89%E7%94%B0%E8%AC%9B%E5%A0%82%E4%BA%8B%E4%BB%B6
```

　同じ昭和４４年の事件でしたが、その当時にテレビでニュースを見たという記憶はなく、本やテレビ、ネットの情報でのみみてきたように思います。ベトナム戦争というのも同じ時代だったと思いますが、そちらはテレビで繰り返しニュースを見ていたような記憶があります。

```
千代田区半蔵門にある法律事務所です。
　市民のみなさま、中小企業のみなさまが日常的に抱える法律問題全般を取り扱っています。
　契約書作成、債権回収、取引を巡るトラブルなどから、破産、債務整理、離婚、相続問題、労働問題など幅広く対応いたします。
　刑事事件にも積極的に取り組んでおり、高い専門性を発揮しています。お気軽にご相談ください。

［source：］戸舘圭之法律事務所【事務所紹介】 | 東京都千代田区麹町 半蔵門 http://www.todatelaw.jp/about.html
```

　弁護士紹介は戸舘圭之弁護士のみです。前回調べたときは気にかけていなかったのかと思いますが、千代田区半蔵門という所在地が強調されています。以前、半蔵門は江戸城の１つと聞いた覚えがあるので、現在は皇居の側ということになるのかもしれません。

[link:] » Lynx 麹町 - Google マップ https://t.co/vxPIkzYhcc

　Googleマップでみると、皇居のすぐ近くに東京駅があるので、少し驚きました。皇居の外堀沿いの道路はトラックで走行した憶えがあるのですが、東京駅は実際に見たことがないと思います。能都中学校の修学旅行でも、実際のことはわからないですが、東京駅の記憶は全くありません。

　確か皇居に行く予定が、同級生がバスの窓から投げた空き缶が車に当たってトラブルになり予定が変更になりました。記憶にあるのは羽田空港と東京タワー、宿泊は東京大学の近くと聞いた静かな場所で、日本昔ばなしに出てくる大きなお寺の本堂のような宿泊施設でした。お寺だったのかは不明です。

　これで、鹿児島の芝原章吾弁護士、同じく野平康博弁護士、東京の中村剛弁護士、同じく戸舘圭之弁護士の４人が共通して個人経営の法律事務所と確認できたかと思います。弱者救済を標榜しているように見えるところも共通していると思っていますが、一人でどこま出来るのか大いに疑問です。

　弁護団のような協力関係はあるものと想定しても、打ち合わせや意見の取りまとめの調整、すりあわせなど負担や足枷となる部分も大きくなるように思えるからです。

　事務所を構えた弁護士とは立場も事情も異なると思いますが、個人活動という印象が強いのもジャーナリストの江川紹子氏になります。情報源の多くは弁護士からの聞き取りに依存しているようにも思えますが、実際にジャーナリストの仕事を見たこともないので、想像の部分が大きいです。

　テレビで、沢尻エリカについて昨日午前と聞こえ、時刻を見ると０時６分と日付が変わっていました。新・情報７daysニュースキャスターですが、世界野球で放送時間がずいぶん遅れていたことを思い出しました。

　この項目の見出しで、銀河鉄道９９９の作者、松本零士氏をメインに取り上げたことを、見出しの確認をしたことで思い出しましたが、本題の部分は少なく、あちこちにそれてしまったように思います。それでも弁護士鉄道というテーマでは、一貫性のあるものです。

　鹿児島県は志布志事件と大崎事件が大きいですが、福岡高裁宮崎支部で逆転無罪となった強姦事件もあってそれもずいぶんとミステリー性の高い事件です。未知の世界への入り口のようなミステリー性が事件に共通していますが、宇宙へのロケット発射施設がある種子島も鹿児島県だったと思います。

　私は、ずっと前からSF映画に興味がなくどんな人気作でもまともに見たものは一本も記憶にないのですが、おそらく初期のSF映画として記憶にあるのは「猿の惑星」で、小学生の時、辺田の浜の家のテレビでみた記憶と、平成１３年に服役中の金沢刑務所の独居房で見た記憶があります。

　弁護士星人の惑星が、弁護士鉄道の宇宙空間という見方も一つかと思います。Twitterで日々発見があるのも弁護士鉄道の表現と言論空間です。

　日付が変わって１１月７日になっていますが、６日は法クラ、弁護士らのツイートで岡口基一裁判官に関するツイートをほとんど見かけなかったように思います。５日の夜は、湧き上がる洪水のようなツイートを目にしていましたが、一夜の幻を見ていたような気分になります。記録はしっかりやっています。

　このあと、最新のツイートで、岡口基一裁判官に関するツイートをまとめ記事として作成しておきたいと思います。ジャーナリストのタイムラインで探すのも目的だったと思いますが、見かけてはいなかったような気がします。他のツイートのことで目的はすぐに忘れていたかもしれません。

〈〈〈：Emacs： 2019-11-17（日曜日）00：34 　〈〈〈


