#+TITLE: "心斎橋通り魔、無期懲役が確定へ　最高裁"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-12-02 17:00:02 +0900
FILE_NAME: 2019-12-02-170002_心斎橋通り魔、無期懲役が確定へ　最高裁.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 最高裁,裁判員裁判
記事タイトル名の文字数：19　保存ファイル名の文字数：41
#+STARTUP: showeverything


* 「裁判員の死刑破棄5件目」というTwitterのトレンド：心斎橋通り魔、無期懲役が確定へ　最高裁
  CLOCK: [2019-12-02 月 17:07]--[2019-12-02 月 18:24] =>  1:17

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 最高裁,裁判員裁判

〉〉〉：Emacs： 2019-12-02（月曜日）17：07　 〉〉〉

```
大阪・心斎橋の路上で平成２４年６月、通行人の男女２人を無差別に刺殺したとして殺人罪などに問われ、１審裁判員裁判の死刑判決が２審で破棄され無期懲役となった礒飛（いそひ）京三被告（４４）の上告審判決で、最高裁第１小法廷（小池裕（ひろし）裁判長）は２日、検察、弁護側双方の上告を棄却した。２審判決が確定する。裁判員裁判の死刑判決破棄事件５件全てが確定することになった。

　第１小法廷は、今回の事件について、場当たり的で衝動的な犯行だったことがうかがえると指摘。「無差別殺人遂行の意思が極めて強固だったとは認められず、生命軽視の度合いも甚だしく顕著だったとはいえない」とした。

［source：］大阪・心斎橋通り魔の無期確定へ　裁判員の死刑破棄５件目　最高裁（1/2ページ） - 産経ニュース https://www.sankei.com/affairs/news/191202/afr1912020028-n1.html
```

　テレビの情報番組ミヤネ屋の後半で、判決が出る前から最高裁前からの中継を交えて報道をしていました。この事件、刑事裁判のこともテレビの報道をみて知っていましたが、今日の判決のことは事前に情報を見ておらず知らなかったと思います。

　最高裁で判決が出るということは、通常の書面審理のみではなく公判が開かれたことになるはずですが、公判の審理が開かれたということも知らず、個人的には全くいきなりのニュースでした。この産経新聞のネットニュースには、裁判員の死刑破棄５件目とありますが、テレビでは聞いていません。

　時刻は１７時１４分になったところです。ちょうど１７時頃にテレビをつけ、となりのテレ金ちゃんというローカル番組で、このあと全国ニュースをお届けします、というところから始まるという絶妙のタイミングでした。

　今日は４つの刑事裁判の大きなニュースがありました。そのうち１７時を過ぎてからのeveryでニュースを見たのは、新井浩文被告の保釈のニュースだけだった気がします。１７時１２分あたりからスポーツ関係のニュースが続き、最初のニュースも流行語大賞でした。

　４つの刑事裁判の大きなニュースというのは、新井浩文被告の懲役５年判決、福岡地裁での元警察官の妻子３人の殺害で死刑求刑、川崎市の通り魔殺人事件で無期懲役の求刑、そして最高裁の心斎橋通り魔、無期懲役判決になります。

　産経ニュースでは大阪・心斎橋となっていますが、テレビなどの他の報道では大阪ミナミと見てきたように思います。心斎橋というのは思い出のある場所で、昭和５７年の夏だったと思いますが、初めて大阪に遊びに行った場所が心斎橋でした。

　大阪のミナミという繁華街は漫画や小説などでもよく見かけてきましたが、心斎橋とは別の場所だと思っていました。

　大阪市の中心部というのは、昭和５９年にだけ集中して行った記憶があります。最初に金沢市場輸送の４トン保冷車に乗務した頃のことです。大阪市内の仕事が多かったのですが、東部市場から本場市場に向かったことも何度かありました。

　先輩の運転手から大阪市内は広い一方通行の道路も多く、日本で一番道路がややこしいと聞いていましたが、たしかに東京都内では道路事情で困ることは余りなかったように思います。それも昭和５９年に聞いた話で、その後は見聞きしたことのない話ではあります。

　テレビでロンドン橋の５人殺傷事件をやっていますが、２，３日前にツイートの動画で、警察官が射殺をする直前の動画を見ていました。一般人が組み伏せていたのですが、警察官が離れるように指示をし、直後に射殺したという話でした。

　ちょうどイギリスのロンドンのことが出てきたのですが、ロンドン市内の道路事情はとても複雑なので、タクシー運転手はとても頭がよく、優秀でないとできない仕事という話がありました。たぶんテレビでみたように思いますが、１０年近く前になるかもしれません。

　５時４５分で、１分ほど前になりますが、テレビでまた刑事裁判のニュースがあり、懲役１７年の判決でした。犯行態様から軽めの判決かと思ったのですが、「虚偽のいいわけに終始しており、反省していない」などと断罪されたようです。完全に忘れていましたが、高崎市職員の女性殺害事件です。

```
さいたま市のビルで１月、群馬県高崎市出身の女性会社員（22）＝埼玉県春日部市＝が殺害された事件で、殺人と銃刀法違反の罪に問われた交際相手で元前橋市職員の男（26）＝前橋市大渡町＝の裁判員裁判論告求刑公判が27日、さいたま地裁（北村和裁判長）で開かれ、検察側は懲役20年を求刑した。弁護側は傷害致死罪により懲役７年が相当と主張した。

［source：］交際相手殺害 元前橋市職員に20年求刑　さいたま地裁で検察側｜社会・話題｜上毛新聞ニュース https://www.jomo-news.co.jp/news/gunma/society/176485
```

　Google検索では求刑のニュース記事だけ見つかりました。１１月２８日付の記事です。求刑が懲役２０年で、弁護側は傷害致死で懲役７年が相当と主張したとのことです。以下に別の引用をしますが、弁護側の主張が具体的に記載されています。

```
弁護側は、目撃証言について「傷の状況や解剖医の証言と矛盾し、時間の経過によって変化していて信用できない」と主張。包丁の刃約20センチに対し、致命傷の最深部が3.7センチであるとして「取り押さえられて抵抗した際、包丁が被害者に当たってしまったと考えても矛盾がない」と訴えた。インターネット検索については「閲覧時間は短く、予測変換で出てきたページを見ただけで殺意があったとは言えない」とした。

［source：］交際相手殺害 元前橋市職員に20年求刑　さいたま地裁で検察側｜社会・話題｜上毛新聞ニュース https://www.jomo-news.co.jp/news/gunma/society/176485
```

　今日は、刑事裁判のニュースだけではなく事件のニュースも多く感じるのですが、男女が倒れ男の子が死亡という始まりのニュースで、中学生同士の心中事件なのかと思ったのですが、母親が子どもを殺害し本人も意識不明の重体となっているようです。島根県安来市とありました。

　安来節と同じで「やすきし」になるものと思っていたのですが、テレビの女子アナウンサーははっきり「やすぎし」と発音をしていました。この安来市については、国道９号線沿いの奇石のことで取り上げましたが、そのことがきっかけで翌日ぐらいに恋路海岸に行ってきました。

　そのとき恋路海岸というか恋路の集落でもいろいろ発見があったのですが、そのあと珠洲市まで足をのばし、久しぶりに珠洲総合病院の前に行ったところ、いつの間にか出来ていた図書館に入り、そこで北國新聞の縮小版で平成４年の傷害・準強姦被告事件の記事を読むということもありました。

　その珠洲市民図書館が出来ていた場所は、平成２１年９月当時、珠洲総合病院の駐車場で、そこでの京都の親戚の話というのも印象的なものでいずれ記述することを予定しています。また、温帯低気圧でその珠洲市民図書館の屋根が強風でまくれ上がるというニュースもありました。

```
台風１７号に伴う暴風が吹き荒れた２３日、珠洲市民図書館（同市野々江町）の屋根がめくれる被害があった。図書館は今年３月にオープンしたばかり。市は２４日から休館としたが、再開のめどは立っていない。

　市や奥能登広域圏事務組合消防本部によると、２３日午後１時半ごろに消防への通報で被害を把握。トタンの屋根が…

［source：］台風１７号　暴風、各地で被害　新設図書館、屋根めくれる　珠洲　／石川 - 毎日新聞 https://mainichi.jp/articles/20190925/ddl/k17/040/250000c
```

[link:] » 珠洲市民図書館 - Google 検索 https://t.co/vt1IzHX7Rl

　検索オプションでニュースを指定し、出てきたのは上記の毎日新聞の有料記事１件のみでしたが、続報で億を超える被害というニュースで、１億か２億と書いてあったように思います。修理が終わる前に大型台風が来て心配されていましたが、被害のニュースはなかったようです。

[link:] » 島根・安来市のアパートで小学生男児死亡 母親は重体 TBS NEWS https://t.co/U9L0GYaWkD

　なぜか死亡した小学生男児の年齢の記載がないのですが、テレビで父親は病院に入院中、３人家族とありました。

　次のニュースも気になるニュースでテレビで繰り返し報道を見ていますが、テレビでは名前の報道がなく、昼前のニュースでは２歳か３歳という曖昧な報道のされかたをしていたので、それも気になっていました。さきほどのテレビの報道で女子アナの解説にも気になる点がありました。

```
弁護側は、目撃証言について「傷の状況や解剖医の証言と矛盾し、時間の経過によって変化していて信用できない」と主張。包丁の刃約20センチに対し、致命傷の最深部が3.7センチであるとして「取り押さえられて抵抗した際、包丁が被害者に当たってしまったと考えても矛盾がない」と訴えた。インターネット検索については「閲覧時間は短く、予測変換で出てきたページを見ただけで殺意があったとは言えない」とした。

［source：］交際相手殺害 元前橋市職員に20年求刑　さいたま地裁で検察側｜社会・話題｜上毛新聞ニュース https://www.jomo-news.co.jp/news/gunma/society/176485
```

〈〈〈：Emacs： 2019-12-02（月曜日）18：24 　〈〈〈

* 「ミナミ通り魔　最高裁二審支持「無期懲役」」、弁護士らの反応の記録
  CLOCK: [2019-12-03 火 09:55]--[2019-12-03 火 17:22] =>  7:27

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 最高裁,裁判員裁判

〉〉〉：Emacs： 2019-12-03（火曜日）09：55　 〉〉〉

[link:] 2019年12月03日00時16分の登録： REGEXP：”最高裁”／データベース登録済みツイートの検索：2019-12-02〜2019-12-03／2019年12月03日00時14分の記録：ユーザ・投稿：31／40件 http://hirono2014sk.blogspot.com/2019/12/regexp2019-12-022019-12.html

　日付が変わり本日12月3日になってからの記録作成だったようです。このまとめの作成には1日つまり24時間という範囲指定を行っています。時間範囲を指定する引数の部分に、コマンド展開で、その時の時間からちょうど1日間を指定範囲にしています。

　端末でのコマンド展開は「"`date +"%Y-%m-%d %H:%M" --date "1 day ago"`/`date +"%Y-%m-%d %H:%M"`"」になります。

　これをechoコマンドの引数にすると、「2019-12-02 10:02/2019-12-03 10:02」という文字列に置き換わります。

　「最高裁」をキーワードにしたまとめ記事は、ニュースサイトのツイートのリツイートや、記事を紹介しただけのものが多く、意見の表明のようなものはわずかでした。

　１つだけ気になるツイートがあって、Twitterのプロフィールからは弁護士と特定しうる記載はないものの、ツイートの内容でだいぶん前から個人的な判断として法クラとして認定してきたアカウントです。

　最近はツイートも見かけていなかったのですが、タイムラインを開いたところ、気になるツイートがあってそこにあるリンクを開いたところ、昨日12月2日付の最高裁の判決文を読むことが出来ました。

▶（36／40） TW k1e8i1k5o2k2e29（漂う蛸） 日時： 2019-12-02 21:59:00 +0900 URL： https://twitter.com/k1e8i1k5o2k2e29/status/1201485956445945856
{% tweet 1201485956445945856 %}
> 今日の最高裁判決は「無差別殺人」という殺人の社会的類型について一般論を展開しているが、こういう一般論はかなり珍しい気がする。

　漂う蛸という変わったプロフィールの名前のアカウントです。この蛸というのも個人的に思うところがあって一層強く印象に残っていました。パチスロ機「伝説の巫女」の虎次郎だったと思いますが、ボーナスチャンスの演出に、海辺でのタコとの対決があったからです。

　大きな凶暴そうなタコで、なぜか「世界をとるの」というような文字を書いた鉢巻を頭につけていました。最近になって舳倉島でもタコは海藻を食べる悪者として敵対視するような伝承があったという情報をみかけたということもありました。

　ここ5年ほどの間に知ったように思いますが、海でとったタコを同じ網に入れていると共食いを始めるとのことです。タコが自分の手足を食べるというのも、以前より見かけてきた表現です。個人的な弁護士に対するイメージは、見境なしの獰猛さという点でこの蛸という要素もあります。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜k1e8i1k5o2k2e29（漂う蛸） 日時：2019-12-03 10:34／2019/12/02 18:07 URL： https://twitter.com/kk_hirono/status/1201676116626268160 https://twitter.com/k1e8i1k5o2k2e29/status/1201427592382795776
> 被告人を死刑に処した裁判員裁判による第１審判決を量刑不当として破棄し無期懲役に処した原判決の刑の量定が維持された事例 https://t.co/t6LXAjSxcL
▶▶▶　　　　　End　　　　　▶▶▶

［link：］ 裁判所 | 裁判例情報：検索結果詳細画面 http://www.courts.go.jp/app/hanrei_jp/detail2?id=89071

　記録を調べてみましたが、やはり弁護士を同業者とするツイートがあったり、弁護士である可能性が高そうです。プロフィールの名前が変わっているとは思いますが、特に異常性や社会的病害、その他影響を感じたことはなく、それでブックマークにも入れていなかったのだと思います。

```
% dp -p|grep 蛸
[link:] 2019年02月08日13時32分の登録： ＼ystk　@lawkus＼その当時あまり区別なく交流していたことには異論ないのですが、今は垣根が高くなった（やや蛸壺化した）のではないかというのが先のツイートの趣旨です http://hirono2014sk.blogspot.com/2019/02/ystklawkus_8.html
[link:] 2019年03月26日11時15分の登録： ＼漂う蛸　@k1e8i1k5o2k2e29＼同業者に対する不当懲戒請求事案は重くしたほうがいいですよね。ただの業務妨害になるわけですから。 http://hirono2014sk.blogspot.com/2019/03/k1e8i1k5o2k2e29.html
[link:] 2019年03月26日11時16分の登録： ＼漂う蛸　@k1e8i1k5o2k2e29＼被疑者「警察官が先生のことを金欠豚バッジ弁護士って言ってましたよ。」 弁護人「よろしい、ならば戦争だ。本当のフルコース刑事弁護 http://hirono2014sk.blogspot.com/2019/03/k1e8i1k5o2k2e29_26.html
[link:] 2019年03月26日11時17分の登録： ＼漂う蛸　@k1e8i1k5o2k2e29＼法律相談や依頼者との打合せでときたま現れる「知り合いの弁護士さん」ですが、我々からするとネッシーみたいな存在ですよね。 http://hirono2014sk.blogspot.com/2019/03/k1e8i1k5o2k2e29_62.html
[link:] 2019年03月26日11時17分の登録： ＼漂う蛸　@k1e8i1k5o2k2e29＼最近の判決批判の騒ぎをみてると、罪刑法定主義が単なる法律上の原則ではなく、憲法上の原則であることの重要性がわかるな。  http://hirono2014sk.blogspot.com/2019/03/k1e8i1k5o2k2e29_38.html
[link:] 2019年03月27日09時26分の登録： ＼漂う蛸　@k1e8i1k5o2k2e29＼しかし、あの人の怨霊みたいなコメントを集める素質というか、タタリ神的能力は凄まじいな。  http://hirono2014sk.blogspot.com/2019/03/k1e8i1k5o2k2e29_27.html
[link:] 2019年03月27日09時27分の登録： ＼漂う蛸　@k1e8i1k5o2k2e29＼すごいからみかたをしている人を見たが、同業者みんなから嫌われてるんじゃないかな。あの人。 http://hirono2014sk.blogspot.com/2019/03/k1e8i1k5o2k2e29_19.html
[link:] 2019年03月27日09時28分の登録： ＼漂う蛸　@k1e8i1k5o2k2e29＼しかし、年度末で無罪が続くと、同じく年度末でただでさえ忙しいだろう検察庁が、控訴の検討もしなきゃならなくなって大変だろうな。  http://hirono2014sk.blogspot.com/2019/03/k1e8i1k5o2k2e29_71.html
[link:] 2019年03月27日09時29分の登録： ＼漂う蛸　@k1e8i1k5o2k2e29＼本当に批判されるような内容なら控訴審で結論が変わるでしょうし、そうでないなら一審が維持されるでしょうね。  http://hirono2014sk.blogspot.com/2019/03/k1e8i1k5o2k2e29_47.html
[link:] 2019年03月28日14時48分の登録： ＼漂う蛸　@k1e8i1k5o2k2e29＼どのような主張をされるにしても，判例実務における性犯罪規定の解釈や事実認定について，もう少し前提を共有できないものかな。例えば http://hirono2014sk.blogspot.com/2019/03/k1e8i1k5o2k2e29_28.html
[link:] 2019年04月03日14時09分の登録： ＼漂う蛸　@k1e8i1k5o2k2e29＼某事件だけど，勾留や保釈の際にさんざん罪証隠滅の危険を吹聴して，保釈後もあんな保釈条件じゃだめだとか言ってたのに，どうして別件 http://hirono2014sk.blogspot.com/2019/04/k1e8i1k5o2k2e29.html
[link:] 2019年04月10日16時08分の登録： ＼漂う蛸　@k1e8i1k5o2k2e29＼最近何かと検察特捜部が話題なので大坪弘道「勾留百二十日」を読んでいるのですが「刑事事件を専門に手がけるヤメ検は検察と持ちつ持た http://hirono2014sk.blogspot.com/2019/04/k1e8i1k5o2k2e29_10.html
[link:] 2019年04月21日19時48分の登録： ＼漂う蛸　@k1e8i1k5o2k2e29＼深澤諭史さんがリツイート\n￼\n漂う蛸\n\n \n@k1e8i1k5o2k2e29\n 2時間2時間前\n￼ その他\n元警察や元検察の http://hirono2014sk.blogspot.com/2019/04/k1e8i1k5o2k2e29-k1e8i1k5o2k2e29-22.html
[link:] 2019年05月02日22時46分の登録： ＼漂う蛸　@k1e8i1k5o2k2e29＼そろそろ、令和1号の準抗告を獲得するために、弁護人たちが裁判所夜間窓口へ駆け込む準備を始める時間帯ですね。 http://hirono2014sk.blogspot.com/2019/05/k1e8i1k5o2k2e291.html
[link:] 2019年05月10日00時20分の登録： ＼漂う蛸　@k1e8i1k5o2k2e29＼判決を読んだ印象としては、監護者性交等罪（18歳未満）であれば問題なく「影響力があることに乗じて」は認定できそうな事案で、法改 http://hirono2014sk.blogspot.com/2019/05/k1e8i1k5o2k2e2918.html
[link:] 2019年05月10日00時42分の登録： ＼漂う蛸　@k1e8i1k5o2k2e29＼仮に抗拒不能が認められた場合は、その抗拒不能の原因である長年の性的虐待等について被告人は認識しているけれど、やはり故意は認めら http://hirono2014sk.blogspot.com/2019/05/k1e8i1k5o2k2e29.html
[link:] 2019年06月28日11時08分の登録： ＼漂う蛸　@k1e8i1k5o2k2e29＼「まだ最高裁がある」ってセリフは、最近は検察のためのものになってきたなぁ。 http://hirono2014sk.blogspot.com/2019/06/k1e8i1k5o2k2e29.html
[link:] 2019年06月29日23時52分の登録： ＼漂う蛸　@k1e8i1k5o2k2e29＼大崎事件（第３次最高裁決定）に思う｜名古屋市中区の弁護士法人 金岡法律事務所 http://hirono2014sk.blogspot.com/2019/06/k1e8i1k5o2k2e29_29.html
[link:] 2019年07月01日17時16分の登録： ＃漂う蛸　@k1e8i1k5o2k2e29＃のツイート／2019-05-31_0017〜2019-07-01_1601／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年07月01日17時16分 http://hirono2014sk.blogspot.com/2019/07/k1e8i1k5o2k2e292019-05-3100172019-07.html
[link:] 2019年07月08日21時28分の登録： ＃漂う蛸　@k1e8i1k5o2k2e29＃のツイート／2019-06-05_2229〜2019-07-08_2114／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年07月08日21時28分 http://hirono2014sk.blogspot.com/2019/07/k1e8i1k5o2k2e292019-06-0522292019-07.html
[link:] 2019年07月21日21時19分の登録： ＼漂う蛸　@k1e8i1k5o2k2e29＼大阪はもう当確すべて出たか。亀石先生はダメだったか。 http://hirono2014sk.blogspot.com/2019/07/k1e8i1k5o2k2e29.html
[link:] 2019年09月24日21時58分の登録： ＼漂う蛸　@k1e8i1k5o2k2e29＼これは文科省が音頭をとって児相みたいに非常勤で配置するのかしら。年間4億円の予算すべてが弁護士報酬としても300人配置だと、一 http://hirono2014sk.blogspot.com/2019/09/k1e8i1k5o2k2e294300.html
[link:] 2019年10月16日15時41分の登録： ＼漂う蛸　@k1e8i1k5o2k2e29＼会長になって、「弁護士になって５年、１０年と過ぎてもキャリアアップできない状況」の５０歳越えた弁護士の救済に労力やお金を使おう http://hirono2014sk.blogspot.com/2019/10/k1e8i1k5o2k2e29.html
[link:] 2019年11月14日22時31分の登録： ＼漂う蛸　@k1e8i1k5o2k2e29＼書籍の紹介（責任能力研究）｜名古屋市中区の弁護士法人 金岡法律事務所 http://hirono2014sk.blogspot.com/2019/11/k1e8i1k5o2k2e29.html
[link:] 2019年11月28日03時17分の登録： ＼漂う蛸　@k1e8i1k5o2k2e29＼保釈と自白といえば最近だと郷原先生の担当された青梅の談合事件もありますね。否認すると保釈が通らないという運用がどれだけ被告人に http://hirono2014sk.blogspot.com/2019/11/k1e8i1k5o2k2e29_28.html
```

[link:] » 伝説の巫女　「愛娘」 - ニコニコ動画 https://t.co/MtfG84Apzm

[link:] » 【伝説の巫女】　『もののけ音頭』　『夢の途中』 - YouTube https://t.co/eOIqfKgN2h \n 　虎次郎の蛸への連打。再生23秒あたり。

[link:] » 【伝説の巫女】　『もののけ音頭』　『夢の途中』 - YouTube https://t.co/eOIqfKgN2h \n 　虎次郎が海岸で歌を熱唱の場面。蛸の出現前。再生2分51秒辺り。

[link:] » 【伝説の巫女】　『もののけ音頭』　『夢の途中』 - YouTube https://t.co/eOIqfKgN2h \n 　虎次郎の背後に、海から巨大な蛸の出現場面。再生3時29秒辺り。

　ボーナスチャンスで虎次郎と蛸の対決のときに流れるのが「愛娘」という曲だったと思います。正確には海辺で木箱の上に立ち虎次郎が「愛娘」を熱唱している時に現れるのが凶暴そうな蛸でした。

```
ストーリー［編集］
今もまた古（いにしえ）の頃、九九九年前。四方を海に囲まれ、異国文化と交わる事の無い島国が、悪霊妖怪によって壊滅状態に陥った。多くの犠牲者の魂が、島の中心に位置する神社の境内に集結し、巨大な神火となった。その炎の中から、一人の戦士が現れる。彼女の名は、『炎の巫女戦士』。人々の希望と哀しみを正義の炎に変え、悪霊妖怪達を封印した。

時は流れ、伝説は再び繰り返される。島の中心に位置する村民のシンボル、『もののけ神社』の占拠を足がかりに、島国の独占を謀る愚霊斗武者率いる悪霊妖怪軍団。彼らの陰謀を阻止すべく、かえでとその仲間達は立ち上がる。

登場人物［編集］
日丸かえで（声 ‐ 野川さくら）
主人公。駄目親父・虎次郎に代わってもののけ神社を守るため修行中の巫女。
荒行で開眼すると『炎の巫女』に変身する。口癖は「〜だもん」。なお、変身すると性格と口調がかなり荒っぽく変わる（メーカーの小冊子によると、炎のかえでの状態では「大胆不敵で正義のためには手段を選ばない」との事）。
日丸虎次郎（声 ‐ 中井和哉）
かえでの父親。もののけ神社の神主。
サングラスをかけ、『特攻』と書かれた鉢巻を巻いている。趣味は筋トレとカラオケ。天狐ボーナスの大当たりラウンド中の曲は、娘への愛情を歌った歌である。

［source：］パチスロ伝説の巫女 - Wikipedia https://ja.wikipedia.org/wiki/%E3%83%91%E3%83%81%E3%82%B9%E3%83%AD%E4%BC%9D%E8%AA%AC%E3%81%AE%E5%B7%AB%E5%A5%B3
```

　もののけ神社の神主という設定になっている伝説の巫女、日丸かえで、の父親、虎次郎ですが、かえでの回想シーンによると、かえでが生まれた頃は、髪の毛もあって普通に見える父親でしたが、かえでが生まれてすぐに妻であるかえでの母親がなくなったらしく、そこから変わったようです。

　今朝は、「無期懲役」をキーワードにまとめ記事を作成しました。期間の指定のないものと、期間を24時間以内にしたもの２つです。

[link:] 2019年12月03日10時05分の登録： REGEXP：”無期懲役”／データベース登録済みツイート：2019年12月03日10時01分の記録：ユーザ・投稿：107／352件 http://hirono2014sk.blogspot.com/2019/12/regexp201912031001107352.html
[link:] 2019年12月03日10時06分の登録： REGEXP：”無期懲役”／データベース登録済みツイートの検索：2019-12-02〜2019-12-03／2019年12月03日10時05分の記録：ユーザ・投稿：20／28件 http://hirono2014sk.blogspot.com/2019/12/regexp2019-12-022019-12_43.html

　想定していなかったのですが、無期懲役のワードだと、川崎通り魔事件の無期懲役の求刑のニュースが出てきました。昨日の昼、テレビでニュースをみましたが、どの番組だったか思い出せません。たぶんミヤネ屋の全国ニュースのコーナーであったような気はしますが、未確認です。

▶（02／28） RT nippyo（日本評論社）｜YahooNewsTopics（Yahoo!ニュース） 日時：2019-12-02 14:30:00 +0900／2019-12-02 12:28:00 +0900 URL： https://twitter.com/nippyo/status/1201372935455264768 https://twitter.com/YahooNewsTopics/status/1201342290448371713
{% tweet 1201372935455264768 %}
> 【06年川崎通り魔 無期懲役求刑】 \n https://t.co/cIHp9UsKw1 \n \n 川崎市のトンネルで2006年、面識がない女性を殺害したとして殺人罪に問われた被告の裁判員裁判が横浜地裁であり、検察側は無期懲役を求刑した。被告は… https://t.co/jRkzrqWQFa

▶（08／28） TW news24ntv（日テレNEWS24） 日時： 2019-12-02 15:50:00 +0900 URL： https://twitter.com/news24ntv/status/1201393228068487168
{% tweet 1201393228068487168 %}
> トンネルで女性殺害　男に無期懲役を求刑 https://t.co/kOCUBJtCd1 #日テレNEWS24 #ntv

　上記の日テレニュースの記事ですが、「トンネルで女性殺害　男に無期懲役を求刑」というのはずいぶん簡単な見出しになっています。川崎という地名が入ることは多かったと思いますが、手抜きで付けた見出し名ではなさそうな気はします。

▶（12／28） TW tv_asahi_news（テレ朝news） 日時： 2019-12-02 17:00:00 +0900 URL： https://twitter.com/tv_asahi_news/status/1201410697692737536
{% tweet 1201410697692737536 %}
> 栃木・強盗致死事件　“主犯格”に無期懲役を求刑 \n https://t.co/VIkXdHauuV

　テレビでは見ていなかった刑事裁判のニュースですが、記事の日付が昨日12月2日となっているものの、記事の本文に公判の日付が見当たりませんでした。判決が6日とはあります。通常だと裁判員裁判になりそうですが、その記載も記事には見当たりません。

```
去年、2回にわたって栃木市の住宅に押し入り、82歳の男性を殺害して現金などを奪ったとして暴力団の元組員らが逮捕された事件の裁判で、検察側は主犯格とみられる元組員の男に無期懲役を求刑しました。

［source：］栃木・強盗致死事件　“主犯格”に無期懲役を求刑 https://news.tv-asahi.co.jp/news_society/articles/000170649.html
```

　栃木県や茨城県は殺人事件のニュースが多いという印象がありますが、この強盗致死事件のことは知らなかったと思います。殺害して現金などを奪ったとあるのに、強盗殺人ではなく強盗致死となっているようです。法律上、強盗致死が条文にあることは知っていましたが、適用は珍しく感じました。

　指示役で主犯、無期懲役の求刑というのも気になるところです。この短い記事からは事件の内容がほとんどわからず、まとめ記事の作成がなければ知ることもなかったように思います。

　そういえば先程の最高裁の判決文に、弁護士の名前が１つあったことを思い出しました。見たことのない弁護士名でしたが、大物っぽい感じはしました。

```
新聞記者を経て弁護士になりました。これまで300件以上の刑事事件（裁判員裁判は30件以上）を担当しました。 依頼者のみなさまに寄り添う弁護をモットーにしています。

［source：］弁護士紹介 – ゼラス法律事務所 https://www.zealous-law.com/introduction/#takayama
```

　同姓同名の可能性は未確認ですが、この代表弁護士、高山厳弁護士の可能性は高そうです。斜め方向から撮影された顔写真が掲載されていますが、比較的若い感じです。学歴に年の記載はないですが、弁護士登録は平成19年と記載があります。弁護士経験は12年目ぐらいかと思います。

　最初にゼラス法律事務所が「ゼウス法律事務所」に見えて、ギリシア神話の最高神のような神様の名前ではなかったかと思ったのですが、ゼラスという言葉の意味も気になるところです。何より気になったのは、3人にいる男性弁護士の2人目の弁護士のキャッチコピーです。

　ゼラス法律事務所の住所が大阪市北区西天満となっているのも気になっていたことを思い出すきっかけになりました。

　かなり珍しい名前と思っても、同じ業界に同姓同名があったという経験はずいぶん前になりますがあったという記憶があります。高山厳弁護士に同姓同名はないのかと、再度、Google検索を行ったところ、思いがけない発見がありました。高野隆弁護士、趙誠峰弁護士との接点です。

　趙誠峰弁護士は、昨日12月2日の同じ日になりますが、俳優、新井浩文被告の強制性交事件で求刑通りの懲役5年の判決が出ていて、その代理人のはずの弁護士になります。その辺りも含めて、このあと別の記事エントリーとして取り上げておきたいと思います。

　時刻は12時17分です。また思わぬところから大きな発見がありました。

▶（18／28） TW momo3580（momo3580@肥える秋） 日時： 2019-12-02 18:53:00 +0900 URL： https://twitter.com/momo3580/status/1201439164937302017
{% tweet 1201439164937302017 %}
> 個人的には納得行かない。 \n \n 大阪・ミナミ通り魔事件　無期懲役確定へ　最高裁、被告、検察双方の上告を棄却 https://t.co/uQzRURsI1A

　同じツイートになるのかと思いますが、さきほどの「最高裁」をキーワードにしたまとめ記事でも、同じアカウントのツイートを見かけていました。プロフィールの名前に余り見覚えはなく、これはコロコロと変更されることもあるのですが、プロフィールを見ても弁護士とは確認できませんでした。

　私のまとめ記事は、同じスクリプト（台本のようなプログラム）使って、データの作成からブログへの投稿まで１つの処理つまりコマンドの実行で行っていますが、CSSによるデザインの適用も同じになっています。

　「momo3580（momo3580@肥える秋）のプロフィール情報へのリンク」という部分は、文字列の背景色を薄い水色にし、本人のツイートであることを示しています。

　指定したアカウントのリツイートの場合は、背景色を薄いピンクとし、次のように表示しています。→　emeth_pippi（当職ぴっぴにゃん)＜リツイートをしたアカウント＞のプロフィール情報へのリンク

　データベースへの登録済みツイートが処理の対象になりますが、その多くは、現時点で1623という登録済みアカウントになります。TwitterAPIなどの検索は、その登録アカウントのリストと照合し、マッチしたもののみをデータベースに追加するという処理を行っています。

　個人的な発案で作った個人的な処理装置になりますが、個人的であるが故に不十分な点もあるかと思います。これは主にTwitterAPIのライセンスによる処理回数のリミット制限によるものです。APIの仕様を把握しきれているわけでもないので、違いの大きさはわかっていません。

```
momo3580@肥える秋
@momo3580
【注】TW/RT等は、全て単なる私的なものです。
【自己紹介】ゆるふわもこもこですが中身はそうでもないおじさんです。
中北関東2010年3月からTwitterを利用しています
543 フォロー中
1,286 フォロワー

［source：］momo3580@肥える秋（@momo3580）さん / Twitter https://twitter.com/momo3580
```

```
% dp -p|grep '@momo3580'
[link:] 2019年05月09日10時37分の登録： ＼momo3580煩悩之鎌足　@momo3580＼一度でも記者会見などをやれば分かります。\n基礎的知識をまったく持たず、明らかに間違ったことを質問してくる記者さんがいるこ http://hirono2014sk.blogspot.com/2019/05/momo3580momo3580.html
[link:] 2019年06月24日13時54分の登録： ＼momo3580@早朝覚醒　@momo3580＼何故法クラはTLを殺ばつ化しようとするのか。\n我々はその謎を探るべく、総本山の17階へ登ろうとしたが、エレベータがなかな http://hirono2014sk.blogspot.com/2019/06/momo3580momo3580tl-17.html
```

　過去の記録を調べましたが、上記の2件のみでした。ツイートの内容は思い出すことのあるものでしたが、覚えにくいプロフィールの名前である上、たぶん他にツイートを見る機会が少なかったのだと思います。アイコンは「ぐんまちゃん」ではなかったかと思う着ぐるみの写真です。

　大きな発見となったのは「「弁護士、時効までに訴訟せず」　2.5億円求め提訴：朝日新聞デジタル」という内容のあるツイートです。似たような問題を数日前に見たところでしたが、そちらは和解で、大阪府北区西天満の弁護士法人の法律事務所となっていたように思います。

　これも新たもカテゴリを設置して、新規のエントリーとして記録をしておきたいと思います。

　前後になりますが、他にも大きめの発見がありました。実質はかなり大きな発見だと考えています。栃木県の黒羽刑務所とも関連があります。

▶（20／28） TW tk84yuki（高橋ユキ） 日時： 2019-12-02 19:58:00 +0900 URL： https://twitter.com/tk84yuki/status/1201455584064630784
{% tweet 1201455584064630784 %}
> 『つけびの村』でも記したように、ご遺族は陳述で「私たちの望みは被告人が全てを正直に話すこと」と語っていた。「しかしそれは裏切られた」とも。→川崎通り魔殺人で検察側が無期懲役を求刑　横浜地裁 https://t.co/aRMDWYh2He

　久しぶりに見たアカウントになりますが、Twitterのプロフィールで確認したところ、やはり霞っ子クラブの関係者でした。「傍聴人。フリーライター。」とプロフィールの先頭にあります。

　「ご遺族は陳述で「私たちの望みは被告人が全てを正直に話すこと」と語っていた。「しかしそれは裏切られた」とも。」というツイートの部分が、運命的とも思えるぐらいじわじわと来る発見になったのですが、これも別のエントリーとして記録をしたいと思います。

　なお、固定されたツイートに紹介されている「つけびの村」という書籍ですが、調べて山口県の集落での事件だと確認しました。平成の八つ墓村とも呼ばれた事件です。この事件については、他のライターのことでもずいぶん気になったことがあり、山梨県の地方病ともつながります。

[link:] » 地方病 (日本住血吸虫症) - Wikipedia https://t.co/RxVxslHsUA

　すでにいくらか取り上げたことはあったかもしれません。ミヤイリガイ（宮入貝）というのも出てきて、それが病原体として発見されるのですが、この辺りも私の「弁護士脳汚染除去装置」の研究開発に影響を与えています。なお、宮入は宮入慶之助 (1865 - 1946)の名前のようです。

　生誕の1865年はまだ江戸時代ですが、私の生まれが1964年になるのでちょうど99年前になるのだと気が付きました。たぶんこのWikipediaでしか見たことのない名前だと思いますが、救われた人はずいぶん多そうです。

```
ミヤイリガイ（宮入貝）またはカタヤマガイ（片山貝）、学名： Oncomelania hupensis nosophora は、盤足目・イツマデガイ科に分類される巻貝の一種である。日本住血吸虫の中間宿主として知られる。

ミヤイリガイの名は発見者の宮入慶之助に、カタヤマガイの名は日本住血吸虫症の症状を書き記した19世紀中頃の書物『片山記』［3］に由来する。また、岡山県高屋川流域の生息地ではナナマキガイという方言で呼ばれていた［4］。

殻は栗褐色で厚く堅い。殻の表面は滑らかで光沢がある。殻の高さ7mm、幅2.5mmほどで、巻きは8階。水田の溝や浅い小川などの止水域の泥底に生息する［5］。親貝は6月頃、常に湿潤な柔らかい泥土に産卵し、孵化した個体は秋までに大きくなるのが一般的。冬は叢の根元や窪みで越冬する［6］。寿命は約2年かそれ以上と推測される［7］。

［source：］ミヤイリガイ - Wikipedia https://ja.wikipedia.org/wiki/%E3%83%9F%E3%83%A4%E3%82%A4%E3%83%AA%E3%82%AC%E3%82%A4
```

　今回調べてみると、「中間宿主」という言葉が新たな発見に感じられました。「水田の溝や浅い小川などの止水域の泥底に生息する」とあります。長野県の食堂に入った時、田んぼにいると思う「タニシ」が名物料理になっているのを見て、ずいぶん驚いたことがありました。

```
桂田富士郎は加賀国大聖寺藩（現：石川県加賀市）出身の病理学者で、岡山医学専門学校（現：岡山大学医学部）教授の当時35歳であった。また、桂田は当時岡山県南西部で流行していた、別の寄生虫病（肝臓ジストマ）の研究者でもあった［79］。

1904年（明治37年）春、前述した山梨での討論会で三神と意気投合した桂田は岡山から山梨の三神宅へ赴き、両名による甲府盆地各所の罹患者の診察および糞便検査が行われ、数名の便から三神が以前に発見した新種と思われる虫卵を再確認した［78］。また、県病院より提供された杉山なか等3名の病理標本を顕微鏡の倍率を上げ改めて詳細に検証し、大きさや形状から判断して、これら3例の肝臓にある虫卵も糞便検査で見つかった卵と同一であると確信した［80］。

［source：］地方病 (日本住血吸虫症) - Wikipedia https://ja.wikipedia.org/wiki/%E5%9C%B0%E6%96%B9%E7%97%85_(%E6%97%A5%E6%9C%AC%E4%BD%8F%E8%A1%80%E5%90%B8%E8%99%AB%E7%97%87)
```

　上記の部分も気になったので引用をしておきました。「加賀国大聖寺藩（現：石川県加賀市）出身」とありますが、ここでも思い出したのは山中温泉出身と聞く辻正信のことです。岡山医学専門学校は、これも加計学園理事長の記者会見のことで、昨日か一昨日に取り上げたところかと思います。

　１つ上のレベルの見出しには「日本住血吸虫の発見」とありますが、なにぶんページの情報量が多すぎて、とても読み切れないのが残念です。前にも読んだことのあるWikipediaですが、全部に目を通したとは考えにくく、どこまで読んだのかも憶えがありません。

　時刻は16時25分ですが、外がだいぶん薄暗くなってきました。

▶（25／28） TW kmuramatsu（ʇɐ） 日時： 2019-12-02 22:09:00 +0900 URL： https://twitter.com/kmuramatsu/status/1201488505941061632
{% tweet 1201488505941061632 %}
> ミナミ通り魔　最高裁二審支持「無期懲役」 https://t.co/6VG3DX8dNk

▶（09／28） RT emeth_pippi（当職ぴっぴにゃん）｜YahooNewsTopics（Yahoo!ニュース） 日時：2019-12-02 15:50:00 +0900／2019-12-02 12:28:00 +0900 URL： https://twitter.com/emeth_pippi/status/1201393210620178433 https://twitter.com/YahooNewsTopics/status/1201342290448371713
{% tweet 1201393210620178433 %}
> 【06年川崎通り魔 無期懲役求刑】 \n https://t.co/cIHp9UsKw1 \n \n 川崎市のトンネルで2006年、面識がない女性を殺害したとして殺人罪に問われた被告の裁判員裁判が横浜地裁であり、検察側は無期懲役を求刑した。被告は… https://t.co/jRkzrqWQFa

　いったん下まで目を通して、上に遡りながら確認しましたが、川崎市の通り魔事件無期懲役求刑をツイート（リツイート）した弁護士アカウントは上記の1件だけのようです。プロフィールの名前が最近になって少し変わったように思います。

sakamotomasayuk ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW sakamotomasayuk（坂本正幸） 日時：2019/12/02 11:48 URL： https://twitter.com/sakamotomasayuk/status/1201332224534007811
> 対国家の権限として人権が発展してきたことは自明の論理 \n 課税権が問題となりそこから生まれてきている \n 人権の基本はきちんと歴史に学ぶことが必要である \n 人権の敵というよりも暴走させてはならないのが権力 \n 対国家性だけで敵というのが短絡的 https://t.co/qE1OFWBbbk
▷▷▷　　　　　End　　　　　▷▷▷

　当職ぴっぴにゃん、というアカウントについて気になり、タイムラインを遡っていると、リツイートとして上記の坂本正幸弁護士のツイートを見つけました。次の元警察官のアカウントのツイートを公式引用していますが、法クラの批判が目立つアカウントでもあります。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜supergundam0310（宇野博幸） 日時：2019-12-03 16:50／2019/12/02 07:56 URL： https://twitter.com/kk_hirono/status/1201770748911603712 https://twitter.com/supergundam0310/status/1201273871648772096
> サンモニで法学部教授が人権に対するものは国家権力だと(人権 対 国家権力)と書いて説明。最大の人権たる命を奪うのは殺人犯。殺人を予防し逮捕してるのは警察。警察は最大の人権を守っているのに国家権力だから人権の敵だと決めつけ、感謝のか… https://t.co/uEh3wT6IoV
▶▶▶　　　　　End　　　　　▶▶▶

　ピッピーというようなプロフィールの名前のアカウントが別にいて、そのプロフィールの名前に変更があったのかと思っていたのですが、別のアカウントの可能性が高いと思えてきました。プロフィールの内容も見覚えのないものと気が付きました。

```
最近、相撲が好きやねん。2020年の大阪場所も行くねん。大阪で弁護士と司法書士。行政書士資格も保有。刑事弁護、相続、債務整理、離婚や不貞などを中心に。不動産決済を中心に司法書士もボチボチやってます。以上は世を忍ぶ仮の姿で、本当はアメ村のマーメイドです。
2015年5月からTwitterを利用しています
800 フォロー中
986 フォロワー

［source：］当職ぴっぴにゃん（@emeth_pippi）さん / Twitter https://twitter.com/emeth_pippi
```

　ちょっと匿名弁護士とは思えないほどプロフィールに具体性があります。データベースを調べたところ過去にはプロフィールの名前を「しろぴっぴハンパないって」としていた時期もありました。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜O59K2dPQH59QEJx（ピピピーッ） 日時：2019-12-03 17:01／2019/12/01 15:48 URL： https://twitter.com/kk_hirono/status/1201773451888873473 https://twitter.com/O59K2dPQH59QEJx/status/1201030267214761985
> ワイは着手金もらわないで動くことはないかな。 賛否はあると思うが。 https://t.co/Z7zBStUeFj
▶▶▶　　　　　End　　　　　▶▶▶

　やはり上記の「ピピピーッ」というプロフィールの名前のアカウントと混同していたようです。警察官が吹く警笛の音をイメージさせるアカウントですが、「ぴっぴ」は、精液の迸りを表現しているようで、「しろぴっぴハンパないって」というのは、弁護士とプロフィールにある組み合わせとして疑問です。

```
             id: 255501
           name: しろぴっぴ@グローバル化に適応
        rt_name: 烏丸蒼一@金曜メ-43b 艦CORE小説
         tw_url: https://twitter.com/emeth_pippi/status/962207655015063554
         rt_url: https://twitter.com/KarasumaS1/status/958988600011456512
        tw_date: 2018-02-10 15:12:00
        rt_date: 2018-02-01 18:01:00
          tweet: RT @KarasumaS1: 人間には三種類の休日が要る。
・用事を片付ける休み
・遊ぶ休み
・休む休み
つまり週休3日こそが健康で文化的な最低限度の生活。
      org_tweet: 人間には三種類の休日が要る。
・用事を片付ける休み
・遊ぶ休み
・休む休み
つまり週休3日こそが健康で文化的な最低限度の生活。
        retweet: 1
           user: emeth_pippi
 statuses_count: 17702
        rt_user: KarasumaS1
    create_time: 2018-07-16 01:53:58
        profile: 大阪で弁護士と司法書士をしています。刑事事件、債務整理、離婚、相続、不動産、顧問業務を中心に。たまにROCKなDJ。ラグビーとボクシングが好き。ラブライバー。アメ村筋トレ部/大人の天満会/イエローカズタロウズ/#しろぴっぴのミッテラ会館50周年全店飲み尽くしの旅
            app: Twitter for iPhone
       location: 
followers_count: 646
  friends_count: 458
       rt_count: 53374
      fav_count: 0
            tag: nil
```

　リツイートとしてデータベースにデータがあったのですが、なぜ登録したのかよくわからない内容のツイートです。プロフィールの内容に見覚えがないのも不思議ですが、今日になってこんなかたちでの発見となったところです。

　上記のデータベースのデータの引用は、プロフィールの内容も、2018年7月16日の時点でのものになります。APIでのツイートのデータの取得と一緒に、アカウントの情報も取得していますが、もともとツイートの情報とアカウントの情報は一体で同時に取得されるものです。

　プロフィールに大阪の弁護士とありますが、心斎橋の通り魔事件というのも大阪市内の事件で、刑事裁判も大阪地裁、大阪高裁の可能性が高く、最高裁の弁護人も大阪府北区西天満の弁護士だと本日知ることになりました。

　無期懲役をキーワードに含むツイートの記録が「20／28件」というのは少なく感じますが、最高裁の判決があった昨日の、19時のNHKニュースでも見ておらず、今日はテレビをつけていない時間も多かったですが報道を見ていません。8時から9時半ぐらいはあちこちチャンネル変更していました。

〈〈〈：Emacs： 2019-12-03（火曜日）17：22 　〈〈〈

