#+TITLE: "弁護士将来危険也としか考えようのない深澤諭史弁護士の弁護士業界での活躍という現実"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-11-20 21:28:44 +0900
FILE_NAME: 2019-11-20-212844_弁護士将来危険也としか考えようのない深澤諭史弁護士の弁護士業界での活躍という現実.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 深澤諭史弁護士,
記事タイトル名の文字数：40　保存ファイル名の文字数：62
#+STARTUP: showeverything


* 輪島前神社と天満宮、宇出津の小棚木、音羽町の蘇家宮：弁護士将来危険也としか考えようのない深澤諭史弁護士の弁護士業界での活躍という現世の現実
  CLOCK: [2019-11-20 水 21:32]--[2019-11-20 水 23:43] =>  2:11

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 深澤諭史弁護士

〉〉〉：Emacs： 2019-11-20（水曜日）21：32　 〉〉〉

　個人的に、魂を震わす狂人弁護士、爆走弁護士野郎「欲望一直線」としか考えようのない深澤諭史弁護士ですが、本日、今夜はさらにその思いを強め、ここに記録のエントリとして奉納することに致しました。特定した案件で奉納するとしたのは今回が初めてのはずです。

　私つまり廣野秀樹は、自由に奔放な人生を歩んできたという幾分の負い目も含めた思いもあって、個人の思想・信条は最大限尊重する主義でいるつもりです。しかしながら、この深澤諭史弁護士のTwitterの発言を巡っては、かねてより魂を震わす、憤りと蘇民将来の危機感を抱き続けてきました。

　「蘇我宮」ではなく「蘇家宮」だったので、エントリーのタイトルを修正しました。この深澤諭史弁護士のような凄まじき大馬鹿者が東京大学法科大学院から解き放たれたことには、その製造物責任を含め、関係は知りませんが、東京大学の壊滅、厄災除去を含めた歴史的一大事という認識です。

　2015年前に、石川県輪島市と神奈川県横浜市を舞台としたNHK連続テレビ小説まれ、の放送があって、その後2回、輪島大祭の輪島前神社大祭を見物に行ったのですが、2回目のときキリコの「天満宮」のことが気になって、帰ってからネットでいろいろと調べたということがありました。

　このNHK連続テレビ小説まれ、の個人的な思い入れですが、主人公の稀の家族が東京から輪島市に移住してきたというバス停近くの場面があって、輪島市内とは離れた旧鳳至郡門前町の猿山岬近くの風景だと思ったのですが、話を聞いていた昭和初期の母親の京都からの移住のことに思いを馳せました。

　少なくとも平成に入ってから初めてのことで、全く見覚えのない連続テレビ小説のタイトルも多いのですが、東京都渋谷区桜丘の櫻井光政弁護士のツイートがきっかけで、ずいぶん話題となっていたことは知っていて、連続テレビ小説あまちゃん、の視聴を開始しました。

　そのあと「ごちそうさん」というNHK連続テレビ小説があって、見逃したのは結婚の申し入れの回だけで、小木港西堤防のアジ釣りでワンセグでの視聴に失敗した時だけだったのですが、大阪の実家の場面で照明の具合から、同じ時代の京都市での先祖に思いを馳せたということも大きいです。

　物心がついてから振り返る母親の人生は、まさに「弁護士鉄道」によって悲惨なものになりましたが、これを奉納として家内安全、子孫繁栄に資することが、自分と被害者家族に与えられた理不尽な人生の担ぎ荷ではないかと考えるとともに、神仏の憤怒の怒りというものを強く意識するようになりました。

　輪島大祭を見物に行ったのも連続テレビ小説まれ、の放送がきっかけで、同じ能登のキリコ祭りになりますが、お祭りの見物に行こうと考えたことは、それまで一度もありませんでした。キリコには奥津宮、重蔵宮、住吉宮、天満宮とありましたが、宇出津のキリコには見かけないものなので気になりました。

　また、輪島大祭のキリコの練習風景を石川県内のローカル番組でみたのですが、そのときに輪島大祭の太鼓は、町の邪気を追い払うためのものだと知って、宇出津のあばれ祭りの起源や由来についても関心を持つようになり、それと同じことで祭礼委員となったことで、資料に触れる機会もありました。

　弁護士の厄神性、疫病神については、モトケンこと矢部善朗弁護士（京都弁護士会）、小倉秀夫弁護士、深澤諭史弁護士の三人だけでも弁護士業界を吹き飛ばし破滅させるだけの凄まじいパワーを感じてきましたが、同じ弁護士業界の内部が余りに無頓着なのが、気になっていました。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-20 22:20／2017/01/12 20:43 URL： https://twitter.com/kk_hirono/status/1197142615650471936 https://twitter.com/hirono_hideki/status/819510034849677317
> 2017年01月12日00時03分54秒の記録＿”蘇家宮”のGoogle検索 https://t.co/cm6vmfz3U3
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-20 22:20／2017/01/12 00:14 URL： https://twitter.com/kk_hirono/status/1197142588626616320 https://twitter.com/hirono_hideki/status/819200858055393281
> 蘇家宮 - Google Search https://t.co/x2dJpC3CIi
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-20 22:19／2016/07/27 13:32 URL： https://twitter.com/kk_hirono/status/1197142531240161280 https://twitter.com/hirono_hideki/status/758157970609954821
> 蘇家宮 https://t.co/c20xMn3y0F
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「蘇家宮」の検索結果 - Twilog https://t.co/q2XSXnzEmq

　意外なことに奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)のTwilogで、「蘇家宮」をワードに含むツイートは3件のみでした。厳密に言えば、宇出津の小棚木と音羽町のキリコのナカフクにある蘇家宮の、最初の文字は旧字体なのか文字が違っています。

　奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)のTwilogでの「蘇家宮」の初出は、意外なことに2016年7月26日となっていて、宇出津のあばれ祭りとは違って、曜日ではない日が固定されている8月25日の輪島大祭、輪島前神社大祭とは、時期が違っていました。

　個人的に「うちてしやまぬ」という思いにも駆られる深澤諭史弁護士のツイート、タイムラインになりますが、信心が乏しいと自覚する私こと廣野秀樹でも、先祖と歴史を愚弄し、誠に凄まじき大馬鹿野郎、世紀の歴史的大発見とみているのが、深澤諭史弁護士になります。

　深澤諭史弁護士は、自身に不都合あるいは不利益と感じるネット上の反応について、単純に中傷などと決めつけておりますが、これも弁護士業界の消費者被害として、深刻重大なものを感じており、まさに弁護士脳の社会汚染としての公害であると捉えております。弁護士一代深澤稼業です。

[link:] » 蘇家宮 - Google 検索 https://t.co/Q9tRVsT1yi

[link:] » 蘇家宮　宇出津 - Google 検索 https://t.co/PBIoh0sIyB

　「蘇家宮　宇出津」でのGoogleの検索結果はわずかに9件のみでした。

　深澤諭史弁護士の発想、思考について、ある種の病気「弁護士病」としか個人的に考えようのないのは、何度か取り上げてきたと思いますが、盲腸をキーワードに含むツイートにもあります。

[link:] 2019年11月20日22時39分の登録： REGEXP：”中傷”／深澤諭史（@fukazawas）の検索（2013-06-22〜2019-11-16／2019年11月20日22時39分の記録98件） http://hirono2014sk.blogspot.com/2019/11/regexpfukazawas2013-06-222019-11.html

　上記は作成したての深澤諭史弁護士のツイートのまとめ記事になります。

▶（01／98） TW fukazawas（深澤諭史） 日時：2013-06-22 22:58:00 +0900 URL： https://twitter.com/fukazawas/status/348439893074124801
{% tweet 348439893074124801 %}
> 非弁活動について、縄張り争い云々と中傷する者がいるが、全く的外れである。 \n 非弁業者の実態を少しでも見れば、到底看過できないと思うはず。

▶（02／98） TW fukazawas（深澤諭史） 日時：2013-09-12 10:31:00 +0900 URL： https://twitter.com/fukazawas/status/377967609334870016
{% tweet 377967609334870016 %}
> ふと思ったけれども，当番弁護って，３６５日対応でしたよね…。 \n 身内を讃えるのもなんですけど，一部マスコミや一部学者に既得権とか何とか，無知無理解に基づく中傷をされながらも，頑張って対応を続ける弁護士会と担当弁護士はもっと評価されてもよい。

　パソコンで機械的に収集、データベースに記録したツイートのデータになりますが、初っ端の2件のツイートをみただけでも、偏狭、偏執としての弁護士業界の賛美、礼賛を深澤諭史弁護士の弁護士脳に感じます。宗教的な物狂いと感じることもある深澤諭史弁護士のツイートの数々です。

▶（97／98） TW fukazawas（深澤諭史） 日時：2019-10-14 18:55:00 +0900 URL： https://twitter.com/fukazawas/status/1183682667948072967
{% tweet 1183682667948072967 %}
> （；；・∀・）いやー，ほんと，あのときのローの先生方の言動は酷かったです。 \n （；；＾ω＾）もっというと，法学部の学生すら中傷されていた気がするお・・・。 https://t.co/XHhRQt4QiF

▶（96／98） TW fukazawas（深澤諭史） 日時：2019-10-14 18:46:00 +0900 URL： https://twitter.com/fukazawas/status/1183680484863139840
{% tweet 1183680484863139840 %}
> （・∀・）あのときのはしゃぎっぷり，予備校，既存法曹や受験生への根拠ない中傷，その後の失敗と，「はだしのゲンの町内会長」の大量発生，永久に語り継ぐべきですね。 https://t.co/jnWY2upriU

▶（95／98） TW fukazawas（深澤諭史） 日時：2019-08-31 12:42:00 +0900 URL： https://twitter.com/fukazawas/status/1167643742754394112
{% tweet 1167643742754394112 %}
> クレーマーにネットに書かれる？中傷される？ \n 確かにそれはリスクだが，従うリスクに比べれば無視できる規模である。 #クレーマーへの心得

　深澤諭史弁護士に関する認知、理解の極めつけは、次のブログ記事が１つになりますが、まだ正式な歴史的資料の記録には至っていないことを付言しておきます。

```
接見室から逃亡した事件が話題になっています。いつもの話ですが，ネット上では，勘違いから弁護人を非難する言説があるようです。そこで，誤解の解消のため，簡単に解説をしたいと思います。

［source：］接見室の構造と逃亡事件 ： 弁護士 深澤諭史のブログ http://xn--zqs94lv37b.club/archives/11404508.html
```

　他にも関連したブログ記事が深澤諭史弁護士にはあったようにも思いますが、とりあえず、上記の深澤諭史弁護士のブログ記事をGoogleの検索から発掘したことをご報告としておきたいと思います。繰り返すと思いますが、弁護士脳の社会汚染について、歴史的に貴重な資料の一つです。

　この富田林警察署の逃走事件は、接見した弁護士名が検索で見つけ出すことも出来なかったですが、警察官に1時間半とかで見込みを伝えた8月12日の接見が、被疑者の申し出で30分で終了しながら、警察署に報告せずに立ち去ったというにわかに信じがたいほどの非常識と、欠如が大前提にあります。

　警察署における留置場や接見室の構造については、金沢西警察署と金沢中警察署で体験がありますが、とりわけ夜間帯は警察署の窓口を通過したところに接見室があるはずで、窓口に警察官が不在であったとは考え難く、声掛けをいなかった弁護士の異常性が際立ち、問題視しなかった業界も連帯で同じです。

　「押忍！番長」というパチスロ機では、平成19年辺りに、不良と思しき少女との卓球対決という演出があって、その少女の声として、「見切ったよ」というのが強く印象に残っています。見極めという漢字に近かったかもしれません。そこへの到達点も深澤諭史弁護士にありました。

　腐りきった汚物とも思える深澤諭史弁護士ですが、それと同時に欲望への純真さと、そこに到達するまでの登竜門を感じることがあります。自傷他害は、小倉秀夫弁護士の評価として表現を用いたことがあったと思いますが、まさに社会問題の体現として深刻重大なものを日々に感じ、記録をしています。

　時に、神様が社会的な問題性を問い掛ける使者とも考えることのある深澤諭史弁護士のツイート及びリツイートを含むTwitterタイムラインですが、深澤諭史弁護士自身も最近、神が舞い降りたという意味のツイートがあったことを思い出しました。

　時刻は23時19分になります。テレビのチャンネルはNHKのまま歴史秘話ヒストリアが終わったところですが、いつの間にか遅い時間になっていて、ちょっと驚きました。明日は予定もあるので、早めに寝ることを考えていました。夕食もつまみ食い程度で、まだ中途半端です。

　挑発をしてでもブロックを解除させ、弁護士業界の現実につき向き合った意見を聞きたいとも希求するのがTwitterの深澤諭史弁護士のアカウントですが、Twilogの登録もないので、垂れ流しの流し網漁とも考えるのが、深澤諭史弁護士と三浦義隆弁護士に代表されるTwitterの利用です。

　文字通り取り返しのつかない不利益で人生を狂わされたと考え、告発をするのが弁護士鉄道の歩み、沿革になります。その代表者の一人が深澤諭史弁護士になりまして、極めて貴重な歴史的資料ともなっております。徹底した記録保存も日々の日課となっています。

　時刻は23時28分になります。変更を考えながらテレビのチャンネルをNHKのままにしていたことに気がついたのですが、組み体操のニュースがあって、「人間起こし」とかありました。この組体操の問題については、深澤諭史弁護士のツイートとしても魂を震わすものを見ております。

　「人間起こし」というのは初めて目にしましたが、輪島市の輪島前神社、恵比須講のニュースとともに、起舟祭、帆柱起こし音頭のことを思い出しました。トラック野郎という昭和の映画に、トラック音頭という曲がありましたが、深澤諭史弁護士のタイムラインは、弁護士音頭という狂奔を感じます。

　映画「トラック野郎」の「トラック音頭」には、「春夏秋冬夢枕、粋な稼業がやめらりょか」という歌詞があったと思います。それも深澤諭史弁護士の弁護士という資格に対する異常な思い入れと重なるもので、まさに「弁護士野郎　欲望一直線」です。

　深澤諭史弁護士の弁護士としての異常性については、かなり前からツイートでも指摘をしてきたと思いますし、「弁護士狂人深澤モード」というのも記憶にあるところです。最近は、その深澤諭史弁護士よりも、それに無頓着で問題視をしていない同業の弁護士らに、より強い問題性を感じています。

〈〈〈：Emacs： 2019-11-20（水曜日）23：43 　〈〈〈

