#+TITLE: "深澤諭史弁護士の日弁連（日本弁護士連合会）に関するツイート"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-11-06 10:54:37 +0900
FILE_NAME: 2019-11-06-105437_深澤諭史弁護士の日弁連（日本弁護士連合会）に関するツイート.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 深澤諭史弁護士,日弁連
記事タイトル名の文字数：29　保存ファイル名の文字数：51
#+STARTUP: showeverything


* 日弁連の偉い先生は，その「良い弁護士」にどんな苦情が弁護士会に来ているか，ある程度把握しているはずなのに。：深澤諭史弁護士の日弁連（日本弁護士連合会）に関するツイート
  CLOCK: [2019-11-06 水 10:58]--[2019-11-06 水 12:13] =>  1:15

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 深澤諭史弁護士,日弁連

〉〉〉：Emacs： 2019-11-06（水曜日）10：58　 〉〉〉

fukazawas ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW fukazawas（深澤諭史） 日時：2019/11/06 10:16 URL： https://twitter.com/fukazawas/status/1191887057678790656
> 日弁連の偉い先生は，その「良い弁護士」にどんな苦情が弁護士会に来ているか，ある程度把握しているはずなのに。 \n ほんと，（中略）とか，酷いもんですよ。羊頭狗肉ってレベルでないです。 https://t.co/j4Atk6VIMl
▷▷▷　　　　　End　　　　　▷▷▷

[link:] 2019年11月06日10時50分の登録： ＼深澤諭史　@fukazawas＼日弁連の偉い先生は，その「良い弁護士」にどんな苦情が弁護士会に来ているか，ある程度把握しているはずなのに。\nほんと，（中略）とか，酷いも http://hirono2014sk.blogspot.com/2019/11/fukazawas_33.html

　上記の深澤諭史弁護士のツイートは、このあと取り上げる「ごしべんせんせー」というアカウントのツイートを公式引用しています。プロフィールの名前がころころ変わるアカウントかと把握していますが、初めに見た頃が最も印象的なもので、「弁護士バビロン」などとなっていました。

　このところちょいちょいと見かけるようになった深澤諭史弁護士の同業者（弁護士）批判のツイートですが、日弁連に対して意見のようなことを述べているのに新たな局面に踏み込んだような特徴を感じました。

　深澤諭史弁護士の同業者批判については、「強い」で検索をすれば、網が大きいですが確実に情報が集まるかと思いますので、これからまとめ記事を作成します。

[link:] 2019年11月06日11時14分の登録： REGEXP：”強い”／深澤諭史（@fukazawas）の検索（2013-03-15〜2019-11-04／2019年11月06日11時14分の記録350件） http://hirono2014sk.blogspot.com/2019/11/regexpfukazawas2013-03-152019-11.html

　網を大きくしたため、想定外のものが引っかかってきましたが、上位（古いものから）4件のツイートを見ただけでも、圧倒されるような存在感を感じるとともに、2013年のツイートとなっていますが、2019年現在も日弁連、第二東京弁護士会が深澤諭史弁護士の放置している現実を受け止めました。

▶（001／350） TW fukazawas（深澤諭史） 日時： 2013-03-15 19:24:00 +0900 URL： https://twitter.com/fukazawas/status/312509590958915585
{% tweet 312509590958915585 %}
> 裁判員裁判について，審理期間がないものは除外する方針だけど，死刑求刑や性犯罪は除外しないとのこと。重大事件を考えてもらうためだそうです。 \n となると，裁判員は短期間で人殺しについて人殺しの判断を強いられるわけなのですか…。

▶（002／350） TW fukazawas（深澤諭史） 日時： 2013-04-06 14:37:00 +0900 URL： https://twitter.com/fukazawas/status/320409918840655872
{% tweet 320409918840655872 %}
> 司法制度改革審議会意見書を読むとおもしろいことに気がつきます。いろいろな提案がされていますが，結局，発言力の無い弱者に負担を強いる制度（司法修習貸与制，裁判員等）だけはすんなり導入されていることです。 \n 弱者に光を当てるつもりだったのでしょうが，当てられたのは殺人光線でした。

▶（003／350） TW fukazawas（深澤諭史） 日時： 2013-12-06 23:29:00 +0900 URL： https://twitter.com/fukazawas/status/408966489069219840
{% tweet 408966489069219840 %}
> どんなに権力を背景にしようが，どんなに身柄拘束して苦痛を与えようが，最終的には，何を供述するかを決めるのは被疑者自身。 \n \n 自白だけでなく，どんな供述も強いることではまともなものは得られない。強いるのでなくて仕向けないと。 \n 実力が無いと安易に強いる方向に行きやすいが。

▶（004／350） TW fukazawas（深澤諭史） 日時： 2014-08-06 18:41:00 +0900 URL： https://twitter.com/fukazawas/status/496954097916862466
{% tweet 496954097916862466 %}
> 人物がおかしいとか，そういうことで心証がとられると仮定すると，法廷では，相手方当事者の悪性を立証し合うという，非常にみっともない，駄目な本人訴訟みたいな訴訟活動を強いられることになりますな。

　深澤諭史弁護士のツイートは、個人的にミステリー性が極めて高く、未知の領域であるとともに、実名顔出しの現職弁護士であるとともに、執筆、講演等でも社会的な活動をされ、さらに非弁を中心に、弁護士会内部の委員会に多数参加し、常議員なるものも務められているようです。

　「強い（つよい）」の検索で「強いられる（しいられる）」が該当してくるというのも意外でしたが、350件のツイートに目を通す暇もなく、深澤諭史弁護士の同業者批判という趣旨に沿ったかたちで検索に絞りを掛け、まとめ記事を作り直したいと思います。

　うまく絞り込みができそうなキーワードを探しながらまとめ記事の深澤諭史弁護士のツイートをみていたのですが、すぐに一つ思わぬ発見がありました。金岡弁護士のブログ記事を紹介したもののようです。着手金3桁ともあります。

　リンクの金岡弁護士の記事は、まだ開いてもいませんが、このあと独立した項目として取り上げておきたいと思います。3日ほど前に見たものも同じでしたが、ツイートの本文に「金岡法律事務所」の文字がなく、その分、記事の引用に文字数を割り当てているようです。

[link:] 2019年11月06日11時32分の登録： REGEXP：”強い．＊弁護士”／深澤諭史（@fukazawas）の検索（2014-11-03〜2019-11-04／2019年11月06日11時32分の記録82件） http://hirono2014sk.blogspot.com/2019/11/regexpfukazawas2014-11-032019-11.html

▶（77／82） TW fukazawas（深澤諭史） 日時：2019-08-30 21:26:00 +0900 URL： https://twitter.com/fukazawas/status/1167413332543860736
{% tweet 1167413332543860736 %}
> 「強い」が自称だけの弁護士を避ける方法 - 弁護士 深澤諭史のブログ https://t.co/GpE1Po9H1a \n ネットの広告によくある話（・∀・）

▶（78／82） TW fukazawas（深澤諭史） 日時：2019-09-22 19:06:00 +0900 URL： https://twitter.com/fukazawas/status/1175712899437776896
{% tweet 1175712899437776896 %}
> ハッタリに強い弁護士（・∀・；） https://t.co/BnwzmDJY9W

▶（79／82） TW fukazawas（深澤諭史） 日時：2019-10-06 16:54:00 +0900 URL： https://twitter.com/fukazawas/status/1180753237785243648
{% tweet 1180753237785243648 %}
> （・∀・）文科省が最近，大学に強いていることって，基本的には，平成の司法改革の時に，一部の法学者の先生方が，法曹特に弁護士にやったことのマイルド版なんですよね。 https://t.co/G9dHXdg1TB

▶（80／82） TW fukazawas（深澤諭史） 日時：2019-11-04 10:04:00 +0900 URL： https://twitter.com/fukazawas/status/1191159346576543746
{% tweet 1191159346576543746 %}
> 弁護士のセルフブランディングの歴史をたどると，「敷居の低い系」から始まり，「○○に強い弁護士」に発展し，最近の流行は，「俺は普通の弁護士でない，弁護士資格なんか不要！普通の弁護士でない俺には普通の弁護士のダメな点がわかる！」系だな。 \n #司法発見伝

▶（81／82） TW fukazawas（深澤諭史） 日時：2019-11-04 10:07:00 +0900 URL： https://twitter.com/fukazawas/status/1191160042264772608
{% tweet 1191160042264772608 %}
> （・∀・）この最近の流行が優れているのは，無条件に特別感や優良性を演出できるのに，ボロが出にくいところなんですよ。 \n （＾ω＾）「刑事弁護に強い」とかいってもすぐにボロが出たり，ぼったくりがばれますが，特別弁護士系は，そうはいかない… https://t.co/DIXOq9wP4g

▶（82／82） TW fukazawas（深澤諭史） 日時：2019-11-04 10:12:00 +0900 URL： https://twitter.com/fukazawas/status/1191161369300615169
{% tweet 1191161369300615169 %}
> 「○○に強い弁護士」などと自称すると，ハリボテなのがばれるリスクがある。一方で「俺は普通の弁護士でない」系は，特殊性は自称すればすぐに作れるし，同じ特殊性はめったにないのでボロがでるリスクも低い。 \n つまり，これは将来性のあるボロい… https://t.co/R6T7hkI3Mt

　このハリボテというのも深澤諭史弁護士のツイートとして、ちょくちょく見かけていますが、見せかけだけで中身がないということなのでしょう。今回見かけた羊頭狗肉という四文字熟語も類似性はありそうな気がします。

```
１ 張り子で、ある形に作ったもの。張り子作りの芝居の小道具など。ぼて。

２ （比喩的に）見かけは立派だが、実質の伴わないことやもの。張り子の虎。「二世議員ばかりで実務経験のない張りぼて内閣」

［source：］張りぼて（はりぼて）の意味 - goo国語辞書 https://dictionary.goo.ne.jp/jn/180206/meaning/m0u/
```

　ハリボテというのも他に余り見かけない言葉と思っていたので調べたところ、漢字では「張りぼて」となるようです。青森のねぶた祭りなどの人形も、この張り子になるのかと考えますが、人形とは書いていないので、どうなのかと少し気になります。

　他に深澤諭史弁護士のツイートでよく見かけるのに「#司法発見伝」というのがあって、ハッシュタグになっていたかと思います。ここで決まって思い出すのが、八犬伝というNHKの人形劇ですが、昭和40年代後半だったと思います。はっきりと記憶にあるのですが、ストーリーは理解しませんでした。

　八犬伝は南総里見八犬伝がベースになっていたと思います。拘置所でも本を一冊読んだことがありました。千葉県の房総半島が歴史的な舞台だと理解していますが、今年はその千葉県に台風や大雨の被害が続きました。あれほど短期間に災害が集中したのも、過去に記憶のないことです。

　あくまで個人的な考えの一つですが、弁護士に対する神仏の怒りが大災害を招いているのではと思いを巡らすこともあります。昨年の9月頃だったと思いますが、台風が来てすぐに家の格子戸が落ちてガラスが割れるということがありました。

　災害の他に災難がありますが、そこでも深刻に考えさせられてきたのが深澤諭史弁護士の「消費者被害」という言葉です。深澤諭史弁護士はそれを非弁に限定し、非弁に利用される弁護士にも慈愛を匂わせながら、その原因を司法制度改革や成仏理論に強く太く結びつけています。

〈〈〈：Emacs： 2019-11-06（水曜日）12：13 　〈〈〈

