#+TITLE: "深澤諭史弁護士の消費者被害と、司法制度改革の市場原理に関するツイート"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-11-06 15:52:26 +0900
FILE_NAME: 2019-11-06-155226_深澤諭史弁護士の消費者被害と、司法制度改革の市場原理に関するツイート.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 深澤諭史弁護士,市場原理,司法制度改革
記事タイトル名の文字数：34　保存ファイル名の文字数：56
#+STARTUP: showeverything


* 「消費者被害」をキーワードにしたツイートのまとめ記事：深澤諭史弁護士の消費者被害と、司法制度改革の市場原理に関するツイート
  CLOCK: [2019-11-06 水 16:44]--[2019-11-06 水 18:34] =>  1:50
 
  CLOCK: [2019-11-06 水 15:54]--[2019-11-06 水 16:42] =>  0:48

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 深澤諭史弁護士,市場原理,司法制度改革

〉〉〉：Emacs： 2019-11-06（水曜日）15：54　 〉〉〉

[link:] 2019年11月06日14時03分の登録： REGEXP：”消費者．＊被害”／深澤諭史（@fukazawas）の検索（2013-07-17〜2019-11-04／2019年11月06日14時03分の記録64件） http://hirono2014sk.blogspot.com/2019/11/regexpfukazawas2013-07-172019-11.html

　このあとに作成した「市場原理」をキーワードにしたまとめ記事ほど、発見や収穫はなかったですが、やはりほとんどが非弁の問題に結び付けられていました。こちらでは消費者被害と司法制度改革を直接結びつけるツイートの確認はなかったかもしれません。見落としがなければです。

▶（04／64） TW fukazawas（深澤諭史） 日時：2014-09-02 21:06:00 +0900 URL： https://twitter.com/fukazawas/status/506775102336167937
{% tweet 506775102336167937 %}
> ＞ＲＴ \n まさに非弁がそれ。 \n マイルールで一般消費者を騙して，マイルールで事件を処理して，相手方も”依頼者”も被害を被る。

　マイルールというのは見かけない言葉ですが、自分の決めたルールということなのでしょう。取っ掛かりが思い出せず、すぐには探し出せないですが、深澤諭史弁護士の依頼者に対する取り決めこそ、ずいぶん独善的で身勝手なものを感じます。弁護士業界全体に通底する潮流でもあります。

　とりあえず、根拠を示しておきたいので不必要に数が多くなりそうですが、「依頼者」をキーワードに深澤諭史弁護士のツイートのまとめ記事を作成したいと思います。すでに作成したものがあるとも思いますが、最新の情報として記録をしておきます。

[link:] 2019年11月06日16時06分の登録： REGEXP：”依頼者”／深澤諭史（@fukazawas）の検索（2012-10-04〜2019-10-16／2019年11月06日16時06分の記録679件） http://hirono2014sk.blogspot.com/2019/11/regexpfukazawas2012-10-042019-10.html

▶（673／679） TW fukazawas（深澤諭史） 日時： 2019-09-16 09:08:00 +0900 URL： https://twitter.com/fukazawas/status/1173388257893044224
{% tweet 1173388257893044224 %}
> エリートサラリーマンは，確かに弁護士の仕事に的外れな注文をつけまくる一方で，医師とか公認会計士とか，専門職の依頼者は，ほぼそういうことしないんですよね。 \n 何も言わなくても事件処理に必要な１００％のことはやってくれるし，何かお願いす… https://t.co/7GbwElMnyQ

　このツイートは見覚えがありますが、「弁護士の仕事に的はずれな注文をつけまくる」とあります。一つや2つではなさそうな表現ですが、的外れということでばっさりと切り捨てているようです。その基準は具体例がないので不明ですが、独自のルールになるものと思います。

▶（667／679） TW fukazawas（深澤諭史） 日時： 2019-07-11 13:49:00 +0900 URL： https://twitter.com/fukazawas/status/1149178863190073344
{% tweet 1149178863190073344 %}
> 依頼者を燃やして、その熱で暖を取るようなことは、弁護士としては避けるべきであろう。 \n （・∀・；）

　今日のテレビのバイキングで、拡散で辞職になった市議のことを取り上げていましたが、100万円の損害賠償の請求からこじれたようです。今回は被害者側の弁護士のコメントを見なかったですが、集中してテレビを見ていなかったので見落としもあるかもしれません。

　前は、実名顔出しで代理人とかいう弁護士がテレビに出ていたように思いますが、弁護士名は記憶になく調べてもいないように思います。だいぶん前の問題になりつつありますが、今回バイキングが番組で取り上げたのも、弁護士による売り込みや情報提供、根回しの所産なのかそ想像しました。

　同じバイキングで、すっかり姿を見かけなくなったのは佐藤大和弁護士ですが、ネットでも情報は見かけなくなっています。和歌山の不審死事件で、疑いのかかった女性の弁護活動のようなことも行っていたようですが、その件に関する情報も見かけないので、委任関係が続いているのかも不明です。

〈〈〈：Emacs： 2019-11-06（水曜日）16：42 　〈〈〈

〉〉〉：Emacs： 2019-11-06（水曜日）16：44　 〉〉〉

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜viking_fujitv（【フジテレビ公式】バイキング） 日時：2019-11-06 16:23／2019/11/06 12:14 URL： https://twitter.com/kk_hirono/status/1191979393603772417 https://twitter.com/viking_fujitv/status/1191916803003305984
> 　本日11月6日(水)の放送は？　 　マラソン・競歩“札幌開催”で日本陸連が会見！マラソン瀬古利彦氏は「頭の中が切り替えられない」「IOCの力の前ではどうにも…」決定に怒りとあきらめ…　常磐道あおり運転“デマ拡散”で辞職市議が会見…その主張とは！？ 　ただいま放送中です　
▶▶▶　　　　　End　　　　　▶▶▶

　「常磐道あおり運転“デマ拡散”で辞職市議が会見」というコーナーでしたが、この問題に関しても法クラの反応というのをほとんどみていません。深澤諭史弁護士もこの問題は触れていないと思います。

　もっと気になったのが、一昨日になるでしょうか、群馬県高崎市の商業高校の体罰動画の拡散問題で、その日だけテレビで取り上げるのをいくつか見ていました。テレビの報道の時点で、動画が拡散されたのは、放送の前日の取材の時点で2週間前となっていたように思います。

　その報道をテレビで見た前日だったと思うのですが、深澤諭史弁護士のツイートで拡散に関するブログ記事の紹介がありました。だいぶん前の記事だったと思いますが、自分のツイートのリツイートの繰り返しや、古いブログ記事のツイートは、深澤諭史弁護士のツイートでよくみるものです。

[link:] 2019年11月06日16時54分の登録： REGEXP：”拡散”／深澤諭史（@fukazawas）の検索（2015-05-04〜2019-11-03／2019年11月06日16時54分の記録163件） http://hirono2014sk.blogspot.com/2019/11/regexpfukazawas2015-05-042019-11.html

　まとめ記事を作成しました。タイトル名を見ただけでわかりますが、3日前の11月3日が深澤諭史弁護士の「拡散」をキーワードに含むツイートの最新となっています。深澤諭史弁護士のツイートは全件をデータベースに登録しており、昼頃にも更新処理を行いました。

▶（163／163） TW fukazawas（深澤諭史） 日時：2019-11-03 12:11:00 +0900 URL： https://twitter.com/fukazawas/status/1190828838252498944
{% tweet 1190828838252498944 %}
> 「拡散希望」と反社会的な紛争解決手段の問題 : 弁護士 深澤諭史のブログ https://t.co/gvkZqUMFVo \n \n これは経験上の問題ですけれども，通常，紛争が生じた場合に「拡散希望」などと言っているケースでは，そういうこ… https://t.co/MCA0I0DopC

```
2019年11月03日

「拡散希望」と反社会的な紛争解決手段の問題
このテーマの記事は，これで４つ目ですが最近，まだまだよく目にしますので，言及することにします。

これは今回に限らず何度も言っていることですが，とにかく紛争が生じたときに，その紛争解決，それも自分に有利な形で解決するために，「拡散希望」だのといって広めようとすることは，基本的には百害あって一利なし，です。仮にするのであれば，専門家の慎重な助言が必須です。安易にやっていいことでは絶対にありません。 

まず最初に，紛争が生じたということ自体，基本的にプライバシーに属するということを忘れてはなりません。

［source：］「拡散希望」と反社会的な紛争解決手段の問題 ： 弁護士 深澤諭史のブログ http://xn--zqs94lv37b.club/archives/20031031.html
```

　深澤諭史弁護士のツイートによくある古いブログ記事の再掲かと思っていたのですが、確認すると記事の投稿日が11月3日となっていました。設定であえてそうしてあるのか日時の情報はなく、年月日のみです。

　深澤諭史弁護士がこの記事で述べているのは、紛争の解決を有利にするための拡散のようです。高崎市の商業高校の問題は、テレビで、なんとなくの撮影投稿と解説がされていました。

　なにより驚いたのは、テレビの動画再生の場面では気が付かず、問題にもされていなかったと思うのですが、Twitterで添付された動画を見ると、授業中なのに女子生徒が2人手前に写り込んでいて、一人が机に尻をのせて後ろ向きに座り、もう一人が横向きで椅子の上に胡座をかいていました。

　Twitterの検索でも、そちらの女子生徒の行動をより問題視する声が多かったですが、キーワードの検索をやめると全く情報を見かけなくなりました。法クラのツイートでも全く見ていません。モトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインでも相変わらずは、宇崎ちゃんです。

　そういえば、今日の午前中はTwitterのトレンドで、「森友文書」をみましたが、テレビでの報道は一切見ておらず、法クラのツイートとしても今のところは見ていません。

fukazawas ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW fukazawas（深澤諭史） 日時：2019/11/06 16:28 URL： https://twitter.com/fukazawas/status/1191980699177422848
> 偉大なる我らが宰相をはじめとする日本が好きな普通の日本人は，この芸術展のせいで，どれだけ日本の評判が落ちるか心配されているかもしれないが， \n 少なくとも，この芸術展１００回分より公認撤回１回の方が確実に評判が落ちるのは間違いない（・… https://t.co/fqErovzaAn
▷▷▷　　　　　End　　　　　▷▷▷

fukazawas ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW fukazawas（深澤諭史） 日時：2019/11/06 16:26 URL： https://twitter.com/fukazawas/status/1191980054814842880
> ウィーン市民、けげんな声　芸術展の日本公認撤回 | 2019/11/6 - 共同通信 https://t.co/XJsFadOq19 \n  \n 「ウィーン市民からは5日「正々堂々とした行為とは思えない」などと、不寛容さにけげんな声が上がっ… https://t.co/sYlKpUWSfP
▷▷▷　　　　　End　　　　　▷▷▷

　上記の深澤諭史弁護士のツイートは、深澤諭史弁護士のタイムラインで、それぞれ45分前、48分前として表示されています。テレビは15時30分ぐらいに消してからつけていませんが、その前に「公認撤回」をトレンドでみかけ、簡単な内容は早くしています。テレビでは見ていません。

　どうもこの手のツイートは、深澤諭史弁護士の食いつきがすこぶるよいようです。旗幟も鮮明となっています。

　深澤諭史弁護士のタイムラインを遡りながら見ていると、トレンドに「田代まさし」とあって、26,357と数は少なめなのですが、下に「国内　田代まさし容疑者を逮捕　覚せい剤取締法違反の疑い」とあるので驚きました。再犯を繰り返していたかと思いますが、かなり長く摘発はなかったかずです。

　覚せい剤といえば、東京の警察署の留置場から出てきた清原容疑者を、弁護士らが車に乗せて、ラクビーボールのようにマスコミを尻目に走り去った場面がなにより印象的で、翌日辺りには病院前で、高級焼肉弁当を振る舞ったこともテレビで話題となっていました。御神体のようなお祭り騒ぎでした。

　その清原和博元選手が、ようやく野球で社会復帰を果たせたという内容のニュースがあったのもつい先日のことでした。今日はバイキングからグッディへの引き継ぎでも、速報扱いでスノボの元日本代表選手が大麻で逮捕されたと報道をしていたばかりのことです。

　そのスノボの元日本代表選手の場合は、麻薬を取り締まるところに呼び出しで出頭したところでの逮捕だという報道でした。著名人を呼び出した上での逮捕というのは、これまで聞いたことがなかったと思いますが、段取り通りでの逮捕と報道であったと考えられます。

　さらに、その上での田代まさし、の逮捕なので、安倍政権が不利な情報をごまかすために、マスコミを利用したという声も聞こえてきそうです。

　テレビをつけると、何事もなかったように「便秘に悩む女性に・・・人気　”腸活トレーニング”とは？」という特集をやっています。腸活というのは初めて目にしましたが、Linuxのmozcで一発で変換できました。

　「みそ玉」というのも初めて見聞きしました。17時47分で全国ニュースが再開したようですが、見出しをみたところ、田代まさし、の逮捕は、5つの4つ目ぐらいになっていて、大きな扱いではないという印象です。繰り返した再犯から今回の逮捕までの期間が長いだけに社会の影響は大きな気がします。

　テレビでニュースがありましたが、東京都内で宮城県警に現行犯逮捕されたとのことでした。前に宮城県内で所持か使用をしていたとか、その容疑でも逮捕したとか解説があったので、挙動不審で職務質問を受けての逮捕とは違いがあるようです。塩釜警察署もテレビに出ていました。

　田代まさし、の薬物での逮捕は今回で3回目という解説で、思っていたより少なく感じましたが、前回が2010年でコカインでの逮捕ということで、見覚えのある逮捕時の映像が流れていました。

　時刻は18時33分です。これから久しぶりにカレーライスを作る予定です。材料は昨日、どんたく宇出津店で買ってきました。

〈〈〈：Emacs： 2019-11-06（水曜日）18：34 　〈〈〈



