#+TITLE: "「悪態ついてくる依頼者にも善管注意義務を満たす対応をしなければならない。」というリツイート"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-10-10 10:17:11 +0900
FILE_NAME: 2019-10-10-101711_「悪態ついてくる依頼者にも善管注意義務を満たす対応をしなければならない。」というリツイート.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 深澤諭史弁護士,深澤諭史弁護士のリツイート,ピピピーッ
記事タイトル名の文字数：45　保存ファイル名の文字数：67
#+STARTUP: showeverything


* 「悪態ついてくる依頼者にも善管注意義務を満たす対応をしなければならない。」というピピピーッのツイート、深澤諭史弁護士のリツイート
  CLOCK: [2019-10-10 木 10:20]--[2019-10-10 木 11:06] =>  0:46

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 深澤諭史弁護士,深澤諭史弁護士のリツイート,ピピピーッ

〉〉〉：Emacs： 2019-10-10（木曜日）10：20　 〉〉〉

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-10-10 10:34／2019/10/10 10:24 URL： https://twitter.com/kk_hirono/status/1182107043504644096 https://twitter.com/s_hirono/status/1182104631112941568
> 2019-10-10-073757_深澤諭史さんがリツイートピピピーッ@O59K2dPQH59QEJx·16hいつも丁寧に対応していただける依頼者のためには頑張り過ぎちゃうけど、いつも悪態つ.jpg https://t.co/1bwnQfer0R
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-10 10:36／2019/10/10 09:12 URL： https://twitter.com/kk_hirono/status/1182107499731636224 https://twitter.com/hirono_hideki/status/1182086380127522817
> 2019年10月10日07時37分の登録： ＼ピピピーッ　@O59K2dPQH59QEJx＼いつも丁寧に対応していただける依頼者のためには頑張り過ぎちゃうけど、いつも悪態ついてくる依頼者にも善管注意義務を満たす対応 https://t.co/V3SSMOPtZJ
▶▶▶　　　　　End　　　　　▶▶▶

　本日は、このピピピーッというアカウントのツイートに多くの発見があるのですが、もともと注目するツイートの多いアカウントで、その多くも深澤諭史弁護士のタイムラインで深澤諭史弁護士のリツイートとして見てきたように思います。

```
ピピピーッ
@O59K2dPQH59QEJx
2016年9月からTwitterを利用しています
76 フォロー中
3,471 フォロワー

［source：］ピピピーッ（@O59K2dPQH59QEJx）さん / Twitter https://twitter.com/O59K2dPQH59QEJx
```

　改めてプロフィールをみても記載はありません。２０１６年９月からTwitterを利用しているとありますが、これはTwitter社が全てのアカウントに付けている情報かと思います。フォローとフォロワー数も同じです。

　もともと身元を明らかにしていないアカウントは弁護士の可能性が高くても重視していなかったのですが、あらためて実名弁護士の深澤諭史弁護士がリツイートをしていることで、賛同型、共有型のみなしとして、弁護士業界の実態の資料として取扱をしたいと思います。

　深澤諭史弁護士がリツイートをしたピピピーッのツイートには「善管注意義務」とあります。これは平成８年頃、福井刑務所で受刑中、法律の勉強でよく見かけていた用語で、ちょうど同じ頃にはPL法すなわち製造物責任法の成立、施行というのもあったかと思います。

　弁護士業界の製造物責任という意味では、弁護士としての資質に問題がありそうな弁護士が日弁連（日本弁護士連合会）のことを「総本山」と呼び、自称他称で「法クラ」という言葉が飛び交います。実はこの法クラについても、本日は思いがけない発見がありました。

　「善管注意義務」という法律用語は、法クラの間でもほとんど見かけなかったので、あるいは禁忌される魔除けの御札のようなものの１つかと考えたことがありました。さらに密行性が際立って高いと考えるのが「判決の既判力」となるのですが、レア度がマックスレベルかと思います。

　この「善管注意義務」というのは特別なものではなく、日常生活で一般的についてまわる法律関係だと思うのですが、より対価が大きく権限も弁護士自治の元、強化されているはずの弁護士の善管注意義務が問題とされた例は見たことがなく、ずっと前から不思議な現象だと思っていました。

　このあと現実の弁護士業界の実態として、刑裁サイ太のクレオをご紹介したいと思います。そんな名前のビスケットのお菓子があったような気もするのですが、クレオというのは法クラが総本山と呼ぶ、日弁連（日本弁護士連合会）の建物の名称らしいです。

　ずいぶん長く調べてもいないので、私自身の記憶や知識をチェック、確認する意味でも「善管注意義務」について調べておきたいと思います。私の理解では基準は２つしかなく、もう一つが「自己のためにするのと同一の注意義務」ではなかったかと思います。

　このピピピーッというアカウントのツイートのリツイートは、深澤諭史弁護士の他に向原栄大朗弁護士と高橋雄一郎弁護士のタイムラインで見たように思いますが、思い違いや勘違いがあってもいけないのでスクリーンショットの記録を作成しています。あとで確認とともに取り上げます。

〈〈〈：Emacs： 2019-10-10（木曜日）11：06 　〈〈〈

* 弁護士の「善管注意義務（善良な管理者としての注意義務）」について調べてみる
  CLOCK: [2019-10-10 木 11:10]--[2019-10-10 木 13:00] =>  1:50

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: モトケンこと矢部善朗弁護士（京都弁護士会）,善管注意義務,深澤諭史弁護士

〉〉〉：Emacs： 2019-10-10（木曜日）11：10　 〉〉〉

　まずは先程、モトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインでみたモトケンこと矢部善朗弁護士（京都弁護士会）のツイートをさらりとご紹介しておきたいと思います。善管注意義務→弁護士倫理→弁護士懲戒と関連性もありそうです。

motoken_tw ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW motoken_tw（モトケン） 日時：2019/10/10 10:48 URL： https://twitter.com/motoken_tw/status/1182110548751572992
> @ka_ys_on 弁護士倫理的に見てむちゃくちゃな弁護士ならば、懲戒請求という手があります。弁護士倫理違反の弁護士について懲戒請求しても不当懲戒請求になりませんので、安心してどうぞ。ただし、本当に弁護士倫理違反になるかどうかあなたの弁護士に確認したほうがいいですよ。
▷▷▷　　　　　End　　　　　▷▷▷

　相変わらずリツイートの失敗ですが、これはモトケンこと矢部善朗弁護士（京都弁護士会）によるブロック解除の時期を正確に補足するための処置でもあります。彼自身がどこまで危機感を持つのかと、弁護士業界全体の反応を確かめながら記録する措置です。

　弁護士倫理といえば、その倫理の講習をしているのが深澤諭史弁護士との情報があります。本人によるツイートですが、この時点でまとめ記事を１つ作成しておこうと思います。プログラムに出てくるデバッグのブレークポイントのようなものです。

[link:] 2019年10月10日11時18分の登録： REGEXP：”倫理”／深澤諭史（@fukazawas）の検索（2013-12-13〜2019-09-30／2019年10月10日11時18分の記録149件） http://hirono2014sk.blogspot.com/2019/10/regexpfukazawas2013-12-132019-09.html

[link:] 2019年10月10日11時18分の登録： REGEXP：”弁護士．＊倫理”／深澤諭史（@fukazawas）の検索（2014-01-27〜2019-09-30／2019年10月10日11時18分の記録76件） http://hirono2014sk.blogspot.com/2019/10/regexpfukazawas2014-01-272019-09.html

[link:] 2019年10月10日11時19分の登録： REGEXP：”注意義務”／深澤諭史（@fukazawas）の検索（2015-11-29〜2018-12-06／2019年10月10日11時19分の記録6件） http://hirono2014sk.blogspot.com/2019/10/regexpfukazawas2015-11-292018-12.html

　回転寿司の３点盛りセットのような感じでサクッと作成しました。この手のものはほぼ一瞬で出来てしまい、投稿も完了します。

　絞り込みが不十分と感じたので、もう１つ３点盛りセットを追加しました。３つ名は深澤諭史弁護士がもっとも弁護士会の活動にも関与しているらしい「非弁」をキーワードに指定しましたが、その数、１７３３件となっています。

[link:] 2019年10月10日11時23分の登録： REGEXP：”研修．＊講師”／深澤諭史（@fukazawas）の検索（2015-07-23〜2019-10-04／2019年10月10日11時23分の記録39件） http://hirono2014sk.blogspot.com/2019/10/regexpfukazawas2015-07-232019-10.html

[link:] 2019年10月10日11時23分の登録： REGEXP：”倫理．＊講師”／深澤諭史（@fukazawas）の検索（2016-07-02〜2019-09-30／2019年10月10日11時23分の記録16件） http://hirono2014sk.blogspot.com/2019/10/regexpfukazawas2016-07-022019-09.html

[link:] 2019年10月10日11時24分の登録： REGEXP：”非弁”／深澤諭史（@fukazawas）の検索（2012-09-08〜2019-10-08／2019年10月10日11時23分の記録1733件） http://hirono2014sk.blogspot.com/2019/10/regexpfukazawas2012-09-082019-10.html

▶（10／16） TW fukazawas（深澤諭史） 日時：2019-04-27 08:54:00 +0900 URL： https://twitter.com/fukazawas/status/1121925603463057409
{% tweet 1121925603463057409 %}
> 弁護士会倫理研修講師、細かいのを含めると一人で10件以上担当するっぽいんだが。 \n （・∀・；）

▶（15／16） TW fukazawas（深澤諭史） 日時：2019-09-30 21:37:00 +0900 URL： https://twitter.com/fukazawas/status/1178650012072337408
{% tweet 1178650012072337408 %}
> 倫理研修の講師を沢山やりました - 弁護士 深澤諭史のブログ https://t.co/v5OOsSOGXZ \n （・∀・）結構疲れました。

　どうもこの弁護士会の倫理研修というのは非弁ともセットになることがあるようです。非弁業者に取り込まれ利用される弁護士ということなのでしょう。そういうのも深澤諭史弁護士のタイムラインでは見かけてきましいた。二弁フォロンティアで、怪談のようなものもありました。

▶（01／16） TW fukazawas（深澤諭史） 日時：2016-07-02 11:32:00 +0900 URL： https://twitter.com/fukazawas/status/749068269458522113
{% tweet 749068269458522113 %}
> 来週，二弁の倫理研修ですこし講師をやりますので，対象の方は，よろしくお願いします。 \n 非弁について語ります。 \n 非弁提携問題だけでは無くて，非弁行為をする相手方がいた場合の無効主張とかについても注意喚起します（これをちゃんとやれば，かなりの数の非弁は根絶できるので）。

　そういえば、最近はみかけないですが、深澤諭史弁護士の非弁の警鐘には「無効」という用語が頻繁に出ていました。法律行為の無効のことかと考えますが、一般にしられていそうもないものでとりわけ大きな法律効果の影響を及ぼすようです。調べましたが判例は見つかりませんでした。

[link:] 2019年10月10日11時37分の登録： REGEXP：”注意義務”／深澤諭史（@fukazawas）の検索（2015-11-29〜2018-12-06／2019年10月10日11時37分の記録6件） http://hirono2014sk.blogspot.com/2019/10/regexpfukazawas2015-11-292018-12_10.html

　注意義務は６件でした。このうち善管注意義務が含まれているかは、これから確認します。６件なので確認も簡単かと思いますが、さきほどの非弁のように１７００件を超えるとなると、ページ内検索でも大変そうです。

　トップに（古いもの）から善管注意義務が出てきましたが、これも非弁と無効絡みのものでした。

▶（1／6） TW fukazawas（深澤諭史） 日時：2015-11-29 10:19:00 +0900 URL： https://twitter.com/fukazawas/status/670774003372568576
{% tweet 670774003372568576 %}
> 弁護士としては、このような非弁業者が事件に関与した場合、その代理人を相手にしない、無権代理の主張をするということは善管注意義務として要求されると考えます。 \n 事後的に無効になるリスクを自分の依頼者に負担させるべきではないからです。

▶（2／6） TW fukazawas（深澤諭史） 日時：2015-12-13 10:54:00 +0900 URL： https://twitter.com/fukazawas/status/675856400719810560
{% tweet 675856400719810560 %}
> https://t.co/Tue1rt6BtS \n へたすれば弁護士の善管注意義務ですよね。 \n 私も必ず言うようにしています。零細個人事業主に原価割れリスクの高い仕事を依頼するのだから、「ちゃんとやってもらえない『可能性』だってある」と。

　現在のURLの公式引用とは違うようですが、上記の深澤諭史弁護士のツイートは、次の足立啓太弁護士のツイートのURLを引用しています。この足立啓太弁護士にもずいぶん前からブロックされていて、たぶん３つのアカウント全部になるかと思っています。

　この足立啓太弁護士については、ブロックの解除などすることがないアカウントという認識でいます。しかし、決めつけはいけないので、確認はやっておきます。

keita_adachi ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW keita_adachi（弁護士あだちけいた @光の中から現れた短期決戦の鬼） 日時：2015/12/13 10:24 URL： https://twitter.com/keita_adachi/status/675848628024422401
> 法テラスで依頼しても真面目にやってくれないという認識が、ネット外でも一部では拡がっていることを既に確認してる。 \n 従って法テラス相談でもその点はハッキリ指摘するようにしている。
▷▷▷　　　　　End　　　　　▷▷▷

　上記の足立啓太弁護士の２０１５年１２月１３日のツイートは、単体で先にも後にも返信のツイートがありません。URLを引用したかたちの深澤諭史弁護士のツイートも表示がないですが、法テラスの問題に深澤諭史弁護士は非弁を絡めてきたようです。

　この非弁に対する強いこだわりは、動物的な縄張り意識にも感じるのですが、ツイートをみていて深澤諭史弁護士に肉薄するほど弁護士の権益に執着とこだわりを感じるのが福岡市天神駅近くの向原栄大朗弁護士です。同業者ですら泥棒弁護士とツイートし、死刑問題もそっちのけです。

　深澤諭史弁護士のツイートをみていて、しばしばイメージが重なって去来するのは、中学校１年生の頃、週刊少年ジャンプの連載とともに読んでいた「東大一直線」の主人公、東大通になります。作者の小林よしのり氏は、当時から福岡県の出身として知られ、漫画の舞台も同じかもしれません。

　漫画の「東大一直線」は、その後の数年後「東大快進撃」などとタイトル名も変わっていたようですが、その頃にはすっかりジャンプやマガジンという週刊誌の漫画を読まなくなっていました。深澤諭史弁護士は漫画から飛び出してきたキャラクターで、現在も快進撃を続けています。

　Twitterでブロックされていなければ、深澤諭史弁護士に非弁行為を理由に法律行為が無効とされた判例が実在するのかと質問してみたくもあります。仮にあっても下級審の事例判例で、法律的な指針となる判断を示した判例はないのではと思いますし、あれば出す弁護士はいるでしょう。

▶（3／6） TW fukazawas（深澤諭史） 日時：2015-12-19 16:46:00 +0900 URL： https://twitter.com/fukazawas/status/678119239119593472
{% tweet 678119239119593472 %}
> 非弁の作成書面に基づく合意が無効だって判断されたケースだって、少なくないわけだから、これから非弁関与の合意については、積極的に無効主張することが、弁護士の善管注意義務になるかもしれませんね。

　「非弁の作成書面に基づく合意が無効」となっています。これは当事者の無効の主張による裁判所の判断と思われます。非弁行為は、弁護士を心底軽蔑し不信を募らせた依頼者が弁護士以外を選任するケースがありそうですが、その依頼者の相手方が無効を主張することがあるのでしょうか？

　性犯罪被害者やその家族に向け、私選弁護人で示談に応じておかないと、取り返しのつかない不利益が起こりうるということも、深澤諭史弁護士はツイートをしてきたかと思います。選択の余地がないのが弁護士鉄道であれば、特にそれを爆破し壊滅的打撃を与えるのも社会正義かと思います。

▶（4／6） RT fukazawas（深澤諭史）｜naotarou1981（とりなお） 日時：2018-03-18 18:45:00 +0900／2018-03-18 16:38:00 +0900 URL： https://twitter.com/fukazawas/status/975307241229201409 https://twitter.com/naotarou1981/status/975275184629284865
{% tweet 975307241229201409 %}
> 「休みは手帳に書いて自分で確保する」「万全な体調にしておくことは依頼者に対する善管注意義務」って新人の頃標識せんぱいから聞いた言葉は今でもよく覚えてる。

naotarou1981 ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW naotarou1981（とりなお） 日時：2018/03/18 16:38 URL： https://twitter.com/naotarou1981/status/975275184629284865
> 「休みは手帳に書いて自分で確保する」「万全な体調にしておくことは依頼者に対する善管注意義務」って新人の頃標識せんぱいから聞いた言葉は今でもよく覚えてる。
▷▷▷　　　　　End　　　　　▷▷▷

　弁護士の過労問題として、今朝気になるツイートを見ていたことを思い出しました。私は長距離トラック運転手をしていた頃、信号待ちで仮眠するだけでも効果を実感していたのですが、さらに厳しく張り詰めた状態が長期継続するのが、弁護士の業務のようです。

　どこで見たのか思い出せなかったのですが、ピピピーッのタイムラインがきっかけだったようです。ブラウザでタブが開いたままになっていたのですぐに見けることが出来ましたが、とっかかりが思いつかなくて手間がかかりそうだと心配していました。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜O59K2dPQH59QEJx（ピピピーッ） 日時：2019-10-10 12:26／2019/10/09 23:05 URL： https://twitter.com/kk_hirono/status/1182135338359119872 https://twitter.com/O59K2dPQH59QEJx/status/1181933655347777536
> 脳や心臓で死にますよ、本当に。  睡眠不足は疲れを感じていなくても、体への負荷がハンパないです。 https://t.co/o5mO6w3i6I
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜KR31917261（KR） 日時：2019-10-10 12:27／2019/10/09 02:38 URL： https://twitter.com/kk_hirono/status/1182135580089450497 https://twitter.com/KR31917261/status/1181624956997603328
> ヤバい、意識が飛びそう 今気づいたけど、ここ１週間の合計睡眠時間１０時間行ってない もう明日の法律相談の準備は諦めて寝るしかない、、、
▶▶▶　　　　　End　　　　　▶▶▶

```
KR
@KR31917261
69B。ワークライフバランスという理想とブラックな現実との狭間で苦闘中。ツイートは基本愚痴。
Japan2018年5月からTwitterを利用しています
216 フォロー中
917 フォロワー

［source：］KR（@KR31917261）さん / Twitter https://twitter.com/KR31917261
```

　ほとんど見覚えのないTwitterアカウントだったのですが、プロフィールをよくみると69Bとあります。これは司法修習69期を意味するものと思います。ヘッダ画像の写真は、フィリピンのような東南アジアの町並みなのだと、ページを開き直したところで気が付きました。

　フィリピンで法律業務といえば、まっさきに頭に浮かぶのが滋賀県高島市の野田隼人弁護士になります。値引きの相談にも応じない得意分野というツイートも比較的最近に見かけたように思います。いろいろ謎めいた印象もある弁護士です。

▶（5／6） TW fukazawas（深澤諭史） 日時：2018-08-10 10:44:00 +0900 URL： https://twitter.com/fukazawas/status/1027732402460717057
{% tweet 1027732402460717057 %}
> 司法書士の立会における本人確認義務，というテーマで，以前，司法書士会で講演をさせて頂きましたが， \n 裁判所は，かなり（私からすると不当に）高い注意義務を司法書士に課しているので，注意が必要。 \n （・∀・；）

　深澤諭史弁護士は裁判所が司法書士に高い注意義務を課していると、それも司法書士会の講演で話したとあります。深澤諭史弁護士の司法書士会に招かれた講演というのは、何年か前から見かけておりますし、つい最近も見たように思います。

▶（6／6） TW fukazawas（深澤諭史） 日時：2018-12-06 13:05:00 +0900 URL： https://twitter.com/fukazawas/status/1070529554442215424
{% tweet 1070529554442215424 %}
> 交通事故で正当な賠償を得るには、整骨院の利用は不利益に当たることが多いから、弁護士の誠実義務、善管注意義務に反する可能性があるとおもいます・・。 https://t.co/0gVHaSnLcm

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜nakahaya0427（弁護士中間隼人@横浜の弁護士） 日時：2019-10-10 12:37／2018/12/06 07:48 URL： https://twitter.com/kk_hirono/status/1182138075817725952 https://twitter.com/nakahaya0427/status/1070449987908071424
> 交通事故案件獲得のために整骨院と提携するのって法テラス同様、ビジネス的には悪手だと思う。  薄利多売でクセのある案件が多いから。
▶▶▶　　　　　End　　　　　▶▶▶

　整骨院の不正というのはテレビの短いニュースで何度か見かけたような気がしますが、ネットで問題視されたのは、見かけていなかったかもしれません。弁護士と整骨院の連携と、弁護士と法テラスの連携を同一視しているようにも読めますが、理解が正しいのか自信は持たないです。

　弁護士の誠実義務、と深澤諭史弁護士のツイートにありますが、これは他で見たことがありません。誠実義務という言葉自体がとても珍しく感じました。ちょっと調べてみます。

[link:] » 誠実義務 - Google 検索 https://t.co/3rchCvYSqU

　Googleの検索結果の1ページ目をみると、労働者、介護福祉士がありますが、弁護士は見当たりません。上から6番目でしょうか「信義誠実の原則」が見えます。信義則と呼ばれるものかと思いますが、これは民法の第一条の３つの１つであったような気がします。

[link:] » 誠実義務 弁護士 - Google 検索 https://t.co/phW0JaSBWT

　けっこう具体的な情報がずらずらと出てきたようです。弁護士職務基本規定第5条というのも見えます。

　あまり深入りしてもきりがないので、検索を善管注意義務に変えます。

[link:] » 善管注意義務 弁護士 - Google 検索 https://t.co/U2AtfAOMuf

[link:] » soc28-3.pdf https://t.co/GcHh16oIRb \n 弁護士の善管注意義務と説明義務　ー最高裁平成25年4月16日判決民集67巻4号１０４９頁を手がかりとして　王冷然

　面倒なPDFファイルで、見出しの部分をコピペすると文字化けをしていました。手作業で文字入力をしTwitterに投稿したものです。最初の方を少し読んだだけですが、医師のインフォームドコンセントとの比較など出てきて興味深いです。やはり、具体性を欠いているともあります。

　「弁護士の説明義務や注意義務の内容は、具体性を欠いている。確かに、下級審裁判例がある程度存在するが、最高裁レベルの判決としてはこれまで存在しなかったところ、ようやく」と最高裁判例を紹介しているようです。最高裁判決があったことも初めて知りました。

〈〈〈：Emacs： 2019-10-10（木曜日）13：00 　〈〈〈

