#+TITLE: "裁判員裁判三傑③否認する被告人に真実話さないと償えないと問う裁判所←ＮＥＷ！！"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-11-26 16:39:51 +0900
FILE_NAME: 2019-11-26-163951_裁判員裁判三傑③否認する被告人に真実話さないと償えないと問う裁判所←ＮＥＷ！！.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 深澤諭史弁護士,裁判員裁判,新潟市西区女児殺害事件,司法試験
記事タイトル名の文字数：39　保存ファイル名の文字数：61
#+STARTUP: showeverything


* 「街弁になる予定」というアカウントの反応と深澤諭史弁護士の返信ツイート：裁判員裁判三傑③否認する被告人に真実話さないと償えないと問う裁判所←ＮＥＷ！！
  CLOCK: [2019-11-26 火 17:16]--[2019-11-27 水 11:26] => 18:10

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 深澤諭史弁護士,裁判員裁判,新潟市西区女児殺害事件,司法試験

〉〉〉：Emacs： 2019-11-26（火曜日）17：16　 〉〉〉

　ベースとなるのは次の深澤諭史弁護士のツイートです。裁判員の問題だけを三点盛りで取り上げ、３つ目にNEW！！などと印をつけていますが、これは昨日辺りに取り上げた新潟市西区女児殺害事件の死刑求刑のニュースに関連したものです。

fukazawas ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW fukazawas（深澤諭史） 日時：2019/11/23 11:28 URL： https://twitter.com/fukazawas/status/1198065660171096064
> 裁判員裁判三傑 \n ①障害者は受け入れ先がないので求刑より長く刑務所入れるのが健全な社会常識 \n ②無罪っぽいんで刑を軽くします。 \n ③否認する被告人に真実話さないと償えないと問う裁判所←ＮＥＷ！！
▷▷▷　　　　　End　　　　　▷▷▷

　上記の深澤諭史弁護士のツイートには、今現在、次の２つのツイートが返信としてぶら下がっています。１つは忘れた頃に見かけるスイカのアイコンでプロフィールの名前も「モフ」とわかりやすいものになっています。２つ目は、しばらく前にとりあげた航海玉子というアカウントです。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜mofjd（モフ） 日時：2019-11-26 17:23／2019/11/23 11:32 URL： https://twitter.com/kk_hirono/status/1199242150191366144 https://twitter.com/mofjd/status/1198066743958130689
> @fukazawas 今回のは「裁判員」裁判だから、というわけではないので、同列に扱うのはおかしい気がします。裁判長が困った人という話で、困った裁判長の話は裁判員裁判以外でもあり得ますよね。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kd_ixi（エンリケ航海玉子） 日時：2019-11-26 17:23／2019/11/23 12:37 URL： https://twitter.com/kk_hirono/status/1199242210916519936 https://twitter.com/kd_ixi/status/1198083130978029568
> @mofjd @fukazawas 裁判官がそんな質問をしようと考えるはずがなく、裁判員からどうしても聞いてくれと言われて仕方なく聞いている、と善解することもできなくはないです。
▶▶▶　　　　　End　　　　　▶▶▶

　メインの深澤諭史弁護士のツイートは現時点で、リツイートが３８件、いいねが９６件と多くはありません。

　今回気になったのは、それとは別の次の深澤諭史弁護士のツイートで、返信先がありますがそちらの返信先のアカウントのことが気になりました。プロフィールに「街弁になる予定」とあったからです。弁護士業界の将来を担う人材ということにもなるのかと考えます。

fukazawas ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW fukazawas（深澤諭史） 日時：2019/11/23 16:36 URL： https://twitter.com/fukazawas/status/1198143198427631616
> @galaxy_idol02 恐ろしいことに全部マジ（・∀・；）
▷▷▷　　　　　End　　　　　▷▷▷

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜galaxy_idol02（レーティア） 日時：2019-11-26 17:36／2019/11/23 16:30 URL： https://twitter.com/kk_hirono/status/1199245509522685952 https://twitter.com/galaxy_idol02/status/1198141653585813504
> RT これマジ！？
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜galaxy_idol02（レーティア） 日時：2019-11-26 17:36／2019/11/23 16:37 URL： https://twitter.com/kk_hirono/status/1199245599956037633 https://twitter.com/galaxy_idol02/status/1198143480104546309
> @fukazawas 恐ろしすぎますね💦 二つ目とかは裁判員に対して利益原則を教えてなかったんでしょうかね・・・
▶▶▶　　　　　End　　　　　▶▶▶

　上記の２件目になりますが、１１月２３日１６時３０分のツイートに、深澤諭史弁護士が同日１６時３６分に１件目のツイートを返信をし、さらに同日１６時３７分に深澤諭史弁護士に返信したのが３件目のツイートになります。

　女の子のアニメのアイコンで、似たようなアイコンはずいぶん見かけることが多いので、把握はしきれないですが、「レーティア」というプロフィールの名前は、これまでにも見かけたように思いました。取り上げるのは今回が初めてになるものと思います。

　確認したところ、すでに記録が数件あって、変更も多いTwitterのプロフィールの名前に変更もありませんでした。

```
% dp -p|grep レーティア
[link:] 2019年05月11日11時55分の登録： ＼レーティア　@galaxy_idol02＼それも含めて依頼者に理解して貰うのが弁護人の仕事だと思ってます 勿論難しいとは思いますが…  http://hirono2014sk.blogspot.com/2019/05/galaxyidol02.html
[link:] 2019年05月11日11時56分の登録： ＼レーティア　@galaxy_idol02＼黙秘権って被疑者(被告人)にとって取調べ中唯一の武器だと思ってるんだけど、同期とこの考えを共有出来てない  http://hirono2014sk.blogspot.com/2019/05/galaxyidol02_11.html
[link:] 2019年05月20日18時10分の登録： ＼レーティア　@galaxy_idol02＼枝野さんと佐藤教授の問答で枝野さん少し好きになった http://hirono2014sk.blogspot.com/2019/05/galaxyidol02_20.html
[link:] 2019年05月24日22時25分の登録： ＼レーティア　@galaxy_idol02＼5人に一人が1年目から1千万超える世界 http://hirono2014sk.blogspot.com/2019/05/galaxyidol02511.html
[link:] 2019年07月26日09時13分の登録： ＼レーティア　@galaxy_idol02＼返信先: \n@fukazawas\nさん\n深澤先生もでしたか！\n自由にできるお金がこんなにあるのかという感じです笑\n本当先輩方に http://hirono2014sk.blogspot.com/2019/07/galaxyidol02-fukazawas.html
[link:] 2019年11月25日11時08分の登録： ＼レーティア　@galaxy_idol02＼RT\nこれマジ！？ http://hirono2014sk.blogspot.com/2019/11/galaxyidol02rt.html
```

　まとめ記事として取り上げていた次のツイートも、今年の７月２６日ですが、すっかり記憶にありませんでした。まとめ記事の埋め込みツイートには、返信先の深澤諭史弁護士のツイートが合わせて表示され、「完全に当職と一致（・∀・）」と見えます。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜galaxy_idol02（レーティア） 日時：2019-11-26 17:48／2019/07/26 08:07 URL： https://twitter.com/kk_hirono/status/1199248482852204545 https://twitter.com/galaxy_idol02/status/1154528726228467713
> @fukazawas 深澤先生もでしたか！ 自由にできるお金がこんなにあるのかという感じです笑 本当先輩方には感謝してもしきれません
▶▶▶　　　　　End　　　　　▶▶▶

fukazawas ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW fukazawas（深澤諭史） 日時：2019/07/26 08:05 URL： https://twitter.com/fukazawas/status/1154528121414025216
> @galaxy_idol02 完全に当職と一致（・∀・）
▷▷▷　　　　　End　　　　　▷▷▷

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜galaxy_idol02（レーティア） 日時：2019-11-26 17:49／2019/07/26 08:02 URL： https://twitter.com/kk_hirono/status/1199248915947614209 https://twitter.com/galaxy_idol02/status/1154527432885460993
> 今までほぼバイトしたことなかったから、給付金も大金に感じる
▶▶▶　　　　　End　　　　　▶▶▶

　深澤諭史弁護士からツイートに返信を送り、全部で４つのツイートが会話となったようです。そういえばと思い出すところもありますが、弁護士として、司法試験の合格者として、司法修習の経験者として、後輩思いとも感じる深澤諭史弁護士のツイートは、ちょくちょく見かけてきました。

　深澤諭史弁護士自身は、それほど露骨な表現ではなかった気もしますが、他の弁護士アカウントでも、Twitterで豪華なご馳走の写真を並べるなどして弁護士の魅力を発信することが、後に続く弁護士や司法修習の意欲を促進し、ひいては弁護士業界全体の隆盛に繋がるという考えがあるようです。

　「弁護士パラダイス」という言葉もたびたび頭に浮かんできましたが、深澤諭史弁護士の場合は、やはり一線を超えているように思えてなりません。司法の利益を享受する立場でも看過できないものがあり、深澤諭史弁護士が弁護士の正当化の根拠とする消費者被害は、それに深刻な拍車を掛けるものです。

　深澤諭史弁護士に対しては弁護士業界のサラブレッド、駿馬とみることもありますが、生物的にも社会的脅威を感じるもので、破滅に向かう最終進化系弁護士に思えてがらず、本人のみならず、同じ業界の反応や動向というのも重視し、日々、記録をしています。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-26 18:09／2019/05/25 00:08 URL： https://twitter.com/kk_hirono/status/1199253829885153280 https://twitter.com/s_hirono/status/1131940122709045249
> 2019-05-24-222450_深澤諭史さんがリツイート＞　レーティア（@galaxy_idol02）：　5人に一人が1年目から1千万超える世界.jpg https://t.co/MnbdDwrPhx
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-26 18:09／2019/11/05 20:44 URL： https://twitter.com/kk_hirono/status/1199253801158373376 https://twitter.com/s_hirono/status/1191682710151950337
> 2019-11-05-204318_深澤諭史さんがリツイートレーティア@galaxy_idol02·23h佐藤幸治教授には他事考慮や考慮不尽という言葉を知って頂きたかったですね（皮肉）.jpg https://t.co/F44HI8idJX
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-26 18:08／2019/11/25 11:21 URL： https://twitter.com/kk_hirono/status/1199253609663229952 https://twitter.com/s_hirono/status/1198788819299909632
> 2019-11-25-111740_レーティア@galaxy_idol02·11月23日RTこれマジ！？.jpg https://t.co/ahSziIZWGs
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-26 18:08／2019/11/25 11:21 URL： https://twitter.com/kk_hirono/status/1199253570123526144 https://twitter.com/s_hirono/status/1198788892549189632
> 2019-11-25-111759_レーティアさんがリツイート深澤諭史@fukazawas·11月23日裁判員裁判三傑①障害者は受け入れ先がないので求刑より長く刑務所入れるのが健全な社会常識.jpg https://t.co/ABCO9z5CQb
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-26 18:08／2019/11/26 16:24 URL： https://twitter.com/kk_hirono/status/1199253537978343424 https://twitter.com/s_hirono/status/1199227415798530050
> 2019-11-26-154655_深澤諭史さんがリツイートレーティア@galaxy_idol02·11月22日なんとなくだけど実務上、被害者供述あり、被害者供述を裏付ける客観証拠薄い、被告.jpg https://t.co/gnmoHZgGxh
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 非常上告-最高検察庁御中_ツイッター(@s_hirono)/「レーティア」の検索結果 - Twilog https://t.co/cUoIHWKHbC

　スクリーンショットの記録には、深澤諭史弁護士のタイムラインで、レーティアというアカウントが佐藤幸治氏に皮肉としたツイートを、深澤諭史弁護士がリツイートしていたものがありました。この程度だとなかなか記憶も出来ないのですが、深澤諭史弁護士の不満の源流の１つです。

　佐藤幸治氏は一般にしられた人物ではないと思いますし、テレビで名前を聞いた覚えもありません。私もネットで調べた程度の知識ですが、司法制度改革には重要な人物で、成仏理論の人物とともに、怨嗟の的となって来たようです。

　その司法制度改革の目玉の一つが、今年１０年目を迎えたとも聞く裁判員制度で、これも深澤諭史弁護士が痛烈に皮肉ったり、罵倒し、玩具のような扱いをすることが多いという印象です。今回の新潟市西区女児殺害事件の死刑求刑の裁判員裁判も、それを踏襲したものとみています。

　レーティアというTwitterアカウントのタイムラインを遡ったのは、「RT これマジ！？」というツイートをみたからで、最近は見かけることが減っているとも感じますが、主に直前のリツイートを指すことが多い手法です。ツイートに繋がりはなく、追うのが困難となります。

　タイムラインを遡ると、やはり直前に深澤諭史弁護士のツイートをリツイートしていて、それに気がついた深澤諭史弁護士が返信のツイートを行っていました。

　そのレーティアというアカウントのタイムラインを遡った時、遡る量も多くはなかったですが、１つ気になるプロフィールの名前のアカウントを見つけました。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜dendenkenken（司法宮かぐや） 日時：2019-11-26 18:32／2019/11/13 18:36 URL： https://twitter.com/kk_hirono/status/1199259533576564736 https://twitter.com/dendenkenken/status/1194549668027330563
> 未修が私にくれたもの　睡眠時間のない日常　未修が私にくれたもの　寝不足イライラ片頭痛　未修が私にくれたもの　🦆がつけた成績表　第一志望だったけど　身体がもたなくて　第一志望だったけど　精神ももたなくて　バイバイ激ヤバ未修　さよならしてあげるわ
▶▶▶　　　　　End　　　　　▶▶▶

　上記にリツイートをしたツイートのアカウントになります。「司法宮」の部分しか記憶になかったのですが、「かぐや」という部分も気になるもので、「かぐや姫の物語」という映画のことや、「かぐや様は告らせたい」などとTwitterのトレンドで見たことを思い出しました。

```
司法宮かぐや
@dendenkenken
UTSL未修 かぐや様は司法試験に合格したい
秀知院大学法科大学院2018年7月からTwitterを利用しています
263 フォロー中
160 フォロワー

［source：］司法宮かぐや（@dendenkenken）さん / Twitter https://twitter.com/dendenkenken
```

　２，３日前に見たときとは、プロフィールの内容が変わったように感じました。「UTSL未修 かぐや様は司法試験に合格した」とわかりやすいものになっており、さらに「秀知院大学法科大学院」とありますが、これは位置情報になるのではと思います。

　ロースクールとも呼ばれる法科大学院については、募集停止が続出しているという法クラのツイートを見たこともありましたが、「秀知院大学法科大学院」というのは、実在するのか疑問で、これから調べてみますが、日本の都道府県に実在するのであれば、驚きの発見です。

[link:] » 『かぐや様は告らせたい～天才たちの恋愛頭脳戦～』秀知院学園生徒会からの挑戦状｜週刊ヤングジャンプ連載100回記念 https://t.co/s6ARZuQskK

　上記のページに詳細はなかったですが、漫画に出ている学園名が秀和院学園のようです。「かぐや様は告らせたい」は、テレビで映画の番宣として見たような記憶も少しあるのですが、かぐやというのは主人公とも思われる登場人物で、「四宮かぐや」という名前のようです。

[link:] » TVアニメ『かぐや様は告らせたい？～天才たちの恋愛頭脳戦～』公式サイト https://t.co/busIGMRgd5

　調べると、TVアニメという情報が出てきましたが、石川県のテレビでは、アニメの放送自体が少なく、土日の朝と夕方にいくつかある程度だと思います。最近はその時間帯のテレビ欄をみることもなかったので、石川県での放送は不明ですが、やっていないような気はします。

　「かぐや様は告らせたい？」と？マークがつくようです。副題が「天才たちの恋愛頭脳戦」のようですが、気になるところはあります。一般には法クラの弁護士らも「天才たちの頭脳戦」と映るのかもしれません。

[link:] » 『かぐや様は告らせたい ～天才たちの恋愛頭脳戦～』TVCM 純愛?編 - YouTube https://t.co/XvceBiC3Vq

　次の動画、に「映画少年時代」という動画が出てきました。ちょっと気になって再生し、２分５１秒で一時停止させたところですが、最初は気が付かなかったものの「少年時代」という戦時中、富山での疎開生活を描いた漫画の実写版のようです。

　藤子不二雄という富山県出身の漫画家の作品で、私は金沢刑務所の拘置所にいるときに官本の漫画を読みました。単行本より大きな本で、収容者の人気もあったのかずいぶん使い込まれていました。漫画の内容もとても印象的なものとして記憶に残っています。

[link:] » 【CM 1991】SONY Handycam オートmini 30秒×4 - YouTube https://t.co/hdrEn6dBk6

　視聴を終えてから気がついたのですが、YouTubeの動画のタイトルに「少年時代」はありませんでした。４つか５つほどCMがありましたが、１つだけ記憶に残るCMは見当たりませんでした。「少年時代」という井上陽水の曲になります。名前を見かけなくなってずいぶん経つと気づきました。

[link:] » 映画少年時代 - YouTube https://t.co/REjuvvWVXF \n 　視聴終了。

　テレビCMの曲とばかり思っていたのですが、映画の主題歌だったようです。エンディングで曲が始まるとすぐに音声が途切れ、終了間際に音が復活してすぐに終わりました。漫画で読んだイメージが強すぎて、映画のことは考えたこともなかった気がします。

[link:] » 井上陽水　少年時代　 - ニコニコ動画 https://t.co/xYvFHkwtQI

[link:] » 生地駅 - Wikipedia https://t.co/NLPqgAWRxz \n 生地駅（いくじえき）は、富山県黒部市吉田字浦島にあるあいの風とやま鉄道線の駅である。

[link:] » 山崎 - Google マップ https://t.co/mLSyuZJdun \n 〒938-0162 富山県下新川郡朝日町

[link:] » 金太郎温泉 - Google マップ https://t.co/hr6D0HyuxE

[link:] » 金太郎温泉 光風閣　CM　1986年 - YouTube https://t.co/7oDXbuE2kn

[link:] » 金太郎温泉50年のあゆみ【YouTube 動画】 https://t.co/iYQtHhJMp9

[link:] » マグマ大使のうた - YouTube https://t.co/RD8pnVCqTb

[link:] » 黄金バット op 【1960年代 】 - YouTube https://t.co/OZedaDPgmJ

[link:] » 少年時代 - Wikiwand https://t.co/N3FqiTXqCR \n 『少年時代』（しょうねんじだい）は、藤子不二雄Ⓐによる日本の漫画および、1990年に公開された映画。1978年（昭和53年）から1979年（昭和5… https://t.co/DsXVDfjzSY

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜mr_114（ミスター） 日時：2019-11-27 01:22／2019/11/25 17:45 URL： https://twitter.com/kk_hirono/status/1199362682840739840 https://twitter.com/mr_114/status/1198885365223813120
> あの人俺の悪口言ってましたよって報告いらない。あの人俺の事悪く言ってたんで山に埋めときましたよっていう完了報告だけ欲しい。
▶▶▶　　　　　End　　　　　▶▶▶

　上記のリツイートは、レーティアというTwitterアカウントのタイムラインで、４０ｍと２ｈの間のリツイートとして見かけたものですが、返信が６２，リツイートが４．１万、いいねが１３．６万となっているのも驚きでした。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜galaxy_idol02（レーティア） 日時：2019-11-27 01:27／2019/11/26 22:35 URL： https://twitter.com/kk_hirono/status/1199363967769927681 https://twitter.com/galaxy_idol02/status/1199320751410569216
> @law__ca いえいえ、理論ばかりで人は説得できませんからね、私も勉強になります！  終わりました、ハードでした笑 ありがとうございます！
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜law__ca（そーち） 日時：2019-11-27 01:27／2019/11/26 22:29 URL： https://twitter.com/kk_hirono/status/1199363953312161792 https://twitter.com/law__ca/status/1199319376563859456
> @galaxy_idol02 感情的なものもあるので難しいですよね… わざわざありがとうございます🙏  2回試験は終わったんですかね？ お疲れさまでした！！
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜galaxy_idol02（レーティア） 日時：2019-11-27 01:26／2019/11/26 22:24 URL： https://twitter.com/kk_hirono/status/1199363919292194817 https://twitter.com/galaxy_idol02/status/1199318122441789440
> @law__ca うーんたしかに難しい問題ですよね 私もまだ自分の考えを詰めきれてないので、もっとしっかり考えてみたいです
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜law__ca（そーち） 日時：2019-11-27 01:26／2019/11/26 22:16 URL： https://twitter.com/kk_hirono/status/1199363893195227138 https://twitter.com/law__ca/status/1199316031165984768
> @galaxy_idol02 みたいなことは言えないです🙊  別に議論するつもりはないですが、違う立場？の人はどう考えているのかなと思ってリプさせてもらいました！
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜law__ca（そーち） 日時：2019-11-27 01:26／2019/11/26 22:15 URL： https://twitter.com/kk_hirono/status/1199363875465940992 https://twitter.com/law__ca/status/1199315732028243968
> @galaxy_idol02 なるほど 僕は三つ子の魂百までマンなので、可塑性があるから～みたいなのはよく分かりません  例えば、女子高生を拉致強姦した後にコンクリ詰めにして殺した少年が結婚して子どもとか産まれても、「未成年のころ… https://t.co/QFoMT1qqDe
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜galaxy_idol02（レーティア） 日時：2019-11-27 01:26／2019/11/26 21:59 URL： https://twitter.com/kk_hirono/status/1199363762353930242 https://twitter.com/galaxy_idol02/status/1199311596490608640
> @law__ca 私は両立するんじゃないのかなと思っていますが、被害者の方も色々な方がいらっしゃるので一概には言えないのかなぁというのが現状です
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜law__ca（そーち） 日時：2019-11-27 01:26／2019/11/26 21:54 URL： https://twitter.com/kk_hirono/status/1199363739960537088 https://twitter.com/law__ca/status/1199310490565955584
> @galaxy_idol02 可塑性があることでの情状弁護と被害者感情って両立しますか？
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Jakotsunya（⎳法律好きなVtuberじゃこにゃー） 日時：2019-11-27 01:25／2019/11/26 21:48 URL： https://twitter.com/kk_hirono/status/1199363594808262656 https://twitter.com/Jakotsunya/status/1199308939000594432
> ツイッターを通じて弁護士さんや弁護士を目指す人に聞いた　#youは何で弁護士に　今晩は銀冠さん ( @ginkanmuri_0202   ) に聞いてみました。ありがとうございます～多分それは考えれば考える程、本当に難しい問題。弁… https://t.co/yx1c9jCUQ3
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜galaxy_idol02（レーティア） 日時：2019-11-27 01:25／2019/11/26 21:50 URL： https://twitter.com/kk_hirono/status/1199363564399546368 https://twitter.com/galaxy_idol02/status/1199309413636423680
> ワイも冤罪事件を知ってこっちの道目指したけど、今は情状弁護も関心ある
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜galaxy_idol02（レーティア） 日時：2019-11-27 01:25／2019/11/26 21:51 URL： https://twitter.com/kk_hirono/status/1199363526071947264 https://twitter.com/galaxy_idol02/status/1199309773935497222
> 2回試験前からこれ読みたいと思ってた https://t.co/RJuWLbR9dn
▶▶▶　　　　　End　　　　　▶▶▶

　ツイートには本の表紙と思われる画像のみですが、「治療的司法の実践　更生を見据えた刑事弁護のために」とあります。映画の「少年時代」と、福井刑務所、金沢刑務所の服役体験を比較しいろいろとも思い出しながら考えていたタイミングでした。

[link:] » 治療的司法の実践　―更生を見据えた刑事弁護のために― / 第一法規ストア https://t.co/5F69NCkKTI

　第一法規をみたのも久しぶりですが、福井刑務所に受刑中、強制わいせつで冤罪を訴え、金沢市の合同法律事務所の話もしてくれた受刑者が、なにか紹介をしてくれた本で初めて知ったのが、この第一法規ではなかったかと思います。Twilogに記録があるかもしれません。

[link:] » 告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)/「第一法規」の検索結果 - Twilog https://t.co/uzhhiFX7QU

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「第一法規」の検索結果 - Twilog https://t.co/cL4dbmHRBc

　告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)のTwilogに第一法規は見当たらず、奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)も該当件数が多かったものの福井刑務所に関するツイートは見当たりませんでした。

　よく考えてみると福井刑務所で話を聞いたのは第一法規ではなかったような気もしてきました。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-27 01:45／2011/01/20 15:41 URL： https://twitter.com/kk_hirono/status/1199368497962217472 https://twitter.com/hirono_hideki/status/27979114090602496
> （引用→）刑事事件の分野では、かけだしのとき蛸島学童殺人事件で先輩弁護士から無罪の追求の仕方を教えられました。山中温泉殺人事件（一審二審の死刑判決が最高裁及び名古屋高裁で逆転無罪）では"金沢合同法律事務所　弁護士の紹介「菅野昭夫」" - http://j.mp/e9IizN
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「金沢合同法律事務所」の検索結果 - Twilog https://t.co/sCfXqzxlEe

[link:] » Introduce Sub07 に何も見つかりません https://t.co/O5QkSw88eM

[link:] » 金沢合同法律事務所 | 専門性の高い弁護士集団。女性弁護士も活躍中！ https://t.co/3IOqDsbnJ2

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-27 01:47／2011/01/20 00:04 URL： https://twitter.com/kk_hirono/status/1199369213208489984 https://twitter.com/hirono_hideki/status/27743102261264384
> やはりそうですか。司法巡査、司法警察員という呼び方もありますね。 RT @thermalpaper00: 刑事ってのは、実は部署、部門の名称であって、警察には刑事という役職は正式には存在しない。刑事部門の捜査員個人を指す場合の通称みたいなものなんだよね。
▶▶▶　　　　　End　　　　　▶▶▶

hirono_hideki ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2011/01/20 13:54 URL： https://twitter.com/hirono_hideki/status/27952010129047552
> RT @thermalpaper00: やっぱり弁護士さんは取調べの録画記録を自由に扱いたいんだなあ。そりゃ例え流出しても自分は何の影響も受けないんだから当然だよねえ。
▷▷▷　　　　　End　　　　　▷▷▷

　意外な発見があったので、とりあえずメモを兼ねています。

[link:] » 被告発人・被告訴人YSNに関するツイートのまとめ（2010年8月５〜7日分） | 廣野秀樹＼さらば弁護士鉄道・泥棒神社の物語（金沢地方検察庁御中） https://t.co/fDS9C2Q1k4

[link:] » 治療的司法の実践 更生を見据えた刑事弁護のために | 政府刊行物 | 全国官報販売協同組合 https://t.co/xwU5JXxGii

[link:] » #youは何で弁護士に - Twitter検索 / Twitter https://t.co/eFJbuEZeh4

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜todateyoshiyuki（弁護士　戸舘圭之） 日時：2019-11-27 02:06／2019/10/25 21:40 URL： https://twitter.com/kk_hirono/status/1199373949643051008 https://twitter.com/todateyoshiyuki/status/1187710418015285249
> じゃこにゃーさんに取り上げていただきました。#youは何で弁護士に  ま、いろいろありますが、何で？と言われればこうなりますわね。  じゃこにゃーさん、冤罪について熱く語っていただきありがとうございます😊 https://t.co/8SMnird49H
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Jakotsunya（⎳法律好きなVtuberじゃこにゃー） 日時：2019-11-27 02:07／2019/10/21 22:58 URL： https://twitter.com/kk_hirono/status/1199374112302366720 https://twitter.com/Jakotsunya/status/1186280685591416832
> ツイッターを通じて弁護士さんや弁護士を目指す人に聞いた　#youは何で弁護士に　今晩は戸舘圭之さんという方に聞いてみました。ありがとうございます～冤罪事件は本当に衝撃が大きい話  #VRアカデミア　#バーチャルyoutuber… https://t.co/BYBJGn9jcK
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 戸舘 圭之弁護士（戸舘圭之法律事務所） - 東京都千代田区 - 弁護士ドットコム https://t.co/XA5DdAoGb5

[link:] » 戸舘 圭之弁護士（戸舘圭之法律事務所） - 東京都千代田区 - 弁護士ドットコム https://t.co/XA5DdAoGb5 \n 「共謀罪」という毒薬 共謀罪があることで生まれる人心制御 \n 週刊金曜日２０１７年３月

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-27 02:27／2019/10/31 23:34 URL： https://twitter.com/kk_hirono/status/1199379183668883456 https://twitter.com/hirono_hideki/status/1189913487889141760
> 2019年10月31日23時32分の登録： ％@Jakotsunya　⎳法律好きなVtuberじゃこにゃー％ツイッターを通じて弁護士さんや弁護士を目指す人に聞いた　#youは何で弁護士に　今晩は戸舘圭之さんという方 https://t.co/kTZcqlR0aP
▶▶▶　　　　　End　　　　　▶▶▶

　今年２０１９年の１０月３１日の記録ということで、まだ一月も経っていないですが、記憶と言うより見に覚えのないツイートです。忙しくやっていたタイミングで、やっつけでとりあえず記録をやったのかもしれません。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Jakotsunya（⎳法律好きなVtuberじゃこにゃー） 日時：2019-11-27 02:31／2019/11/05 22:17 URL： https://twitter.com/kk_hirono/status/1199380256143970304 https://twitter.com/Jakotsunya/status/1191706157485682688
> ツイッターを通じて弁護士さんや弁護士を目指す人に聞いた　#youは何で弁護士に　今晩はくまえもんさんに聞いてみました。ありがとうございます～プリキュッア～！！  #VRアカデミア　#バーチャルyoutuber #Vtuber https://t.co/JIpG6VIwju
▶▶▶　　　　　End　　　　　▶▶▶

TW lawyernakahara（弁護士 中原潤一） 日時： 2019/11/27 09:26 URL： https://twitter.com/lawyernakahara/status/1199484631172534272
> 一番悪いのは、否認してると保釈しない裁判所の運用でしょ。こうやって、無実の人が、保釈されたいがために虚偽自白する運用に自分達がしてしまっていることを、裁判官は理解すべき。 \n  \n 覚醒剤使用、女性に無罪　高裁「虚偽自白の可能性」: 日本… https://t.co/YF3WXD89V3

　上記のツイートはさきほどの発見になりますが、K - 9 9 9 9というTwitterアカウントのタイムラインで本人のリツイートになります。

　今朝は、ほかにも大きな発見があったのですが、次のテーマは昨夜寝る前に、ほぼほぼ決まっています。少なくとも「弁護士に向かって」を含めます。

〈〈〈：Emacs： 2019-11-27（水曜日）11：26 　〈〈〈

