#+TITLE: "「川端伸也の事件回顧録①　of　京都みらい法律事務所」と、宇出津上田町における黄金バットの古い記憶"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-11-05 21:16:55 +0900
FILE_NAME: 2019-11-05-211655_「川端伸也の事件回顧録①　of　京都みらい法律事務所」と、宇出津上田町における黄金バットの古い記憶.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 秋重実弁護士（京都弁護士会）,,井戸謙一弁護士
記事タイトル名の文字数：49　保存ファイル名の文字数：71
#+STARTUP: showeverything


* 黄金バットについて：「川端伸也の事件回顧録①　of　京都みらい法律事務所」と、宇出津上田町における黄金バットの古い記憶
  CLOCK: [2019-11-05 火 21:24]--[2019-11-05 火 23:32] =>  2:08

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 秋重実弁護士（京都弁護士会）,井戸謙一弁護士,元検事,検事正

〉〉〉：Emacs： 2019-11-05（火曜日）21：24　 〉〉〉

　小学校低学年の頃、昭和40年代後半の記憶と思うのですが、外がすっかり暗くなった夕方の時間に宇出津上田町のある家に行った記憶があり、それがずっと黄金バットと強く結びついていました。年に数回思い出しながら記憶が継続していましたが、最近になってその頻度が高まりました。

　きっかけは湖東記念病院事件の再審請求でしたが、比較的最近になってその思いが高まり、ついに「黄金バット」についてネットで検索を実行するに至りました。これからTwilogで確認をしますが、「黄金バット」をキーワードにした最初のツイートは、比較的最近のことだと思います。

　ずっともやもやしたものが続いていて、それが何かのきっかけで「黄金バット」の検索という行動になったのだと思いますが、検索を実行せずに、もやもやした状態がとても長く続いていたのも、振り返ると不思議なことです。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-05 21:35／2019/10/02 09:49 URL： https://twitter.com/kk_hirono/status/1191695642113896448 https://twitter.com/hirono_hideki/status/1179196674138181632
> 黄金バット - Wikiwand https://t.co/zAl9nXoesT
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「黄金バット」の検索結果 - Twilog https://t.co/nzV0lxtBhc

　10月2日とは驚きました。今日が11月5日なのでわずかに一月とちょっと前になります。少なくとも2ヶ月ぐらいは経過しているものと思っていました。きっかけとして関連するツイートがないか、その10月2日のツイートを同じくTwilogで確認してみたいと思います。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-05 21:40／2019/10/02 09:45 URL： https://twitter.com/kk_hirono/status/1191696740254015490 https://twitter.com/hirono_hideki/status/1179195570478444544
> ゴールデンバッド - Google 検索 https://t.co/o5MGpQtqJP
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-05 21:39／2019/10/02 02:18 URL： https://twitter.com/kk_hirono/status/1191696567301836800 https://twitter.com/hirono_hideki/status/1179083109641281536
> 2019年10月01日21時35分の登録： ＼ピピピーッ　@O59K2dPQH59QEJx＼野次馬が去ろうが寄ろうがワイには関係ないんやで。ワイはひたすら呟き続けるキ印なんや。期待なんてされても困るんだが。 https://t.co/lqVDUYkolM
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-05 21:39／2019/10/02 02:18 URL： https://twitter.com/kk_hirono/status/1191696512863965185 https://twitter.com/hirono_hideki/status/1179083083389079552
> 2019年10月01日21時34分の登録： ＼高橋雄一郎　@kamatatylaw＼女性弁護士の自殺が多いというよりも、女性弁護士には自殺と隣り合わせの自営業が多い、というだけなのかもしれないけどね。 https://t.co/CL30TLZHtw
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2019年10月02日 - Twilog https://t.co/Wgw8JHCzMw

　最初に、「ゴールデンバッド」と検索をして、タバコの銘柄の情報ばかりが出てきたことを思い出しましたが、「バッド」というのも勘違いで悪という意味の情報ばかりが出てきました。細かくツイートで記録はしていなかったようですが、バットで黄金バットが正解でした。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-05 21:48／2019/10/01 21:34 URL： https://twitter.com/kk_hirono/status/1191698787292442626 https://twitter.com/hirono_hideki/status/1179011578860978176
> 2019年10月01日21時32分の登録： ＼高橋雄一郎　@kamatatylaw＼平成21年と平成24年に女性弁護士が大量自殺しているんですよ。10年平均だと先に投稿した計算になるかと思います。直近5年はやや改善 https://t.co/XB7Fm4hsoq
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-05 21:48／2019/10/01 21:33 URL： https://twitter.com/kk_hirono/status/1191698758926340096 https://twitter.com/hirono_hideki/status/1179011500024877057
> 2019年10月01日20時19分の登録： ＼ʇɐɯɐɹnɯʞ　@kmuramatsu＼実の娘と性交、父親に懲役9年判決　中学生の頃から常習：朝日新聞デジタル https://t.co/T6v3fkedBr
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-05 21:47／2019/10/01 20:23 URL： https://twitter.com/kk_hirono/status/1191698520257912834 https://twitter.com/hirono_hideki/status/1178993913400479744
> 実の娘と性交、父親に懲役９年判決　中学生の頃から常習：朝日新聞デジタル https://t.co/S8CxdPL6Sw 岐阜地裁では、今年度に入り少なくとも３件の監護者性交等罪および同未遂罪の判決があり、いずれも求刑通りか求刑に近い実刑判決が言い渡されている。（松沢拓樹）
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-05 21:47／2019/10/01 18:40 URL： https://twitter.com/kk_hirono/status/1191698469150347267 https://twitter.com/hirono_hideki/status/1178967881519755264
> 検察側が有罪主張を撤回か 滋賀・患者死亡の再審協議：朝日新聞デジタル https://t.co/5yKvMb9XgW
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2019-11-05 21:47／2019/10/01 07:14 URL： https://twitter.com/kk_hirono/status/1191698431145697280 https://twitter.com/amneris84/status/1178795191651598337
> 新たな有罪立証を断念。ならば、早く有罪主張も撤回すべきでせう →検察側が有罪主張を撤回か　滋賀・患者死亡の再審協議：朝日新聞デジタル https://t.co/oka2wZ9XHg
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-05 21:46／2019/10/01 18:28 URL： https://twitter.com/kk_hirono/status/1191698405036216321 https://twitter.com/hirono_hideki/status/1178964770805780486
> 弁護士の弁護権の濫用による一層の混迷 ― 千葉ゴルフ場鉄塔崩壊事件 ―：データ・マックス NETIB-NEWS https://t.co/tmXwMHVmgR
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2019年10月01日 - Twilog https://t.co/mEqwPd9d6O

　前日の10月1日だったと確認しましたが、やはり湖東記念病院の再審に関するツイートがありました。Twilogで確認できる範囲ですが、先にジャーナリストの江川紹子氏のツイートのリツイートがありました。このリツイートで初めて知ったニュースだったのか否かの記憶はありません。

　次に非常上告-最高検察庁御中_ツイッター（@s_hirono）のスクリーンショットの記録として、Twilogを確認しておきたいと思います。余り事細かに記すのもどうかと思いますが、私個人としても歴史的な発見がそこにあったので相応の意義があるかと思います。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-05 21:56／2019/10/01 21:31 URL： https://twitter.com/kk_hirono/status/1191700748981153793 https://twitter.com/s_hirono/status/1179010948691922944
> 2019-10-01-202501_ʇɐɯɐɹnɯʞ@kmuramatsu·3h実の娘と性交、父親に懲役9年判決　中学生の頃から常習：朝日新聞デジタル.jpg https://t.co/Gkx7Y8Sfta
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-05 21:55／2019/10/01 21:30 URL： https://twitter.com/kk_hirono/status/1191700683780526080 https://twitter.com/s_hirono/status/1179010804651188224
> 2019-10-01-195406_Shoko　EgawaさんはTwitterを使っています：　「愛知県は、電凸攻撃対策として、あいちトリエンナーレについての意見は、担当部局でのみ受け、最初.jpg https://t.co/lECb9K3Y1q
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-05 21:55／2019/10/01 21:30 URL： https://twitter.com/kk_hirono/status/1191700635416027136 https://twitter.com/s_hirono/status/1179010732756623360
> 2019-10-01-195348_Shoko　EgawaさんはTwitterを使っています：　「@rin0rin0rin0rin　検証委員会を作ってよかったですね」　／　Twitter.jpg https://t.co/vnfPwxlIel
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-05 21:55／2019/10/01 21:30 URL： https://twitter.com/kk_hirono/status/1191700559037775873 https://twitter.com/s_hirono/status/1179010660807499776
> 2019-10-01-182924_＼ShokoEgawa　@amneris84＼ShokoEgawa@amneris84·11h新たな有罪立証を断念。ならば、早く有罪主張も撤回すべきでせう.jpg https://t.co/2pqZUrqQun
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-05 21:55／2019/10/01 21:29 URL： https://twitter.com/kk_hirono/status/1191700480969150464 https://twitter.com/s_hirono/status/1179010442057801729
> 2019-10-01-115111_江川紹子による考察…「大崎事件再審棄却」から見えた「人権救済を阻む砦」と化す最高裁への危惧　｜　ビジネスジャーナル.jpg https://t.co/1tdWWRQLYN
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-05 21:55／2019/10/01 21:29 URL： https://twitter.com/kk_hirono/status/1191700451877539840 https://twitter.com/s_hirono/status/1179010369815072770
> 2019-10-01-093707_深澤諭史@fukazawas·19m愛知トリエンナーレの件で、この記事のことを思い出した。みなさん、忘れないでね！（・∀・）（＾ω＾）.jpg https://t.co/X4R7gVikx2
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 非常上告-最高検察庁御中_ツイッター(@s_hirono)/2019年10月01日 - Twilog https://t.co/8kvWyGoEv1

```
有料会員限定記事

比嘉展玖（ひらく） 安藤仙一朗 2019年9月30日23時49分

［source：］検察側が有罪主張を撤回か　滋賀・患者死亡の再審協議：朝日新聞デジタル https://www.asahi.com/articles/ASM9Z61QQM9ZPTJB013.html
```

　2019年9月30日23時49分が配信時刻の記事だったと確認しました。11分で日付が変わる時間ということもありますが、やはり私がこのニュースを初めて知ったのは日付が変わった10月1日の可能性が高いと思います。

　上記の朝日新聞デジタルの有料記事は「残り：568文字／全文：1187文字」となっています。以前の朝日新聞デジタルは、会員登録をすることで月に3本だったか有料記事の全文を読むことが出来て、何度か利用したことがありましたが、現在はそれらしい情報もページに見当たりません。

　上記の朝日新聞デジタルの記事には小さな写真があって下に「記者会見する西山美香さん（左）と井戸謙一弁護団長＝２０１９年９月３０日午後、大津市、比嘉展玖撮影」という記載があります。満足そうな井戸謙一弁護士の姿があって、まるで正義の味方ということから、黄金バットを連想しました。

　黄金バットをネットでGoogle検索したところ、動画がいくつかあってアニメのものと実写版の映画のようなものがありました。私の記憶にあったのはテレビアニメのものであったと思いますが、物心がついた頃の古い記憶で、はっきりテレビで見たという記憶も残っていません。

　黄金バットのテーマ曲というのも、聞いたことのある特徴的な曲ですが、よくあるバラエティ番組での懐かしいテレビ番組の紹介で黄金バットを見たという記憶はありません。幼い頃の記憶に残っていた曲なのだと思います。

　また、ネットでの黄金バットのアニメの動画は、その全てがカラーのきれいな映像となっていました。昭和40年代、それも前半というのはカラーテレビというのはあったとしてもかなり珍しいものであったと思います。身近なところでの記憶ですが、テレビがないという家庭もあったかもしれません。

```
1967年（昭和42年）4月1日から1968年（昭和43年）3月23日まで、アニメ版がよみうりテレビ (ytv) の企画・制作により日本テレビ系列で毎週土曜日19時 - 19時30分に全52話が放映され、高視聴率を得た。

［source：］黄金バット - Wikipedia https://ja.wikipedia.org/wiki/%E9%BB%84%E9%87%91%E3%83%90%E3%83%83%E3%83%88
```

　上記の『ウィキペディア（Wikipedia）』の引用は、黄金バットのテレビでの放送時期を確認したもので、昭和42年4月1日から昭和43年3月23日まで、とあります。私の生まれが昭和39年11月26日なので、まだ記憶がしっかりしていなかったという時期とも一致すると思います。

　今回の確認のために検索で、気になったのは次の引用部分になります。

```
1930年（昭和5年）、鈴木一郎原作で白骨面に黒マントの怪盗が活躍する街頭紙芝居シリーズ『黒バット』が好評だったことから、主人公を黄金色にした絵19枚を永松健夫が描いて誕生した。『黒バット』の最終回で、無敵で不死身の悪役である黒バットを倒す正義のヒーローとして突如、初登場した。

この黄金バットが子供たちに大好評だったため、黄金バットを主人公とした新作紙芝居を蟻友会の後藤時蔵、高橋清三、田中次郎らが製作。当時の驚異的な当たり演目となる。しかし当時の零細な紙芝居業界に著作権意識は存在しなかったため、多種多様な黄金バットが勝手に作られた。さらに当時はセリフは書かれておらず口伝だったため、同じ紙芝居でも演者によって内容に差異があるのが普通だった。なお、戦前の『黄金バット』の紙芝居のほとんどは戦時下の混乱にあって散逸、あるいは戦災により焼失したとされる。当時の紙芝居は貸し出し式だったため倉庫にまとめて保管されており、倉庫が火事に遭うと全て燃えてしまっていた。また、手書きで写し描きされていたので製作数が少なく、人気作は損耗も激しかった。

［source：］黄金バット - Wikipedia https://ja.wikipedia.org/wiki/%E9%BB%84%E9%87%91%E3%83%90%E3%83%83%E3%83%88
```

　口伝の紙芝居とあります。紙芝居というのは昭和40年代の記憶として残っているのですが、たぶんテレビでみた情報で、実際に紙芝居を見ることはなかったか、あったとしても定かではないかすかな記憶です。

　けっこう前から構想していたことですが、この黄金バットについては、井戸謙一弁護士や再審事件に絡めて取り上げる予定でした。滋賀県の湖東とありますが、その辺りはヤンマーディーゼルの天気予報のCMとも関連づいて記憶が形成されています。

　前に少し取り上げたことがあると思いますが、滋賀県の優水化成からイクラを入れると聞いたプラスチック容器を積み込んで札幌市に行ったという運行がありました。これがヤンマーディーゼルの天気予報のCMの記憶とも関連づいています。

[link:] » ゆうすいかせい - Google 検索 https://t.co/ZTxp18mlwD

　Linuxのmozcで日本語変換ができなかったので、ひらがなでGoogle検索をしましたが、優水化成工業株式会社として、石川工場（羽咋郡宝達志水町）、滋賀工場（草津市）という情報が検索結果に見えます。

　なお、この滋賀県から札幌市の運行というのは昭和60年の秋のことだったと思います。別の経験で10月の中頃に札幌市で雪が降るということがあったのですが、その運行のときは雪の心配をしていなかったと思うので、9月中という可能性があるとも思います。

　その運行には結婚する前の前妻を同乗させていましたが、札幌市内で観光を兼ねてゆっくりするつもりが、荷降ろしを終えてすぐに帰り荷が決まり、千歳市ではなかったかと思いますが、ポテトチップスの敷地の大きな工場か倉庫から秋田市行きのポテトチップスの荷物を積みました。

　23時ころとも思いますが、小樽港でフェリーを降りたのと同じ日に、函館港から中西運輸商の社長が指定したフェリーに乗船したのですが、まるで幽霊船のような大きなボロ船だったのが強く印象に残っています。トラックから一歩も出ることなく、翌朝に青森港で下船しました。

　その幽霊船のような大きなボロ船は、砂利の運搬船のようなものであったかもしれません。通常のフェリーとは全く違うものでした。とにかく異様な光景として強く印象に残っており、その不思議な存在感が、幼い頃の黄金バットの記憶とも強く結びついているのかと思います。

　カルビーだったとも思いますが、ポテトチップスを積み込んだ北海道の場所というのも、強く印象に残る記憶で、同じ日の幽霊船とはまるで違って、アニメの漫画に出てくる大金持ちの邸宅とそれを囲む広大な公園の敷地という風景でした。当時はまだポテトチップスは他社の競合がなかったとも思います。

　優水化成で滋賀県の工場からの仕事はその1回だけだったと思います。他は全て当時の羽咋郡押水町の工場からの仕事でした。春は東北方面への建築資材の仕事がけっこう続いてありました。他に印象的だったのは、北九州市内の釣具店に魚箱を運んだ仕事でした。

　羽咋郡押水町の優水化成の仕事は、建築資材を含め全てが発泡スチロールの製品だったと思います。滋賀県の工場で積み込んだ荷物だけが発泡スチロールではないプラスチックの容器でした。ホームセンターで道具入れとして売られているものに似ていましたが、色は青系だったと思います。

　パソコンの時計を見るとちょうど23時でした。日付が変わっているのかもしれないと時刻を確認しました。日付が変わっていないので、今夜と昨夜になりますが、どちらも宇出津新港のアルプに買い物に行くときに、記録資料として宇出津上田町などの写真を撮影しました。

　すでに非常上告-最高検察庁御中_ツイッター（@s_hirono）に画像つきツイートとして投稿済みかと思いますので、このあとリツイートとしてご紹介します。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-05 23:07／2019/11/05 21:00 URL： https://twitter.com/kk_hirono/status/1191718720885780481 https://twitter.com/s_hirono/status/1191686614667292672
> 2019-11-04_190518＿宇出津上田町　辺田の浜方面　陸橋とトンネル.jpg https://t.co/A8iouGSxtz
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-05 23:07／2019/11/05 21:00 URL： https://twitter.com/kk_hirono/status/1191718601721446401 https://twitter.com/s_hirono/status/1191686693276880896
> 2019-11-04_190611＿宇出津上田町　辺田の浜へのトンネル手前.jpg https://t.co/eNBNjYeatD
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-05 23:07／2019/11/05 21:00 URL： https://twitter.com/kk_hirono/status/1191718570578698242 https://twitter.com/s_hirono/status/1191686771152547841
> 2019-11-04_190814＿宇出津新港　アルプ.jpg https://t.co/69IOsh7UIx
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-05 23:06／2019/11/05 21:01 URL： https://twitter.com/kk_hirono/status/1191718537091399680 https://twitter.com/s_hirono/status/1191686852333297665
> 2019-11-04_191251＿宇出津新港アルプ店内　福岡県山川みかんの箱.jpg https://t.co/Mo2STyQViR
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-05 23:06／2019/11/05 21:01 URL： https://twitter.com/kk_hirono/status/1191718515599757319 https://twitter.com/s_hirono/status/1191686931513393153
> 2019-11-04_193526＿宇出津港　大竹町辺りから能登町役場方面.jpg https://t.co/v15SCJNNl1
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-05 23:06／2019/11/05 21:01 URL： https://twitter.com/kk_hirono/status/1191718492673724417 https://twitter.com/s_hirono/status/1191687009716191237
> 2019-11-05_184219＿宇出津仙人町　長楽寺前の道路　上田町方面.jpg https://t.co/o9N4C6MeeB
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-05 23:06／2019/11/05 21:01 URL： https://twitter.com/kk_hirono/status/1191718457277964289 https://twitter.com/s_hirono/status/1191687094541918208
> 2019-11-05_184417＿宇出津上田町　陸橋の上からトンネル手前、辺田の浜方面.jpg https://t.co/bEmmtmTNLs
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-05 23:06／2019/11/05 21:02 URL： https://twitter.com/kk_hirono/status/1191718437866725376 https://twitter.com/s_hirono/status/1191687173549907970
> 2019-11-05_184605＿能都中学校（旧宇出津高校）の坂の上から宇出津新港方面の夜景.jpg https://t.co/WxVyIt7kPY
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-05 23:06／2019/11/05 21:02 URL： https://twitter.com/kk_hirono/status/1191718414353436672 https://twitter.com/s_hirono/status/1191687249991045120
> 2019-11-05_184728＿能都中学校（旧宇出津高校）の坂、宇出津方面トンネル手前　夜.jpg https://t.co/pbusOeoxny
▶▶▶　　　　　End　　　　　▶▶▶

　今夜撮影した上田町の陸橋には、金網のような形状の頑丈そうなフエンスがありましたが、いつの間にできていたものか今回初めて気が付きました。同じ場所からの昼の撮影は前にもあったと思いますが、夜の撮影は今回が初めてになったと思います。

　幼い頃の黄金バットの記憶があるのも、たぶん似たような季節の同じような時間帯だったと思います。夜にその辺りにいるというのも夏のクワガタムシ、カブト虫採りを別にすれば珍しいことでした。

　宇出津上田町のトンネルの先が辺田の浜になります。このトンネルもいつの間にか改修され現在のものとなっていると思いますが、以前はもっと暗くて狭い古いトンネルで、小さい頃に母親と二人でトンネルの中を歩きながら、ずいぶん怖い思いをしたという記憶があります。

　横に歩行者用の大きなトンネルがありますが、これも辺田の浜に住んでいる頃に完成していたと思います。しかし、母親と一緒にこのトンネルを歩いたという記憶は残っておらず、さらに不思議でならないのが、工事をしていたという記憶が全く残っていないことです。

　半月ほど前になりますか、その歩行者用のトンネルをバイクを押しながら歩いて、完成時の年月を記録したプレートがないか探したのですが、見当たりませんでした。その時、意外な発見となったのが防犯カメラで、3箇所はあったと思います。

　今夜、宇出津新港のアルプに買い物に行ったのは、どんたく宇出津店のポイント3倍デーだったのが大きいです。オリーブオイルなど日持ちする食品をまとめ買いしておこうと思いました。今夜もそうだったのですが、けっこう寒くて宇出津新港まで買い物に行くのは、段々と躊躇われる時期となっています。

　そして、家に戻ってまもなく見たのが、秋重実弁護士のタイムラインで、そこに気になるブログ記事の紹介がありました。元検事による回想録のような記事で、完結はしていませんでしたが、母親と怖い思いで古いトンネル内を歩いたことも重ねて、これまでの弁護士鉄道の歩みを振り返る思いがありました。

〈〈〈：Emacs： 2019-11-05（火曜日）23：32 　〈〈〈

* 「あれは三年前　止める　時効」という戸舘圭之弁護士のツイート
  CLOCK: [2019-11-06 水 00:08]--[2019-11-06 水 01:45] =>  1:37

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 戸舘圭之弁護士,時効,再審請求,袴田事件

〉〉〉：Emacs： 2019-11-06（水曜日）00：08　 〉〉〉

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜todateyoshiyuki（弁護士　戸舘圭之） 日時：2019-11-06 00:09／2019/11/05 20:46 URL： https://twitter.com/kk_hirono/status/1191734227726823425 https://twitter.com/todateyoshiyuki/status/1191683265964335104
> あれは三年前 止める 時効 https://t.co/fcTiMo1QUL
▶▶▶　　　　　End　　　　　▶▶▶

　３ｈつまり3時間前として表示されていますが、さきほど見かけた戸舘圭之弁護士のツイートになります。昭和40年代後半の曲として思い出し、すぐに検索して視聴したのが次のYouTube動画になります。

[link:] » ちあきなおみ／喝采　1972年 - YouTube https://t.co/ZCjHeQyXQQ

　タイトルをみると昭和47年の曲のようですが、思っていたより少し古いと感じました。昭和49年あたりと思っていたのですが、テレビでよく見かけかなり印象に残る曲でした。平成8年辺りかと思いますが、最近は余り見なくなったコロッケという芸人がモノマネをしていたという印象もあります。

　戸舘圭之弁護士のツイートを見たのがきっかけになりますが、けっこう驚いたのが「14,497,544 回視聴•2013/09/13」という視聴回数です。当時の世相を反映したような懐かしい曲ですが、私としては小学生だったので、さほど強い思い入れはありませんでした。

　戸舘圭之弁護士は、けっこう若い世代という印象で、30代半ばから40代前半と思っていたので、喝采の曲の歌詞を知るのは意外に感じていました。動画の視聴をして再びツイートを見ると、次のツイートを公式引用していることに気が付き、そこのは曲名が明示されていました。

parasiteillegal ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW parasiteillegal（パラサイトイリーガル） 日時：2019/11/05 20:41 URL： https://twitter.com/parasiteillegal/status/1191681932955807745
> それでは聴いてください \n ちあきなおみ \n 決済
▷▷▷　　　　　End　　　　　▷▷▷

　見かける頻度は少ない見覚えのあるアカウントと思いましたが、ブロックされていることを確認しました。パラサイトリーガルとプロフィールの名前にありますが、パラサイトの意味がはっきり思い出せないものの、一頃流行った言葉で、寄生虫という意味であったような気がします。

　あらためてツイートを見ると、喝采という曲名はないですが、歌い手の「ちあきなおみ」という名前が明示されています。

　ツイートを個別に開いても流れがなく、いきなり単発のツイートですが、まとめ記事を作成したので、これから少し眺めておきたいと思います。

[link:] 2019年11月06日00時25分の登録： ＼パラサイトイリーガル　@parasiteillegal＼それでは聴いてください\nちあきなおみ\n決済 http://hirono2014sk.blogspot.com/2019/11/parasiteillegal.html

29件目 ￼戻る （リツイート）： parasiteillegal（パラサイトイリーガル）｜eru19721103（小西　憲臣） 日時：2019-11-04 17:27／2019-11-04 16:48 URL： https://twitter.com/parasiteillegal/status/1191270766886572032 https://twitter.com/eru19721103/status/1191260858204057600
{% tweet 1191270766886572032 %}
> 依頼者が漁師だと「海が荒れて漁が休みにならないと打ち合わせに行けません。当日の朝、わかったら連絡します。」と言われる。そこで、私の予定がない日に漁が休みとなるよう、海の神に祈祷を捧げることになる。

　喝采や、ちあきなおみ、に関係のありそうなツイートは見当たらなかったですが、リツイートとして気になったツイートを発見したのが上記になります。見覚えのあるアカウントとして確認すると、プロフィールに北海道釧路市の弁護士、とありました。リツイートできるかやってみます。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜eru19721103（小西　憲臣） 日時：2019-11-06 00:34／2019/11/04 16:48 URL： https://twitter.com/kk_hirono/status/1191740677916200960 https://twitter.com/eru19721103/status/1191260858204057600
> 依頼者が漁師だと「海が荒れて漁が休みにならないと打ち合わせに行けません。当日の朝、わかったら連絡します。」と言われる。そこで、私の予定がない日に漁が休みとなるよう、海の神に祈祷を捧げることになる。
▶▶▶　　　　　End　　　　　▶▶▶

```
小西　憲臣
@eru19721103
北海道釧路市の弁護士です。釧路弁護士会所属。不摂生のため右の耳が聞こえません。身内に障がい者がいます。そんなこんなで、そろそろ障がい者の問題とも向き合わないといけないのだろうかと思い始めた年頃（４０代後半）です。
2017年1月からTwitterを利用しています
620 フォロー中
594 フォロワー

［source：］(1) 小西　憲臣（@eru19721103）さん / Twitter https://twitter.com/eru19721103
```

　北海道釧路市の弁護士です、という部分は記憶にあったのですが、それに続く障がい者（障害者）の部分は、よく読んでいなかったように思います。Linuxのmozcで変換が出来なかったですが、「障がい者」と一部がひらがなにされています。

　釧路市は司法修習地として法クラの一部に熱烈な人気があるとツイートで見かけてきましたが、弁護士業務として裁判所の管轄地域もずいぶん広いものと考えられます。私は昭和59年の7月に一度、根室市の花咲港に行ったことがあり、夕方の早めの時間帯に釧路市内を通過しました。

　富山県の魚津市と黒部市の間にある経田漁港からサケマス漁の網を積んで向かったのですが、花咲港は北洋のサケマス漁の基地のようになっていて、小木港の漁船も多数いたのではと思います。花咲港のことは遠洋漁船の友人知人によく話を聞いていました。

花咲港 / 川中美幸 ： 네이버 블로그 http://blog.naver.com/PostView.nhn?blogId=dididisu&logNo=221022667108

　検索すると上記のページが見つかったのですが、埋め込みの動画に曲の歌詞がついているのも珍しいと思ったところ、日本語とハングルと思われる韓国語が一緒になっていて、これは初めて見たことです。

　ハングル文字を見てすぐに思い出したのが、「釜山港に帰れ」という曲ですが、ちょうど昭和58年の1月から3月頃に「氷雨」や「居酒屋」とともに流行していた曲で、カラオケでよく歌われていました。

[link:] » 渥美二郎 釜山港へ帰れ 歌詞&amp;動画視聴 - 歌ネット https://t.co/dNj5GtOt1C

　さきほどと同じように検索をしてすぐに、動画と歌詞付きのページが出てきました。ハングル文字はみあたらないですが、動画の冒頭に昭和58年とアナウンスが出てきたので、さきほど昭和57年としたのが間違いだと気が付き、訂正をしました。

　釧路や根室といえば、地図で見て網走が近くにあり、網走刑務所が有名で観光地にもなっているようですが、2,3日前、深澤諭史弁護士のツイートがきっかけで、ニポポという曲を久しぶりに聴くことがありました。YouTubeの動画ではなかったので、探しても見つからなかったようです。

　そのときに初めて知ったように思ったのですが、ニポポは網走刑務所で受刑者が手作りをしている民芸品とのことでした。深澤諭史弁護士のツイートを見ているときに「空はでかい俺の屋根」という歌詞を思い出し、曲名がわからないまま調べたのですが、「ワッパ人生」という曲名でした。

　深澤諭史弁護士のTwitterタイムラインは、相変わらず、弁護士提灯行列の弁護士音頭といった有様です。前にも書いていると思いますが、ゲゲゲの鬼太郎の「夜は墓場で運動会」にも似ています。このゲゲゲの鬼太郎の曲も、昭和40年代後半にテレビで見ていたという記憶です。

```
寄生生物。寄生虫。寄生植物。居候 (いそうろう) 。厄介者。

［source：］parasite（パラサイト）の意味 - goo国語辞書 https://dictionary.goo.ne.jp/jn/179774/meaning/m0u/
```

　パラサイトについてネットで調べたところ、上記のgoo国語辞書に、寄生生物、寄生虫の他、居候、厄介者とありました。gooのサイトを見たのも久しぶりですが、すっかり忘れていました。サービスが良かったものの10年ほど前にパスワードを忘れログインできなくなったgooのブログもあります。

　弁護士の業界でよく見るのがイソ弁で、居候弁護士を意味するとのことです。これはネットが普及する前から本で見てきた言葉でした。冷遇され、酷使されているという愚痴混じりのツイートばかりを見かけている印象ですが、寄生となると立場が逆にもなりそうです。

　しかし、戸舘圭之弁護士のツイートの、「喝采」と「時効」というのは意外な組み合わせでした。数日前から殺人事件の公訴時効の撤廃についても思い出しながら色々と考えていたのですが、オウム真理教の事件で一家殺害となった坂本弁護士が、宇都宮弁護士の事務員だったと知りました。

　ジャーナリストの江川紹子氏の記事で、それも落合洋司弁護士（東京弁護士会）のツイートから記事を開いて読んだという経緯があって、いろいろと記しておきたいことがあったのですが、あれもこれもとなかなか手がつきません。モトケンこと矢部善朗弁護士（京都弁護士会）の保留もあります。

〈〈〈：Emacs： 2019-11-06（水曜日）01：45 　〈〈〈

