#+TITLE: "新潟市西区女児殺害事件小林遼被告"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-11-23 17:48:49 +0900
FILE_NAME: 2019-11-23-174849_新潟市西区女児殺害事件小林遼被告.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 新潟地裁,新潟市西区女児殺害事件小林遼被告,村松謙弁護士,霞司郎,深澤諭史弁護士
記事タイトル名の文字数：16　保存ファイル名の文字数：38
#+STARTUP: showeverything


* 村松謙弁護士の「霞裁判官をブロック」というツイート、１７時間前を目途に遡った霞司郎のタイムラインでの発見：新潟市西区女児殺害事件小林遼被告
  CLOCK: [2019-11-24 日 09:33]--[2019-11-24 日 14:14] =>  4:41
  CLOCK: [2019-11-23 土 17:55]--[2019-11-24 日 09:33] => 15:38

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 新潟地裁,新潟市西区女児殺害事件小林遼被告,村松謙弁護士,霞司郎,深澤諭史弁護士

〉〉〉：Emacs： 2019-11-23（土曜日）17：55　 〉〉〉

　もともとこの問題は午前中に深澤諭史弁護士のタイムラインで本人のツイートを中心に見かけていたもので、深澤諭史弁護士を軸にするのか取り上げ方に迷いがありました。

　今のところ直接の関係は確認していないのですが、村松謙弁護士のタイムラインで本人のツイートとして見かけたツイートがきっかけで、１７ｈという１７時間前の時間帯を目途に霞司郎のタイムラインを遡ったもので、そこでの発見に、より具体的な情報と深澤諭史弁護士のツイートを発見しました。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kmuramatsu（ʇɐ） 日時：2019-11-23 18:05／2019/11/23 00:10 URL： https://twitter.com/kk_hirono/status/1198165643998060544 https://twitter.com/kmuramatsu/status/1197895125185122305
> 霞裁判官をブロック
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-23 18:09／2019/11/23 18:07 URL： https://twitter.com/kk_hirono/status/1198166571249627136 https://twitter.com/s_hirono/status/1198166068025384960
> 2019-11-23-171732_霞司郎@kasumi_shiro·11月22日ブラックジャックはおよそ現実にあり得ない話で、純粋に虚構として楽しめますが、非弁はそうではありませんからね….jpg https://t.co/WkfWSg6Mvj
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-23 18:09／2019/11/23 18:06 URL： https://twitter.com/kk_hirono/status/1198166547195252737 https://twitter.com/s_hirono/status/1198165995170349056
> 2019-11-23-171545_霞司郎@kasumi_shiro·20h裁判所からこういう言葉を引き出してしまったのは本意ではないでしょうね。.jpg https://t.co/oNua3rVxUw
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-23 18:08／2019/11/23 18:06 URL： https://twitter.com/kk_hirono/status/1198166525926002688 https://twitter.com/s_hirono/status/1198165921757450240
> 2019-11-23-171331_霞司郎@kasumi_shiro·17h「弁護士に頼んでも食い物にされるだけ。本当に味方になってくれるのは『街の法律家』だよ」というメッセージを伝えるポス.jpg https://t.co/0L8g7Z7vOB
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-23 18:08／2019/11/23 18:06 URL： https://twitter.com/kk_hirono/status/1198166388772229121 https://twitter.com/s_hirono/status/1198165847128150017
> 2019-11-23-171204_霞司郎さんがリツイートエンリケ航海玉子@kd_ixi·8h「その瞬間、法廷内に緊張感が走り、空気も張り詰めたとのこと。」じゃなくてその場で異議….jpg https://t.co/pFUyu8u4mN
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-23 18:08／2019/11/23 18:05 URL： https://twitter.com/kk_hirono/status/1198166365955248129 https://twitter.com/s_hirono/status/1198165774839336961
> 2019-11-23-171108_霞司郎さんがリツイート深澤諭史@fukazawas·7h【前田恒彦さんのコメント】「あなたにできる最低限の償いは真実を述べることだと思いますが、真実を述べ.jpg https://t.co/4J1zEoxeg4
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-23 18:08／2019/11/23 18:05 URL： https://twitter.com/kk_hirono/status/1198166336792190976 https://twitter.com/s_hirono/status/1198165702043033600
> 2019-11-23-171026_霞司郎@kasumi_shiro·6h裁判長は知っている人で、おそらく極刑を回避する可能性を残したいとの心情から出てしまったのかなと思いますが、それにして.jpg https://t.co/nDUoPkoHlp
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-23 18:07／2019/11/23 18:05 URL： https://twitter.com/kk_hirono/status/1198166217648771072 https://twitter.com/s_hirono/status/1198165629049565185
> 2019-11-23-170919_霞司郎さんがリツイート深澤諭史@fukazawas·6h裁判員裁判の人民裁判化が、順調に進行してるな、、、。.jpg https://t.co/dvMnWr8opp
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-23 18:07／2019/11/23 18:05 URL： https://twitter.com/kk_hirono/status/1198166195918106624 https://twitter.com/s_hirono/status/1198165555145924608
> 2019-11-23-170809_霞司郎さんがリツイート深澤諭史@fukazawas·6h裁判員裁判の人民裁判化が、順調に進行してるな、、、。.jpg https://t.co/1rwlAg0qBp
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-23 18:07／2019/11/23 18:04 URL： https://twitter.com/kk_hirono/status/1198166171335282688 https://twitter.com/s_hirono/status/1198165481686851584
> 2019-11-23-170737_霞司郎@kasumi_shiro·5hあるいは、休廷中に裁判員から「裁判長！このままでいいんですか？」等と言われたとか？（´～｀）.jpg https://t.co/QOR0kUfwqp
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-23 18:07／2019/11/23 18:04 URL： https://twitter.com/kk_hirono/status/1198166102561288192 https://twitter.com/s_hirono/status/1198165409272193024
> 2019-11-23-170120_ʇɐ@kmuramatsu·16h霞裁判官をブロック.jpg https://t.co/dBRVycPRgq
▶▶▶　　　　　End　　　　　▶▶▶

　村松謙弁護士のツイートは本日１１月２３日の０時１０分となっていました。深澤諭史弁護士のツイートの時刻はまだ確認をしていませんが、霞司郎のタイムラインで新潟地裁の死刑求刑に関するものはいくつか後のツイートやリツイートになっていました。

　昨夜、Twitterのトレンドで「死刑求刑」というワードを見かけていたのですが、今考えると自分でも不思議なほど関心がわかず、リンクを開くこともありませんでした。

　昨夜は珍しく２３時３０分ころに布団に入って眠りました。朝方の暗い時間に目が覚め、時刻は５時４０分ぐらいでしたが、３０分から小一時間ぐらいで二度寝をして、次に目が覚めたのは１０時半ぐらいになっていました。久しぶりに起きた時間が遅く、寝ていた時間も長かったです。

　５時４０分ころに目が覚めた時、そのまま起きてパソコンを始めることも考え、実際にそうすることも少なくないのですが、今日は１０時半頃まで寝ていたので、パソコンで深澤諭史弁護士らのツイートを確認するのも、普段より遅くなったという次第です。

　一日に何度も確認するのが深澤諭史弁護士とモトケンこと矢部善朗弁護士（京都弁護士会）のTwitterタイムラインです。そこで昨夜Twitterのトレンドにあった死刑求刑が、新潟市西区女児殺害事件の刑事裁判だったのだと初めて知りました。

　新潟市西区女児殺害事件は初公判も数日前のニュースとなっていたと思うので、死刑求刑は予想外に早く感じました。通常、求刑は判決前の結審で行われるはずですが、過去にも死刑求刑となるような重大事件では、検索の求刑の数日後に弁護人の再審弁論が指定されたような気もします。

　新潟市西区女児殺害事件の関連ニュースには弁護人の主張もありましたし、最終弁論とはなかったですが懲役１０年あるいはそれ以下という量刑意見も述べられていたようです。判決は１２月４日ともなっていたと思いますが、記憶に自信は持てず、確認を要します。

　ネットでは新潟市西区女児殺害事件の刑事裁判での死刑求刑が昨日２２日の１４時過ぎにニュース記事が配信となっていましたが、テレビに集中していなかったもののミヤネ屋にその放送はなかったように思います。

　このあと確認をする予定ですが、NHKのNEWS７でも新潟市西区女児殺害事件の刑事裁判での死刑求刑は、少なくとも番組冒頭のニュースの項目にはなかったと思います。

　深澤諭史弁護士のタイムラインをみながら、昨夜のテレビのことを考えたのですが、すぐには思い出せなかったものの、昨夜は普段と違うテレビの視聴をしていたことを思い出しました。最初はちょっとみるつもりだったのですが、４時間の番組を最後まで視聴することになりました。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-23 18:40／2019/11/22 20:44 URL： https://twitter.com/kk_hirono/status/1198174400492621824 https://twitter.com/hirono_hideki/status/1197843193456250880
> 池上彰×サザエさんスペシャル　お茶の間ニッポン史50の解説でございま～す!  2019年11月22日（金）  19時00分～22時52分  の放送内容 https://t.co/2sTCf6olz3
▶▶▶　　　　　End　　　　　▶▶▶

〈〈〈：Emacs： 2019-11-24（日曜日）09：33 　〈〈〈

〉〉〉：Emacs： 2019-11-24（日曜日）09：33　 〉〉〉

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-24 09:47／2019/11/24 09:46 URL： https://twitter.com/kk_hirono/status/1198402703828779008 https://twitter.com/s_hirono/status/1198402478951170048
> 2019-11-22_185007＿テレビの画面・会場　石川県柳田　星の観察館「満天星」.jpg 2019-11-22_190020＿テレビの画面・NEWS７・ニュース６項目.jpg 2019-11-22_193630＿テレビの画… https://t.co/6hBIzKscKi
▶▶▶　　　　　End　　　　　▶▶▶


　長い時間、中断をしていました。上記の写真をスマホから取り込む作業で中断となりましたが、そのあと夕食の支度にも取り掛かったかもしれません。今季初のタラ汁を作っていました。輪島のタラのアラでどんたく宇出津店で２９８円でした。鮮度がとてもよかったです。

　気になったのは昨日の午後に行ったどんたく宇出津店で、香箱ガニもズワイガニも全く売っていなかったことです。昨日はコタツも出したのですが、用事を兼ねた買い物に出かける直前のことで、そのあとはまだ使っていません。そろそろ灯油も買ってこようと考えています。

　上記の３枚の写真付きツイートは、TwitterAPIを使わず、通常の投稿をしたものです。テレビのチャンネルを池上彰Xサザエさんの番組に変えたのは１９時３０分過ぎだったと確認しました。

　NHKのNEWS７で写真撮影の記録をしていたのは冒頭の項目紹介の部分だけでした。森友学園の籠池夫妻の刑事裁判のときも、冒頭の主要項目に掲載はなく、番組の後半以降でその他のニュースといった扱いでニュースがありました。

　１１月２２日は、NEWS７で主要項目の確認をしてまもなくチャンネルを変えたか、テレビからは離れたように思います。子を持つ親の立場から関心も高く、被害者が１人が微妙な線引きともなっている死刑問題で、報道がなかったとすれば気になるところです。

　そういえば、NEWS９の方も録画している可能性があるので、そちらを確認しておきたいと思います。NEWS７も同じく毎回設定をしていますが、容量不足の録画失敗が多いものの、数日前に消去で整理をしたように思います。

　２２日のNEWS７を録画再生で確認しました。「今日はご覧の項目でニュースをお伝えしています。次のニュースです。」という直後にロゴマークが移動するかたちで画面が切り替わり、「検察が死刑求刑　新潟　女児殺害」というニュースがありました。簡潔で短いニュースでした。

　弁護士らの異常性が全く伝わらないニュースで、疑問を感じました。最近は、死刑の執行のニュースでも簡単なもので終わっていますが、NHKも弁護士病に罹患・感染し、時空の歪みを生じているのかと考えてしまいます。この時空には弁護士鉄道の過去と未来があります。

　一方で、NHKが公共放送として、弁護士病の罹患・感染の拡大防止を重視しているとも。個人的には深澤諭史弁護士などをNEWS７やNEWS９に出演させて、言いたいことを言わせた方が、国民の知る権利と賢明な判断、選択に資することになり、弁護士鉄道の撤廃にもつながりそうです。

　今日は、大塚隆治弁護士についていろいろと発見がありました。平成６年に検事任官、平成１５年に弁護士になったという経歴ですが、深澤諭史弁護士や三浦義隆弁護士などいわゆる法クラとは、タイプも異なり、正統派に近い標準的な弁護士とも思えました。

　弁護士ドットコムのページで一枚の顔写真も見たところですが、これも以前見たことのあるような写真とは思いました。Twitterのアカウントも久しぶりにみたものでしたが、「おすすめのツイート」に表示されていたアカウントでした。

　アイコンが「大塚」と手書きのような字体で特徴的なのですが、２，３日前に何かで犬塚という名前を見たことを思い出し、気になったというのがタイムラインを開く誘引となりました。

　犬塚という名前をどこで見たのか思い出せないのですが、その時に思い出したのがNHKの人形劇「八犬伝」のことで、南総里見八犬伝がベースになっていると思います。遠い昔の記憶では、犬の字を名前に持つ人物が、選ばれたように集まったという物語だったと思います。

　NHKの人形劇「八犬伝」については、話の筋が全く理解できなかったということを憶えています。人形劇で紙芝居のようでもありましたが、いくらかそれに似た不思議な感覚で日々眺めているのが、法クラが寄り集まる深澤諭史弁護士のタイムラインです。

　そういえば、最近は深澤諭史弁護士のタイムラインで見かけていない気がしますが、Twitterのプロフィールにメツワカなどとする匿名弁護士のアカウントがありました。

　アカウントを取り違え、勘違いしたまま記憶していたのですが、その間違った方が次のアカウントになります。

```
⎳法律好きなVtuberじゃこにゃー
@Jakotsunya
弁護士ではない法律オタク！(元司法試験受験生、あと役に立たない法務博士)これからは趣味で法律好きなVtuberとして活動していくよ〜！絵は #じゃこアート Vtuberは趣味です。自分がやりたいこととみんなと楽しくできたら、それでいいかなぁと。チャンネル登録してくれると嬉しいな！ #VRアカデミア 所属
ウルタールyoutube.com/watch?v=CsgM7J…誕生日： 10月9日2012年9月からTwitterを利用しています
4,006 フォロー中
3,759 フォロワー

［source：］⎳法律好きなVtuberじゃこにゃー（@Jakotsunya）さん / Twitter https://twitter.com/Jakotsunya
```

　過去のスクリーンショットの記録を頼りにTwitterアカウントを見つけ出すことが出来ました。プロフィールも大きく変わりはないようです。

```
泥濘大魔王サイケ
@k_sawmen
地球を愛する普通の地球人。人類滅亡を企む悪の若手弁護士の会、略して「めつわか」の代表です。めつわかメンバーは随時募集中です。弁護士でなくても、めつわかに予備メンバーとして加入可能です。なお、アイコンは自撮りです。イカ：SW-7798-7656-0091
貴方のスマホの中2009年3月からTwitterを利用しています
767 フォロー中
1,297 フォロワー

［source：］泥濘大魔王サイケ（@k_sawmen）さん / Twitter https://twitter.com/k_sawmen
```

　これは「% locate 人類|xargs eog {}」というコマンドの実行で探し出しました。システム全体のファイル名の検索結果を、画像ビューアのアプリに渡し、まとめて開いています。矢印キーで画像の切替ができるので探すのも早いです。

　「地球を愛する普通の地球人。人類滅亡を企む悪の若手弁護士の会、略して「めつわか」の代表です。」とプロフィールにあります。アイコンは現在、比較的普通のものに変わっていますが、以前はかなり異様なものでした。

　最近は、ツイート自体を見かけたおらず、過去のツイートの内容も特に思い出すものがないのですが、そういえば「泥」でTwitterアカウントの検索を行った時、このアカウントは出ておらず、プロフィールの名前が変更されたか、アカウントが非公開か削除されたのかと考えました。

　そういえば、昨夜、足立啓太弁護士のTwitterアカウントが非公開設定になっていたことに気が付きました。

　現在のエントリーのタイトルを確認したところ、村松謙弁護士と霞司郎のことがありました。ずいぶんとそれていたことに気が付きましたが、ブロックというツイートがきっかけで、霞司郎のタイムラインを遡ったという経緯は、書き記すことができたと思います。

　そういえば、テレビでサンジャボが終わったようで、CMが続いていますが、今日のサンジャボの放送で、新潟女児殺害の死刑求刑は取り上げがなかったように思います。沢尻エリカの話題で、明後日に勾留期限を迎えると聞こえたように思います。弁護人の話はなかったような。

　アッコにおまかせ！が始まるはずと思っていたテレビで、女子駅伝が始まりました。最初に松島と出ていたと思いますが、そのあと出なくなりました。ちょうど１年ほど前にも、宮城県松島町をスタート地点とする駅伝の始まりをテレビで見かけたように思います。

[link:] » 2019年11月24日（日）クイーンズ駅伝 開催　松島～仙台間交通規制があります。｜新着情報｜松島センチュリーホテル（公式HP） https://t.co/yLkPNwZWxX

　コースが気になって確認したのですが、国道４５号線がコースになっていて塩釜市内も通過をするようです。金沢市場輸送の定期便では、石巻から塩釜の本社に立ち寄ることが多く、国道４５号線で松島の観光地を通過していました。津波の被害もあったので気になっていた場所です。

　過去の経歴を知らなかったマラソンの女子選手が、常習性の万引きで話題になっていたことを思い出し、そこから織田信成氏の提訴のニュースが、昨夜の土曜日と今日の午前中の情報番組で話題として見かけていなかったように思い出しました。

　織田信成氏に関しては、精神的に追い詰められたことは疑いがないものの、弁護士鉄道に搭乗したことで・・・明るい未来・・・問題解決が難しいように感じました。弱り目に祟り目、ともいいます。

　テレビにパナソニック、天満屋、日本郵政と並んだ表示がありました。なんのことかと思ったのですが天満屋というのは企業名のようです。

　まもなく山登りが始まります、とCMに入りましたが、松島と塩釜市内の間の国道４５号線に坂道があったという記憶はない、後に出来たバイパスの道路になるのかもしれません。松島の海岸線も少しテレビに映りましたが、昭和の頃とはずいぶん違った風景に見えました。

　なお、石巻だけで塩釜を立ち寄らない出発では、大和インターから東北自動車道に乗っていました。仙台南インターで降りていた記憶もありますが、山形自動車道が開通してからはそのまま山形県まで高速道路だったと思います。仙台市内の通行もなかったので非常に楽に感じていました。

　やはり海からずいぶん離れた山間部を現在の国道４５号線はルートとなっているようです。国道４５号線は地域の大動脈のような主要道だったと思いますが、それを通行止めにして駅伝が行われるというのも、別世界を垣間見たような驚きがありました。

　トンネルを抜けたところに、国道４５号線の道路標識が見えました。なにかと思い出のある国道の１つですが、記憶にあるのとはまるで違った道路になっています。やはりバイパスが出来た可能性がありそうですが、Googleマップで確認などはしていません。

　塩釜市内には、国道４５号線沿いでフェリー乗り場のようなところがあって観光客の賑わいも感じられていたと記憶にありますが、塩釜市内の海沿いというのはルートになっていない感じです。今、コースの表示がありましたが、港沿いの道路がコースになっていました。

　塩釜の港から仙台市内に向かって交差点を右折した角だったと思いますが、昭和５９年当時、角に近いところに１軒のトルコ風呂がありました。昭和６０年ころにはソープランドに改名していたはずですが、ソープランドの看板を含めその後のことは不思議と記憶にありません。

　考えてみると、昭和５９年当時でも、塩釜市内と仙台市内の間は、国道４５号線が、バイパスとは別になっていてバイパスの方は片側２車線以上になっていたと思います。旧道のような国道は少しだけ通行した気がしますが、多賀城市内で商店街のようなにぎわいもあった気がします。

[link:] » 第39回全日本実業団対抗女子駅伝競走大会 （クイーンズ駅伝）：日本陸上競技連盟公式サイト - Japan Association of Athletics Federations https://t.co/71bL3LMBDp

　上記のページにコースマップのリンクがありました。リンクはPDFファイルですが、ページタイトルが見たことのない記号で文字化けとなっています。拡大表示もできました。

　仙台市内の地図というのは余り見た記憶もないのですが、地図でみているとずいぶんややこしく感じました。久しぶりに仙台市の卸売市場のことも思い出したのですが、国道４号線に近かったと思う以外に場所が思い出せません。

　ソープランドといえば思い出すのは、山口県下関市で、下関の魚市場はその敷地、場内のようなところにソープランド街がありました。たまたま仕事に行った時に見かけたのですが、目を疑うような光景で、魚市場も賑わいがあって歴史のようなものも感じられたと記憶にあります。

　先日、下関市長発言を批判する法クラのツイートで、返信欄で見たけたようにも思うのですが、下関は日本で唯一、韓国の通貨が使える特別な地域性というツイートをみかけました。本当なのか情報の確認はしていないですが、まったく初めて知る話でした。

　下関市も金沢市場輸送の仕事で行くことが多かったのですが、驚いたのは関釜フェリーで、大きなフェリーの後ろの部分が港に向かう広い道路に迫り出しているようにも見えました。その横には大きな商業ビルがあったと思います。デパートで最上階にサウナがあり、一度入浴したことがありました。

　昨夜は、新潟女児殺害のことから、弁護士バッド→黄金バット→滋賀県→新潟県という流れで考え事をしたのですが、新潟から北海道の小樽港へのフェリーは、何度か乗船をしているものの、フェリー乗り場の場所や状況がほとんど何も思い出せなくなっていることに気が付きました。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜babel0101（anonymity） 日時：2019-11-24 14:00／2019/11/24 12:04 URL： https://twitter.com/kk_hirono/status/1198466299707289600 https://twitter.com/babel0101/status/1198437233214099457
> 突然だが、今ここで休廷し辞表を提出してくる、と言ってもらいたかった。それでもダメだと思うが。
▶▶▶　　　　　End　　　　　▶▶▶

　奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)ではブロックをされているアカウントであったように思います。そちらも確認をしておきましょう。

babel0101 ===> You have been blocked from retweeting this user's tweets at their request.
ブロックされているのでリツイートできませんでした。→　https://twitter.com/babel0101
▶ ブロックされたツイート％babel0101（anonymity）％2019/11/24 12:04％ https://twitter.com/babel0101/status/1198437233214099457
&twitter(1198437233214099457){theme:light}
> 突然だが、今ここで休廷し辞表を提出してくる、と言ってもらいたかった。それでもダメだと思うが。  
▶

　やはり奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)ではブロックを受けていました。深澤諭史弁護士のタイムラインで最新のツイートとして表示を見たもので、深澤諭史弁護士のリツイートになります。

RT fukazawas（深澤諭史）｜babel0101（anonymity） 日時：2019-11-24 13:21／2019-11-24 12:04 URL： https://twitter.com/fukazawas/status/1198456507496419329 https://twitter.com/babel0101/status/1198437233214099457
> 突然だが、今ここで休廷し辞表を提出してくる、と言ってもらいたかった。それでもダメだと思うが。

　個別に開いたツイートは単発となっていました。これもスクリーンショットで記録をしておきましょう。

　ブロックされていることを確認していたので、ある程度の注目はしていたはずですが、今回はプロフィールの内容に憲法ガールの著者などとあることに気が付き、調べたところ男性の実名弁護士であったことに気がつくという発見がありました。

　これは独立したエントリーで取り上げておく必要があります。

〈〈〈：Emacs： 2019-11-24（日曜日）14：14 　〈〈〈

