#+TITLE: "平成14年11月25日頃から平成21年3月15日まで石川県羽咋市釜屋のアパートでの生活"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-10-11 12:33:39 +0900
FILE_NAME: 2019-10-11-123339_平成14年11月25日頃から平成21年3月15日まで石川県羽咋市釜屋のアパートでの生活.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 羽咋市釜屋のアパートでの生活,えん罪,石川県警察
記事タイトル名の文字数：43　保存ファイル名の文字数：65
#+STARTUP: showeverything


* 金沢市粟崎でのひき逃げ死亡事故、えん罪の恐怖を感じた金沢東警察署からの連絡：平成14年11月25日頃から平成21年3月15日まで石川県羽咋市釜屋のアパートでの生活
  CLOCK: [2019-10-11 金 13:03]--[2019-10-11 金 14:05] =>  1:02

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 羽咋市釜屋のアパートでの生活,えん罪,石川県警察

〉〉〉：Emacs： 2019-10-11（金曜日）13：03　 〉〉〉

　時期にはっきりした記憶はないですが、羽咋市のアパートでの生活を始めてまだ日が浅く、気候が温暖な季節だったと思うので、平成15年の春頃の可能性が高いかと思います。

　羽咋市のアパートでの生活で新聞を購読したことは一度もなく、テレビも余り見なかったのですが、その金沢市粟崎でのひき逃げ死亡事故のことは少し知っていました。たぶんテレビのニュースで見ていたのだと思います。

　羽咋市のアパートは派遣会社の寮で、同居人との共同生活になると言われていたのですが、最後まで共同生活をすることはなく同居人の話が出たこともなかったと思います。

　2004年12月26日がインドネシアで大津波があったスマトラ島沖地震と確認したので、たぶんその年の8月いっぱいぐらいまで、派遣先は能登中核工業団地の工場でした。羽咋郡志賀町で志賀原子力発電所の近くになります。

　本社は茨城県にあって光ファイバーのケーブルを作る工場でした。最初の派遣先で、2004年が平成16年なので1年と9ヶ月ぐらい通っていたことになるのかと思います。

　毎日3時間の残業で、夜勤が多かったとも記憶にはあるのですが夜勤と日勤は交代になっていたかもしれません。確か4日出勤して2日休みというローテーションでした。工場自体は24時間のフル稼働だったように思います。

　細かいことは思い出せないですが、夜の20時半から朝の8時半までの勤務が、やはり多かったと記憶にあります。昼休みに外の車の中で弁当を食べたり、金沢地方検察庁のタウエさんに電話で話していたこともよく憶えているので、やはり夜勤と日勤は交代だったのだと思います。

　羽咋市の釜屋のアパートは、志賀町の方から来ると羽咋市内の手前になったのですが、通勤には片道小一時間ほどかかっていたように思います。ちょっとGoogleマップで確認をしておこうと思います。

[link:] » 能登中核工業団地 コミュニティ施設 から 釜屋町 - Google マップ https://t.co/pG5rxtGdUW

　距離は思っていたより短く25キロ程度でした。志賀町の中心部から能登中核工業団地はけっこう離れていたので、羽咋市から35キロほどあるのかと考えていましたが、そうでもない距離でした。交通量はけっこう多かったように思います。

　夜だと30分はかからなかったと思われますが、昼に多少混んでも40分ぐらいかと推定します。夜勤を終えてアパートに戻るとテレビでとくダネ！の放送をやっているようなことも、そういえばあったかもしれないと思いました。

　ぼんやりとしか記憶にないのですが、アパートの駐車場に駐車した車に、ワイパーに紙が挟んであったように思います。電話番号が書いてあって連絡をくれるように書いてありました。

　妙な書き置きだと思いながら、連絡しないまま放置するのも気になったので電話をしました。繋がった先が金沢東警察署だったのは驚きでした。そして、粟崎のひき逃げ死亡事故について、事故発生当時どこにいたのかなど質問をされました。

　電話で対応した警察官の話によると、目撃の車種や色も違っていたようなのですが、同じ軽四ということで事情をきいたような話でした。アパートは国道249号線沿いに少し入り組んで駐車場があったので、通りがかりにメモを挟んだような説明だったとも思います。

　羽咋市から金沢市の粟崎というのはかなり距離も離れていますが、選択した道路では金沢市内の入り口になります。具体的には当時の能登有料道路の内灘料金所を通過した先のルートになるのですが、私は手前の白尾インターで降りて宇ノ気から金沢市内に入ることがほとんどでした。

[link:] » 粟崎町 から 釜屋町 - Google マップ https://t.co/svbj5A5rdc

　金沢市周辺から羽咋市内まで捜査の範囲を広げていたとは考えられますが、事故当時、行った覚えもない場所であったにも関わらず、なにか疑いを掛けられているようで、なんともいえない気分にさせられ、これがえん罪の初期症状に近いものなのかと考えたこともよく憶えています。

　金沢市粟崎のひき逃げ死亡事故のことは、次の記事の部分を記述していた思い出したものです。

5741： 昭和40年代、能登町波並の国道で起こったと聞く小学生の交通死亡事故と、宇出津小学校での自転車運転免許 - 金沢市駅西本町所在市場急配センターにおける組織犯罪殺人未遂事件として再捜査の要請書／石川県警察珠洲警察署御中 http://hirono-hideki.hatenablog.com/entry/2019/10/11/121426

　金沢東警察署に電話をした2,3ヶ月後だったと思いますが、テレビの石川県内ニュースで、粟崎のひき逃げ死亡事故はまだ犯人の目星もついていないような話となっていました。そのあとに情報はみていないですが、未解決事件となった可能性はあると思います。

　この金沢市の粟崎については、他にも思い出したことがあるので、ついでに記述をしておこうと思います。被告発人HTNと被告発人大網健二に関することです。

〈〈〈：Emacs： 2019-10-11（金曜日）14：05 　〈〈〈

