#+TITLE: "ポルターガイスト現象と、社会現象としての弁護士鉄道の現在"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-11-16 13:49:28 +0900
FILE_NAME: 2019-11-16-134928_ポルターガイスト現象と、社会現象としての弁護士鉄道の現在.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 弁護士鉄道
記事タイトル名の文字数：28　保存ファイル名の文字数：50
#+STARTUP: showeverything


* 深澤諭史弁護士のタイムラインと本書作成記録方法の変更：ポルターガイスト現象と、社会現象としての弁護士鉄道の現在
  CLOCK: [2019-11-16 土 13:52]--[2019-11-16 土 14:13] =>  0:21

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 弁護士鉄道,深澤諭史弁護士,ジャーナリストの江川紹子氏

〉〉〉：Emacs： 2019-11-16（土曜日）13：52　 〉〉〉

　本書の記録方法としていろいろと悩みがあり、作業の効率も悪かったのですが、ふとしたひらめきがあって、これまでよりはいくらか改善できそうな方法を思いつきました。

　とりあえずは、深澤諭史弁護士のタイムラインがメインとなり、試行錯誤でやってみるというところです。深澤諭史弁護士のタイムラインは、今日だけでもいくつかの発見があったのですが、このエントリーファイルのメインとなるポルターガイスト現象は、それとは別になります。

　直接のきっかけは、ジャーナリストの江川紹子氏のタイムラインでのジャーナリストの江川紹子氏本人の１つのツイートですが、そこから思いを巡らすことで、新境地のような展望が開けてきました。今まで共存が難しいと頭を悩ませてきた諸課題が、連携を保ちながらひと括りに収斂できるかもしれません。

　深澤諭史弁護士のタイムラインが先か、ジャーナリストの江川紹子氏のタイムラインを先にするかまずはここから迷うところですが、数多くの問題を折り込みながら多彩な時代絵巻としての記録が作成できそうです。試行錯誤ですが目標にはいくらか近づけると思います。

　よりインパクトの強い状態で問題性を強く意識しているジャーナリストの江川紹子氏のツイートから先に取り上げたいと思います。日大アメフト部の悪質タックル問題の不起訴のニュースになりますが、これまでのところテレビでは余り報道をみていません。

　本当は、「ほとんど見ていません」と書きそうになったのですが、１つだけ番組で見ていたかもしれません。最近はテレビを見ない時間もまた増えてきて、今日の土曜日も午前中にしばらく見てからテレビを消し、14時07分の現在もテレビは消したままです。

　記録としての整理、あとで調べやすい保存方法などを意識し、このあとは別のエントリーファイルとして記述をおこない、そのあとブログ記事のリンクとして、ご紹介や参照などをしていきたいと思います。時系列の単位は扱いやすい一月にしたいと思います。

〈〈〈：Emacs： 2019-11-16（土曜日）14：13 　〈〈〈


