#+TITLE: "大観音像と弁護士鉄道"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-11-08 10:08:17 +0900
FILE_NAME: 2019-11-08-100817_大観音像と弁護士鉄道.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 弁護士鉄道,
記事タイトル名の文字数：10　保存ファイル名の文字数：32
#+STARTUP: showeverything


* えきなんローヤーと樋詰哲朗弁護士（金沢弁護士会）、「淡路島100メートル観音が放置13年　廃虚化し台風で外壁損壊　住民不安募る」というニュース：大観音像と弁護士鉄道
  CLOCK: [2019-11-08 金 10:39]--[2019-11-08 金 12:59] =>  2:20

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 弁護士鉄道,えきなんローヤー,樋詰哲朗弁護士（金沢弁護士会）,金沢弁護士会

〉〉〉：Emacs： 2019-11-08（金曜日）10：39　 〉〉〉

　本日11月8日は今のところ大丈夫なようですが、たしか一昨日の6日の朝から昨日9日の深夜までTwitterAPIのエラーが頻発し、何度も投稿をやり直したりしていたのですが、スクリーンショットなどはツイートととしてアップロードできなかったものもあるようです。

　次のスクリーンショットが非常上告-最高検察庁御中_ツイッター（@s_hirono）で発見できなかったことで気がついたのですが、すぐにアップロードをやり直しました。アップロードといってもTwitterAPIを使った画像付きツイートです。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-08 10:43／2019/11/08 10:20 URL： https://twitter.com/kk_hirono/status/1192618737083404289 https://twitter.com/s_hirono/status/1192612751631249409
> 2019-11-07-173421_えきなんローヤーさんがリツイートKURODAtakashi@kitaguni_b·15hこの大仏像、ツンデレ先生が話題にしてたあれですよね。へたにつくるの.jpg https://t.co/jrC618cl9b
▶▶▶　　　　　End　　　　　▶▶▶

　スクリーンショットの記録は、昨日の17時34分となっています。これが初見だったと思います。テレビでもニュースは見ていないですが、この淡路島の大観音の問題は、だいぶん前に一度、テレビの朝の情報番組で取り上げられているのを観たことがあり、知っていました。

　最近もちょくちょくと思い出して、どうなったのか気になり、Googleの検索で調べてみようと思いながら実行までには至らずにいました。Twilogでちょっと確認をしておきたいと思います。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-08 10:53／2019/11/07 17:16 URL： https://twitter.com/kk_hirono/status/1192621061294026754 https://twitter.com/hirono_hideki/status/1192355167196200960
> 淡路島100メートル観音が放置13年 廃虚化し台風で外壁損壊 住民不安募る（毎日新聞） - Yahoo!ニュース https://t.co/ksloRkQXJ5
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-08 10:52／2018/10/05 11:45 URL： https://twitter.com/kk_hirono/status/1192620987591749632 https://twitter.com/hirono_hideki/status/1048041333976223744
> 淡路市議会の議事録によると、観音像を建てた男性の遺族は「道義的な責任がある」として、同市に「相当な額」のふるさと納税をしており、その「浄財」が観音像関連の経費に活用されている。 https://t.co/fZlTKCrF7E
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜bengo4topics（弁護士ドットコムニュース） 日時：2019-11-08 10:52／2015/03/11 12:53 URL： https://twitter.com/kk_hirono/status/1192620809057112065 https://twitter.com/bengo4topics/status/575504696862896128
> 責任能力の有無はどうやって判断しているのか、聞いてみました。|＜淡路島5人殺害＞容疑者に「妄想性障害」の診断歴？「責任能力」はどう判断されるかhttp://t.co/KDdgdkWMx2 http://t.co/BOMErNL4kO
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Hideo_Ogura（小倉秀夫） 日時：2019-11-08 10:52／2015/03/10 12:46 URL： https://twitter.com/kk_hirono/status/1192620759333523456 https://twitter.com/Hideo_Ogura/status/575140723072241666
> あの人たちがいつあちら側に転んでも不思議ではありませんけどね。RT @hosoi_to: 淡路島の事件。容疑者が「インターネット上で人の批判を繰り返していた」という報道を見聞きしてゾクッときましたね－。だって、あの人たちにソックリですものねね。リアルに刃物を振り回すかどうかの差（
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-08 10:51／2015/03/09 22:10 URL： https://twitter.com/kk_hirono/status/1192620602017767424 https://twitter.com/hirono_hideki/status/574920174752690180
> 淡路島の5人殺害事件の被疑者のツイッターアカウント。フォローが189件でフォロワーが1660件。フォローは外国と政治関係が多く、弁護士は見当たらず。自由人権協会というのがあり、ジャーナリストのアカウントが２つ。いずれも先ほどリツイートしたアカウント。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-08 10:51／2015/03/09 21:57 URL： https://twitter.com/kk_hirono/status/1192620523550724096 https://twitter.com/hirono_hideki/status/574916996019650560
> ツイッターをやっていたらしい。淡路島の事件の容疑者。報道ステーション。モザイクがかかっていたけど、みたことのないアイコンに見えた。見覚えのあるアイコンだったらぶっくり。父親が子供の危険性を訴えていたとも。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-08 10:50／2015/03/09 19:05 URL： https://twitter.com/kk_hirono/status/1192620468517212160 https://twitter.com/hirono_hideki/status/574873722986893312
> 被害者の家族が市の法律相談で加害者のネット上の中傷行為について相談していたという。19時のNHKニュース。淡路島の殺人事件。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-08 10:50／2015/03/09 10:11 URL： https://twitter.com/kk_hirono/status/1192620368260812800 https://twitter.com/hirono_hideki/status/574739148755566592
> スッキリも被害者は4人になっている。淡路島の殺人事件。「弁護士と相談しないと話せない」と言っているという。
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「淡路」の検索結果 - Twilog https://t.co/DKqvEV1zpC

　淡路島の5人殺害事件ですが、これはほぼ忘れていたと思います。なんとなくは記憶していたと思いますが、淡路島の事件というのも今見て、少し意外に感じたほどです。心神喪失や心神耗弱が問題になっていた事件と記憶しますが、判決が出ているのか思い出すことはありません。

　この心神耗弱については、ちょうど24時間ほど前の昨日の午前中、気になるツイートを見かけていて、記録の必要を感じていました。あとで簡単にでも取り上げておきたいと思います。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-08 11:00／2018/10/05 05:16 URL： https://twitter.com/kk_hirono/status/1192622801011654656 https://twitter.com/hirono_hideki/status/1047943560987725824
> モトケンさんのツイート: "変な人に絡まれてしまった。京都弁護士会の事務局の方、ご迷惑をおかけします m(_ _)m" https://t.co/J4W8Vj08kW
▶▶▶　　　　　End　　　　　▶▶▶

　数日前にも何かの検索で見覚えのあるツイートですが、次の日付を指定したTwilogの検索結果に出てきたものです。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2018年10月05日 - Twilog https://t.co/igvgLq5IoJ

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-08 11:03／2018/10/05 11:16 URL： https://twitter.com/kk_hirono/status/1192623554350600193 https://twitter.com/hirono_hideki/status/1048034135640424448
> すべての一覧｜広報のと｜能登町役場 https://t.co/Y6R2uw1K5O      広報のと２月号      特集　能登町温泉めぐり      柳田庁舎 広報情報推進課 平成22年4月8日(木曜日) 11時25分
▶▶▶　　　　　End　　　　　▶▶▶

　上記のツイートが2018年10月5日の11時16分で、その次の11時41分のツイートに「【関西の議論】所有者不在で荒れ果て放置される巨大“迷惑観音像”…複雑に絡む権利・法律、倒壊の危険も行政は手を出せず（1/3ページ） - 産経WEST」という内容のツイートがあります。

　気になったニュースや話題はその場で調べることが多いのですが、11時41分という時間はテレビのどのチャンネルも全国ニュースをやっているように思います。11時20分から「ひるおび」が中断し「キューピー3分間クッキング」ですが、30分からの再開はそのままニュース報道になっているかと。

　でも、「キューピー3分間クッキング」が始まる前の「ひるおび」で取り上げていた可能性が高く、それも11時過ぎに観たような気もします。テレビで淡路島の大観音の問題を観たのは、その1回だけだったと思いますが、記憶に自信はなく、あるいは2回あったような気もしてきます。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-08 11:12／2018/10/05 22:34 URL： https://twitter.com/kk_hirono/status/1192625919472463872 https://twitter.com/hirono_hideki/status/1048204816269209600
> 台風25号が北上　珍しい10月に日本海へ入る台風(饒村曜) - 個人 - Yahoo!ニュース https://t.co/yu1gLL1riF
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-08 11:12／2018/10/05 22:19 URL： https://twitter.com/kk_hirono/status/1192626037579845632 https://twitter.com/hirono_hideki/status/1048200978070036480
> 日馬富士を訴えた貴ノ岩・被害の程度と裁判の行方(江川紹子) - 個人 - Yahoo!ニュース https://t.co/lFM3fjsbqA
▶▶▶　　　　　End　　　　　▶▶▶

　一つ間違ってリツイートをしたのですが、気になったのはジャーナリストの江川紹子氏のブログ記事です。たぶんこの記事であったように思うのですが、鳥取県の検察庁に行き、事件の記録を閲覧してきたような話で、その内容も紹介をしていたように記憶します。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2019-11-08 11:20／2018/10/05 21:21 URL： https://twitter.com/kk_hirono/status/1192627863385559040 https://twitter.com/amneris84/status/1048186424959234048
> 刑事事件での被害認定の根拠となった医師の調書の内容を紹介しました　→日馬富士を訴えた貴ノ岩・被害の程度と裁判の行方(江川紹子) - Y!ニュース https://t.co/kz5G96bSY4
▶▶▶　　　　　End　　　　　▶▶▶

　この日馬富士と貴ノ岩の問題についても、TMI法律事務所や、弁護士が富岡八幡宮殺傷事件との関連などを、しっかり記録化しておきたいのですが、なかなか手付かずにいる問題の一つです。

　えきなんローヤーというアカウントについても同様です。富山県高岡市の女性弁護士の可能性があり、調べると実名から顔写真まで出てきたのですが、本人と確認できる情報もなく、今のところ、あえてプライバシーに優先させるような社会的必要性は認めていません。

　駅南というのは駅に南側を意味する言葉だと思います。金沢市の場合は駅西が地名にもなっていますが、駅は全国各地にあるもので首都圏では特に集中している考えから検索すると情報が多すぎて扱いきれないと考えていました。しかし、実際にやってみると驚くほど少なくすぐに特定が出来ました。

　さきほど「えきなんローヤー」のタイムラインから淡路島の大観音のニュース記事のタイトルをコピペしようと思ったのですが、タイムラインを開くと意外な発見がありました。昨日も新たな情報で注目をしていた樋詰哲朗弁護士（金沢弁護士会）のことになります。

　同じ石川県の弁護士で、石川県にあるのは金沢弁護士会だけ、木梨松嗣弁護士、岡田進弁護士、長谷川紘之弁護士、若杉幸平弁護士と4人の被告発人、そして損害賠償、求償権での責任追及の可能性も想定している小堀秀行弁護士、野田政仁弁護士が所属するのと同じ金沢弁護士会です。

　樋詰哲朗弁護士（金沢弁護士会）のTwitterアカウントには奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)でブロックされていることも確認しています。金沢弁護士会全体の情報共有としてもとても参考になる資料です。

hizumelaw ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW hizumelaw（弁護士樋詰哲朗） 日時：2019/11/08 10:02 URL： https://twitter.com/hizumelaw/status/1192608188341686272
> 23条照会調査室に所属しているが、ノウハウのある事務所とそうでない事務所で照会の仕方が違っていて、照会事項を工夫するだけで回答が違ってくる場合もあるなあと思って審査しています。調査担当は内容まで踏み込めないので。
▷▷▷　　　　　End　　　　　▷▷▷

　告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)でも樋詰哲朗弁護士（金沢弁護士会）にブロックされていることを確認しましたが、上記のツイートは最新のツイートとなっており、先程、えきなんローヤーのリツイートとして見たものと思います。

　 23条照会調査室というのは初めて見ました。金沢地方検察庁の調査官室は実際に入ったこともありますが、ネットでも見かけたことはありません。あるいは捜査官室だったかもしれないのですが、そちらも同じことです。

　平成4年の秋だったと思いますが、被告発人木梨松嗣弁護士から八幡温泉病院への弁護士照会の書面が差し入れられたことがありました。封筒で郵送されたものかもしれません。木梨松嗣弁護士の説明はなかったですが、名古屋高検金沢支部の答弁書が届いたのも同じ頃だったと記憶します。

　時刻は11時52分です。チャンネルをバイキングが始まる石川テレビに変更したところですが、ちょっと前にMROの石川県内ニュースがあって、能登町鵜川の「いどり祭り」が昨晩あったと紹介していました。祭りと言っていたように思いますが、神事のみではと思います。

　ニュースを読み上げる女子アナの声で、鵜川のアクセントが「う」にあって、地元の発音とは違っていたのも気になるところでした。この「いどり祭り」も春の辺田の浜の「酒樽がえし」と同じで毎年決まって県内ニュースで見かけます。

　「いどる」というのは「けなす」という意味らしいですが、実際に聞いたことのない方言で、この毎年恒例のようになっているテレビの石川県内ニュースで知るまでは、聞いたこともありませんでした。餅をけなす神事で、以前は正月に行われているものと思い込んでいました。

　樋詰哲朗弁護士（金沢弁護士会）は、石川県の弁護士としては珍しく、Twitterの他にも積極的に法律事務所の宣伝のようなことをやり、それも大々的です。以前は移住者ではと考えていたのですが、何ヶ月か前だったとも思いますが、地元の出身のような情報を見かけました。

```
＞　初めてお会いする方の中には、私を見て驚かれる方も少なくありません。私は右手に障害を持っているからです。原因は不明なのですが、右手首より先がない状態で生まれてきたのです。

＞　今、私自身が子どもを持つ身となり思うのですが、障害を持って生まれてきたわが子を見た時の父母の驚きは察するに余りあるところです。念願かなって、弁護士の仕事に就いた時は、ここまで愛情を持って育ててくれた父母に感謝の気持ちでいっぱいでした。

［source：］弁護士紹介 | 石川県金沢市を中心に北陸地方に根ざした｢弁護士法人あさひ法律事務所｣ https://asahi-law.net/about/
```

　出身地を確認するつもりでページ内のリンクを開いたのですが、上記に引用した意外な情報が出てきて驚きました。引用であることを強調するために「＞　」という記号を接頭辞としました。前から情報はあったのかもしれないですが、今日初めて見たのも不思議です。

　同じページの下の方に「プロフィール」とあって、「1972年　石川県金沢市に生まれる」とありました。中央大学卒業ということも確認できましたが、1996年に法学部法律学科を卒業した後、2006年に同じ中央大学の法科大学院卒業となっていました。

　これまで不思議と気に掛けなかったのですが、中央大学で長年、講師をしているというのが小倉秀夫弁護士になります。小倉秀夫弁護士の担当の学部は記憶にないです。法律学科とは直接関わりがなさそうな気はしますが、同じ中央大学と考えると無縁ではない可能性も頭に浮かんできました。

　小倉秀夫弁護士のTwitterのプロフィールは、時にイスパニア語であったこともあるぐらいで変遷がありますが、プロフィールへのリンクが別にあって、そこには中央大学のことも記載があるはずかと思います。

　樋詰哲朗弁護士（金沢弁護士会）の立場で考えれば、控えめに、同じ大学の講師でネットで目立っていれば関心が向くこともありそうな気がしますし、同じ中央大学内でも友人、知人間で話題や噂話にもなりそうです。

```
【経歴】
　1968年5月　　　　　　　　東京都葛飾区に生まれる
　1984年4月　　　　　　　　東京都立両国高校入学
　1987年3月　　　　　　　　同校卒業
　1987年4月　　　　　　　　早稲田大学法学部入学
　1992年3月　　　　　　　　同校卒業
　1992年4月　　　　　　　　司法研修所入所
　1994年3月　　　　　　　　同出所
　1994年4月　　　　　　　　弁護士登録（東京弁護士会）
　2000年4月〜2016年3月 　　中央大学法学部兼任講師（法学演習：著作権法を担当）
　2009年4月〜　　　　　　　明治大学大学法学部兼任講師（「法・情報・社会」を担当）
　2015年10月〜2016年3月　　首都大学東京法科大学院兼任講師（「著作権法」を担当）

［source：］私のプロフィール http://www.ben.li/text_pr/Profile.html
```

　上記に引用したのが、現在は凍結で更新ができなくなっているらしい小倉秀夫弁護士のTwitterアカウントのプロフィールにあるリンクの内容です。

　何ヶ月か前にも同じページを見ているはずですが、今回、「2000年4月〜2016年3月 　　中央大学法学部兼任講師（法学演習：著作権法を担当）」という記載で、中央大学の講師は終わっていたのだと知りました。前にも目にしていた可能性が高いと思うのですが、既知であった感覚はないです。

　まるまる15年間、中央大学で講師をつとめていたようです。明治大学が2009年から現在も続いているような記載ですが、明治ということで漠然として歴史が長いという先入観があったためか、小倉秀夫弁護士も中央大学の前から講師をしていたという感覚でいたような気がします。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-08 12:47／2019/11/08 12:40 URL： https://twitter.com/kk_hirono/status/1192649812270649344 https://twitter.com/s_hirono/status/1192647950607892480
> 2019-11-08-102507_えきなんローヤーさんがリツイート弁護士樋詰哲朗@hizumelaw·22m23条照会調査室に所属しているが、ノウハウのある事務所とそうでない事務所で照会の.jpg https://t.co/JR4N7TdQIe
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-08 12:47／2019/11/08 12:40 URL： https://twitter.com/kk_hirono/status/1192649758256459776 https://twitter.com/s_hirono/status/1192648023010004994
> 2019-11-08-105944_モトケンさんはTwitterを使っています：　「変な人に絡まれてしまった。京都弁護士会の事務局の方、ご迷惑をおかけします　m（_　_）m」　／　Twitt.jpg https://t.co/Cp5OMqbgwO
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-08 12:47／2019/11/08 12:40 URL： https://twitter.com/kk_hirono/status/1192649716275662848 https://twitter.com/s_hirono/status/1192648095948931072
> 2019-11-08-120719_石川県金沢市を中心に北陸地方に根ざした｢弁護士法人あさひ法律事務所｣.jpg https://t.co/wAPryR3Q9x
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-08 12:47／2019/11/08 12:40 URL： https://twitter.com/kk_hirono/status/1192649700576382977 https://twitter.com/s_hirono/status/1192648168803946496
> 2019-11-08-123623_小倉秀夫（@Hideo_Ogura）さんの返信があるツイート　／　Twitter.jpg https://t.co/SvqXQpei7n
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-08 12:46／2019/11/08 12:41 URL： https://twitter.com/kk_hirono/status/1192649679877505024 https://twitter.com/s_hirono/status/1192648243047358464
> 2019-11-08-123641_私のプロフィール.jpg https://t.co/RCsTDSInq2
▶▶▶　　　　　End　　　　　▶▶▶

　えきなんローヤーを中心にした項目として書き始めたつもりだったのですが、樋詰哲朗弁護士（金沢弁護士会）が主役のようになってしまいました。エントリー全体のテーマは大観音になりますが、先日見かけた法クラのツイートでも、大観音ではなく大仏とするものが２つあった気がします。

　近年知ったことだと思いますが、えきなんローヤーが弁護士をしている可能性の高い富山県の高岡市は、万葉の歴史があり、鋳物の大仏の製造でも全国的に特別な土地だということです。

　観世音菩薩については、これまでに調べたことも多いのですが、悟りを開く前の仏の姿で、困窮者の救済を使命としているという趣旨の情報を多く見てきたように思い、さきほど見た樋詰哲朗弁護士（金沢弁護士会）の弁護士紹介の文章とも、そのまま重なるものを感じました。

　項目名を変更し、樋詰哲朗弁護士（金沢弁護士会）を盛り込みました。そのままこのあと投稿するブログの記事のタイトル名になるものです。

〈〈〈：Emacs： 2019-11-08（金曜日）12：59 　〈〈〈

