#+TITLE: "ウロコ運送と金沢市場輸送の福岡定期便"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-10-06 15:27:52 +0900
FILE_NAME: 2019-10-06-152752_ウロコ運送と金沢市場輸送の福岡定期便.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 金沢市場輸送,
記事タイトル名の文字数：18　保存ファイル名の文字数：40
#+STARTUP: showeverything


* 福岡市でのサワラの刺し身：ウロコ運送と金沢市場輸送の福岡定期便
  CLOCK: [2019-10-06 日 15:30]--[2019-10-06 日 17:05] =>  1:35

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 金沢市場輸送,

〉〉〉：Emacs： 2019-10-06（日曜日）15：30　 〉〉〉

　買い物に行ったどんたく宇出津店で個体が大きいと思われるサワラの刺し身を見かけました。蛸島港産というシールが貼られていましたが能登でサワラというのは珍しいと思われます。小木港や宇出津新港の堤防でも稀にサワラが釣れたという話は聞きますが、小さいものでサゴシという話です。

　金沢港から加賀市の海岸線ではサーフのジギングでサワラが釣れるとも聞きますが、スーパーでサワラを見かけることも滅多にないと思います。以前はサワラの切り身の西京漬けを見かけましたが、人気がないためか今は見かけることがないように思います。

　サワラで思い出すのは福岡のことで、ウロコ運送のSTという駐在員のような立場で、長浜の魚市場から近いマンションに住んでいました。一応、運転手の宿泊所にもなっていたようですが、金沢市場輸送で宿泊に来ていたのは私ともう一人ぐらいだったようです。

　私も毎回、そのマンションに行っていたわけではなかったと思いますが、けっこうよく行ったという思い出が残っています。そしてよく出前の寿司をご馳走になりました。

　当時は余り深く考えていなかったように思いますが、出前の寿司をよくご馳走になっていたのは、小口の荷物を積みに下関の港に立ち寄っていたためと思います。実際、金沢市場輸送では頼まれても断ってやらないという運転手がいました。

　この下関港の立ち寄りは、私もできればしたくない仕事でした。下関インターから往復で馬鹿にならない時間がかかったということもありますが、それ以上に嫌だったのがインターの料金所で重量オーバーの検問を受ける可能性があることでした。

　中国自動車道では他に岡山県の新見インターと島根県の六日市インターが重量オーバーの取締が多く、高速道路を走行中のトラックをパトカーが誘導してインターから降ろし台貫にのせるという話でした。中西運輸商の4t車では実際に新見インターでやられていました。

　金沢市場輸送の大型車では台貫の検問を受けること自体がなかったかもしれません。金沢市場輸送が摘発を受けたのは新潟県の糸魚川インターでした。運転手が会社の指示を受けたと話したところ、増車ができなくなったという話でした。

　全部だったか憶えていないですが、ちょうど5台の平ボディ車が納車されたときのことで、大型トラックのドアの横には社名をペンキで書いておくのが決まりとなっていたのですが、金沢市場輸送ではなく両合物産となっていました。浜田漁業の子会社の社名のように聞いていました。

　私の場合、頼まれた仕事を断ることはなかったのですが、下関とは別に、福岡の魚市場では定期便以外のフリーと呼ばれるかたちで入ることが多く、そのほとんどが金沢行ではなく、東京の築地市場行きでした。

　それも売り場の直卸がほとんどだったと思うのですが、東京の築地市場は全国の魚市場でも特別で、時間内に市場の中に入っても身動きがとれないまま延着することもあるとかで、場内中継というのが普通になっていました。

　中継の相場は当時で一箱50円と聞いていましたが、1000箱あれば5万円になります。中継に出さず売り場へ直卸すれば必要のない経費となります。金沢市場輸送では築地ではないですが、勝手に中継に出したという運転手もいたぐらいです。秋田の市場から青森への中継と聞きました。

　福岡から東京築地への運行は、金沢市場輸送でやる運転手が少ないとも聞きましたが、とてもまかせる気にはなれない運転手もいると聞いたこともありました。

　ウロコ運送のSTさんは、当時40代だったように思います。独身とも聞いていましたが、金沢大学を卒業しているとも聞いていました。マンションには図書館にあるような本棚があって、そこでよく本を読んで時間を潰しました。夏はクーラーがきいていて快適でした。

　私が金沢市場輸送の大型保冷車に乗務して福岡の魚市場に行くようになったのは昭和62年4月からですが、一年ぐらいの間だったでしょうか、魚市場の敷地の奥の方にトラックをとめていました。夜中に長崎方面から陸路のコンテナで運ばれる魚を、日通の人がトラックに積み込んでいました。

　その積み込み作業も乱暴で音がうるさかったのですが、市場の敷地の中、全体が人が多くずいぶんとうるさいものでした。その後、魚市場から離れた広い駐車場にトラックを駐車するようになりました。静かにはなりましたが、遮るものがないので夏場はずいぶん暑かったことも憶えています。

　広い駐車場は、ボートレース場の方に向かったところにありました。正面は魚市場の敷地になっていたとも思います。魚市場の敷地の反対側には、魚市場の壁を隔てて道路沿いに屋台が並んでいましたが、魚市場の正門前にも飲食店はありました。ラーメン屋でしたが、よく入っていました。

　前にも書いていると思いますが、途中にそのラーメン屋の向かいにセブンイレブンのコンビニが出来ました。工事しているところを見た記憶はないのですが、かなり短期間で出来上がり営業を始めていたように思います。かもめ会館という客のほとんどいないパチンコ店もありました。

　私は子どもの頃、刺し身や生魚というのが余り好きではなく、寿司というのもあまり食べた記憶がありません。中学生の頃は、1年か半年に1回ぐらい、母親が寿司の出前をとってやると言い出したのですが、これも前に書いたようにマグロのトロと鰻だけ3千円分の出前でした。

　ちょうど小木分校を中退して金沢に出た昭和56年になりますが、金沢で回転寿司が出来たとずいぶん話題になっていました。元禄寿司だったと思います。片町から横に竪町の商店街に入る路地に店がありました。1回ぐらいは店に入って回転寿司を食べたように思います。

　福岡では寿司以外の出前というのは記憶になく、外に出て店に入ることもなかったと思います。勧められるままに桶に入った出前の寿司を食べていたのですが、なぜかサワラというのがやたらと記憶に残っています。

　福岡の寿司が全部そうなのかはわからないですが、シャリというご飯に対してネタが大きいのも特徴でした。3倍ぐらいはネタが大きかったように思いますが、石川県では全く見たことも聞いたこともない寿司でした。

　2,3年前テレビのローカル番組で、穴水町の方で船でサワラを釣っているのを見かけたことがありました。春が旬で、魚編に春と書くとも説明をしていたかと思います。

　福岡の魚市場ではカツオが大量に水揚げされていましたが、カツオだけは荷物として金沢に運んだことがなく不思議に思っていました。数年前から宇出津のスーパーでもカツオのタタキや刺し身を見かけることが多くなり、テレビのとなりのテレ金ちゃんでも、よく食べられるようになったと言っていました。

　生のサワラを食べたのも平成の時代に入ってから初めてだったと思うのですが、どんな味だったのかも思い出せずにいました。福岡で寿司ネタで食べていたサワラは色も違っていたように思います。赤身か薄いピンクに近い色だったような気がしていました。

　サワラのこともずっと気になっていたのですが、30年以上経ってからようやく食べたように思います。盛り合わせの一貫として口にしていたことはあったかもしれません。考えてみると前にサワラを食べたのは、宇出津新港が出来た頃だったとも思います。

〈〈〈：Emacs： 2019-10-06（日曜日）17：05 　〈〈〈

