* 「目的外で交付等することは，犯罪ですお（刑訴法２８１条の４第１項・同法２８１条の５第１項）」という深澤諭史弁護士のツイート
  CLOCK: [2019-12-29 日 10:54]--[2019-12-29 日 11:23] =>  0:29

〉〉〉：Emacs： 2019-12-29（日曜日）10：54　 〉〉〉

fukazawas ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW fukazawas（深澤諭史） 日時：2019/12/29 10:11 URL： https://twitter.com/fukazawas/status/1211092386018816000
> （・∀・）刑事裁判の被告人になった場合，弁護人経由で検察官が請求する証拠の写しの提供を受けることがあります。 \n （；＾ω＾）この証拠の写しは，あくまで公判準備のために提供されるものであり，目的外で交付等することは，犯罪ですお（刑訴法２８１条の４第１項・同法２８１条の５第１項）
▷▷▷　　　　　End　　　　　▷▷▷

　深澤諭史弁護士のタイムラインでは、上記の目的外で交付というツイートに関連のありそうなものは見当たりませんでした。刑訴法２８１条の４の条文は検索で確認をしましたが、やはり証拠の目的外使用のことでした。

　これまで「証拠の目的外使用」としてのみ見てきた条文ですが、深澤諭史弁護士は「目的外で交付等」としています。条文を読めばわかりますが、証拠の目的外使用には例外が挙げられ、再審請求や非常上告の手続きとあります。

　数年前から疑問として指摘しているはずですが、非常上告は検事総長が最高裁に対して行う刑事手続とされているはずです。近年は見かけなくなっているものの「職権発動を促す」という表現は度々目にしたことがあり、同じ時代には「指揮権の発動」というのもあったかと思います。

```
第281条の4
被告人若しくは弁護人（第440条に規定する弁護人を含む。）又はこれらであった者は、検察官において被告事件の審理の準備のために閲覧又は謄写の機会を与えた証拠に係る複製等を、次に掲げる手続又はその準備に使用する目的以外の目的で、人に交付し、又は提示し、若しくは電気通信回線を通じて提供してはならない。
当該被告事件の審理その他の当該被告事件に係る裁判のための審理
当該被告事件に関する次に掲げる手続
イ　第1編第16章の規定による費用の補償の手続
ロ　第349条第1項の請求があった場合の手続
ハ　第350条の請求があった場合の手続
ニ　上訴権回復の請求の手続
ホ　再審の請求の手続
ヘ　非常上告の手続
ト　第500条第1項の申立ての手続
チ　第502条の申立ての手続
リ　刑事補償法の規定による補償の請求の手続
前項の規定に違反した場合の措置については、被告人の防御権を踏まえ、複製等の内容、行為の目的及び態様、関係人の名誉、その私生活又は業務の平穏を害されているかどうか、当該複製等に係る証拠が公判期日において取り調べられたものであるかどうか、その取調べの方法その他の事情を考慮するものとする。

［source：］刑事訴訟法第281条の4 - Wikibooks https://ja.wikibooks.org/wiki/%E5%88%91%E4%BA%8B%E8%A8%B4%E8%A8%9F%E6%B3%95%E7%AC%AC281%E6%9D%A1%E3%81%AE4
```

　第281条の4の条文は上記のページで確認しました。深澤諭史弁護士のツイートには第281条の5があるようなのですが、これは見聞きした憶えがなく、あとで調べるつもりです。

　もうひとつ「第281条の4」のGoogle検索の結果から次のページを読みました。気になった部分が一つあったので次に該当部分を引用しますが、ジャーナリストの江川紹子氏の記事が紹介されています。

```
また，証拠の目的外使用には問われなかったものの，弁護士が「警察による取調べの様子を録画したDVDをテレビ局に提供したこと」につき，当該弁護士が検察から懲戒請求されたというケースもあります（H26.1.17付きヤフーニュース「「品位」を問われるべきはどちらか～証拠の「目的外使用」で弁護士会の審尋開かれる」　なお，懲戒請求申立てを受けた大阪弁護士会は，当該弁護士に対する懲戒処分はしないという決定をしました（H26.2.8付き日本経済新聞「弁護士の映像提供問題　異議申し立て大阪地検行わず」））。

なお，この「開示された証拠の目的外使用を規制すること」については，裁判員制度が導入される際に立法化されたものですが，刑事訴訟法の条文を改正する法律案が国会に提出された際，日本弁護士連合会は「証拠の内容を問わず、また公開の法廷に提出された証拠か否かを問わず一律に使用禁止の対象としていることから、その使用理由が如何に正当なものであったとしても、審理の準備以外の目的で開示証拠を使用することは全て禁止されることになり、被告人の防御権を不当に制約することは勿論、裁判公開原則や報道の自由とも抵触するおそれが大きい」などとして，改正に反対する声明（H16.4.9付き「刑訴法改正法案から証拠の目的外使用条項の削除を求める会長声明」）を出しています（しかし，改正はなされてしまいました）。

［source：］刑事訴訟の記録をインターネットに掲載した男性が逮捕。 | ネットイージス.com |ネットでの誹謗中傷等にお悩みの方はパロス法律事務所へ http://net-aegis.com/blog/649
```

　引用のためにページの見直しをして気がついたのですが、ページの下、フッタとも呼ばれる部分に弁護士の名前があって「櫻町直樹（東京弁護士会）」とありました。人名としては初めて目にしたとも思います。法律事務所の名前も初めて目にするものです。

〈〈〈：Emacs： 2019-12-29（日曜日）11：23 　〈〈〈

