* 「着手金３桁に、接見日当は１回６万円」という7月28日付の金岡繁裕弁護士（愛知県弁護士会）のブログ記事を、深澤諭史弁護士のタイムラインで12月27日のツイートとして発見
  CLOCK: [2019-12-28 土 00:51]--[2019-12-28 土 02:23] =>  1:32

〉〉〉：Emacs： 2019-12-28（土曜日）00：51　 〉〉〉

fukazawas ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW fukazawas（深澤諭史） 日時：2019/12/27 10:37 URL： https://twitter.com/fukazawas/status/1210374177724583936
> （；；；・∀・）似たようなケースの相談を受けたことがある。 https://t.co/AZNlVnuZZ9
▷▷▷　　　　　End　　　　　▷▷▷

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜takeemon19（ふとりたに） 日時：2019-12-28 00:52／2019/12/27 09:39 URL： https://twitter.com/kk_hirono/status/1210589254683783169 https://twitter.com/takeemon19/status/1210359432078454784
> やはり消費者加害の匂いを感じる刑事弁護 https://t.co/cIB5GyNXD7  どことは言わないがネットで集客している某事務所が支店を開いたばかりなのに私選が何件かあると昔言ってた事があったなあ
▶▶▶　　　　　End　　　　　▶▶▶

```
ふとりたに
@takeemon19
たけえもん・334おじさん。兵庫県姫路市在住の若手弁護士。生まれてこのかた阪神ファンです。鳥谷推し。最近は江越や岩貞も推しています^_^
誕生日： 1月1日2013年6月からTwitterを利用しています
3,973 フォロー中
2,106 フォロワー

［source：］ふとりたに（@takeemon19）さん / Twitter https://twitter.com/takeemon19
```

　数日前にも見かけていましたが、プロフィールのアイコンが変わっていました。前と同じように顔の部分がいたずら書きのようなもので隠されていますが、サンタの仮装をした姿のように見えます。小さいアイコンだとアイドルの若い女性のように見えたのですが、大きいのは女装した男性に見えます。

　ちょっと忘れかけていたような気もするのですが、大きいアイコンを見るためにTwitterのアカウントのページを開いたところ、「兵庫県姫路市在住の若手弁護士」とプロフィールにあったことを思い出しました。ヘッダ写真の風景と固定されたツイートに変わりはないようです。

　2019年12月27日09時39分とあるツイートを深澤諭史弁護士が同日10時37分にURLの公式引用をしたようです。ざっとこの「ふとりたに」というアカウントのタイムラインを遡ったところ、他に金岡繁裕弁護士（愛知県弁護士会）やその記事に関連したツイートは確認されませんでした。

　やはりたまたまの偶然なのかと思いますが、7月28日の金岡繁裕弁護士（愛知県弁護士会）のブログ記事を、「ふとりたに」というアカウントが12月27日になってツイートに取り上げたことになります。

［link：］ やはり消費者加害の匂いを感じる刑事弁護|名古屋市中区の弁護士法人 金岡法律事務所 http://www.kanaoka-law.com/archives/728

　普通に記事のページタイトルを取得すれば、上記の通り「|名古屋市中区の弁護士法人 金岡法律事務所」という部分が付いてくるはずなのですが、一様にこの金岡法律事務所の部分がカットされているツイートばかりを見かけているので、それもずっと気になっています。

　検索の対象ともなるツイートの本文に金岡繁裕弁護士（愛知県弁護士会）の「金岡」という名前を入れたくない、残したくない意思があるのかと勘ぐりたくもなってきます。凄まじすぎる弁護士パワーとしては頷けるところもあるだけに、なおさら実際のところが気になってまいります。

　金岡繁裕弁護士（愛知県弁護士会）のブログ記事は「やはり消費者加害の匂いを感じる刑事弁護」となっていますが、本文を読んでいくとそこにも強いパワーと異常性を感じました。弁護士業界そのものが解き放つ社会的危機感に輪をかけて、独自な解釈を披瀝している点です。

　加害性の認識が緩いともいえますが、消費者加害を名目に踏み台あるいは叩き台として、自己の弁護士としての正統性をピーアールしていると感じさせるもので、深澤諭史弁護士に強く見られてきた特徴に共通しています。それ故に深澤諭史弁護士の反応が出たのかもしれません。

　社会的な問題性を強く感じるので次に全文を引用します。弁護士の社会的危険性、有害性を強く感じるところです。

```
2019年7月28日(日)｜Category：その他
以前、本欄で、「とある『刑事専門』事務所との紛議」について紹介し、実費を含めた全額返金対応が「されてしまった」こと、「他で稼げば良いから紛争は全額返金で終わらせる」的な対応にも思えることを紹介した。
公平に言えば、クレーマー対策として返金してさっさと終わらせると言うことは有り得るものの、刑事専門を標榜するなら、正々堂々と、徴収した弁護士費用の正当性を掲げて対抗して欲しいという気持ちがある。

さて、今般、起訴直後に「刑事弁護に強い」を標榜する事務所の弁護士と交代で受任した事件がある。着手金３桁に、接見日当は１回６万円（但し、片道１時間近くかかる警察署ではある）、さぞ充実した弁護を展開しておられたのだろうと思いきや・・引き継ぎ精算時、着手金は返すから日当と実費だけ請求する、と仰る。
そこで実費の明細を出して、と要求すると（当然の要求だが、特に今回は実費が１５万円を超えていたので、捜査段階だけでなんで１５万円も？まさか毎回タクシーで接見？といぶかしく思ったのだ）、半日もせずして、日当も実費も全部放棄する、と、対応が変わった。
本当に１５万からの実費がかかっているとして、かつ、自身の弁護活動に恥じるところがないなら、せめて実費くらい粘れよ、と言いたくなる。

やはり、消費者加害の匂いを感じないわけにはいかない。
刑事事件に強いことを標榜すればするほど、顧客は引っかかりやすくなる。高額をふっかけても顧客は強さに期待して喜んで払う。幸運にも上手く行けば文句は出ない。失敗を重ねても、全額返金対応をしておけば大きな問題には発展しない。回転率を上げるため揉めそうなら全額返金して、金払いの良いところからｎ弁護士費用の徴収を重点化する。
こういう発想でことが進んでいるなら、消費者加害そのものだ。

客観的に弁護活動の善し悪しを査定し、約定の弁護士費用が相当か否かを判定することは難しい。本件に準えて言えば「標準的捜査弁護とは何か」という指標が必要になるからだ。医事紛争では不法行為性を巡り一般的医療水準論というものがあるが、消費者加害性のある弁護活動該当性を巡り一般的弁護水準論の指標の確立は可能なのだろうか。誰がどのように鑑別したものだろうか。難しい問題ではあるが、野放しというわけにもいかないだろう。

（弁護士　金岡）

［source：］やはり消費者加害の匂いを感じる刑事弁護|名古屋市中区の弁護士法人 金岡法律事務所 http://www.kanaoka-law.com/archives/728
```

　「刑事事件に強いことを標榜すればするほど、顧客は引っかかりやすくなる。高額をふっかけても顧客は強さに期待して喜んで払う。幸運にも上手く行けば文句は出ない。失敗を重ねても、全額返金対応をしておけば大きな問題には発展しない。」とあります。

　「回転率を上げるため揉めそうなら全額返金して、金払いの良いところからｎ弁護士費用の徴収を重点化する。こういう発想でことが進んでいるなら、消費者加害そのものだ。」ともあります。一見すると消費者の側に立って問題点を指摘しているように見えなくはありません。

　刑事裁判を経験すると、一審の重要性がよくわかります。一審の結果が想像を超えたとんでもないものであったので控訴するという例が多いのではと考えていたタイミングでもあるのですが、その控訴審の即日判決に対する批判も同じ金岡繁裕弁護士（愛知県弁護士会）のブログ記事で見たものです。

　考えてみると、控訴を増やすことが弁護士の利益、売上げアップにもなります。私自身も一審の被告発人岡田進弁護士が国選弁護人で、控訴審の被告発人が私選弁護人となりました。弁護士の仕事を１つ増やしたことは紛れもない事実になります。

　最近は、一審で無罪判決を出すと控訴審や上訴のことは情報を出さなくなるという例があります。それも社会的な影響が大きそうな刑事事件で、一審の無罪判決が出る前は、余りアピールもしていなかった弁護士らが無罪判決のときには記者会見をし、検索の控訴以降はだんまりです。

　似たような経過で一審の無罪判決が出たのが郷原信郎弁護士の藤井美濃加茂市長事件でしたが、控訴審では裁判所に相手にされず、被告人本人の本人尋問も認められることはなかったようです。

　金岡繁裕弁護士（愛知県弁護士会）は、弁護活動の良し悪しを査定し、約定の弁護士費用の相当性を判定することは難しいともしていますが、三桁の着手金というのはこれまでにも弁護士のツイートや発言として見かけてきたものです。

　刑事弁護の着手金は返還することのない費用で、成功報酬とは別にされることがほとんどのはずです。それこそ結果の良し悪しに関係なく弁護士の懐に入るお金なのでしょう。成功報酬も無罪は例外ですが、不起訴なら確率も高く、求刑を下回る量刑も弁護士の成功とされているようです。

　無罪判決は弁護士の実績や宣伝効果が期待できるらしく、強いこだわりをもつ弁護士というのも以前はちょくちょくと見かけてきましたが、無罪判決がそう珍しくはなくなるにつれ表立ったこだわりは見かけないようになった気もします。

　「やはり消費者加害の匂いを感じる刑事弁護」と金岡繁裕弁護士（愛知県弁護士会）の記事のタイトルにはありますが、繰り返し読むほど奥深さを感じるものです。刑事弁護は身内を含め急な対応を迫られる場合も多そうです。不安を掻き立てているようにも思えてきます。

　実際に金岡繁裕弁護士（愛知県弁護士会）が問題を提起するような弁護士がいるのかもしれません。「刑事弁護に強い」というフレーズは数年前はアトム法律事務所の代名詞のようにもなっていましたが、最近は名前を見かけなくなり、他にも同じ宣伝広告の法律事務所をネットで見ることがあります。

〈〈〈：Emacs： 2019-12-28（土曜日）02：23 　〈〈〈

