* 「日本の刑事司法があれなのは反論しようがないが、「当事者の主観的に見て不当な司法なら従わなくても良い」と」という平野敬弁護士（第二東京弁護士会）のツイート
  CLOCK: [2019-12-31 火 21:53]--[2019-12-31 火 22:25] =>  0:32

〉〉〉：Emacs： 2019-12-31（火曜日）21：53　 〉〉〉

stdaux ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW stdaux（スドー） 日時：2019/12/31 16:32 URL： https://twitter.com/stdaux/status/1211913100556820480
> 日本の刑事司法があれなのは反論しようがないが、「当事者の主観的に見て不当な司法なら従わなくても良い」ということを認めてしまうと一切の法制度が成り立たなくなるので、曖昧な笑顔を浮かべつつ首を振るしかないって、ソクラテスのおじさんが言っていた
▷▷▷　　　　　End　　　　　▷▷▷

2019年12月31日21時49分の登録： ＼スドー　@stdaux＼日本の刑事司法があれなのは反論しようがないが、「当事者の主観的に見て不当な司法なら従わなくても良い」ということを認めてしまうと一切の法制度が成 http://hirono2014sk.blogspot.com/2019/12/stdaux_31.html

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-12-31 22:02／2019/12/31 22:02 URL： https://twitter.com/kk_hirono/status/1211996148644241408 https://twitter.com/s_hirono/status/1211995983954841601
> 2019-12-31-215524_スドー@stdaux·5時間日本の刑事司法があれなのは反論しようがないが、「当事者の主観的に見て不当な司法なら従わなくても良い」ということを認めてしまうと.jpg https://t.co/lM2FSi6GDC
▶▶▶　　　　　End　　　　　▶▶▶

　寝た時間のことはよく憶えていないのですが、Twitterの投稿を見ると９時２分にはツイートをしていたようです。起きてからパソコンの時計を見たのが１２時１４分ではなかったかと思うのですが、そこですぐにカルロス・ゴーン氏が保釈条件を破って国外に出たニュースを知りました。

　午後はテレビで、ホテルニュージャパンの大火災の番組をみていて、そのあと白山神社にお神酒を届けてきました。スマホを忘れて出かけたので行動記録をかねた写真を撮ることは出来なかったです。

　夕方に、Aコープ能都店で買い物をしてから銭湯に行きました。Aコープ能都店の閉店時間は１８時でしたが、昨日とは違って客の数が多く、惣菜は少ししか残っていなかったですが、精肉のほとんどが半額シールになっていました。

　Aコープ能都店は明日の１日と明後日の２日が閉店で、それで新鮮な肉が半額となっていたようです。すき焼き用と思われる能登牛が２４０ｇで１９８０円になっていたと思いますが、その半額で滅多にはないことなので買ってきました。焼き豆腐がなかったのが残念でした。

　数日前に買ったおでんの袋が今日の３１日で賞味期限で、おでんを作りました。大根は昨日、Aコープ能都店で買ってきたものかと思います。生卵のパックを開けて５個をおでんのゆで卵にしたのですが、鍋に入れた直後に残りの卵をパックごと床に落としてしまい全部割れてしまいました。

　買い物に出かける頃には雪が降っていました。けっこう寒くはなっています。テレビはずっとNHKの紅白歌合戦をつけています。以前とは番組の雰囲気が変わっているようにも感じますが、知らない曲も多いです。

　正月らしさは感じておらず、１２月も２０日を過ぎた頃からずいぶん早かったように感じます。

〈〈〈：Emacs： 2019-12-31（火曜日）22：25 　〈〈〈

* 「ロイター通信は、「ゴーン元会長の突然の逃亡は、日本の司法制度に厳しい視線を投げかけた。その司法制度とは、」という深澤諭史弁護士のリツイート
  CLOCK: [2019-12-31 火 22:33]--[2019-12-31 火 23:33] =>  1:00

〉〉〉：Emacs： 2019-12-31（火曜日）22：33　 〉〉〉

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kurodalawoffice（黒田法律事務所 弁護士黒田厚志） 日時：2019-12-31 22:33／2019/12/31 21:35 URL： https://twitter.com/kk_hirono/status/1212003805409099778 https://twitter.com/kurodalawoffice/status/1211989317029023744
> ロイター通信は、「ゴーン元会長の突然の逃亡は、日本の司法制度に厳しい視線を投げかけた。その司法制度とは、容疑者を長期間拘束し、１日８時間におよぶ取り調べの際に弁護士が立ち会うことを禁止する、というものだ」と伝えています。  https://t.co/eJx8lVB9WR
▶▶▶　　　　　End　　　　　▶▶▶

RT fukazawas（深澤諭史）｜kurodalawoffice（黒田法律事務所 弁護士黒田厚志） 日時：2019-12-31 21:45／2019-12-31 21:35 URL： https://twitter.com/fukazawas/status/1211991673988739073 https://twitter.com/kurodalawoffice/status/1211989317029023744
> ロイター通信は、「ゴーン元会長の突然の逃亡は、日本の司法制度に厳しい視線を投げかけた。その司法制度とは、容疑者を長期間拘束し、１日８時間におよぶ取り調べの際に弁護士が立ち会うことを禁止する、というものだ」と伝えています。 \n  \n https://t.co/eJx8lVB9WR

[link:] 2019年12月31日22時30分の登録： ＼黒田法律事務所 弁護士黒田厚志　@kurodalawoffice＼ロイター通信は、「ゴーン元会長の突然の逃亡は、日本の司法制度に厳しい視線を投げかけた。その司法制度とは http://hirono2014sk.blogspot.com/2019/12/kurodalawoffice.html

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-12-31 22:35／2019/12/31 22:34 URL： https://twitter.com/kk_hirono/status/1212004432411447296 https://twitter.com/s_hirono/status/1212004121433145344
> 2019-12-31-223057_深澤諭史さんがリツイート黒田法律事務所弁護士黒田厚志@kurodalawoffice·55分ロイター通信は、「ゴーン元会長の突然の逃亡は、日本の司法制度に.jpg https://t.co/MS623Ia1SV
▶▶▶　　　　　End　　　　　▶▶▶

　今日はけっこうバタバタしていて落ち着きがなかったのですが、紅白歌合戦が始まってからは、台所にいる時間も長かったのですが、時間の経過がかなりゆったりと感じています。そんな年の瀬、大晦日に飛び込んだのがカルロス・ゴーン氏の逃亡になりますが、法クラは宣伝に便乗していると見えます。

　深澤諭史弁護士のタイムラインで、リツイートとして目にしたアカウントは弁護士黒田厚志とありますが、ずいぶん久しぶりに目にしたように思います。金沢弁護士会にも黒田という弁護士がいたような記憶があり、どうなのかと思ったのですが、プロフィールに大阪地裁のそば、とありました。

```
% dp -p |grep @kurodalawoffice
[link:] 2018年12月14日21時18分の登録： ＼黒田法律事務所 弁護士黒田厚志　@kurodalawoffice＼そんな簡単に結論でないがな。 ↓ 「現行の海上自衛隊が保有する艦艇においても、艦内神社は存在している。 http://hirono2014sk.blogspot.com/2018/12/kurodalawoffice.html
[link:] 2018年12月14日21時18分の登録： ＃黒田法律事務所 弁護士黒田厚志　@kurodalawoffice＃のツイート／2018-12-12_0834〜2018-12-14_2048／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月14日21時18分 http://hirono2014sk.blogspot.com/2018/12/kurodalawoffice2018-12-1208342018-12.html
[link:] 2019年01月12日11時27分の登録： ＼黒田法律事務所 弁護士黒田厚志　@kurodalawoffice＼「弁護士と会ってから話す」と話す必要も無い（∵黙秘権がある）し、「弁護士と接見しただろ、だから供述しろ http://hirono2014sk.blogspot.com/2019/01/kurodalawoffice.html
[link:] 2019年01月12日11時27分の登録： ＃黒田法律事務所 弁護士黒田厚志　@kurodalawoffice＃のツイート／2019-01-09_1658〜2019-01-11_2018／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年01月12日11時27分 http://hirono2014sk.blogspot.com/2019/01/kurodalawoffice2019-01-0916582019-01.html
[link:] 2019年04月27日21時42分の登録： ＼黒田法律事務所 弁護士黒田厚志　@kurodalawoffice＼石川先生！\n（本日の朝日朝刊） http://hirono2014sk.blogspot.com/2019/04/kurodalawoffice.html
[link:] 2019年12月31日22時30分の登録： ＼黒田法律事務所 弁護士黒田厚志　@kurodalawoffice＼ロイター通信は、「ゴーン元会長の突然の逃亡は、日本の司法制度に厳しい視線を投げかけた。その司法制度とは http://hirono2014sk.blogspot.com/2019/12/kurodalawoffice.html
```

　記録も少ない弁護士アカウントだと確認しました。前回の記録が４月２７日となっているのでずいぶん前になります。似たようなまぎわらしい弁護士アカウントはいくつかあるので記憶だけではわからなかったのですが、やはりかなり久しぶりに見かけたアカウントだったようです。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-12-31 22:51／2019/12/31 22:49 URL： https://twitter.com/kk_hirono/status/1212008357566926848 https://twitter.com/s_hirono/status/1212007946005053440
> 2019-12-31-224845_黒田法律事務所　弁護士黒田厚志（@kurodalawoffice）さん　／　Twitter.jpg https://t.co/lDeURRkRZc
▶▶▶　　　　　End　　　　　▶▶▶

　Twitterのページを開くと、ヘッダ写真が電車で、これはすぐに比較的最近に見覚えのあるものと思ったのですが、プロフィールのアイコンの写真がSLの蒸気機関車とみえるもので、こちらは記憶がはっきりしませんでした。

　タイムラインから気になったツイートをいくつか掲載し、ご紹介とします。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜gnksmz（清水元貴） 日時：2019-12-31 22:54／2019/12/31 19:14 URL： https://twitter.com/kk_hirono/status/1212009214790393856 https://twitter.com/gnksmz/status/1211953815823323136
> こうやって弁護人に責任があるとか（この記事によるとだけど）検察幹部が言ってしまうような国だから、ゴーンさんも逃げたくなったのではないだろうか。同じ法曹として恥ずかしい。 https://t.co/pcWSxcrs9C
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜gnksmz（清水元貴） 日時：2019-12-31 22:54／2019/12/31 19:32 URL： https://twitter.com/kk_hirono/status/1212009150357495809 https://twitter.com/gnksmz/status/1211958185952571392
> 裁判所にも責任はないと思う。人間が判断する以上、このようなことが起きてしまうのは仕方ない。保釈しない、という判断をしたら、今度は、被告人が十分な防御をできなくなって、冤罪を生む、などといった問題が生じる。そういうことに思いが至らない人が検察幹部をやっているのが信じられない。
▶▶▶　　　　　End　　　　　▶▶▶

　リストに登録済みのアカウントのようでしたが、余り見覚えのないアカウントでプロフィールの名前が実名らしいものとなっていて、プロフィールには弁護士（第二東京弁護士会）とありました。

　保釈に報酬はもらわないという弁護士が一人いたように思うのですが、高野隆弁護士であったような気がします。他は保釈が弁護士の収入ともなっているはずですが、弁護士が責任を問われるいわれはなく、弁護人に責任があると検察幹部が言うと、だからゴーン氏が逃げたくなる国としています。

　大阪といえば、今年は検察の不手際とされる逃走事件が２件あったかと思います。黒田厚志弁護士はTwitterのプロフィールの所在地を大阪市北区西天満としています。この西天満の弁護士というのも、ここ２ヶ月ほどの間に不手際のような小さいニュースを２件見かけています。

　小さいニュースで不手際ではありましたが、その責任の追求は弁護士の生活、人生を木っ端微塵に吹き飛ばすような大きなものでした。

_hznf_ ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW _hznf_（hznf） 日時：2019/12/31 18:28 URL： https://twitter.com/_hznf_/status/1211942302018609152
> いや、何で弁護人に責任があるんだよ https://t.co/89Po8SIZ4w
▷▷▷　　　　　End　　　　　▷▷▷

　ときどき見かけてきたネコのアイコンの弁護士らしいアカウントで、ブロックはされていない可能性が高いと思いながらリツイートを試みたのですが、ブロックされていることを確認しました。ブロックされた上記のツイートは、次の産経ニュースを公式引用しています。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Sankei_news（産経ニュース） 日時：2019-12-31 23:08／2019/12/31 18:23 URL： https://twitter.com/kk_hirono/status/1212012567536660481 https://twitter.com/Sankei_news/status/1211941048768819200
> 「世界に恥さらした」…出国のゴーン被告、検察の懸念的中　裁判所も動揺 https://t.co/Qc1LD69Tjy  ある検察幹部は「いつか逃げると思っていた。日本の刑事司法の恥を世界にさらした裁判所と弁護人の責任は重い」と痛烈に批判します。
▶▶▶　　　　　End　　　　　▶▶▶

　リンクの記事を開いていない段階なので未確認ですが、ツイートの内容は見出し付きの記事のリンクの別に、コメントか引用なのか判然としない部分があって、それがニュースサイトのツイートとは思えないようなものとなっています。

```
ゴーン被告側はただちに保釈を請求したが、捜査の過程でゴーン被告の妻、キャロルさんが事件関係者と接触していたことが発覚するなどしたため、特捜部は証拠隠滅の恐れが高いなどとして強く反対。だが４月２５日、東京地裁の島田一裁判官は証拠隠滅の恐れを認めながらも「弁護人らの指導監督が徹底している」などとして保釈を許可した。

［source：］「世界に恥さらした」…出国のゴーン被告、検察の懸念的中　裁判所も動揺 - 産経ニュース https://www.sankei.com/affairs/news/191231/afr1912310017-n1.html
```

　どうも保釈を許可したという裁判官の実名が報道されているようです。「東京地裁の島田一裁判官は証拠隠滅の恐れを認めながらも「弁護人らの指導監督が徹底している」などとして保釈を許可した。」とあります。

　どうも産経ニュースのツイートにあるような記述は記事に見当たらなかったので、次に確かな参考情報として記事の全文引用をしておきます。

```
　ゴーン被告側はただちに保釈を請求したが、捜査の過程でゴーン被告の妻、キャロルさんが事件関係者と接触していたことが発覚するなどしたため、特捜部は証拠隠滅の恐れが高いなどとして強く反対。だが４月２５日、東京地裁の島田一裁判官は証拠隠滅の恐れを認めながらも「弁護人らの指導監督が徹底している」などとして保釈を許可した。

　ある検察幹部は「弁護人の責任は十分ある。あの手この手を尽くして細かい条件と引き換えに得た保釈の結果が逃亡だ」と憤る。別の幹部は「いつか逃げると思っていた。日本の刑事司法の恥を世界にさらした裁判所と弁護人の責任は重い」と痛烈に批判する。

［source：］「世界に恥さらした」…出国のゴーン被告、検察の懸念的中　裁判所も動揺 - 産経ニュース https://www.sankei.com/affairs/news/191231/afr1912310017-n1.html
```

　全文引用をしてから、私の見落としによる勘違いがあったことに気がついたので、全文の引用は取りやめ部分の引用としました。

　時刻は２３時２１分です。出演は記事を読んだものの記憶にはなかった松田聖子が出てきて、ちょっと驚いていました。ずいぶんと久しぶりに姿を見たということもありますが、年齢の変化がよくわからないです。声の方がいくらか変わっているように感じ、喉の調子がよくないのかもしれないです。

〈〈〈：Emacs： 2019-12-31（火曜日）23：33 　〈〈〈

