* 「検察側証人の畢竟独自の見解感がすごい。乳腺外科医「わいせつ事件」高裁初公判、出廷した精神科医の証言とは（ダイヤモンド・オンライン）」という刑裁サイ太のリツイート
  CLOCK: [2020-02-09 日 11:27]--[2020-02-09 日 13:43] =>  2:16

〉〉〉：Emacs： 2020-02-09（日曜日）11：27　 〉〉〉

:CATEGORIES: 刑裁サイ太,医療問題,乳腺外科医わいせつ事件,検察側証人,控訴審

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜laparkadejapon（アリアンデルの猫） 日時：2020-02-09 11:28／2020/02/08 08:30 URL： https://twitter.com/kk_hirono/status/1226332115400134656 https://twitter.com/laparkadejapon/status/1225924758589464576
> 検察側証人の畢竟独自の見解感がすごい。  乳腺外科医「わいせつ事件」高裁初公判、出廷した精神科医の証言とは（ダイヤモンド・オンライン） https://t.co/8YYYy0JL0w
▶▶▶　　　　　End　　　　　▶▶▶

RT uwaaaa（サイ太）｜laparkadejapon（アリアンデルの猫） 日時：2020-02-08 16:34／2020-02-08 08:30 URL： https://twitter.com/uwaaaa/status/1226046582312722433 https://twitter.com/laparkadejapon/status/1225924758589464576
> 検察側証人の畢竟独自の見解感がすごい。 \n  \n 乳腺外科医「わいせつ事件」高裁初公判、出廷した精神科医の証言とは（ダイヤモンド・オンライン） https://t.co/8YYYy0JL0w

　テレビにハズキルーペのCMがあって、「ハズキルーペだいすきというセリフがありましが、まさに「法クラ弁護士だいすき」と言った内容の記事でした。昨夜に読んでいます。女性と思われる名前の医療ジャーナリストという人の記事でした。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-02-09 11:33／2020/02/09 00:06 URL： https://twitter.com/kk_hirono/status/1226333163862888448 https://twitter.com/s_hirono/status/1226160442545852418
> 2020-02-08-193150_サイ太@uwaaaa·2時間会務に精を出していた頃も特においしい事件の紹介もなかったので、元々村二分くらいになってたような気がする.jpg https://t.co/fhTGmtexrq
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-02-09 11:32／2020/02/09 00:06 URL： https://twitter.com/kk_hirono/status/1226333124503564288 https://twitter.com/s_hirono/status/1226160473059409921
> 2020-02-08-193614_サイ太さんがリツイートアリアンデルの猫@laparkadejapon·11時間検察側証人の畢竟独自の見解感がすごい。乳腺外科医「わいせつ事件」高裁初公判、.jpg https://t.co/Y2u9zIR9P4
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-02-09 11:32／2020/02/09 00:06 URL： https://twitter.com/kk_hirono/status/1226333095659331584 https://twitter.com/s_hirono/status/1226160503937875968
> 2020-02-08-194905_乳腺外科医「わいせつ事件」高裁初公判、出廷した精神科医の証言とは（ダイヤモンド・オンライン）　-　Yahoo!ニュース.jpg https://t.co/OUaE52H4Mq
▶▶▶　　　　　End　　　　　▶▶▶

　スクリーンショットの記憶は昨夜の１９時半頃ですが、匿名弁護士刑裁サイ太のタイムラインを開き、「おいしい事件の紹介」というのはなんのことなのかと思いながら、少し下に見つけたのが乳腺外科医のわいせつ事件に関するリツイートでした。

　２，３日前になりますが、同じ乳腺外科医わいせつ事件の同じ控訴審初公判に関する記事をネットで読んでいて、違った視点から書かれた記事になりますが、その内容の落差に驚きました。２，３日前のものは週刊文春の記事のようになっていたと思います。高野隆弁護士ともからめた内容でした。

　昨日は午後に、個人的ではない用事でコンセールのと、に行き、用事が終わった後に同じ建物にある図書館に入り、週刊文春と週刊新潮の目次の部分だけ目を通したのですが、乳腺外科医わいせつ事件の見出しには気が付かず、たぶん小さい記事の扱いになっていたのかと思います。

　図書館にある新聞にも少し目を通したのですが、北陸中日新聞ではコインハイブ事件の逆転有罪判決について、見出しに「パソコンの無断使用」などとあったのが目を引き、気になりました。

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020/02/07 10:34 URL： https://twitter.com/hirono_hideki/status/1225593727571247104
> 男性医師は女性患者の胸を舐めたのか、それとも“せん妄”による幻覚だったのか | 文春オンライン https://t.co/DbtpDl7EwT

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020/02/07 10:46 URL： https://twitter.com/hirono_hideki/status/1225596597846724609
> (2ページ目)男性医師は女性患者の胸を舐めたのか、それとも“せん妄”による幻覚だったのか | 文春オンライン https://t.co/Zol4s9D0i8 \n 本件の男性医師は警察が駆け付けた途端、逃げるように病院を後にしてしまった… https://t.co/JdkOnLMl2j

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020/02/07 11:39 URL： https://twitter.com/hirono_hideki/status/1225610101630783488
> 2020年02月07日10時32分の登録： ＼ぽぽひと@睡眠重視　@popohito＼弁護人、高野先生か。\n\n男性医師は女性患者の胸を舐めたのか、それとも“せん妄”による幻覚だったのか | 文春オンライン https://t.co/HBI0z4RZ0H

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「文春」の検索結果 - Twilog https://t.co/qkaGXPX0SR

　Twilogから調べました。２月７日として記録がありました。昨日は８日なので前日の一日前になりますが、私としては２，３日前という感覚でいました。どうも７日の金曜日に控訴審の初公判があってそれでニュースになっていたようです。

　図書館では森村誠一の「悪魔の飽食」を探すという目的もあったので、北陸中日新聞の記事は見出しを読んだだけだったのですが、考えてみるとテレビでがんがん報道する注目の事件、刑事裁判でもないのに控訴審の初公判が、北陸中日新聞の記事になっていたのは珍しく感じられることです。

　私も２，３回したネットで見かけた情報ですので知らない人が多そうですが、中日新聞の子会社が東京新聞とのことです。その東京新聞の記者になっていたと思いますが、望月衣塑子記者がいて安倍政権に批判的な取材をすることで話題を見かけるようになっています。

```
望月 衣塑子（もちづき いそこ、1975年 - ）は、日本の新聞記者。中日新聞社の社員。2020年2月現在、東京本社社会部記者。

［source：］望月衣塑子 - Wikipedia https://ja.wikipedia.org/wiki/%E6%9C%9B%E6%9C%88%E8%A1%A3%E5%A1%91%E5%AD%90
```

　名前を単語登録する目的で検索をしていたのですが、検索結果の要約に「中日新聞社の社員」、「東京本社社会部記者」というのが見えていました。「日本歯科医師連盟のヤミ献金事件をスクープした[2][10]。」というのもありますが、この短いものが本文となっています。

　昨年の１０月辺りまで北陸中日新聞を購読していましたが、紙の利用と新聞は広告チラシをみるぐらいで、開くこともあまりないぐらいでした。それでもネットの情報では、かなり偏向気味の刺激的な記事を書いているということは知っていました。

```
菅官房長官の定例会見をめぐって、東京新聞の望月衣塑子記者が「番記者たちが『望月は指させない』と内々で決めた」とツイートしたことに対し、毎日新聞が6日に「事実に反するツイート拡散」と猛反論を行い、ネット上で「内ゲバ」などと話題になっている。

［source：］望月記者の事実無根ツイート。毎日新聞が怒りの猛反論報道 – アゴラ http://agora-web.jp/archives/2044175.html
```

　この問題も昨日あたりに記事を１つ読んでいたのですが、やはり「東京新聞の望月衣塑子記者」とあります。３日前になる２月６日の記事です。さきほどの引用部分を読み返して気がついたのですが、中日新聞、東京本社とあります。中日新聞といえば名古屋で、球団の中日ドラゴンズにもなっているはず。

```
中日新聞（ちゅうにちしんぶん）は、日本の新聞社・中日新聞社が東海地方を中心とする地域で発行する日刊新聞である。

戦時統合により新愛知と名古屋新聞が統合して創刊。その関係で、今なお大島家と小山家の2オーナー制が続いている。名古屋圏では圧倒的なシェアを誇っており2017年9月現在、中日新聞単独部数は235万部（朝刊）［2］で、全国6位だが、中日新聞東京本社が発行する東京新聞や中日新聞北陸本社が発行する北陸中日新聞などを併せれば約302万部（朝刊）［2］（ABCレポート、但し日刊県民福井は自社公称）に達し、地方紙ながら発行部数では毎日新聞（約294万部）、日経新聞（約260万部）、産経新聞（約155万部）といった全国紙の体裁を取っている新聞を上回り、参考記録ながら全国第3位相当の部数となる。

［source：］中日新聞 - Wikipedia https://ja.wikipedia.org/wiki/%E4%B8%AD%E6%97%A5%E6%96%B0%E8%81%9E
```

　疑問に思ったことの確認のためしらべたのですが、発行部数が毎日新聞や産経新聞を上回り、地方紙でありながら「参考記録ながら全国第3位相当」とあります。１位と２位は読売新聞と朝日新聞が想像されますが、書かれてはいないようです。

　中日新聞東京本社が発行する東京新聞、中日新聞北陸本社が発行する北陸中日新聞とあり、ページの右側には小さな写真付きで中日新聞本社とあります。

　中日新聞北陸本社というのが気になり、リンクになっているのを開いたのですが、住所が金沢市駅西本町2丁目12番30号となっているので驚きました。同じ石川県に住んでいてもほとんど聞いたことのなかった中日新聞北陸本社になります。

　金沢市駅西本町の中日新聞北陸本社はWikipediaに写真がありますが、かなり大きそうな建物です。平成１０年に関係者KYNの配管工事の仕事で行ったのが、香林坊の北陸中日新聞の会社事務所だったと思います。古い雑居ビルのような感じでした。

　香林坊１０９の隣の方で南町の広い道路に面していました。斜めに香林坊の交差点があってミスタードーナツの店が見えたような記憶もあります。レシプロソーというのを使い説明を受けたのですが、固定して配管を切断する機械でした。珍しく１日で終わった仕事であったとも思います。

```
2/8(土) 6：01配信

初公判があった東京高裁　Photo by Maki Fukuhara
　2016年、男性乳腺外科医が手術したばかりの女性患者から、準強制わいせつ罪で訴えられ、検察から懲役3年を求刑された事件があった。昨年、東京地裁は乳腺外科医に無罪の判決を言い渡したが、検察は東京高裁に控訴した。2月4日、初公判が開かれた。（医療ジャーナリスト　福原麻希）

【「患者の言動とふるまいの時系列図」など図版はこちら】


［source：］乳腺外科医「わいせつ事件」高裁初公判、出廷した精神科医の証言とは（ダイヤモンド・オンライン） - Yahoo!ニュース https://headlines.yahoo.co.jp/article?a=20200208-00227956-diamond-soci
```

　４ページに分かれかなり長文の記事でした。時間も掛かるのでもう一度読み直す気持ちにはなれないですが、とても考えさせられ参考になる記事でした。被告人を擁護、支援するような内容の記事ですが、それは同時に正常な精神状態ではなかったとされた被害者の否定にもなります。

　術後のせん妄が争点になった事件、刑事裁判であります。ざっと「せん妄」という文字を探したのですが、すぐには見当たらず、その前に「幻覚や錯覚」というのが目に入っていました。

　せん妄について、たしかアメリカでの症例を持ち出したのが、高野隆弁護士になります。高野隆弁護士その人の言葉として記事を読んだのかは忘れましたが、弁護団の主張としては少なくともそうなっていました。

　そういえば、ぽぽひと、という注目アカウントのツイートとして知ったのが、同じ乳腺外科医わいせつ事件の控訴審初公判を取り上げた文春オンラインの記事になります。高野隆弁護士に対する懐疑と批判が入り混じったように感じられた記事でした。

　文春オンラインの記事は、過去に首を傾げたくなったり、行き過ぎた論理の飛躍を感じるものもあったのですが、すごくわかりやすく論理的に被告人の真犯人性を印象づけていました。

　別のエントリーとして取り上げておきたいと思いますが、このエントリーでご紹介した医療ジャーナリスト福原麻希氏のダイヤモンドオンラインの記事と内容を比較すれば、違いが鮮明になるかと思います。

〈〈〈：Emacs： 2020-02-09（日曜日）13：43 　〈〈〈

* Twitterの通知にあった山口貴士弁護士の誤認逮捕のニュースから同じライブドアニュースの犬鳴村伝説の記事、そして久しぶりに調べた石川県津幡町の怪奇スポット「牛首トンネル」
  CLOCK: [2020-02-09 日 15:51]--[2020-02-09 日 16:31] =>  0:40

〉〉〉：Emacs： 2020-02-09（日曜日）15：51　 〉〉〉

:CATEGORIES: 山口貴士弁護士,誤認逮捕,心霊スポット,都市伝説

　いちおう、「都市伝説」というキーワードをカテゴリーに加えておきました。読んだ記事に都市伝説という言葉はなかったかもそれないですが、社会的現象としての注目点があり、都市伝説と共通したものを感じております。さらにいえば深澤諭史弁護士に代表される現代の弁護士伝説です。

　メモや備忘をかねたツイートは次のようになっています。

RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜otakulawyer（山口貴士 aka無駄に感じが悪いヤマベン） 日時：2020-02-09 14:11／2020-02-08 20:42 URL： https://twitter.com/hirono_hideki/status/1226373111257296896 https://twitter.com/otakulawyer/status/1226109142181376000
> ネコの写真を撮影していなければ20日勾留コース。女性の被害証言もうのみにせずに裏を慎重にとらないと冤罪だらけになる。 \n  \n &gt;男子学生は事件直前、友人宅の敷地内で猫の写真を撮影していたことが判明。 \n   https://t.co/v8TYSSaJpv

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-02-09 15:59／2020/02/09 14:38 URL： https://twitter.com/kk_hirono/status/1226400123703312389 https://twitter.com/hirono_hideki/status/1226379743588577280
> 「牛首トンネル」は石川最恐の心霊スポット！場所や危険な地蔵の噂を調査！ | TRAVEL STAR https://t.co/ss2DqiT31P 宮島隧道が牛首トンネルと呼ばれるようになったのは、トンネルがある牛首村の八坂神社の… https://t.co/tCHC5qWmWg
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-02-09 15:58／2020/02/09 14:36 URL： https://twitter.com/kk_hirono/status/1226400078807457792 https://twitter.com/hirono_hideki/status/1226379221875822592
> 「牛首トンネル」は石川最恐の心霊スポット！場所や危険な地蔵の噂を調査！ | TRAVEL STAR https://t.co/ss2DqiT31P
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-02-09 15:58／2020/02/09 14:35 URL： https://twitter.com/kk_hirono/status/1226400054551834624 https://twitter.com/hirono_hideki/status/1226378956196044801
> 牛首トンネル（うしくび）　　:金沢観光情報 【 きまっし金沢 】 https://t.co/Frrpk0wkuK
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-02-09 15:58／2020/02/09 14:30 URL： https://twitter.com/kk_hirono/status/1226400021131620358 https://twitter.com/hirono_hideki/status/1226377779077210113
> 【閲覧注意】最恐の心霊スポット「犬鳴トンネル」へ潜入…『犬鳴村』は実在した＜写真36点＞ - 映画 Movie Walker https://t.co/omfTXlWyoJ 日本政府の統治が及ばない、狂人が住んでいるなど数々の都市伝説を生んだ犬鳴村とは | 撮影/黒羽政士
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-02-09 15:58／2020/02/09 14:16 URL： https://twitter.com/kk_hirono/status/1226399979482140672 https://twitter.com/hirono_hideki/status/1226374323868295169
> 斧を持った男が…なぜ「犬鳴村伝説」はいまだ語り継がれるのか - ライブドアニュース https://t.co/E5kwU3Jdlx
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-02-09 15:58／2020/02/09 14:16 URL： https://twitter.com/kk_hirono/status/1226399959190138880 https://twitter.com/hirono_hideki/status/1226374193169592320
> 観光客激減で鹿せんべいに群がるシカ「じらさず与えて」と注意も - ライブドアニュース https://t.co/cjR4hL6lnG
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-02-09 15:58／2020/02/09 14:14 URL： https://twitter.com/kk_hirono/status/1226399939661426690 https://twitter.com/hirono_hideki/status/1226373853003186182
> 公然わいせつ事件で大学生を誤認逮捕 被害者が間違いないと証言するも - ライブドアニュース https://t.co/RPRr1jQMbU
▶▶▶　　　　　End　　　　　▶▶▶

　牛首トンネルがある牛首村の八坂神社、と、牛首村とあることに気が付きましたが、石川県で牛首村というのは白峰村の旧地名になります。牛首紬というのもあったように思います。白峰村は石川県で最も福井県に近い集落ということで、宇出津小学校の授業で習ったような記憶があります。

　Googleマップでは津幡町字牛首となっていました。石川県河北郡になるはずですが、金沢市とは入り組むようなかたちで隣接しています。倶利伽羅という地名があり、木曽義仲の火牛の計の伝承があります。実際は中国の晏嬰の時代と晏子の本で読んだこともあります。

```
由来はインドの古典！クリカーラ峠とは？
石川県津幡（つばた）町と富山県小矢部（おやべ）市の境界にあるのが倶利伽羅峠だ。
峠にある日本3大不動の1つ、倶利伽羅不動尊の本尊”倶利伽羅不動明王”から地名になった。
倶利伽羅の由来はインドの古典サンスクリット語”kulikah”（クリカーラ）であり、黒い龍王の名前だそうだ。
不動尊では「剣に黒い龍が巻きついたお不動様」と訳されている。

［source：］倶利伽羅峠 | 金沢ライフマップ https://kanazawa-life.com/lifemap/vol-024/
```

　上記の引用部分には倶利伽羅という地名の由来をインドの古典サンスクリット語「クリカーラ」とし、倶利伽羅不動明王から地名になったとしています。倶利伽羅不動尊というお寺のことは、ネットで知るようになりました。毎日のようにその辺りの国道８号線を通行していた時期はありました。

　倶利伽羅峠と、峠がつくと個人的に旧道をイメージするのですが、国道８号線で石川県と富山県の県境、その石川県側という漠然としたイメージが倶利伽羅になります。県境にはトンネルがあったように思いますが、金沢からくるとトンネルの手前はしばらく上り坂が続いていました。

　上り坂が始まる前の平地で、金沢から富山に向かうと右手に入浴施設があって、平成１０年、そこも関係者KYNの配管工事の仕事でしばらく通ったことがありました。ネットの情報では現在、倶利伽羅に道の駅があるのですが、確認はしていないものの同じ場所の可能性は考えています。

[link:] » 字倶利伽羅 - Google マップ https://t.co/JcKwbNNseq

　Googleマップで調べて初めて気がついたのですが、倶利伽羅という地名の場所は国道８号線とまったく接しておらず、離れていました。さらに離れた場所には倶利伽羅駅や津幡署倶利伽羅駐在所というのが見えます。この駐在所の前の道路は、国道８号線の旧道になりそうな感じです。

〈〈〈：Emacs： 2020-02-09（日曜日）16：31 　〈〈〈

