* 忘れていた、ポッキーゲーム本体のツイート、自家製パンチェスタという法クラ（弁護士の可能性大）のツイート
  CLOCK: [2020-01-12 日 00:14]--[2020-01-12 日 00:33] =>  0:19

〉〉〉：Emacs： 2020-01-12（日曜日）00：14　 〉〉〉

［link：］ 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”ポッキーゲーム”／データベース登録済みツイート：2020年01月11日22時15分の記録：ユーザ・投稿：53／70件 http://hirono2014sk.blogspot.com/2020/01/regexp2020011122155370.html

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜jikapan（自家製パンチェッタ） 日時：2020-01-12 00:14／2014/11/11 16:27 URL： https://twitter.com/kk_hirono/status/1216015631390142469 https://twitter.com/jikapan/status/532072156973109248
> そういえば妻とまだ恋人だったとき、本当にポッキーゲームを知らなくて、教えてくれ、と言ったら妻が口にポッキーを咥えて「んー」というから真似して私もポッキー咥えて「んー」ていったら妻大爆笑。 ホントおかしい話ですよね。私独身で妻なんか居ないのに。おかしい。私頭おかしい。
▶▶▶　　　　　End　　　　　▶▶▶

　実は、最近ツイートをほとんど見かけていなかったアカウントになります。ツイート本体の掲載を忘れていなければ再び取り上げることはなかったかと思います。

77：2020-01-11_23:38:20 ＊ 「無罪主張していた被告人からの感謝の言葉、これが一番メンタルを削られる。」という深澤諭史弁護士のリツイートで思い出した、過去の法クラの流行語「ポッキーゲーム」のこと https://hirono-hideki.hatenadiary.jp/entry/2020/01/11/233818

　これから久しぶりにアカウントのタイムラインを開いてみます。

```
転職組で歳食ってますが、登録して１０年以上過ぎたけどまだまだ若手弁護士。 扱い多いのは離婚相続など家事事件と刑事事件。 刑事以外の分野の企業法務はほぼイソ弁時代だけなので商事分野実務のツイは疑って見てください。 法廷よりゲーム，マンガ，アニメ等イベントのお客としての方が良く会える系法曹。
ワープロは一太郎派です。
港のある町2012年7月からTwitterを利用しています
4,977 フォロー中
5,501 フォロワー

［source：］自家製パンチェッタ（@jikapan）さんの返信があるツイート / Twitter https://twitter.com/jikapan
```

　上記にTwitterアカウントのプロフィールを引用しましたが、いつの間にか内容が変わっているように感じました。プロフィールのアイコンはダイオウグソクムシですが、暗い深海の底をイメージさせるような濃い青色の背景をベースとしたものです。

　ずいぶん久しぶりに見かけた感があるアカウントですが、他の法クラのTwitterのタイムラインで見かけていなかったのは、やばいと感じた法クラのアカウントをブロックし、リツイートを出来なくさせていたという可能性はあるかと思います。健全性がうかがえるのかもしれないです。

[link:] 2020年01月12日00時21分の登録： ＃自家製パンチェッタ　@jikapan＃のツイート／2019-12-31_1644〜2020-01-11_2031／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2020年01月12日00時21分 http://hirono2014sk.blogspot.com/2020/01/jikapan2019-12-3116442020-01.html

　記録済みのまとめ記事を確認しました、昨年２０１９年８月以降のものを次に列挙します。わりと最近にも記録の作成があったと確認しました。

```
[link:] 2019年08月05日16時19分の登録： ＼自家製パンチェッタ　@jikapan＼弁護士が住所地及び事務所所在地以外で資金洗浄をしていたと思われる証拠写真。\n当該弁護士は、事務所所在地近くで資金洗浄したと思われる http://hirono2014sk.blogspot.com/2019/08/jikapan.html
[link:] 2019年08月11日14時33分の登録： ＼自家製パンチェッタ　@jikapan＼漢字はほぼ読めない障害持った方が、逮捕直後に漢字交じりの「自発的に出した犯行告白の上申書」出してたわ。何十もの漢字のとこ、ほぼぜん http://hirono2014sk.blogspot.com/2019/08/jikapan_11.html
[link:] 2019年08月14日20時00分の登録： 　＼自家製パンチェッタ　@jikapan＼今日はサイ太先生の大嘘判例八百選を入手するためだけにコミケに参加したので、結局、なんと他に一冊の本も入手いたしませんでした。\nホン http://hirono2014sk.blogspot.com/2019/08/jikapan_14.html
[link:] 2019年08月23日20時22分の登録： ＃自家製パンチェッタ　@jikapan＃のツイート／2019-08-17_1520〜2019-08-23_2013／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年08月23日20時22分 http://hirono2014sk.blogspot.com/2019/08/jikapan2019-08-1715202019-08.html
[link:] 2019年08月27日23時51分の登録： ＼自家製パンチェッタ　@jikapan＼代理人の方が抗議を出されているとおり氏名公表がご遺族の意思でないなら、行政機関京都府警の公表をマスコミが遺族の方の意思を無視し垂れ http://hirono2014sk.blogspot.com/2019/08/jikapan_27.html
[link:] 2019年10月01日18時14分の登録： ＼自家製パンチェッタ　@jikapan＼現実の事件を扱うときはせめて専門家呼ぼうよ…。\n弁護士の弁護権の濫用による一層の混迷　― 千葉ゴルフ場鉄塔崩壊事件 ―：データ・マ http://hirono2014sk.blogspot.com/2019/10/jikapan.html
[link:] 2019年10月12日01時09分の登録： ＼過食弁　@juntaba1＼返信先: \n@jikapan\nさん\nそうですよね。鎌倉がもう目前です。御恩に報いるため立ち上がらねばって何の話でしたっけ http://hirono2014sk.blogspot.com/2019/10/juntaba1-jikapan.html
[link:] 2019年10月12日19時46分の登録： ＼自家製パンチェッタ　@jikapan＼返信先: \n@juntaba1\nさん\nどうも。アンドロメダの帝王です。 http://hirono2014sk.blogspot.com/2019/10/jikapan-juntaba1.html
[link:] 2019年10月14日01時22分の登録： ＼自家製パンチェッタ　@jikapan＼少なくとも人命では過去最大の被害ではなく終わりそうだけど「おおげさに騒いでも大したことない」よりは「情報を早く出して、事前にみんな http://hirono2014sk.blogspot.com/2019/10/jikapan_14.html
[link:] 2019年10月15日17時32分の登録： ＼自家製パンチェッタ　@jikapan＼承継的共同正犯(共犯の因果関係(離脱))の問題の罪名選択などの目の付け所は、去り際のセリフ。\n・無言で去る\n・「俺やめるわ」\n・「 http://hirono2014sk.blogspot.com/2019/10/jikapan_15.html
[link:] 2019年10月22日22時24分の登録： ＼自家製パンチェッタ　@jikapan＼修習地を「飛ばされた」と言う修習生のことを責めるとき「A班B班問題」調査で、地方修習になると主な項目だけで平均５０万円以上の出費を http://hirono2014sk.blogspot.com/2019/10/jikapanab.html
[link:] 2019年11月03日00時22分の登録： ＼自家製パンチェッタ　@jikapan＼返信先: \n@un_co_the2nd\nさん\n相手の自己都合でも正義を返せという決定を出す独立行政法人は悪。（話が逸れる） http://hirono2014sk.blogspot.com/2019/11/jikapan-uncothe2nd.html
[link:] 2019年11月09日00時13分の登録： ＼自家製パンチェッタ　@jikapan＼山口先生のプロフィールを拝見したら私の一年先輩で、憲法の先生も同じで、やっぱり私も憲法学は小林節先生の価値相対主義が根本にあるの思 http://hirono2014sk.blogspot.com/2019/11/jikapan.html
[link:] 2019年11月11日22時53分の登録： ＼自家製パンチェッタ　@jikapan＼以前、弁護士とかのオフ会的なもので名刺交換した後にアカウント名を名乗ったら「あー！ポッキーゲームの！昔そのツイート見ました！」って http://hirono2014sk.blogspot.com/2019/11/jikapan_11.html
[link:] 2019年11月11日23時12分の登録： ＼自家製パンチェッタ　@jikapan＼返信先: \n@TGN54\nさん\nこれは適用条文に該当するしないに関わらず有罪です。 http://hirono2014sk.blogspot.com/2019/11/jikapan-tgn54.html
[link:] 2019年11月20日21時21分の登録： ＼自家製パンチェッタ　@jikapan＼でっかく張り紙とか旗とか出してて、「これ、深澤先生案件なんだろうか…。」とか思いながら、余りに堂々としてるから大丈夫なんかな、と麻 http://hirono2014sk.blogspot.com/2019/11/jikapan_20.html
[link:] 2019年12月12日20時39分の登録： ＃自家製パンチェッタ　@jikapan＃のツイート／2019-12-06_1328〜2019-12-12_1857／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年12月12日20時39分 http://hirono2014sk.blogspot.com/2019/12/jikapan2019-12-0613282019-12.html
[link:] 2019年12月27日03時12分の登録： ＼自家製パンチェッタ　@jikapan＼あれ？ようやく今気付いたんだけどサイ太先生って冬コミはサークル参加されないのかな？\n今回はサイゲが企業ブースでプリコネやゾンサガの http://hirono2014sk.blogspot.com/2019/12/jikapan.html
[link:] 2020年01月02日20時47分の登録： ＼自家製パンチェッタ　@jikapan＼サイ太先生の大嘘判例八百選入手のためだけに冬コミ参加してます。まっすぐサイ太先生のスペースを目指していますが、無事、へんたいふしん http://hirono2014sk.blogspot.com/2020/01/jikapan.html
[link:] 2020年01月12日00時21分の登録： ＃自家製パンチェッタ　@jikapan＃のツイート／2019-12-31_1644〜2020-01-11_2031／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2020年01月12日00時21分 http://hirono2014sk.blogspot.com/2020/01/jikapan2019-12-3116442020-01.html
```

　深澤諭史弁護士を深澤先生、刑裁サイ太をサイ太先生とするツイートの記録が見られ、他にも余り記憶にはないツイートの記録が散見されました。１月２日にも記録があって、それも「サイ太先生の大嘘判例八百選入手のためだけに冬コミ参加してます。」というのは意外でした。

〈〈〈：Emacs： 2020-01-12（日曜日）00：33 　〈〈〈

