* 「サンドのお風呂いただきます選「熱海　前後編」」がきっかけで、静岡県熱海市が神奈川県小田原市の近くだと知ったこと
  CLOCK: [2020-01-04 土 13:53]--[2020-01-04 土 14:40] =>  0:47

〉〉〉：Emacs： 2020-01-04（土曜日）13：53　 〉〉〉

```
サンドのお風呂いただきます選「熱海　前後編」［字］　ウェブ検索
1/4 (土) 13：05 ～ 13：59 （54分） この時間帯の番組表
ＮＨＫ総合１・金沢(Ch.1)
バラエティー - 旅バラエティ
番組概要
サンドウィッチマンとスピードワゴンが静岡県熱海へ！幻の魚・アラを堪能し、絶景温泉や大人気の来宮神社を巡り、頑固職人の美しき和風風呂や破天荒漁師の大家族と出会う！

番組詳細
人気温泉地、静岡県・熱海でサンドウィッチマンとスピードワゴンが爆笑湯けむり旅！幻の魚・アラやサザエを堪能し、女性に話題のスポット・来宮神社へ。そこで、65歳の見習い神職と出会い、「夫婦愛あふれる修行風呂」をいただく。さらに観光名所の源泉をめぐり、温泉卵に舌鼓。出会ったのは、頑固な瓦職人の「美しすぎる和風風呂」、そして、4回の結婚と離婚を経験した破天荒漁師の複雑な関係の大家族の生きざまに思わず感動！

【出演】サンドウィッチマン，【ゲスト】スピードワゴン，【語り】コムアイ

［source：］サンドのお風呂いただきます選「熱海　前後編」［字］ - Gガイド.テレビ王国 https://tv.so-net.ne.jp/schedule/134816202001041305.action
```

　NHKで１２時のニュース番組をみていた後、ほとんどみないままにテレビをつけていたところ始まった番組で、しばらくは番組名もわからず、民放の新春特別番組なのかと思っていました。

　テレビを消そうかと思ったタイミングで出てきたのが、６５歳の見習い神職のコーナーだったと思います。見習い巫女といえば、パチスロ；パチンコ機の「伝説の巫女」になるのですが、そのことがあって番組に集中することになりました。

　この「サンドのお風呂いただきます」という番組を最初に観たように記憶にあるのが京都市の大きな神社の参道にあるという料理店でした。愛宕神社であったような気もします。

```
お座敷の背景と、創業400年のお店ということでたぶんこちらのお店です。お店の制服にもちらっと店名が書いてありますね。

創業は江戸時代、愛宕神社の門前茶屋として発祥し、現在は鮎料理の名店として有名です。接待や会合にもよく使われる料亭ですが、よくこんなお店のお風呂に入れたなあ(^^;

夜は15,000円～ですが、お昼はお手頃なミニ懐石(4,800円：税サ込)やお丼もあります。

［source：］NHK「サンドのお風呂いただきます」(7/31・8/21放送)は京都・前編＆後編。日蓮宗大本山や老舗料亭のお風呂など・・・。 - 京都てっぱん日記 http://otaku-son.hatenablog.com/entry/2019/07/27/172858
```

　やはり愛宕神社でした。石川県では聞いたことがないと思う神社でもあるのですが、火の用心の信仰があると情報をみたように思います。その情報をみたのも京アニ放火殺人事件の後であったような気がします。その放火事件でも蠢きを見せ、沈静化しているのが弁護士らになります。

　ここにも結びつきがあるのが神奈川県小田原市の村松謙弁護士や神奈川県弁護士会と京都弁護士会になります。京都弁護士会に対する宗教的な異常性を感じたのは、ずいぶん前になりますが、舞鶴女子高生殺害事件における弁護活動です。

　この「サンドのお風呂いただきます」という番組では、大家族が紹介されることが多く、それをみるだけでもいろいろと考えることがありました。番組表では気が付かなかったのですが、１４時台は、北海道函館が同じく前後編として放送されています。

　伊豆半島だったと思いますが、熱海市はその西側をイメージしていたように思います。伊豆半島ではなく駿河湾で浜松市に近い辺りを想像したこともあったのですが、テレビでちょくちょくと熱海をみながら、その場所を確認しようと考えたことはなかった気がします。

　同じ静岡県の伊東市については、きっかけが思い出せないものの気になることがあって、Googleマップで場所を確認したということがありました。同じ伊豆半島の東側で、熱海市の一つ奥が伊東市になるのだと、今回気がついたように思います。

　能都中学校の修学旅行のとき、大きな箱のような駅を見たという記憶があって、熱海駅ではないかと思ったのですが、これは前にも考えたことがあって、そのときにも熱海市の場所を確認していた可能性はあります。ただ、今回、小田原市にずいぶん近いのだと見えたのがすごく印象的でした。

　能都中学校の修学旅行は２年生のときで、昭和５３年になると思われます。京都、奈良、箱根、東京の４泊５日でした。東京に向かうのに新幹線に乗ったという記憶もかすかにあります。熱海駅で新幹線を降りた可能性を今回考えたのですが、熱海に新幹線が停車するのか確認していません。

[link:] » 東海道新幹線（東京−新大阪）の路線図・停車駅 - 駅探 https://t.co/vQ5Zav41FF

　熱海が東海道新幹線の停車駅だと確認しました。東京からだと一つ手前が小田原駅、無期懲役の判決で万歳三唱したという東海道新幹線無差別殺傷事件の事件現場となったのが、小田原市の近く、被疑者が逮捕され、裁判が開かれたのも小田原市でした。

　以前、黒羽刑務所について調べた時に、小田原の少年院が廃止になるような記事を見かけました。もともと少年犯罪とは関わりのある土地柄だったようですが、特異性を放ち妖気のようなものすら漂うに感じるのが、かねて注目をしてきた神奈川県弁護士会の村松謙弁護士になります。

　そういえば、さきほどの「サンドのお風呂いただきます」の熱海の後編の始まりに、「かんいちおみや」とかいう銅像をみたのですが、昭和４０年代後半から昭和５０年代初めの頃は、テレビでみかけることが多い話であったと記憶にあります。

〈〈〈：Emacs： 2020-01-04（土曜日）14：40 　〈〈〈

* 小説『金色夜叉』、貫一お宮の物語から着想し作成した、弁護士らが検察・検事の作文だというツイートのまとめ記事
  CLOCK: [2020-01-04 土 15:47]--[2020-01-04 土 17:44] =>  1:57

〉〉〉：Emacs： 2020-01-04（土曜日）15：47　 〉〉〉

　熱海については前回の次のエントリーで取り上げています。

38：2020-01-04_14:43:24 ＊ 「サンドのお風呂いただきます選「熱海　前後編」」がきっかけで、静岡県熱海市が神奈川県小田原市の近くだと知ったこと https://hirono-hideki.hatenadiary.jp/entry/2020/01/04/144322

```
熱海駅から海に向かって歩くこと約15分。温泉旅館やホテルが立ち並ぶ国道135号線沿いに、日本髪の女性と学ランに身を包んだ男性の銅像が立っています。この像は明治時代の小説『金色夜叉』の代表的なシーンを再現したもので、舘野弘青が制作しました。主人公の間貫一（はざまかんいち）にはお宮という許嫁がいましたが、お宮がダイヤモンドの指輪に目がくらんで富豪の富山唯継に嫁いでしまいます。このことに腹を立てた貫一が、熱海海岸でお宮を問い詰め、復讐を誓うという場面を表したのがこの銅像です。「来年の今月今夜のこの月を、僕の涙で曇らせてみせる」という貫一のセリフが有名ですね。

この物語は完結する前に作者の尾崎紅葉が亡くなってしまったため、弟子の小栗風葉が完結させました。金色夜叉のヒットは、そして物語の舞台になったことで、熱海の名は一躍世間に広まったのです。その後、昭和に入ってからもこの作品は映画化やドラマ化され、今でも幅広く愛されています。

［source：］あの名作の舞台になった！熱海海岸「お宮の松」に秘められたエピソード|ゆこたび https://www.yukoyuko.net/yukotabi/archive/gm42243
```

　現在のことはわからないですが、昭和の時代は有名なお話だったと記憶にあります。前回のエントリーで書いたとおり、後半の番組の初めに銅像の写真が出てきたのですが、ロケ地とはなっておらず、その後番組内で出てくることはなかったように思います。

　上記の記事によると、明治時代の小説「金色夜叉」とあります。これも聞き覚えのあるものですが、小説の題名というのは知らなかった気がします。夜叉という言葉も最近はみかけないですが、女性っぽい鬼の面のことが夜叉と呼ばれていたように思います。

　夜叉についても調べてみないとわからないですが、女性というイメージが結びついています。その金色夜叉の小説にあるという貫一お宮の物語は、記事に説明がある通りの記憶で、簡潔にまとめられていますが、銅像になった場面の後にも先にも、知識がなく、小説であれば架空の話なのかもしれません。

　上記の記事には、金色夜叉のヒットが物語の舞台となった熱海を一躍世間に広めたとあります。昼にテレビで見た「サンドのお風呂いただきます」では、江戸時代に将軍がお風呂を楽しんでいたような話があった気がします。

　これまでに江戸時代や幕末の話として熱海という地名を見たことがなく、比較的新しく出来た地名なのかと考えることもありました。小田原城などは歴史的にも有名ですが、熱海は地理的に近いもののやはり古い時代の話を聞いたことがありません。

```
古くからの湯治の地であり、元々の地名表記は「阿多美」（阿多美郷）であったが［1］、海から熱い湯が湧き出ていたことや「あつうみが崎」とも呼ばれていたことなどから、江戸時代までには「熱海」表記が定着した［2］。

熱海温泉の開湯伝説としては、奈良時代（749年）に箱根の万巻上人が、漁民を困らせていた海中にあった泉脈を山里（大湯間歇泉）へ移し、そこに湯前神社（湯前権現）を作ったという由来が伝わっている［2］［3］。『伊豆風土記』の記述（713年）にも、大湯間歇泉を表現していると見られる箇所がある［3］。どちらの場合も、湯前神社に祀られている神である少名毘古那神に言及している。

［source：］熱海市 - Wikipedia https://ja.wikipedia.org/wiki/%E7%86%B1%E6%B5%B7%E5%B8%82
```

　気になったので調べてみましたが、江戸時代までには熱海の表記が定着していたとあります。江戸時代に熱海村は幕府直轄地（天領）だったとも記載があります。能登でも現在の輪島市門前町に黒島という天領があったとテレビでも見たことがありますが、なぜ天領だったのかはわかっていません。

　以前何かを調べていて、江戸時代に、その門前町の付近の住民が白山の麓の方に移住させられたというような話を見かけたことがありました。全国的ではないですが門前町はそばが名物で、自然薯のことをテレビで見たことがあり、今日の熱海の放送でも自然薯の話が出ていました。

```
高等中学校の学生の間貫一（はざま かんいち）の許婚であるお宮（鴫沢宮、しぎさわ みや）は、結婚を間近にして、富豪の富山唯継（とみやま ただつぐ）のところへ嫁ぐ。それに激怒した貫一は、熱海で宮を問い詰めるが、宮は本心を明かさない。貫一は宮を蹴り飛ばし、復讐のために、高利貸しになる。一方、お宮も幸せに暮らせずにいた。

お宮を貫一が蹴り飛ばす、熱海での場面（前編　第8章）［注釈 1］は有名である。貫一のセリフとして「来年の今月今夜のこの月を僕の涙で曇らせてみせる」が広く知られているが、これは舞台・映画でのもっとも簡略化したセリフに基づいたものであり、原著では次のように記述されている。

「吁（ああ）、宮（みい）さんかうして二人が一処に居るのも今夜ぎりだ。お前が僕の介抱をしてくれるのも今夜ぎり、僕がお前に物を言ふのも今夜ぎりだよ。一月の十七日、宮さん、善く覚えてお置き。来年の今月今夜は、貫一は何処（どこ）でこの月を見るのだか！　再来年（さらいねん）の今月今夜……十年後（のち）の今月今夜……一生を通して僕は今月今夜を忘れん、忘れるものか、死んでも僕は忘れんよ！　可いか、宮さん、一月の十七日だ。来年の今月今夜になつたならば、僕の涙で必ず月は曇らして見せるから、月が……月が……月が……曇つたらば、宮さん、貫一は何処かでお前を恨んで、今夜のやうに泣いてゐると思つてくれ」［3］

［source：］金色夜叉 - Wikipedia https://ja.wikipedia.org/wiki/%E9%87%91%E8%89%B2%E5%A4%9C%E5%8F%89
```

```
文芸評論家北嶋廣敏によれば、主人公・間貫一のモデルは児童文学者の巖谷小波である。彼には芝の高級料亭で働いていた須磨という恋人がいた。が、小波が京都の新聞社に2年間赴任している間に、博文館の大橋新太郎（富山唯継のモデル）に横取りされてしまった。小波は別に結婚する気もなかったのでたいして気にも留めていなかったというが、友人の紅葉が怒って料亭に乗り込み須磨を足蹴にした。熱海の海岸のシーンはそれがヒントになったという。須磨（須磨子）は、ある旅館の若主人が東京放浪中に生ませた娘であったが、舞踊にも秀でた美人で、大橋と結婚後は8人の子を生み、五女の豊子は金子堅太郎の息子・武麿に嫁いだ［4］［5］。

［source：］金色夜叉 - Wikipedia https://ja.wikipedia.org/wiki/%E9%87%91%E8%89%B2%E5%A4%9C%E5%8F%89
```

```
1980年代になって、硯友社文学全体の再評価の中で、典拠や構想についての研究が進み、アメリカの小説にヒントを得て構想されたものであるという説が有力になり、2000年7月、堀啓子北里大学講師が、ミネソタ大学の図書館に所蔵されているバーサ・M・クレー (Bertha M.Clay)、本名en：Charlotte Mary Brameの 『Weaker than a Woman（女より弱きもの）』が種本であることを解明した［6］［7］［8］［9］［10］。初出は、イギリスのen：Family Herald紙に、1878年8月17日から同年11月23日まで連載されたものである［11］。（下記外部リンク参照）

［source：］金色夜叉 - Wikipedia https://ja.wikipedia.org/wiki/%E9%87%91%E8%89%B2%E5%A4%9C%E5%8F%89
```

　友人がモデルで、作者の紅葉が旅館に乗り込み恋人を横取りした金持ちを蹴り飛ばし、それが熱海海岸のシーンのヒントになったとあります。他に、２００７年になって大学講師がアメリカに所蔵されている種本を解明したともあります。

　種本というのは余り見かけない言葉ですが、今なら著作権侵害の問題にもなるような引用や改変があったのかとも想像してしまいます。それが２００７年になって発見されたというのもすごい話ですが、未完のうちに作者である紅葉が亡くなり、門下生が書き継いだとあります。

　女性を足蹴りにするのはそれだけで大問題になりそうですが、そういう場面は昭和の頃にテレビでみたような記憶が微かに残っています。なにかアニメのようなものでみたような気もするのですが、遠い記憶なのですごくぼやけています。

　「宮さん」という曲も明治の初期で、日本で初めての軍歌という話をなにかで読んだことを思い出しました。友人の男性の名前が宮とばかり思っていましたが、明治には「宮」という名前の女性もいたのか、それに「お」をつけているようです。これは「お冨さん」と同じです。

[link:] » 【軍歌】宮さん宮さん - Miyasan Miyasan - - YouTube https://t.co/jwvYIxgRxm

```
「宮さん宮さん」（みやさんみやさん）は、1868年（慶応4年/明治元年）頃に作成された軍歌・行進曲である。トコトンヤレ節［1］［2］もしくはトンヤレ節ともいう。作詞は品川弥二郎、作曲は大村益次郎とされているが確証はない［3］。事実上、日本初の軍歌と言える。

概要［編集］
歌詞は、戊辰戦争での新政府軍（官軍）の気勢を描いている。歌詞の「宮さん」は、戊辰戦争時に新政府の総裁で東征大総督でもあった有栖川宮熾仁親王を指す［4］。

［source：］宮さん宮さん - Wikipedia https://ja.wikipedia.org/wiki/%E5%AE%AE%E3%81%95%E3%82%93%E5%AE%AE%E3%81%95%E3%82%93
```

　軍勢の行列を見物する町民の視点で、町民同士の会話をイメージしていたのですが、宮さんは新政府の総裁で東征大提督のことだとあります。歌詞とは別に曲調がのどかでもあったので下々の見た景色と戦時下の話題とばかり思っていました。

[link:] » 維新回天 - Google 検索 https://t.co/EQyUiTLUQF

　維新回天という言葉を思い出したのですが、言葉の定義は見当たらず、坂本竜馬の本か何かのタイトルになっているようです。回天というのは、太平洋戦争中の人間魚雷のことであったように思います。

```
山口県周南市大津島。太平洋戦争の末期、海軍が開発したある秘密兵器が次々と運び込まれた。その兵器に乗るために、全国から４００人の若者たちがやってきた。秘密兵器の搭乗員を募集するとだけ聞いて志願してきたという。
　秘密兵器人間魚雷回天。人間もろともに体当たりし、命と引き換えに敵艦を沈める極限の兵器である。搭載された爆薬は、空母をも沈められる破壊力を持つといわれた。出撃すると二度と生きては帰れない。終戦までに、１０４人もの搭乗員が海に散っていった。
　太平洋戦争末期に行われた、海の中の特攻人間魚雷回天の真相に迫る。　

［source：］人間魚雷・悲劇の作戦 http://www5a.biglobe.ne.jp/~t-senoo/Sensou/ningen_gyorai/ningen_gyorai.htm
```

　維新回天という言葉が頭に浮かんだのは、深澤諭史弁護士のツイートで紹介していた、カルロス・ゴーン氏の逃亡で高野隆弁護士が公開したブログ記事のことがあるからです。ずいぶん長い間見かけないですが、狂瀾を既倒にめぐらす、という言葉があったはずです。mozcの日本語変換に難儀しました。

　既倒という感じは違っているような気がしてきましたが、ちょっと意味のわからない感じです。「すでにたおれた」という意味でしょうか。

[link:] » 狂瀾を既倒に廻らす(キョウランヲキトウニメグラス)とは - コトバンク https://t.co/pQlwY5YbOL

　「既倒」で検索をしたのですが、それで正しかったようです。

　韓愈という人物の名前は見覚えがありますが、「狂瀾を既倒に廻らす」は故事成語だったようです。史実に基づくのが故事成語であれば違っているのかと思いましたが、上記のページにも故事成語は見当たりません。学説のようなものかとも考えます。

[link:] » 狂瀾を既倒に廻らす | 会話で使えることわざ辞典 | 情報・知識＆オピニオン imidas - イミダス https://t.co/H5y5Dl96TY

　上記のページには「（荒れ狂う大波を押し戻す意から）　傾きかけた態勢を元の状態に引き戻すことをいう。」とありますが、まさにカルロス・ゴーン氏の弁護団、弘中惇一郎弁護士と高野隆弁護士の現在の状況、立場に当て嵌まる言葉と思います。

　そのカルロス・ゴーン氏の弁護団、弘中惇一郎弁護士や高野隆弁護士を擁護、支援する弁護士軍団のような方角のツイートに散見されたのが、もう一つの本項目のテーマとした「検察・検事の作文」になります。

　ちょっと深澤諭史弁護士のタイムラインで発見がありました。エンリケ航海玉子というアカウントのツイートを深澤諭史弁護士がリツイートしたものになりますが、現時点はこれが深澤諭史弁護士のタイムラインで最新のツイートとなっているようです。

　エンリケ航海玉子というアカウントについては、１，２ヶ月前にも取り上げていると思うのですが、深澤諭史弁護士のタイムラインだけでもいろいろと発見が多すぎて、内容が思い出せなくなっています。航海とプロフィールの名前にありますが、嵐の難破船をイメージさせる弁護士業界です。

　時刻は１７時１９分です。車が水をはねるような音はしばらく前から聞こえたいたのですが、外を見ると案の定、雨が降っていました。早い時間に買い物に行っていればともくやまれます。

```
[link:] 2020年01月04日15時14分の登録： REGEXP：”作文”／データベース登録済みツイート：2020年01月04日15時11分の記録：ユーザ・投稿：92／224件 http://hirono2014sk.blogspot.com/2020/01/regexp20200104151192224.html
[link:] 2020年01月04日15時23分の登録： REGEXP：”作文”／データベース登録済みツイートの検索：2020-01-01〜2020-01-04／2020年01月04日15時22分の記録：ユーザ・投稿：19／19件 http://hirono2014sk.blogspot.com/2020/01/regexp2020-01-012020-01_4.html
```

　上記が「作文」をキーワードにしたまとめ記事になります。２時間ほど前に事前準備として用意していたものです。２つ目が、１９ユーザーの１９ツイートと数が少なくなっていますが、７日以内の指定をしたものです。

　"`date +"%Y-%m-%d %H:%M" --date "1 day ago"`/`date +"%Y-%m-%d %H:%M"`"とコマンドラインで実行すると、コマンド置換演算子で、「2020-01-03 17:24/2020-01-04 17:24」となります。

　上記は１日を指定したものでした、１とある部分を７とすると「2019-12-28 17:26/2020-01-04 17:26」という時間の範囲の指定ができます。

　期間の指定をしなかったものは９２ユーザの２２４ツイートですが、古い情報も目立ったので、カルロス・ゴーン被告逃亡のニュースがあった１２月３１日を基準とし、予兆のような情報の可能性も踏まえ、７日以内という指定をしました。

　ざっと目を通したところ、「やぎさん」というアカウントのツイートとリツイートがほとんどでした。たしかに度々タイムラインで見かけていたツイートではあります。３年ぐらい前からは見かけているアカウントと思うのですが、似たものを非公開アカウントとして見かけてきました。

　同じアカウントが公開と非公開を切り替えている可能性があり、これまではそのように考えていたのですが、ここ最近は、似た別のアカウントが存在するのか、それを同一の人物がアカウントを使い分けているのかと考えるようになりました。

　プロフィールに弁護士らしい情報は記載がないですが、ツイートの内容をみていると弁護士か法律関係者の可能性が極めて高いアカウントです。返信のやり取りもよく見かけてきました。大学関係者の可能性もあるようにみています。実務家のような内容が多い気はします。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜soushokuyagisan（やぎさん） 日時：2020-01-04 17:38／2020/01/01 14:45 URL： https://twitter.com/kk_hirono/status/1213379184539533312 https://twitter.com/soushokuyagisan/status/1212248468422479873
> 弁護団はこの義務に従って、日本の特捜は作文はもちろん証拠を偽造してでも有罪立証をしようとするし、いかなる弁護人のもとでも日本の裁判所が無罪判断をすることが極めて稀であるという今後の見通しを誠実に説明したのでしょう。
▶▶▶　　　　　End　　　　　▶▶▶

　検察や検事の作文とし、敵愾心を燃やすようなツイートはこれまでにも見かけてきたのですが、過去のツイートを探すのも手間と時間が掛かりますし、過去との繋がりも大きいのですが、よりわかりやすく参考となる情報をさきほど深澤諭史弁護士のタイムラインで見つけています。

　カルロス・ゴーン氏の逃亡は、過去をフラッシュバックのように呼び起こす現象を発生しているのですが、その発生の源がホリエモンこと堀江貴文氏で、それを取り上げた弁護士ら法クラのツイートが散見されて来ました。

〈〈〈：Emacs： 2020-01-04（土曜日）17：44 　〈〈〈

