* 「検察が録音録画下で黙秘権を行使する被疑者に対して、何十時間も罵詈雑言を浴びせて自白を迫り、250日もの間全く無関係の妻との接見禁止も」という趙誠峰弁護士のツイート
  CLOCK: [2020-02-02 日 11:37]--[2020-02-02 日 12:23] =>  0:46

〉〉〉：Emacs： 2020-02-02（日曜日）11：37　 〉〉〉

:CATEGORIES: 趙誠峰弁護士,高野隆弁護士,弘中惇一郎弁護士,カルロス・ゴーン氏,黙秘権

　Twitterの通知に「斎藤司さんがCHO Seiho／趙誠峰さんのツイートをリツイートしました」とあったのがきっかけですが、数時間遅れでも目にしていたツイートかと思います。斎藤司さんはプロフィールに「龍谷大学法学部教授(刑事訴訟法)」とあります。

　そういえばまだ調べたことはないのですが、今日は相互フォローになっていることを確認しました。私が自分からフォローすることはもう５年以上一度もしていないのですが、フォローをもらったとはっきり記憶にあるアカウントではなかったように思います。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜tsukassaito（斎藤司） 日時：2020-02-02 11:46／2020/02/01 12:18 URL： https://twitter.com/kk_hirono/status/1223799768318537728 https://twitter.com/tsukassaito/status/1223445411551043585
> なぜ、刑事弁護人は「悪い人」を弁護するのか？京都弁護士会 https://t.co/mqJxJaLCnf
▶▶▶　　　　　End　　　　　▶▶▶

　斎藤司氏のタイムラインを少し遡ってみました。リツイートが多いと思っていたところ、ご本人のツイートが出てきて、その２つ目が上記にリツイートしたツイートになります。YouTube動画がリンクにありますが、昨夜辺りに見かけて、少しだけ再生してみた動画でした。

　どこのタイムラインをみかけたのか覚えていないですが、そのまますっかり忘れていました。遠山大輔弁護士が出てきて、以前注目したことのある弁護士と思っていました。今もう一度再生すると、京都弁護士会制作とありました。そして遠山弁護士を別の弁護士と勘違いしていたのかとも。

　龍谷大学も京都だったと思いますが、法科大学院まである法律と関係の深い大学というイメージです。仏教系の大学と聞いたようなこともあるのですが、これも今のところ詳しく調べることはしていないと思います。

　刑弁オアシスというのがあって、短期間注目し集中的に調べたことがあったのですが、そこに大学の女性の先生がいて、慈悲深い生き仏のようなお顔立ちであったことを思い出しました。名前は記憶にないですが、刑弁オアシスで検索すれば、画像の指定ですぐに見けることができそうです。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜cho_seiho（CHO Seiho／趙誠峰） 日時：2020-02-02 11:58／2020/02/01 21:50 URL： https://twitter.com/kk_hirono/status/1223802889434349569 https://twitter.com/cho_seiho/status/1223589549072252928
> 検察が録音録画下で黙秘権を行使する被疑者に対して、何十時間も罵詈雑言を浴びせて自白を迫り、250日もの間全く無関係の妻との接見禁止も認められなかった事件について2/3 17:00から記者会見やる予定です@神奈川県庁内県政記者クラブ… https://t.co/DvAcjUQbRM
▶▶▶　　　　　End　　　　　▶▶▶

　これも検索を悪の大権現とする、弁護士教の呪詛調伏の儀式のようなツイートです。２月３日の記者会見の紹介という内容のツイートですが、日付より前の部分がそのまま、なにか変わった本のタイトルのように見えました。

　「検察が録音録画下で黙秘権を行使する被疑者に対して、何十時間も罵詈雑言を浴びせて自白を迫り、250日もの間全く無関係の妻との接見禁止も認められなかった事件について」、というのがその部分になります。

　「接見禁止も認められなかった」というのは誤記と思われ、ツイートは修正ができず、一度削除してから投稿をやり直すというのもごく稀に見かけることがあります。意味を取り違えるほど致命的な誤記とは思わないですが、趙誠峰弁護士ご本人の判断で削除という可能性も一応ありそうです。

　実は、このところ高野隆弁護士と弘中惇一郎弁護士の逮捕の可能性を考えています。出入国管理法違反の幇助犯としての逮捕になります。故意の認定に難しさは感じていますが、徴表がつかめれば東京地検特捜部が動く可能性はありそうです。

　この趙誠峰弁護士のツイートをみるまえに、高野隆弁護士のブログの記事を読んでいたのですが、そちらもずいぶん極端に感じるところがありました。

〈〈〈：Emacs： 2020-02-02（日曜日）12：23 　〈〈〈

* 「何たる不見識。どれだけの日本人が、戦争が終わった後に、ソ連のために命を失い、陵辱された知ってのことか」というジャーナリストの江川紹子氏のツイート＆秋重実弁護士のリツイート
  CLOCK: [2020-02-02 日 13:07]--[2020-02-02 日 13:54] =>  0:47

〉〉〉：Emacs： 2020-02-02（日曜日）13：07　 〉〉〉

:CATEGORIES: ジャーナリストの江川紹子氏,秋重実弁護士,安倍政権

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2020-02-02 13:08／2020/02/01 22:02 URL： https://twitter.com/kk_hirono/status/1223820432479928320 https://twitter.com/amneris84/status/1223592364490387456
> 何たる不見識。どれだけの日本人が、戦争が終わった後に、ソ連のために命を失い、陵辱された知ってのことか… →旧ソ連戦勝75周年式典、出席検討する＝安倍首相 https://t.co/jk9jxEIH35
▶▶▶　　　　　End　　　　　▶▶▶

RT akishigemakoto（MakotoAkishige（civilista））｜amneris84（Shoko Egawa） 日時：2020-02-01 22:09／2020-02-01 22:02 URL： https://twitter.com/akishigemakoto/status/1223594212853071872 https://twitter.com/amneris84/status/1223592364490387456
> 何たる不見識。どれだけの日本人が、戦争が終わった後に、ソ連のために命を失い、陵辱された知ってのことか… →旧ソ連戦勝75周年式典、出席検討する＝安倍首相 https://t.co/jk9jxEIH35

　よくみると、まだ検討段階のニュースらしく、これはテレビのニュースでみかけ知っていました。ジャーナリストの江川紹子氏のツイートは昨夜の２２時０２分となっています。

　テレビでは日露平和条約締結や北方領土返還のためだと思いますが、プーチン大統領と話し合いの機会を得るため出席を検討する、ということであったと思います。

　日本とロシアの友好関係、共同事業については、これも以前、ジャーナリストの江川紹子氏が安倍首相を頭ごなしに否定するツイートをし、ロシアをまるっきり信用のできないならず者と決めつけている印象を受けました。

　ジャーナリストの江川紹子氏はプーチン大統領についても、おかしか文字の使い方をしていたように思います。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2020-02-02 13:25／2016/12/16 22:18 URL： https://twitter.com/kk_hirono/status/1223824812725829634 https://twitter.com/amneris84/status/809749419729952768
> もうプーちん帰っちゃったし、二人だけの会談で何を話したか検証不能だし。あべちゃんもぷーちんも、どちらも自分に都合のいいことを自国民に言えるようにしようねって、二人っきりで決めたとしても、分からないわけで。
▶▶▶　　　　　End　　　　　▶▶▶

　「もうプーちん帰っちゃったし」というジャーナリストの江川紹子氏のツイートをみつけました。「ちん」をキーワードにして見つけたものになります。その前の「ロシア」で見つからなかったのですが、意外な発見がありました。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2020-02-02 13:47／2017/06/27 19:28 URL： https://twitter.com/kk_hirono/status/1223830306144190464 https://twitter.com/amneris84/status/879647504140075008
> 捜査員の偽証は、繰り返されてきた。 　たとえば、３月に再審無罪が確定したロシア人男性の短銃所... - 「GPS使用ない」と虚偽証言＝窃盗事件公判で捜査員―警視庁（時事通信） https://t.co/7q2P5hpMKx #YJnewsComment
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2020-02-02 13:47／2017/01/25 09:29 URL： https://twitter.com/kk_hirono/status/1223830290142920706 https://twitter.com/amneris84/status/824051636901269504
> 〈検察側はおとり捜査を適法と主張するのが困難と判断したとみられる〉と。やっと　→おとり捜査：ロシア人男性、無罪の公算　北海道 - 毎日新聞 https://t.co/DfOI4z2ZHJ
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2020-02-02 13:47／2016/03/04 09:41 URL： https://twitter.com/kk_hirono/status/1223830271239192576 https://twitter.com/amneris84/status/705553699297296384
> 19年にわたって、手弁当で弁護活動を続けてきた、と　→ロシア人アンドレイさんに対する違法捜査　再審開始決定　弁護団の努力に敬意を表する https://t.co/lmZz25heyh
▶▶▶　　　　　End　　　　　▶▶▶

〈〈〈：Emacs： 2020-02-02（日曜日）13：54 　〈〈〈

