* 「どこの国のどんな司法制度も無実の人と犯人を正確に区別することができません。人間は神の目は持ってませんから。」というモトケンこと矢部善朗弁護士（京都弁護士会）のツイート
  CLOCK: [2020-01-16 木 10:15]--[2020-01-16 木 11:37] =>  1:22

〉〉〉：Emacs： 2020-01-16（木曜日）10：15　 〉〉〉

:CATEGORIES: モトケンこと矢部善朗弁護士（京都弁護士会）,冤罪,人権保障,無実

motoken_tw ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW motoken_tw（モトケン） 日時：2020/01/16 08:50 URL： https://twitter.com/motoken_tw/status/1217594905784025088
> どこの国のどんな司法制度も無実の人と犯人を正確に区別することができません。人間は神の目は持ってませんから。 \n そうしますと、無実の人の人権を保障しようとすると、つまり、捕まったり有罪になったりしないようにするためには、被疑者被告人の人権を保障することになります。 \n （続く
▷▷▷　　　　　End　　　　　▷▷▷

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-01-16 10:18／2020/01/16 10:18 URL： https://twitter.com/kk_hirono/status/1217617155287502849 https://twitter.com/s_hirono/status/1217617039746953216
> 2020-01-16-094514_モトケンさんはTwitterを使っています：　「どこの国のどんな司法制度も無実の人と犯人を正確に区別することができません。人間は神の目は持ってませんから。.jpg https://t.co/vkhvBpL7uQ
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-01-16 10:18／2020/01/16 10:18 URL： https://twitter.com/kk_hirono/status/1217617091102068739 https://twitter.com/s_hirono/status/1217617008566517760
> 2020-01-16-094427_モトケン@motoken_tw·53分どこの国のどんな司法制度も無実の人と犯人を正確に区別することができません。人間は神の目は持ってませんから。そうします.jpg https://t.co/yAQYMrJko2
▶▶▶　　　　　End　　　　　▶▶▶

　このモトケンこと矢部善朗弁護士（京都弁護士会）のツイートを見る少し前に、気になる記事を１つ読んでいました。ジャーナリストや報道についても考えさせられる機会だったので、個別に取り上げることを考えていますが、次の記事になります。きっかけはTwitterのトレンドでした。

[link:]  ゴーンに惨敗した日本、森法相の大失言が世界に印象付けた「自白強要文化」 | 情報戦の裏側 | ダイヤモンド・オンライン https://diamond.jp/articles/-/225890

　モトケンこと矢部善朗弁護士（京都弁護士会）の司法制度に関する連日続く一連のツイートも、出処や始まりはカルロス・ゴーン氏の逃亡劇とその後の日本の司法制度批判にあるものと見られます。モトケンこと矢部善朗弁護士（京都弁護士会）の場合は、元検事という立場も強調気味です。

　モトケンこと矢部善朗弁護士（京都弁護士会）のツイートで「神の目」が出てきたのも、今回が初めてではなかったように思います。モトケンこと矢部善朗弁護士（京都弁護士会）に限定はしていなかったかもしれないですが、まとめ記事を作成したような気がします。

```
% dp -p|grep 神の目
[link:] 2019年03月30日10時10分の登録： ＼へい、にーさん　@ssk_krr＼神ならぬ人間が、神の目で見たらどうなるかについて、何故わかるのかという哲学的な問い（）と格闘しようかと思ったが、起案神に憑依されたので http://hirono2014sk.blogspot.com/2019/03/sskkrr.html
[link:] 2019年03月30日13時42分の登録： ＼モトケン　@motoken_tw＼神の目を持たない人間がどうやって適正な裁判をしたらいいか、ということを考えて作られているのが現在の裁判制度。\n裁判官と言えども神の目は http://hirono2014sk.blogspot.com/2019/03/motokentw_30.html
[link:] 2019年03月30日15時51分の登録： REGEXP：”神の目”／データベース登録済みツイート：2019年03月30日15時51分の記録：ユーザ・投稿：4／4件 http://hirono2014sk.blogspot.com/2019/03/regexp20190330155144.html
[link:] 2019年03月30日16時06分の登録： REGEXP：”神の目”／データベース登録済みツイート：2019年03月30日16時04分の記録：ユーザ・投稿：60／102件 http://hirono2014sk.blogspot.com/2019/03/regexp20190330160460102.html
[link:] 2019年03月30日16時13分の登録： ％@mental_poverty　心の貧困％正義の女神の目隠しは、元々は盲目というネガティブなニュアンスだったのが、公正というポジティブなニュアンスに変わったらしい。今で http://hirono2014sk.blogspot.com/2019/03/mentalpoverty_30.html
[link:] 2019年03月30日16時42分の登録： ＼法律カキフライ　@ilillilliliili＼神の目はだれが持っているの？？ http://hirono2014sk.blogspot.com/2019/03/ilillilliliili.html
[link:] 2019年03月30日23時21分の登録： ＼りっぴぃ　@rippy08＼「神の目」と言えば、「ジキルとハイドと裁判員」（コミック、完結済み）は、「神の目」を得てしまった裁判官・ジキルのお話。。 http://hirono2014sk.blogspot.com/2019/03/rippy08_30.html
[link:] 2019年03月31日19時26分の登録： ＼モトケン　@motoken_tw＼無罪判決を受けた被告人に対し、判決は無罪だけど彼は本当は（犯罪を）やったに違いない、と言うことは、自分だけは神の目を持っていると言って http://hirono2014sk.blogspot.com/2019/03/motokentw_52.html
[link:] 2019年04月02日07時55分の登録： ＼サイ太　@uwaaaa＼喜久山弁護士と性犯罪無罪事件について ――刑事訴訟と「神の目」 - Togetter http://hirono2014sk.blogspot.com/2019/04/uwaaaa-togetter.html
[link:] 2019年04月02日08時51分の登録： ＼弁護士 吉峯耕平（「カンママル」撲滅委員会）　@kyoshimine＼「神の目弁護士」などの二つ名が定着してしまった喜久山先生だが、ご本人は「神の目を持っている」と宣言 http://hirono2014sk.blogspot.com/2019/04/kyoshimine.html
[link:] 2019年04月02日09時08分の登録： ＼hznf　@_hznf_＼神の目の弁護士、芸風が神原元弁護士に似てるな。神原弁護士にはいつの間にかブロックされてたので最近の言動は知らないが、あの人も自分が絶対正義と信 http://hirono2014sk.blogspot.com/2019/04/hznfhznf.html
[link:] 2019年04月12日22時05分の登録： ＼喜久山大貴　@kikuyamahiroki＼＞おそらく昨今批判をしている人々は「神の目から見た真実」が明らかになるよう努めろと言っているのだと思います。 違うと思う。 http://hirono2014sk.blogspot.com/2019/04/kikuyamahiroki_12.html
[link:] 2019年04月20日07時43分の登録： REGEXP：”神の目”／データベース登録済みツイート：2019年04月20日07時40分の記録：ユーザ・投稿：76／146件 http://hirono2014sk.blogspot.com/2019/04/regexp20190420074076146.html
[link:] 2019年06月09日20時33分の登録： REGEXP：”神の目．＊弁護士”／データベース登録済みツイート：2019年06月09日20時33分の記録：ユーザ・投稿：15／18件 http://hirono2014sk.blogspot.com/2019/06/regexp2019060920331518.html
[link:] 2019年08月22日23時43分の登録： ＼橋本太地（弁護士・あなたのみかた法律事務所）　@kojin_syugi＼返信先: @jmtpjmgmtさん\n京都に神の目を持つ弁護士がいますよ http://hirono2014sk.blogspot.com/2019/08/kojinsyugi-jmtpjmgmt.html
[link:] 2019年10月18日14時17分の登録： ＼D弁　@dben82716007＼司法は真相を解明する義務がある旨の記載があったよ。民事訴訟の場でね・・・。司法関係者には神の目があるのかしら（当職にはない） http://hirono2014sk.blogspot.com/2019/10/ddben82716007.html
```

　法クラの間で、京都の喜久山大貴弁護士の神の目の発言が話題になっていたようですが、すっかりと忘れていたことで今も余り具体的には思い出せずにいます。昨年の４月１２日にその喜久山大貴弁護士のツイートの記録がみえますが、それより前から非公開設定になっていたような感覚です。

　喜久山大貴弁護士については、明石市の花火大会での大きな事故に関する発言が飛び抜けて衝撃的でした。そういえば、昨日のちょうど今頃の時間帯にも、その明石市長に関する記事を読んでいて、発端は明石市民まつりの再開に関する議論とありました。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-01-16 10:38／2019/12/27 00:15 URL： https://twitter.com/kk_hirono/status/1217622101147807744 https://twitter.com/hirono_hideki/status/1210217620584067074
> 2019年12月26日10時39分の登録： ＼明石順平@「人間使い捨て国家」発売中　@junpeiakashi＼自民党が与党だとこういうことが起きる。\n自民党は経営者の方しか見てない「労働者の敵」なんですよ。拙著「 https://t.co/1vplZpLnzB
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kobeshinbun（神戸新聞） 日時：2020-01-16 10:38／2020/01/15 07:19 URL： https://twitter.com/kk_hirono/status/1217622002099347457 https://twitter.com/kobeshinbun/status/1217209678364475393
> 明石市長また暴言　市議に「議員辞めてまえ」　新年会で口論 https://t.co/cC3aQeRMIa #神戸新聞 #明石市 https://t.co/1wFySuhAov
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-01-16 10:37／2020/01/15 10:39 URL： https://twitter.com/kk_hirono/status/1217621967404072960 https://twitter.com/hirono_hideki/status/1217259913195376641
> 明石市長また暴言　市議に「議員辞めてまえ」　新年会で口論（神戸新聞）　兵庫県明石市の泉房穂市長（５６）が市内…｜ｄメニューニュース（NTTドコモ） https://t.co/lmjvRoixK2 ２００１年の明石歩道橋事故後、中止… https://t.co/88qWthLN8P
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「明石」の検索結果 - Twilog https://t.co/L4K0cUDz0E

　１つおまけのように加えたのが名前が明石の明石順平弁護士になります。喜久山大貴弁護士ほどではないですが、斬新で理解を超えた発言が目立つ点はSF作家のようなイメージもあって少なからず共通性を感じます。もっとも明石順平弁護士の場合は、同じ弁護士から懲戒請求されるようなことはないはず。

```
時刻は11時27分です。喜久山大貴弁護士の法律事務所について調べ、そこで塩見卓也弁護士の名前を見つけました。久しぶりにみた弁護士名だと思いましたが、少し調べるとやはりバルタン星人のフィギアのような写真を掲げたアカウントでした。

　タイムラインを見ていると、そこで見かけたようにも思いますが、渡辺輝人弁護士のことを思い出し、名前で検索をしてTwitterのページを開き、そこに法律事務所のホームページのリンクがあることに気が付きました。プロフィールだったと思います。

　その前に、渡辺輝人弁護士の所属する法律事務所が京都市だったことを思い出していました。ついつい佐々木亮弁護士（ささきりょう）と同じように東京の弁護士をイメージしてしまうのですが、前に京都の弁護士であることを発見していたことを思い出しました。

　そういえば1つ思い出しましたが、喜久山大貴弁護士のツイートへの返信の中で、「ナベテル」を上回る、というようなツイートを目にしていました。これまでに何度か見かけてきましたが、渡辺輝人弁護士は一部にナベテルと呼ばれているようです。

　その渡辺輝人弁護士の法律事務所のホームページもみていたのですが、16人の弁護士が所属の法律事務所で、ホームページのつくりもよくできたものでした。渡辺輝人弁護士も労働問題の専門弁護士として注目はしてきたのですが、なかなか手が回らぬのが現状です。

　今書いていることも、予定外だったのですが、急遽、優先度を上げて取り上げておくことにしました。「市民を挟む弁護士と警察の関係性」の意義が大きく、とても参考になると判断したからです。

　喜久山大貴弁護士は弁護士になる前、7年間神戸に住んでいたとツイートに書いていました。そのときの思い出したのですが、甲山事件がきっかけで弁護士になったという弁護士の記事を読みました。10日から2週間ほど前かなと思います。

　その弁護士の名前も、なにが発見のきっかけだったのか思い出せないですが、甲山事件について新たな知見をえることができました。甲山事件についても、ずっと以前、書籍を読んだことがありました。えん罪の専門書で、複数の事件・刑事裁判が取り上げられていたと思います。

［source：］市場急配センター殺人未遂事件に加担した4弁護士２裁判官の告訴告発： # 「この弁護士、明石歩道橋事故だとかの群衆事故を知らんのか。」（感熱紙）をモトケンこと矢部善朗弁護士（京都弁護士会）がリツイート # http://hirono2017kk.blogspot.com/2018/08/blog-post_8.html
```

　記事の引用をしてから記事のタイトル名の内容に気が付きました。モトケンこと矢部善朗弁護士（京都弁護士会）のリツイートとありますが、元のツイートは感熱紙という匿名アカウントで、何度か取り上げていますが、北九州の現職の警察官の可能性が高いアカウントです。

　考えてみると独自の神の目を持つ弁護士は多そうです。個性が強烈に強いということもありますが、類は友を呼ぶという共通した傾向もよく見かけられるものです。

　モトケンこと矢部善朗弁護士（京都弁護士会）の場合は、実にあっさりと神の目という概念を持ち出していますし、それを無実に当て嵌めています。無罪と無実は違うもので、無実の場合は全く見に覚えのない事実で罪に問われることになるはずです。

　無実で罪に問われる可能性を高めているのは弁護士が最大の功労者、伝統の弁護士鉄道というのが私が長年、研究をしてきた見立てとなります。黙秘権を最大の武器であるがリスクも大きいとするのがモトケンこと矢部善朗弁護士（京都弁護士会）のもう１つの主張です。

　無実の人にはその現場にいなかったり、無関係であったという別の事実が存在するはずですが、黙秘権の行使はその自身の事実を主張、証明する機会の放棄に等しいのではと考えます。また、その本来の事実を軽視し、警察や検察に対する不信や不満を盛りたてるのも弁護士の特徴です。

　そういえば、昨日のテレビのバイキングで気になる話題がありました。欠陥住宅に関する問題で、その場所というのも宮崎とテレビから声を聞いたように思います。ネットではまったくみかけていない問題で調べてもいませんでした。

　それほど大きな被害が出ている感じではなく身近にありがちな問題という点では、バイキングの番組での取り上げを評価したいとは思いましたが、番組の制作で、どのように選択され、取材されたのかその経緯や裏側が気になる放送ではありました。

[link:] » バイキング　欠陥住宅 - Google 検索 https://t.co/FuiGipaZFK

[link:] » 夢のマイホームは欠陥だらけ・未完成住宅も・ずさんすぎる・建築業者の代表親子が逮捕！実態は？ フジテレビ【バイキング】｜ＪＣＣテレビすべて https://t.co/5lTb2DOYL1

　放送の初めの方は集中してみていなかったかもしれません。集中してみるようになってその話題の終わりの方に、一度だけ逮捕と聞こえたように思っていたのですが、逮捕はされていたらしく、それで顔出しになっていたのかと納得しました。

　この放送で一番驚いたのは、弁護士が責任を追求された父親に、「１１０番しろ」などとアドバイスをしたという話でした。上記の番組情報をみると西川研一弁護士の名前があります。司会者から発言を向けられ、うまく話を逸したという印象がありました。よくある弁護士の考えの推測です。

　最近のバイキングでは、弁護士を笑いものにして盛り上がることも多いのですが、余りいじられてはいないと感じるのが西川研一弁護士で、清原博弁護士になると、ずいぶんといじられ突っ込まれもしている感じです。横粂勝仁弁護士も似た傾向はありますが、呆れるような疑問視はされていないようです。

[link:] » バイキング　１１０番 - Twitter検索 / Twitter https://t.co/iQT0iGTctQ

[link:] » バイキング　弁護士 - Twitter検索 / Twitter https://t.co/qInI9wyXIh

　Twitterで特に大きな反応はなかったようです。依頼者と被害者の関係を調整するのも弁護士の仕事の範囲のような気がするのですが、弁護士は来たら１１０番しろとアドバイスをしていたようです。これだと被害者の不安と不信も大きくなり、さらに問題をこじらせそうです。

　わずらわしい被害者の追求を阻止するのが弁護士に期待された役割と考えれば、それもありなのかもしれません。

〈〈〈：Emacs： 2020-01-16（木曜日）11：37 　〈〈〈

