* 弘中惇一郎弁護士への鍵をぶち壊した事務所捜索のニュース、弁護士会の存在意義が問われている、というツイートに、無法者集団だな、とした秋重実弁護士（京都弁護士会）のツイート
  CLOCK: [2020-01-29 水 22:03]--[2020-01-29 水 22:31] =>  0:28

〉〉〉：Emacs： 2020-01-29（水曜日）22：03　 〉〉〉

:CATEGORIES: 弘中惇一郎弁護士,秋重実弁護士

　今のところ、今日一番の記録価値のある弁護士ツイートかと思います。今日は風邪の症状もいくぶん良くなっています。一番悪かったのが一昨日になるかと思いますが、余り経験がないほど風邪の症状が長引いています。

　今日は気温も高めで、夕方に外をみると空に三日月がくっきりと見えて雨雲はありそうにありませんでした。明日はけっこう雨が降る予報とはなっているようです。夕方に宇出津新港まで買い物に行くことを予定していたのですが、風邪が回復に向かっていることもあり、大事をとりました。

akishigemakoto ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW akishigemakoto（MakotoAkishige（civilista）） 日時：2020/01/29 21:23 URL： https://twitter.com/akishigemakoto/status/1222495577595793408
> 無法者集団だな https://t.co/CbKqXFjB15
▷▷▷　　　　　End　　　　　▷▷▷

　昨年度になるのか、京都弁護士会の副会長をしていたという秋重実弁護士になります。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜O59K2dPQH59QEJx（ピピピーッ） 日時：2020-01-29 22:10／2020/01/29 20:03 URL： https://twitter.com/kk_hirono/status/1222507359957745665 https://twitter.com/O59K2dPQH59QEJx/status/1222475284252770305
> 弁護士会の存在意義が今問われている。 刑事弁護の危機と戦う会員を、守らなくてよいのだろうか。  弘中弁護士「鍵ぶっ壊して…」事務所捜索を #日テレNEWS24 #日テレ #ntv https://t.co/CrVhlW4JrK
▶▶▶　　　　　End　　　　　▶▶▶

[link:] 2020年01月29日21時52分の登録： ＼MakotoAkishige（civilista）　@akishigemakoto＼無法者集団だな http://hirono2014sk.blogspot.com/2020/01/makotoakishigecivilistaakishigemakoto_29.html

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-01-29 22:12／2020/01/29 21:52 URL： https://twitter.com/kk_hirono/status/1222507818852343810 https://twitter.com/s_hirono/status/1222502811830587392
> 2020-01-29-215215_MakotoAkishige（civilista）@akishigemakoto·28分無法者集団だな.jpg https://t.co/vFhMRdZYKX
▶▶▶　　　　　End　　　　　▶▶▶

　弘中惇一郎弁護士の法律事務所への家宅捜査については、午後にテレビでみていたように思いますが、最初のきっかけは深澤諭史弁護士のタイムラインにあったとも思い出してきました。

　弘中惇一郎弁護士の法律事務所への家宅捜査については、NHKのNEWS７では取り上げがなかったと思われます。ニュースの項目になかったのは確かなことで、その他のニュースに出るのかと思いながらみていたのですが、今回はその他にニュースに気がつくことがなかったです。

　弘中惇一郎弁護士の法律事務所への家宅捜査については、同じくNHKのNEWS９では、報道があったと思いますが、「鍵を壊した」件については、触れられていなかったように思います。

```
% tu fukazawas 200|grep -B 1 -A 1  弘中
TW fukazawas（深澤諭史） 日時： 2020-01-29 21:26 URL： https://twitter.com/fukazawas/status/1222496173509861378
> 弘中弁護士「鍵ぶっ壊して…」事務所捜索を #日テレNEWS24 #日テレ #ntv https://t.co/pEpJ8mMgpr \n 法曹がこんなことしては、いけません。。。。。

--
RT fukazawas（深澤諭史）｜O59K2dPQH59QEJx（ピピピーッ） 日時：2020-01-29 20:07／2020-01-29 19:52 URL： https://twitter.com/fukazawas/status/1222476363287785472 https://twitter.com/O59K2dPQH59QEJx/status/1222472652712861696
> 弘中事務所のドアが壊されたんだって？ \n これに抗議する弁護団の活動があれば30万くらい送金するわ。

RT fukazawas（深澤諭史）｜O59K2dPQH59QEJx（ピピピーッ） 日時：2020-01-29 20:07／2020-01-29 20:03 URL： https://twitter.com/fukazawas/status/1222476355230564352 https://twitter.com/O59K2dPQH59QEJx/status/1222475284252770305
> 弁護士会の存在意義が今問われている。 \n 刑事弁護の危機と戦う会員を、守らなくてよいのだろうか。 \n  \n 弘中弁護士「鍵ぶっ壊して…」事務所捜索を #日テレNEWS24 #日テレ #ntv https://t.co/CrVhlW4JrK

```

　深澤諭史弁護士の「弘中惇一郎弁護士の法律事務所への家宅捜査」に関するリツイートは、早いものでリツイートの時刻が２０時０７分だったと確認しました。これをみると、最初に知ったきっかけが深澤諭史弁護士のタイムラインだったという可能性は、ほぼないように思えてきました。

　一昨日や昨日に比べれば、だいぶんましな状態ですが、風邪の影響で集中力がよくありません。これはメモをかねた自分のツイートで調べた方が、確かなことを確認できそうです。Twitterのありがたみを痛感します。

```
% tu hirono_hideki 200|grep -B 1 -A 1  弘中         
TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-01-29 21:49 URL： https://twitter.com/hirono_hideki/status/1222502017517551621
> 2020年01月29日21時48分の登録： ＼深澤諭史　@fukazawas＼弘中弁護士「鍵ぶっ壊して…」事務所捜索を #日テレNEWS24 #日テ https://t.co/oOsUr4C0sP

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-01-29 21:49 URL： https://twitter.com/hirono_hideki/status/1222501991189925889
> 2020年01月29日21時04分の登録： ＼山口貴士 aka無駄に感じが悪いヤマベン　@otakulawyer＼弘中先生は元弁護人として刑事訴訟法105条の押収拒絶権を行使することが分かっているのに捜索をするのは https://t.co/KYP4S6Fmll

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-01-29 21:49 URL： https://twitter.com/hirono_hideki/status/1222501964891619334
> 2020年01月29日20時22分の登録： ＼ピピピーッ　@O59K2dPQH59QEJx＼弁護士会の存在意義が今問われている。\n刑事弁護の危機と戦う会員を、守らなくてよいのだろうか。\n\n弘中弁護士「鍵ぶっ壊して… https://t.co/mkjcTRgtqW

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-01-29 21:49 URL： https://twitter.com/hirono_hideki/status/1222501938551349249
> 2020年01月29日20時21分の登録： ＼ピピピーッ　@O59K2dPQH59QEJx＼弘中事務所のドアが壊されたんだって？\nこれに抗議する弁護団の活動があれば30万くらい送金するわ。 https://t.co/cNxCsdeO7k

--
RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜Kotchian35（幸ちゃん） 日時：2020-01-29 21:17／2020-01-29 13:07 URL： https://twitter.com/hirono_hideki/status/1222494017767661568 https://twitter.com/Kotchian35/status/1222370573092671490
> 弘中弁護士の事務所、東京地検が捜索…ゴーン被告の元弁護人 \n https://t.co/kDrKps6V3U \n  \n 何で今回は裁判所が令状を出したか？　まず、弘中氏が弁護団から抜けたこと。勿論守秘義務はあるが、裁判所がそこを無視したのは、… https://t.co/s10crFXM59

--
RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜O59K2dPQH59QEJx（ピピピーッ） 日時：2020-01-29 21:15／2020-01-29 17:25 URL： https://twitter.com/hirono_hideki/status/1222493370498473986 https://twitter.com/O59K2dPQH59QEJx/status/1222435531977445376
> 弘中事務所の差押の件、街弁は無関係と思いがちだけど、国選でウッカリ筋悪の特殊詐欺否認とか引いたら、十分に影響のあり得る話だよ。

--
RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜n51n1215k921（もんくま） 日時：2020-01-29 21:04／2020-01-29 19:21 URL： https://twitter.com/hirono_hideki/status/1222490804859523074 https://twitter.com/n51n1215k921/status/1222464824791027712
> @YopparaiHebi @otakulawyer @sato__michiko 大丈夫です、弘中惇一郎さんは、受任してくださらないと思うので心配しなくていいと思います。 \n 弘中惇一郎さんはマクリーン事件の弁護人ですし。

--
RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜otakulawyer（山口貴士 aka無駄に感じが悪いヤマベン） 日時：2020-01-29 21:03／2020-01-29 12:40 URL： https://twitter.com/hirono_hideki/status/1222490548042289154 https://twitter.com/otakulawyer/status/1222363833458544640
> 弘中先生は元弁護人として刑事訴訟法105条の押収拒絶権を行使することが分かっているのに捜索をするのは、東京地検を手こずらせた優秀な弁護士に対する嫌がらせだし、他の弁護士の刑事弁護活動を牽制する意図があるとしか思えない。 \n  https://t.co/VDnFVg2w2f

--
TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-01-29 20:56 URL： https://twitter.com/hirono_hideki/status/1222488594100572160
> 弘中弁護士の事務所、東京地検が捜索…ゴーン被告の元弁護人 : 国内 : ニュース : 読売新聞オンライン https://t.co/8GBykqlB2R

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-01-29 20:55 URL： https://twitter.com/hirono_hideki/status/1222488524319944704
> ゴーン元会長逃亡、弘中弁護士事務所を捜索　東京地検　（写真=共同）　:日本経済新聞 https://t.co/QR8fjfsgVo

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-01-29 20:51 URL： https://twitter.com/hirono_hideki/status/1222487388749848576
> ゴーン被告逃亡 弘中惇一郎弁護士の事務所を捜索 東京地検 | NHKニュース https://t.co/UzbjXVENtr \n 捜索を受けたことについて弘中弁護士は「大変だなとか不愉快だなとか、いろいろな思いがある」と述べました。

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-01-29 20:51 URL： https://twitter.com/hirono_hideki/status/1222487307820789760
> ゴーン被告逃亡 弘中惇一郎弁護士の事務所を捜索 東京地検 | NHKニュース https://t.co/UzbjXVENtr

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-01-29 20:50 URL： https://twitter.com/hirono_hideki/status/1222487093345021953
> ゴーン被告逃亡 弘中惇一郎弁護士の事務所を捜索  https://t.co/UzbjXVENtr \n 弘中弁護士は出張のため不在で、事務所にいた弁護士が立ち入りを拒否したということですが、係官らは合鍵のようなもので事務所の鍵を開け、ゴ… https://t.co/8UeDzcfGID

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-01-29 20:48 URL： https://twitter.com/hirono_hideki/status/1222486715928989697
> ゴーン被告逃亡 弘中惇一郎弁護士の事務所を捜索 東京地検 | NHKニュース https://t.co/UzbjXVENtr \n 弘中弁護士 「大変 不愉快 いろいろな思いある」 \n 弘中惇一郎弁護士は29日、午後４時半すぎから報道陣の取材に応じました。

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-01-29 20:47 URL： https://twitter.com/hirono_hideki/status/1222486519622975490
> ゴーン被告逃亡 弘中惇一郎弁護士の事務所を捜索 東京地検 | NHKニュース https://t.co/UzbjXVENtr \n 元会長が使っていたパソコンや、ほかの資料については、依頼者の秘密を守るために法律で認められている権利に基づいて、押収を拒否したということです。

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-01-29 20:46 URL： https://twitter.com/hirono_hideki/status/1222486289594765312
> ゴーン被告逃亡 弘中惇一郎弁護士の事務所を捜索 東京地検 | NHKニュース https://t.co/UzbjXVENtr \n 東京地検は、ゴーン元会長の保釈中の面会記録を押収したということですが、弁護側は、それ以外の資料などの押収は拒否したということです。

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-01-29 20:31 URL： https://twitter.com/hirono_hideki/status/1222482292322390017
> 弘中弁護士「鍵ぶっ壊して…」事務所捜索を｜日テレNEWS24 https://t.co/dnSSrzI23u

--
TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-01-29 19:55 URL： https://twitter.com/hirono_hideki/status/1222473244260716545
> 2020年01月29日17時11分の登録： REGEXP：”弘中．＊家宅捜索”／データベース登録済みツイート：2020年01月29日17時10分の記録：ユーザ・投稿：26／30件 https://t.co/uSFYK4vw0H

--
TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-01-29 17:10 URL： https://twitter.com/hirono_hideki/status/1222431733066260480
> 2020年01月29日17時03分の実行記録 \n twitterAPI-search-lawList-mydql-add.rb "弘中 家宅捜索" \n ツイート数：14/1719 リツイート数：10/1719 トータル：2056 \n hiro… https://t.co/vQufNwwgty

--
RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜Sankei_news（産経ニュース） 日時：2020-01-29 13:46／2020-01-29 12:10 URL： https://twitter.com/hirono_hideki/status/1222380533574823936 https://twitter.com/Sankei_news/status/1222356359217180678
> 東京地検が弘中事務所を家宅捜索 \n https://t.co/3sA1WxuMyc \n  \n ゴーン被告の弁護人を務めていた弘中惇一郎弁護士の事務所を東京地検が家宅捜索。

--
TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-01-28 10:26 URL： https://twitter.com/hirono_hideki/status/1221967804779220993
> 2020年01月27日18時25分の登録： REGEXP：”（弘中惇一郎弁護士｜弘中惇一郎先生｜弘中先生｜弘中弁護士）”／データベース登録済みツイートの検索：2019-12-31〜2020-01-27／2020年01月27日18時… https://t.co/Z5qqyIg5lf

--
TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-01-27 17:57 URL： https://twitter.com/hirono_hideki/status/1221718855099150337
> 2020年01月27日17時56分の実行記録 \n twitterAPI-search-lawList-mydql-add.rb "弘中 弁護士" \n ツイート数：38/1717 リツイート数：43/1717 トータル：1523 \n hiron… https://t.co/CWqqvNDNG7

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-01-27 17:47 URL： https://twitter.com/hirono_hideki/status/1221716365263794182
> 2020年01月27日17時47分の実行記録 \n twitterAPI-search-lawList-mydql-add.rb "弘中 先生" \n ツイート数：11/1717 リツイート数：12/1717 トータル：156 \n hirono_… https://t.co/6uqOCZSwDS

```

〈〈〈：Emacs： 2020-01-29（水曜日）22：31 　〈〈〈

* 「弘中惇一郎弁護士の法律事務所への家宅捜査」、「鍵をぶち壊して」というニュースに対する主に弁護士らの反応と記録
  CLOCK: [2020-01-29 水 22:38]--[2020-01-30 木 00:48] =>  2:10

〉〉〉：Emacs： 2020-01-29（水曜日）22：38　 〉〉〉

:CATEGORIES: 弘中惇一郎弁護士,ツイートのまとめ

```
2020年01月29日22時33分の実行記録
twitterAPI-search-lawList-mydql-add.rb "弘中 家宅捜索"
ツイート数：19/1719 リツイート数：13/1719 トータル：3148
hirono_hideki 2／1件
kk_hirono 3／0件
s_hirono 0／0件
```

[link:] 2020年01月29日22時35分の登録： REGEXP：”弘中．＊家宅捜索”／データベース登録済みツイート：2020年01月29日22時34分の記録：ユーザ・投稿：29／38件 http://hirono2014sk.blogspot.com/2020/01/regexp2020012922342938.html

▶（01／38） TW cho_seiho（CHO Seiho／趙誠峰） 日時： 2020-01-08 12:06:00 +0900 URL： https://twitter.com/cho_seiho/status/1214745219377221633
{% tweet 1214745219377221633 %}
> 弁護士と依頼人とのコミュニケーションの秘密は憲法上の権利です。 \n 弁護人にしてみればPCを任意提出するわけにはいかず、検察も差押えするしかなく、弁護人は当然押収拒絶する。それだけの話を「弘中事務所に家宅捜索！」とか速報打つマスコミは… https://t.co/fsRaA1i3so

　皮切りが高野隆弁護士の愛弟子的存在とも聞く趙誠峰弁護士でしたが、ツイートは１月８日のものでした。テレビの画面のような画像が付いていますが、そこには「弘中惇一郎弁護士事務所に強制捜査乗り出すも拒まれる」とあります。前回も強制捜査ではあったようです。

▶（05／38） TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-01-09 14:24:00 +0900 URL： https://twitter.com/hirono_hideki/status/1215142268165746689
{% tweet 1215142268165746689 %}
> 56：2020-01-08_15:11:46 ＊ 「それだけの話を「弘中事務所に家宅捜索！」とか速報打つマスコミはアホ。害悪でしかない。」という深澤諭史弁護士がリツイートした趙誠峰弁護士のツイート https://t.co/bdpukjpKaq

　あまり記憶にはなかったエントリーになりそうです。

▶（06／38） TW tv_asahi_news（テレ朝news） 日時： 2020-01-29 12:03:00 +0900 URL： https://twitter.com/tv_asahi_news/status/1222354426624528384
{% tweet 1222354426624528384 %}
> 【速報】弘中惇一郎弁護士の事務所を家宅捜索　ゴーン被告の海外逃亡にからみ　東京地検 \n https://t.co/thR32iDcU8

　３８件中の６番目のツイートが、本日１月２９日のツイートで、１２時０３分となっています。速報に近いものと思われますが、ぎりぎり午後のニュースになりそうです。

　１月８日のニュースが意外に少ないですが、テレビの報道では「強制捜査」となっていて、今回の１月２９日の同じく午前、弘中惇一郎弁護士の法律事務所への立ち入りが「家宅捜査」となっているようです。「家宅捜査」というのも最近はテレビで余り見かけていないような気がしました。

　家宅という言葉自体を見かけなくなっているように思いましたが、「お家（おうち）」と「お宅（おたく）」を一緒にしたような言葉で、個人の民家や住まいを意識させます。法律事務所に対する強制捜査が異例なのだとは思いますが、お家やお宅とは違うような気がします。

　調べたところ、１月８日というのはレバノンでのカルロス・ゴーン氏の記者会見の当日でした。写真の情報を確認していたところ、弘中惇一郎弁護士の法律事務所への強制捜査と同じ日だったのかと思ったのですが、終わりに強制捜査があったのは１月４日らしい情報が目に入りました。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-01-29 23:09／2020/01/29 23:04 URL： https://twitter.com/kk_hirono/status/1222522053426733057 https://twitter.com/s_hirono/status/1222520874999275522
> 2020-01-08_150909＿テレビの画面・.jpg https://t.co/rDC2vtGAYD
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-01-29 23:08／2020/01/29 23:04 URL： https://twitter.com/kk_hirono/status/1222522028395098112 https://twitter.com/s_hirono/status/1222520947338428416
> 2020-01-08_191310＿テレビの画面・.jpg https://t.co/b3ULTMFgOQ
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-01-29 23:08／2020/01/29 23:04 URL： https://twitter.com/kk_hirono/status/1222522012419031040 https://twitter.com/s_hirono/status/1222521019384004609
> 2020-01-08_212552＿テレビの画面・ゴーン元会長　まもなく会見　レバノン.jpg https://t.co/oQXuYEEoaw
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-01-29 23:08／2020/01/29 23:05 URL： https://twitter.com/kk_hirono/status/1222521994932940800 https://twitter.com/s_hirono/status/1222521095284117504
> 2020-01-08_212735＿テレビの画面・.jpg https://t.co/M3AcDNOdol
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-01-29 23:08／2020/01/29 23:05 URL： https://twitter.com/kk_hirono/status/1222521971520360448 https://twitter.com/s_hirono/status/1222521167669383168
> 2020-01-08_212741＿テレビの画面・.jpg https://t.co/Ifo2YkRx3V
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-01-29 23:08／2020/01/29 23:05 URL： https://twitter.com/kk_hirono/status/1222521957314252805 https://twitter.com/s_hirono/status/1222521240256040961
> 2020-01-08_212753＿テレビの画面・.jpg https://t.co/GcJAj3hNlu
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-01-29 23:08／2020/01/29 23:06 URL： https://twitter.com/kk_hirono/status/1222521941354934274 https://twitter.com/s_hirono/status/1222521312486182915
> 2020-01-08_212759＿テレビの画面・.jpg https://t.co/JEfUWrbYUy
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-01-29 23:08／2020/01/29 23:06 URL： https://twitter.com/kk_hirono/status/1222521927748554755 https://twitter.com/s_hirono/status/1222521388147195910
> 2020-01-08_212815＿テレビの画面・.jpg https://t.co/6rCur5cTCW
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-01-29 23:08／2020/01/29 23:06 URL： https://twitter.com/kk_hirono/status/1222521911487283201 https://twitter.com/s_hirono/status/1222521460293423105
> 2020-01-08_212838＿テレビの画面・.jpg https://t.co/gkugAAcMzX
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-01-29 23:08／2020/01/29 23:07 URL： https://twitter.com/kk_hirono/status/1222521898451394560 https://twitter.com/s_hirono/status/1222521532125040640
> 2020-01-08_212845＿テレビの画面・.jpg https://t.co/3zDDRzDXsL
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-01-29 23:08／2020/01/29 23:07 URL： https://twitter.com/kk_hirono/status/1222521884916404224 https://twitter.com/s_hirono/status/1222521604787171328
> 2020-01-08_212852＿テレビの画面・.jpg https://t.co/lnzYv6QgTO
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-01-29 23:08／2020/01/29 23:07 URL： https://twitter.com/kk_hirono/status/1222521867736477697 https://twitter.com/s_hirono/status/1222521677021503489
> 2020-01-08_212902＿テレビの画面・.jpg https://t.co/hhgabdBdGL
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 弘中惇一郎弁護士　事務所への強制捜査拒否｜日テレNEWS24 https://t.co/jtEocBjqJN

　どうも右クリックが禁止のようであり、引用はできないですが、１月４日ではなく１月８日が弘中惇一郎弁護士の事務所への強制捜査があった当日で、当日のニュースになっていたようです。記事の配信時刻は１１時４５分と、午前中となっています。

```
東京地検は８日午前、出入国管理法違反の疑いで東京・千代田区にある弘中惇一郎弁護士の事務所に強制捜査に乗り出したが、拒まれたという。弁護士には、業務上所持するもので、他人の秘密に関するものについては押収を拒否することができると刑事訴訟法で規定されている。

東京地検は弘中弁護士に、保釈中にゴーン被告が使っていたパソコンの任意提出を求めてきたが、弘中弁護士は「中身を確認してから提出する」などとして、８日までに任意での提出に応じていなかった。

［source：］弘中惇一郎弁護士　事務所への強制捜査拒否（日本テレビ系（NNN）） - Yahoo!ニュース https://headlines.yahoo.co.jp/videonews/nnn?a=20200108-00000157-nnn-soci
```

▶（13／38） TW yuuheipapa（ユウヘイ・パパ） 日時： 2020-01-29 12:47:00 +0900 URL： https://twitter.com/yuuheipapa/status/1222365559632945152
{% tweet 1222365559632945152 %}
> 弘中事務所に家宅捜索のニュースは，本当だったようで。 \n \n 誰だ？　そんな令状出したのは？ \n \n 押収拒絶権行使されたら，恥の上塗りだと思うが。それとも，被疑者は弘中さん自身だとか？ \n \n 続報待つだよ

　弘中惇一郎弁護士の逮捕については、法クラの弁護士の間でいくつかツイートを見てきました。検察を批判するための世論喚起の起爆剤としての待望論なのかと想像することはあったのですが、一般人でも逮捕状の要件を満たすだけの根拠の確保は難しそうだとはみていました。

▶（22／38） TW mizuno_ryo_law（福岡の弁護士　水野遼） 日時： 2020-01-29 15:00:00 +0900 URL： https://twitter.com/mizuno_ryo_law/status/1222399112881983490
{% tweet 1222399112881983490 %}
> 令状を出すこと自体おかしい。断固争うべき。 \n \n ゴーン被告逃亡、東京地検が弘中事務所を家宅捜索 \n https://t.co/eCHgNaBq0u

▶（24／38） TW k_kazika（かじか） 日時： 2020-01-29 15:02:00 +0900 URL： https://twitter.com/k_kazika/status/1222399552184963072
{% tweet 1222399552184963072 %}
> うざい。 ゴーン被告不法出国事件、弘中弁護士事務所を家宅捜索 https://t.co/spThwu51gg

　ざっとみたところやはり弁護士らの反応は少ないようです。弘中だけでやってみたいと思います。

　夕方に、法クラにブロックされていることが多い(@hirono_hideki)のアカウントでログインした状態ですが、「弘中」とTwitter検索をブラウザで行ったところ、弘中惇一郎弁護士ではなく、弘中という女子アナに関するツイートがかなりを占めていました。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜todateyoshiyuki（弁護士　戸舘圭之） 日時：2020-01-29 23:37／2020/01/29 13:42 URL： https://twitter.com/kk_hirono/status/1222529227829870592 https://twitter.com/todateyoshiyuki/status/1222379429130686470
> 弁護人の法律事務所に対する捜索はしばしば行われてるようですが、嫌がらせであることは明らかですし、巷の世間の批判の矛先を弘中弁護士達に向けさせようとしている意図がみえみえの悪質な行いだと思います。
▶▶▶　　　　　End　　　　　▶▶▶

```
2020年01月30日00時14分の実行記録
APIのリミットに達するので8500で処理と中断しました。
twitterAPI-search-lawList-mydql-add.rb "弘中"
ツイート数：136/1719 リツイート数：207/1719 トータル：8500
hirono_hideki 21／5件
kk_hirono 32／2件
s_hirono 2／0件
```

[link:] 2020年01月30日00時23分の登録： REGEXP：”弘中”／データベース登録済みツイートの検索：2020-01-29〜2020-01-30／2020年01月30日00時17分の記録：ユーザ・投稿：139／339件 http://hirono2014sk.blogspot.com/2020/01/regexp2020-01-292020-01.html

〈〈〈：Emacs： 2020-01-30（木曜日）00：48 　〈〈〈

