* 「弁護士のなんたるかを知らずに弁護士がどうのと言ってくるアカウントは例外なくクソリパーw」というモトケンこと矢部善朗弁護士（京都弁護士会）のツイート、遡ると７３１部隊のクレーマーという問題
  CLOCK: [2020-02-07 金 13:42]--[2020-02-07 金 14:31] =>  0:49

〉〉〉：Emacs： 2020-02-07（金曜日）13：42　 〉〉〉

:CATEGORIES: モトケンこと矢部善朗弁護士（京都弁護士会）

motoken_tw ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW motoken_tw（モトケン） 日時：2020/02/07 12:34 URL： https://twitter.com/motoken_tw/status/1225623852266377216
> 弁護士のなんたるかを知らずに弁護士がどうのと言ってくるアカウントは例外なくクソリパーw https://t.co/bs6MBLsjFs
▷▷▷　　　　　End　　　　　▷▷▷

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜nora_mike_mike（猫（ミケ）・固定ツイも読んでね） 日時：2020-02-07 13:43／2020/02/07 11:59 URL： https://twitter.com/kk_hirono/status/1225641267029106688 https://twitter.com/nora_mike_mike/status/1225614952687259649
> @motoken_tw @okino3rd 「クレーマーの主張が１００％正しいと言ってるようなもの」 妄想を押し付けられても困ります。 僕がこのスレッドで言及しているのは、編集者と作者の態度。 言っていないことを捏造して反論するの… https://t.co/75vkvOF5N9
▶▶▶　　　　　End　　　　　▶▶▶

TW motoken_tw（モトケン） 日時： 2020/02/07 10:29 URL： https://twitter.com/motoken_tw/status/1225592280184020992
> @nora_mike_mike @okino3rd あなたは、今回のクレーマーの主張が１００％正しいと言ってるようなものですね。 \n そういう人が妥協に言及するなんて噴飯ものです。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜nora_mike_mike（猫（ミケ）・固定ツイも読んでね） 日時：2020-02-07 13:43／2020/02/07 11:59 URL： https://twitter.com/kk_hirono/status/1225641267029106688 https://twitter.com/nora_mike_mike/status/1225614952687259649
> @motoken_tw @okino3rd 「クレーマーの主張が１００％正しいと言ってるようなもの」 妄想を押し付けられても困ります。 僕がこのスレッドで言及しているのは、編集者と作者の態度。 言っていないことを捏造して反論するの… https://t.co/75vkvOF5N9
▶▶▶　　　　　End　　　　　▶▶▶

TW motoken_tw（モトケン） 日時： 2020/02/05 00:54 URL： https://twitter.com/motoken_tw/status/1224722852907081728
> 少年ジャンプ編集部は、ごく一部のクレーマーに屈することによって、どれだけ多くの人を不愉快にさせ、どれだけ多くの読者の心を離反させたのか、ということは何も考えていないのだろうな。 https://t.co/c3izB35qaU

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜jump_henshubu（少年ジャンプ編集部） 日時：2020-02-07 13:46／2020/02/03 18:37 URL： https://twitter.com/kk_hirono/status/1225642061950373890 https://twitter.com/jump_henshubu/status/1224265644155138048
> 週刊少年ジャンプ10号(2月3日発売)『僕のヒーローアカデミア』についてお知らせ  週刊少年ジャンプ編集部 https://t.co/rKzagOJHl0
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-02-07 13:48／2020/02/07 13:37 URL： https://twitter.com/kk_hirono/status/1225642542865117184 https://twitter.com/s_hirono/status/1225639622488682496
> 2020-02-07-131304_モトケンさんはTwitterを使っています　「弁護士のなんたるかを知らずに弁護士がどうのと言ってくるアカウントは例外なくクソリパーw　　Twitter.jpg https://t.co/JvTTpXQneD
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-02-07 13:48／2020/02/07 13:37 URL： https://twitter.com/kk_hirono/status/1225642522505924611 https://twitter.com/s_hirono/status/1225639652851208194
> 2020-02-07-133156_モトケンさんはTwitterを使っています　「@nora_mike_mike　@okino3rd　あなたは、今回のクレーマーの主張が１００％正しいと言って.jpg https://t.co/IM1T61OPO5
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-02-07 13:48／2020/02/07 13:37 URL： https://twitter.com/kk_hirono/status/1225642493535895552 https://twitter.com/s_hirono/status/1225639683423535104
> 2020-02-07-133238_モトケンさんはTwitterを使っています　「少年ジャンプ編集部は、ごく一部のクレーマーに屈することによって、どれだけ多くの人を不愉快にさせ、どれだけ多く.jpg https://t.co/UjGSGkKxMW
▶▶▶　　　　　End　　　　　▶▶▶

　最初、また日本赤十字社の献血ポスターの問題なのかと思っていたのですが、少し見覚えのあった週刊少年ジャンプの問題でした。モトケンこと矢部善朗弁護士（京都弁護士会）のツイートとして見ていたと思うのですが、その最初にみていたときは７３１部隊の問題とは気が付きませんでした。

　すぐに思い出したのは昨日か一昨日に、７３１部隊に関係したツイートを法クラのタイムラインで２つ続けて、タイムラインの最上部付近でみかけていたことです。

［link：］ 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”マルタ”／データベース登録済みツイート：2020年02月07日14時02分の記録：ユーザ・投稿：5／10件 http://hirono2014sk.blogspot.com/2020/02/regexp202002071402510.html

　「ノーマルタイヤ」が「マルタ」に該当していました。「「人体実験をするおっさん」の名前が「マルタ」だから、捕虜で人体実験をした731部隊が想起されるのであって、「マルタ」自体はただの音。」というツイートがありました。

　マルタという人物が人体実験を行ったと読めそうですが、森村誠一の「悪魔の飽食」によれば、人体実験とした中国人やロシア人のことを木の丸太になぞらえ「マルタ」と呼んだ、という話のはずです。

　それにしてもモトケンこと矢部善朗弁護士（京都弁護士会）のツイートが攻撃的で、クレーマーと決めつけているのですが、弁護士商売の繁盛のために故意に燃料投下、挑発をしているように思えます。もともとその傾向は感じてきましたが、今回は特に強くそれを感じました。

　私が森村誠一の「悪魔の飽食」を読んだのは、昭和５７年の秋のことです。西暦にすると１９８２年、今から３７年以上前のことになります。この本を読んだのは、本の評判や知識が全く無い状態で、偶然が重なったことで読んだのですが、衝撃の内容でした。

　もう１０日以上経つと思いますが連日、中国の武漢で発生したとされる新型コロナウィルスのニュースが続いています。昭和の時代は伝染病と呼ばれていたように思いますが、ちょうど２，３日ほど前に「悪魔の飽食」のことを思い出していました。中心となったのはハルピンではなかったかとも思います。

　モトケンこと矢部善朗弁護士（京都弁護士会）が森村誠一の「悪魔の飽食」を読んでいるのかは不明ですが、必要以上に刺激を与えることは、とんでもない危険性があるのではとも懸念します。昨日、今日はテレビで京都の観光に大きな影響が出ていることを取り上げてもいました。

　森村誠一の「悪魔の飽食」については、何年か前、４，５年ぐらいは経っている感覚になりますが、ネットで話題を見かけ調べたことがありました。かなり根拠不明のまま描いた部分もあったようでした。似ていると思ったのが従軍慰安婦の問題ですが、丁度、１，２日前に判決の記事をみました。

　法クラの弁護士のタイムラインで、これも１つだけ見かけたように思います。これも別のエントリーとして取り上げておきたいと思います。

〈〈〈：Emacs： 2020-02-07（金曜日）14：31 　〈〈〈

* 「元朝日記者の控訴棄却　慰安婦記事で札幌高裁」という２月６日の植村隆氏が敗訴のニュース記事、主に弁護士らの反応の記録
  CLOCK: [2020-02-07 金 14:49]--[2020-02-07 金 15:38] =>  0:49

〉〉〉：Emacs： 2020-02-07（金曜日）14：49　 〉〉〉

:CATEGORIES: 札幌高裁,従軍慰安婦問題,ツイートのまとめ

```
元朝日新聞記者の植村隆氏（６１）が、慰安婦について書いた記事を「捏造（ねつぞう）」とされ名誉を傷つけられたとして、ジャーナリストの桜井よしこ氏（７４）と出版社３社に謝罪広告の掲載と損害賠償を求めた訴訟の判決で、札幌高裁（冨田一彦裁判長）は６日、訴えを退けた１審判決を支持し、植村氏の控訴を棄却した。

　冨田裁判長は判決理由で、３社発行の週刊誌などに掲載された桜井氏の記事が、植村氏の社会的評価を低下させたと認定。一方、桜井氏が記事内容を真実であると信じたことについて理由があると認められるほか、公共の利害に関することであるとして、植村氏の社会的評価が低下しても違法性はないとした。

［source：］元朝日記者の控訴棄却　慰安婦記事で札幌高裁 - 産経ニュース https://www.sankei.com/affairs/news/200206/afr2002060014-n1.html
```

　上記の産経新聞のニュース記事は配信時刻が２０２０年２月６日１７時０４分となっています。一昨日に知ったような感覚でいたのですが、昨日のニュースでした。判決自体が同じ２月６日です。

[link:] 2020年02月07日14時36分の登録： ＃弁護士神原元　@kambara7＃のツイート／2020-01-18_1309〜2020-02-07_0123／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2020年02月07日14時36分 http://hirono2014sk.blogspot.com/2020/02/kambara72020-01-1813092020-02.html

[link:] 2020年02月07日14時43分の登録： REGEXP：”植村隆”／データベース登録済みツイート：2020年02月07日14時41分の記録：ユーザ・投稿：54／162件 http://hirono2014sk.blogspot.com/2020/02/regexp20200207144154162.html

[link:] 2020年02月07日14時45分の登録： REGEXP：”植村隆”／データベース登録済みツイートの検索：2020-02-06〜2020-02-07／2020年02月07日14時45分の記録：ユーザ・投稿：9／11件 http://hirono2014sk.blogspot.com/2020/02/regexp2020-02-062020-02_7.html

　ツイートのまとめ記事を２つ作成しました。期限の指定なしが５４ユーザの１６２ツイート、３日以内に指定したものが９ユーザの１１件という結果です。そのまえに神原元弁護士の最新ツイートをまとめていますが、植村隆氏に関するツイートがタイムラインでは見当たりませんでした。

70件目 （リツイート）： kambara7（弁護士神原元）｜akabishi2（akabishi2） 日時：2020-01-27 08:11／2018-10-21 00:44 URL： https://twitter.com/kambara7/status/1221571271390924800 https://twitter.com/akabishi2/status/1053673380337971200
{% tweet 1221571271390924800 %}
> 《弁護士「いかにも本人の発言であるかのような、この文章はどこから持ってきたのですか」 \n 　西岡氏「覚えていないですね。まずいですね」 \n 　弁護士「まずいですよね。これは記事の引用ですか？　元の文書がどこかにないとおかしいですね？」… https://t.co/87XuQ94jVP

121件目 （リツイート）： kambara7（弁護士神原元）｜kambara7（弁護士神原元） 日時：2020-01-22 08:32／2020-01-10 20:33 URL： https://twitter.com/kambara7/status/1219764642961973248 https://twitter.com/kambara7/status/1215597574800826371
{% tweet 1219764642961973248 %}
> 武蔵小杉合同法律事務所開設10周年記念シンポをやります。 \n 3月26日午後6時半開演 \n 　登壇・植村隆、安田浩一 \n 　場所・中原市民館 \n 映画「標的」（短縮版） \n 懇親会予定 \n \n 極右政権とネトウヨをぶっ飛ばそう‼️ https://t.co/da1QMZYiqX

　ページ内検索を行いました、神原元弁護士のTwitterアカウントはプロフィールにも植村隆氏の名前があるのですが、ページ内検索で該当があったのは最新１９９件のツイートのうち２件で、上記に引用したように７０件目と１２１件目となっています。

```
弁護士神原元
@kambara7
2000年から弁護士。武蔵小杉合同法律事務所を主宰。自由法曹団常任幹事。植村隆東京弁護団事務局長。見守り弁護団。著作「ヘイトスピーチに抗する人々」（新日本出版社2014年）。「9条の挑戦 ～非軍事中立戦略のリアリズム」（大月書店2018年）。布施辰治弁護士を敬愛。愛読書「レ・ミゼラブル」。非軍事中立論者。死刑廃止論者。
mklo.org2012年8月からTwitterを利用しています
991 フォロー中
1.8万 フォロワー

［source：］弁護士神原元（@kambara7）さんの返信があるツイート / Twitter https://twitter.com/kambara7/with_replies
```

　プロフィールに「植村隆東京弁護団事務局長」とあります。この引用で気がついたのですが、東京弁護団とありました。今回の植村隆氏の控訴審判決は、札幌高裁となっています。私は最初にこの植村隆氏の問題を知った頃に、札幌の裁判所での勝訴判決をみたと記憶しています。

　そのときは植村隆氏が札幌の大学で教員をしていて、娘に危害が及ぶような脅迫を受けたという裁判であったと記憶にあります。これも５年以上は経っている感覚ですが、この情報は調べてすぐに確認ができそうです。

```
訴状などによると、問題の投稿が行われたのは2014年9月8日午前4時1分。男性は「＠anubis717」のアカウント名を使い、「朝日新聞従軍慰安婦捏造の植村隆の娘、Ａ高校2年植村○○が、高校生平和大使に選ばれた。詐欺師の祖母、反日韓国人の母親、反日捏造工作員の父親に育てられた超反日サラブレッド。将来必ず日本に仇なす存在になるだろう」と書き込んだ（高校名Ａ、長女の名前○○は実名）。制服姿の長女の写真も合わせて掲載。長女は「名誉が傷つけられ、プライバシー権、肖像権が侵害された」と主張していた。

  一方、男性は当初、プロバイダーの問い合わせに対し「ツイッターの投稿は15年12月6日、アカウントごと削除した」「植村氏の娘であることはネット上でも広まっていた公知の事実」「写真は高校のホームページでも公開され、転載にすぎない」などと回答。名誉毀損やプライバシー侵害には当たらないとの考えを示していた。ところが、前回6月22日の第2回口頭弁論に初めて姿を見せた際、裁判官には全面的に謝罪する姿勢に転じた。このため、裁判所は和解を提案したが、長女は「二度と同じ思いをする人が出てほしくない」と判決を望んだという。

［source：］元朝日記者の長女が勝訴 | News Socra （ニュース ソクラ） https://socra.net/society/%E5%85%83%E6%9C%9D%E6%97%A5%E8%A8%98%E8%80%85%E3%81%AE%E9%95%B7%E5%A5%B3%E3%81%8C%E5%8B%9D%E8%A8%B4/
```

　植村隆氏本人が弁護団とともに娘のために行った民事裁判とばかり理解をしていたのですが、高校生の長女本人が原告として裁判をしていたようです。問題の投稿が２０１４年９月８日とあり、東京地裁の判決が２０１６年８月３日のようです。記事の投稿日時と、本文の３日が一致しています。

　１７０万円の損害賠償請求で、全額の１７０万円の支払いを認めた判決となっていますが、この満額の認容というのは初めて見たように思います。悪質性を認めたようですが、刑事事件として告訴はなかったのかと気になるところです。

　ちょうど昨日の２月６日になりますが、テレビのバイキングで、春名風花さんの刑事告訴を警察が不受理にしたという問題が取り上げられていました。ネットでは見ていた情報ですが、弁護士が提出した告訴状を警察が母親に郵送で送り返したという新情報もテレビに報道していました。

　春名風花さんがまだ未成年者であるため、警察が母親に送り返したのだと理解しましたが、弁護士に対する面当てと同時に、弁護士による実質詐欺被害に近い問題としてサインを送ったのではと想像しました。

```
アカウント名	ツイート数	リツイート数
本 秀紀（MotoBuch1228）	0	1
シリウスＡ（eeyy888777）	0	1
ネコマルくん（rxxXoJEnqzBGGOS）	0	1
弁護士 岩山勝湖 Katsuhiro Iwayama, Attorney at Law（LawIwayama）	0	1
Nobuko M Kosuge（nobuko_kosuge）	0	1
江木大輔（daisuke29801）	0	1
鈴木　耕（kou_1970）	0	1
愛（ailuv2u）	0	1
奉納＼さらば弁護士鉄道・泥棒神社の物語（hirono_hideki）	1	2


［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”植村隆”／データベース登録済みツイートの検索：2020-02-06〜2020-02-07／2020年02月07日14時45分の記録：ユーザ・投稿：9／11件 http://hirono2014sk.blogspot.com/2020/02/regexp2020-02-062020-02_7.html
```

　私以外のアカウントが８つありますが、全てがリツイートのようです。植村隆氏は自身の記事を捏造とされたことを名誉毀損とし訴え、敗訴したことになります。裁判所が捏造記事と認めたわけではなく、原告が真実と信じた理由と公益性を認め、違法性なしとあります。

　日韓関係悪化の源泉、最上流の問題というイメージがあったのですが、乏しい弁護士らの反応です。私も控訴審で判決が出ることは知らなかったですが、もともと無関心な弁護士が多くて、大きなニュースになっていないので知らないままの弁護士も多いのかもしれません。

〈〈〈：Emacs： 2020-02-07（金曜日）15：38 　〈〈〈

