* 「「国選ではそこまで無理ぽ」と断ったら、被害者からワイにヘイトを向けられた。」という深澤諭史弁護士のリツイート
  CLOCK: [2020-02-13 木 12:17]--[2020-02-13 木 12:45] =>  0:28

〉〉〉：Emacs： 2020-02-13（木曜日）12：17　 〉〉〉

:CATEGORIES: 深澤諭史弁護士,国選弁護人,被害者代理人

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜O59K2dPQH59QEJx（ピピピーッ） 日時：2020-02-13 12:18／2020/02/13 00:31 URL： https://twitter.com/kk_hirono/status/1227794152730923008 https://twitter.com/O59K2dPQH59QEJx/status/1227616115137769473
> ワイは、「被害者と加害者の対話がしたいから立ち会ってほしい」と被害者代理人が言い出したので、「国選ではそこまで無理ぽ」と断ったら、被害者からワイにヘイトを向けられた。 https://t.co/3LOVmDgUPe
▶▶▶　　　　　End　　　　　▶▶▶

　上記のツイートは次のツイートを公式引用したものです。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜battamon_black（ＫＢブラック（アルコールやめられない）） 日時：2020-02-13 12:19／2020/02/12 16:55 URL： https://twitter.com/kk_hirono/status/1227794368750178307 https://twitter.com/battamon_black/status/1227501392983511045
> 「国選弁護人なのでそういうことはできません」って被害者代理人に言われてもそんなことは知らん
▶▶▶　　　　　End　　　　　▶▶▶

RT fukazawas（深澤諭史）｜O59K2dPQH59QEJx（ピピピーッ） 日時：2020-02-13 10:54／2020-02-13 00:31 URL： https://twitter.com/fukazawas/status/1227773126152339456 https://twitter.com/O59K2dPQH59QEJx/status/1227616115137769473
> ワイは、「被害者と加害者の対話がしたいから立ち会ってほしい」と被害者代理人が言い出したので、「国選ではそこまで無理ぽ」と断ったら、被害者からワイにヘイトを向けられた。 https://t.co/3LOVmDgUPe

　割と最近になって、刑事裁判の被害者代理人にも国選があるという情報を見かけたのですが、ネットでたまたま見かけたような情報で、調べて確認もしていません。テレビでみたことはないとも思います。

　被害者代理人としてテレビでも注目したのは池袋の母子死亡事故と大津市園児死傷事故になりますが、池袋の方はもっぱら遺族の男性が発言をされ、弁護士は横に座っているだけという印象が残っています。

　それに対して、記者会見で代理人弁護士がもっぱら発言をしていたのが大津市園児死傷事故になります。ネットで最後に見かけたニュース記事は、なにかのタイミングでたまたまみかけたものでした。判決日の指定まであったと思いますが、その日付も全く憶えていません。

　その日付の確認もあるので、このあとTwilogで調べながら別のエントリーとして弁護士鉄道の記録を作成します。

　深澤諭史弁護士のリツイートとして見かけたことで感慨深く、味わい深いツイートです。一昨日の夜遅くになりますが、小木港東一文字堤防のアジ釣りから戻ったタイミングで、深澤諭史弁護士が初めてフル出演したというAbemaTVの視聴をしました。

　深澤諭史弁護士が出演したAbemaTVは、昨日の午前中に取り上げる予定でいたのですが、モトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインで福永活也弁護士に関するツイートを見かけ、それが他で見かけていた法クラのツイートとも関連があることがあとでわかりました。

　福永活也弁護士についても前々から取り上げておきたいことがあったのですが、法クラの間で話題をみかけたのも久しぶりのことでした。法クラの間では５０倍とされることが多い福永活也弁護士であります。これも昨日のことのメモとして、別のエントリーとして上げておきたいと思います。

〈〈〈：Emacs： 2020-02-13（木曜日）12：45 　〈〈〈

* Twitterのプロフィールに鹿児島県警本部長とある小野次郎氏のツイートがきっかけで調べた、グリコ・森永事件での滋賀県警本部長の焼身自殺
  CLOCK: [2020-02-13 木 14:54]--[2020-02-13 木 20:33] =>  5:39

〉〉〉：Emacs： 2020-02-13（木曜日）14：54　 〉〉〉

:CATEGORIES: 落合洋司弁護士（東京弁護士会）,警察,未解決事件,大津園児死傷事故

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-02-13 15:01／2020/02/13 13:53 URL： https://twitter.com/kk_hirono/status/1227835135518597120 https://twitter.com/hirono_hideki/status/1227818004320178176
> 2020年02月13日13時52分の実行記録 twitterAPI-search-lawList-mydql-add.rb "石川賢治" ツイート数：0/1740 リツイート数：0/1740 トータル：74 hirono_hide… https://t.co/PxT6pUIbfF
▶▶▶　　　　　End　　　　　▶▶▶

　上記のツイートを投稿したタイミングだったと思うのですが、Twitterのトレンドに懲罰動議というのがあって、そのタイムラインを開いたところ見つけたのが小野次郎氏のツイートになります。以前なにかがきっかけで注目したことのあるアカウントになります。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜onojiro（小野次郎） 日時：2020-02-13 15:05／2020/02/13 13:20 URL： https://twitter.com/kk_hirono/status/1227836075827023873 https://twitter.com/onojiro/status/1227809807857356801
> ヤジを飛ばす総理がお粗末。 だが、長年答弁席に座っている総理がつい野次を漏らす。 野党側が懲罰動議を仄めかす。 TV入り委員会で総理に謝罪させる。 ここまで持って行く腕を持った野党議員は、最近では何人もいない。 今回は、総理の反則… https://t.co/SH3uW85CIF
▶▶▶　　　　　End　　　　　▶▶▶

```
小野次郎
@onojiro
1953年生れ。(公益財団法人)日本航空教育協会会長、鹿児島県警本部長、小泉総理秘書官、参議院議員など歴任。危機管理が専門。改革志向だが戦争は反対。脱原発、自然エネルギー立国。
山梨、東京、そして全国2010年1月からTwitterを利用しています
2.1万 フォロー中
2万 フォロワー

［source：］小野次郎さん (@onojiro) / Twitter https://twitter.com/onojiro
```

　上記に小野次郎氏のTwitterのプロフィールを引用しましたが、１９５３年生まれ、とあるのは昭和２８年のことで、１９６４年生まれの私とは１１歳しか違わないことに気が付きました。プロフィールには歴任とありますが、鹿児島県警本部長というのが最大の注目点です。

　これまでに何度か取り上げていると思いますが、平成２１年の９月から１２月当時の石川県警察の本部長が鹿児島県出身となっていました。大家警部補との電話で本部長のことも話していました。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-02-13 15:15／2010/04/30 23:45 URL： https://twitter.com/kk_hirono/status/1227838665562320902 https://twitter.com/hirono_hideki/status/13132902761
> 昨年の9月頃に、金沢中警察署と石川県警察本部に電話をかけ、本部長宛に上申書を提出することになりました。一度A4用紙6枚ぐらいの上申書を作成し、能登警察署の大家刑事に直接手渡しました。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-02-13 15:14／2011/11/11 11:52 URL： https://twitter.com/kk_hirono/status/1227838434904948742 https://twitter.com/hirono_hideki/status/134825919083855873
> 2009年9月10日付石川県警察本部長宛上申書（能登警察署大家刑事に手渡し）｜アポロン対ディオニュソス http://t.co/jg8MYWbr
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「大家 本部長」の検索結果 - Twilog https://t.co/f1aK4WJdlq

　驚いた発見がありました。平成２１年９月に書面を作成した記憶はあったのですが、それが石川県警察本部長宛の上申書だったとは、もうずっと前に忘れていたものと思います。リンクはアメブロの記事で、「アポロン対ディオニュソス」をブログ名としていた当時のものでした。

　上申書の内容が記事として掲載されていましたが、請求の趣旨が２点あり、２点目が「極めて不適切な職務執行により被った不利益及び慰謝の措置として金壱千万円の支払いを求める。」というものでした。これもすっかり忘れていたのですが、そういうこともあったのか、という感想です。

　目的は平成２１年当時の石川県警察本部長の名前を探すことにあったのですが、思わぬ発見と当時に、警察や弁護士に対する認識も今とはずいぶん違っていることを具体的に再確認できる機会となりました。上記の２点目の後、１行ぐらいしか読んでいないのですが、後で読む予定でいます。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「石川 本部長」の検索結果 - Twilog https://t.co/ifSgBMD83x

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-02-13 15:41／2011/04/02 13:25 URL： https://twitter.com/kk_hirono/status/1227845341124259840 https://twitter.com/hirono_hideki/status/54036761671766017
> 前の石川県警察本部長です。→　警視庁は、５月１５日まで延べ１５０人を派遣する予定。宮園司史生活安全部長は「被災者と絆を結び、真に心のこもった支援をしてほしい」と激励した。 http://ow.ly/4rExo
▶▶▶　　　　　End　　　　　▶▶▶

　ようやく見つけました。宮園司史氏でした。サッカーに前園という有名な選手がいて、テレビで鹿児島県出身という話を聞いていたので、名前が似ていたという記憶は残っていたのですが、同じ前園ではないだろうとは思っていました。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-02-13 15:44／2011/03/25 11:23 URL： https://twitter.com/kk_hirono/status/1227846090461863936 https://twitter.com/hirono_hideki/status/51106916990062592
> 金沢西警察署に電話をして、再捜査の行方について確認をしました。正式は要望書は出していないですが、宮園石川県警本部長にはその旨の書面を提出してあります。 http://twaud.io/qMRg
▶▶▶　　　　　End　　　　　▶▶▶

```
県警新本部長の着任会見

広島県警の新しい本部長が着任し、会見を開きました。

新しく県警本部長に就任した宮園司史さんは、兵庫県出身の５３歳。

１９８３年に警察庁に入庁し、石川県警本部長や防衛省の大臣官房審議官などを歴任しました。

会見では、「力強い警察を確立し、全国一安全安心な広島県を実現させたい」と抱負を述べ、廿日市市の女子高校生殺害事件など未解決事件の捜査に力を入れたい、と話しました。

（県警　宮園司史本部長）

「この種の事件の解決は、県民の皆様が安心して生活していただく上でも、最重要課題の１つであると、粘り強く捜査を進め、１つ１つ解決に結びつけ、被害者やご遺族の方の無念を晴らしたい」

［2014.9.16 11：59］

［source：］宮園司史　県警新本部長の着任会見 - アルコール・カフェイン業界のステマ広告と事件・事故 https://blog.goo.ne.jp/alcoholdanger/e/2cd69d78add3a7047083e2dd4c2fe880
```

　上記の記事には兵庫県出身とあります。広島県警本部長としての着任会見とありますが、これも眠っていた記憶が呼び起こされたような感覚です。２０１４年９月とあるので６年ほど前になります。定年のことは調べていないですが、これをみるとまだ定年退職前の可能性もありそうな気がしてきました。

```
警察庁長官官房付に７日付で転出する県警の宮園司史本部長（５５）が６日、県警本部で離任会見をした。約１年９カ月の在任期間について「充実した日々を過ごすことができた」と振り返った。

　宮園本部長は、４月に広島市であった外相会合とオバマ米大統領の広島訪問に伴う警備を印象に残った出来事に挙げ、「広島の歴史に残る仕事の一端を担えたことに感謝したい」と強調。「県民の協力と理解がなければやり遂げることはできなかった」と述べた。

［source：］オバマ氏広島訪問　「警備やり遂げた」　宮園・県警本部長が離任会見 | ヒロシマ平和メディアセンター http://www.hiroshimapeacemedia.jp/?p=60432
```

　県警本部長の任期というのは不思議と考えたこともなかったのですが、３月１１日に決選投票が行われるという日弁連の会長は任期が２年という情報をみかけたように思います。上記の中国新聞の記事は２０１６年６月７日とあります。

```
ベストアンサーに選ばれた回答
 

焼鳥 美依瑠さん 2014/1/2822：19：34
警察庁長官官房付、というのははっきり言ってなにもしません。
というのも、基本的に長官官房付は次のポストへ向けた待機の期間に就くような短期の役職で、数か月程度で異動になります。人事の調整のためのポスト、とも言えますね。その間、雑務に近いようなことはしますが、法案の作成のような大仕事に携わることはありません。
あるいは、不祥事を起こした警察庁の警察官が処分が決まるまで長官官房付、となることもあります。ちなみに都道府県警では、不祥事を起こした警察官は、処分まで警務部付になります。

［source：］警察庁長官官房付きとはおもにどんなことをするんですか？わからない人でもわ... - Yahoo!知恵袋 https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q13120139068
```

```
宮園 司史みやぞの つかし

環太平洋大学教授、広島大学客員教授

東京大学法学部卒。 昭和58年警察庁入庁。在香港日本国総領事館領事、石川県警察本部長、防衛省大臣官房審議官、広島県警察本部長を経て関東管区警察局長を最後に退職（平成29年）。警察庁、防衛省、外務省等での勤務経験を踏まえ、上記大学等において主にコンプライアンス、危機管理、サイバー・セキュリティ、大規模災害対処等に係る講義・講演を行っている。内容的には第一線の実務経験を生かし、各種事例に基づき演題に即した具体的な対応策について講演を行う。

講演実績・著書等
【講演】大学、経済関係団体、企業等での講演多数

講演ジャンル
ビジネス コンプライアンス ビジネス 危機管理 ビジネス サイバー・セキュリティ ビジネス 大規模災害対策

［source：］講師派遣紹介 l 公益財団法人 労災保険情報センター https://www.rousai-ric.or.jp/tabid/552/Default.aspx
```

　「広島県警察本部長を経て関東管区警察局長を最後に退職（平成29年）」という情報をみつけました。年齢を推定させる情報はないですが、警察を定年退職したとは思えない若さの顔写真が一緒になっています。

```
 保存 共有 印刷その他
石川県警と警察庁などは10日、約4150万円に上る県警の不正経理に絡み、横山雅之埼玉県警本部長を減給100分の10（1カ月）の懲戒とするなど石川県警の元本部長4人を含めた計131人の処分を発表した。

懲戒処分は横山氏のほかに、宮園司史警視庁生活安全部長、渡辺巧中部管区警察局長、谷直樹警察大学校教務部長の元本部長3人と、元警務部長2人の計5人を戒告とした。防衛省に帰任した別の元警務部長について、警察庁は戒告相当と同省に通知した。

［source：］元本部長ら131人処分　石川県警の不正経理　　：日本経済新聞 https://www.nikkei.com/article/DGXNASDG1005C_Q1A210C1CC1000/
```

　上記は２０１１年２月１０日の記事となっています。退職した警察官の処分というのは聞いたことがないですが、「防衛省に帰任した別の元警務部長について、警察庁は戒告相当と同省に通知した。」というのも参考になる情報です。

```
どんなに勉強したってかなわない相手がいる。教科書をパッと読んだだけで、教師の話をさっと聞いただけで、すべてを、いやそれ以上を理解してしまう人たちだ。彼らは幼いころ、神童と畏敬の念をこめて呼ばれていた。

　神童は大人になってどうなったか。願わくば、頭の良さを生かして、社会のために役立ってほしいところだが、小泉純一郎の迷フレーズ「人生いろいろ」である。そこで、新刊『神童は大人になってどうなったのか』（太田出版）では、愛すべき神童たちを追いかけてみた。みなさんにたいへんな敬意を表しつつ、敬称略をお許しください。

［source：］「灘高校1979年卒」の神童は、大人になってどうなったのか？ | 神童は大人になってどうなったのか？ | 文春オンライン https://bunshun.jp/articles/-/4081
```

```
灘中学・高校。神童の宝庫である。指折りの天才、秀才が集まった。


勝谷誠彦氏　©文藝春秋
　なかでも1979年卒業生の面々には、やたらと濃いキャラクターが集まった。勝谷誠彦、和田秀樹、中田考、吉田尚正、宮園司史、井内摂男、西川知一郎、伊藤芳朗、飯泉嘉門。彼らは1960年、61年生まれ。わたしと同学年だが、まるで別世界に住む人たちに見えた。

［source：］「灘高校1979年卒」の神童は、大人になってどうなったのか？ | 神童は大人になってどうなったのか？ | 文春オンライン https://bunshun.jp/articles/-/4081
```

　思わぬかたちで、宮園司史氏の年齢がわかる情報が出てきました。記事は文春オンラインとなっています。勝谷誠彦氏は、ちょうど宮園司史氏が石川県警察本部長だった頃、テレビの「そこまで言って委員会」の常連コメンテーターとして見ていたように思います。たかじん、の時代です。

```
もう1人、警察官僚がいた。元広島県警察本部長の宮園司史だ。2014年、オバマ米大統領の広島訪問に伴う警備で陣頭指揮をとった。その後、警察庁長官官房となり、最近、退職している。

［source：］「灘高校1979年卒」の神童は、大人になってどうなったのか？ | 神童は大人になってどうなったのか？ | 文春オンライン https://bunshun.jp/articles/-/4081
```

```
関西のお笑いの雰囲気をかもし出す、灘神童79年卒業組
　宮園と灘高時代に成績を競い合ったのが井内摂男、西川知一郎。灘高文系トップ3と言われた。なかでも井内は駿台、Z会などで上位成績者に登場し、同年代の受験生にとってはヒーローだった。神童・勝谷も小学校時代に井内をどうしても超えられなかったと振り返る。井内は経産省官僚となった。中部経済産業局長時代、「地方創生コンシェルジュ」と銘打って、地域発展の陣頭指揮をとった。50代半ばにすっかり悪名高い内閣府の知的財産戦略推進事務局長に就任。やはり最近、退職した。安倍、菅体制がいやになったのか。

　西川は法曹の世界に入った。現在の肩書きは福岡高裁宮崎支部部総括判事である。最近では、九州電力川内原子力発電所の再稼働に反対する住民側の申し立てを退けている。原発容認派裁判官として、原発反対派から嫌われてしまう。

　西川とは法廷で顔を合わせることがあるかも知れないのが弁護士の伊藤芳朗だ。

　1990年代半ば、オウム真理教事件ではワイドショーに出ずっぱりだった。タレント弁護士的な役回りを果たしたが、テレビ番組制作に肩入れしすぎてしまう。番組の依頼で弁護士の立場を利用し、戸籍謄本などを不正に取得して金銭を受け取ったとされ、東京弁護士会から業務停止4カ月の懲戒処分を受けてしまった。どこか憎めない。


飯泉嘉門氏　©文藝春秋
　吉田、宮園、井内、西川、伊藤は灘らしくすべて東京大法学部卒。飯泉嘉門もそのお仲間だ。飯泉は自治省官僚を経て、2003年から徳島県知事を4期つとめる。県知事選の公約にJリーグに加盟するチームを作ることを掲げている。自治省時代、2002年のワールドカップで試合会場となった新潟県や埼玉県に出向したとき、地域活性化を目の当たりにしたからという。それが、現在のJ2チーム、「徳島ヴォルティス」だ。勝谷と灘知事会は作れなかった。

　ついでにもう1人。勝谷が灘中学に入学早々のこと、通学途中で「会社四季報」を読みながらぶつぶつ呟いている、一学年上の中坊を見かけた。のちの村上ファンドである。やや都市伝説っぽいが、村上世彰は78年卒。1年浪人して東京大法学部へ進み、通産省を経て、M&Aコンサルタント会社を興す。インサイダー取引で逮捕歴はあるが、いまでも意気揚々だ。最近、『生涯投資家』（文藝春秋）を上梓して上場企業のあり方を問いかける。もの申す姿勢は変わらず、なかなか懲りない。

　こうした灘神童の面々は社会にどんな影響を与えたか。

［source：］(2ページ目)「灘高校1979年卒」の神童は、大人になってどうなったのか？ | 神童は大人になってどうなったのか？ | 文春オンライン https://bunshun.jp/articles/-/4081?page=2
```

　神童という言葉自体が死語のようになっていて、長い間見かけることがなかったのですが、上記の文春オンラインの記事は２０１７年９月１３日となっています。神童という言葉は私の脳内で定期的に思い出すものではあったのですが、ほとんどが小倉秀夫弁護士と紐付いていました。

　たぶん昭和３５年４月１日から昭和３６年３月３１日が宮園司史氏の生まれになるのだと思います。学年でいえば４つ年上、私が能都中学校の１年生の時に石川県立水産高校の相撲部で２年生だった人たちと同級生なのだと想像します。

　なにか大きな不祥事か疑惑でもなければ、文春オンラインの記事になることのなかった宮園司史氏だと思いますが、小野次郎氏のツイートをきっかけに、こういう情報が見つかるとは、インターネットの情報網というものをあらためて考えさせられました。

　直接、記憶にはないものの大家警部補に手渡しで、当時の石川県警察本部長だった宮園司史氏宛に上申書を提出していました。返事のようなものはもらっておらず、立場の違いもあるので仕方がないと思っていたのですが、そうではないという可能性も同時に模索していきたいと思いました。

　次に、自殺したという元滋賀県警本部長のことです。このことは落合洋司弁護士（東京弁護士会）のツイートで初めて知ったはずかと思います。自殺したという情報はしっていたものの、検索したのもたぶん今回が初めてで、焼身自殺と知ったのも驚きでした。

　焼身自殺というのも私が最近注目をしていたワードで、それがネットで石川県最強の心霊スポットともされる牛首トンネルになります。そのいわれの始まりが、若者のトンネル内での焼身自殺にあったというネット上の話です。

　一昨日の２月１１日、小木港の東一文字堤防にアジとヤリイカ釣りに行っていましたが、かほく市から来ている人がいて、その人とはけっこう前から顔見知りで親しく話す間柄です。７０代と聞いたように思います。正確な年齢や生年も聞いていたのですが、ちょっと忘れています。

　まずそのかほく市の７０代の人に尋ねたのですが、牛首という集落のことはよく知っているし、行ったこともあるが、牛首トンネルの話は全く知らなかったといい、スマホで検索した情報を見せたところ、笑いながら呆れたような様子にもみえる反応でした。仕事柄交際範囲も広い人です。

　そのあと、同じかほく市の高松から来たという青年とも話をしました。年齢のことは聞かなかったですが２０代にみえました。牛首トンネルのことはよく知っているといい、行ったこともあると話していましたが、殺人や焼身自殺のあったことは全く知らないと話していました。

[link:] » かほく市、石川県 から 字牛首 - Google マップ https://t.co/NJUf562pYJ

　かほく市の中心は宇野気になるようです。つい最近になってテレビでかほく市の市役所の位置を知ることがあり、宇野気でも津幡寄りに見えました。市役所の建物はみておらず、手書きのような地図に記載があったものです。話題も市役所とは別にあったはずです。

　河北郡の宇野気町、七塚町、高松町の３つが合併して出来たのがかほく市と聞いています。割と最近に知ったのですが、津幡町と内灘町は現在もそのまま河北郡として残っているとのことです。その河北郡の方が金沢市と隣接していることになりますし、町の規模も大きく感じます。

```
河北郡（かほくぐん）は、石川県（加賀国）の郡。ここでは前身にあたる加賀郡（かがぐん）についても記述する。

人口63,400人、面積130.92km²、人口密度484人/km²。（2020年1月1日、推計人口）

以下の2町を含む。

津幡町（つばたまち）
内灘町（うちなだまち）

［source：］河北郡 - Wikipedia https://ja.wikipedia.org/wiki/%E6%B2%B3%E5%8C%97%E9%83%A1
```

　調べてみると、河北郡の人口は６万３４００人とのことです。別に珠洲市を調べたところ、本州にある市の中で１番人口が少ないとあり、棒グラフがあるのですが、ピーク時の１９５０年で３万8千人ほど、２０１０年代の中ほどには１万５千人を下回っているように見えます。

　具体的数字の人口は見当たらないのですが、それもページのかなり下の方に出てきた情報で、さきに珠洲市の語源について記載がありました。

```
語源［ソースを編集］

須須神社
「スズ」の地名
「須須神社社伝縁起　第一」に高倉宮・金分宮の2社からなることが出ており、高倉宮主神ニニギノミコトが来臨した折、鈴を以てこの地を鎮める、とある。鈴の万葉仮名が須須・須受で、その佳名が珠洲。 スズの地名はそこからとったもの。 金分宮の主神が美穂須須見命（ミ・ホ・スス・ミ・ノ・ミコト）で、稲穂の豊かな実りを象徴している。豊かな稲穂を振って音を立てる様子が鈴である。 大伴家持が天平21年（749年）都の妻に贈るため真珠を願う歌を詠むが、そこには「珠洲の海人の沖つ御神にい渡りて…」とあり、半島先端部の広い範囲が珠洲（真珠のような洲）と意識されていたようである。

沿革［ソースを編集］
古代［ソースを編集］
第10代崇神天皇の時代（紀元前97年 - 紀元前29年）：須須神社創建の伝承
珠洲郡の名の初出は713年（和銅6年）の「平城京出土木簡」　表（越前国珠洲郡月次里）　　裏（庸舟木部　申　六斗）
718年（養老2年）5月2日：越前国から羽咋郡、能登郡、鳳至郡、珠洲郡の四郡を分立して能登国成立。

［source：］珠洲市 - Wikipedia https://ja.wikipedia.org/wiki/%E7%8F%A0%E6%B4%B2%E5%B8%82
```

　須須神社は、割と最近になって場所をしったのですが、車で前の道路を通過したことしかありません。バイクでは立ち寄っていないことになります。珠洲の三崎になります。三崎でも寺家になるのかと思われます。能登最大のキリコの寺家の祭りは、YouTubeでみていますが、大きな神社がありました。

```
須須神社は日本海側一帯の守護神とされ、第10代祟神天皇の時代に創建された由緒ある神社です。祭神は、寺家高座宮の主神高倉彦神（たかくらひこのかみ）と山伏山山頂の奥宮に祀られている美穂須須美命（みほすすみのみこと）です。須須神社の宝物殿には、国指定重要文化財の木造男神像や、数々の古文書、義経ゆかりの品々が収蔵されています。中でも「蝉折の笛」は義経が海難を救われたお礼として奉納した宝物の一つです。

須須神社では、毎年3月15日に伝統行事の的打神事が行われます。流鏑馬から派生した神事で、悪神を矢で退治し一年の平安を祈ります。参拝者が的に命中させると幸運になると伝えられています。

［source：］須須神社 https://www.city.suzu.lg.jp/kankounavi/spot/history/temple/suzu_shrine.html
```

　「祭神は、寺家高座宮の主神高倉彦神（たかくらひこのかみ）と山伏山山頂の奥宮に祀られている美穂須須美命（みほすすみのみこと）です。」、山伏山というのも余り聞いた覚えはないのですが、美穂須須美命というのは今初めて見たような神様のお名前です。

```
記紀神話には出てこない、『出雲国風土記』固有の神。

国引き神話で結ばれる出雲の「美保関」と越（能登半島）の「珠洲岬」に鎮座する。いわば出雲と越のつながりを象徴する神。
御穂須須美命は、『出雲風土記』に所造天下大神と奴奈宜波比売命との子とある神で、 御穂須須美命が座したことから美保郷の名がついたとある。

［source：］御穂須々美命（みほすすみのみこと）／日本の神々の話 ： 四季歩のつれづれ http://tamtom.blog44.fc2.com/blog-entry-2334.html
```

```
出雲を発った出雲族が日本海を北上し、能登半島に上陸した痕跡が珠洲市にある、御穂須須美命を祭神とする須須神社である。
一方、長野県の千曲川流域を主として、御穂須須美命を祭神とする神社が十社ほど存在する。中野市の越智神社、佐久市の諏訪神社、埴科郡坂城町の坂城神社など。
これは越後の海岸に上陸した出雲族が信濃川から千曲川に沿って遡った痕跡である。
天穗日命や大国主命を祭神とする「出雲－祝」系神社も、新潟県の出雲崎から埼玉県の入間市までたどることが出来る。

［source：］御穂須々美命（みほすすみのみこと）／日本の神々の話 ： 四季歩のつれづれ http://tamtom.blog44.fc2.com/blog-entry-2334.html
```

　上記に２箇所の引用を行いましたが、「国引き神話で結ばれる出雲の「美保関」と越（能登半島）の「珠洲岬」に鎮座する。いわば出雲と越のつながりを象徴する神。」というのも全く知らなかったと思います。

　島根県の美保関は一度行ったことがあるはずなのですが、記憶にあるのは鳥取県境港市に架かる大きな橋のことです。現在は出雲市となっている平田市の缶詰工場にに筍を持っていった記憶があり、たぶんそちらから境港市に向かった時のことと思います。妻と長男が同乗していました。

　私はカメラを所持しておらず、古い白黒カメラはあったと思いますが使うことはありませんでした。金沢市場輸送の長距離トラック運転手の仕事で撮影した写真は、愛媛県の松山市から東京、そして千葉県の犬吠埼に向かった運行と、境港市があるのみです。四国での撮影はなぜかありません。

　たぶん海の向こうに大山、が見える場所で撮影した長男の写真があったのですが、横縞の半袖シャツに赤い短パンで、カメラの撮影の前後には、大山に向かって全身で雄叫びをあげるような行動があり、とても印象的に憶えています。季節的に１歳と２ヶ月ぐらいかと思う頃のことです。

　平田市や境港市のことは、前にも少し触れていると思います。境港市からは鮮魚を積んで金沢に戻った記憶があるのですが、境港市では仕事を受けた運送会社の建物は記憶にあるものの、どこで食事をしたのか思い出せないのも不思議に思っています。

　もう１つ中国自動車道、関門海峡の手前の壇ノ浦サービスエリアで明け方に長男と撮影した写真のことを思い出しましたが、あれはたまたま居合わせた運転手仲間にその場で撮影してもらい後でもらった写真だと思います。１枚か２枚しかなかった写真で、よく行った九州で撮影した写真は１枚もありません。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜onojiro（小野次郎） 日時：2020-02-13 18:09／2020/02/13 13:55 URL： https://twitter.com/kk_hirono/status/1227882407761596416 https://twitter.com/onojiro/status/1227818508391604224
> コロナウイルス感染。 クルーズ船内がパンデミック！ 短期間この船に乗船して香港で下船したという人物からのウイルス感染では説明できない規模に拡散している。 船内衛生管理、検疫方法、検査・医療体制に重大な問題あり。 厚労省の責任も免れ… https://t.co/ZEPpOVwM4R
▶▶▶　　　　　End　　　　　▶▶▶

　さきほどリツイートしたツイートと同じ４時間前と表示されている小野次郎氏のツイートをリツイートしました。「厚労省の責任も免れない。」とありますが、早期に下船させ、クルーズ船の乗客乗員以外に感染が広がっていれば、もっと大きな問題として同じ責任の指摘がありそうです。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-02-13 18:20／2020/02/13 14:47 URL： https://twitter.com/kk_hirono/status/1227885337566801922 https://twitter.com/hirono_hideki/status/1227831522637443072
> 元捜査員300人以上の証言から見えてきた新しい真実。いまもっとも「犯人に近づいた」本－グリコ・森永事件 - ニャムレットの晴耕雨読｜ニャムレットの晴耕雨読 https://t.co/YFiWf563Nn およそ9ヵ月後の昭和60年… https://t.co/2HAwOFdVai
▶▶▶　　　　　End　　　　　▶▶▶

　上記にリツイートしたツイートの全文がAPIで取得できていませんが、「およそ9ヵ月後の昭和60年8月7日、滋賀県警察本部長の山本昌二さんが退職したその日に官舎で焼身自殺を図ります。」というのが記事の引用部分になります。

　Google検索では、はっきり見出しでわかる情報は見当たらなかったのですが、要約の部分に「山本昌二さん」という名前が見えて、他のニュース出来事を一覧にしたページもたまに見ることがあるので、中日の野球選手で活躍した投手の名前ではと思いました。

　テレビのスポーツニュースでは「やまもとまさ」と呼ばれていましたが、現役当時は昨日辺りにTwitterのトレンドで知った野村克也監督の全盛期とも重なっていたように思います。普段は野球を見ることがなかったので、これも福井刑務所の服役中のことかと思います。

　今日は起きた時間が遅く１１時過ぎで、目がさめてすぐにスマホで電話がなりそうと思って２，３秒後に本当に電話がなり、スマホを探す間にぎりぎりのタイミングで切れたのですが、宇出津の図書館からの電話でした。３冊取り寄せで頼んだ１冊は４月になります、という確認の電話でした。

　もう４，５年は利用していなかったと思いますが、VBAの本１冊とpythonの本を２冊お願いしました。図書館のパソコンで石川県の横断検索を行ったのですが、いつのまにかページのデザインが一新し、以前とは全く違ったものになっていました。

　深澤諭史弁護士の本を探して取り寄せることも考えたことはあったのですが、不思議と実行に移すことがありませんでした。今回も深澤諭史弁護士の本は探してもいません。自分のパソコンではまだ開いてもいない石川県の横断検索になります。

[link:] » 石川県 横断検索 - Google 検索 https://t.co/xn3bDNyY5l

[link:] » 石川県内図書館横断検索 https://t.co/t5RcDlDn3c

```
2件見つかりました。
タイトル著者名出版者出版年ISBN所蔵館
インターネット利用の心得ケーススタディ ： 知らないではすまされない鳥飼重和監修 ： 香西駿一郎執筆 ： 神田芳明執筆 ： 深沢諭史執筆201443221257193
その「つぶやき」は犯罪です ： 知らないとマズいネットの法律知識神田芳明 ［ほか］ 著新潮社2014.51
検索対象の絞り込み

すべて
石川県立図書館


［source：］石川県内図書館横断検索 https://www.library.pref.ishikawa.lg.jp/wo/cross/?q=%E6%B7%B1%E6%BE%A4%E8%AB%AD%E5%8F%B2
```

　ページタイトルは変わらない仕様となっているようですが、URLにはリクエストパラメータにｑという変数にエンコードした深澤諭史という文字列があります。見つかったのは２件で、どちらも複数人との共著となるようです。

　検索結果の項目をクリックすると、所蔵図書館の情報が出てきました。アジャイルを使ってブロック要素の書き換えを行っているようですが、クリックでのイベント発生は不思議に見かけない技術です。ちょうど１０年ほど前にはRailsでよく使っていました。フェードイン、フェードアウトなど。

　フェードイン、フェードアウトのアジャイルも不思議と見かけることがありません。ページ内の変化をわかりやすく伝えるためのものと思いますが、見かけることがありません。技術的にはとても簡単なものだったのでなおさらに不思議です。jQueryとかで簡単にできるはずです。

　今日はグッディが始まる前の時間にテレビを消してつけていません。時刻を見ると１８時５３分となっていました。テレビを消す前から今日は深澤諭史弁護士のタイムラインも見てはいない気がします。それだけ別のことに集中をしていたことになりますが、法クラのツイートの頻度も不思議な現象です。

　実は、アジャイルという言葉を見たのも数年ぶりなのですが、自分でGoogle検索をやって目にしたものになります。俊敏という意味があるというのも初めて知ったのですが、以前はAから始まるアルファベット３文字での表記が多かったと思うのですが、その情報も見つかりません。

```
今回はAjax（エイジャックス）を取り上げます。Web 2.0の代表的な技術として取り上げられ、一世を風靡（ふうび）したAjax。皆さんも“Ajax”という言葉自体は知っていると思います。

　Ajaxを使ったサイトといえば、Googleマップなどが有名ですね。AjaxはGoogleマップによって世に知れわたったといっても過言ではないと思います。

［source：］いまさら聞けない、“Ajax”とは何なのか？ (1/3)：いまさら聞けないリッチクライアント技術（3） - ＠IT https://www.atmarkit.co.jp/ait/articles/0708/23/news134.html
```

　アルファベットの大文字３つと思っていたのですが、それは記憶違いでAjaxだったようです。エイジャックスと読むようですが、これもずっと見かけることはなかった用語になります。上記の記事は２００７年８月２３日公開となっています。

　「「DOM」「XML」「XMLHttpRequest」「非同期処理」「JavaScript」。これらのキーワードがAjaxと密接な関係があるようです。」とあります。

　深澤諭史弁護士が出演したAbemaTVでは、参議院議員の山田太郎氏がコインハイブ事件についてjavascriptを繰り返し強調していました。javascriptというのも見かけなくなっていたのですが、アジャイルよりかなり古い技術になりそうです。

　数年前までYouTubeに使われていたflashも消えてしまった技術で、それが原因でパソコンでのアメーバピグもサービスが終了しさみしいことになりました。

　「＠IT eBook（60） - ＠IT」というサイトですが、ホームページのデザインの文字の配置と大きさが良く出来ていて見やすいと感じました。弁護士の法律事務所のホームページでは業者に作成してもらったようなものを見かけますが、あとは普通のブログサービスがほとんどです。

[link:] » 石川県内図書館横断検索 https://t.co/DTzCpXWopD

［link：］ 石川県内図書館横断検索 https://www.library.pref.ishikawa.lg.jp/wo/cross/?q=%E9%87%91%E6%B2%A2%E5%BC%81%E8%AD%B7%E5%A3%AB%E4%BC%9A

　上記は「金沢弁護士会」を検索ワードに指定したものですが１１１件とあります。mozcの単語登録で「ｋｂ」というのを金沢弁護士会と北周士弁護士に割り当てているのですが、北周士弁護士を探すつもりだったのが、誤変換となり、それでもやってみようという検索になりました。

```
2件見つかりました。
タイトル著者名出版者出版年ISBN所蔵館
弁護士 ： 転ばぬ先の経営失敗談北周士編著東京 ： 第一法規2015.344740299411
弁護士独立のすすめ北周士編著東京 ： 第一法規2013.244740283171
検索対象の絞り込み

すべて
石川県立図書館


［source：］石川県内図書館横断検索 https://www.library.pref.ishikawa.lg.jp/wo/cross/?q=%E5%8C%97%E5%91%A8%E5%A3%AB%E5%BC%81%E8%AD%B7%E5%A3%AB
```

　深澤諭史弁護士も２件だったと思いますが、北周士弁護士も同じ２件でありながらいずれも単著となっているようです。深澤諭史弁護士や北周士弁護士、野田隼人弁護士、向原栄大朗弁護士らの共著もあったはずですが、所蔵はされていないのかもしれません。

　野田隼人弁護士、向原栄大朗弁護士ともに石川県図書館横断検索で所蔵はみつかりませんでした。弁護士の部分を除いての検索も行ってのことです。どういう基準で所蔵しているのかは不明ですが、最近の法律関係の所蔵は意外に少ないのだということは確認が出来たように思います。

　「およそ9ヵ月後の昭和60年8月7日、滋賀県警察本部長の山本昌二さんが退職したその日に官舎で焼身自殺を図ります。」というのは、計算すると昭和５９年の１２月になります。

　グリコ・森永事件は、テレビでとても大きな報道が長く続いていたと記憶にありますが、ワイドショーなどで報道を見た記憶はなく、テレビをほとんどみない時期だったのだという推定はありました。個別に事件の時期を調べるつもりでいたのですが、その前に見つけたものになります。

　一連の犯行の終結が昭和５９年１２月になるようですが、一連の犯行の始まりはまだ確認をしていません。私の名義で借りた金沢市東力二丁目のアパートですが、考えてみるとずっと長い間、テレビはなかったように思います。昭和６１年３月に結婚をして、その前後にテレビを買った記憶はあります。

　今頃になって思い出したのですが、昭和６０年の秋頃にはテレビがあったと思います。たぶん再放送になるのですが、夕方に「スチュワーデス物語」と「スクールウォーズ」をみていました。大きいテレビを買ったのはやはり結婚をした前後になるとは思います。あるいはもっと後かもしれません。

　昭和６０年当時のテレビというのは小型のものでもかなり高い値段だったと思いますし、アパートの家賃を滞納することや、ガスが停められ冬場に水風呂に入った時期にテレビを買えたとは到底考えられないことです。しかし、大きなテレビを買う前のことは思い出せません。

[link:] » マグニチュード7 - Twitter検索 / Twitter https://t.co/dfh6dJt6kC

　１９時前にテレビをつけるつもりで、それが１８時５５分あたりのことですぐに忘れていたのですが、Twitterのトレンドで地震があったことをしりました。震源地が択捉島南東沖とあります。マグニチュード７がトレンドになっていますが、最大震度は４とのことです。

　今回は落合洋司弁護士（東京弁護士会）の過去のツイートを探すというタイミングでのトレンドの発見でした。

　平成２１年より前からブログをみていた落合洋司弁護士（東京弁護士会）のことで最も印象深いのは、昨年２０１９年３月末から４月初めに掛けた立憲民政党の参院選公認取り消しの話題ですが、ちょうど同じ頃にみたのが「子どもが好きな神様」というYouTube動画でした。

　時刻は１９時５６分ですが、ふたたびTwitterに目を移したところ、トレンドに槇原敬之の逮捕があって、１５７，８６８件という大きな自然災害の発生並、あるいはそれ以上の反応となっています。名前を聞いてもっとも印象深いのは山口貴士弁護士の銀河鉄道９９９のブログ記事のことです。

　槇原敬之氏は以前にも薬物使用で逮捕されていたと思いますが、ずいぶんと長い間があったと思うので、それだけに衝撃やニュース性が高く併せて弁護士のことも再び注目される好機となりそうです。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜nhk_shutoken（NHK@首都圏） 日時：2020-02-13 20:01／2020/02/13 17:23 URL： https://twitter.com/kk_hirono/status/1227910663600627713 https://twitter.com/nhk_shutoken/status/1227870915452534785
> 歌手の槇原敬之容疑者が、覚醒剤取締法違反の疑いで警視庁に逮捕された。 https://t.co/plukLDzLSR
▶▶▶　　　　　End　　　　　▶▶▶

　上記のNHK@首都圏のツイートもリツイートの数が１．７万として表示されています。このようなニュースのTwitterアカウントは意外なほどリツイートの数が少なことが多く、１千件を超えたものは見たことがなかったように思うのですが、いきなり１．７万件を目撃しました。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜news24ntv（日テレNEWS） 日時：2020-02-13 20:04／2020/02/13 17:20 URL： https://twitter.com/kk_hirono/status/1227911524800352256 https://twitter.com/news24ntv/status/1227870113262473216
> 警視庁が歌手の槇原敬之容疑者を逮捕　覚せい剤取締法違反容疑 https://t.co/z6FMsqZFWM #槇原敬之 https://t.co/hEn7cALrIk
▶▶▶　　　　　End　　　　　▶▶▶

　上記のツイートには動画でのニュース映像があるのですが、再生していると女子アナの同じ言葉が繰り返され、確認すると１９秒という再生時間でした。これほど短いニュース動画をみたのもおそらく初めての経験です。

　もともと再犯の数が多く常習性が強いと思われていたタレントの田代まさし氏のときも、安倍政権が不利な時に警察が逮捕をしたという憶測を見かけていたように思いますが、今回の槇原敬之氏の逮捕は、警察がずっと生け簀の魚やイカのように泳がせていたものを使った印象があります。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜news_abematv（AbemaTVニュースch） 日時：2020-02-13 20:09／2020/02/13 17:19 URL： https://twitter.com/kk_hirono/status/1227912684193996800 https://twitter.com/news_abematv/status/1227870006068645893
> 【ニュース速報】 槇原敬之容疑者(50)を逮捕 覚せい剤取締法違反  警視庁はさきほど、歌手の槇原敬之容疑者を覚せい剤取締法違反容疑で逮捕した。 #AbemaNews
▶▶▶　　　　　End　　　　　▶▶▶

　「さらば弁護士鉄道」というのが私が掲げるテーマ、目標になりますが、そういえば、さきほど珠洲市の三崎の神社に源義経が奉納をしていたという話を読んでいたことを思い出しました。

　時刻は２０時２７分です。昨夜の続きで下処理済みのアジフライを作る予定でいますが、夕食もまだです。深澤諭史弁護士のタイムラインをみたところですが、槇原敬之の逮捕の問題も消し飛ぶような発見がありました。そのアカウント名も「弁護士の母」となっています。

　本項目で取り上げた元滋賀県警本部長の焼身自殺ですが、一通りのことは書けたかなと思います。大津サービスエリアについても書いておきたかったことはあるのですが、さほど大きなことではありません。いずれまた取り上げる機会もあるやもしれません。

　あるやに思ったのですが、「大津 サービスエリア」とTwilogで検索したところ奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)、告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)ともに該当はなしと出ました。

〈〈〈：Emacs： 2020-02-13（木曜日）20：33 　〈〈〈

