* 「Twitterやってない裁判官にツイッターワールドの空気感を言語化して伝えるのに苦労してる。」という深澤諭史弁護士のリツイートの先は、明示のないコインハイブ事件の逆転有罪判決
  CLOCK: [2020-02-08 土 11:31]--[2020-02-08 土 12:31] =>  1:00

〉〉〉：Emacs： 2020-02-08（土曜日）11：31　 〉〉〉

:CATEGORIES: コインハイブ事件,深澤諭史弁護士,逆転有罪判決,平野敬弁護士

fukazawas ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW fukazawas（深澤諭史） 日時：2020/02/08 11:15 URL： https://twitter.com/fukazawas/status/1225966329892466688
> あるあるある https://t.co/sSgk08l70y
▷▷▷　　　　　End　　　　　▷▷▷

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hKodama（HRK） 日時：2020-02-08 11:34／2020/02/08 07:19 URL： https://twitter.com/kk_hirono/status/1225971089794158592 https://twitter.com/hKodama/status/1225906836605267968
> Twitterやってない裁判官にツイッターワールドの空気感を言語化して伝えるのに苦労してる。 https://t.co/XMn1j0X4ol
▶▶▶　　　　　End　　　　　▶▶▶

TW fukazawas（深澤諭史） 日時： 2020-02-08 11:15 URL： https://twitter.com/fukazawas/status/1225966329892466688
> あるあるある https://t.co/sSgk08l70y

RT fukazawas（深澤諭史）｜hKodama（HRK） 日時：2020-02-08 11:15／2020-02-08 07:19 URL： https://twitter.com/fukazawas/status/1225966307809431552 https://twitter.com/hKodama/status/1225906836605267968
> Twitterやってない裁判官にツイッターワールドの空気感を言語化して伝えるのに苦労してる。 https://t.co/XMn1j0X4ol

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜idleness_venomy（venomy） 日時：2020-02-08 11:35／2020/02/07 23:45 URL： https://twitter.com/kk_hirono/status/1225971480288063488 https://twitter.com/idleness_venomy/status/1225792651955359749
> あの事件のポイントは、インターネットの知識が全くないおじいちゃんに、今のインターネットの現状がどうであるかを知らしめることだと思うんですよね。（そんなことは弁護人も百も承知だと思いますが。） https://t.co/SH4dJTJhBY
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kd_ixi（エンリケ航海玉子） 日時：2020-02-08 11:36／2020/02/07 23:37 URL： https://twitter.com/kk_hirono/status/1225971580255141889 https://twitter.com/kd_ixi/status/1225790765466451969
> 不正指令電磁的記録の範囲がゆるーくなると、まず、マイクロソフトやアップルがOSの裏で動かしてるいろんなアプリがアウトになりそうな。 望んでもいないポップアップ広告とかも、犯罪になるやろ。
▶▶▶　　　　　End　　　　　▶▶▶

　公式引用されたツイートを辿ると、行き着いたのはこれまでに何度か取り上げている、エンリケ航海玉子というアカウントでした。そのツイートに不正指令電磁的記録という用語があって、右クリックメニューからGoogleで検索を行ったところ、見つかったのが次の記事になります。

```
閲覧した人のパソコン（PC）端末の処理能力を無断で使って暗号資産（仮想通貨）を採掘（マイニング）するプログラムをウェブサイトに設置したとして、ウェブデザイナーの諸井聖也被告（32）が不正指令電磁的記録保管罪に問われた事件の控訴審判決が7日、東京高裁であった。栃木力裁判長は被告を無罪とした一審・横浜地裁判決を破棄し、罰金10万円の有罪とした。

諸井被告は「とても残念です」と話し、弁護人は上告する方針を明らかにした。

判決で栃木裁判長は、他人のPC端末の処理能力を使って仮想通貨をマイニングするプログラム「Coinhive（コインハイブ）」について「PCの機能が提供されていることを知る機会や実行を拒絶する機会も保障されていない」として、意図に反するものと指摘。また「（閲覧者に）一定の不利益を与えるプログラムと言えるうえ、生じる不利益に関する表示もされておらず、社会的に許容すべき点は見あたらない」とし、ウイルスに当たると認定した。

一審判決については「法律の解釈を誤ったことによる不合理なもの」としたうえで、被告の行為について「自己の利益のためプログラムに対する社会一般の信頼を害する犯行で悪質」と話した。

［source：］仮想通貨の無断「採掘」に逆転有罪　東京高裁　　：日本経済新聞 https://www.nikkei.com/article/DGXMZO55368280X00C20A2CE0000/
```

　この事件、この刑事裁判は「コインハイブ事件」と呼ばれ、記事の見出しにも使われることが多かったものですが、上記の日本経済新聞の記事の見出しには含まれておらず、見出しの文字数も少ないですが、これまでとは違った事件の印象を与えるものとも感じました。

　一審の無罪判決について、「▽採掘による消費電力の増加や処理速度の低下などの影響は軽微だった、といった理由から不正なウイルスとするには「合理的な疑いが残る」とし、被告に無罪判決を言い渡した。」と紹介がありますが、このCPUの使用率の点は、控訴審のことで触れられていないようです。

　このコインハイブ事件は、弁護士ドットコムの女性記者が専属的な取材を行い記事を出していました。この点は、これも２，３日前に逆転有罪判決が出たばかりの久留米支部の性犯罪事件とも共通していて、毎日新聞の女性記者が初めに記事を出し、一審の無罪判決が世論を喚起しました。

15：2019-12-30_22:49:51 ＊ コインハイブ事件の無罪判決にみる平野敬弁護士（第二東京弁護士会）の警察、検察批判のスタンス https://hirono-hideki.hatenadiary.jp/entry/2019/12/30/224945

　以前のエントリーになりますが、たぶんこの記事の中に弁護士ドットコムの記事のリンクがあるものと思います。記者は出口絢記者だったと思います。

　記事の冒頭に、前のエントリーの掲載がありました。そちらの方がコインハイブ事件の控訴審を取材した弁護士ドットコムの出口絢記者の記事の取り上げになるようです。

5788： 弁護士ドットコム編集部出口絢記者の記事　弁護人平野敬弁護士（第二東京弁護士会）：コインハイブ控訴審、検察官からの質問に「黙秘」貫く - 金沢市駅西本町所在市場急配センターにおける組織犯罪殺人未遂事件として再捜査の要請書／石川県警察珠洲警察署御中 http://hirono-hideki.hatenablog.com/entry/2019/11/30/172103

　なお、私が出口絢記者にこだわるのは、平野敬弁護士にまじかに接して何を感じ、何を伝えてくれるのかにあります。そのために記者の名前をあえて強調し、重要な記録に組み入れています。弁護士鉄道の現状と歴史についての分析と検証です。

　出口絢記者よりは名前を覚えるのが苦手な毎日新聞の女性記者ですが、そのツイートが上記の記事に埋め込まれていました。次のツイートになります。安部志帆子記者になります。性犯罪の刑事裁判で大きな光をあててくれたような記者であり、取材と記事がなかったら人知れず埋もれていたかもです。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜mai_shihoko（安部志帆子@毎日新聞） 日時：2020-02-08 12:04／2019/11/20 20:23 URL： https://twitter.com/kk_hirono/status/1225978687452876800 https://twitter.com/mai_shihoko/status/1197113238250352640
> ３月に福岡地裁久留米支部で無罪判決の出た準強姦事件の控訴審が始まりました。 被告は出廷しましたが、黙秘を続けました。 https://t.co/5UwjXzOFHC ＃毎日新聞 #ニュース
▶▶▶　　　　　End　　　　　▶▶▶

　「弁護士ドットコム編集部出口絢記者の記事　弁護人平野敬弁護士（第二東京弁護士会）：コインハイブ控訴審、検察官からの質問に「黙秘」貫く」という上記の記事ですが、タイトルに出口絢記者の名前があるものの、記事のリンクのあとは、ほとんどが安部志帆子記者のことで終わっていました。

```
●CPU使用率50%「負荷をかけたくないと思った」
被告人質問は、裁判官の質問から始まった。

＜男性はローカル環境でテストした上で、自身のサイトに設置するコインハイブをCPU使用率50%の設定にしていた＞

裁判官からテストした理由を問われると、「見ている方に不快感を与えないことが重要だった。負荷をかけたくないと思った」と言い、CPU使用率50%では、パソコンの動作が重くなったり、ファンがうるさくなったりするなどの変化がほぼなく、「ユーザーに不利益を与える設定ではないと思った」と話した。

［source：］コインハイブ控訴審、検察官からの質問に「黙秘」貫く　判決は2月7日 - 弁護士ドットコム https://www.bengo4.com/c_1009/n_10461/
```

　探し物が見つかったのと同時に驚いたのですが、記事には「●CPU使用率50%「負荷をかけたくないと思った」」という部分が小見出しで強調表示されていました。やはりCPUの使用率が５０％だったのだと確認したことになります。正直な受け答えになるのだと思いますが、これが無罪の主張とは。

　前にはNHKニュースNEWS９のテレビ画面を撮影した写真も交えて取り上げたような気もするのですが、無罪判決となった被告人は平野敬弁護士とともに顔出しでインタビューをしていました。気になったのはそこに平野敬弁護士の名前が出ていなかったことです。

　高性能なCPUならば５０％の使用率を無断で使われても通常のパソコンの使用であれば影響は出ないかもしれないですが、安価なコア数も少ないCPUであれば影響はでそうです。高性能なCPUというのもその用途によっては必要条件となるはずです。仕事に支障を起こす危険も考えられます。

　昨年の９月頃になりますか、ある人から相談を受けて囲碁ソフトのコンパイルを行ったのですが、最終的にCPUを補助する高性能グラフィックボードのGPUの問題にぶつかりました。問題にぶつかって調べていると、GPUがフル稼働になると目玉焼きが焼けるほどパソコンの温度が上がるとのことです。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-02-08 12:31／2020/02/08 12:11 URL： https://twitter.com/kk_hirono/status/1225985422712438784 https://twitter.com/s_hirono/status/1225980411563532288
> 2020-02-08-121032_コインハイブ控訴審、検察官からの質問に「黙秘」貫く　判決は2月7日　-　弁護士ドットコム.jpg https://t.co/g6zT7YdqKw
▶▶▶　　　　　End　　　　　▶▶▶

〈〈〈：Emacs： 2020-02-08（土曜日）12：31 　〈〈〈


