* 「弁護士の押収拒絶権とかをなんか弁護士の特権とか思ってる人いるけどそれ全然違うから。秘密ばらまけというならばらまく方が楽ですよ。守秘義務負うって大変なのよ。」という趙誠峰弁護士のツイート
  CLOCK: [2020-02-01 土 09:19]--[2020-02-01 土 09:32] =>  0:13

〉〉〉：Emacs： 2020-02-01（土曜日）09：19　 〉〉〉

:CATEGORIES: 趙誠峰弁護士,三浦義隆弁護士,守秘義務,押収拒絶権,弁護士

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜cho_seiho（CHO Seiho／趙誠峰） 日時：2020-02-01 09:23／2020/01/31 22:44 URL： https://twitter.com/kk_hirono/status/1223401355672313856 https://twitter.com/cho_seiho/status/1223240597667893249
> 弁護士の押収拒絶権とかをなんか弁護士の特権とか思ってる人いるけどそれ全然違うから。秘密ばらまけというならばらまく方が楽ですよ。守秘義務負うって大変なのよ。 弁護士と依頼者のコミュニケーションの秘密とかって、弁護士の権利じゃないから。 ちなみに検察もこのこと全く理解してない。
▶▶▶　　　　　End　　　　　▶▶▶

　三浦義隆弁護士のタイムラインで、リツイートを見かけた趙誠峰弁護士のツイートになります。テレビのウェークアップぷらす、が終わったところですが、エンディングロールが出る直前に、福島県警の７人乗りのヘリが墜落したという速報がありました。

RT lawkus（ystk）｜cho_seiho（CHO Seiho／趙誠峰） 日時：2020-02-01 07:30／2020-01-31 22:44 URL： https://twitter.com/lawkus/status/1223373051321913345 https://twitter.com/cho_seiho/status/1223240597667893249
> 弁護士の押収拒絶権とかをなんか弁護士の特権とか思ってる人いるけどそれ全然違うから。秘密ばらまけというならばらまく方が楽ですよ。守秘義務負うって大変なのよ。 \n 弁護士と依頼者のコミュニケーションの秘密とかって、弁護士の権利じゃないから。 \n ちなみに検察もこのこと全く理解してない。

　同じ弘中惇一郎弁護士の事務所への東京地検の家宅捜査の問題ですが、昨夜は、東京弁護士会と日弁連（日本弁護士連合会）が会長声明を出していました。声明を出すべきという法クラのツイートはいくつか見かけていましたが、出た後の反応というのは今のところ乏しい感じです。

　弘中惇一郎弁護士が犯罪に加担したのであれば、いずれ逮捕という事態もありそうです。東京地検もその方向で捜査を進めているのかもしれず、そうなれば、弁護士の押収拒絶権も守秘義務も吹き飛ぶ、文字通りの強制捜査となるのでしょう。

〈〈〈：Emacs： 2020-02-01（土曜日）09：32 　〈〈〈

* 「「裁判所は死因に関心がない」と忌避～特養入居者の死亡の事件で証人尋問を認めず結審・東京高裁（江川紹子）」という記事で繋がった、一審無罪で検察控訴中の「乳腺外科医のわいせつ事件」
  CLOCK: [2020-02-01 土 09:44]--[2020-02-01 土 11:06] =>  1:22

〉〉〉：Emacs： 2020-02-01（土曜日）09：44　 〉〉〉

:CATEGORIES: 乳腺外科医のわいせつ事件,ジャーナリストの江川紹子氏,趙誠峰弁護士,医療問題,大崎事件,湖東記念病院事件,東京高裁,恵庭OL殺害事件,大野病院事件,モトケンこと矢部善朗弁護士（京都弁護士会）

```
長野県安曇野市の特別養護老人ホームで2013年に入居者K子さん（当時85）が、おやつのドーナツを食べた直後に意識不明となり、約一ヶ月後に死亡した事故を巡って、業務上過失致死に問われ、一審で罰金20万円の有罪判決を受けた山口けさえ・准看護師の控訴審初公判が30日、東京高裁（大熊一之裁判長）で開かれ、即日結審した。裁判所は、弁護側の証人申請を1人も認めず、証拠も1点を除いて採用しなかったことから、弁護人は大熊裁判長らの忌避を申し立てるなど、法廷では激しい攻防が展開された。

［source：］「裁判所は死因に関心がない」と忌避～特養入居者の死亡の事件で証人尋問を認めず結審・東京高裁(江川紹子) - 個人 - Yahoo!ニュース https://news.yahoo.co.jp/byline/egawashoko/20200130-00161102/
```

　一昨日の夜に読んでいたのかと思いますが、ジャーナリストの江川紹子氏の記事は１月３０日２３時３６分となっています。本人のタイムラインのツイートで見かけたものですが、刑事裁判に関する記事は久しぶりに見かけたと思いました。

　私の勘違いかもしれませんが、前回に見かけた時は大熊裁判長の顔写真があったような気もします。昨年の１２月の上旬になるのでしょうか、６人を殺害したペール人の事件の控訴審で、裁判員裁判の死刑判決を取り消し、心神耗弱を理由に無期懲役とした東京高裁の裁判長になります。

　ネットではけっこう批判が出ていたようです。この昨年１２月の前半は、新潟西区の女児殺害事件、東海道新幹線内の無差別殺傷事件の判決があって、適用されなかった死刑判決に対する批判が集中した時期でもあり、３月の４件の性犯罪無罪判決と裁判不信の反応が沸き起こっていました。

```
弁護側はその後、K子さんが亡くなった直後の脳CT画像などを元に、画像診断、救急医療、脳神経外科の各専門医の意見を求めたところ、いずれも心肺停止の原因は脳梗塞との判断だった。弁護側はこの3人を含めて7人の証人尋問を行うよう求めたが、大熊裁判長はいずれの請求も却下。カルテなど16点の証拠請求も、採用したのは、K子さんが老人ホームに入所する直前の健康診断を行った医師への照会のみだった。

　弁護人は「1審を含め6人の医師のうち、5人が脳梗塞と言っている。窒息であれば生じるはずの、脳の浮腫も見られない。（裁判官などの）法律家は医学の専門家ではない。冤罪を生まないために、専門家の意見には真摯に耳を傾けなければならない。それを怠るのは傲慢だ」などと訴え、異議を申し立て。看護助手の女性が呼吸器を外して患者を殺したとして有罪が確定したが、病死とする鑑定などが認められて再審開始が決まった湖東病院事件などの例を挙げて、慎重に事実を解明するよう求めたが、裁判所は却下。判断は変わらなかった。

［source：］「裁判所は死因に関心がない」と忌避～特養入居者の死亡の事件で証人尋問を認めず結審・東京高裁(江川紹子) - 個人 - Yahoo!ニュース https://news.yahoo.co.jp/byline/egawashoko/20200130-00161102/
```

　前回読んでいた時は気が付かなかったようですが、再審となった湖東記念病院事件を関連付けたのは、執筆者のジャーナリストの江川紹子氏ではなく、この特別養護老人ホームの刑事裁判の弁護人のようです。上記に引用をしましたが「湖東病院事件などの例を挙げて」とあります。

　この記事には２人の弁護士の名前が出てきたと思います。まだそこまで読む進めておらず、その弁護士の名前も思い出せないのですが、初めて見るような弁護士の名前だったということもあり、すぐに調べていました。

　たぶん２件目だったと思うのですが、検索にヒットしたのが乳腺外科医のわいせつ事件で、それもジャーナリストの江川紹子氏の記事でした。同じ事件についてジャーナリストの江川紹子氏の記事は３，４件ほど読んでいたのですが、初めて被疑者の医師の実名記載を見たものと思います。

　正確なことは調べる必要があり、時間も掛かるのでそこまではしたくないのですが、一審で無罪判決が出ているのに医師の実名が伏せられ不思議に思っていました。病院名も同じになるものと思います。

```
その集会で、主任弁護人の藤井篤弁護士は、「打ち合わせの席でも、裁判長は医学鑑定については聞く耳を持たず、全く関心を示さなかった」と述べ、大熊裁判長らの姿勢を批判した。

　上野格弁護士も「検察は、このCT画像から脳梗塞と判断するのは疑わしい、窒息でもこの画像のような状態になりうるんだと言いたいのだろうが、ならば証人尋問で直接それを問いただせばいい。裁判所も証人尋問をやってから、判断すべきだ」と検察・裁判所の対応に異議を唱えた。

［source：］「裁判所は死因に関心がない」と忌避～特養入居者の死亡の事件で証人尋問を認めず結審・東京高裁(江川紹子) - 個人 - Yahoo!ニュース https://news.yahoo.co.jp/byline/egawashoko/20200130-00161102/
```

　上記の引用部分に、藤井篤弁護士と上野格弁護士の名前があります。今見ても初めて見るような名前ですが、「格」という名前はなんと読むのかと考えていたことを思い出しました。検索では括弧書きで情報がありましたが、その前には「わたる」と見たような気がしていました。

　事故死を警察が事件として扱ったという批判は、他に大崎事件がありますが、この特別養護老人ホームの事件のように具体的な死因の主張が弁護団には余りみかけませんでした。致命傷となった可能性のある怪我をしたまま家に届けられ放置された、というところまでです。

　間違って配食されたというドーナッツを食べ死亡したというこの事件は、数年前にテレビのニュースで見かけていた記憶があり、また、この控訴審のこともたぶん同じ夜に、テレビのニュースで１つか２つ見ていました。

　弁護士の死因に対する強いこだわり、主張は、大崎事件の他に、恵庭OL殺害事件事件、名古屋刑務所の放水事故死の事件がとりわけ大掛かりで印象的なものでした。名古屋の件は検察の方で逮捕前に生きたブタを使った実験をしていたようです。

　確認するには至らず、YouTubeの動画でみたとも思うのですが、刑務官の弁護をした北口雅章弁護士は、麻酔を掛けたブタでは無意味でやるならそのまま、という趣旨の発言をしていたと私は理解し衝撃も受けていました。

　恵庭OL殺害事件の方は、ブタを使った燃焼実験で、これは裁判所に採用されず弁護団が自ら行った実験とされていましたが、その夜、改めて調べたところ以前には見かけなかった情報を見かけ、そこには毛を剥いだブタを肉屋から調達してきたような話でした。

　このときも肉屋といえば、深澤諭史弁護士を思い出していたのですが「肉屋を支持するブタ」というのが深澤諭史弁護士のお気に入りの言葉で納得性が高いようです。

　ドーナッツを喉に詰まらせ窒息死したとする検察の立証を、弁護士らは死因は脳梗塞なので無罪と主張しているようです。一審で有罪判決が出ていますが罰金２０万円とのことで、罪名も業務上過失致死となっていたと思います。

　死因の因果関係が問題になっているようには読めなかったのですが、ジャーナリストの江川紹子氏は「介護の未来がかかった裁判、と」という小見出しをつけ、「閉廷後に開かれた報告集会には約450人が参加した。」と紹介し、締めくくりは「川島みどり・日本赤十字看護大学名誉教授」のお言葉。

　弁護士らの広報として存分の活躍をされたとも見える記事ですが、インチキ商法の片棒を担いでいるように思えてなりません。もっともこのような弁護士の活動の実態を知らせてくれたのは、ありがたいことで、見ることのできなかった弁護士世界の一面です。

　もっとも弁護士らにすれば、検察が起訴すべきではなかったという批判もあるのでしょう。それを強く感じさせてくれたのが大野病院事件にこだわり続けたモトケンこと矢部善朗弁護士（京都弁護士会）の主張でした。

　大野病院事件は背景事情や医療現場の問題が複雑でしたが、この長野県安曇野市の特別養護老人ホームの問題は、過失と死因が明白でわかりやすいという印象を受けました。

　ドーナッツを喉に詰まらせ窒息しそうになったことが脳梗塞を発症させた、という検察の素因変更があり、立証ができれば、弁護士らも納得するのかもしれないですが、普通そこまでこだわる裁判は少ないでしょうし、罰金２０万円に相当する業務上過失致死の評価とは違う気がします。

```
裁判を傍聴した川島みどり・日本赤十字看護大学名誉教授は、「これは、事故を起こさないようにがんばっている介護の現場で起きた（利用者の）急変だ。急変は予期できない。高齢者のお世話にはこういうことが起きうる。ゼリーなら安全というのも、検察の思い込みに過ぎない。私は88歳だが、これから介護して下さる方のためにも、介護の未来を明るくするためにも、これはおかしいと言い続けていきたい」と語った。

　山口さんも「無罪を勝ち取るまであきらめません」などと訴えた。

　判決期日は未定。

［source：］「裁判所は死因に関心がない」と忌避～特養入居者の死亡の事件で証人尋問を認めず結審・東京高裁(江川紹子) - 個人 - Yahoo!ニュース https://news.yahoo.co.jp/byline/egawashoko/20200130-00161102/
```

　「裁判を傍聴した川島みどり・日本赤十字看護大学名誉教授は、「これは、事故を起こさないようにがんばっている介護の現場で起きた（利用者の）急変だ。急変は予期できない。」とジャーナリストの江川紹子氏は紹介しています。

　ちょうど今、大きなニュースとなっている武漢のコロナウイルスの感染問題でも、基礎疾患というような言葉をテレビでしりました。ちょっと違っていたような気がしますが基礎の部分は合っているはずです。それを踏まえての安全配慮が過失の認定になっている気がします。

　いろいろとしがらみについても考えさせられる弁護士らによる弁護士のための刑事裁判です。まきぞいにされる医療現場にも心配と不安があります。以上。

〈〈〈：Emacs： 2020-02-01（土曜日）11：06 　〈〈〈

