* 「森まさこ先生は、あの発言をヤバいと感得できて、謝罪の上（謝罪の方便は毀誉褒貶あるかもしらんが）撤回できるだけ、アレやコレやの法クラより、」という深澤諭史弁護士のリツイート
  CLOCK: [2020-01-10 金 11:53]--[2020-01-10 金 12:19] =>  0:26

〉〉〉：Emacs： 2020-01-10（金曜日）11：53　 〉〉〉

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-01-10 12:01／2020/01/10 03:20 URL： https://twitter.com/kk_hirono/status/1215468668693303296 https://twitter.com/s_hirono/status/1215337631132704768
> 2020-01-10-030009_深澤諭史さんがリツイートリーチ一発ツモ裏１@luckymangan·7時間森まさこ先生は、あの発言をヤバいと感得できて、謝罪の上（謝罪の方便は毀誉褒貶ある.jpg https://t.co/IFf4jrdnPP
▶▶▶　　　　　End　　　　　▶▶▶

luckymangan ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW luckymangan（リーチ一発ツモ裏１） 日時：2020/01/09 19:23 URL： https://twitter.com/luckymangan/status/1215217454089007106
> 森まさこ先生は、あの発言をヤバいと感得できて、謝罪の上（謝罪の方便は毀誉褒貶あるかもしらんが）撤回できるだけ、アレやコレやの法クラより、よっぽどマシだと思いますよ。俺がブロックされたり、しているアカウントらと比べるのが失礼なくらい。
▷▷▷　　　　　End　　　　　▷▷▷

RT fukazawas（深澤諭史）｜luckymangan（リーチ一発ツモ裏１） 日時：2020-01-09 19:27／2020-01-09 19:23 URL： https://twitter.com/fukazawas/status/1215218649960570880 https://twitter.com/luckymangan/status/1215217454089007106
> 森まさこ先生は、あの発言をヤバいと感得できて、謝罪の上（謝罪の方便は毀誉褒貶あるかもしらんが）撤回できるだけ、アレやコレやの法クラより、よっぽどマシだと思いますよ。俺がブロックされたり、しているアカウントらと比べるのが失礼なくらい。

　この深澤諭史弁護士のタイムラインでの深澤諭史弁護士のリツイートをみたのが、法クラが森まさこ法務大臣の発言を批判した問題を知った最初だったかもしれません。その前にも少し見かけていたような気もするのですが、この辺りをきっかけに調べて問題の確認をしました。

　スクリーンショットの記録は本日未明の３時００分となっています。その後、森まさこ法務大臣についていろいろと調べたのですが、まったく知らなかったことばかりでした。もともと法務大臣に就任する前は、名前も顔も全く知らなかった政治家だと思います。

　調べながらメモと記録をかねたツイートを行っています。まとめ記事を作成しました。「2020-01-08_0924〜2020-01-10_1158／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2020年01月10日12時14分」という範囲なので十分射程内です。

[link:] 2020年01月10日12時14分の登録： ＃奉納＼さらば弁護士鉄道・泥棒神社の物語　@hirono_hideki＃のツイート／2020-01-08_0924〜2020-01-10_1158／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2020年01月10日12時14分 http://hirono2014sk.blogspot.com/2020/01/hironohideki2020-01-0809242020-01.html

〈〈〈：Emacs： 2020-01-10（金曜日）12：19 　〈〈〈

* 「「無罪を証明すべき」とツイートしましたよね。その後、そのツイートを消してますよね。」などと森まさこ法務大臣を詰り畳み掛ける深澤諭史弁護士のリツイート
  CLOCK: [2020-01-10 金 12:24]--[2020-01-10 金 12:57] =>  0:33

〉〉〉：Emacs： 2020-01-10（金曜日）12：24　 〉〉〉

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜TGN54（TｰTAKA） 日時：2020-01-10 12:24／2020/01/09 17:07 URL： https://twitter.com/kk_hirono/status/1215474574290083840 https://twitter.com/TGN54/status/1215183387524136960
> 「無罪を証明すべき」とツイートしましたよね。 その後、そのツイートを消してますよね。 そのツイートを消したことについては特に言及されていませんね。 https://t.co/DcGtf8FCa8
▶▶▶　　　　　End　　　　　▶▶▶

　深澤諭史弁護士のリツイートのURLを取得するため自作のコマンドを実行したのですが、思わぬ結果で芋づる式のようなツイートが出てきました。以下に列挙します。

```
% tu fukazawas 200|grep -B 1 無罪を証明
RT fukazawas（深澤諭史）｜TGN54（TｰTAKA） 日時：2020-01-09 17:48／2020-01-09 17:07 URL： https://twitter.com/fukazawas/status/1215193638482759685 https://twitter.com/TGN54/status/1215183387524136960
> 「無罪を証明すべき」とツイートしましたよね。 \n その後、そのツイートを消してますよね。 \n そのツイートを消したことについては特に言及されていませんね。 https://t.co/DcGtf8FCa8
--
RT fukazawas（深澤諭史）｜ekinan_lawyer（えきなんローヤー🕊1215168026972024832 https://twitter.com/ekinan_lawyer/status/1215167660054347776
> 「無罪を証明」、法クラ流行語大賞狙えるわ。 \n  \n だって、司法試験受かってて修習も終了してる法務大臣のパワーワードだもん。ジワる。
--
RT fukazawas（深澤諭史）｜matimura（田丁木寸） 日時：2020-01-09 16:00／2020-01-09 14:25 URL： https://twitter.com/fukazawas/status/1215166560748204032 https://twitter.com/matimura/status/1215142637109334017
> しかしまあ、ゴーン事件に関しては、裁判所の保釈がけしからんと言っちゃう偉い人とか、正々堂々裁判所で己の無罪を証明しろと言っちゃう偉い人とか、色々出ているわけだが、一般の多くは何が問題かわからず、弁護士さんが何を騒いでいて撤回だのこっそり修正だのになっているかも不明なのが現状か。
--
RT fukazawas（深澤諭史）｜Japanese_Joke（日本人ジョーク(bot)） 日時：2020-01-09 15:43／2020-01-09 15:41 URL： https://twitter.com/fukazawas/status/1215162259653066753 https://twitter.com/Japanese_Joke/status/1215161552547897344
> 2020年1月9日の森雅子法相が「潔白だと言うのなら、司法の場で正々堂々と無罪を証明すべき」と言った。すると時空の歪みで2016年2月3日の安倍首相が現れ、「ないという事をないと証明するのは悪魔の証明だ。（略）あるという事を主張してる側に立証責任がある。当たり前だ」と怒鳴った。
--
RT fukazawas（深澤諭史）｜ppsh41_1945（大神ひろし） 日時：2020-01-09 14:57／2020-01-09 14:30 URL： https://twitter.com/fukazawas/status/1215150489118990337 https://twitter.com/ppsh41_1945/status/1215143807114571776
> 「ゴーン被告人は無罪を証明してみろ」なんて台詞が、まさか法務大臣ともあろう人物の口から出るとは思わなかった。 \n  \n 検察官が被告人の犯罪を証明しなければ有罪とすることが出来ない「推定無罪の原則」すら知らない人物が法務大臣になる日本って… https://t.co/uu6STiLpLs
--
RT fukazawas（深澤諭史）｜nagonagu（宮城 康博） 日時：2020-01-09 14:57／2020-01-09 14:11 URL： https://twitter.com/fukazawas/status/1215150479178493952 https://twitter.com/nagonagu/status/1215139084705812480
> 森まさこ法務大臣がYouTubeにあげた動画を根拠に「無罪を証明すべきだ」とは言ってないという指摘があるが。ニュースの動画にはっきり記録されている。森大臣はその部分を割愛した動画を公開している。かなり意識的にだろうね。https://t.co/UnEIi0ETXH
--
RT fukazawas（深澤諭史）｜ikemen_lawyer（イケメン弁護士(絶対減量するマン-8.9kg)） 日時：2020-01-09 14:42／2020-01-09 14:13 URL： https://twitter.com/fukazawas/status/1215146726836719621 https://twitter.com/ikemen_lawyer/status/1215139566572560386
> 『無罪を証明』は2020年の当職的流行語大賞エントリーNo.1ですね
```

　この項目でメインで取り上げた「TｰTAKA」というプロフィールの名前のTwitterアカウントのツイートは、とりわけ印象的なものの１つでしたが、すっかり忘れていました。念の為の確認と思いタイムラインを下にスクロールしたところで目に入りました。

　「無罪の主張」を「無罪の証明」と言い間違えたことを、深澤諭史弁護士のリツイートにある法クラ（法クラ以外のリツイートも含まれている可能性あり）は、欣喜雀躍とあげつらい、悦に入っているようです。

　刑事裁判における「推定無罪」を絶対的価値として印象づけるのが狙いにもみえます。法律の専門家としての絶対的な自信も、昨夜述べたところの「弁護士鉄道のパスポート」として絶対的価値を基礎づけているようです。

　森まさこ法務大臣の発言は、ツイートと公開された声明文を混同しているところがあるかもしれませんが（ツイートは削除された模様で確認できない）、日本の司法制度をないがしろにする国外逃亡したカルロス・ゴーン氏に、直接、呼びかけをしているような体裁を感じています。

　説得という言い方もできますが、要するに日本に戻って日本の刑事裁判を受け、不服や間違いがあるのならその裁判でやるべき、ということと私は理解しました。そこで「無罪の主張」というのは誰でも簡単にできることで、そのほとんどは主張が認められることなく有罪判決になっているはずです。

　「無罪の証明」を裁判の結果として裁判所に認めさせ思い通りの無罪判決を得るのは、日本の刑事裁判を受けた結果であって、森まさこ法務大臣が言おうとした全体的な趣旨は、「無罪を証明するべく根拠を示せ」ということなのではないかと考えました。その点で法クラの指摘は揚げ足取りです。

〈〈〈：Emacs： 2020-01-10（金曜日）12：57 　〈〈〈

