* 「法律家が法務大臣になって期待されることって、首相の意を汲み法をねじ曲げることなのかね。よく続けられるよね。」という森まさこ法務大臣@morimasakosangiに向けた秋重実弁護士のツイート
  CLOCK: [2020-02-11 火 09:54]--[2020-02-11 火 10:34] =>  0:40

〉〉〉：Emacs： 2020-02-11（火曜日）09：54　 〉〉〉

:CATEGORIES: 森まさこ法務大臣,秋重実弁護士,安倍政権,法律家

akishigemakoto ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW akishigemakoto（MakotoAkishige（civilista）） 日時：2020/02/10 22:55 URL： https://twitter.com/akishigemakoto/status/1226867352077099009
> 法律家が法務大臣になって期待されることって、首相の意を汲み法をねじ曲げることなのかね。よく続けられるよね。 https://t.co/rGiah416XO
▷▷▷　　　　　End　　　　　▷▷▷

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜morimasakosangi（森まさこ MORI Masako） 日時：2020-02-11 09:56／2020/02/10 20:51 URL： https://twitter.com/kk_hirono/status/1227033618083504128 https://twitter.com/morimasakosangi/status/1226836126914109440
> 本日も衆議院予算委員会にて答弁しました。 https://t.co/oszuMAQYLT
▶▶▶　　　　　End　　　　　▶▶▶

　昨夜だったと思いますが、国会での質疑の場面に久しぶりに姿を見た山尾志桜里衆院議員が質問をする様子で、そのあとに森まさこ法務大臣が答弁をするような様子がありました。質疑の内容は聞いていなかったですが、高検検事長の定年延長の問題のようでした。

　安倍政権が検察を支配、コントロールするための画策という主張はネットで見かけていましたし、これも言い出しっぺは郷原信郎弁護士のように思っています。そこまで都合の良い懐刀であれば、定年になる前に検事総長にしておけばよさそうなものですが、妄想じみた邪推が突っ走って見えます。

　前年度、京都弁護士会の副会長だった秋重実弁護士ですが、同じTwitterのタイムラインでは、同じ安倍政権批判の問題に絡んで次のツイートもリツイートしています。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜sato__michiko（佐藤倫子） 日時：2020-02-11 10:09／2020/02/10 21:19 URL： https://twitter.com/kk_hirono/status/1227036940941160449 https://twitter.com/sato__michiko/status/1226843076716482560
> 黒川検事長の件、山尾さんの質問に対する森法務大臣の答弁が酷すぎて、見ていて悲しくなる。森さんは分かっているはず。安倍政権に入ったりこれを支える官僚になると、いくら理不尽と分かっていても全てに目をつぶってシュールな答弁をし続けなければならないのか。そんなの、もうやめたらいいのに。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜buu34（buu） 日時：2020-02-11 10:09／2020/02/10 22:33 URL： https://twitter.com/kk_hirono/status/1227036860406329344 https://twitter.com/buu34/status/1226861653766983680
> 衆予算委　検察官定年延長問題 山尾「昭和56年9月28日　衆議院内閣委員会、これは当時、民社党の神田厚さんと言う議員が、こういう風に聞いています。『定年制の導入は当然指定職にある職員にも適用されることになるのかどうか。たとえば一般… https://t.co/GKNKRfcNaa
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜miyamototooru（宮本徹） 日時：2020-02-11 10:09／2020/02/10 21:08 URL： https://twitter.com/kk_hirono/status/1227036797152030720 https://twitter.com/miyamototooru/status/1226840476847759361
> 山尾さん、よく過去の政府答弁を調べて追及しました。政府はもともと検事には国家公務員法の定年は適用外だと答弁してきました。森法務大臣は過去の政府答弁を知らないと答弁しましたが、理屈もなく国会での政府見解を変えるなどありえない。 https://t.co/mEYg5dCKEY
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜akasakaromantei（君に届け!滑稽新聞@無糖派） 日時：2020-02-11 10:08／2020/02/10 13:27 URL： https://twitter.com/kk_hirono/status/1227036743880200192 https://twitter.com/akasakaromantei/status/1226724357621202946
> これでもまだ自民党を選びますか？  https://t.co/NZQbugCXbV
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Dgoutokuji（立川談四楼） 日時：2020-02-11 10:08／2020/02/10 13:00 URL： https://twitter.com/kk_hirono/status/1227036710288052226 https://twitter.com/Dgoutokuji/status/1226717653487636481
> 野党議員の名をゆっくり呼ぶ。安倍さんや閣僚の答弁を求めても官僚を指名するなど、棚橋泰文予算委員長の進行は野党の時間潰しに熱心で、公平公正は何処へやら、自民党命が明らさまだ。過激な言葉を慎む立民の枝野幸男代表さえ「首相に尻尾を振っているポチ」と言うほど。ぜひ国会中継を見るがよろし。
▶▶▶　　　　　End　　　　　▶▶▶

YusukeTaira ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW YusukeTaira（平　裕介） 日時：2020/02/10 22:01 URL： https://twitter.com/YusukeTaira/status/1226853781364559873
> おそらく政府答弁なんて簡単に変えちゃうんですよ。遅くとも解釈改憲したときからもう何でもアリになったのでしょう。多くの国民が立憲主義･法治主義を守ることを重視しなくなってきているので違憲違法行政やり放題ですね \n  \n 検察官は定年延長「適… https://t.co/HVG6lVsYuL
▷▷▷　　　　　End　　　　　▷▷▷

RT akishigemakoto（MakotoAkishige（civilista））｜YusukeTaira（平　裕介） 日時：2020-02-10 23:15／2020-02-10 22:01 URL： https://twitter.com/akishigemakoto/status/1226872343458275330 https://twitter.com/YusukeTaira/status/1226853781364559873
> おそらく政府答弁なんて簡単に変えちゃうんですよ。遅くとも解釈改憲したときからもう何でもアリになったのでしょう。多くの国民が立憲主義･法治主義を守ることを重視しなくなってきているので違憲違法行政やり放題ですね \n  \n 検察官は定年延長「適… https://t.co/HVG6lVsYuL

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜lasar141（ラサール石井） 日時：2020-02-11 10:13／2020/02/09 21:53 URL： https://twitter.com/kk_hirono/status/1227038015601532928 https://twitter.com/lasar141/status/1226489270325530625
> 無能。ウソつきの上に無能なんだよ。過去最高に無能。 https://t.co/z15nKieMhz
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜ggzhmru2（ryota） 日時：2020-02-11 10:13／2020/02/10 17:27 URL： https://twitter.com/kk_hirono/status/1227037847154114560 https://twitter.com/ggzhmru2/status/1226784748137148418
> 黒川検事長定年延長問題。山尾・森の元法曹対決。出来が違うね、圧倒的に山尾の勝ち。やっぱり延長は違法だった。昭和56年国家公務員定年制導入論議。政府委員は「検察官は今回の定年制は適用されない」山尾はしっかり勉強してるね。森法相はこの… https://t.co/zReYwp7Qcm
▶▶▶　　　　　End　　　　　▶▶▶

　黒川検事長定年延長問題、とありますが、この問題を最初に見た頃に、一般の検事と検事総長が定年が違って、安倍政権が黒川検事長を検事総長にする目的で定年を延長させたという話になっていました。黒川検事が安倍政権に与えた恩恵というのも見かけましたが、割と古く情報だったような。

akishigemakoto ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW akishigemakoto（MakotoAkishige（civilista）） 日時：2020/02/10 23:54 URL： https://twitter.com/akishigemakoto/status/1226882182699835394
> もう安倍首相がロシアに献上して南クリル諸島になってしまったのだが。まだこの人物についていくのね。 https://t.co/VkTVCcJ7Nt
▷▷▷　　　　　End　　　　　▷▷▷

　上記の秋重実弁護士のツイートは、次のツイートを公式引用したものです。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hoppou_erika（北方領土エリカちゃん） 日時：2020-02-11 10:19／2020/02/10 17:18 URL： https://twitter.com/kk_hirono/status/1227039298836258816 https://twitter.com/hoppou_erika/status/1226782460995764224
> 2月7日の「北方領土の日」に国立劇場で 令和２年北方領土返還要求全国大会が開催されたッピ。  安倍総理は、交渉を一歩一歩着実に前進させていくと挨拶されたッピ！ エリカもみんなと一緒に北方領土返還要求運動に取組み、 啓発活動を盛り上… https://t.co/8pqzuo2Sra
▶▶▶　　　　　End　　　　　▶▶▶

```
(南クリル諸島 から転送)

出典： フリー百科事典『ウィキペディア（Wikipedia）』 (2019/08/20 05：43 UTC 版)

北方領土（ほっぽうりょうど）、北方四島（ほっぽうよんとう）

［source：］南クリル諸島とは - Weblio辞書 https://www.weblio.jp/content/%E5%8D%97%E3%82%AF%E3%83%AA%E3%83%AB%E8%AB%B8%E5%B3%B6
```

　公式引用したツイートにはなかった秋重実弁護士のツイートにある「南クリル諸島」ですが、ウクライナの辺りの大きな湖に島があるのかと思って調べたところ北方領土のことでした。安倍政権のはるか前に時代に北方領土問題はありましたが、秋重実弁護士はそれも全ておっかぶせているようです。

　安倍政権の時代になって、ロシアが北方領土に南クリル諸島という名称をつけたのかと考えましたが、安倍政権がロシアとの交渉失敗でそうなったと言いたいのでしょう。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜RyuichiYoneyama（米山　隆一） 日時：2020-02-11 10:26／2020/02/11 08:01 URL： https://twitter.com/kk_hirono/status/1227041220129521664 https://twitter.com/RyuichiYoneyama/status/1227004719521882112
> まあ悪くないと思います。ところでこれ、自民党がぼろくそに否定した「子ども手当」そのものです。つまり７年前にこれをやっていれば、日本の少子化はここまで酷い事にならなかったという事です。 https://t.co/8py8PinVVc
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜_7479989014082（藤花） 日時：2020-02-11 10:27／2020/02/09 15:40 URL： https://twitter.com/kk_hirono/status/1227041336492118017 https://twitter.com/_7479989014082/status/1226395437948530688
> 100万円までの賄賂は無罪放免、 さすが腐敗政治の国。 https://t.co/RPtBM78Lbh
▶▶▶　　　　　End　　　　　▶▶▶

akishigemakoto ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW akishigemakoto（MakotoAkishige（civilista）） 日時：2020/02/11 09:31 URL： https://twitter.com/akishigemakoto/status/1227027320826818560
> どいつもこいつも逃げまくり https://t.co/W7Ha5VR9Q8
▷▷▷　　　　　End　　　　　▷▷▷

　上記の秋重実弁護士の「どいつもこいつも逃げまく」というツイートも次のツイートを公式引用したものです。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Lanikaikailua（ラナンキュラス（SHINJI KAWAKAMI）） 日時：2020-02-11 10:28／2020/02/10 21:49 URL： https://twitter.com/kk_hirono/status/1227041704902975489 https://twitter.com/Lanikaikailua/status/1226850784836349952
> #北海道新聞 #金子記者 長官は「内閣府に尋ねてほしい」というが、内閣府から何日も回答がなく、内容も突っ込んで説明を求めると、答えられないなど説明能力がない  資料を巡る官房長の隠蔽、虚偽答弁の疑惑について、内閣府の事務方は限界… https://t.co/9UmyUwW9Dp
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜wanpakuten（但馬問屋） 日時：2020-02-11 10:29／2020/02/10 23:37 URL： https://twitter.com/kk_hirono/status/1227041985598382080 https://twitter.com/wanpakuten/status/1226877903981277185
> “国会がまた紛糾、北村大臣の不安定答弁”  山井議員 「新たな文書を作った際には、『いつ誰の責任で変えましたと明記しなさい』と、公文書管理のガイドラインに書いてある」  北村大臣 「来年度より保存する。今までのところはご容赦賜りた… https://t.co/EaewMMmCv2
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜tanutinn（冨永 格（たぬちん）） 日時：2020-02-11 10:30／2020/02/11 08:47 URL： https://twitter.com/kk_hirono/status/1227042102170669057 https://twitter.com/tanutinn/status/1227016244680777728
> クルーズ船をめぐる政権の対応について、玉川徹さん「あまりにも後手後手すぎて、単なる能力の問題というより別の意図を疑ってしまう。政府がもたもたしなくていいように緊急事態条項（改憲）が必要、という世論の盛り上がりを待っているのか、そんな穿った見方さえ出てくると思う」＃モーニングショー
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜sangituyama（こたつぬこ） 日時：2020-02-11 10:31／2020/02/10 23:09 URL： https://twitter.com/kk_hirono/status/1227042350125305856 https://twitter.com/sangituyama/status/1226870892728217600
> 〈高齢者は毎日新聞で完全に洗脳されてるど〉〈ガイキチ朝日新聞〉〈しんぶん赤旗は読むと脳が壊れる新聞だ〉〈ＮＨＫを見ると頭がバカになるど〉  ツイッターJAPANは、こんな投稿やりまくった青年会議所と「政治を語る」パートナーシップ協… https://t.co/Ddl844buDY
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Narodovlastiye（異邦人） 日時：2020-02-11 10:30／2020/02/11 00:40 URL： https://twitter.com/kk_hirono/status/1227042295049932800 https://twitter.com/Narodovlastiye/status/1226893721368584192
> ツイッタージャパンが「リテラシーを高める」としてパートナーシップを組んだ日本青年会議所は、ヘイトスピーチや憎悪表現で物議を醸して削除された、改憲ネット工作を目的とする「宇予くん」なるアカウントを作り上げた連中というのは、きちんと知… https://t.co/DpgUibO0Vj
▶▶▶　　　　　End　　　　　▶▶▶

RT akishigemakoto（MakotoAkishige（civilista））｜sangituyama（こたつぬこ） 日時：2020-02-11 09:45／2020-02-10 23:09 URL： https://twitter.com/akishigemakoto/status/1227030799259557888 https://twitter.com/sangituyama/status/1226870892728217600
> 〈高齢者は毎日新聞で完全に洗脳されてるど〉〈ガイキチ朝日新聞〉〈しんぶん赤旗は読むと脳が壊れる新聞だ〉〈ＮＨＫを見ると頭がバカになるど〉 \n  \n ツイッターJAPANは、こんな投稿やりまくった青年会議所と「政治を語る」パートナーシップ協… https://t.co/Ddl844buDY

　上記の９時４５分のリツイートが秋重実弁護士の最新ツイートになっています。日本青年会議所という名前自体はじめて知ったように思います。

〈〈〈：Emacs： 2020-02-11（火曜日）10：34 　〈〈〈

