福井県大野市　岐阜県白鳥

名古屋の佐川急便

川　自転車

* 「「逃亡請負人」ってこれ名誉棄損では？弘中先生がゴーンの”逃亡に”手を貸したって言ってるわけですよね。」という泥濘大魔王サイケのツイート＆えきなんローヤーのリツイート
  CLOCK: [2020-01-22 水 20:03]--[2020-01-22 水 20:29] =>  0:26

〉〉〉：Emacs： 2020-01-22（水曜日）20：03　 〉〉〉

:CATEGORIES: 泥濘大魔王サイケ,えきなんローヤー,名誉毀損,弘中惇一郎弁護士,カルロス・ゴーン氏

k_sawmen ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW k_sawmen（泥濘大魔王サイケ） 日時：2020/01/22 15:19 URL： https://twitter.com/k_sawmen/status/1219867147934941189
> さらっと冒頭に書いてますが、「逃亡請負人」ってこれ名誉棄損では？弘中先生がゴーンの”逃亡に”手を貸したって言ってるわけですよね。 https://t.co/FgoB12U8nD
▷▷▷　　　　　End　　　　　▷▷▷

RT ekinan_lawyer（えきなんローヤー🕊）｜k_sawmen（泥濘大魔王サイケ） 日時：2020-01-22 18:59／2020-01-22 15:19 URL： https://twitter.com/ekinan_lawyer/status/1219922612429578240 https://twitter.com/k_sawmen/status/1219867147934941189
> さらっと冒頭に書いてますが、「逃亡請負人」ってこれ名誉棄損では？弘中先生がゴーンの”逃亡に”手を貸したって言ってるわけですよね。 https://t.co/FgoB12U8nD

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜ryouheitakaki（弁護士 高木良平） 日時：2020-01-22 20:18／2020/01/22 10:47 URL： https://twitter.com/kk_hirono/status/1219942435595272192 https://twitter.com/ryouheitakaki/status/1219798663569952769
> およそ法律家のコメントとは思えない…  弘中弁護士に強制捜査なし 国が賠償責任を負うことにも？ #ldnews https://t.co/kWbkq5GzAY
▶▶▶　　　　　End　　　　　▶▶▶

［link：］ 弘中弁護士に強制捜査なし 国が賠償責任を負うことにも？ - ライブドアニュース https://news.livedoor.com/article/detail/17698754/

　泥濘大魔王サイケというアカウントの他のツイートは深澤諭史弁護士のタイムラインで見かけているのですが、上記の弘中惇一郎弁護士に対する名誉毀損というのは見ていないように思います。

　次は「% tu fukazawas 200|grep -B 1 泥濘大魔王サイケ」というコマンドの実行結果です。深澤諭史弁護士のツイートの最新２００件を読み込んでいますが、１９９件や１９８件しか読み込めていない場合はあるかもしれません。たぶん１つも２００も同じ処理です。

　ちょっと勘違いしていたのでやり直しました。次が「% tu fukazawas 200|grep -B 1 -A 1  泥濘大魔王サイケ」というコマンドの処理結果です。

RT fukazawas（深澤諭史）｜k_sawmen（泥濘大魔王サイケ） 日時：2020-01-22 19:31／2020-01-22 14:41 URL： https://twitter.com/fukazawas/status/1219930456981786624 https://twitter.com/k_sawmen/status/1219857536737693696
> バカじゃなかったら人を一年間無給で九時五時拘束したうえでバイト禁止したりしないですね https://t.co/fHMHFMYnNZ
--

RT fukazawas（深澤諭史）｜k_sawmen（泥濘大魔王サイケ） 日時：2020-01-22 17:14／2020-01-22 16:35 URL： https://twitter.com/fukazawas/status/1219896210321838080 https://twitter.com/k_sawmen/status/1219886188363837440
> 刑事弁護関係は簡単に荒れる。熱心に考えている人が多いから。
--

RT fukazawas（深澤諭史）｜k_sawmen（泥濘大魔王サイケ） 日時：2020-01-21 13:52／2020-01-21 13:52 URL： https://twitter.com/fukazawas/status/1219482892650205184 https://twitter.com/k_sawmen/status/1219482786794360832
> 事務所名、「どこまでなら弁護士会の承認が出るかチャレンジ」をやってみたいと思うことがある。 \n 「ピカチュウ法律事務所」はたぶんダメだろうが、「ヤドン法律事務所」とか「オムスター法律事務所」ならどうか。「ドククラゲ」だったら？あるいは… https://t.co/wq8fqpVllz

〈〈〈：Emacs： 2020-01-22（水曜日）20：29 　〈〈〈

* Twitterのトレンドで知った「杏さんとの別居報道 東出昌大さんの事務所は「ほぼ事実」」という話題、そこから思い出し、見逃しに気がついた刑事と検事のテレビドラマ
  CLOCK: [2020-01-22 水 20:40]--[2020-01-23 木 02:17] =>  5:37

〉〉〉：Emacs： 2020-01-22（水曜日）20：40　 〉〉〉

:CATEGORIES: テレビドラマ

　そういえば昼、あるいは午前中にも見かけていた「東出昌大」というTwitterのトレンドですが、さきほどはトレンドのキーワードの下に要約のような見出しがリンクになっていました。

　NHK連続テレビ小説の放送の順番を思い出すのも難しいのですが、１回だけ放送を見逃したこと、小木港の西防波堤でアジングをやっていてスマホのワンセグで視聴するつもりが失敗したこと、その場面が父親に結婚の許可をもらうところであったことは、以前に記述があるように思います。

　スマホを持っていたことは一つのヒントになりますが、最初に買ったスマホは珠洲市にバイクで向かう時、松波で川沿いの桜を見たという記憶が残っています。考えてみると当時はすでにTwitterを初めていたので、情報は残されているかもしれません。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-01-22 20:53／2013/10/29 11:30 URL： https://twitter.com/kk_hirono/status/1219951270011662337 https://twitter.com/hirono_hideki/status/395014840424857600
> 昨日は夜明け前から日没後まで小木港の堤防にいました。本命のアジが釣れたのは日が暮れた後です。2匹でした。ワンセグで「ごちそうさん」を見ようとしたのですが、ちょっと前に音だけになり、そのあとヒルナンデスになってしまい、チャンネルを戻せず。恩を仇で返しやがって、の台詞の直後。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-01-22 20:53／2014/04/18 00:56 URL： https://twitter.com/kk_hirono/status/1219951242425712640 https://twitter.com/hirono_hideki/status/456823579493928960
> 「花子とアン」は、半分を少し切るぐらいしか見ていないと思うけど、録画はしている。ごちそうさん、は1回だけ見逃した。求婚で父親に暴行を受けるような回。ワンセグで声だけは初めのうち聞こえていた。動画を見れるように操作していたところ、音声まで聞こえなくなった。小木港の堤防でのこと。
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「ごちそうさん ワンセグ」の検索結果 - Twilog https://t.co/0vjhZ2AV1J

　天気がよく日差しも暖かだったという記憶なので５月か６月とばかり思っていたのですが、１０月２９日のツイートに昨日、とあるので２０１３年１０月２８日のことであったようです。

　２０１８年１０月２８日の写真を探すつもりだったのですが、「死刑に対する朝日の見識-2013-02/死刑に対する朝日の見識_01_2013年02月07日22時19分29秒.jpg」というスクリーンショットの記録のファイルなどが出てきました。

　当時は年月日の情報をファイル名の先頭に持ってくることさえしないでいたようです。これをやらないと特に日本語の漢字を含む場合は、ファイルの並び順で文字コードが基準となって、人間には意味不明のものとなってしまいます。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-01-22 21:05／2013/10/28 22:48 URL： https://twitter.com/kk_hirono/status/1219954288882929666 https://twitter.com/hirono_hideki/status/394822975788052480
> 月曜ゴールデン「山岳刑事(2)」【ヤマデカ(2)　山岳サスペンスの第2弾！！】 2013年10月28日（月）  21時00分～22時54分  の放送内容 Gコード：  カレンダーに登録地域設定 現在放送中です。... http://t.co/42fvEn5BGa
▶▶▶　　　　　End　　　　　▶▶▶

　その２０１８年１０月２８日はTwilogでツイートが２つしかなく、月曜ゴールデン「山岳刑事(2)」【ヤマデカ(2)　山岳サスペンスの第2弾！！を視聴していた可能性があります。まったく見ないのにツイートすることはなかったはずです。しかし、記憶にはないドラマです。

　「廣野氏のコメントの多くこそ私怨に基づくコメ欄汚しと感じている_2013年03月02日18時38分19秒.jpg」というのも見つかりました。モトケンこと矢部善朗弁護士（京都弁護士会）のブログでモトケンこと矢部善朗弁護士（京都弁護士会）がコメントしたものです。

　時刻は日付が変わった23日2時12分です。２２時過ぎに、Googleフォトの方で２０１８年１０月２８日の小木港での写真を見つけていました。この中断中だと思いますが、けっこう大きな発見がありました。滋賀県大津市での保釈取り消しのニュースです。

　ちょうど２２時過ぎにテレビをつけたところ、ちょっと気になる感じのテレビドラマがありました。番宣での見覚えもなかったように思うのですが、ネットの番組表では３話目のようでした。山梨を舞台にしたNHK連続テレビ小説のヒロインの姿があり、主役のようでした。

〈〈〈：Emacs： 2020-01-23（木曜日）02：17 　〈〈〈

