#+TITLE: "コインハイブ控訴審、検察官からの質問に「黙秘」貫く"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-11-30 16:48:28 +0900
FILE_NAME: 2019-11-30-164828_コインハイブ控訴審、検察官からの質問に「黙秘」貫く.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 平野敬弁護士（第二東京弁護士会）,ジャーナリスト,弁護士ドットコム,コインハイブ,黙秘,検察
記事タイトル名の文字数：25　保存ファイル名の文字数：47
#+STARTUP: showeverything


* 弁護士ドットコム編集部出口絢記者の記事　弁護人平野敬弁護士（第二東京弁護士会）：コインハイブ控訴審、検察官からの質問に「黙秘」貫く
  CLOCK: [2019-11-30 土 16:52]--[2019-11-30 土 17:19] =>  0:27

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 平野敬弁護士（第二東京弁護士会）,ジャーナリスト,弁護士ドットコム,コインハイブ,黙秘,検察

〉〉〉：Emacs： 2019-11-30（土曜日）16：52　 〉〉〉

［link：］ コインハイブ控訴審、検察官からの質問に「黙秘」貫く　判決は2月7日 - 弁護士ドットコム https://www.bengo4.com/c_1009/n_10461/

　順番が前後しますが、この弁護士ドットコムの記事から取り上げご紹介をします。女性記者のことも先日来続いているかと思いますが、本日こんなかたちで、出口絢記者のことを取り上げるとは思いもよりませんでした。

　出口絢記者のTwitterアカウントはジャーナリストのフォルダとしてブラウザのブックマークに入れていますが、どこで見つけたアカウントなのか思い出せずにいました。弁護士ドットコムの記者であったことも忘れていたかもしれないですが、このコインハイブ事件がきっかけだったかもしれません。

　出口絢記者のTwitterアカウントを見つける少し前だったと思いますが、毎日新聞久留米支局の女性記者のアカウントに注目し、そちらを先にブックマークに入れていたと思います。ちょうど女性記者の活躍について関心を持ち出したタイミングでの出口絢記者の発見でした。

　これにはいくつか接点や繋がりがあるのですが、その結び目を表すノードとは、毎日新聞、宮崎市、示談、弁護士、大分市、黙秘、名古屋、金岡弁護士と言ったものがあり、このうち重要な要素のうち、金岡弁護士に関する新情報も本日の新たな発見となっており、黙秘は上記の記事にもあります。

　一つ久留米を入れ忘れていたようです。これはメモをかねたツイートが投稿済みと思いますので、そちらから確認したいと思います。これも大きな発見でしたが、ちょっときわどい感じでたまたま見つけることが出来たように思います。発見に至る経緯はすぐに思い出せません。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「久留米」の検索結果 - Twilog https://t.co/1fjCdYK8me

RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜mai_shihoko（安部志帆子@毎日新聞） 日時：2019/11/26 00:59／2019/11/20 20:23 URL： https://twitter.com/hirono_hideki/status/1198994694165811202 https://twitter.com/mai_shihoko/status/1197113238250352640
> ３月に福岡地裁久留米支部で無罪判決の出た準強姦事件の控訴審が始まりました。 被告は出廷しましたが、黙秘を続けました。 https://t.co/5UwjXzOFHC ＃毎日新聞 #ニュース

　やはり、安部志帆子記者のタイムラインで、安部志帆子記者のツイートとして発見したニュースであったようです。ブックマークには入れていますが、１月以上開かないこともざらにあったと思います。たまたま思い出して開いた時の発見だった気がします。

　ここでは簡単に書いておきますが、一部に大きな注目を集めたのが久留米支部の性犯罪の無罪判決で、毎日新聞のその記事に記者として名前があったのが安部志帆子記者になります。そのあとしばらくしてから反響の大きさのためか、上層部の名前で別の記事が上がっていました。この経緯も注目です。

　安部志帆子記者の取材と記事がなければ、広くネットで認知されることはなく、そんな事件が日本の刑事裁判ではごろごろところがっているのかと考えるきっかけにもなりました。

〈〈〈：Emacs： 2019-11-30（土曜日）17：19 　〈〈〈

