#+TITLE: "金沢市場輸送での山三青果（茨城県古河市）の仕事と5台の大型ウィング車の新車納入"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-09-28 11:51:19 +0900
FILE_NAME: 2019-09-28-115119_金沢市場輸送での山三青果（茨城県古河市）の仕事と5台の大型ウィング車の新車納入.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 平成3年1月から5月月頃,山三青果,被告発人東渡好信,金沢市場輸送
記事タイトル名の文字数：39　保存ファイル名の文字数：61
#+STARTUP: showeverything


* 金沢市場輸送での山三青果（茨城県古河市）の仕事と5台の大型ウィング車の新車納入
  :LOGBOOK:
  CLOCK: [2019-09-28 土 15:50]--[2019-09-28 土 20:30] =>  4:40
  :END:

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 平成3年1月から5月月頃,山三青果,被告発人東渡好信,金沢市場輸送

〉〉〉：Emacs： 2019-09-28（土曜日）15：50　 〉〉〉

　ファイルを作成したのが11時51分となっていますが、その後、Aコープ能都店に買い物に行き、また、モトケンこと矢部善朗弁護士（京都弁護士会）の気になるツイートがあって予定していた作業を中断していました。

　ハードディスクでのパソコンの動きの遅さもいよいよ気になっています。ブラウザでページを開くにもけっこうな時間がかかることがあり、長い目で見るとどれだけの時間のロスになるのかと真剣に考えるようになりました。

　モトケンこと矢部善朗弁護士（京都弁護士会）の件のキーワードは「私怨」になります。かたちとして「寝た子を起こす」ことにもなったと私は思うのですが、本人のモトケンこと矢部善朗弁護士（京都弁護士会）がそれだけ気にかけてはいないということなのでしょう。

[link:] » 過労による大事故の発生を真剣に考えた市場急配センターでの最後の運行、静岡県御殿場SA付近 - 金沢市駅西本町所在市場急配センターにおける組織犯罪殺人未遂事件として再捜査の要請書／石川県警察珠洲警察署御中 https://t.co/UkoUq2qu2V

　ブログ記事としてはは上記の内容の続きとなります。整理のために枝分かれをさせました。

　すべて平成3年1月中の納車だったと思うのですが、3台の大型ウイング車が金沢市場輸送の入りました。金沢市場輸送では初めてのウィング車でした。ウィング車は基本、箱車ですが、電動のボタンで左右の荷台の屋根が開きます。パレットのままの積み下ろしにも向いています。

　車番は石川ナンバーで2313、2314、2315と続いていたように思いますが、2314号については現在記憶に残っていません。2313号はもともと平ボディ車の運転手だった小坂さんが乗務して、三菱ふそうの大型車でした。

　私が乗務したのは2315号だったと思います。日野の大型車でした。1月17日の朝に金沢市場輸送の会社に納車されたのですが、この日付をよく憶えているのは、待っている間の朝のテレビのニュースで、湾岸戦争の空爆開始がニュースとなっていたからです。

　もう1台の大型ウイング車は2314号になるのかと思いますが、こちらも日野の大型車だったと思います。これに乗務したのが、それまでずっと三菱ふそうの大型保冷車に乗務していたKKでした。昨日か一昨日にも少し触れましたが、当時の珠洲郡内浦町新保の出身です。

　この続きも別の独立したエントリーとして記録しておこうと思います。彼から聞いた話が嘘偽りだったとは考えられないのですが、仮にそのようなことであったとすれば、金沢市場輸送の会社とのただならぬ関係性が推認され、会社の謎の部分の実態に迫る鍵ともなるはずです。

　金沢市場輸送で山三青果の仕事が始まったのは平成2年の12月に入ってすぐだったと思います。始まったと言っても当初は仕事も荷物も少なかったような印象が残っています。

　全般的に山三青果の仕事は、忙しい時と忙しくない時の違いが大きく、これはそのまま青果物の荷物の量にもよるのですが、それとは別に、夕方の競りの後、出発するときと、午前中にほぼ荷物を積み終えて昼過ぎに出発をするときがありました。

　荷物の中心はレタス、サニーレタス続いて白菜、キャベツだったと思いますが、ナスやトマトを積むこともあったように思います。レタスは軽いですが、キャベツや白菜となると重量オーバーになることもあったように思います。

　鮮魚の場合は時期によって扱う魚の種類も変わったり、サンマのように時期が決まった荷物もあったのですが、青果物についてのは、その辺りがよくわかりませんでした。一般的には12月は市場の仕事が最も忙しくなる時期です。連休明けなども荷物の量が増えがちです。

　なお、これまで山三青果の住所を茨城県古河市としてきましたが、そこの青果市場の中に小さな事務所があって、荷物の積み込みもそこでした。一度だけ山三青果の若い社員を同乗させて埼玉県の深谷市に行ったことがありました。ネギで有名ですが、そのネギを積に行ったかもしれません。

　事務所には決まって出入りをしていましたが、建物の2階にあるとても狭い部屋で、社員の休憩所のようなものはたぶん別にあったのだと思います。また、なにかの機会に封筒をみて山三青果の会社の住所が猿島郡となっていたことも記憶にあります。同じ茨城県です。

　昼過ぎに古河市を出発した運行で記憶にあるのは平成3年12月24日のクリスマスイブの日でした、関越トンネルの手前のトイレだけのパーキングエリアから会社に電話をしたことを憶えていて、風邪のためか声がおかしくなっていて、それを被告発人池田宏美に指摘されたと思います。

　12月から3月と冬の日の短い時期でしたが、早いときはまだ外が明るい時間に富山インターを降りることもあったかと思います。今ではあまり思い出せなくなっていますが、仕事の方も23時頃には終わっていたように思います。

　これが忙しいときだと、福井の市場で荷物をおろし終えて金沢の会社に戻るのが朝の7時頃になることもありました。これは荷物の量とは別の忙しさにもなります。

　古河の青果市場からの荷物の行き先は、富山、高岡、金沢、福井と決まっていたのですが、荷物が多いときは大型車2台に4t車が1台ということもけっこうありました。4つの行き先を分散するので、行き先も減ってこの方が仕事も楽で、終わる時間も早くなる傾向でした。

　大変なのは大型車一台で4箇所積みの場合でした。前にも何度か書いていると思いますが、基本、福井分は金沢の市場で待機する4t車に積み替える中継で、この中継をよくやっていたのが被告発人梅野博之と被告発人多田敏明でした。

　夕方の競りがあると出発は20時頃が多かったように思いますが、遅いときは21時頃になりました。単純に6時間の走行でも午前3時になりますが、荷降ろしに時間がかかったり、富山県高岡市の市場などは高速道路からもけっこう離れていて、戻るのもほぼ往復の時間が掛かります。

　関越自動車道で新潟県内の豪雪地帯も通過するので、道路状況のもよりますがそれなりに時間がかかったり、通行止めで大変な思いをした経験もあるので、冬場はなにかと神経がピリピリとしていました。

　金沢市場輸送で小坂さんが乗務をしていた2313号ですが、これは早い段階で市場急配センターに引き取られ、被告発人安田敏が乗務するようになりました。ここに出てくるのが川上板金でもありますが、これも過去の取り上げているのではと思います。一応確認しておきます。

[link:] » 告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)/「川上板金」の検索結果 - Twilog https://t.co/Vx0nRNfWI6

　キーワードを含むツイートが３つというのは、意外に少ない結果でした。

　金沢市場輸送で小坂さんが乗務していた大型ウィング車のことは、よく思い出せないのですが、平成3年10月頃に市場急配センターで長く市内配達をしていたYTが乗務したのが、その大型車であったかもしれません。

　YTは私と同じ年で河北郡津幡町と聞いていました。その同級生という人物が福井刑務所で工場担当の刑務官を担当台の上から投げ飛ばし、騒動となったのですが、その辺りも詳しいことは裁判記録にあると思います。プライバシーもあるので、ここでは最小限の指摘です。

　津幡のYTは、市場急配センターでも最古参の運転手で、被告発人梅野博之よりしっかりしていて人望もありそうな感じでしたが、入社の時期となると余り思い出せません。昭和62年6月の山中温泉キャッスルバーデンホテルの慰安会のときに、姿があったかも微妙に思います。

　被告発人松平日出男社長は、津幡のYTが市内配達をやめて長距離の大型車に乗務することに反対したと聞きますが、本人がダメなら会社をやめると言い張ったので、折れたような話を聞きました。

　この津幡のYTのことで、これもKKのことと同様に真偽が気になるのは、平成3年12月22日の夜になると思いますが、国道8号線の金沢東インターの近くで喧嘩になり、しばらく気絶をしていたという話でした。これも別のところで独立した記録をしておきたいと思います。

　平成3年の4月中だったように思いますが、追加で2台の大型ウィング車が金沢市場輸送に納入されました。これはそれまでの金沢市場輸送のトラックとはデザインとカラーが違っていました。白がベースで赤と青のラインが入っていました。

　聞いたところによると金沢市場輸送の本恒夫社長の娘の考案したデザインということでした。この本恒夫社長の家族というのは謎の部分が大きく、話を聞くことはありましたが、会社で姿を見るようなことは一度もありませんでした。

　それでも一度、この家族や娘の顔を私は見ているはずなのですが、どういうわけか全く記憶に残っていません。前に一度はネットの情報としても記述をしていると思うのですが、金沢市入江辺りの野田専光寺線沿いの回転寿司でのことです。

　金沢市場輸送の輪島の運転手仲間が3,4人、私のアパートに遊びに来たときでしたが、その近くの回転寿司に食事に行った時のことです。よくあるテーブル席で、隣のテーブル席との間にけっこうな大きさの隙間があったのですが、一人が驚いた声を上げたのです。

　今考えると、それほど驚くことだったのかとも思うのですが、輪島の言葉で「なんちゅう、よく食うおなごかえ」などと言い出したのです。そこで見たのが積み上げられた回転寿司の皿で、その奥に見慣れた本恒夫社長の姿ありました。

　本恒夫社長は、平然と何食わぬ顔で食事をしていましたが、あとで考えると隣のテーブルでの声が耳に入らなかったのか不思議でした。家族の4人連れだったと思うのですが、本恒夫社長以外の顔というのはまったく記憶に残っていません。

　息子と娘がいるような話は聞いていましたが、子どもが3人とも聞いた気がしないではありません。妻はいくつか年上と聞いたことがありました。

　今久しぶりに思い出したのですが、本恒夫社長に息子に関しては、天狗中田ハムの社員と聞いたように思います。この天狗中田ハムですが、昔からテレビCMでもちょいちょいと見かけています。現在はわかりませんが、石川県以外に会社を見かけたことはありませんでした。

　昭和59年当時は、この天狗中田ハムの仕事も金沢市場輸送ですることがありました。下粂運送という小さな運送会社があって緑ナンバーだったと思いますが、緑ナンバーを取得するための最低限の台数とも聞きました。

　真面目そうな二十代ぐらいの男が、その下粂運送の仕事をするようになったのですが、まもなく大阪市内の大きな交差点の真ん中にトラックを駐車して眠り続けるという騒動がありました。酒乱だったらしくトラックの社内には沢山のワンカップの日本酒が転がっていたという話です。

　当時、天狗中田ハムの会社は、金沢市の繁華街の近くで新竪町の商店街の入り口辺りにありました。倉庫だったのかよく憶えていないですが、そこには何度か仕事に行ったことがあり、大阪での騒動があったときも駆り出されてなにかの手伝いをさせられたことを少し憶えています。

　浜田漁業金沢工場の隣にあったのも天狗中田ハムの工場だったように思いますが、そちらは屠殺場だと噂に聞いたことがありました。前を通ると独特の匂いがしましたが、隣接した浜田漁業金沢工場もお馴染みの魚が腐った匂いがいつもしていました。

[link:] » 天狗中田産業（株） 才田工場 - Google マップ https://t.co/KUbtcU2CDG

[link:] » （株）天狗中田本店 - Google マップ https://t.co/jkMdtrZrJp

[link:] » 天狗ハム 金沢本社営業所 - Google マップ https://t.co/8YZWzRfxqn

　ストリートビューで建物の確認などはしていませんが、片町の近くにあるのは天狗中田本店のようです。金沢本社営業所という二項対立のような社名が西金沢にありますが、こちらは余り記憶にありません。そういえばその辺りになにかあったような気はします。

　本恒夫社長の息子と天狗中田ハムの話は、誰から聞いたのか憶えていないですが、話を聞きながら会社の場所として金沢市の八日市から押野の辺りを想像していました。これは被告発人松平日出男の家の場所がある場所としても誰かに聞いたことがあった辺りです。

　確認はしていないですが、供述調書での被告発人松平日出男の住居地は金沢市糸田新となっていたように思います。糸田というのが隣接して別にあったような気もしますが、どちらもかなり狭い範囲でした。私の東力のアパートの近くで、裏道として通ることもありました。

[link:] » 糸田 - Google マップ https://t.co/VsRD6zm5FM

　私の住んでいた東力二丁目のアパートのすぐ近くも住所が糸田になっていて少し驚きました。平成4年当時、一階にコインランドリーとカラオケボックスがあったビルも住所は糸田になるようです。

[link:] » 糸田新町 - Google マップ https://t.co/oy6pemaVXA

　糸田新町ですが、思っていた以上に狭い範囲の住所地です。あるいは二口町や駅西本町のように区域の変更があったのかもしれないですが、糸田新町と思っていた場所が増泉5丁目となっているようです。

　Googleマップでみると昭和大通りとありますが、現在のGoogleマップで見る「すき家金沢増泉店」の辺りに、割と大きなパチンコ店がありました。駐車場も広かったですが、その小路に入って100メートルほどだったでしょうか。左手に松元組の組事務所がありました。

　誰に聞いたのか私の思い込みだったのかもしれませんが、その松元組の組事務所が糸田新町と聞いたことがありました。地図でも北陸本線に隣接していますが、その辺りも裏道として通行した記憶があり、古い町工場のようなものがあったと記憶の片隅に残っています。

　暴力団松元組は、被告発人HTNが少年時代に所属していたヤクザです。その辺りも裁判記録には知りうる限りのことを記録してありますし、もともと石川県警察が注目をしていたところかとも想像します。○○運送のこともありますが、覚醒剤密売ルートとしての情報も少しは聞いています。

　本恒夫社長の妻に関しては、有線放送の関係の仕事をしていると聞いたことがあったのですが、これも話を聞いたときは、深くも考えずに聞き流していました。長距離運転手の仕事でも金沢市場輸送の仕事は、泊まりなど待機時間が長くて、運転手仲間で他愛ない長話をすることもよくありました。

　平成3年4月ということにしておきたいと思いますが、納入された2台に乗務したのは被告発人東渡好信と浜上さんでした。被告発人東渡好信の乗務したのは三菱ふそうだったと思いますが、浜上さんの乗務したのは日野のトラックであったように思います。

　その三菱ふそうの新車を、竹沢俊寿会長と被告発人松平日出男の話で、金沢市場輸送から市場急配センターに移動させると決めたところ、激怒した被告発人東渡好信が市場急配センターの事務所で包丁を手にして、机に突き立てるような行動をしたのです。

　あとから聞いた被告発人池田宏美の話では、待ち構えていた被告発人東渡好信が会社に戻った被告発人松平日出男を包丁を振りかざしたまま外に追いかけ回し、被告発人松平日出男の同行者がそれを幸いに阻止したという話でしたが、いかにも嘘くさい演出だと思いました。

　実際に包丁がテーブルに突き刺さるようなことは、物理的に考えてなかったと思いますが、その異様な空気のなか、被告発人安田繁克から会社に電話があって、その場にいた私と被告発人安田敏は、徳島行のスイカの荷物の積替えのため、尼御前サービスエリアに向かったのです。

　包丁のことは演技や演出だと思いましたが、同じ頃の早朝、金沢中央卸売市場の青果の売り場で、被告発人東渡好信が荷受けのおじいさんの首根っこを掴まえて、キャベツの箱の中に顔面を力づくで押し込んだときは、さすがに驚きました。

　今考えると、金沢市場輸送で小坂さんが乗務していた新車の大型ウィング車は、そのまま金沢市場輸送で小坂さんが乗務を続けていたのかもしれないですが、私が市場急配センターに移ってから小坂さんの姿を見たという記憶はないように思います。

　小坂さんはもともと平ボディ車の運転手で、私が最初に金沢市場輸送に入社した昭和59年当時も同じでした。当時、平ボディの大型車は3台で、2台は日通カラーの新車に近いものでした。いずれも日野のトラックで、原田さんと棟方さんが乗務していました。

　小坂さんが乗務していたのは古い旧型のイスズのトラックだったと思いますが、会社で姿を見ることも少なく、無口で人を寄せ付けないような印象がありました。体格や雰囲気がいくらか総理大臣になる前の小泉純一郎氏に似ていると振り返って思うことがありました。

　裁判記録には少なくとも一回以上の記述があると思いますが、明らかに雰囲気や印象が変わったと感じたのは、加賀能登物産展の仕事で姫路市に行った時のことでした。姫路城が右手に見える広い道路に駐車をして、そこで小型車に積み替えの作業をしていたときのことです。

　昭和59年当時の金沢市場輸送の大型保冷車の仕事のメインは、石巻から四国、南九州への養殖ハマチの餌となる小魚の冷凍物を運ぶ仕事で、一度の運行に最低一週間はかかると聞いていました。

　ウロコ運送との福岡の長浜の魚市場からの定期便はすでに始まっていたので、そちらが唯一の定期便だったとも思います。他に金沢市間明の辺りに名鉄運輸があって、そこからも雑貨の定期便があり、積込みの手伝いに行ったことがありました。

　聞いた話では九州の各地を荷降ろしして周り最後は鹿児島だと聞いていました。浜田漁業金沢工場でのミールの仕事が始まったのも昭和60年の晩秋以降かと思います。

　浜田漁業金沢工場の前の道路は、金沢東インターのトラックステーションの横から当時の河北郡宇ノ気町に通じる主要道で、全て対面通行で道路沿いは田んぼが多かったですが、農免道路と呼ばれていました。

　中西運輸商の仕事のメインは佐川急便で、金沢の営業所が農免道路に近い木越にありました。調べていませんが今も同じ場所にあるのかもしれません。中西運輸商ではトラックステーションの利用も多くて、農免道路でイワシを運搬するトラックをよく見かけるようになりました。

　同じ頃に、金沢市場輸送が浜田漁業金沢工場でイワシの運搬の仕事を始めたという話を聞くようになりました。当初は、その後もトラックステーションを根城とする、青森県八戸市の白ナンバーのグループがメインとなっていました。運搬の規模も当初は小さかったようです。

　あれは昭和63年の秋だったと思いますが、冬場のイワシの運搬の仕事を本格化するため、竹沢俊寿会長は一度に5台の平ボディ車を納入しました。もちろん大型車です。はっきりとは思い出せないですが、いすゞが2台で三菱ふそうが3台であったように思います。

　その前、昭和62年の4月の時点で2台のダンプも新車で納入済みでした。このとき一台のダンプに最初に乗務したのが松浦さんになります。当初は松浦さんの連れのダンプ仲間のような運転手がもう一台に乗務していましたが、イワシの運搬が本格稼働する時期ではなかったと思います。

　イワシの運搬の時期は基本が12月から3月だったと思いますが、ダンプは始めるのもいくらか早く、漁獲量が少なくなった4月中も待機をしながら水揚げがあれば運搬の仕事をしていたようです。

　昭和63年12月から始まったイワシのシーズンには大西真さんがもう一台のダンプに乗務し、翌年の平成1年12月からのシーズンには坂田さんが同じダンプに乗務をしていました。

　イワシの運搬をする平ボディ車は、特製の水槽のようなものを荷台に取り付けていました。竹沢俊寿会長が熱心に工夫し業者を探し回ったとも聞きますが、和歌山県田辺市の工場で制作していました。小さな工場だったと記憶にありますが、一度完成したトラックを引き取りに行ったことがあります。

　その後、大型平ボディ車は2台が追加で納入されましたが、2台ともいすゞのトラックだったと思います。荷台の後方側面にある金沢市場輸送の文字が、それまでのものよりずいぶんと太字になっていたのが印象的です。

　その2台は、イワシの運搬のための水槽のようなタンクを載せることはなく、前からあった他の平ボディ車と同じくミールやダンベを中心にしていました。ダンベと呼ばれたのはイワシを入れる小型の水槽で、左右に8箱ずつ16箱乗っていたと思います。

　ダンベで運ぶイワシというのは、これも養殖ハマチの餌となる原料で、加工場は小さな個人商店のようなところが多く、三重県の白塚町がほとんどでしたが、尾鷲市にも行ったことがありました。伊勢市の冷蔵庫にも行ったかもしれません。

　金沢市場輸送の経営のことはわからなかったですが、このミールを含めたイワシの仕事が金沢市場輸送を急成長させる原動力になったとも考えられますが、保冷車の東北便も売上は大きいと聞くことがありました。

　イワシの運搬は金沢港がメインでした。平成元年12月以降のシーズンでは、市場急配センターからの請負で金沢市場輸送が運搬をするというかたちだと聞いていましたが、税金対策という話でした。山三青果の仕事も当初は同じスタイルだと聞いていました。

　金沢市場輸送への委託をやめて市場急配センターが自社で山三青果の仕事をするということに変わったのですが、私がその話を最初に聞いたのも、金沢市場輸送をやめて、被告発人安田敏の借金の保証人のことで被告発人松平日出男に会った時のことであったと思います。

　私が金沢市場輸送に愛想を尽かし、将来に不安を感じてやめようと思ったのも、最初は被告発人東渡好信が主導した金沢市場輸送でのストライキにありました。4月の中頃から始まったように思います。その最中に被告発人安田敏から連絡が入ったのです。

　今まで深く考えたことはなかったのですが、平成3年12月頃からミール移動の仕事が始まってからも、北陸ハイミールや浜田漁業金沢工場で小坂さんの姿を見ることはありませんでした。

　金沢港のイワシの水揚げの現場に行くことは全くなくなっていたので、よくよく考えると、ダンベの運搬に専属していた可能性もありますが、以前はダンベの仕事いうのは多くはなくて、平ボディ車やウィング車の冬場の仕事のメインは、やはりミールだったのです。

　ミールの仕事は金沢市内近郊での倉庫移動と、県外への運送があって、行き先の大半は愛知県内で、それも知多半島の付け根辺りに集中していると聞きました。聞いた話ではインスタントラーメンのスープの原料になるということでしたが、ミールは他にも養鶏場の餌という用途もありました。

```
フィッシュミール
魚粉とも。生魚を煮熟，圧搾，乾燥し粉末としたもの。初めは肥料として製造されたが，現在ではおもに飼料とされ，一部はタンパク質源食料にも利用されている。ホワイトミールとブラウンミールに分かれ，前者はタラ，カレイのような白身魚を原料とし，後者はニシン，イワシのような赤身魚を原料とする。また，脂肪含有量の多少によって多脂ミールと少脂ミールとに区別。
→関連項目イワシ（鰯）｜飼料
出典　株式会社平凡社百科事典マイペディアについて　情報

［source：］フィッシュミールとは - コトバンク https://kotobank.jp/word/%E3%83%95%E3%82%A3%E3%83%83%E3%82%B7%E3%83%A5%E3%83%9F%E3%83%BC%E3%83%AB-615520
```

　金沢市場輸送にあった大型ウィング車は、すべて市場急配センターに移動させられたわけではなかったように思いますが、そうかと言って、少なくとも平成3年12月中前の間、軽油の給油に行った金沢市場輸送の事務所付近で、ウィング車を見かけたという記憶はありません。

　金沢市場輸送から市場急配センターに移ったあと、いくらか不思議に感じたのは、金沢市場輸送の本恒夫社長が、それまで山三青果の定期便とセットになっていた行き荷の、日通の埼玉（岩槻市）千葉の定期便と、トナミ運輸の栃木への定期便を手放さなかったという話です。

　金沢市場輸送の仕事には東京ストアの定期便があったのですが、それ以外に東京に行くと、なかなか帰り荷の荷物が見つからなかったり、給料の歩合にもならない空車で帰ることも度々ありました。

　豊海や大井ふ頭の冷蔵庫から冷凍物を運んで帰ることもありましたが、安定した帰り荷として記憶にあるのは、主に神奈川県内だったお菓子の運搬でした。卸先は金沢市専光寺の近くの日通の倉庫が多かったように思います。

　「あずまうんゆ」としてその帰り荷の荷主の運送会社に電話をしていたことも記憶にあるのですが、どこのどういう運送会社なのかは、運転手仲間の間でも話を聞くことはなかったように思います。漢字は東運輸の可能性が高そうですが、あちこちにありそうな社名でもあります。

　今考えると、あの日通とトナミ運輸の定期便を金沢市場輸送の本恒夫社長が手放さなかったため、被告発人東渡好信の出番となって、七尾市の丸一運輸の仕事が増えたとも考えられますが、丸一運輸の仕事について話を聞くことはありませんでした。

　はっきりとは思い出せないものの、その日通とトナミ運輸の仕事も雑貨の定期便にしてはずいぶん運賃が良いという話を聞いたかもしれません。はっきり憶えているのは山三青果の運賃が良いという話で、安定しているという話であったとも、12万円と聞いたとも断片的な記憶が残ります。

〉〉〉：Emacs： 2019-09-28（土曜日）20：30　 〉〉〉

