#+TITLE: "元鹿児島県警本部長に対して「自分のツイートの危機管理は全くできないのね」というモトケンこと矢部善朗弁護士（京都弁護士会）の刑事責任追求"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-10-13 11:01:06 +0900
FILE_NAME: 2019-10-13-110106_元鹿児島県警本部長に対して「自分のツイートの危機管理は全くできないのね」というモトケンこと矢部善朗弁護士（京都弁護士会）の刑事責任追求.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 名誉毀損の刑事告訴,モトケンこと矢部善朗弁護士（京都弁護士会）,名誉毀損
記事タイトル名の文字数：67　保存ファイル名の文字数：89
#+STARTUP: showeverything


* 元鹿児島県警本部長に対して「自分のツイートの危機管理は全くできないのね」というモトケンこと矢部善朗弁護士（京都弁護士会）の刑事責任追求
  CLOCK: [2019-10-13 日 11:05]--[2019-10-13 日 17:28] =>  6:23

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 名誉毀損の刑事告訴,モトケンこと矢部善朗弁護士（京都弁護士会）,名誉毀損

〉〉〉：Emacs： 2019-10-13（日曜日）11：05　 〉〉〉

　まず、ここでは概要について記しておきたいと思います。モトケンこと矢部善朗弁護士（京都弁護士会）の刑事責任追求の必要性については、長年、検討をしながら継続をしてきました。大前提として本件再捜査事件の受理が必要とも考えてきました。鶏と卵のような関係性です。

motoken_tw ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW motoken_tw（モトケン） 日時：2019/10/13 09:49 URL： https://twitter.com/motoken_tw/status/1183182923198951425
> この人、危機管理が専門だそうだけど、自分のツイートの危機管理は全くできないのね。 \n 再掲 \n https://t.co/G4D7Dcwk6M https://t.co/mjUeOd84Op
▷▷▷　　　　　End　　　　　▷▷▷

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜onojiro（小野次郎） 日時：2019-10-13 11:09／2019/10/13 04:10 URL： https://twitter.com/kk_hirono/status/1183203133104590848 https://twitter.com/onojiro/status/1183097512833339392
> 本当にそうですか？ 貯めておいた大量の水を一気に放流すれば、河川が氾濫するのはむしろ当然ですよね？ https://t.co/Cna5iMGqXX
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜TrafalgarRio（トラファルガー・リョー） 日時：2019-10-13 11:10／2019/10/13 10:13 URL： https://twitter.com/kk_hirono/status/1183203211466797056 https://twitter.com/TrafalgarRio/status/1183189033679085568
> @motoken_tw いや、危機管理自体についてもダメそうですよ…
▶▶▶　　　　　End　　　　　▶▶▶

motoken_tw ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW motoken_tw（モトケン） 日時：2019/10/13 10:18 URL： https://twitter.com/motoken_tw/status/1183190242129395714
> @TrafalgarRio はい、危機管理的観点でまともなことを言ったツイートを見た記憶がないです。
▷▷▷　　　　　End　　　　　▷▷▷

　どうも小野次郎氏に対する返信とはなっていないようです。小野次郎氏の元のツイートの返信欄にもモトケンこと矢部善朗弁護士（京都弁護士会）のツイートは見当たりません。公式引用ともされていますが、ツイートのURLを引用しただけのようです。

　次が小野次郎氏のTwitterアカウントのプロフィールに引用になります。

```
小野次郎
@onojiro
1953年生れ。(公益財団法人)日本航空教育協会会長、鹿児島県警本部長、小泉総理秘書官、参議院議員など歴任。危機管理が専門。改革志向だが戦争は反対。脱原発、自然エネルギー立国。
山梨、東京、そして全国2010年1月からTwitterを利用しています
1.8万 フォロー中
1.9万 フォロワー

［source：］小野次郎（@onojiro）さん / Twitter https://twitter.com/onojiro
```

　ヘッダ画像の写真がひまわり畑となっており、これも印象的なものであります。このヒマワリというのは弁護士が象徴とするもので弁護士バッチのデザインにもなっているはずです。因みに、その弁護士と対峙することもある一方の検察は、秋霜烈日とされています。

　小野次郎氏のTwitterのプロフィールのアイコンは、そのまま履歴書にも使えそうな顔写真となっています。名前の方は全く記憶になかったのですが、この顔写真は見覚えがあるとすぐに思いました。Twitter社の認証マークも付いていて、本格的な感じです。

　何より注目したのは「鹿児島県警本部長」というプロフィールの経歴で、これがなければ、たぶんこのように取り上げることはなかったと思います。このあと詳しく取り上げておきたいと思いますが、平成２１年当時の石川県警察本部長も経歴が鹿児島県出身となっていました。

　そういえば、数年前、金沢地方検察庁の検事正だった人物が、京都地検の検事正になったというニュースがありましたが、何か著名な事件に関わっていて、不信や否定的な見方を示す情報を見かけたように思います。疑惑の程度はすこぶる軽微だったとは思います。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-13 11:58／2010/05/09 01:08 URL： https://twitter.com/kk_hirono/status/1183215508226596864 https://twitter.com/hirono_hideki/status/13616078975
> http://goo.gl/MQEI 金沢地方検察庁検事正あいさつ（大　島　忠　郁(おおしま　ただふみ)
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-13 11:57／2017/08/23 11:42 URL： https://twitter.com/kk_hirono/status/1183215042184925185 https://twitter.com/hirono_hideki/status/900186578710089728
> （引用→）　山本氏は平成３年任官。関西地方の地検を中心に勤務し、大阪地検特捜部に通算３年間在籍。京都地検特別刑事部長、法務省人権擁護局総務課長などを歴任した。兵庫県出身。 https://t.co/57Mu9F38e9
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-13 11:55／2014/04/06 00:41 URL： https://twitter.com/kk_hirono/status/1183214683513180161 https://twitter.com/hirono_hideki/status/452471114888142849
> @joking_my_dear 名誉毀損と言うことで相談はしています。京都地検の検事正は、前任地が金沢地方検察庁だったらしいので、私のことも把握されているとは、少しは期待しています。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-13 11:54／2013/08/05 03:35 URL： https://twitter.com/kk_hirono/status/1183214503313297408 https://twitter.com/hirono_hideki/status/364092171865292800
> ちなみに前もツイートしたけど、現在の京都地検の検事正は数年前の金沢地方検察庁の検事正だったはず。最近確認していないけど就任の年月期間的に、たぶん転任はなさそう。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-13 11:53／2010/05/11 01:01 URL： https://twitter.com/kk_hirono/status/1183214238971465728 https://twitter.com/hirono_hideki/status/13733820777
> 高松地検（１日） | 香川のニュース | 四国新聞社 http://goo.gl/hv4D　のなかで、▽検事（京都地検検事）浜崎一、を見つけたが、2002年のデータみたい。当時を知る生き証人の一人には間違いない。これも同姓同名は可能性が低い。
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「京都地検」の検索結果 - Twilog https://t.co/YWqDe7t24M

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「検事正」の検索結果 - Twilog https://t.co/qrwW72tEJp

　思ったより簡単には見つからなかったですが、大島忠郁という名前が確認できました。名前さえわかれば情報は集まり、確認できることもあるかと思います。

```
大島氏は大阪地検特捜部の押収資料改竄事件が発覚した平成２２年９月当時、大阪地検ナンバー２の次席検事として対応に追われた。「前代未聞の不祥事に強い衝撃を受け、悩んだ」と振り返る。事件発覚から約４年。今度はトップとして大阪地検の指揮に当たるが「職責を全うしたい」と決意を述べた。

　九州大法学部を卒業後の昭和５６年に任官。大阪地検刑事部長や金沢地検検事正などを歴任。京都地検検事正から７月１８日付で現職に就いた。宮崎県出身。

［source：］「基本に忠実に」大島検事正が着任会見　大阪地検 - 産経WEST https://www.sankei.com/west/news/140723/wst1407230020-n1.html
```

　前提となる名前を探すのは容易ではなかったですが、すぐにドンピシャのような情報が見つかりました。→「大阪地検特捜部の押収資料改竄事件が発覚した平成２２年９月当時、大阪地検ナンバー２の次席検事として対応に追われた。」。

　平成２２年と聞いてもピンと来ないですが、2010年といえば、私が4月にTwitterを始めた年になります。押収資料改竄事件というのは、村木裁判に関連したフロッピーディスクの問題のことかと思います。9月に発覚したとありますが、時期のことは余り記憶にないです。

　大島忠郁氏は、その後、金沢地方検察庁、京都地検の検事正を歴任し、上記の記事にある2014年7月23日頃に大阪地検の検事正となって記者会見を開いていたと、あります。

　こまかい経過は確認できないですが、大阪地検次席検事から金沢地方検察庁の検事正に移動したものと時期的に考えられます。正確なことはわからないですが、左遷というかたちになるのかもしれません。

　再び記事に目を向けて気がついたのですが、締めくくりに「宮崎県出身」とありました。こういう検事正の就任もそうですが、県警本部長も出身が強調されるような気がします。一月ほど前になりますか、石川県警察本部長の就任ニュースでも、岡山県となっていたように思います。

[link:] » 奈良地方裁判所 平成６年（わ）３９３号 判決 - 大判例 https://t.co/city0eIapl

　「大島忠郁」のGoogle検索を1年以内に絞り込んだところ、上記のページが最上位に出てきました。記事の日付のような情報が2019年となっていたので、大阪地検の検事正から奈良地検に移動し、それも決済官ではない平検事になったのかと驚いたのですが、よく見ると平成6年の判決でした。

　地検トップの検事正とナンバー2の次席検事は、決済官で公判に出ることもないと聞きます。マスコミ対応も次席検事と言われてきましたが、神奈川県愛川町の収監時の逃走事件では、横浜地検の検事正が記者会見を行い、やはり前例がないと報道がされていました。

　検事の任期は2年から4年とされています。検察官の場合は副検事を含むとされますが、副検事は司法試験の合格が必要とされていないと思いますが、検事と同様に転勤があるのか、今回始めて疑問に思いました。

　検事正が例外となっているとは聞きませんが、普通に考えて検事と同じ2年から4年の任期かと思われます。2014年7月に大阪地検検事正の就任であれば、4年は過ぎているので現職とは考えられませんが、その後の情報というのは見当たりませんでした。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-10-13 12:46／2019/10/13 11:49 URL： https://twitter.com/kk_hirono/status/1183227529244446720 https://twitter.com/s_hirono/status/1183213216882511872
> 2019-10-13-095514_モトケン@motoken_tw·31m常識として知っておくべき連ツイ。.jpg https://t.co/oAt3pTdxHE
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-10-13 12:46／2019/10/13 11:50 URL： https://twitter.com/kk_hirono/status/1183227477868433409 https://twitter.com/s_hirono/status/1183213288814833664
> 2019-10-13-102338_モトケン@motoken_tw·34mこの人、危機管理が専門だそうだけど、自分のツイートの危機管理は全くできないのね。再掲.jpg https://t.co/mdw37cIAT1
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-10-13 12:46／2019/10/13 11:50 URL： https://twitter.com/kk_hirono/status/1183227452744556544 https://twitter.com/s_hirono/status/1183213362311614468
> 2019-10-13-103225_小野次郎（@onojiro）さん　／　Twitter.jpg https://t.co/GTDtaSJKCh
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-10-13 12:46／2019/10/13 11:50 URL： https://twitter.com/kk_hirono/status/1183227435837317122 https://twitter.com/s_hirono/status/1183213434478841856
> 2019-10-13-105439_モトケンさんはTwitterを使っています：　「@TrafalgarRio　はい、危機管理的観点でまともなことを言ったツイートを見た記憶がないです。」　／.jpg https://t.co/Fdxw22oMsT
▶▶▶　　　　　End　　　　　▶▶▶

　モトケンこと矢部善朗弁護士（京都弁護士会）も検事としての経歴があります。10年ぐらいという情報を見かけたような気がしますが、ずいぶん前のことです。落合洋司弁護士（東京弁護士会）が検事として11年の経験と何度か宣伝をしていた記憶もあり、少し短く感じました。

　落合洋司弁護士（東京弁護士会）は私と同じ昭和39年生まれとなっていますが、確か2月ぐらいの生まれなので学年は一つ上になります。モトケンこと矢部善朗弁護士（京都弁護士会）については、5年ぐらい前かに58歳という年齢を見たように思いますが、記憶も曖昧です。

　今まで気が付かなかったというか深く考えることがなかったようですが、モトケンこと矢部善朗弁護士（京都弁護士会）が検事に任官する前に弁護士をしていたという情報はみておらず、だとすれば30代になってから司法試験に合格したという可能性もあるのかと考えました。

　ホームページに情報があるのか確認をしておきたいと思います。

スタッフ紹介 | 四季の風法律事務所 http://shikinokaze.com/staff/

　1982年10月に司法試験合格、1985年4月検事任官（東京地検検事）と記載がありました。年齢を推定できそうな情報はありません。昭和57年10月に司法試験合格とのことですが、私の同級生が高校を卒業したのが翌年58年の3月でした。

　1998年3月検事退官（岐阜地検三席検事）とありますので、13年ほど検事をしていたことになるようです。これは落合洋司弁護士（東京弁護士会）の11年より長く、私の勘違いがあったようです。

```
矢部 善朗さんの自己紹介
弁護士です。
Vocaloid 大好き。

検事を13年した後、弁護士に。

司法修習３７期
四季の風法律事務所（075-342-3633)

９年間ロースクールの教員（刑事系）をしていましたが、今は、弁護士一本です。

最近、カメラ買いました。でも、写真と撮る暇が不足気味。

［source：］矢部 善朗 | Facebook https://www.facebook.com/yoshirou.yabe
```

　なぜか同じFacebookのアカウントでログインすると、表示がなくなるモトケンこと矢部善朗弁護士（京都弁護士会）の個人名でのFacebookアカウントです。上記に引用しましたが、「９年間ロースクールの教員（刑事系）をしていましたが、今は、弁護士一本です。」とあります。

　司法修習37期というのは、これまで見かけてきた修習期で記録的に思えるぐらい古いものですが、昭和57年の司法試験合格で37期となるようです。57から37を引くと20になるので、昭和20年の司法試験合格が1期となるのかもしれません。戦後数年後から始まっているのかと考えていました。

　インターネットの名誉毀損の刑事事件で懲役刑となれば、弁護士としても失職するのではないかと思いますが、おそらく法律家の歴史として初の足跡になるのではと思います。ある種の記念碑としての記録、位置づけがふさわしい歴史的な人物とは思います。

　モトケンこと矢部善朗弁護士（京都弁護士会）のFacebookには、２つの顔写真があって、アカウントに紐づけされた写真は、Twitterの個人名でのアカウントと同じ写真かと思います。はにかんで笑ったような表情の写真です。

　２つの写真は表情も違っておりますが、同一の人物とは見えません。もう1枚のモトケンこと矢部善朗弁護士（京都弁護士会）の写真ですが、これは10年以上前に創価大学の教員として大学のホームページに掲載されていたものと同じように思います。

　当時は、Twitterではなくブログでの情報発信がほとんどだったモトケンこと矢部善朗弁護士（京都弁護士会）ですが、そこに京都から東京都八王子市の大学に通勤していることなど書いていたことがありました。Twitterも早めには始めていたようですが、それより前のことです。

　一方の小野次郎氏のTwitterのプロフィールですが、1953年生まれ、とあります。私はなにげに昭和53年だと勘違いをしていたかもしれません。生年とは考えずに任官のような情報として取り違えていました。

　1年ほど前か、テレビのバラエティ番組でホリエモンこと堀江貴文氏と対談をしていた元政治家の亀井静氏が、警察庁の長官か何かであったことは印象にありますが、県警の本部長から政治家になったという話は初めて見たように思います。参議院議員など歴任とあります。

　あらためて県警の本部長について考えてみると、以前は週刊誌などに県警本部長の首が飛ぶ、という表現がよく使われていたように思います。実際にどれほどの権限や責任があるのかは不明です。優秀な人物という印象ですが、モトケンこと矢部善朗弁護士（京都弁護士会）がずいぶん小馬鹿にしています。

　小野次郎氏はフォロワー数は1.9万ですが、フォロー数も1.8万となっており、これも認証マークのアカウントとしても珍しい気がしました。独自のポリシーや判断をお持ちという感じです。

　時刻は14時06分ですが、Twitterで一部に障害が起こっているようです。3つ手前の投稿の後、告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)に投稿がされていません。小野次郎氏のツイートをリツイートしようとして気が付きました。

　告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)のアカウントは、ヘッダ写真とプロフィールのアイコン画像も非表示となっています。

　自宅のネット環境で通信障害が起こっていたようです。いきなりネットに接続できないというのは、これまでにもあったことですが、Twitterで一部が表示されないなどという症状から始まってネットの接続ができなくなったというのは今回が初めてと思います。

　まず異変を感じたのが、次の小野次郎氏のツイートに公式引用されているツイートの画像が表示されなかったことです。ダムの放流に関する立て札のような看板の写真です。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜onojiro（小野次郎） 日時：2019-10-13 14:28／2019/10/13 12:43 URL： https://twitter.com/kk_hirono/status/1183253125588586496 https://twitter.com/onojiro/status/1183226792284344323
> 地方は違いますが、私も幼児の頃からこのような掲示板を見て育ちました。 けたたましい警報とサイレンの音は記憶があります。 雨上がりなどにも放流が行われるので、子供だけで河川敷には絶対に近づくなと言われていました。 https://t.co/6xbcIdrBBp
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜rin_earth（rin_earth） 日時：2019-10-13 14:28／2019/10/13 11:57 URL： https://twitter.com/kk_hirono/status/1183253190516457472 https://twitter.com/rin_earth/status/1183215248091701248
> @nanban0025 @onojiro ダム放流警報看板を見た事の無い人が多いようで驚いてます。ダム下流の河川でこんな看板を子供の頃からアチコチで見ております。ダム放流は河川流量・水位を急増させるなんて常識だと思ってましたから。… https://t.co/9AGPdOxa8K
▶▶▶　　　　　End　　　　　▶▶▶

　写真の看板は、ダムの名前の文字がぼやけて判別できないですが「高知県光栄企業局」とダムの管理事務所の隣にあります。奥能登にもいくつかダムはあるのですが、規模が小さいためか放流のことは情報を見たことがありませんでした。

　ダムの放流で被害が出て問題となったのは、2年ほど前のテレビニュースで愛媛県でした。しかし、そのときも放流と増水の危険性については、テレビで詳しい説明がなかったように思います。昨夜は速報としてダムの放流がテレビで繰り返されていましたが、これまでに経験のないことでした。

```
愛媛県を流れる一級河川、肱川の野村ダムと鹿野川ダムの放流後、ダム下流の堤防が決壊し、8名の方が亡くなりました。
　野村ダムと鹿野川ダムは国直轄のダムですが、肱川流域ではさらに支流の河辺川で国が新たに山鳥坂ダム事業を進めています。山鳥坂ダムの完成予定は2026年度です。肱川の治水対策の予算は、その大半が山鳥坂ダム事業に注がれてきましたが、今回の水害はたとえ山鳥坂ダムが完成していたとしても防ぐことはできませんでした。

［source：］野村ダムと鹿野川ダムの放流による肱川の水害（その３） | 八ッ場（やんば）あしたの会 https://yamba-net.org/42746/
```

　記事は昨年、2018年7月23日となっています。少し思い出した気がしますが、同じ頃に北九州市の砂防ダムでイノシシが取り残され、連日テレビで取り上げられていたことがありました。行政の対応や業務の内容についてもいろいろと知ることがあったり、考えさせられる問題でした。

　ブログというよりはホームページのようですが、「八ッ場（やんば）あしたの会」とあります。今朝もこの八ッ場については、Twitterでいろいろと情報を見かけていました。これも何年か前、たまたまテレビで特集を見たことがあり、記憶にあったダムの問題です。

　時期をみると、岡山県で大きな水害があったときかと思いますが、岡山県での被害の大きさでテレビの報道もそちらの方に集中していました。たまたまのタイミングで、愛媛のダムのニュースを見かけたように思います。

　愛媛といえば、阿蘇山の大噴火の可能性を認め原発の差し止めを認めたような判決もニュースにありました。名前をすぐに忘れてしまう弁護士ですが、ピンク色かなにかの派手なスーツを着て、嬉しそうに小躍りでもする感じでテレビに出ていました。河合弁護士だったかもしれません。

　そのときもテレビでは弁護士の名前が出ていなかったかもしれません。数年前からネットで見かけてきた顔だったので私はすぐにわかりました。ホームページが豪勢だったのも印象に残っています。

```
四国電力伊方原発３号機（愛媛県伊方町）の運転差し止めを求め、広島市の住民らが申し立てた仮処分の抗告審で、広島高裁は１３日、運転を差し止める決定をした。直ちに効力を持ち、対象期間は来年９月３０日まで。３号機は定期検査中で、四国電が来年１月に稼働を再開する計画は事実上不可能となり、政府や電力会社の原発再稼働方針には再び大きな打撃となった。

［source：］伊方３号に高裁が停止命令　「阿蘇噴火、火砕流の危険」　広島地裁判断を覆す https://genpatsu.tokyo-np.co.jp/page/detail/631
```

　十分な確認は出来ていないですが、上記のニュースになるのかと思います。記事は2017年12月14日となっています。高裁の判決というのも意外に感じましたが、それも四国ではない広島高裁のようです。

　余り見かけた記憶もないですが、四国の高等裁判所は香川県の高松市だったように思います。全国に３つという高等裁判所の１つです。瀬戸内海の島々を含め愛媛県と広島県が隣接していることは知っていましたが、四国の原発なので、四国の裁判所で出た判決だと思い込んでいました。

　細かいことは憶えていないですが、阿蘇山大噴火の可能性というのは数千年から数万年単位での発生確率とされていたように思います。この可能性の理論を当てはめれば、日本での社会生活が成り立たなくなるとも考えましたが、手放しで喜ぶ弁護士に異常性も感じました。

[link:] » 四国電力（株） 伊方発電所 - Google マップ https://t.co/7aojtMreva

　Googleマップで場所を確認しましたが、Googleマップでは表示が見当たらないものの、佐多岬に位置するものと思います。この佐多岬ですが、たまたま深夜の番組で映像を見たことがありました。番組には四国の他の風景も出ていましたが、不思議なものを感じながらみていました。

[link:] 2018-11-02_021727＿テレビの画面・空中散歩　−　四国・碧（あお）き海と山河を巡る　佐多岬.jpg  http://hirono2014sk.blogspot.com/2018/11/2018110312342018-11-011633312018-11.html#20181102021727

[link:] 2018-10-28_071251＿テレビの画面・サンデーLIVE・イノシシ　ついに決着も・・・ふるさと納税ピンチ？　イノシシ捕獲大作戦　砂防ダム.jpg  http://hirono2014sk.blogspot.com/2018/10/2018102913082018-10-280711152018-10.html#20181028071251

[link:] 2018-10-26_154844＿宇出津新港〜宇出津〜上田町〜宇加塚〜病院〜柳田温泉　笹川、川の上流の砂防ダム（余ノ井川）　上流側.jpg  http://hirono2014sk.blogspot.com/2018/11/2018110117152018-10-231205242018-10.html#20181026154844

　イノシシ捕獲大作戦とありますが、私が記録したものでは同じ問題に対する最後のテレビ放送となっていました。この見出しを見ると、イノシシを救出していなかったことがふるさと納税にマイナス効果を及ぼしていたようです。見た番組ですが、細かくは憶えていません。

```
[1245]  % pp -p|grep 河合
[link:] 2018-07-04_224058＿テレビの画面・報道ステーション・大飯原発の”運転認める”住民側が逆転敗訴　原告側　河合弘之弁護士.jpg  http://hirono2014sk.blogspot.com/2018/07/2018070507552018-07-030532032018-07.html#20180704224058
[link:] 2018-11-25-144151_河合弘之弁護士は依頼人を破産させる　–　アゴラ.jpg  http://hirono2014sk.blogspot.com/2018/12/2018120310082018-11-23-1758012018-11-30.html#20181125144151
[link:] 2018-11-25-144436_全国の反原発派から募金が集まるだろう。河合を初めとする悪徳弁護士がこれまで東電に対する訴訟で巻き上げた金を電力利用者に還元するにはいい機会だ.jpg  http://hirono2014sk.blogspot.com/2018/12/2018120310082018-11-23-1758012018-11-30.html#20181125144436
[link:] 2018-11-25-144524_河合弘之弁護士は依頼人を破産させる　–　アゴラ.jpg  http://hirono2014sk.blogspot.com/2018/12/2018120310082018-11-23-1758012018-11-30.html#20181125144524
[link:] 2018-12-26_191324＿テレビの画面・NEWS７・東電福島第一原発事故　検察官役の弁護士　旧経営陣３人に禁固５年求刑　河合弘之弁護士.jpg  http://hirono2014sk.blogspot.com/2018/12/2018122818422018-12-261044532018-12.html#20181226191324
[link:] 2018-12-26_191331＿テレビの画面・NEWS７・東電福島第一原発事故　検察官役の弁護士　旧経営陣３人に禁固５年求刑　河合弘之弁護士.jpg  http://hirono2014sk.blogspot.com/2018/12/2018122818422018-12-261044532018-12.html#20181226191331
[link:] 2018-12-26_191335＿テレビの画面・NEWS７・東電福島第一原発事故　検察官役の弁護士　旧経営陣３人に禁固５年求刑　河合弘之弁護士.jpg  http://hirono2014sk.blogspot.com/2018/12/2018122818422018-12-261044532018-12.html#20181226191335
[link:] 2018-12-26_191342＿テレビの画面・NEWS７・東電福島第一原発事故　検察官役の弁護士　旧経営陣３人に禁固５年求刑　河合弘之弁護士.jpg  http://hirono2014sk.blogspot.com/2018/12/2018122818422018-12-261044532018-12.html#20181226191342
```

　弁護士現象の記録の成果が発揮できたかと思います。「・NEWS７・東電福島第一原発事故　検察官役の弁護士　旧経営陣３人に禁固５年求刑　河合弘之弁護士」とあるのは、ちょっと記憶にないですが、河合弁護士が指定弁護士の一人だったのか？　インタビューだけ？

　ちょっと糠喜びがあったようです。伊方原発ではなく大飯原発となっていて、それも住民の原告側の逆転敗訴とあります。大飯原発は福井県だったと思うので、控訴審であれば名古屋高裁金沢支部となりそうです。これも記憶がはっきりしていないので確認が必要です。

　やはり名古屋高裁金沢支部で、内藤正之裁判長とテレビに顔が出ている記録もありましたが、同じ石川県に住みながら余り記憶には残っていない裁判長です。名前はほぼ記憶になりですが、顔は見覚えのあるものだとは思いました。

　福井県は全国的にも原発が集中していると聞きますが、ずっと前から原発反対の裁判が多く、控訴審となると決まって名古屋高裁金沢支部がテレビにも出ていました。

　幟に名前があるのかと気がついたのですが、幟旗の横に白地の字幕で「原告側　河合弘之弁護士」とあるようです。シャツが黄色ですが背広は黒のようです。思っていたより高齢に見えますが、右隣の少し奥に僧侶のような人の姿があります。同志ということになるのかと思います。

[link:] » 伊方原発　河合　弁護士 - Google 検索 https://t.co/wqJ09J3bcZ

[link:] » お知らせ │ 河合弘之弁護士監督　映画『日本と原発』『日本と再生』公式サイト https://t.co/UVCMUVQHaX

　検索結果で見つけて驚いたのですが、河合弘之弁護士は、映画監督もしていたようです。映画監督で思い出すのは歌手の「さだまさし」さんで、映画の作成に入れ込みすぎて莫大な借金を抱え込んだと聞きますし、かなり有名な話かと思います。完済もされているようです。

広島高裁：伊方原発３号機の運転差し止め命令 │ 河合弘之弁護士監督　映画『日本と原発』『日本と再生』公式サイト http://www.nihontogenpatsu.com/news/20171213ikata.html

　探していたものが見つかりました。歴史的仮処分決定という下にある写真にピンク色のジャケットと呼んだほうがいいのか、背広にも見える上着を着た河合弘之弁護士の姿があります。通った主張自体も理論がぶっ飛んだものだと思いましたが、このピンクの色の服も相俟って印象的でした。

```
2019/06/27

弁護士であり、映画監督である河合弘之はニューヨーク・タイムズ紙　特集「転換期のリーダー」に取り上げられました。
下記は、その翻訳です。

［source：］お知らせ │ 河合弘之（かわいひろゆき・弁護士）公式サイト http://lawyer-kawai.com/news
```

　本当に映画監督だったようです。企業業務の専門弁護士というイメージが強かったのですが、これは久保利英明弁護士のイメージともそのまま重なっています。

　前にも書いたことがあると思いますが、久保利英明弁護士を知った頃、テレビの特集で見たのが「すき家」の過重労働問題でした。久保利英明弁護士といえば一票の格差の裁判で、隊列を組み姿がど派手なスーツ、ネクタイとともに印象的ですが、隊列に河合弘之弁護士を見た気もするのです。

　途中まで読んだのですが、上記のページには「私はビジネス弁護士として大型の経済事件を担当し、そのほとんどで勝利しました。」から「東京電力福島原発事故（2011年3月11日）が発生しました。私は神が私の首根っこをつかんで私に命令」とまで書いてありました。思いがけぬ発見です。

　最近は見かけないですが、一時期、原発のニュースといえば「ふげん」や「もんじゅ」を見かけることが多く、宗教的な意味や英知が込められているような話を読んだことがありました。

　自然と人間との関わり、ではダムの問題とも共通することが多いように思います。工事に絡む補償や利権の問題なども共通点があるかと思います。昭和40年代になると思いますが、石川県では手取川ダムの問題もテレビで見かけながら育ったという気がします。

　昭和40年代というのは、公害問題が多い時代でもありました。裁判というのはとんでもない長い時間がかかるものというイメージもその頃から植え付けられていたように思いますが、それも弁護士鉄道という歴史の一つに思います。

　まだまとまったかたちで取り上げてはいないと思いますが、その原発問題で名古屋高裁金沢支部の原告勝訴の判決を出し、弁護士となって、刑事裁判の再審請求で再審開始を得た人物がいます。滋賀県での事件で、そもそもが病死であったものを警察官が手柄欲しさに事件にしたような話となっています。

　井戸謙一という名前だったかもしれません。写真を見るたびに頭に思い浮かんでいたのが、なぜか「黄金バット」という古いアニメで、これは実際に見たのかどうかわからないほど古い記憶のものです。逆に言えば、生まれてから初めの方の記憶ということになります。

　もう3週間ほど前になるでしょうか、朝だったと思いますが、初めて黄金バットをGoogleで検索してアニメの動画をみました。最初は「ゴールデンバット」だと勘違いしていたので、タバコの情報ばかり出てきました。黄金バットは正義の味方とのことです。

　黄金バットはもともと紙芝居だったという情報もそのときに見かけましたが、そういえば聞いたような話でした。井戸謙一弁護士の再審請求もまさに劇的なもので、わかりやすく紙芝居のような印象があるのですが、再審請求の決定が出た後に、ずいぶん時間が掛かっているようです。

```
裁判長として、住民基本台帳ネットワークシステム差止等請求事件（金沢地方裁判所平成14年（ワ）第836号等、2005年（平成17年）5月30日判決言い渡し）［2］や、志賀原子力発電所2号原子炉運転差止請求事件（同裁判所平成11年（ワ）第430号、2006年（平成18年）3月24日判決言い渡し）［3］といった著名事件の判決に関与した。

［source：］井戸謙一 - Wikipedia https://ja.wikipedia.org/wiki/%E4%BA%95%E6%88%B8%E8%AC%99%E4%B8%80
```

　これまで名古屋高裁金沢支部の裁判長だったと思い込んできたのですが、金沢地方裁判所の裁判長として「志賀原子力発電所2号原子炉運転差止請求事件（同裁判所平成11年（ワ）第430号、2006年（平成18年）3月24日判決言い渡し）」を出していたようです。

　先日取り上げた高検検事とは違い、高裁の判事は地裁の判事よりはるかに格上というイメージがあったのですが、上告理由でも高裁の判決は地裁の判決とは違う扱いになっていたかと思いますし、地裁の判決を覆すのも高裁です。

```
最高裁判所の判例がない場合に、大審院若しくは上告裁判所たる高等裁判所の判例又は刑事訴訟法施行後の控訴裁判所たる高等裁判所の判例と相反する判断をしたこと（3号）

［source：］上告 - Wikipedia https://ja.wikipedia.org/wiki/%E4%B8%8A%E5%91%8A
```

　確認のため調べたのですが、私の理解が正しくなかったかもしれません。「刑事訴訟法施行後の控訴裁判所たる高等裁判所の判例と相反する判断」というのが私には理解困難です。そのまま読むと現行の控訴審判決が全て対象になりそうな気がします。左にある大審院は、大日本帝国憲法の時代かと。

　私個人の知る範囲ですが、高等裁判所の判例で特別な扱いとなった判例というのは見かけたことがありません。憲法判断を仰ぐのは最高裁とも聞きますし、上告しないで控訴審で確定した判決に憲法判断とされたものをみたことはないです。

　実際に刑事裁判の上告審を2度経験した者としてはっきり言えることは、刑事裁判の上告審はとても簡単です。一方、民事裁判の控訴審は、一審の判決で仮執行宣言が付くことが多いとも何かで見た記憶がありますが、相当馬鹿にならない金額の金銭的負担を強いられ、容易ではなさそうです。

　この仮執行宣言というのも法クラや弁護士のツイートでは見かけたことがありません。裁判の結果などどうでもよく着手金が目当てとも想像できますが、それは事件放置で着手金の返還を求められたり、判決書まで偽造したという弁護士のニュースとも実に噛み合うものです。

　刑事事件の上告審といっても破棄や減刑があったのは2年に1件だけだったという話もあるぐらいです。1件もなかった年が近年にあって、その翌年に郷原信郎弁護士が藤井美濃加茂市長事件の上告審で演説をするYouTubeの動画がありましたが、馬鹿らしくて途中で寝てしまい続きを観てはいません。

[link:] » 判例違反の疑いも顧みずに上告を棄却した最高裁決定は不当 藤井前美濃加茂市長の弁護団が強い抗議を表明 - YouTube https://t.co/yZSUrUhhBE \n 13,420 回視聴•2017/12/26

　馬鹿馬鹿しい郷原信郎弁護士の話に時間を使いたくないので、クリックしながら場面の先送りをしましたが、どこかの事務所の一室で座談会をしているような映像でした。

　私が過去に視聴しながら寝てしまった郷原信郎弁護士のYouTube動画は、住民を集めた集会場のような映像で、雰囲気が民事の集団訴訟の説明会のようでした。リーガルハイというドラマで、似たような場面を観たことがあり、山深い山村ということになっていたかと思います。

[link:] » 美濃加茂　上告 - Google 検索 https://t.co/m0iQm1SPQJ

　Googleの動画検索で、あの住民説明会のような映像がないものかと探したのですが、上告中に再選という情報を見かけました。控訴審中の再選かと思っていたのですが、上告中だったとすれば驚きです。

　この岐阜県美濃加茂市についても調べたことがありますが、能登で一番大きな七尾市よりいくらか人口が多い程度だったと思います。可児市に仕事に行った時、通過していると思うのですが、七尾市に匹敵するような街の大きさがあったとは記憶になく、岐阜市の通勤圏として人口が多いとは考えられます。

　この藤井美濃加茂市長事件は、もともと宇出津が舞台となった金沢セクハラ裁判に似たような印象があり、地元の人の見方や反応にも共通するところがあるようにも感じていました。

　この藤井美濃加茂市長事件は、贈賄者とされた人物が郷原信郎弁護士からすさまじい攻撃を受け、人格すらも破壊された印象がありましたが、たまたま見かけた情報によると、元は地域の病院で経理を任されるような人物ではあったようです。たぶん公立病院だったように思います。

　この藤井美濃加茂市長事件で、もっとも不思議に感じたのは、関心も強くもって漁るようにネットの情報を集めたのに、最高裁で有罪判決が確定した後になって、一審の担当検事が女性で、恋愛感情で被告を不利としたような情報も見かけたことです。この構図は滋賀県の再審請求事件とも似ています。

[link:] » 検察・警察と詐欺師が「タッグ」で創り出した「美濃加茂市長」事件の全貌！「日本版・司法取引制度の導入で同じことが起きる」〜主任弁護人・郷原信郎弁護士に岩上安身が訊く！ 2018.1.12 - YouTube https://t.co/XmfkISnN7b

　7分29秒という短めの動画のようですが、これも時間は極力使いたくなかったので、飛ばし読みをしていました。再生6分34秒という位置ですが、「関口検事は近づいて・・・・親密な関係の男女」と赤字の文字が見えます。大きなスクリーンでパソコンの画面を表示しているようです。

　先日、郷原信郎弁護士が無罪判決を獲得した刑事裁判を調べていると、無罪判決を出した裁判体の3人の裁判官のうち2人が女性のような名前だった気がします。女性の判事は全く珍しくないですが、3人のうち2人が女性というのは初めて見たもので、とても珍しく感じました。

```
採算の悪い工事を、地元業界の責任者という立場上、仕方なく引き受けたら罪に問われた――東京都青梅市が発注した公共工事の指名競争入札で談合があったとして、同市内の土木建設会社「酒井組」の元代表取締役の酒井政修さん（63）が公契約関係競売入札妨害（談合）罪に問われた裁判で、東京地裁立川支部（野口佳子裁判長、鎌田咲子裁判官、荻原惇裁判官）は9月20日、被告人を無罪とする判決を言い渡した。

［source：］無罪・青梅談合事件から見える日本の刑事司法の今(江川紹子) - 個人 - Yahoo!ニュース https://news.yahoo.co.jp/byline/egawashoko/20190920-00143527/
```

　余り記憶に自信が持てなかったのですが、「野口佳子裁判長、鎌田咲子裁判官」という名前は、女性の名前の可能性が極めて高いと思います。絶対ではないかもしれないですが、この名前で男性だとなにかと日常生活にも支障がおきそうです。

　東京都青梅市が発注した公共工事とありますが、昨夜、実在するというありふれた名前の建設会社の社長が、台風19号がんばれ、とツイートしたことで話題となっていました。虚偽の情報が紛れている指摘もありましたが、朝になってから関連した情報は見かけていません。

[link:] » 大山大介の炎上はなりすまし(釣り垢)?大山建設や大山興業の社長を調査! | Pocket of Time https://t.co/YGJlPdwGNX

　常磐自動車道のあおり運転暴行事件で、ガラケーで撮影をしていたという女性のときも、早い段階で情報を見かけ間違った情報である指摘も見かけていたのですが、女性が逮捕されたことで別人であったことが明らかになり、代理人という弁護士がそのあとよくテレビに出ていました。

〈〈〈：Emacs： 2019-10-13（日曜日）17：28 　〈〈〈

