#+TITLE: "大崎事件最高裁決定のような血も涙もない決定ができる最高裁の裁判官・調査官は，何を思い，何を考えているのか"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-09-23 20:50:32 +0900
FILE_NAME: 2019-09-23-205032_大崎事件最高裁決定のような血も涙もない決定ができる最高裁の裁判官・調査官は，何を思い，何を考えているのか.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 鴨志田裕美弁護士,大崎事件,再審請求,最高裁
記事タイトル名の文字数：52　保存ファイル名の文字数：74
#+STARTUP: showeverything


* 大崎事件最高裁決定のような血も涙もない決定ができる最高裁の裁判官・調査官は，何を思い，何を考えているのか
  :LOGBOOK:
  CLOCK: [2019-09-24 火 00:16]--[2019-09-24 火 02:04] =>  1:48
  :END:

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 大崎事件,再審請求,最高裁

〉〉〉　：VSCode： 2019-09-23 23:55:43 　〉〉〉

TW kamo629782（かもん弓（鴨志田 祐美）） 日時： 2019-09-18 12:11 URL： https://twitter.com/kamo629782/status/1174159033378340865
> 本日付西日本新聞２面のコラム「風向計」。 \n  \n 大崎事件最高裁決定のような血も涙もない決定ができる最高裁の裁判官・調査官は，何を思い，何を考えているのか。 \n 私たちは「分厚い秘密の壁」に阻まれ，知ることができません。 \n  \n 本当にそれでいい… https://t.co/AwodTwEK57

TW kamo629782（かもん弓（鴨志田 祐美）） 日時： 2019-09-17 18:02 URL： https://twitter.com/kamo629782/status/1173885003710644224
> ...ということで、ぜひお読み下さい！ https://t.co/gPi0Vsp9zF

　あと１分で日付が変わり９月２４日になるところです。今日は１６時３０分頃になってようやく目的としていたVSCodeでのツイートとしての投稿と日付情報の挿入が出来るようになりました。朝方まで起きていて、９時過ぎには起きて、そこからも取り組んでいました。

　日中は台風の通過があって風が強かったものの天気はよく、夕方の早い時間には強かった風もおさまっていきました。３日ほど前から能登半島を直撃するという予想で気にかけていたのですが、何事もなく通り過ぎて本当に良かったです。九州の方では竜巻などの被害もあったようです。

　ここ数日はテレビをつける時間も少なく、パソコンの設定やプログラムに没頭していたのですが、ようやく一息ついて、午後からは久しぶりにテレビもつけっぱなしです。そんな中で、これも数日ぶりに鴨志田裕美弁護士のタイムラインをみて、気になり考えさせられるツイートが目に入りました。

〈〈〈　：VSCode： 2019-09-24 00:11:04 　〈〈〈

〉〉〉：Emacs： 2019-09-24（火曜日）00：16　 〉〉〉

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kamo629782（かもん弓（鴨志田 祐美）） 日時：2019-09-24 00:27／2019/09/17 18:02 URL： https://twitter.com/kk_hirono/status/1176156012773949440 https://twitter.com/kamo629782/status/1173885003710644224
> ...ということで、ぜひお読み下さい！ https://t.co/gPi0Vsp9zF
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kamo629782（かもん弓（鴨志田 祐美）） 日時：2019-09-24 00:26／2019/09/18 12:11 URL： https://twitter.com/kk_hirono/status/1176155989365542912 https://twitter.com/kamo629782/status/1174159033378340865
> 本日付西日本新聞２面のコラム「風向計」。  大崎事件最高裁決定のような血も涙もない決定ができる最高裁の裁判官・調査官は，何を思い，何を考えているのか。 私たちは「分厚い秘密の壁」に阻まれ，知ることができません。  本当にそれでいい… https://t.co/AwodTwEK57
▶▶▶　　　　　End　　　　　▶▶▶

　告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)のアカウントでロックが掛かっていました。１０日ほど前にも同じことがあったのですが、投稿数が少なくなってからロックがかかるようになりました。

　本人確認のため一時的にロックしています、というようなメッセージでしたが３年ぐらい前まではちょくちょくとありました。ここ数日、投稿数も少なかったのが、急に頻度があがったので、不正の可能性があると判断されたのかもしれません。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-09-24 00:39／2019/09/24 00:38 URL： https://twitter.com/kk_hirono/status/1176159223148793858 https://twitter.com/hirono_hideki/status/1176158954084110337
> 2019年09月23日20時35分の登録： ％@1961kumachin　中村元弥％「自由と正義」に同封されている委員会ニュース。今月は巻頭の大崎事件最高裁決定に対する怒りに震える鴨志田祐美先生の文章だけでも読みま https://t.co/SN8tIR1JPI
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-09-24 00:39／2019/09/24 00:38 URL： https://twitter.com/kk_hirono/status/1176159183130906624 https://twitter.com/hirono_hideki/status/1176158927718768640
> 2019年09月23日20時33分の登録： ＼かもん弓（鴨志田 祐美）　@kamo629782＼本日付西日本新聞２面のコラム「風向計」。\n\n大崎事件最高裁決定のような血も涙もない決定ができる最高裁の裁判官・調査官は https://t.co/GNNAAasSDb
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-24 00:38／2019/09/24 00:34 URL： https://twitter.com/kk_hirono/status/1176158963227750400 https://twitter.com/s_hirono/status/1176158005202542592
> 2019-09-24-003426_最高裁調査官への信書　大崎事件　中島　邦之｜【西日本新聞ニュース】.jpg https://t.co/NjWHxZVjDX
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-24 00:38／2019/09/23 21:33 URL： https://twitter.com/kk_hirono/status/1176158942688235520 https://twitter.com/s_hirono/status/1176112395128733697
> 2019-09-23-203404_かもん弓（鴨志田祐美）@kamo629782·9月17日。。。ということで、ぜひお読み下さい！.jpg https://t.co/ATAqipeD95
▶▶▶　　　　　End　　　　　▶▶▶

　中村元弥弁護士の引用ツイートも気になったのですが、ここ数日は中村元弥弁護士のTwitterのタイムラインも余り見てはいませんでした。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜1961kumachin（中村元弥） 日時：2019-09-24 00:43／2019/09/17 11:16 URL： https://twitter.com/kk_hirono/status/1176160215768518656 https://twitter.com/1961kumachin/status/1173782845828894720
> 「自由と正義」に同封されている委員会ニュース。今月は巻頭の大崎事件最高裁決定に対する怒りに震える鴨志田祐美先生の文章だけでも読みましょう。死亡時期についての不意打ちなど、本当にヒドイ決定で、最高裁の方がよほど著しく正義に反するぜ！！
▶▶▶　　　　　End　　　　　▶▶▶

　中村元弥弁護士の引用ツイートというのは私の勘違いで、実際はその逆、中村元弥弁護士のツイートを鴨志田裕美弁護士がURLの引用をしたものでした。「死亡時期についての不意打ち」というのはちょっと理解が出来ませんが、決定的な最高裁批判としては十分に理解ができます。

　鴨志田裕美弁護士が引用した西日本新聞の記事ですが、まだ読んではおらず今から読むところです。数日前にもどこかの弁護士会が大崎事件の批判声明を出したと鴨志田裕美弁護士がツイートをしていましたが、確か６月２５日に出て翌日に報道された決定のニュースがなぜ今頃の声明となるのか疑問でした。

最高裁調査官への信書　大崎事件　中島 邦之｜【西日本新聞ニュース】 https://t.co/RViJanIVl2

<hr />

```
2019/9/18 10：30 (2019/9/19 17：36 更新)
西日本新聞 オピニオン面
Facebook
Twitter

　「人権救済の最後の砦（とりで）」とも例えられる最高裁判所に、調査官と呼ばれる人たちがいることをご存じだろうか。

【関連】「再審制度 今こそ改正を」　松橋、大崎事件の弁護士ら訴え　熊本市

　その役割を、元最高裁調査官の渡部保夫氏が著書「刑事裁判ものがたり」で紹介している。全国の地裁や高裁で実務経験を積んだ裁判官約30人が担う。下級審の裁判記録や上告趣意書などを読み込んで調査報告書にまとめ、裁判官に提出。裁判官は報告書に拘束される必要はないが、これを参考に判断する。

　1979年から5年間、同調査官だった木谷明氏も著書で「判決文の原案も調査官が作る」と説明。調査官は裁判官の補助者として、司法の最高府の判断に相当な影響力を持つ黒子的存在といえる。

［source：］最高裁調査官への信書　大崎事件　中島 邦之｜【西日本新聞ニュース】 https://www.nishinippon.co.jp/item/n/544039/
```
```
その調査官が近年、弁護人と距離を置き面談に応じなくなった、という嘆きを弁護士たちから聞いた。鹿児島県大崎町で79年、男性の変死体が見つかった大崎事件弁護団の鴨志田祐美弁護士は、やむなく、最高裁決定が出る2カ月前の今年4月、担当調査官宛てに信書を送った。本人の了解を得て内容を紹介する。

　「鹿児島地裁が原口アヤ子さんに殺人罪などで有罪判決を出したのは39年前。桜をめでる季節が40回も巡ってきたのに、彼女はそれを見上げることもないまま無実を叫び続ける日々を送っています」

　「今年1月、突然脈拍が30台に落ち、血圧も50台までに下がり、モニター監視される深刻な状態となりました。これほどの長い期間を待たせ続けたことの罪深さを、私たちは思い知らされました」

　「もはや弁護人、裁判官、調査官という肩書を超え、52歳から（92歳の）今日まで無実を訴え続けてきた女性の人生のフィナーレに、人としてどう向き合うかを考えるべき時ではないでしょうか」

［source：］最高裁調査官への信書　大崎事件　中島 邦之｜【西日本新聞ニュース】 https://www.nishinippon.co.jp/item/n/544039/
```

　上記に２箇所記事の引用をしました。最高裁の調査官については、早い段階、今から２０年以上前にたまたま見た本で知ったように思いますが、事実上、最高裁で事件を判断し処理をしていると知っていました。その後に２回ぐらい同じような情報をネット、Twitterで見かけたようには思います。

　私が最高裁に関心を持ったのは、上告審に継続したという事実以上に、市場急配センターのKKさんの存在がありました。これは告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)で３ヶ月ほど前にも取り上げていると思います。

　父親が最高裁の判事で、その判事の父親が竹沢俊寿会長の友人で、社会勉強のために金沢市場輸送でトラック運転手の仕事を始めたという話でしたが、その前は石川県警察の白バイ隊員で機動隊に所属していたといい。群馬県渋川市の近くに実家があり、家には大きな梅園があるとも話していました。

　宇出津には関越道のバス事故で母親を亡くし、それが縁で群馬県警察の白バイ隊員になったという人がいて、新聞やテレビの特集でも見かけていたのですが、改めてそのことを思い出しました。父親は２つ年下だったように思います。少しですが仕事で一緒になった時期もありました。

「事故を一件でも減らしたい」遺族が群馬県警白バイ隊員に　関越道バス事故7年 - 毎日新聞 https://t.co/H1g9EPmMX3

<hr />

　「会員限定有料記事　毎日新聞2019年4月28日 21時01分(最終更新 4月28日 21時34分)」となっています。ちょうどその頃だったと思いますが、銭湯の脱衣所に入ったタイミングでニュースの特集が始まったように思います。

　群馬県で関越自動車道といえば、沼田インター付近の陸橋から飛び降り自殺をしたという能登町松波の人のことについても久しぶりに思い出しました。能登町新保の出身で金沢市場輸送で運転手をしていたKOから聞いた話でした。

　松波も新保も以前は珠洲郡内浦町になりますが、新保の運転手は小木中学校を選択して通ったという話でした。小木港の遠洋漁船の仕事をしていたと聞きますが、年は私の一つ上の学年で、自殺したという人と同学年になります。私が名前など少し知っていたのは相撲部の有力選手だったからです。

　上記の西日本新聞の記事には木谷明弁護士が1979年から5年間、最高裁の調査官をしていたという話がありますが、これは初めて知った話のように感じました。そういえば4,5日前に郷原信郎弁護士が無罪判決を獲得したという話をTwitterで少し見かけていました。

　藤井美濃加茂市長事件の上告審で、郷原信郎弁護士の弁護団に参加した著名な弁護士が、最高裁の調査官であったという話は、その弁護団会議のようなYouTubeの動画で見て知っていました。このところツイートを見かけていないですが、ミカンの顔のアイコン弁護士も同席していました。

　前に少し触れていると思いますが、同じ銭湯の浴場からあがる前、風呂道具を片付けに脱衣所に入ったタイミングで、テレビに木谷明弁護士の姿を見て、それから結構長い時間、特集に見入ったということがありました。恵庭OL殺人事件などです。。報道特集だったと思います。

　木谷明弁護士といえば、碁の世界で知られた木谷一門の息子という話ですが、数日前、Facebookがオープンソースで公開しているという囲碁ソフトのインストールをやっていて、これも数日がかりになりましたが、最終的にGPUのドライバが入っていないということで断念をしました。

　Linuxの環境でのみ配布されている囲碁ソフトで、久しぶりにmakeコマンドでコンパイルなどやったのですが、GPUのドライバが必須となっているようなので断念し、ネットで調べたところ100万円から350万円以上の製品がその囲碁ソフトに使われていると知って非常に驚きました。

　GPUというのはビデオカードで高画質の描画を行うものという固定観念があったので、囲碁のソフトとはイメージがつながらなかったのですが、それだけ高度な計算処理を行い、コンピューター対人間の頭脳戦をやっているのだと想像すると、なんとなく理解はできました。

　高度な情報処理ということになりますが、最近もモトケンこと矢部善朗弁護士（京都弁護士会）のツイートで、法律の専門家である弁護士は膨大で高度な判断の処理過程を経て発言をしているということを強調していました。私が囲碁ソフトに取り組んでいたのと同じ頃かと思います。

　「全国の地裁や高裁で実務経験を積んだ裁判官約30人が担う。」と上記の西日本新聞の記事にありましたが、この最高裁調査官の人数というのは全く初めて知ったもので、第一印象はずいぶんと少ないのだと驚きました。

　7月中になるかと思いますが、名前を思い出せない、いや思い出した海渡雄一弁護士のFacebookの記事で、具体的な数値として上告審の係属事件数を知りました。そちらもずいぶん多いと意外な情報でしたが、金沢刑務所の拘置所にいたときの経験でも居房に札のある割合はけっこうなものでした。

　最高裁の判事の数というのもニュースや話題を見ることがないので、知らない人が多そうですが、３つの少法廷と大法廷をあわせて15人ということで、これは私の知る限り、変わったことのない人数かと思います。

　調査官の数が30人ということは、ちょうど最高裁判事の15人という数の2倍になりますが、それで日本全国の上告審を受け持ち、刑事事件も民事裁判も、行政裁判も同じになるのかとおもいますが、その数でまともに対応できるのかと考えるのが、非現実的に思えてきます。

　郷原信郎弁護士の美濃加茂市長事件の上告審があった前年、刑事裁判の上告審で無罪方向の自判や差し戻しは０だったという情報を見ています。美濃加茂市長事件の上告審がなければ知ることのなかった情報かもしれません。

　私の知る範囲になりますが、刑事裁判の上告審で無罪や減刑方向に破棄されたのは２件で、１つは平成６年頃に殺人百科か事件百景という文庫本で見たものでしたが、２件目も刑裁サイ太のツイートで知ったものも、どちらも世間に全く注目を浴びないような刑事事件でした。

　それだけに大崎事件の最高裁の決定は大きなものを感じました。私が知らないだけで最高裁が出した無罪や減刑の判決や決定というのは他にもあるのかもしれないですが、ずいぶんと踏み込んだ内容で具体的な指摘をしたというのも、大崎事件の再審請求における最高裁の決定でした。

　いずれ踏み込んで取り上げておきたいとは考えてきたのですが、その大崎事件の最高裁決定は、図書館で読売新聞、朝日新聞、毎日新聞、日本経済新聞、北陸中日新聞とすべての記事に目を通しました。まったく取り上げていないように見えたのが北國新聞でもありました。

〈〈〈：Emacs： 2019-09-24（火曜日）02：04 　〈〈〈

