#+TITLE: "沢尻エリカの薬物事件で弁護人になったという河津博史弁護士"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-11-20 14:30:12 +0900
FILE_NAME: 2019-11-20-143012_沢尻エリカの薬物事件で弁護人になったという河津博史弁護士.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 河津博史弁護士,薬物事件
記事タイトル名の文字数：28　保存ファイル名の文字数：50
#+STARTUP: showeverything


* テレビで「次世代の支柱」とも紹介されていた高野隆弁護士、弘中惇一郎弁護士との関係：沢尻エリカの薬物事件で弁護人になったという河津博史弁護士
  CLOCK: [2019-11-20 水 14:34]--[2019-11-20 水 18:30] =>  3:56

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 河津博史弁護士,薬物事件,高野隆弁護士,弘中惇一郎弁護士,郵便料金不正事件

〉〉〉：Emacs： 2019-11-20（水曜日）14：34　 〉〉〉

　あとでテレビ画面をスマホで撮影したファイルで確認をする予定ですが、河津博史弁護士の沢尻エリカの弁護人就任は、情報番組グッディの始まりで知ったのが最初だったと思います。同じチャンネルのバイキングでも取り上げていましたが、そのときはなかったと思います。

　今日も朝はテレビをつけておらず、11時50分に近くなってからつけ、そこに石川県内ニュースが始まっていたように思います。2つ目にみたのが幼稚園児の石川テレビ放送局の訪問で、金沢市寺中町の幼稚園と聞こえましたが、前にも2回ほど寺中町の幼稚園とテレビで聞いたことがありました。

　金沢市の寺中町は範囲が広くなかったと思いますが、中西運輸商の事務所が金石街道沿いにあった場所で、そのまま金石方面に百メートルぐらい行くと金沢西警察署があったと思います。金沢西警察署の場所はほぼ同じですが、平成9年頃には新しい建物になっていました。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「次世代の」の検索結果 - Twilog https://t.co/z6bidIPa6K

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2019年04月07日 - Twilog https://t.co/wfyBu2TuyS

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-20 14:48／2019/04/07 11:12 URL： https://twitter.com/kk_hirono/status/1197028941669683200 https://twitter.com/hirono_hideki/status/1114712403269132289
> 「父殺しの女性」を救った日本初の法令違憲判決 (5ページ目)：日経ビジネス電子版 https://t.co/5iBGGe2Ah9 　「それだけじゃなく、刑法200条が違憲無効になったからだよ。そのおかげであの条文に苦しめられた人たちも救えた」
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-20 14:48／2019/04/07 14:03 URL： https://twitter.com/kk_hirono/status/1197028829090287616 https://twitter.com/hirono_hideki/status/1114755664029585409
> 性的虐待の父親を無罪にした鵜飼裕充裁判長、他にも意味不明な無罪判決ばかり出していた - Togetter https://t.co/Hgx879hamA
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-20 14:47／2019/04/07 14:10 URL： https://twitter.com/kk_hirono/status/1197028769703186432 https://twitter.com/hirono_hideki/status/1114757372361170944
> 【コラム 江川紹子】藤井美濃加茂市長収賄容疑事件:法を軽んじる裁判長に藤井市長を裁く資格はあるか | 財経新聞 https://t.co/0JHLSzB0Ty 閉廷後の法廷で、私はあっけにとられていた。それは、藤井浩人・美濃加茂市… https://t.co/siVDThfJnk
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-20 14:47／2019/04/07 14:14 URL： https://twitter.com/kk_hirono/status/1197028591000645632 https://twitter.com/hirono_hideki/status/1114758321385246722
> ツイート数：2 リツイート数：0 トータル：3 河津博史 ajx-all-user-mysql-REGEXP_blogger_hirono2014sk.rb "河津博史"
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-11-20 14:47／2019/04/07 14:16 URL： https://twitter.com/kk_hirono/status/1197028553105108992 https://twitter.com/hirono_hideki/status/1114758755785166848
> 弁護士　次世代の支柱 - Google 検索 https://t.co/bABW6DTF8u
▶▶▶　　　　　End　　　　　▶▶▶

　余りはっきりしたかたちで記録は残していなかったようですが、同じ日に「「父殺しの女性」を救った日本初の法令違憲判決」という記事を見つけ、読んでいた可能性がありそうです。印象的な記事でしたが、気になりながら読んだ時期については思い出せず、見つけるのも難しいと思っていました。

　静岡県だったと思いますが、テレビで河津桜というのをみて、それからしばらくした頃に河津博史弁護士のことを知ったと思うので、個人的には独自の印象がありますが、ネットで調べても人なりを確認できるような情報はなく、ばやけた印象が続いています。

　私が子供の頃から少年時代は、なにかと「清水次郎長一家」を見聞きする機会があり、馴染み深かったとも思います。「森の石松」という子分の異名もありましたが、これは時代劇の盗賊団でもよくみかけたもので、たまたま見かけた書物では、東海道に盗賊が多かったという印象もあります。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜MSumeragi（sumeragi.m.t.🌺肉球新党） 日時：2019-11-20 14:59／2019/03/09 10:15 URL： https://twitter.com/kk_hirono/status/1197031712699469824 https://twitter.com/MSumeragi/status/1104188830737817600
> #上田晋也のサタデージャーナル カルロス・ゴーン被告 まさかの「変装」保釈  スゴ腕「最強弁護団」勝算は？ 弘中惇一郎(73) 「無罪請負人」 「カミソリ弘中」 高野　隆(62) 「刑事弁護界のレジェンド」 「保釈の神様」 河津博… https://t.co/FwiAkn4jc5
▶▶▶　　　　　End　　　　　▶▶▶

　上記は当日に奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)でリツイートしていたツイートになりますが、無罪請負人、カミソリ弘中、高野隆弁護士の刑事弁護界のレジェント、とともに河津博史弁護士（４６）に、次世代の支柱、弘中氏の右腕、とあります。

　昭和40年代は旅芸人のような一座の公演も身近なものとして記憶にあります。昭和50年代もずいぶんと多くの時代劇がテレビドラマになっていました。最近はテレビのドラマ自体が少なくなっている気がしますが、ネットもその前のテレビゲームもなかった時代のことです。

　ずいぶん前から高野隆弁護士については、旅芸人の座長というイメージが強くあるのですが、これは中村元弥弁護士のツイートを見たことも大きく影響していると思いますし、記録もいくつか残していることと思います。

　一座という言葉は今では見かけないように思いますが、昭和の時代はポスターで見かけることも多かったように思います。特に印象に残るのは、動物園と一緒になっていた金沢市卯辰山の金沢ヘルスセンターです。演劇を見た記憶はないですが、独自の雰囲気がありました。

　一座は劇団に似ていると思いますが、裁判員裁判に力を入れ、法廷技術などを伝授しているのも高野隆弁護士ですし、姫路市で審理日数が最長という記録も樹立しています。どれだけ公費や、他に適正、公正な裁判を受ける権利に悪影響を及ぼしているのか個人的な関心事ですが、問題の声はみかけません。

　昼過ぎにバイキングでみたのが最初だったと思いますが、沢尻エリカ容疑者に薬物反応が出ずシロだったという報道が出ていました。そのあとの詳しいテレビの報道では、４つほどの薬物の名称を並べて、その全てで反応が出なかったと解説をしていました。

　科捜研のようなところの鑑定結果だと思いますが、そのような鑑定が弁護士らによって大きな問題とされ、控訴審で逆転の無罪判決となった強姦事件が鹿児島市内でありました。いくつか気になるところのある事件でしたが、被害者とされた女性に、弁護士らが慈悲を示していたのが特に強烈です。

　テレビでも特集があって、NHKのEテレだったと思いますが、その放送を事前に知ることができたのも中村元弥弁護士のツイートだったと記憶にあります。無罪となった元被告人が、錦江湾で船から真鯛を釣り上げ、晴れ晴れしい笑顔だったのも印象的な場面でした。

　警察の科学鑑定に弁護士らが大きな疑惑を投げかけた刑事裁判で、私はネット上のあらゆる情報を漁るぐらいに調べたのですが、それほど簡潔でもなかったテレビの報道とは、ずいぶんと印象や認識が変わる事実関係が含まれていました。

　被害者は少女で、深夜の繁華街での強姦事件、私はテレビの報道で夜の水商売の母親の仕事終わりを待って、ご飯や小遣いをせびりに来た素行のよくない少女を想像し、不良仲間の悪知恵で強姦被害をでっち上げた可能性まで一つの可能性として想像しました。

　とても参考になるところの大きな刑事事件、刑事裁判なので、この続きは独立したエントリーとして記録をしておきたいと思います。時期も近かったと思いますが、この鹿児島の強姦無罪事件と、似た問題点があると感じたのが大阪の強姦再審無罪事件でした。

　大阪の強姦再審無罪事件は医師の診断の内容が違っていたと思いますが、鹿児島の強姦無罪事件では、被疑者とは別の男性の精液が被害者の体内から検出されたとされ、それが逆転無罪判決の決め手ともなったようです。

　それと、私としてはこれまで見てきた情報を総合し、高野隆弁護士の一番弟子という印象の強い趙誠峰弁護士ですが、今年の2月頃に無罪判決が出たと記憶にある乳腺外科医のわいせつ事件に名前がありました。これは高野隆弁護士も弁護団に参加をしていたようです。

　細かく正確なことは現在の記憶で断定はできないですが、乳腺外科医のわいせつ事件の無罪判決で、検察が控訴したというニュースがあった前後に、大鶴基成弁護士の退任と、高野隆弁護士と弘中惇一郎弁護士の弁護人就任のニュースがあって、そこに河津博史弁護士の名前もあったのだと思います。

　時間が経つにつれて記憶も曖昧になりますし、ネット上の情報も新たな事件・裁判の報道で埋もれた落ち葉のような状態になるとも考えます。Wikipediaが一つの参考になりますが、情報をひとまとめにし、参照をしやすくしておきたいという思いと必要性を新たにしました。

　時刻は11時52分です。ちょっと前のテレビで思い出したのですが、昼前にテレビをつけたタイミングで見たのは、輪島市の輪島前神社の恵比須講のニュースでした。

```
地元の漁師たちによりますと、ことしは巻き網漁のアジやサバは豊漁だったものの、能登半島沖の「大和堆」などで漁を行う中型イカ釣り漁船は、違法操業を行う外国の漁船の影響で不漁だったということです。
中型イカ釣り漁船を所有する「輪島漁業生産組合」の宮下新市組合長は「ことしは『大和堆』での漁が不漁だったので、来年こそはスルメイカが捕れてほしい」と話していました。
来年１月１０日には、恵比須様を海へと送り出す「おでまし恵比須」が行われます。

［source：］輪島で「お帰り恵比須」漁に感謝｜NHK 石川県のニュース https://www3.nhk.or.jp/lnews/kanazawa/20191120/3020003297.html
```

　昼前にテレビで見たときも気になっていたのですが、スルメイカ漁の地元漁師の話がありました。輪島市でも大和堆でのスルメイカ漁の操業を行っているようですが、距離的にも大和堆から近いはずの輪島市で話題を見たことがなく、電気を沢山つけたイカ釣り船も、輪島港では見ていなかった気がします。

　電気を沢山つけたイカ釣り船は、地元の宇出津港でも見かけていますが、たまにテストなのか電灯をつけているのをみると、夜でも日中のようなものすごい明るさで、目立つ船です。輪島港は宇出津港とは比較にならず漁船の数が多いので、たまたま見かけていなかったのかもしれないです。

　石川県でのスルメイカ漁は6月頃に集中していました。長くて一月もなかったように思いますが、金沢市場輸送でその時期は連日のように金沢港にスルメイカを積みに行っていました。もちろん生のスルメイカです。

　大和堆での北朝鮮の不法創業問題で決まってテレビニュースにみるのが、宇出津と同じ能登町となっている小木港ですが、大和堆に操業に行く中型イカ釣り漁船は、冷凍設備を備えたもので急速冷凍で「船凍イカ」と呼ばれています。輪島港では見ない船です。

　記事をよく読むと「中型イカ釣り漁船を所有する「輪島漁業生産組合」の宮下新市組合長は「ことしは『大和堆』での漁が不漁だったので、来年こそはスルメイカが捕れてほしい」」とありました。イカ漁の話は聞いたことがなかったですが、輪島丸船団になるのかもしれません。

　そういえば、今年は今のところ北朝鮮と思われるハングル文字の漁船の漂着というニュースは見ていないように思います。ここ最近も大気が不安定で強い風が吹き、海も荒れていたようです。高波で田の浦、羽根間という宇出津から小木に向かう主要道の通行止めもありました。

　時刻は16時23分です。今日はずいぶん久しぶりに石川テレビのままチャンネルも変えずに、再放送と思われる刑事ドラマをつけているのですが、婦警役の女優の名前も顔もわからず、ちょっと気になるとともに、昨日のタピオカ店とトラブルになった女性タレントのことを思い出しました。

　女性タレントの名前も思い出せないですが、今日はまったく話題を見ていないようで、一日でずいぶんと変わるものだと思いました。弘中惇一郎弁護士の記者会見もニュースで少し見ましたが、情報番組が取り上げるのは見ていないものの、弁護団の入れ込みが強く伝わるニュースでした。

[link:] » ゴーン　弁護団 - Google 検索 https://t.co/3ydJqndcvz

```
日産自動車の前会長カルロス・ゴーン被告（６５）が東京地検特捜部に逮捕されてから１９日で１年になることを受け、前会長の弁護団が声明を公表した。「ゴーン氏は無実。真実に反する嫌疑に断固として対抗する」と改めて訴えた。

　弁護団は声明で、逮捕後の長期間にわたる身柄拘束や保釈後の妻との接触禁止などによって、「公正な裁判を受ける権利が侵害されてきた」と指摘。前会長が「人質司法の犠牲となっている」と訴えた。

　そのうえで、前会長に対する「不適正で違法な捜査は経済産業省や日産関係者が関与して行われ、ゴーン氏が２０年にわたり身を捧げてきた日産に回復不能な損害を与えた」と指摘。それでも「ゴーン氏の決意が揺らぐことはなく、無実であり、潔白を証明して家族と再会する機会を心待ちにしている」とした。

［source：］「ゴーン氏は人質司法の犠牲」　逮捕１年、弁護団が声明：朝日新聞デジタル https://www.asahi.com/articles/ASMCL6CQDMCLUTIL047.html
```

　上記に引用をした朝日新聞の記事は、11月19日7時0分が配信時刻のようです。未明や明け方に記者会見を行うはずもなく前日の18日と思ったのですが、写真の下に、ゴーン前会長の主張などを説明する弁護団、11月11日午後1時ごろ、東京都千代田区、とありました。

　記事の本文には、「１９日で１年になることを受け、前会長の弁護団が声明を公表した」とあるので、あるいは11日の記者会見で取材したものを、ちょうどカルロス・ゴーン氏の逮捕から1年目となる昨日の19日を選んで、記事として配信をしたという可能性もありそうです。

```
ゴーン被告は今年４月、４回目の起訴後に保釈が認められた。ただ、東京地裁は保釈条件として妻キャロルさんとの面会を禁止しており、声明はこの点も批判。「ゴーン氏は潔白を証明し、家族と再会するのを心待ちにしている」と結んだ。ゴーン被告の初公判は来春にも開かれる見込みで、現在は地裁で争点整理が続いている。

［source：］逮捕１年「真実に反する」　ゴーン前会長弁護団が声明 - 産経ニュース https://www.sankei.com/affairs/news/191119/afr1911190008-n1.html
```

　上記の産経新聞のニュースも、11日午後1時頃という弘中惇一郎弁護士ら弁護団の記者会見を、昨日の午前7時32分に記事として配信したようです。朝日新聞と足並みを揃えていますが、8日後のニュースにこだわったのは、弁護団の要請や、あるいは取材の条件であることが窺えます。

　昨夜のニュースzeroだったでしょうか、1年目とかいいながらこの日産のニュースを取り上げていましたが、内容は新社長や新体制に関するもので、カルロス・ゴーン氏のことは丸っきり触れていなかったように思います。この辺りも記憶の曖昧さをなくすためスマホで撮影をしています。

```
会社法違反（特別背任）などで起訴された日産の前会長カルロス・ゴーン被告（65）の弁護団の弘中惇一郎弁護士（74）河津博史弁護士、小佐々奨弁護士が11日、都内の日本外国特派員協会で会見を開いた。弘中弁護士は「ゴーンさんが無罪であることを確信しているが、逮捕、起訴は、ゴーンさんを追い出すために日産がたくらみ、検察が行った違法なもの。裁判自体が無効でゴーンさんを開放すべき」と主張した。

［source：］ゴーン氏弁護団「日産が追い出し企む」不当逮捕主張 - 社会 ： 日刊スポーツ https://www.nikkansports.com/general/nikkan/news/201911110000271.html
```

　同じGoogleの検索結果で見つけた上記のニュース記事も、11月11日の記者会見を取り上げていますが、配信時刻が当日14時19分となっています。これは日刊スポーツの記事となっていますが、これを見てあの「日本外国特派員協会」の記者会見だったのだと初めて知りました。

　やはり記者会見の写真で弘中惇一郎弁護士の隣の席にいるのは河津博史弁護士のようです。記事にはもう一つ弁護士の名前があって「小佐々奨弁護士」とありますが、「こささ」と読むのか初めて見るような珍しい名前です。

　時刻は16時56分です。テレビで、富山の氷見港の寒ブリ宣言があって、遅めと思ったのですが、11日早いという説明がありました。去年より、と言っていたように思います。近年は11月に宇出津港で寒ブリがまとまって水揚げされたというニュースを見ていたように思います。

　テレビで見る寒ブリの回遊ルートでは、氷見港の方から七尾港、宇出津港とまわってくるようなので氷見が先になるのかと思いますが、水温で富山湾を回遊せず、山陰の方で豊漁になったというニュースも3年ほど前にあって、不漁で宇出津の寒ブリまつりが中止になったのもその時かもしれないです。

　氷見港が寒ブリで全国的に有名になったのもここ数年のことかと思いますが、個体差以外に能登と違いがあるのかと考えますが、氷見の方はブランド化にも成功し、ずいぶん値段が違うように聞いたことがあります。

　それ以上に気になっていたのが、石川県の加能ガニと福井の越前ガニ、鳥取県の松葉ガニの価格差ですが、今年は具体的にどれほどの価格差があるのか知ることが出来ました。大きさの違いが大きいのかと思っていたのですが、そうではなさそうでした。価格差はとても大きいはずです。

　そういえば、香箱ガニもまだ食べていませんでした。解禁の翌日で580円になっていましたが、ずいぶんと小さなカニで買って食べようという気にはならなかったです。以前は、398円か293円だったのですが、北陸新幹線の開業から値段が高くなり、サイズも小さくなったと思います。

[link:] » 河津博史弁護士 - Google 検索 https://t.co/rJCFyW8AYF

　検索結果を見て少し驚いたのですが、河津博史弁護士の所属は「霞ヶ関総合法律事務所」という名前のようです。霞ヶ関といえば有名な官庁街ですが、これを法律事務所にしたものは、これまで目にしなかったと思います。河津博史弁護士の検索は春にも行っているはずです。

[link:] » 霞ヶ関総合法律事務所（東京都港区｜法律事務所｜弁護士） | 霞ヶ関総合法律事務所（東京都港区｜法律事務所｜弁護士） https://t.co/oeEvd89Rfz

　フェードで切り替わりのある画像が浮き出てくるのかと思ったのですが、何も表示はされず、空白の広めのスペースがデザインとなっているようです。リンクの項目も、事務所概要、取扱業務、弁護士紹介、お知らせの４つで、下に住所と電話番号のある実にシンプルなものです。

　弁護士紹介のページは、9人の弁護士の名前がありますが、これもとてもシンプルです。個々の弁護士名がリンクになっているようなので、そちらに詳細があるのかもしれません。河津博史弁護士以外の名前は、見覚えのないものばかりです。このページに代表者や所長も不明です。

[link:] » 河津 博史 | 霞ヶ関総合法律事務所（東京都港区｜法律事務所｜弁護士） https://t.co/vaXAM7nJ67

　飾りがなくとてもシンプルなのは同じでしたが、経歴もわりあい地味な印象で、仲間と思われる高野隆弁護士や趙誠峰弁護士とはずいぶんと違いを感じます。異常性としての接点はわずかに、深澤諭史弁護士と同じ第二東京弁護士会の所属ということになります。主著がずいぶん多いようです。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜keskil_（けっす） 日時：2019-11-20 17:33／2019/11/19 19:19 URL： https://twitter.com/kk_hirono/status/1197070405296521218 https://twitter.com/keskil_/status/1196734774624129024
> ネトウヨツイートにつけたいいねがよく流れてくる弁護士をミュート…
▶▶▶　　　　　End　　　　　▶▶▶

　上記は、その深澤諭史弁護士のTwitterタイムラインで見かけたところのツイートで、深澤諭史弁護士のリツイートとなっているものです。なんどか見かけてきたアカウントですが、プロフィールに弁護士とあることを確認しました。弁護士とはなさそうという予想は外れました。

```
けっす
@keskil_
弁護士（広島修習）／お酒飲みません
2009年7月からTwitterを利用しています
2,077 フォロー中
2,194 フォロワー

［source：］(2) けっす（@keskil_）さん / Twitter https://twitter.com/keskil_
```

　深澤諭史弁護士にリツイートされたツイートの内容を読むと、フォロしているアカウントがリツイートではなく「いいね」したツイートも、ホームのタイムラインに流れてくるようですが、これは知らなかったことで、いいねはアカウントの個人的な記録とばかり思っていました。

　私自身は、このTwitterの「いいね」はほとんど使っておらず、記録の必要性を考えるツイートはブロックされた弁護士のアカウントであることが多く、ブロックをされていなければリツイートをすることが多いからです。

　そういえば、今日は深澤諭史弁護士のタイムラインで気になるツイートの4連発があって、軽くメモ程度には記録しておく必要性を感じていたので、以下に掲載をしておきます。「ほりぐちです」という弁護士アカウントは、岡口基一裁判官に関するツイートでも数日前に要記録のものを見ていました。

fukazawas ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW fukazawas（深澤諭史） 日時：2019/11/20 10:49 URL： https://twitter.com/fukazawas/status/1196968834327908352
> 実名・匿名・なりすましを問わず，弁護士でないのに弁護士と名乗ると，実際に業務を行い，あるいは行う計画や意思がなくても名乗った時点で非弁行為として犯罪になりますよ。 \n （＃・∀・）
▷▷▷　　　　　End　　　　　▷▷▷

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2019-11-20 17:48／2019/11/20 10:36 URL： https://twitter.com/kk_hirono/status/1197074221488193536 https://twitter.com/shima_chikara/status/1196965452330627072
> 懲戒請求者への提訴を「よくやるねぇ」とあきれ顔で語られることもありますが、この声明にある思いは、私と同じ。 「私たちは、少数者の人権保障の最後の砦である司法の一翼を担う弁護士として、懲戒制度を正しく運用し、弁護士法の定める使命を全… https://t.co/FmyxamYqsl
▶▶▶　　　　　End　　　　　▶▶▶

fukazawas ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW fukazawas（深澤諭史） 日時：2019/11/20 09:50 URL： https://twitter.com/fukazawas/status/1196953862860488704
> ほんこれ。多分，改憲の最大の支障になっている。今の自民党は，憲政史上最強の護憲勢力だとおもっています。 \n （・∀・） https://t.co/iNHf7apJTq
▷▷▷　　　　　End　　　　　▷▷▷

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜mstk_Horiguchi（ほりぐちです） 日時：2019-11-20 17:49／2019/11/19 20:08 URL： https://twitter.com/kk_hirono/status/1197074436114939905 https://twitter.com/mstk_Horiguchi/status/1196747013825515521
> 自分は憲法を改正してもいいとは思ってるんだが、こうも現与党の現職議員たちが憲法を読んでいない、理解していない発言を繰り返してるとこの人たちが議論した改正案には賛成できないとなるわさ  国会議員だったら憲法勉強して欲しいです
▶▶▶　　　　　End　　　　　▶▶▶

　この憲法に対する考え方、言及というのも私が深澤諭史弁護士を記録観察する重要要素の一つで、羅針盤のような方向観察にも資するものです。深澤諭史弁護士に公式引用とリツイートをされたツイートの「ほりぐちです」というアカウントも、憲法に関する純度の高いツイートを見てきました。

　時刻は17時56分です。テレビは15時過ぎに石川テレビのグッディにテレビ金沢のミヤネ屋から変更したままで、そのままだったので、河津博史弁護士の取り上げ方について別の放送局の報道をみておきたいと、チャンネルを変えそうになっていたタイミングでした。

　また、「無罪請負人」などと大きな見出し付きで沢尻エリカと河津博史弁護士のことが出てきました。カルロス・ゴーン氏の記者会見で、河津博史弁護士の音声とともに「控訴は棄却されるべき」などと字幕が出てきましたが、初公判も始まっていないのにあり得ない誤記かと思います。

　正しくは「公訴棄却」のはずですが、カルロス・ゴーン氏の刑事事件で、この「公訴棄却」の主張は見た覚えが残っておらず、公訴と控訴を取り違えるとも考えにくいので、「無罪請負人」を強調することと同じく、意図的なものが含まれているような疑念が拭えません。

　カルロス・ゴーン氏の弁護団の記者会見の写真や映像をみていると、弁護団がそのまま難破船になって、幽霊船となりつつある弁護士歴史の時代絵巻をみているような気分になります。言葉を変えれば、映画の舞台演出をそのままリアルに見ているような気分と感覚です。

　弁護士らも今回ばかりは、慎重で様子見をしているのか、沢尻エリカに薬物反応が出たニュースに触れたツイートは今のところ見かけておりませんが、常連客のための蔵出しとして秘蔵の扱いをしているのかと思えるような無反応のニュース報道というのも少なくはありません。

　注意喚起となれば弁護士の仕事が減りそうな案件で、逆にありがちな落とし穴にはまれば、弁護士商売が繁盛しそうな案件があります。宇出津の寒ブリ漁も定置網で、地元では「大敷網」と呼ばれていますが、網に絡めて獲物を狙うのは、人間界における弁護士商売に似ていると考えることがあります。

　そういえば、沢尻エリカの逮捕で、安倍政権や政府の陰謀を唱える人は予想外に多い反応だったのですが、政権が不利な報道をごまかすために、いつでも逮捕できる薬物使用の芸能人を泳がせ、生け簀から取り出すさまをツイートしている人もいました。

　この件については、趙誠峰弁護士が前振りのようなツイートをいくつか行っていて、1万を超えるリツイートもあったり、けっこうな反応を集めているようです。考えてみると、趙誠峰弁護士と河津博史弁護士は、将棋の駒の飛車角のような存在感があると思えてきました。

　世間の反応次第では、早々に退任という可能性もありそうに思いますが、これでもかと高野隆弁護士伝授の弁護士道を突き進んでもらいたいものです。

〈〈〈：Emacs： 2019-11-20（水曜日）18：30 　〈〈〈

