#+TITLE: "裁判長、新井被告に「人生は終わったわけではない」　強制性交等罪で懲役5年判決"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-12-02 16:01:46 +0900
FILE_NAME: 2019-12-02-160146_裁判長、新井被告に「人生は終わったわけではない」　強制性交等罪で懲役5年判決.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 東京地裁,強制性交等罪,無罪主張,趙誠峰弁護士,毎日新聞,バイキング
記事タイトル名の文字数：38　保存ファイル名の文字数：60
#+STARTUP: showeverything


* 毎日新聞の有料記事：裁判長、新井被告に「人生は終わったわけではない」　強制性交等罪で懲役5年判決
  CLOCK: [2019-12-02 月 16:05]--[2019-12-02 月 16:40] =>  0:35

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 東京地裁,強制性交等罪,無罪主張,趙誠峰弁護士,毎日新聞,バイキング

〉〉〉：Emacs： 2019-12-02（月曜日）16：05　 〉〉〉

```
昨年7月、派遣型マッサージ店の従業員だった30代の女性に性的暴行を加えたとして、強制性交等罪に問われた元俳優の新井浩文（本名・朴慶培）被告（40）に対し、東京地裁は2日、求刑通り懲役5年の実刑判決を言い渡した。滝岡俊文裁判長は「犯行は卑劣で悪質。経緯、動機にくむべき点はなく、厳しい非難に値する」と述べた。新井被告側は即日控訴した。

　地裁は、新井被告が明かりの消された自宅寝室で、マッサージの施術を受けるという状況に付け込んで性的暴…

［source：］注目裁判・話題の会見：裁判長、新井被告に「人生は終わったわけではない」　強制性交等罪で懲役5年判決 - 毎日新聞 https://mainichi.jp/articles/20191202/k00/00m/040/089000c
```

　記事の見出しにある「人生が終わったわけではない」という部分は有料記事になるようです。判決がいつあるか求刑の時のニュース等で知っていたように思いますが、今日がその日とは知らず、午前中にTwitterの「懲役５年」というトレンドで知りました。

　裁判が始まってから逮捕のときとは報道のされ方が違っているように感じましたが、それというのも弁護人の判断と方針が強く出ているように感じていました。その弁護人が趙誠峰弁護士ですが、今日のバイキングの放送でも、意見が紹介されつつ、名前は出ていませんでした。

　お昼の情報番組バイキングは、いつも番組の始まりに今日のラインナップという番組内容の紹介があり、いつも２，３のニュースや話題を同じ画面で紹介していますが、今日は新井浩文被告のニュース１本で、その分、画面の表示も大きく、異様にも感じるヒートアップの報道ぶりでした。

　この毎日新聞の記事にも「弁護側は即日控訴した。」とあります。この一審の弁護人に新井浩文被告の意向に沿った積極性は感じていなかったので、控訴審は弁護人の交代を考えていたのですが、即日というよりは即時の控訴の表明で、同じ弁護人がやっているのだと思います。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜cho_seiho（CHO Seiho／趙誠峰） 日時：2019-12-02 16:23／2019/12/02 08:35 URL： https://twitter.com/kk_hirono/status/1201401586498461696 https://twitter.com/cho_seiho/status/1201283765022187521
> なんでや。。。  最高裁（1日）名古屋高裁部総括判事（名古屋家裁所長）鹿野伸二▽名古屋家裁所長（名古屋高裁部総括判事）戸田久▽名古屋高裁部総括判事（青森地裁所長）古久保正人▽青森地裁所長、石井俊和  人事、最高裁: 日本経済新聞 https://t.co/mimfbPmeTd
▶▶▶　　　　　End　　　　　▶▶▶

　趙誠峰弁護士のTwitterタイムラインは上記のツイートが最終更新となっており、７時間前として表示されています。判決のネットでの反応をみてから意見の表明があるのかもしれないですが、即時控訴するのであれば、その理由は早めに表明した方が説得力もありそうです。

　毎日新聞の有料記事は「残り387文字（全文604文字）」となっています。残りは公開された部分の２倍強ですが、バイキングでの詳細な報道と比較し、どんな情報が有料部分にあるのか気になるところです。有料の会員制はこの記事のみを対象にしたものではないとは考えています。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜cho_seiho（CHO Seiho／趙誠峰） 日時：2019-12-02 16:33／2019/11/30 00:34 URL： https://twitter.com/kk_hirono/status/1201403986252709888 https://twitter.com/cho_seiho/status/1200437886903914496
> 今日、また誤った有罪判決が確定してしまいました。私は知ってます、これが冤罪事件であることを。 彼女を救えなかった自分の非力さを恥じるばかり。彼女が母国に帰れるまで再審請求だろうがなんだろうがやり続けるしかない。 絶望してる暇はない。
▶▶▶　　　　　End　　　　　▶▶▶

　１１月３０日の趙誠峰弁護士のツイートで見覚えのあるものでした。同じ３０日にはもう一つツイートがあって、そのあとに同じ１１月３０日となっているツイートのリツイートがあって、１２月１日にも本人のツイートが１つありました。新井浩文被告に関するものは見当たりません。

　この刑事裁判の求刑が懲役５年で、判決が同じ５年だったということも気になっているのですが、それは三浦義隆弁護士のツイートが影響しています。

〈〈〈：Emacs： 2019-12-02（月曜日）16：40 　〈〈〈

