#+TITLE: "妻子3人殺害で元警官に死刑求刑　判決は13日"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-12-02 15:54:32 +0900
FILE_NAME: 2019-12-02-155432_妻子3人殺害で元警官に死刑求刑　判決は13日.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 福岡地裁,死刑求刑,元警察官
記事タイトル名の文字数：22　保存ファイル名の文字数：44
#+STARTUP: showeverything


* REGEXP：”元警官に死刑求刑”／データベース登録済みツイート：2019年12月03日08時40分の記録：妻子3人殺害で元警官に死刑求刑　判決は13日
  CLOCK: [2019-12-03 火 08:43]--[2019-12-03 火 09:39] =>  0:56

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 福岡地裁,死刑求刑,元警察官

〉〉〉：Emacs： 2019-12-03（火曜日）08：43　 〉〉〉

　昨夜はテレビニュース、報道に注目をしていましたが、最高裁の判決を含め、刑事裁判に関する報道はほとんどなく、はっきり確認したのは東京のどこか忘れましたが嘱託殺人という刑事裁判のみでした。それも判決や求刑ではなく初公判であったかもしれません。

　注目したテレビニュースとは、１９時台のNEWS７、２１時台のNEWS９、２２時台の報道ステーション、２３時台のzeroになります。昼のテレビはやたらと刑事裁判のニュースが多くて、それもこれまで経験のないことでした。

　家族間の殺人事件というのは被害者の数が多くても比較的量刑が軽い扱いになる傾向があると思います。多くは思い詰めた上での一家心中の失敗であったり、汲むべき事情があると認められたり、強い処罰感情を持つ遺族がいないということも大きいのかと思います。

　元警察官で死刑判決を受けた人は過去にもいました。はっきり思い出すのは宝石商の殺人事件で、私が拘置所にいる頃、アサヒ芸能という週刊誌に、その死刑囚の元警察官が連載の執筆を行っていました。居酒屋の経営に失敗し、元同僚や部下にも借金を重ねていたという話もありました。

[link:] » 【1984年】山中湖連続殺人事件【沢地和夫】 - NAVER まとめ https://t.co/JcR0g308mA

　上記の記事では居酒屋ではなく割烹店となっていました。確認はできなかったですが強盗殺人になるのではと思います。週刊誌の手記の連載では、猥褻な下ネタが多く、死刑執行の抗議で取り下げたということを思い出したので、その時点では死刑が確定しておらず、死刑囚ではなかったのかもしれません。

[link:] 2019年12月03日08時41分の登録： REGEXP：”元警官に死刑求刑”／データベース登録済みツイート：2019年12月03日08時40分の記録：ユーザ・投稿：10／11件 http://hirono2014sk.blogspot.com/2019/12/regexp2019120308401011.html

▶（04／11） TW sokudokubengosi（ワーキングプア弁護士） 日時： 2019-12-02 13:10:00 +0900 URL： https://twitter.com/sokudokubengosi/status/1201352889471385605
{% tweet 1201352889471385605 %}
> 妻子3人殺害で元警官に死刑求刑 判決は13日 福岡地裁公判 https://t.co/e0PAngQ1in \n \n 無罪を主張する被告が犯人と示す直接証拠はなく、裁判員らは難しい判断を迫られる。 \n \n いやそれ無罪ってことだから、

　上記の大仏アイコン匿名弁護士のツイートは、実名でもある奥村徹弁護士がリツイートしています。

▶（06／11） RT okumuraosaka（弁護人弁護士奥村徹(大阪弁護士会)）｜sokudokubengosi（ワーキングプア弁護士） 日時：2019-12-02 14:13:00 +0900／2019-12-02 13:10:00 +0900 URL： https://twitter.com/okumuraosaka/status/1201368706221146112 https://twitter.com/sokudokubengosi/status/1201352889471385605

　次が落合洋司弁護士（東京弁護士会）のツイートです。

▶（10／11） TW yjochi（?弁護士 落合洋司　散る桜　残る桜も散る桜 ?） 日時： 2019-12-02 19:14:00 +0900 URL： https://twitter.com/yjochi/status/1201444410182922240
{% tweet 1201444410182922240 %}
> 第三者による犯行の可能性をどこまで排除できるか。だろう。 \n →妻子3人殺害で元警官に死刑求刑　判決は13日　福岡地裁公判（毎日新聞） - Yahoo!ニュース https://t.co/XDV6V24M3z

```
2019年12月03日08時39分の実行記録
twitterAPI-search-lawList-mydql-add.rb "元警官に死刑求刑"
ツイート数：9/1623 リツイート数：3/1623 トータル：322
hirono_hideki 0／0件
kk_hirono 1／0件
s_hirono 0／0件

8：40 - 2019年12月3日

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”元警官に死刑求刑”／データベース登録済みツイート：2019年12月03日08時40分の記録：ユーザ・投稿：10／11件 http://hirono2014sk.blogspot.com/2019/12/regexp2019120308401011.html
```

　埋め込みツイートの表示をそのままコピペしました。TwitterAPIの検索メソッドを利用した登録済みアカウントの該当ツイートのデータベースへの自動登録処理になります。登録アカウントは1623件ですが、トータルが該当ツイートの総数で322件という少ない数です。

　元警察官で否認をしている、という以外でも死刑の求刑なので、もっと関心があってもよさそうですが、否認で死刑求刑、それも警察官であったということは社会的な信頼や知的能力も高めであったと考えられます。

〈〈〈：Emacs： 2019-12-03（火曜日）09：39 　〈〈〈

