#+TITLE: "妻子3人殺害「事実無根。間違いなく冤罪」元巡査部長、無罪主張　福岡地裁初公判"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-11-05 11:52:49 +0900
FILE_NAME: 2019-11-05-115249_妻子3人殺害「事実無根。間違いなく冤罪」元巡査部長、無罪主張　福岡地裁初公判.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: ニュース記事,冤罪主張,警察官の事件,裁判員裁判
記事タイトル名の文字数：38　保存ファイル名の文字数：60
#+STARTUP: showeverything


* 「妻子3人殺害「事実無根。間違いなく冤罪」元巡査部長、無罪主張　福岡地裁初公判」という毎日新聞のネット記事
  CLOCK: [2019-11-05 火 11:59]--[2019-11-05 火 14:32] =>  2:33

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: ニュース記事,冤罪主張,警察官の事件,裁判員裁判

〉〉〉：Emacs： 2019-11-05（火曜日）11：59　 〉〉〉

RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜mainichi（毎日新聞） 日時：2019/11/05 11:41／2019/11/05 11:30 URL： https://twitter.com/hirono_hideki/status/1191545957394964480 https://twitter.com/mainichi/status/1191543154060734464
> 福岡の母子3人殺害、元巡査部長が無罪主張https://t.co/J13ZKrVpTn

　特定のアカウントのタイムラインでのリツイートではなく、ホームのタイムラインでたまたま見かけた毎日新聞のツイートになります。上記のリツイートは見かけてすぐに実行したものです。

　今朝はテレビをつけておらず、さきほど気がついてテレビをつけたのが１１時５７分でした。１１時５５分から始まる情報番組バイキングで今日のラインナップを確認するつもりだったのですが、２分ほど時間が遅れたことになります。

```
福岡県小郡市の自宅で妻子3人を殺害したとして、殺人罪に問われた元福岡県警巡査部長、中田充（みつる）被告（41）＝懲戒免職＝は5日、福岡地裁（柴田寿宏（としひろ）裁判長）であった裁判員裁判の初公判で「一切身に覚えがなく、事実無根。間違いなく冤罪（えんざい）です」と無罪を主張した。

［source：］妻子3人殺害「事実無根。間違いなく冤罪」元巡査部長、無罪主張　福岡地裁初公判 - 毎日新聞 https://mainichi.jp/articles/20191105/k00/00m/040/084000c
```

　毎日新聞のネットニュースでは、有料記事となっていないものを見たのも久しぶりで、ずいぶん珍しく感じました。「毎日新聞2019年11月5日 10時37分(最終更新 11月5日 11時51分)」という配信時刻と思われる親切な表示もあります。

　記事の内容が最初にみたときと変わっていました。最終更新の意味を理解しましたが、このようにそれぞれ更新前の前後の記事を読んだのは今回が初めての経験かと思います。

　報道を見かけなくなって気になっていた事件の一つです。同様の事件は他にもいくつかあって、神奈川県小田原市付近での新幹線車内の殺傷事件や新潟市西区での電車での轢殺を偽装した女児殺害事件があります。

　記事によると、２０１７年６月５日夜から６日朝の間に発生した事件とあります。うる憶えですが、発生から早い段階でテレビのニュースになっていたと思います。被疑者が親族に異変を連絡したことが事件の発覚になっていたように記憶があります。

　２０１７年６月というのも時期の特定として記憶はなかったのですが、当初よりいくつか気になることがあって注目をした事件でした。まず、事件の場所が、福岡県小郡市として報道されていました。

　福岡県には長距離トラック運転手の仕事でよく行っていたのですが、小郡市というのは記憶にないもので、小郡という地名は、福岡県を含む九州方面に国道９号線の下道で行く時、利用していた小郡インターの印象が強くありました。

　金沢市場輸送の会社のルールでは、九州方面に下道で行く時、小郡インターから先の高速道路の利用が認められていました。ただ、私は途中から山口インターを使うことが多くなり、その点でも小郡インターというのは印象的でした。

　国道９号線から山口インターに行く道も今は記憶にないですが、小郡インターに向かうときに通ったのが湯田温泉であったように思います。温泉街の真ん中をトラックで通行し、その道沿いのホテルが、能都中学校の修学旅行のときの風景と重なるものがありました。

[link:] » 小郡市 - Wikipedia https://t.co/JlVBYlwoCA

　上記の『ウィキペディア（Wikipedia）』に「1972年（昭和47年）4月1日 - 市制施行し、小郡市となる。」とあります。昭和５９年から平成４年というのが私が長距離トラック運転手をしていた時期になりますが、すでにその頃には存在した市名になります。

　そういえば九州自動車道のインターの看板に、他のインター名と抱合せのような感じで「小郡」という地名があったようなきがしますが、「小郡市」となると、やはり記憶にはなかった気がします。隣接した筑紫野市などは強く記憶にも残っていただけに、不思議な発見のように感じられました。

　福岡県小郡市は佐賀県鳥栖市とも隣接し、それも中心部同士がずいぶん近くに見えます。鳥栖市は九州自動車道と長崎自動車道の分岐点になっていて、国道３号線沿いでもあったので、給油や帰り荷を待つ待機場所としてもとてもよく利用していました。

　鳥栖インターの側にはトラックステーションもありましたが、ガソリンスタンドで風呂に入って寝ることもありました。大型トラックが入る大きなガソリンスタンドでは風呂が付いていることが多く、無料でした。会社からなどの電話連絡も取り次いでくれます。頼んだ時間に起こしてもくれます。

　私は当初、事件のニュースで福岡県小郡市と聞いた時、北九州市の近くをイメージしたように思います。山口県の小郡インターの印象が強かっただけに、地理的に近い北九州市が思い浮かんだとも思います。

　北九州市は、金沢市場輸送の定期便でも決まった立ち寄り先となっていました。福岡市と２箇所おろしで、どちらも西武運輸でした。荷物は富山のトナミ運輸の雑貨になります。

　九州自動車道が門司から直方市辺りまでつながったのは、私が金沢市場輸送で大型車に乗務して１年ほど経った頃であったように思います。それまでは決まって北九州市の都市高速を通行していました。高架が高くて道幅も狭く、昭和６０年当時でもかなり老朽化していたという印象があります。

　中西運輸商の仕事では佐川急便の広島・九州便だったので、運行の大半が九州だったと思います。金沢市場輸送でも月に2回から、多いときで5回ぐらいの運行が九州でした。多かったのは11月から1月ぐらいのミカンの時期です。

　ちょうど昨日の夕方の遅い時間になりますが、九州のことで気になることがありました。どんたく宇出津店で、懐かしいミカンの箱を目にしたのですが、山川みかん、とありました。

[link:] » 南筑後農業協同組合 山川支所 - Google マップ https://t.co/YSy47mVd8E

　この前に実行した検索では福岡県久留米市山川町が出てきて、市街地に近かったので、こんなところにミカンがあるのかと不思議に思っていました。

```
みやま市（みやまし）は、福岡県南部に位置する市。瀬高町、高田町、山川町が合併し、2007年1月に発足した。

［source：］みやま市 - Wikipedia https://ja.wikipedia.org/wiki/%E3%81%BF%E3%82%84%E3%81%BE%E5%B8%82
```

　この福岡県みやま市も近年知った地名ですが、高田町について調べていたときのことかと思います。上記の『ウィキペディア（Wikipedia）』によると、旧山門郡山川町、旧三池郡高田町とあります。

　三池ということで三池炭鉱を思い出しました。昭和の時代は何かと見聞きすることが多かったと記憶にあります。高田町は、日栄運送から変わった富山市の池田運輸の仕事で、何度か行っていた場所になりますが、海抜の低そうな平坦な道が続いていたという印象で、炭鉱とは無縁と思っていました。

　池田運送や高田町については、すでに一通り記述したものがあるかと思います。地元の駐在員のような若者がいて、名前の方は忘れましたが、同じ池田運輸の仕事で、佐賀県唐津市のは入り口のようなところにも出荷場があってミカンを積みにいっていました。

[link:] » 告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)/「池田運輸」の検索結果 - Twilog https://t.co/qsfmfyaUbT

　気になるツイートの発見がありました。

TW kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中） 日時： 2014/01/11 00:47 URL： https://twitter.com/kk_hirono/status/421669615538696192
> すでに本書においても昨年（2013年）中に書いていると思いますが、あえて名前を書いておく必要があると判断した人物です。その彼に前橋市内の国道50言線で、信号待ちで停車中に声を掛けられたのも、池田運輸の仕事で群馬県の埼玉県境にキュウリを積みに向かっているときだったかもしれません。

TW kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中） 日時： 2014/01/11 00:38 URL： https://twitter.com/kk_hirono/status/421667455375638529
> 古河の青果市場の仕事を専属でするようになるちょっと前は、群馬県内の館林市など埼玉県にも近い農協などからキュウリなどの野菜を運ぶ仕事を何度かした憶えがあり、それも池田運輸の仕事だと聞いていたように思います。請負先は日報にも記載する必要がありました。

　そういえばと少し思い出したのですが、関東からキュウリを積んできたのも池田運輸の仕事であったように思います。意外だったのは、前橋市内の国道50号線でKKさんに会った時の様子ですが、これは茨城県古河市の山三青果に向かっていたとこのこととばかり思い込んでしました。

　今年に入ってからも記述をしたように思いますが、前橋市内の国道50号線でKKさんに会ったのは、鹿児島市内から積んできた白菜を長野市の市場で降ろした翌日のことです。また、鹿児島市の市場での白菜の積み込みは、前日に熊本県八代市の海沿いで荷降ろしをしていました。

　池田運輸については、運転手の間で金沢市場輸送との関係性が話題となったことがなく、直接、富山の池田運輸の会社に行くこともなかったのですが、富山インターの近くの道路沿いに沢山のトラックのとまった会社があって、その前をちょくちょくと通りかかった記憶があります。

　池田運輸というのはありふれた名前というだけではなく、同じ名前の規模の大きな運送会社が他にあったように思います。関西方面の運送会社だったように思いますが、よほど規模が大きいのかとくトラックを見かける運送会社でした。

　富山の池田運輸は、ベースが濃い緑色となっていたように記憶にありますが、珍しいぐらいに地味なデザインのトラックでした。とにかく運転手の間で話題になることがほとんどなかったので、それも不思議なことでした。

　福岡県池田町の駐在員ですが、大きな出荷場のごく一部を間借りしたようなスペースで会ったという記憶もあります。古い大きな学校の教室のようであったという印象もかすかに残っています。

　駐在員は、外回りや営業が向いていそうな若者でした。年はいくつか上だったと思いますが、20代だったとも思います。気さくでいろいろと話もしたのですが、名前の方もずっと前に忘れてしまいました。

　似たような関係性だったのが、その前の日栄運送の駐在員になります。こちらも今は名前が思い出せないですが、池田運輸とは違い、運転手の間でもよく話題になって名前が出ていました。

　家が熊本県の山鹿市か菊池市と聞いていたように思います。最初に出会った頃は、熊本市の植木の出荷場であったように思います。出荷場というより市場だったかもしれません。かなり規模の大きなもので、中西運輸商の仕事でも行ったことがありました。

　そのあと、長崎県の長与町の出荷場で、顔を合わせるようになりましたが、熊本から泊まり込みで来ていると話していました。長崎の長与のみかんは、石川県のスーパーで一番見かけることの多いみかんであったとも思います。

　昨夜、どんたく宇出津店で見かけた山川みかんの箱ですが、箱のデザインが昭和の時代と変わっていないように思いながら、「白木みかん」となっていたような記憶もあります。

　福岡県と熊本県の県境付近で福岡県内になりますが、その辺りにも2,3箇所、ミカンを積みに行った記憶があり、どこの運送会社の仕事だったかは記憶にないですが、駐在員はいなかったとも思います。

　スーパーでミカンの箱売りというのも、近年は余り見かけないように思います。小家族化もあると思いますが、ミカンの流通量自体が、昭和の時代と比較してずいぶん少なくなっているような気がします。

　個人的な体験にもとづく印象ですが、同じ福岡県でも山口県に近い北九州と、熊本県に近い久留米市の周辺では、かなり印象が違ってきます。北九州市は、広島と同じく昭和の時代のヤクザ映画で抗争の舞台というイメージがけっこう根強い気もします。

　その北九州市の現職警察官というのが感熱紙というアカウントで、中途半端になっていたエントリーがあるかと思いますが、その感熱紙というアカウントのことも、小郡市の警察官の家族殺害事件のときに、思い浮かべていました。

〈〈〈：Emacs： 2019-11-05（火曜日）14：32 　〈〈〈

