#+TITLE: "被告発人HTNと被告発人大網健二の関係"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-10-11 14:08:42 +0900
FILE_NAME: 2019-10-11-140842_被告発人HTNと被告発人大網健二の関係.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 平成9年頃,被告発人HTN,被告発人大網健二
記事タイトル名の文字数：19　保存ファイル名の文字数：41
#+STARTUP: showeverything


* あずけられたノートパソコンに金沢市粟崎○○邸新築工事のファイル：被告発人HTNと被告発人大網健二の関係
  CLOCK: [2019-10-11 金 15:56]--[2019-10-11 金 18:02] =>  2:06

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 平成9年頃,被告発人HTN,被告発人大網健二

〉〉〉：Emacs： 2019-10-11（金曜日）15：56　 〉〉〉

　私が金沢市の北安江の借家に住み始めたのは、平成9年7月の初めで1日か2日になると思います。「 % cal 7 1997」というコマンドで確認すると7月1日は火曜日となっていました。曜日は記憶にないですが、土日ではない平日という記憶は残っていました。

　夜、暗くなってからと記憶にあります。7月の1日頃だとだいぶん日は長そうなので、19時でもだいぶん明るそうです。それを考えると20時から遅くて21時の頃に、被告発人大網健二とKYNが2人で、引っ越し用の2トントラックに乗って宇出津の私の家に来ました。

　被告発人大網健二がK村さんに借りてきたトラックだったと思います。K村さんからの借り物ということを強調することはなかったと思いますが、その辺りも少しは気になっていました。このK村さんは被告発人松平日出男と関わりのある人物で、それも濃厚な人間関係がうかがえます。

　宇出津から2トントラックに引っ越しの荷物を積んで、夜中に金沢市の北安江の借家に到着しました。荷降ろしの作業のことも今は思い出せないですが、終わった頃には日付は変わっていたと思います。1時、2時という時間だったかもしれません。

　たしか双葉湯の近くにコンビニがあって、被告発人大網健二が必要がないほど沢山のパンとともに、3種類から5種類ぐらいのゴキブリ退治のスプレーなどを買ってくれました。作業中にゴキブリが出たからです。

　被告発人大網健二の処世術で意味のある行動なのかとは考えましたが、そのときに始まったことでもなく、よくあることだったので特に深くは考えずにいました。むしろ気になったのは、始めて北安江の借家の下見に行った時、家の裏側の居間のガラスの鍵が閉まっていなかったことです。

　現在もアルミサッシにはあるタイプの鍵かと思いますが、カタツムリのような形状で半月を回して開け閉めするものです。当時も一般的なものだったと思いますが、現在は違った形状のものがあるのかもしれません。

　トラックでの引っ越しは1回だけだったと思います。テレビや洗濯機は、引っ越してすぐに、近くのアルプラザ平和堂で注文し配達をしてもらったと思います。買い物のときは被告発人大網健二も同行していました。

　これも前に記述したことだと思いますが、金沢中央卸売市場からアルプラザ平和堂の間の地域は、開発が進んで以前の原形をとどめないぐらいに町並みが変わっていました。わずかに残っていた原形の１つが双葉湯になります。

　双葉湯のすぐ近くには「飛鳥」という食堂があって、昭和59年当時は金沢市場輸送の運転手の行きつけの店で、つけ払いまで出来ました。よく行っていましたし、被告発人大網健二も同じ時期に一緒に行っていたはずです。

　場所は変わっていないと思いましたが、飛鳥の店は店内が全面改装されていて、昭和59年当時とはまったく違っていました。木目のカウンター席などがあって、明るい店内の小料理屋のようになっていました。客の数も多く繁盛している様子でした。

　昭和59年当時の飛鳥は、食堂と言っても店内は昼でも薄暗い雰囲気で、スナックのような飲み屋に近かったと思いますし、棚にはキープされたボトルが並んでいたような気もします。夜に店に入ることは、金沢市場輸送の仕事の内容で少なかったのですが、夜は飲み屋だったのかもしれません。

　もう3年近くになりますか、テレビに白峰村のラーメン屋のような焼肉店が紹介されていたのですが、その店内の様子が昭和59年当時の飛鳥によく似ていると感じました。白峰村の店は、高齢の女性が一人で切り盛りをしているという話で、それも不思議に感じるところがありました。

[link:] » 『 食堂 永清 』50年続く白峰でジビエ焼肉を堪能できる隠れた名店|金沢時間 https://t.co/Cxk4fD96IV

[link:] » 白峰観光協会 — 絹肌の湯と雪だるまの里 https://t.co/PSsKfplXc1

　上記の情報にある店だと思います。妙に懐かしいような雰囲気のあるお店で、アニメ自体は余り関心もなく知らないのですが、千と千尋の神隠し、に出てくるような雰囲気もあるように思います。店主がずいぶん高齢そうなのに元気そうなのも不思議でした。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-11 16:44／2018/02/19 11:16 URL： https://twitter.com/kk_hirono/status/1182562573704552448 https://twitter.com/hirono_hideki/status/965409749138223104
> 白峰　大衆食堂　永清のラーメン！ : でくのぼうぷれす https://t.co/EluzOobOrn すでに古希を回った女性店主が一人で切り盛りしているようです。  続けられうちは、続けて行きたいと、、、。
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「永清」の検索結果 - Twilog https://t.co/S94vcFHrcd

　Twilogの検索結果は3件で全て2018年2月19日となっています。これだと「はじめてのおつかい」という番組で白峰村の八坂神社をみたのは、永清より前になるのかと思われます。はじめてのおつかい、は正月の放送で1月の7日から9日の間であったと思います。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-11 16:58／2018/02/19 02:10 URL： https://twitter.com/kk_hirono/status/1182566250989289472 https://twitter.com/hirono_hideki/status/965272246510956546
> 能登の祭 能登町藤波 酒樽がえし 2017 - YouTube https://t.co/o2KQeyJv7s
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-11 16:56／2018/02/19 19:10 URL： https://twitter.com/kk_hirono/status/1182565725887590400 https://twitter.com/hirono_hideki/status/965529037270499328
> 国道45号線の最大の難所、中野坂。【東北に自転車で行ってきた！　第百五十五話】｜東京都世田谷区池尻から東北を応援する、スタジオ自転車部部長・小山のブログ https://t.co/YPODeYFafz
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-11 16:55／2018/02/19 20:23 URL： https://twitter.com/kk_hirono/status/1182565405639884800 https://twitter.com/hirono_hideki/status/965547313904025602
> はじめてのおつかい！|ボクシング山中パパが大挑戦！笑顔＆涙が満載3時間SP|2018/01/08(月)19:00放送|日本テレビ|TVでた蔵 https://t.co/Rmjq6sYvSA 白山連峰がある石川・白峰で碧ちゃん（2歳11か月）がはじめてのおつかい。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-11 16:54／2018/02/19 20:35 URL： https://twitter.com/kk_hirono/status/1182565156728918018 https://twitter.com/hirono_hideki/status/965550466091249669
> @Hideo_Ogura @izumillion 貴方こと小倉秀夫弁護士モトケンこと矢部善朗弁護士（京都弁護士会）、深澤諭史弁護士は、魂を揺さぶる気違い弁護士だと思っています。危険生物としての社会汚染の垂れ流しです。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-11 16:54／2018/02/19 20:42 URL： https://twitter.com/kk_hirono/status/1182565069235707904 https://twitter.com/hirono_hideki/status/965552092042571776
> @Hideo_Ogura @izumillion 私こと廣野秀樹は、蘇民将来のために、貴方こと小倉秀夫弁護士とモトケンこと矢部善朗弁護士（京都弁護士会）に刑事責任を負わせる、そのことをお忘れなきようお願いします。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-11 16:54／2018/02/19 20:47 URL： https://twitter.com/kk_hirono/status/1182565029712785408 https://twitter.com/hirono_hideki/status/965553447738130432
> 「はじめてのおつかい」に届く“放送中止願い”とは？ 関係者が明かす、驚きの声 https://t.co/NoYLUZtjnw
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-11 16:53／2018/02/19 20:49 URL： https://twitter.com/kk_hirono/status/1182564970799628288 https://twitter.com/hirono_hideki/status/965553907656155136
> 「放送中止を要望する声が時折届くのが、『はじめてのおつかい』（日本テレビ系）なんです」（テレビ番組関係者）1991年から始まり、お正月などの節目ごと年に数回ずつ放送されている同番組は、今年で26年目を迎える歴史ある番組だ。もはや説… https://t.co/j8IbTvF4rv
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-11 16:53／2018/02/19 20:52 URL： https://twitter.com/kk_hirono/status/1182564911353720835 https://twitter.com/hirono_hideki/status/965554570683342849
> 「撮影時は周囲をカメラマンが囲んで、それ以外にも警備担当スタッフが十数名ついています。撮影前には、全ての道路状況を調べあげ、危険な箇所は通らないルートを設定、またどうしても避けられない場合にはスタッフを増員して事故防止に努めていま… https://t.co/ssPfs4q84D
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-11 16:51／2018/02/19 23:43 URL： https://twitter.com/kk_hirono/status/1182564259684732928 https://twitter.com/hirono_hideki/status/965597815316480000
> 兵庫県で5歳児がはねられ死亡「1人でおつかいに行かせるべきではない」という指摘も｜ニフティニュース https://t.co/XmuV4ZRsgt
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-10-11 16:51／2018/02/19 23:46 URL： https://twitter.com/kk_hirono/status/1182564240588075008 https://twitter.com/hirono_hideki/status/965598582488182784
> @Hideo_Ogura 脅迫とか粛々とか決めつけた私にこと廣野秀樹に対する返答はないのでしょうか。石川県警察珠洲警察署に、持参するお土産として、具体的な話を聞いておきたいのです。公然性という記録を担保して。
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2018年02月19日 - Twilog https://t.co/5wSwQp47sg

　この2018年2月19日は214件のツイートがあったようです。いろいろと思い出すこともありましたが、白峰村の永清という焼肉店をテレビで見たのが、はじめてのおつかい、を見たあとだったとは意外でした。一月半ほど前という感覚はあっていたようですが、逆だと思い込んでいました。

　前にも書いたことがあると思いますが、私は国道で白峰村を通ったことがあるはずなのですが、記憶には何も残っていません。福井県勝山市の繊維工場のようなところに行った時のことでした。これも石川県警察が絡むので、いずれ書いておきたいと予定しています。

[link:] » 北安江 - Google マップ https://t.co/4qIBp7RDNH

　北安江は金沢駅の裏側、駅西に近いですが、Googleマップで範囲が簡単に確認できるようになったのも近年のことかと思います。住宅地図をみて範囲を確認することはなかったと思いますし、平成9年当時とは範囲が違っている可能性というのもあるかもしれません。

　金沢駅に近いですが、昭和56年頃は民家もまばらでさみしいところだったと記憶にあります。駅西の開発が急激に進んだのは昭和62年ぐらいだったと思います。もともと駅西というのは金沢駅の裏側でその近くでしたが、金沢中央卸売市場の過ぎ近くまで駅西に変わりました。

　その金沢中央卸売市場の住所は金沢市西念となっていましたが、けっこう離れた場所にある飛鳥や双葉湯も同じ西念だと聞き、それがけっこう不思議に思えていました。

[link:] » 西念 - Google マップ https://t.co/Ar9EULNaXs

　Googleマップで範囲をみると、金沢駅から金沢港に向かって縦に長くなっていて、一部が国道8号線バイパスに隣接しています。

　金沢駅西口からバイパスに向かう広い道路が、Googleマップでは「けやき通り」となっていますが、これは初めて聞いたように思います。50メートル道路と呼ばれていたように思いますが、道幅が本当に50メートルあるのか疑問でした。

　Googleマップに駅西本町三丁目となっている大きな交差点がありますが、この交差点から西念町の交差点に行く道路は、以前全く無い道路だったと思います。交差点となっている突き当りには大きな古いマンションがあって、1階にT林が行きつけとして喫茶店があったかと思います。

　同じマンションの2階だったとも思いますが、麻雀荘があって、そこからプラザというパチンコ店に行ったことを憶えているのですが、ややこしい路地を通った先に、広い駐車場の大きなパチンコ店があったので、不思議に思ったことをよく憶えています。

　そのプラザというパチンコ店は、別によく通る道路の道沿いにも近かったのですが、そちらから気がつくことはありませんでした。気がついたのは北安江の借家で生活が始まってからのことで、パチンコ店の駐車場とアルプラザ平和堂の駐車場は隣接するようになっていました。

　アルプラザ平和堂は、それだけでもかなり広い敷地でしたが、裏の方にもけっこう大きなホームセンターがありました。どちらも平成9年の7月以降に、突如として知った建物だったのですが、その前がどのような土地だったのかよく憶えておらず、古い住宅地であったような気はします。

　平和堂アル・プラザ金沢の住所は金沢市諸江となっています。この諸江という住所は金沢市で一番広いような気もします。国道8号線バイパスにまたがって、けっこう奥の方まで住所が諸江だと聞いていました。そこの住宅に住んでいたのが河野さんになります。

[link:] » 諸江町 - Google マップ https://t.co/yHZQy172Uz

　Googleマップの地図上でみると、それほど広くは感じないですが、やはり浅野川沿いにまでバイパスをまたがって続いています。ここは浅野川線とかいう電車が金沢駅から内灘駅まで続いていました。

　和田くんのアパートもその線路沿いにありましたが、その浅野川線の線路沿いというのは、けっこう他とは違った雰囲気がありました。西念や北安江もそうだったと思いますが、以前は古くて粗末な家が多く、貧民街のような印象もあったのですが、現在はまるで違っていると思います。

　西念については、昔から土地が痩せていて農作物の栽培に向かず、土地の単価も安いと聞いたことがありました。地域の人にそんな話を聞いたことはなかったのですが、だんだんと家の数も増え、新しい建物も増えていったかと思います。北安江の借家の周辺も新しい家がほとんどでした。

〈〈〈：Emacs： 2019-10-11（金曜日）18：02 　〈〈〈

