#+TITLE: "「指定弁護士の石田、神山、山内、渋村、久保内先生には、素晴らしい訴訟活動をしていただきました。」という9月21日のツイート（海渡雄一弁護士）"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-09-30 23:15:00 +0900
FILE_NAME: 2019-09-30-231500_「指定弁護士の石田、神山、山内、渋村、久保内先生には、素晴らしい訴訟活動をしていただきました。」という9月21日のツイート（海渡雄一弁護士）.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 海渡雄一弁護士,神山啓史弁護士,東電,指定弁護士
記事タイトル名の文字数：70　保存ファイル名の文字数：92
#+STARTUP: showeverything


* 「指定弁護士の石田、神山、山内、渋村、久保内先生には、素晴らしい訴訟活動をしていただきました。」という9月21日のツイート（海渡雄一弁護士）
  :LOGBOOK:
  CLOCK: [2019-09-30 月 23:17]--[2019-10-01 火 00:59] =>  1:42
  :END:

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 海渡雄一弁護士,神山啓史弁護士,東電,指定弁護士

〉〉〉：Emacs： 2019-09-30（月曜日）23：17　 〉〉〉

　調べたところ東電旧経営陣の無罪判決があったのは9月19日のようです。

```
２０１１年３月の東京電力福島第一原発事故をめぐり、旧経営陣３人が業務上過失致死傷罪で強制起訴された裁判で、東京地裁（永渕（ながふち）健一裁判長）は１９日午後、勝俣恒久・元会長（７９）、武黒（たけくろ）一郎・元副社長（７３）、武藤栄・元副社長（６９）の３被告にいずれも無罪（いずれも求刑・禁錮５年）の判決を言い渡した。検察官役の指定弁護士が控訴すれば、控訴審でさらに争われることになる。

経営陣の意思決定過程、解明しきれず　東電原発事故裁判
ちょうど８年前、爆発した原発　無罪訴える３人に福島は
　３人は、原発の主要施設の敷地の高さ（約１０メートル）を上回る津波が来ると予想できたのに対策を怠って事故を招き、４・５キロ離れた双葉病院（福島県大熊町）の入院患者らに避難を余儀なくさせ、４４人を栄養失調や脱水症状で死亡させたなどとして強制起訴された。

［source：］東電会長ら旧経営陣３人に無罪判決　原発事故で強制起訴：朝日新聞デジタル https://www.asahi.com/articles/ASM9M35HBM9MUTIL008.html
```

　次が判決があったという9月18日を基準とした海渡雄一弁護士のツイートです。

TW kidkaido（海渡雄一） 日時： 2019-09-30 22:46 URL： https://twitter.com/kidkaido/status/1178667465116536832
> 大泉夫妻の健康被害裁判で勝訴できなかったこと、本当に申し訳なく思っています。この裁判の教訓を踏まえて、福島における健康被害の存在を明らかにしていく地道な作業が必要です。 https://t.co/AT1lK9HxlI

TW kidkaido（海渡雄一） 日時： 2019-09-30 16:42 URL： https://twitter.com/kidkaido/status/1178575940034498561
> 本日30日午後三時過ぎに指定弁護士が控訴の手続きを取りました。皆さんの願いが叶いました \n 指定弁護士の先生方に心から感謝します。 \n これからも、指定弁護士を支えて、高裁での逆転有罪判決を求めて、活動を続けます。これからもよろしくお願い… https://t.co/XNDz7IhQbV

TW kidkaido（海渡雄一） 日時： 2019-09-30 15:29 URL： https://twitter.com/kidkaido/status/1178557440582832128
> 昨日の郡山での街頭署名行動を毎日新聞が記事にしてくれました。 \n ありがたいことです。 https://t.co/XXZtY4VJqK

TW kidkaido（海渡雄一） 日時： 2019-09-30 15:25 URL： https://twitter.com/kidkaido/status/1178556405919318016
> https://t.co/Ht4fsXYr70

TW kidkaido（海渡雄一） 日時： 2019-09-30 13:46 URL： https://twitter.com/kidkaido/status/1178531573991272448
> 海渡です。今しがた、東京地検まで、指定弁護士宛ての署名900人分を提出しました。デジタルを含めれば、総数は14200人となりました。 \n 福島と全国からの控訴を求める声は伝えられたと思います。 \n 「東電旧経営陣に無罪判決」　控訴求め署名… https://t.co/llkKAVbwNB

TW kidkaido（海渡雄一） 日時： 2019-09-30 10:15 URL： https://twitter.com/kidkaido/status/1178478451117838336
> 関電幹部の金品授受、原発工事費用が工事業者「吉田開発」から、高浜町元助役を経由して還流していた。もともとは、電気料金だったお金から、自らの懐に入れていた。 \n アベマTVで河合弁護士が解説しています。 https://t.co/7sCZqiTBie

TW kidkaido（海渡雄一） 日時： 2019-09-30 00:13 URL： https://twitter.com/kidkaido/status/1178326978216087552
> 素晴らしい。政府間関係が悪化したときこそ、民間で良い関係を取り戻さなくては。日韓の弁護士会でも、共同でできることがあるはずです。 https://t.co/C5VDDU98ql

TW kidkaido（海渡雄一） 日時： 2019-09-30 00:05 URL： https://twitter.com/kidkaido/status/1178324858200973312
> ようやくネットの署名が13300、紙の署名が900です。あと800名で15000人になります。指定弁護士の皆さんに控訴をしていただき、控訴審も同じ五人の指定弁護士の方々に事件を担当してもらいたいです。どうかよろしくお願いします。 https://t.co/WeKFVZKcyu

TW kidkaido（海渡雄一） 日時： 2019-09-28 16:03 URL： https://twitter.com/kidkaido/status/1177841265058009088
> 今日の六時過ぎから、東京地裁の無罪判決を徹底批判する、対談をします。プレゼンも全面的に作り直しました。どうか、みなさんご覧になってください。岩上さんのご厚意でフル・オープンで、無料で見られます。IWJを経済的にも支えてください。私… https://t.co/CbMpZJ712g

TW kidkaido（海渡雄一） 日時： 2019-09-28 16:00 URL： https://twitter.com/kidkaido/status/1177840517221994497
> ※全編オープン【9/28 18時半～】「司法の歴史に汚点を残す判決だ！」福島原発刑事訴訟 東電元経営陣3名「全員無罪」?! 岩上安身による福島原... https://t.co/buPNxg0Mlm @YouTubeさんから \n 岩上… https://t.co/s7gxziGDE6

RT kidkaido（海渡雄一）｜picoyai（やいちゃん） 日時：2019-09-28 00:25／2019-09-27 06:27 URL： https://twitter.com/kidkaido/status/1177605203400331264 https://twitter.com/picoyai/status/1177333866131968008
> たまげた。「返却の機会を伺いながら保管していた」というクソ言い訳が通用するなら賄賂案件はなくなるね💢 https://t.co/lYUGOPeLFk

RT kidkaido（海渡雄一）｜tasaki_kanagawa（田崎 基（神奈川新聞 記者）） 日時：2019-09-28 00:21／2019-09-27 18:52 URL： https://twitter.com/kidkaido/status/1177604084582383621 https://twitter.com/tasaki_kanagawa/status/1177521509868261376
> ええぇ！？？信じがたいコメント。 \n いい大人が何を言っているのか…。 \n 関電役員の金品授受、経団連会長「友達で悪口言えない」：朝日新聞デジタル https://t.co/hT9wsqrPOv

TW kidkaido（海渡雄一） 日時： 2019-09-27 15:41 URL： https://twitter.com/kidkaido/status/1177473442095886336
> 私も参加します。 \n シンポの後、郡山駅前で、無罪判決に対する控訴を求める街頭宣伝行動を行う予定です。街頭行動にも、ぜひご参加をお願いします。 https://t.co/LmCAIklskP

RT kidkaido（海渡雄一）｜ueno_wan（上野千鶴子） 日時：2019-09-25 19:55／2019-09-22 23:24 URL： https://twitter.com/kidkaido/status/1176812447790841856 https://twitter.com/ueno_wan/status/1175777896100585472
> 拡散希望。福島原発告訴団、福島原発刑事訴訟支援団より、東電刑事裁判元経営陣「無罪」判決控訴を求める緊急署名のお願いです。控訴期限は２週間、10月2日まで、下記、緊急署名ページへ。 \n https://t.co/I5qDQCasfB

TW kidkaido（海渡雄一） 日時： 2019-09-25 18:23 URL： https://twitter.com/kidkaido/status/1176789218057572352
> 朝日新聞ウェブ論座にこの判決の根本的な問題点をまとめた「東電旧経営陣無罪判決、裁判所が犯した七つの大罪」が掲載されました。七つの大罪のうち、一番基礎的なことをまとめた二つ目までは無料で読むことができます。ぜひ、お読みください。 \n https://t.co/jyUr6j8XQT

TW kidkaido（海渡雄一） 日時： 2019-09-24 21:05 URL： https://twitter.com/kidkaido/status/1176467712010117120
> 国際人権法の権威である青学の申先生の日韓関係と徴用工問題に関する新しい論考がネット上に公開されました。 \n  \n 論理明晰な素晴らしい論考で、私もその論旨に全面的に賛成です。... https://t.co/wRVvocfr39

TW kidkaido（海渡雄一） 日時： 2019-09-24 16:11 URL： https://twitter.com/kidkaido/status/1176393694020165632
> マイナンバーカードで、ポイント還元などと浮かれていると、日本でも同じようなことが起きない保障があるのか! https://t.co/dKQnojaTow

TW kidkaido（海渡雄一） 日時： 2019-09-23 20:50 URL： https://twitter.com/kidkaido/status/1176101415623655424
> 今日、神戸に出かけて、土井たか子さんの五周忌の偲ぶ会でした。そうしたら、なんとその場で、この署名集めをされていた方がいました。感謝!感謝!です。ネット署名も一万人まであと一歩です。 https://t.co/ROdXlBRsHN

TW kidkaido（海渡雄一） 日時： 2019-09-23 19:59 URL： https://twitter.com/kidkaido/status/1176088627891318784
> 満員で、心の温まる素晴らしい会でした。土井さんの素敵な笑顔に励まされ、憲法改正を認めないことを誓いました。 https://t.co/GI6R3syaaS

TW kidkaido（海渡雄一） 日時： 2019-09-23 08:38 URL： https://twitter.com/kidkaido/status/1175917321451233280
> いま、賛同は7700人に達しました。なんとか、一万人を超したい。 \n https://t.co/TAGASFnXy2東電刑事裁判元経営陣-無罪-判決に控訴を?recruiter=38526106&amp;utm_source=share_pe… https://t.co/WEhLBuKYNO

TW kidkaido（海渡雄一） 日時： 2019-09-22 07:06 URL： https://twitter.com/kidkaido/status/1175531730100346882
> 署名数現在4300です。もっと増やしたいです。よろしくお願いします。 \n 【緊急署名】東電刑事裁判元経営陣「無罪」判決に控訴してください！ https://t.co/pne3bHJ2Cn @lnjnowさんから

TW kidkaido（海渡雄一） 日時： 2019-09-22 00:47 URL： https://twitter.com/kidkaido/status/1175436361580462082
> 既に賛同者は3700人を超えました。24日に指定弁護士の先生方にお会いして、控訴と控訴審での指定弁護士担当の継続をお願いします。その時に第一次の署名賛同数をお伝えしたいと思います。緊急拡散をよろしくお願いします。 https://t.co/876KCFWnSF

TW kidkaido（海渡雄一） 日時： 2019-09-21 11:36 URL： https://twitter.com/kidkaido/status/1175237415507644417
> 指定弁護士の石田、神山、山内、渋村、久保内先生には、素晴らしい訴訟活動をしていただきました。集中的な業務に全力を尽くしてくださったことに、心から感謝します。 \n  判決への批判は日増しに高くなっています。ぜひとも、控訴し、控訴審も同じ… https://t.co/gKKgZzHyDu

RT kidkaido（海渡雄一）｜oguchilaw（弁護士　小口　幸人） 日時：2019-09-20 19:51／2019-09-20 09:32 URL： https://twitter.com/kidkaido/status/1174999563414859778 https://twitter.com/oguchilaw/status/1174843845822967810
> 東電無罪判決の日の朝、最高裁長官が首相官邸を訪問しているなんて…、砂川事件のときの田中最高裁長官の件を想起せざるを得ない動きです。 \n  \n まさか、判決を先行して伝えたり、控訴審・上告審の話をしたりなんてことはないと思うのですが… \n  \n 国… https://t.co/KdL87D4525

TW kidkaido（海渡雄一） 日時： 2019-09-17 18:48 URL： https://twitter.com/kidkaido/status/1173896538394771456
> 絵空事の核燃料サイクル、今やニュース価値なし？ - 石川智也｜論座 - 朝日新聞社の言論サイト https://t.co/tf58BEdXzZ \n もんじゅ後の日本政府の頼みの綱フランス・アストリッド高速炉計画が挫折。いよいよ、六ケ所… https://t.co/pkjMkALlqS

TW kidkaido（海渡雄一） 日時： 2019-09-15 11:47 URL： https://twitter.com/kidkaido/status/1173065696135139329
> 19日の東京地裁判決が迫る中で、時事通信が、東電刑事裁判の判決直前報道を流してくれました。武藤さんと私のコメントが取り上げられています。ぜひ、ご覧ください。 https://t.co/MkgFlX0NUa

　もう少し工夫が必要かと思いましたが、東電旧経営陣の強制起訴無罪判決に関連がありそうな弁護士らのツイートをまとめ記事として２つ作成しました。内容はなかなかシンプルなものとなっています。大崎事件も似たような傾向性を感じておりますが、弁護士鉄道の未来を暗示するようにも思えます。

```
アカウント名	ツイート数	リツイート数
落合洋司（オンラインチャット相談対応可）（yjochi）	1	1
小倉秀夫（Hideo_Ogura）	2	0
Shoko Egawa（amneris84）	1	0
週刊金曜日（syukan_kinyobi）	0	2
福島みずほ（mizuhofukushima）	0	1
海渡雄一（kidkaido）	1	0
ツジタワタル（弁護士）（Black_Sundae）	0	2
テレ朝news（tv_asahi_news）	1	0
NHKニュース（nhk_news）	1	0
BLOGOS編集部（ld_blogos）	1	0
時事ドットコム（時事通信ニュース）（jijicom）	3	0
ヨナタン（jonathan_1955）	0	1
朝日新聞(asahi shimbun）（asahi）	1	0
保坂展人（hosakanobuto）	0	1
山口直也 Naoya Yamaguchi（nashyama）	1	0
HRK（on_and_under）	0	1
山下真史（yama4tamasa4）	0	1
赤ネコ@弁護士兼マンガ家（Redips00）	0	1
yasaka motonori（siinokilaw）	0	1
イザ！編集部（iza_edit）	1	0
中野昌宏 Masahiro Nakano（nakano0316）	0	1
毎日新聞（mainichi）	1	0
弁護士　戸舘圭之（todateyoshiyuki）	1	0
読売新聞社会部（YOL_national）	1	0
トモシビ（lighta_ampligh）	0	1


［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”東電．＊控訴”／データベース登録済みツイートの検索：2011-07-21〜2019-09-30／2019年09月30日22時11分の記録：ユーザ・投稿：25／31件 http://hirono2014sk.blogspot.com/2019/09/regexp2011-07-212019-09.html
```

```
アカウント名	ツイート数	リツイート数
郷原信郎（nobuogohara）	6	0
Shoko Egawa（amneris84）	3	0
モトケン（motoken_tw）	4	0
47NEWS（47news）	1	0
山口一臣（kazu1961omi）	2	0
長谷川幸洋（hasegawa24）	1	0
岩上安身（iwakamiyasumi）	1	0
有田芳生（aritayoshifu）	1	0
堀江貴文(Takafumi Horie)（takapon_jp）	1	0
Ｂ54なぶさん（yotajirosan）	1	0
海渡雄一（kidkaido）	4	0
福島みずほ（mizuhofukushima）	0	4
ツジタワタル（弁護士）（Black_Sundae）	0	4
変えよう！会（kaeyoukai0608）	0	1
東京ユニオン（toukyouyunion）	0	1
中野昌宏 Masahiro Nakano（nakano0316）	0	4
週刊金曜日（syukan_kinyobi）	0	3
なかがわ　もとみつ　(中川素充)（Motomitsu_N）	1	0
テレ朝news（tv_asahi_news）	1	0
NHKニュース（nhk_news）	1	0
?弁護士 落合洋司 YOJI OCHIAI（yjochi）	0	1
BLOGOS編集部（ld_blogos）	1	0
時事ドットコム（時事通信ニュース）（jijicom）	5	0
NHK@首都圏（nhk_shutoken）	1	0
ヨナタン（jonathan_1955）	0	1
朝日新聞(asahi shimbun）（asahi）	1	0
保坂展人（hosakanobuto）	0	1
山口直也 Naoya Yamaguchi（nashyama）	1	0
HRK（on_and_under）	0	1
山下真史（yama4tamasa4）	0	1
小川慎一/Shinichi Ogawa（ogawashinichi）	0	1
弁護人弁護士奥村徹(大阪弁護士会)（okumuraosaka）	1	0
弁護士中村晃基（福山）（koukitei）	1	0
NTV NEWS24（news24ntv）	1	0
鈴木　耕（kou_1970）	0	1
赤ネコ@弁護士兼マンガ家（Redips00）	0	1
うえさん（B82SckYJ98ekhRD）	1	0
yasaka motonori（siinokilaw）	0	2
ぎたべん（guitar_ben）	0	1
東京新聞（TOKYO Web）（tokyo_shimbun）	0	1
毎日新聞（mainichi）	1	0
黒田法律事務所 弁護士黒田厚志（kurodalawoffice）	0	1
Smith目（iy0kahn）	0	1
とろろ（lit_soc）	1	1
ystk（lawkus）	1	0
弁護士　戸舘圭之（todateyoshiyuki）	1	1
スヤスヤいちご（ichigo_ba）	0	1
読売新聞社会部（YOL_national）	1	0
横井 克俊（KatsutoshiYokoi）	0	1
トモシビ（lighta_ampligh）	0	1
安藤じゅん子@千葉りっけん（andojunko）	0	1
非常上告-最高検察庁御中_ツイッター（s_hirono）	1	0
法務ニュース・訴訟速報（Sosho_Sokuho）	0	1


［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”指定弁護士．＊控訴”／データベース登録済みツイートの検索：2010-06-13〜2019-09-30／2019年09月30日22時12分の記録：ユーザ・投稿：53／85件 http://hirono2014sk.blogspot.com/2019/09/regexp2010-06-132019-09.html
```

　東電OL殺害事件や政治家小沢一郎氏の強制起訴も、同じキーワードとして検索結果に含まれていました。単純なキーワード指定になりますが、それでも乏しい数、反応の小ささはよく現れていると思います。

```
2019年09月30日21時56分の実行記録
twitterAPI-search-lawList-mydql-add.rb "東電 控訴"
ツイート数：0/1525 リツイート数：0/1525 トータル：2
hirono_hideki 0／0件
kk_hirono 0／0件
s_hirono 0／0件

［source：］奉納＼さらば弁護士鉄道・泥棒神社の物語さんはTwitterを使っています： 「2019年09月30日21時56分の実行記録 twitterAPI-search-lawList-mydql-add.rb "東電 控訴" ツイート数：0/1525 リツイート数：0/1525 トータル：2 hirono_hideki 0／0件 kk_hirono 0／0件 s_hirono 0／0件」 / Twitter https://twitter.com/hirono_hideki/status/1178655226842120192
```

```
2019年09月30日22時07分の実行記録
twitterAPI-search-lawList-mydql-add.rb "指定弁護士 控訴"
ツイート数：28/1525 リツイート数：39/1525 トータル：4826
hirono_hideki 0／0件
kk_hirono 0／0件
s_hirono 1／0件

［source：］奉納＼さらば弁護士鉄道・泥棒神社の物語さんはTwitterを使っています： 「2019年09月30日22時07分の実行記録 twitterAPI-search-lawList-mydql-add.rb "指定弁護士 控訴" ツイート数：28/1525 リツイート数：39/1525 トータル：4826 hirono_hideki 0／0件 kk_hirono 0／0件 s_hirono 1／0件」 / Twitter https://twitter.com/hirono_hideki/status/1178657707546382337
```

　「"東電 控訴" ツイート数：0/1525 リツイート数：0/1525 トータル：2」、「ツイート数：28/1525 リツイート数：39/1525 トータル：4826」がTwitterAPIでの検索結果になります。

　時刻は23時34分です。今夜は23時30分からニュースzeroが始まりました。さきほど疲れが出てけっこう眠かったのですが、指定弁護士控訴のニュースを、報道番組がどう扱うのか確認しておきたくて頑張りました。今朝は5時起きで、一応アオリイカ釣りに出かけていました。釣果は０です。

　穴水町から輪島市、柳田温泉に入って夕方に家に戻りました。気温が２７度ほどありました。汗ばむことはなかったですが、久しぶりにけっこう疲れを感じていました。急に予定が入って前の日も小木港でアオリイカ釣りをしていて、そのときは２杯釣れていました。

　時刻は２３時４５分です。あと１５分で９月も終わりですが、寒い日の少ない９月でした。なにかと調べ物や設定、準備の多い９月でしたが、次につながる収穫も多かったと思います。

　９月１９日に何をしていた思い出すことはないですが、まとめ記事の記録を確認したところ、当日の投稿というのは数が少なかったようです。

[3707]  % dp -p | grep 2019年09月19
[link:] 2019年09月19日01時05分の登録： ツイートの記録資料：＼法務検察・石川県警察宛＼／モトケン（@motoken_tw）／”2019年09月18日”：170件 http://hirono2014sk.blogspot.com/2019/09/motokentw20190918170.html
[link:] 2019年09月19日01時05分の登録： ツイートの記録資料：＼法務検察・石川県警察宛＼／深澤諭史（@fukazawas）／”2019年09月18日”：30件 http://hirono2014sk.blogspot.com/2019/09/fukazawas2019091830.html
[link:] 2019年09月19日01時06分の登録： 2019-09-18の投稿一覧＼検察・石川県警察宛記録資料＼奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中：8件 http://hirono2014sk.blogspot.com/2019/09/2019-09-188.html
[link:] 2019年09月19日21時47分の登録： ＼深澤諭史　@fukazawas＼オープンカーで地方自治体の長と一緒にパレード #法クラでワイだけ選手権 http://hirono2014sk.blogspot.com/2019/09/fukazawas_19.html
[link:] 2019年09月19日21時47分の登録： ＼ピピピーッ　@O59K2dPQH59QEJx＼他の弁護士を安易に批判できないけど、預り金口座を作ってないのは、なかなか弁解し難いと思うのがワイの肌感覚。\n\n難しいのは相 http://hirono2014sk.blogspot.com/2019/09/o59k2dpqh59qejx_19.html
[link:] 2019年09月19日21時49分の登録： ＼深澤諭史　@fukazawas＼（・∀・）８０年前にこれやりましたね。\n（＾ω＾）結果は、お察しだお http://hirono2014sk.blogspot.com/2019/09/fukazawas_23.html
[link:] 2019年09月20日01時30分の登録： ツイートの記録資料：＼法務検察・石川県警察宛＼／モトケン（@motoken_tw）／”2019年09月19日”：45件 http://hirono2014sk.blogspot.com/2019/09/motokentw2019091945.html
[link:] 2019年09月20日01時30分の登録： ツイートの記録資料：＼法務検察・石川県警察宛＼／深澤諭史（@fukazawas）／”2019年09月19日”：35件 http://hirono2014sk.blogspot.com/2019/09/fukazawas2019091935.html

　９月２０日は、少し数が多いようですが、この辺りの数が平均値に近いかもしれません。

[3709]  % dp -p | grep -E '2019年09月20日.+の登録'
[link:] 2019年09月20日01時30分の登録： ツイートの記録資料：＼法務検察・石川県警察宛＼／モトケン（@motoken_tw）／”2019年09月19日”：45件 http://hirono2014sk.blogspot.com/2019/09/motokentw2019091945.html
[link:] 2019年09月20日01時30分の登録： ツイートの記録資料：＼法務検察・石川県警察宛＼／深澤諭史（@fukazawas）／”2019年09月19日”：35件 http://hirono2014sk.blogspot.com/2019/09/fukazawas2019091935.html
[link:] 2019年09月20日01時31分の登録： 2019-09-19の投稿一覧＼検察・石川県警察宛記録資料＼奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中：7件 http://hirono2014sk.blogspot.com/2019/09/2019-09-197.html
[link:] 2019年09月20日09時08分の登録： REGEXP：”大崎事件”／データベース登録済みツイートの検索：2019-09-17〜2019-09-19／2019年09月20日09時07分の記録：ユーザ・投稿：21／25件 http://hirono2014sk.blogspot.com/2019/09/regexp2019-09-172019-09_20.html
[link:] 2019年09月20日18時26分の登録： ＼サイ太　@uwaaaa＼この種，「名誉毀損で法的措置を執る」とツイートしてる人の法的措置を執らない率は異常 http://hirono2014sk.blogspot.com/2019/09/uwaaaa_20.html
[link:] 2019年09月20日18時26分の登録： ＼深澤諭史　@fukazawas＼（・∀・）しっかし，きたんせと話すと，毎回いろいろ学びがあるな・・・。 http://hirono2014sk.blogspot.com/2019/09/fukazawas_20.html
[link:] 2019年09月20日19時22分の登録： ＼Shota ABE　@sa_stpo＼初の単著『被疑者取調べの憲法的規制』（日本評論社、2019年）を上梓致しました。\nアメリカ・Miranda法理を整理し、韓国におけ http://hirono2014sk.blogspot.com/2019/09/shota-abesastpo2019-miranda.html
[link:] 2019年09月20日19時29分の登録： ＼弁護士 市川 寛　@imarockcaster42＼私も編集委員を務めました「冤罪白書2019」が10月に発売されます。3、4日の日弁連人権大会の場でも買えるようです。 http://hirono2014sk.blogspot.com/2019/09/imarockcaster4220191034.html
[link:] 2019年09月20日20時22分の登録： ＼ぎたべん　@guitar_ben＼今回の陰謀論は無理があると思うけど、裁判所の場合普段から情報開示なさ過ぎるから疑われる面もあると思う。今回のもやましいところないなら「 http://hirono2014sk.blogspot.com/2019/09/guitarben_20.html
[link:] 2019年09月20日20時47分の登録： ＼弁護士　野田隼人　@nodahayato＼陰謀論は多数派を形成しないから政治運動には向かない。ある程度の数さえ集まれば良いもの、カルトとかテロとかには向くが、同時に態度 http://hirono2014sk.blogspot.com/2019/09/nodahayato_20.html
[link:] 2019年09月20日20時49分の登録： ＼及川智志　@ShminLo＼若者が気にしているのは、弁護士になった後のこと。弁護士の需給問題は言っていくべき。日弁連が言うべきことを言わないと、みくびられるだけでは。 http://hirono2014sk.blogspot.com/2019/09/shminlo.html
[link:] 2019年09月20日20時51分の登録： ＼きゅきゅ　@Qu2_law＼あっ、明治の先輩の深澤先生！！ライローなどが予備抜けして合格していく中、遅遅ながら予備抜けせず今年合格にに滑り込みましたm(_ _)m\n受験 http://hirono2014sk.blogspot.com/2019/09/qu2lawm-m.html
[link:] 2019年09月20日20時54分の登録： ＼ピピピーッ　@O59K2dPQH59QEJx＼朝から起案して無罪判決が書ける裁判官は、今すぐ、退官すべき。\n\n起案マシーンとして、大手事務所が億出すよ。 http://hirono2014sk.blogspot.com/2019/09/o59k2dpqh59qejx_20.html
[link:] 2019年09月20日20時54分の登録： ＼なべきょう＠過眠症　@wata_nabekyo_ko＼大量懲戒請求されたときに、検索したらたくさん出てきたよ。 http://hirono2014sk.blogspot.com/2019/09/watanabekyoko_20.html
[link:] 2019年09月20日20時57分の登録： ＼ぱね　@panaihito＼法クラツイ弁には、ある特定の要素のツイートをすれば、まず間違いなくリツイートをもらえるという話題がある。\n最も簡単にリツイートをもらえる話題 http://hirono2014sk.blogspot.com/2019/09/panaihito.html
[link:] 2019年09月20日20時59分の登録： ＼モトケン　@motoken_tw＼東電元経営陣に対する裁判で、有罪判決を予測していた法律家はどれくらいいるかな？\nツイッターの法クラアカウントに判決前の予測についてアン http://hirono2014sk.blogspot.com/2019/09/motokentw_20.html
[link:] 2019年09月20日21時02分の登録： ＼奥山俊宏　@okuyamatoshi＼福島第一原発事故の刑事裁判。指定弁護士は、４つの措置を全て終えるには相当の期間がかかるとして、その間は原発の運転を停止する義務があ http://hirono2014sk.blogspot.com/2019/09/okuyamatoshi.html
[link:] 2019年09月20日21時04分の登録： ＼モトケン　@motoken_tw＼機械的というのは違いますね。\n弁護士は（検事も）、常に相手方の言い分と証拠を検討しているということです。\n裁判官は当然双方の言い分と証 http://hirono2014sk.blogspot.com/2019/09/motokentw_31.html
[link:] 2019年09月20日21時20分の登録： ＼モトケン　@motoken_tw＼でっち上げじけんの場合は、刑事事件に強い弁護士がおススメ。 http://hirono2014sk.blogspot.com/2019/09/motokentw_28.html
[link:] 2019年09月20日21時21分の登録： ＼モトケン　@motoken_tw＼この件は検察官役をやってみたかった。＞東電会長ら旧経営陣３人に無罪判決　原発事故で強制起訴：朝日新聞デジタル http://hirono2014sk.blogspot.com/2019/09/motokentw_95.html
[link:] 2019年09月20日21時23分の登録： ＼モトケン　@motoken_tw＼ツイッターじゃなくて、弁護士の事務所で弁護士に相談してください。 http://hirono2014sk.blogspot.com/2019/09/motokentw_55.html
[link:] 2019年09月20日21時25分の登録： ＼Shoko Egawa　@amneris84＼郷原弁護士は、「そもそも起訴するような事件ではなかった。裁判でも時間をかけて補充立証するなど、非常に無責任な対応。検察には http://hirono2014sk.blogspot.com/2019/09/shoko-egawaamneris84_20.html
[link:] 2019年09月20日21時29分の登録： ＼Shoko Egawa　@amneris84＼病院もひどいが、その代理人弁護士も相当にひどい￼　→HIV内定取り消し訴訟、法廷では被告側の代理人から差別的な表現の質問も http://hirono2014sk.blogspot.com/2019/09/shoko-egawaamneris84hiv.html
[link:] 2019年09月20日21時31分の登録： ＼?弁護士 落合洋司 YOJI OCHIAI　@yjochi＼風俗店火災、元社長ら不起訴＝さいたま地検 - 弁護士落合洋司（東京弁護士会）の日々是好日 http://hirono2014sk.blogspot.com/2019/09/yoji-ochiaiyjochi.html
[link:] 2019年09月20日21時31分の登録： ＼?弁護士 落合洋司 YOJI OCHIAI　@yjochi＼東電旧経営陣に無罪判決　刑事司法の限界示す - 弁護士落合洋司（東京弁護士会）の日々是好日 http://hirono2014sk.blogspot.com/2019/09/yoji-ochiaiyjochi_20.html
[link:] 2019年09月20日21時35分の登録： ＼?弁護士 落合洋司 YOJI OCHIAI　@yjochi＼ソープって、お風呂に入っている間に自由恋愛だから無罪じゃなかったっけ？笑\n→北九州市最大のソープランド摘発　 http://hirono2014sk.blogspot.com/2019/09/yoji-ochiaiyjochi_68.html
[link:] 2019年09月20日21時36分の登録： ＼ʇɐɯɐɹnɯʞ　@kmuramatsu＼刑法ゼミで、組織のミスについて誰か個人に刑事責任を問うのはやはり相当難しいんじゃないか。みたいな話をしてた２０年前。\n個人主義 http://hirono2014sk.blogspot.com/2019/09/nkmuramatsu.html

　記録として残していたようですが、次のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートというのは、ちょっと記憶にありませんでした。なかなか味わいのある内容です。

```
記録作成等の措置を講ずるべき弁護士・ジャーナリスト関連のツイート
基準となる注目のツイートを含む最新199件のツイート
2019-09-18 12：44から199件：最新2019-09-20 19：04という範囲（2日6時間20分）の取得
基準となる注目ツイートの位置と内容タイムラインの該当箇所に移動

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： ＼モトケン　@motoken_tw＼この件は検察官役をやってみたかった。＞東電会長ら旧経営陣３人に無罪判決　原発事故で強制起訴：朝日新聞デジタル http://hirono2014sk.blogspot.com/2019/09/motokentw_95.html
```

　９月２０日が金曜日と表示されていました。東電旧経営陣の強制起訴無罪判決があった19日は木曜日になりますが、何をしていたかとなると思い出せません。ニュースは早い段階でテレビで見ていたようには思います。

```
294件目 » 2019-09-19_005852＿テレビの画面・.jpg

［link：］ 2019-09-19_005852＿テレビの画面・.jpg http：//hirono2014sk.blogspot.com/2019/09/2019092501592019-08-311136102019-09.html#20190919005852#20190919005852

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： 2019年09月25日01：59記録＼法務検察・石川県警察宛＼テレビの画面撮影資料：2019-08-31_113610〜2019-09-25_000231：407件 http://hirono2014sk.blogspot.com/2019/09/2019092501592019-08-311136102019-09.html#20190919005852
```

　調べたところ、9月19日というのはテレビの画面撮影の記録が1件のみでした。少し記憶にあるものですが、深夜番組で日付が変わってから撮影したものです。「大島寅さんのバカヤロー飯　調布の絶品グルメベスト3！」とあります。なんとなくその場の気分で撮影したものです。

　9月20日も数が少なく4件ほどです。21日は０のようです。２２日も数が少ないですが、２３日となると数が増えて、台風１７号関係のものが多くありました。こういうのも記憶の喚起に役立ったり、なにかの証明に役立つ場合もあるかと思っています。

　確認したところスマホの写真は9月13日12時37分57秒以降のものがアップロード待ちの状態でした。9月19日はキーボードの壊れた古いノートパソコンにUbuntuをインストールしていた形跡がありました。9月20日の北陸中日新聞に東電旧経営陣の無罪判決の記事を撮影していました。

　そういえばさきほどニュースzeroが終わってテレビを消しましたが、東電旧経営陣無罪判決の指定弁護士控訴というニュースはなかったと思います。金沢のニュースで保育園児の散歩のような場面があって、コスモスと出ていた花のことが気になりました。見覚えのない花です。

　日付が変わっっていますが、穴水町で彼岸花を見ました。走行中の車内から見たのでよくわからなかったですが、1〜２年ほど前にテレビかなにかで見た彼岸花も、実際に見た覚えがなかったので気になっていました。曼珠沙華という別名もあるとのことです。

　コスモスという花の名前もよく知っているつもりでしたが、実際にどういう花なのか考えたこともなかったようです。園児の背丈以上の大きさで、自然に自生しているように見えましたが、見覚えのない花だと思いました。

　東電旧経営陣強制起訴の検察官役指定弁護士の面々も、この世に咲く不思議な花に思えてきましたが、世間の関心の乏しさが気になっています。マスコミの扱いも同様です。もうだいぶん前から再審の裁判でも、ニュース以外に情報番組でリアルに取り上げるのを見かけません。

〈〈〈：Emacs： 2019-10-01（火曜日）00：59 　〈〈〈

