#+TITLE: "控訴審判決に対する上告率や唐の大宗が出てきた「大崎事件最高裁決定を、司法を変えていく反転攻勢の糸口としなければならない」（海渡雄一弁護士）"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-09-30 20:52:53 +0900
FILE_NAME: 2019-09-30-205253_控訴審判決に対する上告率や唐の大宗が出てきた「大崎事件最高裁決定を、司法を変えていく反転攻勢の糸口としなければならない」（海渡雄一弁護士）.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 海渡雄一弁護士,上告,大崎事件,Facebook
記事タイトル名の文字数：69　保存ファイル名の文字数：91
#+STARTUP: showeverything


* 控訴審判決に対する上告率や唐の大宗が出てきた「大崎事件最高裁決定を、司法を変えていく反転攻勢の糸口としなければならない」（海渡雄一弁護士）
  :LOGBOOK:
  CLOCK: [2019-09-30 月 20:54]--[2019-09-30 月 21:37] =>  0:43
  :END:

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 海渡雄一弁護士,上告,大崎事件,Facebook

〉〉〉：Emacs： 2019-09-30（月曜日）20：54　 〉〉〉

　ずっと気になっていたのですが、確認も兼ねて記事を探すと予想以上に手間取りました。大崎事件の最高裁決定に関する記事に含まれていたことも忘れていたので、探すにも手掛かりが掴みづらくありました。

　7月18日という日付の特定がTwilogから出来たことが、たどり着く道筋となりました。これも記憶が曖昧だったスクリーンショットの記録が発見できたのですが、迷いはあったものの記録の必要性を強く感じたことが、今回の発見に至る道標となりました。

　しかし、Facebookの記事のスクリーンショットだと、Twitterのように短文で日付が入っていないので記事の特定は簡単ではありませんでした。スクリーンショットの記録を遡ると、大崎事件に関する記事があって、そこに当たりをつけて、内容を確認、照合することが出来ました。

　海渡雄一弁護士の投稿数が少なめというのも大いに幸いしました。逆に言えば、投稿数が少ないので見つけやすいだろうと、すぐに確かな備忘録を作成して置かなかったことが、今回の時間のロスにもなりました。

　記事の見出しと思われる部分には「「大崎事件最高裁決定を、司法を変えていく反転攻勢の糸口としなければならない」とあります。非常にメッセージ性の高いものを感じますが、弁護士業界の歴史的な疑問点、不信感につながるものも感じます。

　前提となるところをしっかり押さえた上で、指摘等を行っていきたいので、一般的なマナーとしてはどうかとも思い、迷うところもありましたが、長文をそっくりそのまま次に全文引用することにします。

```
Yuichi Kaido
7月15日 · 
まだ最高裁はあるか？
　大崎事件最高裁決定を、司法を変えていく反転攻勢の糸口としなければならない

　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　海渡　雄一

　本稿は、大崎事件最高裁決定後の記者会見で、鴨志田祐美弁護士が原口さんの無念を想い、悔し涙を流されていたお姿を拝見し、深く感動を覚え、微力ながら、今の最高裁をむしばむ病巣の根源に迫ろうと思索を重ねて起案したものです。

大崎事件最高裁決定の衝撃
　最高裁判所第一小法廷（小池裕裁判長、池上政幸、木澤克之、山口厚、深山卓也裁判官）は、６月２５日付で、大崎事件第３次再審請求特別抗告審において、再審開始を認めた原決定（福岡高裁宮崎支部）および原々決定（鹿児島地裁）を取り消し、自判して原口アヤ子さんの雪冤の願いを無惨に踏みにじる再審請求を棄却すると決定した。
　決定はその冒頭で「本件抗告の趣意は、判例違反をいう点を含め、実質は単なる法令違反、事実誤認の主張であって、刑訴法４３３条の抗告理由に当たらない」と述べている。にもかかわらず、職権で判断をするとして、事件の中身について判断を進めている。
　最高裁は通常の裁判手続きで高裁の判断を覆すときには、口頭弁論を開き、当事者の意見を直接聞く。ところが、本件では弁護人の意見を聞く機会を設けたことすら一度もなかった。地裁と高裁が再審開始を判断した際の決め手となる吉田鑑定意見書について、最高裁は、吉田氏の高い見識を認めている。にもかかわらず、最高裁は、遺体の腐敗が著しく、また写真のみによる鑑定であることから、吉田鑑定の証明力には限界があるなどとして、吉田氏に説明や反論の機会さえ与えず、差し戻しではなく自判し、破棄しなければ著しく正義に反するとして再審開始の一、二審決定を覆したのだ。このような判断手法は、えん罪に泣く者への同情心のかけらも最高裁判事は持ち合わせていないことを示している。
　私が、まず指摘したいことは、最高裁が、再審以外の通常事件において、高裁の有罪判決を破棄する例がほとんどなくなってきていると言うことである。八海事件や松川事件では最高裁によるえん罪の救済が図られ、「まだ、最高裁がある」が、被告人と救援者の合い言葉だった時代があった。
　最近の実情はどうであろうか。過去3年分（平成２８，２９，３０年度版）の犯罪白書をみてみる。
　平成27年に言い渡された控訴審判決に対する上告率（控訴棄却の決定，控訴の取下げ，公訴棄却の決定及び移送等による終局を除く終局処理人員に対する上告人員の比率）は，37.5％であった。同年における最高裁判所の上告事件の終局処理人員は，1,891人（第一審が高等裁判所であるものを含む。）であり，その内訳は，上告棄却1,565人（82.8％），上告取下げ317人（16.8％），公訴棄却決定9人であった（司法統計年報による。）。
　平成28年に言い渡された控訴審判決に対する上告率（控訴棄却の決定，控訴の取下げ，公訴棄却の決定及び移送等による終局を除く終局処理人員に対する上告人員の比率）は，40.2％であった。同年における最高裁判所の上告事件の終局処理人員は，1,957人（第一審が高等裁判所であるものを含む。）であり，その内訳は，上告棄却1,597人（81.6％），上告取下げ351人（17.9％），公訴棄却決定6人（0.3％）であった（司法統計年報による。）。
　平成29年に言い渡された控訴審判決に対する上告率（控訴棄却の決定，控訴の取下げ，公訴棄却の決定及び移送等による終局を除く終局処理人員に対する上告人員の比率）は，40.9％であった。同年における最高裁判所の上告事件の終局処理人員は，2,106人（第一審が高等裁判所であるものを含む。）であり，その内訳は，上告棄却1,776人（84.3％），上告取下げ327人（15.5％），公訴棄却決定2人，破棄自判1人（自判内容は無罪）であった（司法統計年報による。）。
　つまり、上告を容れて、無罪方向で原判決を破棄した事件は過去３年間でわずか一件だけであると言うことである。そのような最高裁が、再審開始を棄却する方向で、検察官の特別抗告を容れたのであるから、最高裁の目線がどちらを向いているか、明らかではないか。このような判断は、下級審裁判官に対して、「再審開始」などという判断は控えよという強力なメッセージとなっただろう。
　えん罪は国家権力の行使によって生ずる様々な人権侵害の中で、最も悲惨なものである。　であるからこそ、えん罪を生み出さないための刑事裁判制度が構想され、自白獲得のための拷問を禁止し、「疑わしきは被告人の利益に」という証拠法則の徹底が図られてきた。従来、えん罪の克服はヨーロッパにおける刑事裁判制度の発展に沿って理解され、日本の刑事裁判制度はこれを追う必要があると説かれてきた。もちろん、このような立論は間違っていない。
　しかし、この大崎事件の最高裁決定は、我が国の最高裁が、えん罪の救済ではなく、再審開始を徹底して妨害し、多少のえん罪犠牲者を生み出しても、犯罪者の必罰を図るという意思をあきらかにしたように、私には見える。司法はえん罪の救済という任務を放棄したのだろうか。これは、司法を仕事の場とする私たち弁護士に対してはもちろんのこと、市民社会全体に対する衝撃的なメッセージである。

イギリスの刑事再審委員会制度は機能しているか？
　本年の３月イギリス・レディング大学で教鞭を執られていた佐藤舞氏が、ホイル教授と共著でオックスフォード大学出版会から「Reasons to doubt疑う理由　誤った判決とイギリス刑事再審委員会」を出版された(Oxford University Press、2019)。これは、イギリス(スコットランドを除く)刑事事件再審査委員会(Criminal Cases Review Commission) の活動に関する研究である。
　刑が確定した刑事事件のうち、どのような事件に関して同委員会が、「えん罪である可能性が高い (real possibility test) 」という判断を下しているのかを分析したものである。佐藤氏らは、３年間をかけ事件ファイルの内容分析および調査員へのインタビューを行い、社会学的観点から委員会の活動を実証的に明らかにした。
　１９９１年「バーミンガム６人事件」について、控訴院が有罪判決を破棄した。この衝撃的なえん罪について「刑事司法に関する王立委員会」が設立された。１９９３年には王立委員会報告書提言No. 331が公表された。１９９５年刑事上訴法が制定され、１９９７年には、刑事事件再審委員会が設立された。
　この委員会は、えん罪の救済目的のために特化された国家機関である。そして、同法の１７条によって、外部機関から文書を入手する権限が与えられ、申し立てられた事件の５９％のケースで、この権限が適用されている(２０１１－２０１３)。平均１ケースにつきう４．９回適用され、裁判所、警察、検察、社会福祉、医者、学校等から情報が集められる。日本では再審請求弁護人がやるような仕事を委員会が証拠収集の権限を持ってやってくれるのである。
　委員会では、本人が簡単に読み、書き込むことのできる申し立てフォームを作成している。このような努力によって、委員会では、１９９７年から２０１９年１月までに24,658の請求を受け、658 件を控訴院に付託し、そのうち437件で控訴院が有罪判決を破棄している。控訴院への付託決定に検察官が異議を申し立てるような仕組みは設けられていない。年間の請求数は1,000-1,400件程度で推移し、付託率は０．８から３％で推移している。この制度によって、毎年平均すれば約２０件程度の再審無罪判決が出されていることになる。
　決して高率ではない。しかし、日本における再審事件の救済率に比べれば、比較にならないほど高い。日本の刑事訴訟制度がイギリスのそれに比べて格段に優れているのでなければ、イギリスで毎年２０件の再審無罪判決があるのに、日本では本当に数えるほどしか再審が開始されない実情は、日本の司法制度がえん罪救済のために機能していないと言うことを示しているといわなければならないだろう。

台湾における再審のための証拠開示制度
　今年の３月２日に結成された冤罪犠牲者の会で記念講演を行った李怡修氏（一橋大学）は、次のように報告している。
李氏は台湾イノセンス・プロジェクト(TIP)での活動経験をもつ。
　台湾では、事件が確定すると、捜査段階から公判段階、確定判決までに収集されたすべての証拠が「一件記録」として保管される。再審を申し立てようとする弁護人は、このすべてを自由に閲覧・謄写することができる。請求人(元被告人)自身も同様に全証拠にアクセスできるよう、法改正されることが決まっている。つまり日本のように、証拠開示請求する必要性そのものが存在しないのである。

中国における冤罪救済の進展
　中国においても、冤罪救済のための大きな流れが見られる。
　「2016年12月2日、20年以上も経過した聶樹斌事件の無罪判決がようやく言い渡され、この長年にわたり冤罪が叫ばれ続けてきた事件がついに解決された。聶樹斌さんは1995年に故意の殺人と婦女強姦の罪を問われ、有罪判決の上、死刑が執行された。2014年12月12日、最高裁は山東省高級人民法院（高裁）に対し、同事件の再審査を命じた。事件の劇的な進展とその複雑性、特殊さだけでなく、その冤罪から経過した月日の長さ、事件の再審の難しさ、そして関心の高さのいずれをとっても、同事件は中国司法においてシンボルとなる事件だと言われている。
　冤罪事件の再審はいずれも社会の公平さと正義について、新たな解釈となるものだ。先ごろ、最高裁は「中国法院の司法改革（2013-2016）」白書を公表した。同白書には2013年から2016年までの間に、中国の各レベルの裁判所で法に基づく無罪判決を受けた被告は3718人、そして国の賠償案件は16889件となり、その賠償金額は69905.18万元（1元は約16.6円）にのぼることを明らかにし、「2016年は全国の裁判所で過去4年間の重大冤罪事件23件、被告37人の再審を行ったほか、新たに冤罪事件11件、被告17人の再審が行われた。これは過去最高の件数となった」としている（北京週報　２０１７年３月１３日「3年間で冤罪無罪判決3718人　中国の司法分野、人権保障へ新たな動き」）。
　中国政府による少数民族や政治的反対派に対する刑事司法を適用した厳しい抑圧は、国際的に強く批判されている。このような動きも、国際社会からの批判を意識したものと見る見方もあるだろう。しかし、中国の最高裁は、冤罪の救済を最重要課題として明確に認識していることだけは確かである。そして、日本の最高裁には、この基本認識が欠けているのである。

唐の大宗は、宰相の最重要の仕事は冤滞の救済であると述べている
　今の日本のえん罪救済制度の実効性は、ヨーロッパ諸国や台湾、中国における制度に比べて遅れているだけでなく、遠い古代の中国や日本の王朝時代の制度と比べても、その精神において明らかに後退しているように思われる。最高裁の裁判官諸氏に、自らのよって立つ理念を思い返していただくために、話を古代にまでさかのぼることを許されたい。
　古代中国では、冤罪をなくすと言うことは、古来君主の最も大切な任務であると考えられてきた。唐の史官である呉兢が編纂したとされる聖君太宗の言行録「貞観政要」は、今も人生訓として読み継がれている名著であるが、ここにはつぎのような太宗の文言が書き留められている。

「【論択官　第４】
貞観二年、太宗、房玄齢・杜如晦に謂ひて曰く、卿は僕射たり。当に朕の憂を助け、耳目を広開し、賢哲を求訪すべし。比聞く、卿等、詞訟を聴受すること、日に数百有りと。此れ即ち符牒を読むに暇あらず、安んぞ能く朕を助けて賢を求めんや、と。因りて尚書省に勅し、細務は皆左右丞に付し、惟だ冤滞の大事の、合に聞奏すべき者のみ、僕射に関せしむ。」
僕射とは、尚書省の長官であり、簡単に言えば宰相のことである。この時代、行政権のトップが司法権も行使していた。宰相は最高裁の長官も兼ねていたといえる。そして宰相の最大の任務は、刑事裁判において冤罪に泣いている者がいないかを検討することだと太宗は述べているのである 。

慮囚制度とは
　もう少し詳しく、唐代の冤罪の救済の仕組みを検討してみたい。日本と中国の法制史の大家である瀧川政次郎博士の米寿記念論集『律令制の諸問題』に島善高氏の執筆された「唐代慮囚考」という興味深い論考が収録されている。

　この論文には、慮囚制度の沿革・目的・手続き・効果が論述されている。慮囚とは本來「録囚徒」と記し、文字通りに読めば、囚人を記録するということである。前漢の時代にすでにみられ、後漢には制度化されていた。それは、京兆尹や刺史等の地方長官が管内を巡行して獄囚に冤罪や滯獄で苦しむ者の有無を審理し、冤滯者があるときには正しい剣決を與え―平反という―、訴訟を速やかに決着させることであった。
　皇帝の行なう臨時の「録囚徒」も後漢の頃より見られ、その際には輕犯者を赦免する場合もあった。臨時の「録囚徒」は魏晉南北朝、さらには唐代においても頻繁に行なわれ、唐代ではこれを「慮囚」とも表記したという。
　島によれば、古代中国においては、様々な災害は為政者の悪政が招いたものと考えられ、その悪政の究極のものが冤罪だと考えられていたという。であるから、冤罪者を出さないことは、国家の存立に関わる大事であると考えられていたのである。
　君主の悪政とりわけえん罪を正さないことによって深刻な自然災害が起きるという思想を迷信と呼ぶことはたやすい。しかし、この時代の為政者には、えん罪に泣く者とその家族の悲嘆の大きさを想像することができたと見ることも許されるだろう。そして、このような感覚は、一部の軍事独裁国家の司法機関を除けば、現代の世界の司法機関のトップの多くが共有している考え方であるといえるだろう。そして、我々にとっての悲劇は、現代日本の最高裁には、このような想像力すら枯渇してしまったようであるということである。

聖武天皇は、獄を訪ねえん罪に泣く者がないかを調べる詔勅を発している
　日本ではどうか。日本でも、奈良時代に冤罪に泣く者がいないかを獄を訪ねて確認せよと命じた天皇がいた。奈良時代の天皇、聖武天皇である。『続日本紀』から引用する。
「神亀二年（６２５年）十二月二十一日
　次のように詔した。死んだ者は生き返ることができない。処刑された者はもう一度息をふき返すことがない。これは古典にも重要なこととされたことである。刑の執行に恵みを垂れることがなくてよかろうか。今刑部省の奏上した在京および天下諸国の現に獄につながれている囚徒のうち、死罪の者は流罪に、流罪の者は徒罪（ずざい）に減刑せよ。徒罪以下の者については、刑部省の奏上のようにせよ。」（『聖武天皇　責めはわれ一人にあり』森本公誠（２０１０年　講談社）より）
　神亀六年（６２９年）二月に「左道を学び、国を傾けんとした」との嫌疑を掛けられ、長屋王および吉備内親王所生の諸王が邸内で自尽させられる「長屋王の変」が起きた。長屋王は天武天皇の長男である高市皇子の子であり、母は天智天皇の皇女の御名部皇女であった。この事件は、藤原四兄弟によって皇位継承権を持つと考えられた長屋王家の抹殺が図られた事件と考えられている。聖武天皇は、長屋王の変が起きた時の天皇であり、藤原不比等の孫であり、この事件について許可を与えていたと思われる。しかし、長屋王に現実に謀反の計画があったとする証拠はなく、これは『続日本紀』にも「誣告」であったと記されている。聖武天皇の心の裡には、そそのかされたとはいえ、無実の長屋王の命を奪った後悔の念が生涯消えなかったと考えられる。太宰府で開かれた梅花の宴は長屋王の親友であった大伴旅人によってこの悲しい事件の翌年に催された。
　「天平三年（７３１年）一一月一六日
聖武天皇が平城京を巡幸中、監獄のそばを通られると、囚人たちの悲しみ、叫ぶ声が聞こえてきた。天皇はそれに憐れみの心をいだかれ、使いを遣わして、罪状の軽重を刑部省に再審査させるよう命じられた。その結果恩赦が与えられ、死罪以下すべての囚人の罪が減免されることとなった。併せて、囚人に衣服が下賜され、罪人たちが自らの過ちを悔い改めて、更生を図るようにさせられた。」（『聖武天皇　責めはわれ一人にあり』より）冤罪を起こしてはならない。冤罪を正さなければならないという考えは、奈良時代の日本にも確かに存在した。
　
なぜ、日本では３００年余にわたって死刑の執行が停止されたのか
　８１０年に薬子の変で、藤原仲成が誅された後には、死刑が言い渡されても、死罪を遠流か禁獄に減刑することが慣行化した。嵯峨天皇の時代である。これ以来日本は３４７年間という長期間にわたって，律令による死刑は執行されなかった。
　このような死刑の執行停止状況が長く続いた理由については、殺生を戒める仏教の影響を指摘する考え方がある。えん罪による処刑とこれに起因すると信じられた「祟り」による災害を懸念したとの考えもある。
　そもそも、唐代の律令に比べ、日本の大宝律令。養老律令の定める刑罰が軽かったという指摘もある（石井良助『法制史』４７頁以下）。８１８年には、盗犯に対する死刑が事実上廃止された（団藤重光『死刑廃止論』第5版　２６４頁）。
　平安時代の中期まで編纂されていた国史（日本後紀、続日本後紀など）には、災害などをきっかけとして、罪を赦すとの詔勅が無数に収録されている。当時の日本は、中国の制度を手本としていたのであるから、唐代に盛んに行われていた慮囚の考え方は、奈良、平安朝の日本でも共有化されていたのではないか。
　飛鳥時代、奈良時代から平安前期の時代を見ると、多くの皇族や高官が冤罪を疑われる嫌疑や陰謀の犠牲となって処刑されている。山背大兄王子、有馬皇子、大津皇子、長屋王、井上内親王、藤原薬子らがそれである。８１０年に薬子の変で藤原仲成が処刑されたのが、最後の処刑とされており、この事件が嵯峨天皇が死刑の執行の停止を命ずるきっかけとなったのではないだろうか。
　日本の近世には死刑廃止の思想はなかったと考えられてきた。しかし、団藤重光によれば、江戸時代の陽明学の流れの中には死刑廃止と親和性を持つ、考えが見られるという。徳川家光の孫で尾張藩主であった徳川宗春は、著書『温知政要』の中で、慈忍こそが中心思想であり、刑罪はたとい千万人中一人を誤って刑しても取り返しがつかず、天理に背き国持の大恥であると論じているという。そして、その１０年間の治世で死刑を行わなかったという（団藤重光『死刑廃止論』第5版　２７２頁）。
　冤罪で人を刑すれば、取り返しがつかず、その怨念が大きな災害をもたらすという考え方は世界各国にみられ、死刑の執行の停止をもたらしてきたことは疑いない。

いまこそ求められる再審に関する法制度の改革
　このように、新たに冤罪を生み出さない、冤罪に泣くものを確実に救うことは、古代の中国でも、古代の日本でも均しく国政の最重要事項と考えられてきた。
　最高裁による大崎事件の再審開始棄却決定という極めつきの不当決定に、メディアも心ある市民も、いま最高裁に起きている異常な事態に気づきつつある。いま、最高裁には袴田事件の特別抗告審が係属中であり、袴田巌氏の自由か死かを、最高裁はまもなく判断しなければならない。最高裁判所は、冤罪の救済こそが司法の至高の役割であるということを今一度思い出すべきである。
　そして、最高裁の自覚を促すために、国会は再審に関する法制度を改革しなければならない。まず、再審開始決定に対する検察官抗告を認める制度を改めなければならない。この制度こそが、冤罪の救済を阻んでいる元凶だ。そして、再審請求人には、当該事件について捜査機関が収集したすべての証拠の開示を求める権利を保障しなければならない。大崎事件の最高裁決定を、日本の刑事司法を変えていく反転攻勢の糸口としなければならない。

［source：］Yuichi Kaido - まだ最高裁はあるか？ 　大崎事件最高裁決定を、司法を変えていく反転攻勢の糸口としなければならない... https://www.facebook.com/permalink.php?story_fbid=669958863428596&id=100012434656292
```
　前に一通り読んでいますが、それも7月18日のことだったとついさきほどスクリーンショットの記録をみて気がついたところです。よく憶えていない部分もありますが、さきほど拾い読みをしたところ、唐の大宗などが出ていました。

　個人的に中国の唐の時代で思い出すのは則天武后なのですが、読んだ本の中で法律や統治に関する事柄もあったように思います。「ネズミをさばいた男」というような天変小説で出てきた人物も唐の時代の裁判官であったように思いますし、さきほど他に思い出したこともあります。

[link:] » 鼠を裁いた男の著者・刊行日 Weblio辞書 https://t.co/pwEREZrRoV \n 鼠を裁いた男 \n 作者伴野朗 \n  \n 収載図書反骨列伝 \n 出版社PHP研究所 \n 刊行年月1996.1

[link:] » 鼠　裁いた　男 - Google 検索 https://t.co/DIH9SxBlfZ

[link:] » 反骨列伝 / 伴野 朗【著】 - 紀伊國屋書店ウェブストア https://t.co/U9jDNTWnbj \n 目次 \n 鼠を裁いた男―張湯

```
中国，前漢の武帝時代の酷吏。京兆，杜陵 (陝西省長安県南東) の人。初め長安の吏となり，昇進して廷尉となり，法を定めて官吏の監察を厳にし，淮 (わい) 南，衡山などの謀反の獄を治めた。次いで御史大夫となり，匈奴征伐，告緡 (びん) の令，塩鉄の専売など過酷な政策を行い，反対派に弾劾されて自殺した。

［source：］張湯(ちょうとう)とは - コトバンク https://kotobank.jp/word/%E5%BC%B5%E6%B9%AF-98112
```
　
　張湯という名前を思い出すのも時間がかかりましたが、私の勘違いで唐ではなく前漢の武帝の時代でした。もう一つ思い出した名前は魏徴でしたが、こちらは唐の時代だったと思います。

[link:] » 魏徴 述懐 - Google 検索 https://t.co/ttMd3T5JJF

```
<有名な漢詩の一節>
人生意気感 功名誰復論

人生意気に感ず、功名誰か復た論ぜん

人生は意気に感じて立つもので、功名など論ずべきものでない。唐が興る時に筆(学問)を投じて戦線に向かう魏徴が決意を述べたもの。草創期の男たちを鼓舞してきた詩句。

［source：］「述懐」魏徴とは - コトバンク https://kotobank.jp/word/%E3%80%8C%E8%BF%B0%E6%87%90%E3%80%8D%E9%AD%8F%E5%BE%B4-899185
```
　次もずいぶん久しぶりに思い出した気がしますが、これも唐の時代ものとして本で読んだように思います。詠まれているのは前漢の劉邦と争い破れた楚の項羽です。

```
烏江亭に題す<杜牧>
勝敗は兵家も　事期せず
羞を包み恥を忍ぶは　是れ男兒
江東の子弟　才俊多し
巻土重來　未だ知る可からず

［source：］題烏江亭 - 中国の漢詩 - 漢詩・詩歌紹介 - ［学ぶ］ - 関西吟詩文化協会 http://www.kangin.or.jp/learning/text/chinese/k_A4_184.html
```

　前に海渡雄一弁護士のFacebookの記事を読んだときは思い出さなかったことが、今回はぞろぞろと出てきたのですが、なにか気にかかるものがあって、もやもやを感じたいたとも思うのですが、今回思い出すことが出来ていくらかすっきりしました。

　再度、海渡雄一弁護士のFacebookの記事から引用をしますが、次の部分は刑事弁護の歴史、沿革においてとても大きな意味を持つ資料だと思います。Facebookの中に埋もれたかたちと思えてならないのですが、ここに弁護士側の落ち度や悪意、偽装という要素は全く含まれていません。

```
最近の実情はどうであろうか。過去3年分（平成２８，２９，３０年度版）の犯罪白書をみてみる。
　平成27年に言い渡された控訴審判決に対する上告率（控訴棄却の決定，控訴の取下げ，公訴棄却の決定及び移送等による終局を除く終局処理人員に対する上告人員の比率）は，37.5％であった。同年における最高裁判所の上告事件の終局処理人員は，1,891人（第一審が高等裁判所であるものを含む。）であり，その内訳は，上告棄却1,565人（82.8％），上告取下げ317人（16.8％），公訴棄却決定9人であった（司法統計年報による。）。
　平成28年に言い渡された控訴審判決に対する上告率（控訴棄却の決定，控訴の取下げ，公訴棄却の決定及び移送等による終局を除く終局処理人員に対する上告人員の比率）は，40.2％であった。同年における最高裁判所の上告事件の終局処理人員は，1,957人（第一審が高等裁判所であるものを含む。）であり，その内訳は，上告棄却1,597人（81.6％），上告取下げ351人（17.9％），公訴棄却決定6人（0.3％）であった（司法統計年報による。）。
　平成29年に言い渡された控訴審判決に対する上告率（控訴棄却の決定，控訴の取下げ，公訴棄却の決定及び移送等による終局を除く終局処理人員に対する上告人員の比率）は，40.9％であった。同年における最高裁判所の上告事件の終局処理人員は，2,106人（第一審が高等裁判所であるものを含む。）であり，その内訳は，上告棄却1,776人（84.3％），上告取下げ327人（15.5％），公訴棄却決定2人，破棄自判1人（自判内容は無罪）であった（司法統計年報による。）。
　つまり、上告を容れて、無罪方向で原判決を破棄した事件は過去３年間でわずか一件だけであると言うことである。そのような最高裁が、再審開始を棄却する方向で、検察官の特別抗告を容れたのであるから、最高裁の目線がどちらを向いているか、明らかではないか。このような判断は、下級審裁判官に対して、「再審開始」などという判断は控えよという強力なメッセージとなっただろう。
　えん罪は国家権力の行使によって生ずる様々な人権侵害の中で、最も悲惨なものである。　であるからこそ、えん罪を生み出さないための刑事裁判制度が構想され、自白獲得のための拷問を禁止し、「疑わしきは被告人の利益に」という証拠法則の徹底が図られてきた。従来、えん罪の克服はヨーロッパにおける刑事裁判制度の発展に沿って理解され、日本の刑事裁判制度はこれを追う必要があると説かれてきた。もちろん、このような立論は間違っていない。

［source：］Yuichi Kaido - まだ最高裁はあるか？ 　大崎事件最高裁決定を、司法を変えていく反転攻勢の糸口としなければならない... https://www.facebook.com/permalink.php?story_fbid=669958863428596&id=100012434656292
```

〈〈〈：Emacs： 2019-09-30（月曜日）21：37 　〈〈〈


