#+TITLE: "「本日30日午後三時過ぎに指定弁護士が控訴の手続きを取りました。皆さんの願いが叶いました」（海渡雄一弁護士）東電旧経営陣強制起訴・無罪判決"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-09-30 22:23:31 +0900
FILE_NAME: 2019-09-30-222331_「本日30日午後三時過ぎに指定弁護士が控訴の手続きを取りました。皆さんの願いが叶いました」（海渡雄一弁護士）東電旧経営陣強制起訴・無罪判決.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 海渡雄一弁護士,東電,強制起訴,指定弁護士
記事タイトル名の文字数：69　保存ファイル名の文字数：91
#+STARTUP: showeverything


* 「本日30日午後三時過ぎに指定弁護士が控訴の手続きを取りました。皆さんの願いが叶いました」（海渡雄一弁護士）東電旧経営陣強制起訴・無罪判決
  :LOGBOOK:
  CLOCK: [2019-09-30 月 22:24]--[2019-09-30 月 22:50] =>  0:26
  :END:

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 海渡雄一弁護士,東電,強制起訴,指定弁護士

〉〉〉：Emacs： 2019-09-30（月曜日）22：24　 〉〉〉

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:35／2019/08/14 17:29 URL： https://twitter.com/kk_hirono/status/1178664755755536386 https://twitter.com/kidkaido/status/1161555453865791490
> 香港で、日本で、中国で、そして世界中で表現の自由に対する抑圧が強まっている。どうしたら、政治と社会に寛容さを取り戻せるのか。 https://t.co/oOjoySB3ps
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:34／2019/08/19 17:16 URL： https://twitter.com/kk_hirono/status/1178664507393970178 https://twitter.com/kidkaido/status/1163364206273413120
> 「若者を守れ」香港で教員がデモ、愛国教育に反発も：日本経済新聞 https://t.co/KBp2CLBWIl 学生を守るために、教員が立ち上がった。この闘いには香港の未来がかかっている。香港頑張れ! 私たちも共にいる。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜ISOKO_MOCHIZUKI（望月衣塑子） 日時：2019-09-30 22:34／2019/08/20 10:04 URL： https://twitter.com/kk_hirono/status/1178664481133494272 https://twitter.com/ISOKO_MOCHIZUKI/status/1163617711252885504
> 真面目に働いてきた多くの外国人達が現在、長期収容を強いられている  「がんの妻と日本で暮らしたい」パキスタン男性が「在留特別許可」求めて提訴。サディクさん「裁判は大変だが妻の命守る為に頑張る。パキスタンに戻れば命危ない」。妻も涙な… https://t.co/EJhNgsP6Dy
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:34／2019/08/20 13:27 URL： https://twitter.com/kk_hirono/status/1178664405501759493 https://twitter.com/kidkaido/status/1163668899713302528
> まだ、見られていませんが、見てみたいです。 ジャーナリズムは国の民主主義の屋台骨ですね。 https://t.co/iTuW50CmIt
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:34／2019/08/20 14:03 URL： https://twitter.com/kk_hirono/status/1178664372345815041 https://twitter.com/kidkaido/status/1163677790899703808
> いま、金子文子と朴烈について論ずることにどのような意味があるか　その１　 金子文子の生涯とその思想・感性 を共謀罪廃止のための連絡会ブログに掲載しました。 https://t.co/xCrPQKfa8z https://t.co/sjiUYVObuO
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:34／2019/08/21 16:52 URL： https://twitter.com/kk_hirono/status/1178664336295776261 https://twitter.com/kidkaido/status/1164082872644325378
> この映画見てみました。李明博政権と朴槿恵政権の公共放送に対する介入は、安倍政権におとらず、すさまじいものだったのですね。しかし、それを他の報道機関の記者も含めたジャーナリストと市民が連帯して跳ね返していった、こんな闘いがあったので… https://t.co/dBLHi8gRbz
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:34／2019/08/23 18:37 URL： https://twitter.com/kk_hirono/status/1178664294847660033 https://twitter.com/kidkaido/status/1164834115272622080
> 超党派の野党議員が「東電刑事裁判判決を控え 映画を観て講演を聴く会」を開催! ぜひご参加を! ９月４日（水）15:00～  参院会館Ｂ104 参加無料 呼びかけ人 石川大我、石垣のりこ、大河原まさこ、逢坂誠二、藤野保史、堀越啓仁、… https://t.co/REjQkZi5qX
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:33／2019/08/23 18:41 URL： https://twitter.com/kk_hirono/status/1178664275830661121 https://twitter.com/kidkaido/status/1164835019602272256
> 超党派の野党議員が「東電刑事裁判判決を控え 映画を観て講演を聴く会」を開催! ぜひご参加を! ９月４日（水）15:00～  参院会館Ｂ104 参加無料 呼びかけ人 石川大我、石垣のりこ、大河原まさこ、逢坂誠二、藤野保史、堀越啓仁、… https://t.co/BogQoVZ6Zb
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:33／2019/08/24 18:56 URL： https://twitter.com/kk_hirono/status/1178664219673120770 https://twitter.com/kidkaido/status/1165201130617327616
> 玉川徹がGSOMIA破棄で加熱するテレビの嫌韓煽動を批判！ 「視聴率取れるからって国民を煽ってはいけない」   https://t.co/udw075Xfqc   満州事変の直前には、中村大尉事件が発生、中国への敵意があおられてい… https://t.co/BM6MFKkiCM
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kogashigeaki（古賀茂明@フォーラム4） 日時：2019-09-30 22:33／2019/08/24 22:53 URL： https://twitter.com/kk_hirono/status/1178664121685827584 https://twitter.com/kogashigeaki/status/1165260812312727552
> テレ朝は明日早朝04:30〜 地域によって放送時間は異なります 財務次官をクビに追い込んだ元報道ステーションプロデューサー松原文枝さんの「遺作」 松原氏はこれを最後に報道の現場から追放です 安倍総理のポチ、テレ朝早河会長のひどい仕… https://t.co/5CPnmLKwC6
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:32／2019/08/25 08:26 URL： https://twitter.com/kk_hirono/status/1178664003632893952 https://twitter.com/kidkaido/status/1165405099381805056
> 中国人元徴用工の西松建設事件2007年4月27日最高裁判決は、元徴用工らの請求権は日中共同声明5項によって裁判上請求することができなくなったが、請求権は消滅していないとして、関係者に、被害救済に向けて努力をすることを期待し、和解解… https://t.co/rGkhgtxlQe
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:32／2019/08/28 02:08 URL： https://twitter.com/kk_hirono/status/1178663841275625472 https://twitter.com/kidkaido/status/1166397201762750464
> 共謀罪廃止のための連絡会のブログに金子文子と朴烈について書きました。二人は大逆思想のゆえに死刑判決を受けました。この大逆事件と思想と紙一重の共謀を裁こうとする共謀罪との共通性を考察します。 https://t.co/u8rjA6B4E9
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:32／2019/08/28 13:48 URL： https://twitter.com/kk_hirono/status/1178663820291522561 https://twitter.com/kidkaido/status/1166573326438977536
> 再処理工場の安全装置が故障｜NHK 青森県のニュース https://t.co/zJChDnYJWc
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:32／2019/08/28 17:08 URL： https://twitter.com/kk_hirono/status/1178663794521731076 https://twitter.com/kidkaido/status/1166623650973401089
> 東電刑事裁判判決を迎える報告会 9月10日18時半から　亀戸文化センター五階 映画「東電刑事裁判　動かぬ証拠と原発事故」上映と私の講演です。9.19判決を控えて、審理の到達点をご説明します。ぜひ、お越しください。 https://t.co/JKqQx7aZ0A
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:31／2019/08/28 17:16 URL： https://twitter.com/kk_hirono/status/1178663770056343554 https://twitter.com/kidkaido/status/1166625596237127680
> 死刑をなくそう市民会議は、これまでの死刑廃止運動を一回りひろげ、様々な立場の廃止の声を集め、国際世論を踏まえて、国会を動かそうとしています。 死刑廃止運動のバージョンアップ瞬間を目撃してください !… https://t.co/CmwTlQ11ye
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:31／2019/08/30 00:54 URL： https://twitter.com/kk_hirono/status/1178663742302613504 https://twitter.com/kidkaido/status/1167103224328802304
> 「表現の不自由展・その後」展示中止を受け、表現の自由に対する攻撃に抗議し、表現の自由の価値を確認する会長声明｜東京弁護士会 https://t.co/jWUaaWAc06
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜aokiaoki1111（青木美希） 日時：2019-09-30 22:31／2019/08/30 05:45 URL： https://twitter.com/kk_hirono/status/1178663707741581312 https://twitter.com/aokiaoki1111/status/1167176458940190720
> ふた周辺の放射線量の計測結果も公表され、最も高いところで１時間当たり1.97シーベルトあったとのこと。７シーベルトが全身被曝の致死量と言われています。 福島第一原発１号機 燃料プールの水中画像初公開 がれきが堆積 | NHKニュー… https://t.co/6QTErbBFRj
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:31／2019/08/31 06:34 URL： https://twitter.com/kk_hirono/status/1178663670135439360 https://twitter.com/kidkaido/status/1167551196527132672
> 今日の午後です。ぜひご参加を!! https://t.co/8Bwxhovbsv
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:31／2019/09/02 20:29 URL： https://twitter.com/kk_hirono/status/1178663641031168000 https://twitter.com/kidkaido/status/1168486120117555201
> 中日新聞の報道によると、官邸ポリスのトップが、国家安全保障局の局長に就任する可能性が高まっているという。... https://t.co/agAEx6z2vB
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:31／2019/09/02 20:53 URL： https://twitter.com/kk_hirono/status/1178663581522382848 https://twitter.com/kidkaido/status/1168492236159377408
> 驚くべき映像ですね。 香港で起きていることは、近未来の日本でも再現する可能性があります。皆さんの闘いには世界中の市民の自由がかかっています。 香港の市民の闘いを心から応援します。 https://t.co/28eyWgtSzh
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:30／2019/09/04 20:12 URL： https://twitter.com/kk_hirono/status/1178663483551842304 https://twitter.com/kidkaido/status/1169206599967096834
> 都議の皆さん。 国と福島県による避難者いじめに加担しないでください。 https://t.co/SN1wqbBklF
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:30／2019/09/04 22:03 URL： https://twitter.com/kk_hirono/status/1178663432200916993 https://twitter.com/kidkaido/status/1169234491971268609
> 真実は隠せない！ 有罪判決を求める ９．８東電刑事裁判　判決直前大集会 文京区民センター 午後２時から 映画上映、弁護団報告、ジャーナリストからの報告 福島の想い　リレートーク 会場を満員にして、私たちは福島原発事故を忘れていない… https://t.co/TpAPkBr8in
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:30／2019/09/04 22:15 URL： https://twitter.com/kk_hirono/status/1178663407110643713 https://twitter.com/kidkaido/status/1169237512985821185
> ９．７阿佐谷北でも福島原発事故刑事裁判 DVD上映会とお食事会 私も参加して、お話をします。 土曜日　六時半から開場 オーシャンハウス　阿佐谷北6-39-4　 参加費500円 食事の準備があるので、ぜひ事前に予約してご参加ください… https://t.co/1w2PL3S2cW
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:30／2019/09/05 12:50 URL： https://twitter.com/kk_hirono/status/1178663369487728640 https://twitter.com/kidkaido/status/1169457844485124096
> 少年法改正「更生に弊害」　元家裁調査官が反対声明（共同通信） - Yahoo!ニュース https://t.co/PvI6TUTrgh
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:29／2019/09/08 09:15 URL： https://twitter.com/kk_hirono/status/1178663280602050560 https://twitter.com/kidkaido/status/1170490900373311491
> 日本の市民の多くが、日韓の市民同士が仲良く交際・交流したいと望んでいると思います。 このような動きが出てきたこと、とても良いことです。企画してくださった方に感謝します。 ありがとう。 https://t.co/cZsHZGWhN1
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:29／2019/09/08 09:21 URL： https://twitter.com/kk_hirono/status/1178663246590406657 https://twitter.com/kidkaido/status/1170492197835161601
> いよいよ、今日の午後です。 台風が心配ですが、皆さん来てくださるように、あらためてお願いします。 https://t.co/r6fZCG5at7
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:29／2019/09/08 14:43 URL： https://twitter.com/kk_hirono/status/1178663212792762370 https://twitter.com/kidkaido/status/1170573449296666624
> 亀戸の皆さん、いよいよ来週火曜日に迫りました。 お会いできるのを楽しみにしています。 判決は19日です。 https://t.co/lmfiTxPjWf
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:29／2019/09/08 20:12 URL： https://twitter.com/kk_hirono/status/1178663183432601605 https://twitter.com/kidkaido/status/1170656159809728512
> 福島原発事故から被害を受けた多くの皆さんが、納得のできる判決が19日には言渡されるよう、心から願います。 この歌詞には、私たちの想いが詰まっています。 私もいっしょに歌いました。ぜひ、聞いてください。 https://t.co/8nbS0s6YM3
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:29／2019/09/09 15:42 URL： https://twitter.com/kk_hirono/status/1178663115577159681 https://twitter.com/kidkaido/status/1170950536452927489
> 刑事告訴、検察審査会、起訴、公判のすべての過程に立ち会ってきました。この歴史的な裁判によって、東京電力幹部の責任が明らかにされ、福島原発事故で影響を受けた多くの市民にとって納得できる判決に結実できることを祈っています。 https://t.co/9RAMhp92Hy
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:29／2019/09/10 13:36 URL： https://twitter.com/kk_hirono/status/1178663065211957248 https://twitter.com/kidkaido/status/1171281163882598403
> 東電刑事裁判判決を迎える報告会 いよいよ、今晩です。 9月10日18時半から　亀戸文化センター五階 映画「東電刑事裁判　動かぬ証拠と原発事故」上映と私の講演です。 9.19判決を控えて、審理の到達点のすべてをご説明します。ぜひぜひ… https://t.co/eNGfYZjx5u
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kyoubouzaihaisi（共謀罪は廃止できる！） 日時：2019-09-30 22:28／2019/09/13 10:48 URL： https://twitter.com/kk_hirono/status/1178663001643081728 https://twitter.com/kyoubouzaihaisi/status/1172326227681533953
> あいちトリエンナーレ 2019 出展作家 表現の不自由展・その後 〈壁を橋に〉プロジェクト 今こそ集会　(名古屋9/15,　東京9/17) #あいちトリエンナーレ #表現の不自由展 https://t.co/EYdZQEH3jN
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:28／2019/09/15 08:21 URL： https://twitter.com/kk_hirono/status/1178662976137490437 https://twitter.com/kidkaido/status/1173013943595356160
> https://t.co/z06dSMRnNX
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:28／2019/09/15 11:47 URL： https://twitter.com/kk_hirono/status/1178662954260000769 https://twitter.com/kidkaido/status/1173065696135139329
> 19日の東京地裁判決が迫る中で、時事通信が、東電刑事裁判の判決直前報道を流してくれました。武藤さんと私のコメントが取り上げられています。ぜひ、ご覧ください。 https://t.co/MkgFlX0NUa
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:28／2019/09/17 18:48 URL： https://twitter.com/kk_hirono/status/1178662918226755586 https://twitter.com/kidkaido/status/1173896538394771456
> 絵空事の核燃料サイクル、今やニュース価値なし？ - 石川智也｜論座 - 朝日新聞社の言論サイト https://t.co/tf58BEdXzZ もんじゅ後の日本政府の頼みの綱フランス・アストリッド高速炉計画が挫折。いよいよ、六ケ所… https://t.co/pkjMkALlqS
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜oguchilaw（弁護士　小口　幸人） 日時：2019-09-30 22:28／2019/09/20 09:32 URL： https://twitter.com/kk_hirono/status/1178662879253286912 https://twitter.com/oguchilaw/status/1174843845822967810
> 東電無罪判決の日の朝、最高裁長官が首相官邸を訪問しているなんて…、砂川事件のときの田中最高裁長官の件を想起せざるを得ない動きです。  まさか、判決を先行して伝えたり、控訴審・上告審の話をしたりなんてことはないと思うのですが…  国… https://t.co/KdL87D4525
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:28／2019/09/21 11:36 URL： https://twitter.com/kk_hirono/status/1178662813906026497 https://twitter.com/kidkaido/status/1175237415507644417
> 指定弁護士の石田、神山、山内、渋村、久保内先生には、素晴らしい訴訟活動をしていただきました。集中的な業務に全力を尽くしてくださったことに、心から感謝します。  判決への批判は日増しに高くなっています。ぜひとも、控訴し、控訴審も同じ… https://t.co/gKKgZzHyDu
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:27／2019/09/22 00:47 URL： https://twitter.com/kk_hirono/status/1178662764794875904 https://twitter.com/kidkaido/status/1175436361580462082
> 既に賛同者は3700人を超えました。24日に指定弁護士の先生方にお会いして、控訴と控訴審での指定弁護士担当の継続をお願いします。その時に第一次の署名賛同数をお伝えしたいと思います。緊急拡散をよろしくお願いします。 https://t.co/876KCFWnSF
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:27／2019/09/22 07:06 URL： https://twitter.com/kk_hirono/status/1178662741545893889 https://twitter.com/kidkaido/status/1175531730100346882
> 署名数現在4300です。もっと増やしたいです。よろしくお願いします。 【緊急署名】東電刑事裁判元経営陣「無罪」判決に控訴してください！ https://t.co/pne3bHJ2Cn @lnjnowさんから
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:27／2019/09/23 08:38 URL： https://twitter.com/kk_hirono/status/1178662719739707393 https://twitter.com/kidkaido/status/1175917321451233280
> いま、賛同は7700人に達しました。なんとか、一万人を超したい。 https://t.co/TAGASFnXy2東電刑事裁判元経営陣-無罪-判決に控訴を?recruiter=38526106&amp;utm_source=share_pe… https://t.co/WEhLBuKYNO
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:27／2019/09/24 21:05 URL： https://twitter.com/kk_hirono/status/1178662647123730433 https://twitter.com/kidkaido/status/1176467712010117120
> 国際人権法の権威である青学の申先生の日韓関係と徴用工問題に関する新しい論考がネット上に公開されました。  論理明晰な素晴らしい論考で、私もその論旨に全面的に賛成です。... https://t.co/wRVvocfr39
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:27／2019/09/25 18:23 URL： https://twitter.com/kk_hirono/status/1178662612768194560 https://twitter.com/kidkaido/status/1176789218057572352
> 朝日新聞ウェブ論座にこの判決の根本的な問題点をまとめた「東電旧経営陣無罪判決、裁判所が犯した七つの大罪」が掲載されました。七つの大罪のうち、一番基礎的なことをまとめた二つ目までは無料で読むことができます。ぜひ、お読みください。 https://t.co/jyUr6j8XQT
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜ueno_wan（上野千鶴子） 日時：2019-09-30 22:27／2019/09/22 23:24 URL： https://twitter.com/kk_hirono/status/1178662595491819521 https://twitter.com/ueno_wan/status/1175777896100585472
> 拡散希望。福島原発告訴団、福島原発刑事訴訟支援団より、東電刑事裁判元経営陣「無罪」判決控訴を求める緊急署名のお願いです。控訴期限は２週間、10月2日まで、下記、緊急署名ページへ。 https://t.co/I5qDQCasfB
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:26／2019/09/27 15:41 URL： https://twitter.com/kk_hirono/status/1178662472833626112 https://twitter.com/kidkaido/status/1177473442095886336
> 私も参加します。 シンポの後、郡山駅前で、無罪判決に対する控訴を求める街頭宣伝行動を行う予定です。街頭行動にも、ぜひご参加をお願いします。 https://t.co/LmCAIklskP
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:26／2019/09/28 16:00 URL： https://twitter.com/kk_hirono/status/1178662428810203137 https://twitter.com/kidkaido/status/1177840517221994497
> ※全編オープン【9/28 18時半～】「司法の歴史に汚点を残す判決だ！」福島原発刑事訴訟 東電元経営陣3名「全員無罪」?! 岩上安身による福島原... https://t.co/buPNxg0Mlm @YouTubeさんから 岩上… https://t.co/s7gxziGDE6
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:26／2019/09/28 16:03 URL： https://twitter.com/kk_hirono/status/1178662385331998721 https://twitter.com/kidkaido/status/1177841265058009088
> 今日の六時過ぎから、東京地裁の無罪判決を徹底批判する、対談をします。プレゼンも全面的に作り直しました。どうか、みなさんご覧になってください。岩上さんのご厚意でフル・オープンで、無料で見られます。IWJを経済的にも支えてください。私… https://t.co/CbMpZJ712g
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:26／2019/09/30 00:05 URL： https://twitter.com/kk_hirono/status/1178662341493215233 https://twitter.com/kidkaido/status/1178324858200973312
> ようやくネットの署名が13300、紙の署名が900です。あと800名で15000人になります。指定弁護士の皆さんに控訴をしていただき、控訴審も同じ五人の指定弁護士の方々に事件を担当してもらいたいです。どうかよろしくお願いします。 https://t.co/WeKFVZKcyu
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:26／2019/09/30 00:13 URL： https://twitter.com/kk_hirono/status/1178662315073257472 https://twitter.com/kidkaido/status/1178326978216087552
> 素晴らしい。政府間関係が悪化したときこそ、民間で良い関係を取り戻さなくては。日韓の弁護士会でも、共同でできることがあるはずです。 https://t.co/C5VDDU98ql
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:25／2019/09/30 10:15 URL： https://twitter.com/kk_hirono/status/1178662264783523841 https://twitter.com/kidkaido/status/1178478451117838336
> 関電幹部の金品授受、原発工事費用が工事業者「吉田開発」から、高浜町元助役を経由して還流していた。もともとは、電気料金だったお金から、自らの懐に入れていた。 アベマTVで河合弁護士が解説しています。 https://t.co/7sCZqiTBie
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:25／2019/09/30 13:46 URL： https://twitter.com/kk_hirono/status/1178662201034301440 https://twitter.com/kidkaido/status/1178531573991272448
> 海渡です。今しがた、東京地検まで、指定弁護士宛ての署名900人分を提出しました。デジタルを含めれば、総数は14200人となりました。 福島と全国からの控訴を求める声は伝えられたと思います。 「東電旧経営陣に無罪判決」　控訴求め署名… https://t.co/llkKAVbwNB
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:25／2019/09/30 15:25 URL： https://twitter.com/kk_hirono/status/1178662172668264449 https://twitter.com/kidkaido/status/1178556405919318016
> https://t.co/Ht4fsXYr70
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:25／2019/09/30 15:29 URL： https://twitter.com/kk_hirono/status/1178662130100256770 https://twitter.com/kidkaido/status/1178557440582832128
> 昨日の郡山での街頭署名行動を毎日新聞が記事にしてくれました。 ありがたいことです。 https://t.co/XXZtY4VJqK
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-09-30 22:25／2019/09/30 16:42 URL： https://twitter.com/kk_hirono/status/1178662106930929665 https://twitter.com/kidkaido/status/1178575940034498561
> 本日30日午後三時過ぎに指定弁護士が控訴の手続きを取りました。皆さんの願いが叶いました 指定弁護士の先生方に心から感謝します。 これからも、指定弁護士を支えて、高裁での逆転有罪判決を求めて、活動を続けます。これからもよろしくお願い… https://t.co/XNDz7IhQbV
▶▶▶　　　　　End　　　　　▶▶▶

　時刻は22時37分です。2分ほど経ったでしょうか、テレビの報道ステーションで、指定弁護士の控訴のことを少しだけ取り上げていました。時間にして15秒ぐらいだったでしょうか。正確にカウントしたわけではないですが、20秒はなかったような気がします。

　NHKのNEWS７は、その前に録画再生で確認しましたが、指定弁護士の控訴をニュースとして取り上げた形跡はありませんでした。途中で早送りをしていたので見落としがあったかもしれませんが、少なくとも主なニュースの見出しにそれはありませんでした。

　海渡雄一弁護士のTwitterのタイムラインを遡り、気になったツイートと若干のリツイートを告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)でリツイートしました。その数52件でした。

　指定弁護士の控訴についても、今日の夕方になって初めて知ったように思いますが、海渡雄一弁護士が熱心にツイートをしているものの、なぜか無罪判決時のツイートが見当たらず、無罪判決が出た日付も確認が出来ませんでした。ぎりぎりでも2週間前のはずではあります。

　指定弁護士は検察官役と聞きますので、費用は税金として国から出るのでしょう。疑問の声がいっさい聞こえてこないのもどうかと思いますし、左寄りの偏向番組と聞くこともあった報道ステーションですら、指定弁護士の名前も出していないのですから、どうかと思う報道ぶりです。

　無罪判決に対する不服は、今後の控訴理由ということにもなるのでしょうが、これまでの主張にある予見可能性を見ても、ずいぶんと厳しい要求を東電の旧経営陣に課しております。同様に弁護士による人権侵害、憲法違反についても厳しい態度で臨んでもらいたいと記録をしました。

〈〈〈：Emacs： 2019-09-30（月曜日）22：50 　〈〈〈

