#+TITLE: "組み体操について「私の身内が怪我をしたら、教育委員会のメンバー、校長、担当教員などを傷害罪で告訴します。」というモトケンこと矢部善朗弁護士のツイート"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-09-27 20:59:49 +0900
FILE_NAME: 2019-09-27-205949_組み体操について「私の身内が怪我をしたら、教育委員会のメンバー、校長、担当教員などを傷害罪で告訴します。」というモトケンこと矢部善朗弁護士のツイート.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: モトケンこと矢部善朗弁護士（京都弁護士会）,組み体操,教育委員会
記事タイトル名の文字数：74　保存ファイル名の文字数：96
#+STARTUP: showeverything


* 組み体操について「私の身内が怪我をしたら、教育委員会のメンバー、校長、担当教員などを傷害罪で告訴します。」というモトケンこと矢部善朗弁護士のツイート
  :LOGBOOK:
  CLOCK: [2019-09-27 金 21:02]--[2019-09-28 土 01:38] =>  4:36
  :END:

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: モトケンこと矢部善朗弁護士（京都弁護士会）,組み体操,教育委員会

〉〉〉：Emacs： 2019-09-27（金曜日）21：02　 〉〉〉

　昨日の９月２６日あたりに２，３ツイートで見かけていた組み体操に関する問題ですが、モトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインで気になるツイートを見かけ、対話を遡るとやはり組み体操の問題でした。

　この組み体操の問題については、数年前にも法クラの弁護士らのTwitterで頻繁に見かけた時期があり、問題意識を持って記録を作成していると思います。しかし、この組み体操の問題をネットで見かけたのはずいぶん久しぶりのことかと思います。

~  dp -p|grep -E '(組み体操|組体操)' |sed 's/$/\n/'
[link:] 2017年10月10日21時15分の登録： ＼深澤諭史　@fukazawas　RT：　@RyoUchida_RIRIS＼組み体操の事故３５％減少　対策の成果と今後の課題(内田良) http://hirono2014sk.blogspot.com/2017/10/fukazawasrtryouchidariris.html

[link:] 2017年10月18日14時49分の登録： ＼うのじ　@un_co_the2nd　RT：　@mas__yamazaki＼「組み体操」と称する人命軽視の児童虐待について、 http://hirono2014sk.blogspot.com/2017/10/uncothe2ndrtmasyamazaki.html

[link:] 2017年10月18日14時49分の登録： ＼細川暁子　@HosokawaAkiko＼２７年前に、組み体操事故で息子さんを亡くしたご遺族が、沈黙を破り取材に応じてくださった http://hirono2014sk.blogspot.com/2017/10/hosokawaakiko.html

[link:] 2017年10月30日10時18分の登録： ＼深澤諭史　@fukazawas＼件の黒髪事件にしろ、組体操にしろ、いろいろみていると、\n日本の小中高校って、日本国全体で、ミルグラム反応やスタンフォード監獄実験をやって http://hirono2014sk.blogspot.com/2017/10/fukazawas_30.html

[link:] 2017年11月02日23時59分の登録： ＼芳賀淳　@jjjhaga＼「組み体操で死亡」 中３遺族が提訴、損害賠償求める http://hirono2014sk.blogspot.com/2017/11/jjjhaga.html

[link:] 2017年11月07日04時17分の登録： ＼えきなんローヤー　@ekinan_lawyer＼組体操は団結の証などではなく。日常学校生活に潜む狂気が具現化しやすい悪魔の儀式ぐらいには思ってる。 http://hirono2014sk.blogspot.com/2017/11/ekinanlawyer_7.html

[link:] 2017年11月07日16時07分の登録： ＼えきなんローヤー　@ekinan_lawyer＼組体操は団結の証などではなく。日常学校生活に潜む狂気が具現化しやすい悪魔の儀式ぐらいには思ってる。 http://hirono2014sk.blogspot.com/2017/11/ekinanlawyer_37.html

[link:] 2017年11月09日16時06分の登録： ％@keita_adachi　弁護士あだちけいた㌠％そろそろ目聡いどこかが弁護団結成しそう\n\n＜組み体操＞骨折事故５件…４～５月　東京・練馬の小中学校（毎日新聞） http://hirono2014sk.blogspot.com/2017/11/keitaadachinn.html

[link:] 2017年11月09日16時07分の登録： ％@motoken_tw　モトケン％「競技を一律に中止するのはよくない」→「判断は各学校で」というのは論理の飛躍。責任の丸投げ。＞組み体操、一律中止にはせず - 東京都「判断は各学校で」 http://hirono2014sk.blogspot.com/2017/11/motokentw_83.html

[link:] 2017年11月09日16時12分の登録： ％@kmuramatsu　村松 謙％「より安全な組み体操を提言したいとしています。」って！\n組み体操自体、やめるという発想になぜならないのか。。。  http://hirono2014sk.blogspot.com/2017/11/kmuramatsu-n.html

[link:] 2017年11月09日16時13分の登録： ％@okumuraosaka　児童ポルノ/わいせつ/青少年淫行弁護人％組み体操 中学校の3割が中止 | 2017/8/14(月) - Yahoo!ニュース  http://hirono2014sk.blogspot.com/2017/11/okumuraosaka-3-2017814-yahoo.html

[link:] 2017年11月09日16時16分の登録： ％@oyamalaw　弁護士 大山定伸％組体操をやめるという方法がもっとも簡単。\n\n事故相次ぐ組み体操 安全な方法を研究者が紹介 | NHKニュース  http://hirono2014sk.blogspot.com/2017/11/oyamalaw-nn-nhk.html

[link:] 2017年11月09日16時30分の登録： REGEXP：”組体操．＊（事故）？”／データベース登録済みツイートの検索（2017年11月09日16時30分の記録140件） http://hirono2014sk.blogspot.com/2017/11/regexp201711091630140.html

[link:] 2017年11月21日14時21分の登録： ＼ystk　@lawkus＼アイドルなら恋愛禁止でも仕方ない、生徒なら組体操で壊されても仕方ない等。貴乃花が悪者にされる流れもその一例だと思うよ。 http://hirono2014sk.blogspot.com/2017/11/ystklawkus_31.html

[link:] 2018年01月15日10時16分の登録： ＼化石　@beautifulday00＼組体操をやった時点で暴行罪、怪我させたら傷害罪でガンガン立件すべき。警察と検察仕事しろ。 http://hirono2014sk.blogspot.com/2018/01/beautifulday00_89.html

[link:] 2018年10月03日19時50分の登録： ＼村松 謙　@kmuramatsu＼子ども達の小学校、組体操、危険な技全くなくなってた。 やっぱり迫力なくて寂しいという保護者や教員がいるのはわかるねw もう表現種目自体 http://hirono2014sk.blogspot.com/2018/10/kmuramatsu-w.html

[link:] 2019年06月03日21時44分の登録： ＼とりとく　@tkbei＼小学生のとき運動会の組体操でこんな感じの「タワー」のパーツをやらされたが落ちたらどうすんねんと気が気でなかったし生徒間の連帯感などまるでなかった http://hirono2014sk.blogspot.com/2019/06/tkbei.html

[link:] 2019年06月22日14時21分の登録： ＼奥村徹弁護士　@okumuraosaka＼組み体操事故件数、全国ワーストは兵庫県　その理由とは http://hirono2014sk.blogspot.com/2019/06/okumuraosaka_60.html

　上記の結果には意外な点が１つありました。今日もモトケンこと矢部善朗弁護士（京都弁護士会）の組み体操関連のツイートを見てすぐに思い出したのですが、永田という大学教授のツイートです。

　今、記憶のままに書くので間違いがあるかもしれないですが、永田憲史というお名前であったと思います。Twitterの＠付きのユーザ名にも見覚えがあって、昨日作成したまとめ記事に、それを見かけて久しぶりに思い出していました。

　これまでに何度か非公開設定にもされていて、早い段階にブロックもされていました。死刑制度の問題に取り組み研究者のようなお立場でもあるようです。三重県桑名市の辺りの高校で、準備していた講演が中止とされお怒りであったのも、印象深く記憶にあります。

```
▶（02／20） TW KPf_M（Kenji Takeuchi） 日時： 2019-09-25 08：16：00 +0900 URL： https：//twitter.com/KPf_M/status/1176636646260740096
{% tweet 1176636646260740096 %}
> 刑事司法対談（拡大版)　周防正行×木谷明　冤罪を生む「ムラ社会」の論理　法曹一元、証拠全面開示が改革のカギ https：//t.co/eiETwviuay

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”冤罪を生む「ムラ社会」の論理”／データベース登録済みツイート：2019年09月27日12時35分の記録：ユーザ・投稿：18／20件 http://hirono2014sk.blogspot.com/2019/09/regexp2019092712351820.html
```

　プロフィールのアイコンが小さいのですが、古代ヨーロッパの女神像が目隠しをされたか、目の付近が黒い帯で隠されたように見えるものとなっています。これは見覚えがありません。もしかすると、勘違いした別のアカウントなのかもしれません。これから確認します。

```
Kenji Takeuchi
@KPf_M
Twitterは備忘録として使用中。シーズン中はホークス関係のぼやき多め。
Fukuoka, Japanresearchmap.jp/takeuchikenji2010年1月からTwitterを利用しています
368 フォロー中
1,978 フォロワー
フォローしている人にフォロワーはいません

［source：］Kenji Takeuchi（@KPf_M）さん / Twitter https://twitter.com/KPf_M
```

　プロフィールのアイコンは女神像ではなく、飛行船でした。うる憶えですが大正時代化昭和初期のドイツのものとして何かで見かけたことのある大きな飛行船です。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜nakano00k（中野　一茂） 日時：2019-09-27 21:32／2019/09/27 00:56 URL： https://twitter.com/kk_hirono/status/1177561564951396352 https://twitter.com/nakano00k/status/1177250500896411648
> 滝川幸司氏　菅原道真　中公新書。書店にて。文章博士ばかりでなく官僚、詩人として才が溢れる男は家格を超えて出世し全てを失い九州の片隅で消えるように世を去る。祟神、怨霊としての道真ではなく人間「菅原道真」を活写した好著。 https://t.co/5pNbtoy1dk
▶▶▶　　　　　End　　　　　▶▶▶

　リツイートになりますが、タイムラインで見かけたものです。プロフィールにローマ字で福岡とあり、六本松と少し見覚えのある地名があるので、福岡市内の大学関係者の可能性がありそうです。福岡の大学のことは法学部の焼身自殺のことでニュースになっていました。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜QLib_info（九州大学附属図書館） 日時：2019-09-27 21:34／2019/09/27 10:13 URL： https://twitter.com/kk_hirono/status/1177562247322714113 https://twitter.com/QLib_info/status/1177390741162606592
> #九大リポジトリ 9月29日で、九州大学教養部のあった六本松キャンパスが閉校して10年になります。 旧制福岡高等学校時代から伊都キャンパスへの移転まで、その長い歴史を振り返ってみませんか。 『青春群像 さようなら六本松』… https://t.co/neHkSKn04d
▶▶▶　　　　　End　　　　　▶▶▶

　先にツイートをした直後に目に付いたのですが、やはり九州大学の六本松キャンパスとあります。福岡市は近年、裁判所や検察庁も離れた場所に移転となっていて、そちらはGoogleマップで場所を確認しました。以前は長浜の魚市場の近くだと情報を見かけていました。

KPf_M ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW KPf_M（Kenji Takeuchi） 日時：2019/09/26 08:24 URL： https://twitter.com/KPf_M/status/1177000853808414720
> 少年法適用の上限となる年齢が18歳未満だったら2度目の少年院はなかったわけですね。＞自暴自棄から暴行、恐喝…２度の少年送致から人生やり直し、二つの夢実現　仲里健太さん　次ぎの夢はボクシングチャンピオン https://t.co/QSlXXhP2kP
▷▷▷　　　　　End　　　　　▷▷▷

　そういえば少年法に関するツイートも少なくなかったと思いだしたのですが、やはりブロックされているアカウントで、想定のアカウントの可能性が高まったかと思います。

KPf_M ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW KPf_M（Kenji Takeuchi） 日時：2019/09/25 09:56 URL： https://twitter.com/KPf_M/status/1176661618488303616
> 訴訟費用、ネットで募る　運営弁護士「共感も集める」  https://t.co/nS7UQdng0b
▷▷▷　　　　　End　　　　　▷▷▷

　ずいぶん久しぶりに見たアカウントのタイムラインですが、興味深い参考となるツイート、情報が散見されます。ずいぶん久しぶりだと思うのでその辺りを含め、まとめ記事で確認しておきたいと思います。

　見覚えのない＠ユーザ名だと思っていたのですが、「dp -p|grep -E 'TW KPf_M' |sed 's/$/\n/'」で検索したところ結果はゼロでした。この＠ユーザ名も変更は出来るようですが、URLの一部ともなっているので影響も大きく、変更する人は滅多に見かけません。

 ~  dp -p|grep -E 'Kenji Takeuchi' |sed 's/$/\n/'
[link:] 2017年12月03日20時14分の登録： ＼Kenji Takeuchi　@KPf_M＼「理不尽にも松尾さんを起訴した検察官は出世街道を歩み、東京高検検事長を経て８８年に最高裁判事に就任。運命の落差はあまりにも大 http://hirono2014sk.blogspot.com/2017/12/kenji-takeuchikpfm.html

[link:] 2019年03月29日16時27分の登録： ＼Kenji Takeuchi　@KPf_M＼刑事政策の授業につきましても貴重なご意見を頂きましてありがとうございました。引き続き、授業改善のために努力致します。 http://hirono2014sk.blogspot.com/2019/03/kenji-takeuchikpfm.html

[link:] 2019年05月14日02時15分の登録： ＼Kenji Takeuchi　@KPf_M＼木谷明「捜査官！その行為は違法です。（第9回）近親者のメッセージを書いた紙を被疑者に無理やり踏ませた―志布志事件（2）踏み字 http://hirono2014sk.blogspot.com/2019/05/kenji-takeuchikpfm92.html

[link:] 2019年05月19日23時32分の登録： ＼Kenji Takeuchi　@KPf_M＼徳田先生がいらっしゃるという理由で大分での修習を希望し、修習後もそのまま大分に居着いた人が同じ世代だけで何人かいたはず。 http://hirono2014sk.blogspot.com/2019/05/kenji-takeuchikpfm.html

[link:] 2019年05月19日23時33分の登録： ＼Kenji Takeuchi　@KPf_M＼大分の弁護士、徳田靖之先生のご出演。これは必見。\n＞こころの時代～宗教・人生～「光を求めて ともに歩む」5/18 Eテレ 1 http://hirono2014sk.blogspot.com/2019/05/kenji-takeuchikpfm-518-e-1.html

　ここで気がついたのですが、プロフィールの名前のローマ字表記は「けんじ　たけうち」と読めるので、永山という大学関係者とは無関係の公算が高そうです。このKenjiの部分が永山というアカウントのものに似ていたのですが、ブロックされていたというのも意外な発見でした。

　次は永山でデータベースの検索をやってみます。他に永山という名前の弁護士や大学関係者というのは記憶にありません。永山といえば、死刑制度の永山事件が有名ですが、特に言及したものというのも記憶にはありません。

 ~  dp -p|grep -E '永山' |sed 's/$/\n/'
[link:] 2018年06月24日22時14分の登録： ＼関西大学出版部　@Kandai_Press＼【法律】永田憲史『死刑選択基準の研究』永山事件以降の全死刑判決及び検察官上告事件を検討し、死刑と無期懲役の基準を明らかにする http://hirono2014sk.blogspot.com/2018/06/kandaipress.html

　意外なことに結果は１つのみだったのですが、「永田憲史」という名前に間違いはありませんでした。この人物に最初に注目したのも組み体操に関するツイートがきっかけだったのですが、本格的なデータベースの活用を始める前のことであったのかもしれません。

　上記のまとめ記事もよくみると、「関西大学出版部　@Kandai_Press」というアカウントが記録の対象となっていました。本人のツイートは、上記のBloggerのブログとデータベースでは一つも記録していなかったことになりそうです。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-09-27 22:02／2016/06/26 14:33 URL： https://twitter.com/kk_hirono/status/1177569102845530113 https://twitter.com/hirono_hideki/status/746939423149854720
> 奉納＼弁護士妖怪大泥棒神社・金沢地方検察庁御中: 参考資料：　「組体操」をキーワードに含む「関西大学法学部　永田憲史研究室（@penology_nagata）」のツイート・リツイート「20」件  https://t.co/LgB24E5tOF
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-09-27 22:01／2016/01/20 09:42 URL： https://twitter.com/kk_hirono/status/1177568994422714368 https://twitter.com/hirono_hideki/status/689609025130860544
> 本文引用：関西大学法学部永田憲史教授と鹿児島大学准教授坂本正幸弁護士のバス事故報道と道徳教育の法的責任に関するツイート・リツイートのまとめ（2アカウント、25件、201 https://t.co/uYmeROPBVw
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「永田憲史」の検索結果 - Twilog https://t.co/mDRS0Es5CR

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-27 22:20／2019/09/27 22:12 URL： https://twitter.com/kk_hirono/status/1177573692257128449 https://twitter.com/s_hirono/status/1177571823220748289
> 2019-09-27-221014_Kenji　NAGATA@penology_nagataブロックされています@penology_nagataさんのフォローやツイートの表示は.jpg https://t.co/jaMPm7PYTf
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-27 22:20／2019/09/27 22:12 URL： https://twitter.com/kk_hirono/status/1177573668890656769 https://twitter.com/s_hirono/status/1177571750785118208
> 2019-09-27-220841_KenjiNAGATAさんがリツイートかもん弓（鴨志田祐美）@kamo629782·10h今朝、事務所に郵送されてきた9月25日付毎日新聞夕刊。小さなコラ.jpg https://t.co/K9M4BlfH1k
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-27 22:20／2019/09/27 22:12 URL： https://twitter.com/kk_hirono/status/1177573646908346368 https://twitter.com/s_hirono/status/1177571678739546113
> 2019-09-27-220607_KenjiNAGATAさんがリツイートピピピーッ@O59K2dPQH59QEJx·7h「女性弁護士は家事事件が得意」と言う老弁は、「現預金のみ遺産100億.jpg https://t.co/io6xcJXHAH
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-27 22:20／2019/09/27 22:12 URL： https://twitter.com/kk_hirono/status/1177573626809159681 https://twitter.com/s_hirono/status/1177571606069043202
> 2019-09-27-220536_Kenji　NAGATA（@penology_nagata）さん　／　Twitter.jpg https://t.co/IYPIHiUYaK
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-27 22:19／2019/09/27 22:11 URL： https://twitter.com/kk_hirono/status/1177573596287209477 https://twitter.com/s_hirono/status/1177571531653697536
> 2019-09-27-220507_ツイート　／　Twitter.jpg https://t.co/Jt6hdOVhuq
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-27 22:19／2019/09/27 22:11 URL： https://twitter.com/kk_hirono/status/1177573565987618816 https://twitter.com/s_hirono/status/1177571459582922752
> 2019-09-27-220419_奉納＼弁護士妖怪大泥棒神社・金沢地方検察庁御中：　参考資料：　「組体操」をキーワードに含む「関西大学法学部　永田憲史研究室（@penology_nagat.jpg https://t.co/O7Hj89iBqQ
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-27 22:19／2019/09/27 22:11 URL： https://twitter.com/kk_hirono/status/1177573516582899713 https://twitter.com/s_hirono/status/1177571387881345024
> 2019-09-27-220303_Kenji　Takeuchi（@KPf_M）さん　／　Twitter.jpg https://t.co/Dw83bBpu7B
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-27 22:19／2019/09/27 22:10 URL： https://twitter.com/kk_hirono/status/1177573496169226240 https://twitter.com/s_hirono/status/1177571315202457600
> 2019-09-27-205222_モトケンさんはTwitterを使っています：　「@KazukoIto_Law　権力に付け入る隙を盛大に与えたという意味で、全く応援できない。」　／　Twi.jpg https://t.co/tp5lCUBMMZ
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-27 22:19／2019/09/27 22:10 URL： https://twitter.com/kk_hirono/status/1177573476208500736 https://twitter.com/s_hirono/status/1177571242141896705
> 2019-09-27-201858_弁護士市川寛@imarockcaster42·9月24日０．１％の奇跡！衝撃　逆転無罪ミステリー【ＭＣ：田村淳】（テレビ東京、2019／9／2718：55.jpg https://t.co/OIh4cldf2M
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-27 22:19／2019/09/27 20:03 URL： https://twitter.com/kk_hirono/status/1177573451529252864 https://twitter.com/s_hirono/status/1177539140583182337
> 2019-09-27-200020_ＮＨＫ生活・防災さんはTwitterを使っています：　「神戸市長“怒り”のツイート　組み体操やめさせない市教委に　運動会の組み体操で事故が相次ぐ中、組み体.jpg https://t.co/YYJiACBcY7
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-27 22:19／2019/09/27 20:02 URL： https://twitter.com/kk_hirono/status/1177573425793003520 https://twitter.com/s_hirono/status/1177539068550213632
> 2019-09-27-195645_モトケンさんはTwitterを使っています：　「私の身内が怪我をしたら、教育委員会のメンバー、校長、担当教員などを傷害罪で告訴します。　　Twitter.jpg https://t.co/kSYtyawE2n
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-27 22:19／2019/09/27 20:02 URL： https://twitter.com/kk_hirono/status/1177573401658937344 https://twitter.com/s_hirono/status/1177538996131360768
> 2019-09-27-195611_モトケンさんはTwitterを使っています：　「@xjfb314　全国の学校であってはならないことです。　事故の状況によりますが、依頼があれば最強の手段を.jpg https://t.co/iVzd22Y0CM
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-27 22:19／2019/09/27 20:02 URL： https://twitter.com/kk_hirono/status/1177573377776615424 https://twitter.com/s_hirono/status/1177538924148690944
> 2019-09-27-194921_モトケンさんがリツイート4代目@4thlawyer·9月26日「面会交流が楽しくない。監護親がお膳立てしないせいだ」って非監護親から何回か言われた経験ある.jpg https://t.co/zJUdDP7m7P
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-27 22:19／2019/09/27 20:01 URL： https://twitter.com/kk_hirono/status/1177573356146552834 https://twitter.com/s_hirono/status/1177538851369177088
> 2019-09-27-194753_モトケン@motoken_tw·1h返信先：@KazukoIto_Lawさん権力に付け入る隙を盛大に与えたという意味で、全く応援できない。.jpg https://t.co/YMKmfDYHyN
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-09-27 22:17／2019/09/27 22:15 URL： https://twitter.com/kk_hirono/status/1177573082543689728 https://twitter.com/hirono_hideki/status/1177572497014718464
> 2019年09月27日22時09分の登録： ＼Kenji NAGATA　@penology_nagata＼拙稿「絞罪噐械圖式の頒布と絞罪器械の設置実務――明治初期の絞首刑の執行を巡る資料を読み解く――」は関西大学学 https://t.co/HHBGv494wi
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-09-27 22:17／2019/09/27 22:15 URL： https://twitter.com/kk_hirono/status/1177573062532685824 https://twitter.com/hirono_hideki/status/1177572470749949953
> 2019年09月27日22時08分の登録： https://t.co/veqQzVb0rp https://t.co/wHbKMjmXR5
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-09-27 22:17／2019/09/27 22:15 URL： https://twitter.com/kk_hirono/status/1177573051271020547 https://twitter.com/hirono_hideki/status/1177572444342669312
> 2019年09月27日22時06分の登録： ＼ピピピーッ　@O59K2dPQH59QEJx＼「女性弁護士は家事事件が得意」と言う老弁は、「現預金のみ遺産100億円の遺産分割事件」であっても、発言に従い、当該事件を女 https://t.co/Mzr1svSUOt
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-09-27 22:17／2019/09/27 22:15 URL： https://twitter.com/kk_hirono/status/1177573021822771200 https://twitter.com/hirono_hideki/status/1177572418002419713
> 2019年09月27日21時30分の登録： ＃Kenji Takeuchi　@KPf_M＃のツイート／2019-09-02_0709〜2019-09-27_1634／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年… https://t.co/T455eISPYb
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-09-27 22:17／2019/09/27 22:15 URL： https://twitter.com/kk_hirono/status/1177573001446875136 https://twitter.com/hirono_hideki/status/1177572391666368512
> 2019年09月27日20時55分の登録： ＼モトケン　@motoken_tw＼告訴すると言ったけど、（検事なら）起訴するとか、判決で確実に有罪になるとは言ってないのだがな。\n現状で１０段以上の多段ピラミッドをさせ https://t.co/wweIfN9XYh
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-09-27 22:17／2019/09/27 22:15 URL： https://twitter.com/kk_hirono/status/1177572980550819840 https://twitter.com/hirono_hideki/status/1177572365368090625
> 2019年09月27日20時54分の登録： ＼モトケン　@motoken_tw＼被害者代理人としての立場と検事の立場が同じだと言うのかね？\n検事は受理された告訴について、告訴状の記載どおりの事実と罪名で起訴しなきゃ https://t.co/hbebA4K6qB
▶▶▶　　　　　End　　　　　▶▶▶

　モトケンこと矢部善朗弁護士（京都弁護士会）をメインで取り上げる予定だったのですが、永山憲史という人物に関するものが多くなっています。これは私の中で通底する問題なのですが、学校教育と子育ては組み体操とも重なる部分を感じています。

　まとめ記事の永山憲史という人物の組み体操ですが、ご本人のツイートは埋め込みツイートが表示されず、１つだけ確認しましたがツイートは削除されていました。過去にも一度に沢山のツイートの削除があったような気がしました。

```
［penology_nagata__20160626_1430_1／20のツイート］
％penology_nagata（関西大学法学部　永田憲史研究室）のツイート％投稿日時％2015-06-03 10：59：00％ツイートのURL％ https：//twitter.com/penology_nagata/status/605916784793821184 ％
％penology_nagata（関西大学法学部　永田憲史研究室）のツイートの内容％
#％引用％ 名大の内田良先生のご尽力でマスコミでもかなり取り上げられるようになってきたので、学校で組体操を漫然とやらせて児童・生徒が負傷すれば、教員が業務上過失傷害罪に問われても仕方ないのでは。これだけ問題意識が広まってくると予見可能性がないという抗弁は無理でしょう。
％データベースへの登録日時％2016-06-26 14：29：25％

［source：］奉納＼弁護士妖怪大泥棒神社・金沢地方検察庁御中： 参考資料：　「組体操」をキーワードに含む「関西大学法学部　永田憲史研究室（@penology_nagata）」のツイート・リツイート「20」件 http://hirono2016k.blogspot.com/2016/06/penologynagata20.html?spref=tw
```

　上記の引用部分のツイートも存在しないと出ていました。内容はやはりかなり踏み込んだ内容のものとなっています。

　「学校で組体操を漫然とやらせて児童・生徒が負傷すれば、教員が業務上過失傷害罪に問われても仕方ないのでは。これだけ問題意識が広まってくると予見可能性がないという抗弁は無理でしょう。」とあります。投稿日は２０１５年６月３日です。

　まとめ記事に記録した他のツイートの内容は読んでいませんが、上記のツイート１つだけでも社会的問題性の指摘としては必要十分でしょう。

　次に、これからGoogle検索で永山憲史という人物について最新の情報を調べ確認をしておきたいと思います。たぶん関西大学の教授ということのなるのかと思いますが、現時点では過去のあいまいな記憶となっており、仮りの表現として「永山憲史という人物」としました。

[link:] » 永山憲史 - Google 検索 https://t.co/nYW0p8wInI

　全国的に見れば、特に珍しい名前の組み合わせとも思わなかったのですが、検索結果は驚くほど少なく大学の関係者ということも今回は確認が出来ませんでした。そういえば昨夜のNHKの日本人のお名前という番組に、同姓同名の夫婦が紹介されていたのを思い出しました。

　同姓同名の夫婦というのは考えたこともなかったのですが、一組は漢字まで全く同じという夫婦でした。以前検索したときは三重県の高校に関する情報も確認できたように思いますが、これほど結果の乏しいGoogle検索も初めてのことかと思います。２ページになっていました。

　信じられないものを見たような感覚なので、確かな現実としてスクリーンショットに記録しました。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-27 23:14／2019/09/27 23:08 URL： https://twitter.com/kk_hirono/status/1177587194363383808 https://twitter.com/s_hirono/status/1177585853058580486
> 2019-09-27-230721_永山憲史　-　Google　検索　-　Google　Chrome.jpg https://t.co/MGD4j6zy9j
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-27 23:13／2019/09/27 23:08 URL： https://twitter.com/kk_hirono/status/1177587179188391936 https://twitter.com/s_hirono/status/1177585780656496640
> 2019-09-27-230705_永山憲史　-　Google　検索　-　Google　Chrome.jpg https://t.co/24NZXRs2y1
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-27 23:13／2019/09/27 23:08 URL： https://twitter.com/kk_hirono/status/1177587163954704386 https://twitter.com/s_hirono/status/1177585708220895235
> 2019-09-27-230647_永山憲史　-　Google　検索　-　Google　Chrome.jpg https://t.co/hvi8RhuqX7
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-27 23:13／2019/09/27 23:07 URL： https://twitter.com/kk_hirono/status/1177587148922347520 https://twitter.com/s_hirono/status/1177585635638407174
> 2019-09-27-224047_永山憲史　-　Google　検索　-　Google　Chrome.jpg https://t.co/WLdLvRc9Mm
▶▶▶　　　　　End　　　　　▶▶▶

　検索結果がのきなみ少ないと感じていたのですが、永田を永山と勘違いしていたことに気が付きました。Twilogで「憲史」と検索したことで気が付きことが出来ました。次は三重県の高校の情報も見つかるかと期待します。

```
［刑事法］教授永田　憲史
専門分野
刑事学・刑事政策

研究テーマ
財産的刑事制裁、死刑選択基準・死刑執行、オセアニア諸国の刑事司法。

学部ゼミ紹介
「非行少年に関する実際の事例の分析」、「犯罪や刑罰に関して最近制定された法律の検討」、「法廷教室を利用した模擬裁判」、「刑務所・少年院の見学」などを行っている。

大学院演習科目紹介
企業法務演習、公共政策演習（企業法務、公共政策コース）
刑事学・刑事政策の諸問題をテーマとする。刑事司法制度に関する現行法および運用の現状を把握し、歴史的経緯を踏まえた上で、立法論および運用論の観点から諸論点を詳細に検討することを中心とする。議論を行うにあたって諸外国の状況を適切に理解することが必要であるため、英語をはじめとする外国語文献の読解を重視する。また、関係する社会福祉制度への理解を深めることで刑事司法制度の諸問題を立体的に考察する一助としたい。

［source：］［刑事法］　教授　永田　憲史 | 教員紹介 | 関西大学 法学部・法学研究科 http://www.kansai-u.ac.jp/Fc_law/staff/nagata.html
```

　関西大学の刑事法の教授だと確認しましたが、専門分野が刑事学・刑事政策となっています。刑事学というのは見かけてこなかったように思いますが、刑事政策の方は旧司法試験の選択科目にもなっていたはずで、モトケンこと矢部善朗弁護士（京都弁護士会）のツイートにも出てきます。

```
▶（01／28） TW motoken_tw（モトケン） 日時：2011-07-06 18：41：00 +0900 URL： https：//twitter.com/motoken_tw/status/88543032344985600
{% tweet 88543032344985600 %}
> 刑事政策の最大の課題は再犯防止です。犯罪者を人間扱いしないで再犯防止を語ることはできない。RT @nanami666： 被害者に落ち度のない場合の、犯罪者に対する人権思想は害悪だ、と思う。良くも悪くも、それが修正される時代が来るのではないか。

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”刑事政策”／モトケン（@motoken_tw）の検索（2011-07-06〜2019-06-01／2019年09月27日23時26分の記録28件） http://hirono2014sk.blogspot.com/2019/09/regexpmotokentw2011-07-062019-06.html
```

　まとめ記事を作成しました。２８件というのは思ったより少ない数ですが、モトケンこと矢部善朗弁護士（京都弁護士会）らしさがよく現れているかと思います。制度論との組み合わせも何度か目にしてきたように思います。現状のデータベースからの抽出です。

```
▶（06／28） TW motoken_tw（モトケン） 日時：2013-09-25 08：49：00 +0900 URL： https：//twitter.com/motoken_tw/status/382652983403905024
{% tweet 382652983403905024 %}
> 事実認定というものが全く理解できない人と、刑事司法または刑事政策の議論をすることの不毛さを実感中。

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”刑事政策”／モトケン（@motoken_tw）の検索（2011-07-06〜2019-06-01／2019年09月27日23時26分の記録28件） http://hirono2014sk.blogspot.com/2019/09/regexpmotokentw2011-07-062019-06.html
```

[link:] » 死刑の実態を明らかにし具体的な議論へ | 関西大学ニューズレター『Reed』｜関西大学 https://t.co/s5B69fBWWM

　永田憲史関西大学教授の顔写真が出てきましたが、正直余り見た覚えがないと感じました。想像よりはいくらか若くも見えましたが、年齢の方も確認はしていないか、情報を見ても頭には残らずすぐに忘れています。

[link:] » 永田憲史　三重 - Google 検索 https://t.co/W8YU1No6n3

```
関西大学法学部　永田憲史研究室　@penology_nagata　17：38
四日市高校の件、三重県教育委員会が謝罪等を拒否するという判断をされましたので、三重県内の公立学校等からの講演等の依頼は今後全てお断りさせていただくこととしました。詳細はPDFをご覧ください。
k3.dion.ne.jp/~penology/0/24…

SOLAさんがリツイート | 577 RT

［source：］5月11日(水)のつぶやき その２ - firefly https://blog.goo.ne.jp/firefly_/e/deb4f5cc37e588e8fdf2e7570450a553
```

　元のツイートは削除されているようですが、情報としてツイートの片鱗を見つけることができました。四日市高校とありますが、桑名市の高校であったようにも考えていました。その辺りも長距離トラック運転手の仕事でおおまかな土地勘はあります。

　急ぎではない仕事で名古屋市の海に近い辺りに向かうときは、岐阜県の関ヶ原から三重県桑名市の国道４３号線に出ていました。桑名市は愛知県と隣接していたと思います。

```
データベースへの登録順で、最初に「組体操」が出てきたのは、上記の2016年1月20日8時31分4秒の登録ツイートでしたが、よく見ると永田憲史教授本人のツイートではなく、小田原の村松謙弁護士のツイートをリツイートしたものでした。

　Twilogであれば普通に出来ますが、それ以外の方法では、私の知る限りAPIを使う以外、リツイートのURLを取得することはできません。リツイートのURLのリンクを開いても、元のツイートに飛ばされ、ブラウザのURLも元のツイートのものになってしまいます。

　そういえば、小田原の村松謙弁護士も、非公開設定にしていた時期がありました。非公開設定にした影響はよくわからないのですが、現時点でAPIからツイートの取得を試みてみたいと思います。

［source：］市場急配センター殺人未遂事件に加担した4弁護士２裁判官の告訴告発： ＃＃＃＃　関西大学法学部永田憲史教授　刑事学／刑事政策のツイートの記録　＃＃＃＃ http://hirono2017kk.blogspot.com/2017/11/blog-post_75.html
```

```
時刻は、16時52分です。外もだいぶん薄暗くなってきました。さきほどテレビで全国ニュースが始まったところですが、群馬県上野村でヘリが墜落4人が死亡というニュースの詳細です。墜落と死亡の速報は先に出ていたのですが、橋の上に墜落したという現場の映像がありました。

　よりによってコンクリートの橋の上に、と思ったのですが、終わりに目撃者によると真っ逆さまに墜落したということでした。現場周辺の見取り図が出ていて、墜落現場のすぐ近くに神社があったのも、気になるところです。長野県で資材を降ろし、栃木県に戻るところだったという情報もありました。

［source：］市場急配センター殺人未遂事件に加担した4弁護士２裁判官の告訴告発： ＃＃＃＃　関西大学法学部永田憲史教授　刑事学／刑事政策のツイートの記録　＃＃＃＃ http://hirono2017kk.blogspot.com/2017/11/blog-post_75.html
```

　上記に過去の自分のブログ記事から引用をしましたが、期待した三重県の高校に関するものは見当たりませんでした。

```
（09／91） RT penology_nagata（関西大学法学部　永田憲史）｜KPf_M（Kenji Takeuchi） 日時：2014-08-25 11：17：00 +0900／2010-11-22 10：28：00 +0900 URL： https：//twitter.com/penology_nagata/status/503727769612611584 https：//twitter.com/KPf_M/status/6519359350505472 TWEET： 光市事件に関する最高裁判所の判断が、これまでの司法判断の中でどれだけ異質なものでどれだけ整合的に説明することができないかは、永田憲史『死刑選択基準の研究』を読むとよく分かります。職業裁判官は永山基準との関係をどう説明しているんでしょう。ナゾです…。

［source：］TWEET：”2013-05-24 11：50〜2017-07-18 18：37”／Kenji NAGATA（@penology_nagata）のツイートの記録（2017年07月19日00時14分・91件） | 金沢地方検察庁御中＿2016 https://hirono2016s.wordpress.com/2017/07/19/tweet%EF%BC%9A2013-05-24-1150%E3%80%9C2017-07-18-1837%EF%BC%8Fkenji-nagata%EF%BC%88penology_nagata%EF%BC%89%E3%81%AE%E3%83%84%E3%82%A4%E3%83%BC%E3%83%88%E3%81%AE%E8%A8%98%E9%8C%B2/
```

　まとめ記事の数あるツイートのなかでたまたま目に止まったものですが、「光市事件」が気になって目を通したところ、最初に永山憲史改め永田憲史関西大学教授と取り違えた福岡の大学関係者のツイートを永田憲史教授がリツイートしたというものでした。

KPf_M ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW KPf_M（Kenji Takeuchi） 日時：2010/11/22 10:28 URL： https://twitter.com/KPf_M/status/6519359350505472
> 光市事件に関する最高裁判所の判断が、これまでの司法判断の中でどれだけ異質なものでどれだけ整合的に説明することができないかは、永田憲史『死刑選択基準の研究』を読むとよく分かります。職業裁判官は永山基準との関係をどう説明しているんでしょう。ナゾです…。
▷▷▷　　　　　End　　　　　▷▷▷

　あとで記録としてのスクリーンショットも掲載する予定ですが、昭和５３年ぐらいになるでしょうか、私が中学生の頃、流行した「コックリさん」を思い出します。永田憲史関西大学教授と三重県に強くこだわったのも光市母子殺害事件と同じ少年事件が本質にあります。

　ここでこの「Kenji Takeuchi」という人物についても、確かと思われる情報を確認しておきたいと思います。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜QuniKrimP（九州大学 刑事政策研究室） 日時：2019-09-28 00:12／2018/07/27 21:56 URL： https://twitter.com/kk_hirono/status/1177602030107422722 https://twitter.com/QuniKrimP/status/1022827989740879872
> 武内謙治「学外活動（フィールドワーク）は、ほろ苦いコーヒーの味——書をもって街にも出よう」が法学教室454号（2018年）2-3頁に掲載されました。
▶▶▶　　　　　End　　　　　▶▶▶

[link:] » Kenji Takeuchi - Google 検索 https://t.co/syhgBSIZRR

[link:] » 九州大学 武内 謙治 - Google 検索 https://t.co/nc97Jbx6IS

[link:] » 九州大学-研究者情報 [武内 謙治 (教授) 法学研究院 民刑事法学部門] https://t.co/fkIiRG5vL1

少年行刑法の研究 \n キーワード：少年行刑、教育思想 \n 2009.07～2009.07. https://t.co/fkIiRG5vL1

日本における少年司法制度の歴史的研究 \n キーワード：適正手続保障、ケースワーク原理、事実認定 \n 1998.04～2006.03. https://t.co/fkIiRG5vL1

主要著書 \n 全てを見る→ \n 1.本庄 武=武内 謙治, 『刑罰制度改革の前に考えておくべきこと』, 日本評論社, 2017.12, 自由刑、非拘禁措置、国際的動向を踏まえ、現在の刑罰制度改革の問題点とあるべき姿を描いた。. https://t.co/fkIiRG5vL1

主要原著論文 \n 全てを見る→ \n 1.武内謙治, 少年司法の過去・現在・未来——少年司法のゆくえ, 龍谷大学矯正・保護総合センター研究年報, 8, 33-45, 2019.03. https://t.co/fkIiRG5vL1

主要総説, 論評, 解説, 書評, 報告書等 \n 全てを見る→ \n 1.武内謙治, 浜井浩一『実証的刑事政策論』, 犯罪社会学研究37号, 2012.10. https://t.co/fkIiRG5vL1

主要学会発表等 \n 全てを見る→ \n 1.武内謙治, 社会内処遇, 犯罪社会学会第45回大会・シンポジウム「犯罪者処遇はどう変わるのか？」, 2018.10. https://t.co/fkIiRG5vL1

学会活動 \n 所属学会名 \n 日本更生保護学会 \n 日本刑法学会 \n 日本犯罪社会学会 \n 日本司法福祉学会 \n 法と心理学会 \n ドイツ少年裁判所・少年審判補助者連合 https://t.co/fkIiRG5vL1

学協会役員等への就任 \n 2018.08～2021.08, 日本司法福祉学会, 理事. \n 2015.08～2018.08, 日本司法福祉学会, 理事. \n 2014.10～2017.10, 日本犯罪社会学会, 理事. \n 2011.10～201… https://t.co/Xb0bC94Uz9

学会誌・雑誌・著書の編集への参加状況 \n 2018.07～2019.05, 季刊刑事弁護, 国内, 編集委員. https://t.co/fkIiRG5vL1

研究資金 \n 科学研究費補助金の採択状況(文部科学省、日本学術振興会) \n 2019年度～2022年度, 基盤研究(B), 分担, 再犯防止概念の多角的検討. https://t.co/fkIiRG5vL1

[link:] » KAKEN — 研究者をさがす | 武内 謙治 (10325540) https://t.co/hOWkEhbH2O

所属 (過去の研究課題情報に基づく) *注記2016年度 – 2019年度: 九州大学, 法学研究院, 教授 \n 2014年度 – 2015年度: 九州大学, 法学(政治学)研究科(研究院), 教授 \n 2012年度 – 2014年度:… https://t.co/Qhqy6NVZNO

[link:] » 【研究者データ】武内謙治 | 日本の研究.com https://t.co/IOf8ofOIxe

[link:] » 九大大学院法学研究院の武内謙治教授　写真｜【西日本新聞ニュース】 https://t.co/wmNURwc670

[link:] » 日本弁護士連合会：日弁連新聞　第539号 https://t.co/oFc0IHQN3e

[link:] » 日本弁護士連合会：日弁連新聞　第539号 https://t.co/oFc0IHQN3e \n 武内謙治教授（九州大学）は、「若年者に対する新たな処分」は少年の健全育成の理念とは相いれず問題であると強調した。その上で、「民法上の成年… https://t.co/67WvfbEzNr

　武内謙治九州大学教授と確認が出来ましたが、これはGoogle検索のサジェストでローマ字を打ち込んだときに出てきたと思います。顔写真を２つ見つけ、日弁連のものは２０１８年のものと確認出来ましたが、年齢を推測する情報は他に見当たりませんでした。

　顔写真は神原元弁護士に似ているとも感じましたが、同じ神原元弁護士の写真としてネット上にあるものも別人のような印象を受けるものもあるので、余り確かなものとは考えていません。年代的にも都道府県警察の本部長という印象を受けました。似た顔を見たような気もします。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「武内謙治」の検索結果 - Twilog https://t.co/6XhVekpgaO

RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜nippyo（日本評論社） 日時：2017/05/03 23:29／2017/05/02 11:11 URL： https://twitter.com/hirono_hideki/status/859776941276119041 https://twitter.com/nippyo/status/859228717087825920
> 【新刊】『守柔（しゅじゅう）─現代の護民官を志して』守屋克彦／著　石塚章夫・武内謙治／インタビュアー 刑事司法、少年司法に誠実に取り組み「国民のための裁判官」を目指し続けた一法曹の軌跡。 https://t.co/t96ykwMII0

RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜KPf_M（Kenji Takeuchi） 日時：2017/12/03 21:18／2017/11/27 08:53 URL： https://twitter.com/hirono_hideki/status/937294912642363393 https://twitter.com/KPf_M/status/934933211183964160
> 2017年12月上旬に書店に並びます。よろしくお願いいたします。  本庄武＝武内謙治編著『刑罰制度改革の前に考えておくべきこと』（日本評論社） https://t.co/3GNDeqnsoG

　竹内というのはよく見る名前ですが、武内謙治となると見かけた覚えがなく、Twilogで確認をすると過去にリツイートが２つあって、２つ目が武内謙治九州大学教授本人のツイートのリツイートでした。

　ツイートの横にあるアイコンは１６ｘ１６ぐらいのサイズになるのでしょうか、やはりこれまで見覚えのなかったもので、小さいままのぱっと見が、目の部分に黒い帯を入れた女神像の美術作品で、それも淡い色合いとにじみ具合が心霊写真にも思える印象的なものです。

　繰り返しますが、本来のアイコンの写真は９０年から１００年前と想像するヨーロッパの飛行船ですが、そらの雲が原爆投下のきのこ雲のようにも見えてきました。いろいろと謎を感じる歴史的なイメージの広がりです。

[link:] » 三重　花火大会　事件 - Google 検索 https://t.co/704KDyHZJ7

```
三重県中3女子死亡事件（みえけんちゅうさんじょししぼうじけん）は、2013年8月25日午後10時55分頃に三重県三重郡朝日町で発生した事件である。三重県警による正式な呼称は 三重郡朝日町地内における女子中学生強盗殺人・死体遺棄事件。別名、朝日町中3致死事件、三重・朝日町女子中学生致死事件［1］［2］。当初は強盗殺人事件として扱われたが、強制わいせつ致死罪・窃盗罪での立件となった［3］。怨恨もなく見かけただけの女子中学生を殺害し、自身の同級生たちにも悟らせないように工作していたことへの強い批判がある［4］。

［source：］三重県中3女子死亡事件 - Wikipedia https://ja.wikipedia.org/wiki/%E4%B8%89%E9%87%8D%E7%9C%8C%E4%B8%AD3%E5%A5%B3%E5%AD%90%E6%AD%BB%E4%BA%A1%E4%BA%8B%E4%BB%B6
```

```
被害者と容疑者［編集］
被害者
明るい性格で父親想いであり、多くの人に親しまれていた。存命であれば、2014年3月7日に卒業式を迎える予定であった［5］。
Aの遺族は、自宅ポストに「遺族・親族一同」として「犯人の行為は決して許すことができず、厳罰を望んでいます」と記した紙を張り出した［5］。
Aの両親（共に45歳）はBが強盗殺人ではなく強制わいせつ致死等で起訴されると、事件後初となる記者会見を開いて「納得できない部分はありますが、裁判所は重い判決を下してほしいです」と述べた。
容疑者
県内のK高校の3年生（男子）で、前日の卒業式には出席し、友人と談笑していた。「同級生らは信じられないと動揺していた」「成績も良く、友人も多かった」「皆に慕われる明るい性格だった」と報道された。しかし、家を知る地元住人では「マスコミは何を調べてあんなことを言っとるんですか。人間ができとる？ 頭がいい？ まるっきり違う。警察や教委はよくマスコミをあれだけコントロールしたな、と近所では失笑してますよ」と「犯人は優等生報道」に実態が違うとの不信感が残っている［9］。朝日新聞も2010年に現場近くで未解決になっていた器物損壊事件をおこしていたことを報道している［1］。少年は自身のツイッターに事件当時Twitterで「ちょ、え、めっちゃやばいやん」「四日市の女子中学生らしい…手の震え止まらん。」などと事件についてツイート、自宅に捜査員が来た後に「近くの家の人に聞いて回るらしい」「気持ちの整理がつかない」「THE・平和の町やったのに(T-T) 気持ちの整理つかんわ…」などと終始事件と逮捕前日の3月1日まで無関係を装っていた。少年のTwitterは「金目当ての犯行」と主張して逮捕されるまで変わったところは無かった［10］［11］。しかし、金目当てなのに6000円所持の中学生女子を襲ったことや遺体から疑念を持たれていたが［12］、「家族にわいせつ目的だったことを知られるのが嫌だったから、金目的と言ってしまった」などと話した［7］。

［source：］三重県中3女子死亡事件 - Wikipedia https://ja.wikipedia.org/wiki/%E4%B8%89%E9%87%8D%E7%9C%8C%E4%B8%AD3%E5%A5%B3%E5%AD%90%E6%AD%BB%E4%BA%A1%E4%BA%8B%E4%BB%B6
```

　２０１３年８月２５日の事件とありました。calコマンドで確認したところやはり日曜日の夜の事件でしたが、早い段階でのテレビの報道を夜に見ていた記憶があります。

　他にこの三重県の事件で記憶に残るのは、警察が被疑者の高校の卒業式を待って逮捕したというような報道があったことと、父親との親子仲がよく、近所でよく一緒にキャッチボールをしていたような付近住民の話が、お昼の情報番組に出ていたことです。

　罪名は強制わいせつ致死となっていたようです。わいせつ目的であったことは事件からしばらくあとの報道で知っていましたが、懲役 5年以上 9年以下（求刑懲役 5年以上 10年以下）の不定期刑というのは、今回初めて知ったかもしれません。検察の控訴があったようです。

[link:] » 朝日町 - Google マップ https://t.co/h44ldxma6B

　Googleマップで三重県朝日町の場所を確認したところ、海にずいぶん近いという意外な場所でした。三重県三重郡とありますが、桑名市と四日市市に挟まれているように見えます。

　もっと山の方で海から離れた場所を想像していたのですが、新興の住宅地で四日市市の山の方の外れに仕事に行ったことがあり、その辺りを想像していました。被告発人安田敏と一緒にいた岐阜県海津町の山下工務店の仕事のことで、昭和６１年の７月頃になります。

　平成４年の１月の下旬も３回ほど集中して三重県四日市市にミールを運ぶ仕事があり、そのときの運行の様子もなまなましく記憶に残っているのですが、その辺りの記憶も重ねて、被害者家族、加害者家族の立場を思いいろいろと考えさせられる事件でした。

　いったん暴走し歯止めがかからなくなった少年の性衝動が引き起こした少年による性犯罪事件ということで、光市母子殺害事件とも共通性を感じますが、光市の事件の方は死刑判決が確定しています。

　調べた範囲でも永田憲史関西大学教授の立場から不服や不満という情報しか見当たらなかったですが、あの同じ三重県の四日市市の近郊で起きた中３女子死亡事件からそんなに経っていないのに、その土地の高校生を相手に死刑の講義をするというのはどうなのかと深く考えました。

　組み体操を教育として捉えず、犯罪の構成要件に該当するものとしてTwitterけ見解を示していたこととも併せて、四日市高校での死刑の講義が必要な教育の一環として優位的ものなのかとも深く考えました。被害者加害者の立場から諸刃の剣の問題性が、その前にあったような気がします。

```
【学歴】

三重県立四日市高校卒業

京都大学法学部卒業

京都大学大学院法学研究科民刑事法専攻修士課程修了

同・博士課程研究指導認定退学

日本メディカル福祉専門学校社会福祉士科一般通信課程卒業

     *情緒障害児短期治療施設（当時。現・児童心理治療施設）で実習をさせていただき、社会福祉士国家試験の受験資格を取得しましたが、まだ一度も受験できておりません……。

【職歴】

2001年4月1日  日本学術振興会特別研究員（DC1）採用

2004年3月31日 同・任期満了

2005年4月1日 関西大学法学部 専任講師

2008年4月1日 同・准教授

2015年4月1日 同・教授

【最近の授業担当】　　　若き日のゼミでの1コマ

2005年度以降の授業担当・非常勤講師歴

2018年度： 刑事学総論、刑事学各論、展開講義（平等問題の最先端）《コーディネーター》、専門演習1、専門演習2、研究論文、トピック演習、M刑事学研究講義1（不開講）、M刑事学研究講義2（不開講）、M刑事学研究演習1（不開講）、M刑事学研究演習2（不開講）

2019年度： 刑事学総論、刑事学各論、展開講義（平等問題の最先端）《コーディネーター》、専門演習1、専門演習2、研究論文、トピック演習、M刑事学研究講義1（不開講）、M刑事学研究講義2（不開講）、M刑事学研究演習1（不開講）、M刑事学研究演習2（不開講）

2020年度：（春学期に関西大学研修員、秋学期に関西大学学術研究員として研究専念義務が課されるため、授業を担当いたしません）

2021年度：（例年通り担当予定）

【専門領域】

刑事学・刑事政策・犯罪学

1. 罰金刑をはじめとする財産的刑事制裁

2. 死刑選択基準・死刑執行

3. オセアニア諸国（特にニュージーランド、南太平洋島嶼国家・地域）の刑事司法

4. 犯罪者処遇の医療的側面

［source：］プロフィール - 関西大学法学部　永田憲史研究室（刑事学・刑事政策） https://penology.jimdo.com/%E3%83%97%E3%83%AD%E3%83%95%E3%82%A3%E3%83%BC%E3%83%AB/
```

　確認のため確かな情報が欲しいともう少しGoogleで調べたのですが、永田憲史関西大学教授は三重県四日市高校の卒業生だと確認しました。上記のページでの発見としてもう一つ気になったのは「4. 犯罪者処遇の医療的側面」です。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-28 01:36／2019/09/28 00:40 URL： https://twitter.com/kk_hirono/status/1177623027506221056 https://twitter.com/s_hirono/status/1177608953485651969
> 2019-09-28-003751_Kenji　Takeuchi@KPf_Mブロックされています@KPf_Mさんのフォローやツイートの表示はできません。詳細はこちら.jpg https://t.co/u3q5RKMuTO
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-28 01:36／2019/09/28 00:40 URL： https://twitter.com/kk_hirono/status/1177623009600786432 https://twitter.com/s_hirono/status/1177608881427501056
> 2019-09-28-001737_日本弁護士連合会：日弁連新聞　第539号.jpg https://t.co/Z2LveG6oYs
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-28 01:36／2019/09/28 00:39 URL： https://twitter.com/kk_hirono/status/1177622993976971264 https://twitter.com/s_hirono/status/1177608809012813824
> 2019-09-28-001556_九大大学院法学研究院の武内謙治教授　写真｜【西日本新聞ニュース】.jpg https://t.co/3cL0cwrqMF
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-28 01:36／2019/09/28 00:39 URL： https://twitter.com/kk_hirono/status/1177622976667078656 https://twitter.com/s_hirono/status/1177608737189588992
> 2019-09-28-001326_九州大学　刑事政策研究室さんはTwitterを使っています：　「武内謙治「学外活動（フィールドワーク）は、ほろ苦いコーヒーの味——書をもって.jpg https://t.co/yAHs3mK3tq
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-28 01:36／2019/09/28 00:39 URL： https://twitter.com/kk_hirono/status/1177622952285573120 https://twitter.com/s_hirono/status/1177608665286635520
> 2019-09-27-235701_Kenji　TakeuchiさんはTwitterを使っています：　「光市事件に関する最高裁判所の判断が、これまでの司法判断の中でどれだけ異質なものでどれだ.jpg https://t.co/sCG29Kx3kR
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-28 01:36／2019/09/28 00:39 URL： https://twitter.com/kk_hirono/status/1177622935684575232 https://twitter.com/s_hirono/status/1177608592901337088
> 2019-09-27-233212_［刑事法］　教授　永田　憲史　｜　教員紹介　｜　関西大学　法学部・法学研究科.jpg https://t.co/EYzB06fzHi
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-28 01:35／2019/09/28 00:38 URL： https://twitter.com/kk_hirono/status/1177622918525644800 https://twitter.com/s_hirono/status/1177608519308066816
> 2019-09-27-232202_永田憲史　-　Google　検索　-　Google　Chrome.jpg https://t.co/BKZTYrXdKy
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-28 01:35／2019/09/28 00:38 URL： https://twitter.com/kk_hirono/status/1177622901349998593 https://twitter.com/s_hirono/status/1177608446507487234
> 2019-09-27-231823_奉納＼さらば弁護士鉄道・泥棒神社の物語（@hirono_hideki）／「永山憲史」の検索結果　-　Twilog.jpg https://t.co/yZSEr0lxgv
▶▶▶　　　　　End　　　　　▶▶▶

〈〈〈：Emacs： 2019-09-28（土曜日）01：38 　〈〈〈

