#+TITLE: "モトケンこと矢部善朗弁護士（京都弁護士会）と、北九州の警察官Twitterアカウントの関係"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-10-15 13:21:33 +0900
FILE_NAME: 2019-10-15-132133_モトケンこと矢部善朗弁護士（京都弁護士会）と、北九州の警察官Twitterアカウントの関係.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: モトケンこと矢部善朗弁護士（京都弁護士会）,感熱紙,名誉毀損
記事タイトル名の文字数：45　保存ファイル名の文字数：67
#+STARTUP: showeverything


* サイコキャプチャーについて調べてみた：モトケンこと矢部善朗弁護士（京都弁護士会）と、北九州の警察官Twitterアカウントの関係
  CLOCK: [2019-10-15 火 13:24]--[2019-10-15 火 17:28] =>  4:04

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: モトケンこと矢部善朗弁護士（京都弁護士会）,感熱紙,名誉毀損

〉〉〉：Emacs： 2019-10-15（火曜日）13：24　 〉〉〉

```
感熱紙(サイコキャプチャー)
@thermalpaper00
時々おかしなことを口走りますが、基本的に無害です。
九州地方2009年10月からTwitterを利用しています
773 フォロー中
1,833 フォロワー

［source：］感熱紙(サイコキャプチャー)（@thermalpaper00）さんの返信があるツイート / Twitter https://twitter.com/thermalpaper00/with_replies
```

　感熱紙という部分は、モトケンこと矢部善朗弁護士（京都弁護士会）のブログの常連コメンテーターの頃から同じもので、ハンドル名ということになるかと思います。括弧書きのサイコキャプチャーの部分もここ数年は変わっていないと思うのですが、違っていた時期もありました。

```
[1276]  % mysql -u root benngosi_twitter -e 'SELECT DISTINCT name FROM tw_user_tweet WHERE user LIKE "%thermalpaper00%"\G'|sed 's/\*/＊/g'
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 1. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
name: 感熱紙(木星帰りの男)
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 2. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
name: 感熱紙(エイハブリアクター搭載)
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 3. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
name: 感熱紙(ハイパーメガ粒子砲)
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 4. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
name: 感熱紙(リフレクターインコム)
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 5. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
name: 感熱紙(エイハブリアクター)
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 6. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
name: 感熱紙(祝バーザムHGUC化)
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 7. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
name: 感熱紙(グリプス２)
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 8. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
name: 感熱紙(フラッグファイター)
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 9. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
name: 感熱紙(不死鳥狩り)
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 10. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
name: 感熱紙(サイコミュ試験型)
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 11. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
name: 感熱紙(サイコキャプチャー)
```

　モトケンこと矢部善朗弁護士（京都弁護士会）とは違い、この感熱紙というアカウントについては、毎日監視することがないばかりか、数ヶ月以上調べていなかったことがあると思います。

　ツイートの更新も少ないアカウントと思っていたのですが、本日ツイート数を見たところ3.3万件と表示されているので、短期に集中したツイートもあったのかもしれません。Twitter歴は2009年10月から、とあるので、かなり長く、ちょうど10年目になるようです。

　10年で3.3万件というのは、「33000 / (12 * 10)」という計算で、月平均のツイート数が275件となりました。たまにタイムラインを開くと更新が少なかったので、もっと更新の頻度が低いものと思っていました。

　データベースの登録はかなりムラがあるとあると思いますが、それでもプロフィールの名前が変更されたもので11件存在したと確認しました。全ての基本が「感熱紙」となっています。

　私は平成9年の1月から4月の初めにノートパソコンを買うまでの間、正味2ヶ月間ぐらいだったと思いますが、ワープロ専用機を10万5千円ぐらいで買って、使っていました。そのときに、その期間だけ感熱紙というものを使ったことがありました。

　その経験がなければ感熱紙の理解がなかったと思いますし、今は感熱紙と聞いてわかる人は少なくなっているように思います。感熱紙の特徴としては、数年で印刷した文字が薄くなって消えていくということを聞いていました。

　現在でも感熱紙というアカウントのタイムラインを開くことは少なく、定期的な記録はしておくように心がけているのですが、タイムラインを遡ってツイートを読むことは余りありません。

　何年か前に、小学校低学年かそれより小さい息子がいることと、ガンダムのファンというツイートを見かけたことがありました。プロフィールの名前も、そのダンダムか他のアニメ、あるいはゲームの影響なのかとは考えていましたが、個人の趣味として深くは考えませんでした。

　ガンダム世代という言葉も聞いたことがあり、年代として当て嵌まるのか調べてはいないのですが、テレビでアニメを見なくなった時期になっていたのか、個人的にダンダムというのはほとんど知らないのですが、有名で人気があることはしっています。

　テレビでアニメを見たので最後の方に記憶にあるのは、怪物くん、や、忍者ハットリくんでしたが、昭和56年頃と思います。昭和57年頃は「アラレちゃん」というのも人気でたまに観ていましたが、そちらは夕方ではなく19時台の放送だったと思います。

　アンパンマンが出てきたのも昭和58年ぐらいだったように思いますが、夕方の早い時間の放送であったように思います。

　今日は、サイコキャプチャーの意味が気になって初めて調べたのですが、バイオハザードのときと似た、意外な結果がありました。

　まず、キャプチャーから調べました。聞いたことはある言葉でなんとなくイメージはあったのですが、調べた情報ではパソコンのスクリーンショットと同じ意味ということで、つまりは記録保存することなのかと新たな理解をしました。

　サイコというのもホラー映画などで聞いたことがある言葉でしたが、より身近だったのはサイコパスです。サイコパスは社会的に有用な人物に少なくないとも聞き、その代表的な職業に弁護士もあったので、考えたり、調べたりもしたことがありました。

　サイコパスとサイコが同じ意味とは考えなかったのですが、違いを調べることはありませんでした。パスというのはパソコンやプログラミングでよく見かける用語で、ファイルの置き場所や経路を指すものと理解しています。コマンドサーチパスでは、パスを通すという言い方もします。

　サイコで調べると、怨霊というものが出てきましたが、精神・霊魂が本来の意味のようです。サイコという映画があって1960年の映画で1998年にリメイク作品があったとか、小説があったという情報が多いようですが、この映画と小説のことは知らなかったと思います。

　1960年というのは昭和35年なので、私が生まれる4年前ですが、そのあとのことは時代を生きてきたのでだいたいのことはわかっているつもりです。オカルトという言葉が流行る前だったとも思いますが、エクソシストという映画が社会現象のように大ヒットしました。

　当時は情報源が乏しかったですが、恐怖新聞という人気漫画に出てきたのもポルターガイストで、エクソシストに似ていたと思います。恐怖新聞は週刊少年チャンピオンの連載で、まだ辺田の浜に住んでいた頃に見ていたという記憶があります。

　この恐怖新聞については、岡口基一裁判官や久保利英明弁護士のことで取り上げたことがあるかと思いますが、もっとしっかりした記録を残しておきたいと作業の必要性を感じているところです。弁護士鉄道の歴史遺産として。

　感熱紙というアカウントが、どのような意味合いでサイコキャプチャーという言葉を使っているのか、厳密なことは本人にしかわからないと思いますが、ざっと調べたところでも、サイコというのはサイコパスや異常者をイメージさせることが大きいようです。

　バイオハザードについても、まだ弁護士鉄道の歴史遺産として十分な説明はしていないと思うのですが、2年ほど前になりますか、ふとバイオについて調べたところ「生物」という意味らしく、ハザードを危険だとすると、そのまま危険生物に当て嵌まるようで、驚いたことがありました。

　このバイオハザードの個人的なイメージは、パチスロ機にあるのですが、映画があることも知っていました。数年前、テレビの番組表で地上波の放送があることを知ったのですが、視聴することはなく録画もしませんでした。

　バイオ燃料という言葉もあったと思います。これも羽咋市に住んでいた時の終わり頃、テレビで夕方に、ニュースの特集として見たものだったと思いますが、ゴミ処理場の映像とともに説明をみたことがありました。

　最近は見かけないですが、純粋培養という言葉もテレビか何かで見かけたことがあって、人体実験の研究室で化物が誕生したというのもバイオハザードのパチスロ機のストーリーだと理解がありました。

　パチスロ機には激アツと呼ばれるモードがあって、いつのまにかそのモードに突入していました。巨人のような怪物が廃墟のようになった研究所の敷地で暴れていたというイメージが残っています。前提知識がないまま突入したモードだったので、理解も不十分でした。

[link:] » 【バイオハザード】 タイラント先生の課外授業 - YouTube https://t.co/bOEy7KvBLw

　Googleの画像検索から調べたのですが、バイオハザードのパチスロ機の巨人のような怪物はタイラントという名前のようです。人体標本で内蔵や血管が透けているようにも見える怪物です。

[link:] » パチスロ　バイオハザード　プレミアムART解説ムービー - YouTube https://t.co/kL8dmSCklk

　プレミアムARTというモードだったのか、よくわからないのですが、タイラントという怪物がずっと外にいて、その場面が長く続くモードがありました。その場面は刑務所の敷地内ともよく似ているように思えて印象的でした。

　私がバイオハザードのパチスロ機をやったのもダイナム羽咋店でした。このバイオハザードの機種は他店でやったことがなかったかもしれず、設置が少ない機種だったのかもしれません。

　ダイナム羽咋店の正面から店内に入ると、中央に一本通路があって、その奥側でした。右から2列目の通りの右側で、その右側の真ん中から台に向かって左側に8台ぐらいバイオハザードの機種が並んでいたように記憶します。

　その奥は左右になっていたとも思いますが、新世紀エヴァンゲリオンのパチスロ機が設置されていました。その名は暴走モードだったと思いますが、大げさな演出の割に、メダルの増えることが少ないモードで、期待することもなかったように思います。

　この右から2列目の通路の奥の左側は、全部が「押忍番長」という機種だったこともあったかと思います。通路の手前側というのは、正面の大きなガラスで外の明るい日差しがそのまま差し込んでいたように思いますが、恐怖新聞のパチスロ機が5台ほど並んでいたこともありました。

　ダイナム羽咋店でパチスロ機があったのは、正面右端からの2列だけだったと思います。真ん中の通路が仕切りにもなっていて左右にパチスロ機が並んでいました。

　ダイナム羽咋店が出来た頃は、まだ4号機の時代だったかもしれないですが、すぐに5号機に入れ替わって、4号機で最後まで残っていた機種は「俺の空」だけでした。申請を受けた後の残りの期間が長かったという話も聞いたことはありました。

　当時のパチスロ機をやったことがない人は、さっぱりわからない話だと思いますが、4号機で爆発的な人気だったのが「北斗の拳」と「吉宗」でした。ギャンブル性が高すぎると問題になって、規制されたのが5号機でした。

　5号機の北斗の拳が最初に出た頃は、まだ人気があってダイナム羽咋店でも設置台数が多かったですが、その後の新機種では人気もなくなって設置台数も少なくなっていました。

　その設置台数が少なくなった北斗の拳の新機種でしたが、演出に「大王様」というのがありました。この大王というのはラオウになりますが、ストーリーの主人公がケンシロウではなくラオウとなっていたかもしれません。

　これまでに何度か書いてきたことですが、週刊少年ジャンプに「北斗の拳」の連載が始まり、ずいぶんと人気でもあったのですが、ちょうどその連載が始まってしばらくしてから私は漫画離れとなり、それ以来、現在までその手の週刊誌の漫画はほとんど見ることがありません。

　その手ではない週刊誌の漫画は、その後もよく見る時期がありました。週刊少年ジャンプや週刊少年マガジンという分厚い雑誌の漫画は全く手にもしなくなったのですが、週刊漫画、モーニング、ヤングマガジン、ビックコミックスピリッツというタイプのものは、よく見ていました。

　長距離トラック運転手をしている頃、コンビニで立ち読みをしたり、買うことも多かったのですが、暇つぶしと同時に、雰囲気が割と好きであったように思います。

　パチスロ機というのもけっこう雰囲気が好きでした。金沢市場輸送の仕事は忙しいこともありましたが、時間つぶしに難儀する仕事でもありました。青果物や鮮魚という市場の仕事は、現地での待ち時間が長かったからです。連休だと3日ぐらい待機することがありました。

　漫画の単行本というのも平成に入ってからは買ったことがなかったかもしれません。１つだけ金沢刑務所の拘置所にいるときに、代紋という漫画の単行本を１つ私物購入したことがありました。１つとても気になる場面があったからだと思います。

　漫画は子どもの頃によく読んでいましたが、他にすることがなかったというのも大きいかと思います。娯楽が少ない時代でしたし、ファミコンがブームになったのも18歳ぐらいだったと思いますが、やることはなかったです。

　ただ、パチスロやパチンコをやめるために、テレビゲームを始めたことがありました。PCエンジンと言われたカード式でしたが、まもなくCDロームを使える機器を買いました。当時で5万円以上はしたと思います。最先端のゲームだったとも思います。

　最近は、Twitterの弁護士がそのまま漫画やゲームのキャラクターのように思えることが多いのですが、実際そのままのようなツイートをしてきたのも深澤諭史弁護士であります。

[link:] 2019年10月15日16時32分の登録： REGEXP：”クエスト”／深澤諭史（@fukazawas）の検索（2015-10-22〜2019-06-07／2019年10月15日16時32分の記録27件） http://hirono2014sk.blogspot.com/2019/10/regexpfukazawas2015-10-222019-06.html

　まとめ記事を作成してから気がついたのですが、ドラゴンクエストという人気ゲームがありました。クエストというのはゲームによく出てくる言葉だと思ったのですが、印象に強くあったのは深澤諭史弁護士の「法クラクエスト」です。

▶（05／27） TW fukazawas（深澤諭史） 日時：2016-07-27 09:44:00 +0900 URL： https://twitter.com/fukazawas/status/758100645551276032
{% tweet 758100645551276032 %}
> 異世界の勇者「うちの世界じゃ，『魔王を倒せ』と王様はいうのだけれども，５０ゴールドと最安装備しかもらえないんだ。酷いだろ。」 \n \n 法クラの勇者「先払いしてもらえるだけいいじゃないか。こっちの王様（冒険者テラス）じゃ，実費も後払で下手すりゃ踏み倒されるんだぞ」 \n #法クラクエスト

▶（06／27） TW fukazawas（深澤諭史） 日時：2016-07-27 09:50:00 +0900 URL： https://twitter.com/fukazawas/status/758102303761047552
{% tweet 758102303761047552 %}
> 冒険者テラス「隣町に魔王軍が向かっている！隣町を救うため，直ちに急行して下さい！」 \n （討伐後） \n 冒険者テラス「魔王軍の到着後のため，報酬はゼロゴールドです。」 \n #法クラクエスト

▶（07／27） RT fukazawas（深澤諭史）｜Jakotsunya（魔王じゃこにゃー） 日時：2016-07-27 10:02:00 +0900／2013-12-19 22:33:00 +0900 URL： https://twitter.com/fukazawas/status/758105254483283969 https://twitter.com/Jakotsunya/status/413663480781103104
{% tweet 758105254483283969 %}
> この世界がおかしくなったのは、今の司法改革になってからじゃ・・・ \n \n #法クラクエスト

▶（13／27） TW fukazawas（深澤諭史） 日時：2017-05-16 22:24:00 +0900 URL： https://twitter.com/fukazawas/status/864471601772765184
{% tweet 864471601772765184 %}
> 「弁護士よ！ \n なにゆえ　国選や扶助事件を　じゅにん　するのか？ \n 弁護士の苦しみこそ　わが　よろこび。 \n じょうぶつするものこそ　うつくしい。 \n さあ　わが　ほうしゅうけっていの　まえで　ふんしするがよい！ \n 」 \n #法クラクエスト

▶（21／27） TW fukazawas（深澤諭史） 日時：2018-08-26 09:36:00 +0900 URL： https://twitter.com/fukazawas/status/1033513481381629952
{% tweet 1033513481381629952 %}
> 弁護士の困窮こそ，わがよろこび。成仏する者こそ，美しい。 \n さあ，我が報酬決定の前で憤死するがよい！ \n #法クラクエストにありがちなこと

▶（22／27） TW fukazawas（深澤諭史） 日時：2018-08-26 12:57:00 +0900 URL： https://twitter.com/fukazawas/status/1033564022983938048
{% tweet 1033564022983938048 %}
> 非弁「せんせいは どんと かまえてくれるだけで いいです。げつがく５０まんえん を ほしょうしましょう」 \n #法クラクエストにありがちなこと

▶（24／27） RT fukazawas（深澤諭史）｜popohito（ぽぽひと@常時発動型煽りスキル持ち） 日時：2019-06-07 14:34:00 +0900／2019-06-07 13:35:00 +0900 URL： https://twitter.com/fukazawas/status/1136869069926195200 https://twitter.com/popohito/status/1136854108101496832
{% tweet 1136869069926195200 %}
> ちょうていいいん「きじつをぞっこうさせてくださいますね？」 \n \n はい \n ➡️いいえ \n \n ちょうていいいん「そんな ひどい……。」 \n ちょうていいいん「きじつをぞっこうさせてくださいますね？」 \n \n #法クラクエスト

　この「ぽぽひと」というアカウントもまるでゲームのキャラクターなのですが、感熱紙と同じく「ぽぽひと」以外の部分は、プロフィールの名前を何度か変更させてきたように思います。

```
[1282]  % mysql -u root benngosi_twitter -e 'SELECT DISTINCT name FROM tw_user_tweet WHERE user LIKE "popohito"\G'|sed 's/\*/＊/g'
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 1. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
name: ぽぽひと
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 2. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
name: ぽぽひと@内閣総辞職ビーム
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 3. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
name: ぽぽひと@死して屍動けばゾンビ
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 4. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
name: ぽぽひと@常時発動型煽りスキル持ち
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 5. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
name: ぽぽひと@内閣調査室所属
```

　こちらの「ぽぽひと」の方がプロフィールの名前の変更が多いとも思ったのですが、意外に少ない5件でした。目をむくようなツイートを見かける頻度も多かったので、感熱紙というアカウントよりはツイートの記録の頻度は高いと思います。

　記録装置の発動を行っています。不思議に思うのは、この「ぽぽひと」というアカウントについて、弁護士としてどうなのか以前に、弁護士であることを疑うツイートを見かけたことがないことです。

[link:] 2019年10月15日16時50分の登録： REGEXP：”@popohito”／モトケン（@motoken_tw）の検索（2016-03-06〜2019-10-08／2019年10月15日16時50分の記録75件） http://hirono2014sk.blogspot.com/2019/10/regexppopohitomotokentw2016-03-062019.html

　記録装置はまだ発動中ですが、モトケンこと矢部善朗弁護士（京都弁護士会）のツイートに含まれるものを確認と同時にまとめ記事の作成を行いました。この手のものは処理が早く、ほぼ一瞬で完了します。75件という記録数が出ています。

motoken_tw ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW motoken_tw（モトケン） 日時：2019/10/08 08:23 URL： https://twitter.com/motoken_tw/status/1181349300111998976
> @hibinaya @prewarwrestler @popohito @AbeShinzo 権力が自分に都合の悪い報道に圧力をかけようとするのは当たり前。 \n そういう権力に対して、権力を批判するのが報道機関の使命だ、と言うなら、圧… https://t.co/72SpZnvGAM
▷▷▷　　　　　End　　　　　▷▷▷

　比較的最近のTwitterの仕様変更だと思いますが、他二人とブラウザで表示されていた中に「ぽぽひと」のアカウントが含まれ、TwitterAPIで取得したツイートにも上記のように４つのメンションが含まれています。

　次のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートは、ぽぽひと宛の返信であることが、埋め込みツイートではっきり表示されています。ぽぽひととの会話の中に警察批判がテーマとなっているようです。それも8月11日なので比較的最近の記録です。

▶（72／75） TW motoken_tw（モトケン） 日時：2019-08-11 20:11:00 +0900 URL： https://twitter.com/motoken_tw/status/1160508959150657536
{% tweet 1160508959150657536 %}
> @popohito 警察官は警察の上司の命令に従うので、公判検事がいくら不自然だろと言っても言うことを聞かない。

popohito ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW popohito（ぽぽひと@内閣調査室所属） 日時：2019/08/11 08:49 URL： https://twitter.com/popohito/status/1160337410514812928
> ある公務執行妨害事件で、３人の警察官が主要部分について一言一句同じ内容のコピペの供述調書を出してきた。 \n  \n それを見たときは「おいおい手抜きすんなよ」と呆れただけだったが、公判廷で「示し合わせはしていません。３人別々に調書を作りまし… https://t.co/Z7i5Zr1phK
▷▷▷　　　　　End　　　　　▷▷▷

　装置の処理が完了していました。

```
2019年10月15日16時51分の実行記録
twitterAPI-search-lawList-mydql-add.rb "to:popohito"
ツイート数：54/1541 リツイート数：10/1541 トータル：116
hirono_hideki 0／0件
kk_hirono 0／0件
s_hirono 0／0件
```

　Twitterの検索は独自の書式パターンがいくつかあるのですが、"to:popohito"というのは、ぽぽひとのアカウントを指定した返信になります。一方でこのあとのまとめ記事は、”@popohito”を検索対象とするので、返信以外のものも含まれてくると思います。

▶（25／27） RT fukazawas（深澤諭史）｜popohito（ぽぽひと@常時発動型煽りスキル持ち） 日時：2019-06-07 14:37:00 +0900／2019-06-07 13:22:00 +0900 URL： https://twitter.com/fukazawas/status/1136869676061847552 https://twitter.com/popohito/status/1136850817699287040
{% tweet 1136869676061847552 %}
> べんごしは しんけんについてつぶやいた。 \n \n そういうところだぞが あらわれた！ \n \n #法クラクエスト

　ほとんどが「ひらがな」のツイートで、検索に含まれることを避けたとも考えられますが、ここに重要なキーワードが含まれていました。「そういうところだぞ」という部分がそれになります。すでにまとめ記事として作成したものがあったかと思います。

　「おれたちゃ、べんごし、おまつりだ！」（俺達、弁護士、お祭りだ！）とでも叫んでいるように見える弁護士ワードの一つです。

```
[1260]  % dp -p|grep そういうとこだぞ
[link:] 2018年02月15日22時16分の登録： ＼ほうたろう　@lawyerhotaro＼あはは、仮想通貨で大損こいてCC被害者弁護団の費用を高いって言ってる人、そういうとこだぞｗ http://hirono2014sk.blogspot.com/2018/02/lawyerhotarocc.html
[link:] 2018年06月23日14時12分の登録： ＼コントラムンディ　@un_co_the2nd＼連れ去り、で検索すると、bioの段階で「そういうとこだぞ」ってなるアカウントがいっぱい出てくる http://hirono2014sk.blogspot.com/2018/06/uncothe2ndbio.html
[link:] 2019年02月03日14時12分の登録： ＼チョココロネ　@un_co_the2nd＼・弁護士の報酬になる←なら任意に払え\n・養育費欲しいほど金がないなら親権よこせ←そういうとこだぞ http://hirono2014sk.blogspot.com/2019/02/uncothe2nd.html
[link:] 2019年02月17日22時37分の登録： ％@noooooooorth　ノースライム(50倍)％itterの観測範囲内に過ぎないが離婚やら親権やら養育費やらに絡む部分にはてきめんに「そういうとこだぞ」という人が多い気がする。 http://hirono2014sk.blogspot.com/2019/02/noooooooorth50itter.html
[link:] 2019年02月17日22時40分の登録： ％@himaben1st　暇弁(暇とは言ってない)％そういうとこだぞ？ http://hirono2014sk.blogspot.com/2019/02/himaben1st_17.html
[link:] 2019年04月16日21時58分の登録： ＼仙猫カリン　@Bibendum65＼相手の都合を考えずに自分中心で物事を進めようとする。\nそういうとこだぞ案件（定期） http://hirono2014sk.blogspot.com/2019/04/bibendum65_16.html
[link:] 2019年04月17日09時22分の登録： ＼暇弁(暇とは言ってない)　@himaben1st＼この引用ツイートのリプが地獄絵図すぎて、「そういうとこだぞ？」の一言しか浮かんでこない。 http://hirono2014sk.blogspot.com/2019/04/himaben1st_58.html
[link:] 2019年04月17日09時29分の登録： ＼うの字　@un_co_the2nd＼そういうとこだぞホイホイすぎて草\n\n「夫婦で話し合ってできるのに弁護士が介入する必要はない」って言ってくる人、相手方の言い分聞かなく http://hirono2014sk.blogspot.com/2019/04/uncothe2nd_90.html
[link:] 2019年05月05日21時47分の登録： ＼深澤諭史　@fukazawas＼まさに、「そういうとこだぞ」という話ですね。（・∀・；） http://hirono2014sk.blogspot.com/2019/05/fukazawas_49.html
[link:] 2019年06月03日03時27分の登録： ＼暇弁(暇とは言ってない)　@himaben1st＼返信先: @fukazawasさん\nまさに「そういうとこだぞ？」案件です。\n\n http://hirono2014sk.blogspot.com/2019/06/himaben1st-fukazawas.html
[link:] 2019年06月03日03時28分の登録： ＼深澤諭史　@fukazawas＼まさに\nそういうとこだぞ？\nって話ですね（・∀・；） http://hirono2014sk.blogspot.com/2019/06/fukazawas_3.html
[link:] 2019年06月21日08時49分の登録： ＼D弁　@dben82716007＼なんか暴れ回ってるB垢見たけど、これがいわゆる、そういうとこだぞ、案件なわけですね\n\n（そんなんでは支持を得られないヨ） http://hirono2014sk.blogspot.com/2019/06/ddben82716007b.html
[link:] 2019年06月26日07時46分の登録： ＼魚占い　@sakanauranai＼そういうとこだぞ は、どうやってこれまでの◯十年間、社会生活を過ごしてきたのか。 http://hirono2014sk.blogspot.com/2019/06/sakanauranai_26.html
[link:] 2019年06月26日09時08分の登録： REGEXP：”そういうとこだぞ”／データベース登録済みツイート：2019年06月26日09時07分の記録：ユーザ・投稿：30／191件 http://hirono2014sk.blogspot.com/2019/06/regexp20190626090730191.html
[link:] 2019年06月26日09時13分の登録： ％@un_co_the2nd　うの字％連れ去り、で検索すると、bioの段階で「そういうとこだぞ」ってなるアカウントがいっぱい出てくる http://hirono2014sk.blogspot.com/2019/06/uncothe2ndbio.html
[link:] 2019年06月26日09時13分の登録： ％@lawkus　ystk％「そういうとこだぞ」という人を呼び寄せそうなツイート。  http://hirono2014sk.blogspot.com/2019/06/lawkusystk.html
[link:] 2019年07月12日19時52分の登録： ＼深澤諭史　@fukazawas＼（；・∀・）ＤＶの話題になると，「そういうとこだぞ」リプライが沢山ぶら下がる現象って，もう名前はついていましたよね。 http://hirono2014sk.blogspot.com/2019/07/fukazawas_98.html
[link:] 2019年08月15日11時42分の登録： REGEXP：”そういうとこだぞ”／データベース登録済みツイート：2019年08月15日11時41分の記録：ユーザ・投稿：38／214件 http://hirono2014sk.blogspot.com/2019/08/regexp20190815114138214.html
[link:] 2019年08月26日19時09分の登録： ＼深澤諭史　@fukazawas＼他人の労働について敬意を払えない者と，円満な家庭生活を築くのは難しいですよね。\n「そういうとこだぞ」といわれてしまいかねないですね。 http://hirono2014sk.blogspot.com/2019/08/fukazawas_66.html
[link:] 2019年08月28日19時01分の登録： ＼暇弁(暇とは言ってない)　@himaben1st＼そういうとこだぞマンがまた釣れた http://hirono2014sk.blogspot.com/2019/08/himaben1st_28.html
[link:] 2019年09月04日11時40分の登録： ＼うの字　@un_co_the2nd＼クツー無理なのってこの人のこういうとこが大いにある\n\n「そういうとこだぞ」なんだよな\n対立煽る商売は楽しいか？ http://hirono2014sk.blogspot.com/2019/09/uncothe2nd_4.html
[link:] 2019年09月21日17時08分の登録： ＼うの字　@un_co_the2nd＼そうだんで自分の思い通りのヨイショが得られなかったからって受付の人に八つ当たりすんなよ\nそういうとこだぞ http://hirono2014sk.blogspot.com/2019/09/uncothe2nd_21.html
[link:] 2019年09月25日16時05分の登録： ％@noooooooorth　ノースライム％Twitterの観測範囲内に過ぎないが離婚やら親権やら養育費やらに絡む部分にはてきめんに「そういうとこだぞ」という人が多い気がする。 http://hirono2014sk.blogspot.com/2019/09/noooooooorthtwitter.html
```

　次の深澤諭史弁護士のリツイートとして記録されている「優良にゃん」というアカウントですが、具体的な弁護士業務に関連したツイートが多く、実名の弁護士アカウントもリアルな付き合いをしているようなツイートをしていることがありました。アカウントは削除されているようです。

▶（26／27） RT fukazawas（深澤諭史）｜jmtpjmgmt（優良にゃん?） 日時：2019-06-07 14:37:00 +0900／2019-06-07 13:19:00 +0900 URL： https://twitter.com/fukazawas/status/1136869669132853250 https://twitter.com/jmtpjmgmt/status/1136850188218191872
{% tweet 1136869669132853250 %}
> いちねん がんばった こくせん 20まそ いかなかった \n \n #法クラクエスト

▶（27／27） RT fukazawas（深澤諭史）｜jmtpjmgmt（優良にゃん?） 日時：2019-06-07 14:37:00 +0900／2019-06-07 13:27:00 +0900 URL： https://twitter.com/fukazawas/status/1136869648828211200 https://twitter.com/jmtpjmgmt/status/1136852211638497280
{% tweet 1136869648828211200 %}
> そういうとこだぞA「妻は嘘つき」 \n 同B「連れ去りだ！」 \n 同C「金目的！」 \n 同D「弁護士がたぶらかした！」 \n \n どんどんおっきくなっていく \n \n キングそういうとこだぞ「養育費がなくても子どもは育つ」 \n \n #法クラクエスト

　まとめ記事の作成投稿が完了していました。「REGEXP：”@popohito”／データベース登録済みツイート：2019年10月15日17時04分の記録：ユーザ・投稿：211／975件」というタイトル名です。URLはまた別にご紹介をしたいと思います。

　改めて深澤諭史弁護士というのもアニメやゲームの影響を強く受けているようですが、より強くそのような影響を感じてきたのが感熱紙というアカウントで、そのままゲームの世界を覗き込んでいるような気分になることもあります。

　繰り返しますが最近はタイムラインを辿ってツイートを読むことも少ないので変化はわからないですが、真面目なツイートも少なくなく、それも実際の警察官としての業務に裏打ちされているような具体的なものでした。趣味が半分以上でやっているのかもしれません。

〈〈〈：Emacs： 2019-10-15（火曜日）17：28 　〈〈〈

