#+TITLE: "「この男の行動は全て金儲けのための炎上商法、この男に投票した人は、自分の愚かさを自覚して後悔するべき」とするツイート"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-10-03 16:34:08 +0900
FILE_NAME: 2019-10-03-163408_「この男の行動は全て金儲けのための炎上商法、この男に投票した人は、自分の愚かさを自覚して後悔するべき」とするツイート.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: モトケンこと矢部善朗弁護士（京都弁護士会）,炎上商法
記事タイトル名の文字数：58　保存ファイル名の文字数：80
#+STARTUP: showeverything


* 「この男の行動は全て金儲けのための炎上商法、この男に投票した人は、自分の愚かさを自覚して後悔するべき」とするモトケンこと矢部善朗弁護士（京都弁護士会）のツイート
  CLOCK: [2019-10-03 木 22:05]--[2019-10-03 木 22:09] =>  0:04
  CLOCK: [2019-10-03 木 17:19]--[2019-10-03 木 17:49] =>  0:30

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: モトケンこと矢部善朗弁護士（京都弁護士会）,炎上商法

〉〉〉：Emacs： 2019-10-03（木曜日）17：19　 〉〉〉

motoken_tw ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW motoken_tw（モトケン） 日時：2019/09/28 10:25 URL： https://twitter.com/motoken_tw/status/1177756134410604544
> マツコ氏のコメントが正しかったことを立花（敬称を付ける気にならん）自身が証明してますね。 \n この男の行動は全て金儲けのための炎上商法。 \n この男に投票した人は、自分の愚かさを自覚して後悔するべきだと思う。 https://t.co/0wi2vlH7Ya
▷▷▷　　　　　End　　　　　▷▷▷

　2,3日前のツイートかと思っていたのですが、モトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインを遡って見つけ出すと9月28日のツイートとなっていました。それも午前中の10時25分が投稿時刻となっているようです。

　さきほど気がついたのですが、数日前の私怨を含むモトケンこと矢部善朗弁護士（京都弁護士会）のツイートは、このツイートの返信の中で、モトケンこと矢部善朗弁護士（京都弁護士会）が同じ言葉に反応したものであったようです。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜36555023_（しまイさん） 日時：2019-10-03 17:40／2019/09/28 10:28 URL： https://twitter.com/kk_hirono/status/1179677519412248576 https://twitter.com/36555023_/status/1177756846787944449
> @motoken_tw あの党が私怨からできたものだと思ってしまいますのだ
▶▶▶　　　　　End　　　　　▶▶▶

motoken_tw ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW motoken_tw（モトケン） 日時：2019/09/28 10:29 URL： https://twitter.com/motoken_tw/status/1177757286875295744
> @36555023_ 私怨を金儲けに転用した才能は認める。絶対真似したくはないが。
▷▷▷　　　　　End　　　　　▷▷▷

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜36555023_（しまイさん） 日時：2019-10-03 17:41／2019/09/28 10:30 URL： https://twitter.com/kk_hirono/status/1179677813852405760 https://twitter.com/36555023_/status/1177757538416070658
> @motoken_tw NHKも確かに襤褸が出てますのだ、でもあの党はNHK以外の事象で炎上すること多い気がしますのだ……
▶▶▶　　　　　End　　　　　▶▶▶

　他にも次のツイートがモトケンこと矢部善朗弁護士（京都弁護士会）のツイートに対する、ぶら下がりと表現されることもありますが、会話や返信の流れとして表示されています。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜zenitasou（銭田社長@会社員から資産家になる） 日時：2019-10-03 17:46／2019/09/28 23:54 URL： https://twitter.com/kk_hirono/status/1179679204368977920 https://twitter.com/zenitasou/status/1177959891362693121
> @motoken_tw @kinasato_cap001 他の政党もろくに掲げた政策を実施しない詐欺集団なので、N国党だけをどうこう言うのは筋が違うのではないでしょうか。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜6LreZaQDyvt38Vi（ささやん） 日時：2019-10-03 17:46／2019/09/29 09:19 URL： https://twitter.com/kk_hirono/status/1179679146722484224 https://twitter.com/6LreZaQDyvt38Vi/status/1178102026464419841
> @newamanojaku3 収支報告書に書けない上に議員が支持者の裁判費用肩代わりは金銭の授受でアウトじゃね？
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜newamanojaku3（shinji） 日時：2019-10-03 17:46／2019/09/28 17:08 URL： https://twitter.com/kk_hirono/status/1179679106901790721 https://twitter.com/newamanojaku3/status/1177857592573382656
> @motoken_tw 献金を一切受け取らずに党運営をしなければならないので、そのような手法になると思われます。そして、その稼いだお金でNHK撃退シールの発送や不払いによって民事で賠償金の支払い責任を負った支持者の肩代わりをすると… https://t.co/k9u3S8PXsr
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜silvergriffin18（御神苗 雄 (White Glriffon)） 日時：2019-10-03 17:46／2019/09/28 23:23 URL： https://twitter.com/kk_hirono/status/1179678987888365575 https://twitter.com/silvergriffin18/status/1177952084408143872
> @motoken_tw @suuzanantonko 同感ですね。  チンピラに貴重な票をくれてやった莫迦どもは猛省すべきだと思います。
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜yu_Rodenberger（ゆぅ🌒L.I.J） 日時：2019-10-03 17:45／2019/09/29 08:35 URL： https://twitter.com/kk_hirono/status/1179678942359220224 https://twitter.com/yu_Rodenberger/status/1178090892126646273
> @motoken_tw 参院選前あたりから胡散臭さが増してきたのでYoutubeも見なくなりました。 段々カルト臭も漂ってきたので、危険度マシマシでいくと思いますよ
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜darknnn（ばんきら） 日時：2019-10-03 17:45／2019/09/28 10:56 URL： https://twitter.com/kk_hirono/status/1179678836927029248 https://twitter.com/darknnn/status/1177763947769815041
> @motoken_tw 炎上商法は100人中99人が嫌悪しても、変わり者1人でも賛同者が増えたら勝ちの商法だと思います。 まず100人に知ってもらうことが第一でその為の炎上かと。  なので「N国はろくでもない」と拡散した時点で、相… https://t.co/uFYsjedTxi
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜karafune（からふね®︎） 日時：2019-10-03 17:45／2019/09/28 20:02 URL： https://twitter.com/kk_hirono/status/1179678800721764352 https://twitter.com/karafune/status/1177901284705177601
> @motoken_tw この満面の笑みに狂気すら感じます……
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜rukario625（魑魅魍魎の主を目指して） 日時：2019-10-03 17:45／2019/09/28 10:27 URL： https://twitter.com/kk_hirono/status/1179678742756507649 https://twitter.com/rukario625/status/1177756624447950849
> @motoken_tw 逆に、立花氏はその投票した人の期待を裏切ったと捉えることは可能でしょうか？
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜uchi987（uchi【TAMU.FC. No.987】） 日時：2019-10-03 17:44／2019/09/29 17:50 URL： https://twitter.com/kk_hirono/status/1179678640197423104 https://twitter.com/uchi987/status/1178230636076617728
> @motoken_tw @7Znv478Zu8TnSWj そのうち戦争は人口抑制のために必要とかも言い出しそうですね。
▶▶▶　　　　　End　　　　　▶▶▶

motoken_tw ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW motoken_tw（モトケン） 日時：2019/09/29 10:19 URL： https://twitter.com/motoken_tw/status/1178117107801718786
> @zenitasou @kinasato_cap001 一つのツイートで森羅万象について批判すべきだと？
▷▷▷　　　　　End　　　　　▷▷▷

　最後は締めくくりのようなかたちにもなっているモトケンこと矢部善朗弁護士（京都弁護士会）のツイートです。この先に続くと思われる返信は表示がありません。

〈〈〈：Emacs： 2019-10-03（木曜日）17：49 　〈〈〈

〉〉〉：Emacs： 2019-10-03（木曜日）22：05　 〉〉〉

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-10-03 22:07／2019/10/03 20:00 URL： https://twitter.com/kk_hirono/status/1179744905767206912 https://twitter.com/s_hirono/status/1179712881077542913
> 2019-10-03-174812_モトケン@motoken_tw·9月29日一つのツイートで森羅万象について批判すべきだと？.jpg https://t.co/VAd4IWCDPy
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-10-03 22:07／2019/10/03 16:42 URL： https://twitter.com/kk_hirono/status/1179744886448259072 https://twitter.com/s_hirono/status/1179663007816634369
> 2019-10-03-163831_モトケン@motoken_tw·9月28日私怨を金儲けに転用した才能は認める。絶対真似したくはないが。.jpg https://t.co/TIvnqiTxsS
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-10-03 22:07／2019/10/03 16:42 URL： https://twitter.com/kk_hirono/status/1179744864428101632 https://twitter.com/s_hirono/status/1179662935842385920
> 2019-10-03-163659_モトケンさんはTwitterを使っています：　「マツコ氏のコメントが正しかったことを立花（敬称を付ける気にならん）自身が証明してますね。　この男の行動は全.jpg https://t.co/gCOhpDjjWO
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-10-03 22:07／2019/10/03 16:41 URL： https://twitter.com/kk_hirono/status/1179744844777787393 https://twitter.com/s_hirono/status/1179662863964655616
> 2019-10-03-162739_モトケンさんはTwitterを使っています：　「@36555023_　私怨を金儲けに転用した才能は認める。絶対真似したくはないが。」　／　Twitter.jpg https://t.co/LwJYF4QP6R
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-10-03 22:07／2019/10/03 16:41 URL： https://twitter.com/kk_hirono/status/1179744826092208128 https://twitter.com/s_hirono/status/1179662791096979456
> 2019-10-03-162420_モトケン@motoken_tw·9月29日この人は、少しでも自分の意見を批判されると、自分の主張が全否定されたと受け止めて相手を人格攻撃する。モラハラ夫の.jpg https://t.co/UGhtv1Xw6e
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-10-03 22:07／2019/10/03 16:41 URL： https://twitter.com/kk_hirono/status/1179744808203476993 https://twitter.com/s_hirono/status/1179662719294660609
> 2019-10-03-162254_モトケンさんはTwitterを使っています：　「@s953Y4x7ukWEn9x　つまり、あなたは、自分が何の根拠もなく被曝の危険を煽る風評加害者であるこ.jpg https://t.co/UvRdMOM3G8
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-10-03 22:07／2019/10/03 16:41 URL： https://twitter.com/kk_hirono/status/1179744789454917633 https://twitter.com/s_hirono/status/1179662646708076544
> 2019-10-03-161935_ぽぽひと@内閣調査室所属さんはTwitterを使っています：　「ある程度離婚事件を扱っている弁護士に相談しろの一択でいいのでは。　ＤＶ・モラハラで攻撃の矛.jpg https://t.co/Jh5mPWVc6M
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-10-03 22:07／2019/10/03 16:40 URL： https://twitter.com/kk_hirono/status/1179744771729842177 https://twitter.com/s_hirono/status/1179662574482120704
> 2019-10-03-161855_モトケンさんがリツイートぽぽひと@内閣調査室所属@popohito·10月2日ある程度離婚事件を扱っている弁護士に相談しろの一択でいいのでは。ＤＶ・モラハ.jpg https://t.co/ohcRWBruIG
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-10-03 22:07／2019/10/03 16:40 URL： https://twitter.com/kk_hirono/status/1179744755560771584 https://twitter.com/s_hirono/status/1179662502457532416
> 2019-10-03-161351_モトケン@motoken_tw·10月2日ポイントはここだと思う。「何が問題かというと、“他人事”意識がその根底にあること。目の前には、当事者はいないと言.jpg https://t.co/6vLwAN1PTX
▶▶▶　　　　　End　　　　　▶▶▶

〈〈〈：Emacs： 2019-10-03（木曜日）22：09 　〈〈〈

