#+TITLE: "客観的事実関係は明白なので、副検事に担当させてサクッと起訴すれば東京地検もなかなかやるな、と思うけど、そうはならないだろうな。"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-10-03 14:47:51 +0900
FILE_NAME: 2019-10-03-144751_客観的事実関係は明白なので、副検事に担当させてサクッと起訴すれば東京地検もなかなかやるな、と思うけど、そうはならないだろうな。.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: モトケンこと矢部善朗弁護士（京都弁護士会）,事実関係
記事タイトル名の文字数：63　保存ファイル名の文字数：85
#+STARTUP: showeverything


* 「客観的事実関係は明白なので、副検事に担当させてサクッと起訴すれば東京地検もなかなかやるな、と思うけど、そうはならないだろうな。」というモトケンこと矢部善朗弁護士（京都弁護士会）のツイート
  CLOCK: [2019-10-03 木 15:56]--[2019-10-03 木 16:02] =>  0:06
  CLOCK: [2019-10-03 木 14:52]--[2019-10-03 木 15:50] =>  0:58

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: モトケンこと矢部善朗弁護士（京都弁護士会）,事実関係

〉〉〉：Emacs： 2019-10-03（木曜日）14：52　 〉〉〉

motoken_tw ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW motoken_tw（モトケン） 日時：2019/10/03 09:20 URL： https://twitter.com/motoken_tw/status/1179551731144781824
> 客観的事実関係は明白なので、副検事に担当させてサクッと起訴すれば東京地検もなかなかやるな、と思うけど、そうはならないだろうな。＞立花Ｎ国党首を書類送検　「人生潰す」、区議脅した疑い：朝日新聞デジタル https://t.co/b4334qZ3JN
▷▷▷　　　　　End　　　　　▷▷▷

```
警視庁は２日、ＮＨＫから国民を守る党（Ｎ国）の党首、立花孝志参院議員（５２）について、元Ｎ国の東京都中央区議の男性に対する脅迫容疑で書類送検した。関係者への取材でわかった。立花氏は同日、インターネットに投稿した動画で、同容疑にはあたらないと主張した。

　関係者によると、立花氏は７月上旬、４月の統一地方選にＮ国公認で当選した区議が離党したことを批判する動画をネットに投稿。家族らのことも知っているとして「徹底的にこいつの人生潰しにいく」などと発言し、区議を脅した疑いがある

［source：］立花Ｎ国党首を書類送検　「人生潰す」、区議脅した疑い：朝日新聞デジタル https://www.asahi.com/articles/ASMB26HPJMB2UTIL05B.html
```

　「サクッと起訴」というのも見たことのない表現だと感じましたが、元検事である現職弁護士の発言として考えるとなおさら特異なものです。もとよりこのような他者への厳しさはモトケンこと矢部善朗弁護士（京都弁護士会）の人格反応的特徴として度々見てきました。

　名誉毀損かと思ったのですが、書類送検されたという被疑事実は脅迫罪とのことです。このあと確認しますが、量刑の上限が懲役2年という刑事罰として軽いものかと思います。名誉毀損は懲役3年が上限でこれは変わりがないと思います。

```
条文［編集］
（脅迫）
第222条 　
1　生命、身体、自由、名誉又は財産に対し害を加える旨を告知して人を脅迫した者は、2年以下の懲役又は30万円以下の罰金に処する。
2 　親族の生命、身体、自由、名誉又は財産に対し害を加える旨を告知して人を脅迫した者も、前項と同様とする。
保護法益［編集］
保護法益は、意思決定の自由である。ただし、私生活の平穏も同時に保護法益となると解する説もある。

行為［編集］
脅迫罪においての脅迫は、人の生命、財産、身体、名誉、自由（通説によれば貞操や信念も含む）に対して害悪する告知を行うことである。相手が恐怖心を感じるかどうかは問わない（抽象的危険犯）。

［source：］脅迫罪 - Wikipedia https://ja.wikipedia.org/wiki/%E8%84%85%E8%BF%AB%E7%BD%AA
```

```
概要［編集］
公然とある人に関する事柄を摘示し、その人の名誉を毀損した場合に成立する（刑法230条1項）。法定刑は3年以下の懲役若しくは禁錮または50万円以下の罰金である。

毀損された名誉が死者のものである場合には、その摘示内容が客観的に虚偽のものでなければ処罰されない（刑法230条2項）。ただし、名誉毀損をした後、名誉を毀損された者が死亡した場合には、通常の名誉毀損罪として扱われ、当該事実が虚偽でなかったということのみでは免責されない（刑法230条の2の適用が問題となる）。

名誉毀損罪（1項）［編集］
保護法益［編集］
本罪の保護法益たる「名誉」について、通説はこれを外部的名誉、すなわち社会に存在するその人の評価としての名誉（人が他人間において不利益な批判を受けない事実。人の社会上の地位または価値）であるとする。

これに対して、同罪の名誉とは、名誉感情（自尊感情）であるとする説がある。この説によれば、法人、あるいは法人でない社団もしくは財団に対する名誉毀損罪は、論理的には成立し難いこととなる。

背徳または破廉恥な行為のある人、徳義または法律に違反した行為をなした者であっても、当然に名誉毀損罪の被害者となりうる（大判昭和8年9月6日刑集12巻1590頁）。

客体［編集］
本罪の客体は「人の名誉」である。この場合の人とは、「自然人」「法人」「法人格の無い団体」などが含まれる（大判大正15年3月24日刑集5巻117頁）。ただし、「アメリカ人」や「東京人」など、特定しきれない漠然とした集団については含まれない（大判大正15年3月24日刑集5巻117頁）。

行為［編集］
本罪の行為は人の名誉を公然と事実を摘示して毀損することである。

通説では、本罪は抽象的危険犯とされる。つまり、外部的名誉が現実に侵害されるまでは必要とされず、その危険が生じるだけで成立する。

事実の有無、真偽を問わない。ただし、公共の利害に関する事実を、専ら公益目的で摘示した結果、名誉を毀損するに至った場合には、その事実が真実であると証明できた場合は処罰されない（230条の2第1項、#真実性の証明による免責参照）。

［source：］名誉毀損罪 - Wikipedia https://ja.wikipedia.org/wiki/%E5%90%8D%E8%AA%89%E6%AF%80%E6%90%8D%E7%BD%AA
```

　やはり名誉毀損罪の方が脅迫罪よりは法定刑が重くなっていました。脅迫罪での有罪判決というのは余り聞いた憶えがないですが、モトケンこと矢部善朗弁護士（京都弁護士会）がツイートで副検事としているので、簡易裁判所が管轄になるのかもしれません。

　簡易裁判所であれば略式命令という手続きがあるのかと思いますが、脅迫罪だけではない名誉毀損罪でも略式命令というのは聞いたことがないと思いました。成立が争われやすい罪名とも思われますが、そもそも起訴率が低いような個人的な印象もあります。

　今回調べてみて、脅迫罪も名誉毀損罪も同じ抽象的危険犯が通説だと確認しました。脅迫罪の方はその旨の判例があったような気がしますが、名誉毀損罪で抽象的危険犯というのは余り見かけてこなかった気もします。

　名誉毀損罪の場合は、公益性や真実性の証明が問題にされることが多いという印象です。著名人以外の名誉毀損罪での有罪というのは、ニュースとして見かけることがないとも思いますが、報道すること自体が名誉を傷つけ、問題化させるという配慮もあるいはあるのかと想像はします。

　モトケンこと矢部善朗弁護士（京都弁護士会）が「副検事に担当させてサクッと起訴すれば東京地検もなかなかやるな」とする対象は、「ＮＨＫから国民を守る党（Ｎ国）の党首、立花孝志参院議員（５２）」になりますが、数日前にもとても痛烈な批判のツイートを見かけていました。

```
▶（10／15） TW motoken_tw（モトケン） 日時：2019-09-14 09：29：00 +0900 URL： https：//twitter.com/motoken_tw/status/1172668623527133184
{% tweet 1172668623527133184 %}
> N国の立花がYouTubeでしょうもない言い訳をしているんだが、彼の本業はYouTuberつまりYouTubeに動画を投稿して金を稼いでいる人なので、リンクは貼らない。

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”立花”／モトケン（@motoken_tw）の検索（2017-11-16〜2019-09-29／2019年10月03日15時32分の記録15件） http://hirono2014sk.blogspot.com/2019/10/regexpmotokentw2017-11-162019-09.html
```

motoken_tw ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW motoken_tw（モトケン） 日時：2019/09/23 09:04 URL： https://twitter.com/motoken_tw/status/1175923863743389696
> 立花といい小西といい、彼らみたいな恫喝体質の人間が国会議員をやっていることにとても憤りを感じております。 \n 私が黒瀬さんの立場なら、小西議員を提訴することを本気で考えます。 \n ただし、黒瀬さんに提訴をお勧めするわけではありません。面倒臭いですからね。
▷▷▷　　　　　End　　　　　▷▷▷

motoken_tw ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW motoken_tw（モトケン） 日時：2019/09/28 10:25 URL： https://twitter.com/motoken_tw/status/1177756134410604544?phpMyAdmin=cfc2644bd9c947213a0141747c2608b0
> マツコ氏のコメントが正しかったことを立花（敬称を付ける気にならん）自身が証明してますね。 \n この男の行動は全て金儲けのための炎上商法。 \n この男に投票した人は、自分の愚かさを自覚して後悔するべきだと思う。 https://t.co/0wi2vlH7Ya
▷▷▷　　　　　End　　　　　▷▷▷

motoken_tw ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW motoken_tw（モトケン） 日時：2019/09/29 10:59 URL： https://twitter.com/motoken_tw/status/1178127218066612224?phpMyAdmin=cfc2644bd9c947213a0141747c2608b0
> 立花孝志は、今NHKから国民を守るために何をしているのだろう？ \n なお、このツイートのリプ欄に彼のYouTubeの動画のリンクを貼り付けるのはご遠慮ください。 \n 貼り付けられたとしても私は見ません。 \n 他の人にも見ないことを推奨します。
▷▷▷　　　　　End　　　　　▷▷▷

　YouTube動画を炎上商法の金目的と決めつけていますが、選挙で選ばれた国会議員で、たしか国会議員というのは会期中の不逮捕特権が認められるほど身分が保障されていたように思います。

```
【弁護士】 次に憲法５０条は「両議院の議員は、法律の定める場合を除いては、国会の会期中逮捕されず、会期前に逮捕された議員は、その議院の要求があれば、会期中これを釈放しなければならない。」と規定しています。いわゆる不逮捕特権というものです。

【生徒】 国会議員だけに不逮捕特権を認めるなんて平等に反しないんですか？

【弁護士】 いいところに気づきましたね。不逮捕特権は法の下の平等（14条1項）の例外と考えられています。

【生徒】 そうなんですか。
では、なぜ国会議員にだけ不逮捕特権が認められているのですか？

【弁護士】 一般に①議員の身体の自由を保障し、政府によって議員の職務執行が妨げられないようにすること、②議員での審議を可能にすることの２つが理由だとされています。

［source：］第50条　議員の不逮捕特権 | 日本国憲法を対話で学ぼう http://www.xn--vcs02wdldnpbczo.biz/kenpou/kokkai/s_50.html
```

　あるネット記事が、モトケンこと矢部善朗弁護士（京都弁護士会）の苛烈な批判の的、根拠になったいたようですが、もともとマスコミやネット記事に対しても厳しく批判してきたのがモトケンこと矢部善朗弁護士（京都弁護士会）のスタンスだったわけです。

　立花氏のYouTube動画は、私も見ておらず開いてもいないですが、不本意に記事とされたことの釈明や反論のようなものとも思えました。それもモトケンこと矢部善朗弁護士（京都弁護士会）は金儲けのための炎上商法と決めつけ、ここでもサクッと起訴、と評しているわけです。

　少し調べて確認しておきたいこともあるので、続きは別のエントリーとして取り上げたいと思います。

〈〈〈：Emacs： 2019-10-03（木曜日）15：50 　〈〈〈

〉〉〉：Emacs： 2019-10-03（木曜日）15：56　 〉〉〉

　スクリーンショットの記録の添付を忘れていたかと思います。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-10-03 15:57／2019/10/02 19:43 URL： https://twitter.com/kk_hirono/status/1179651771787923461 https://twitter.com/s_hirono/status/1179346272437833730
> 2019-10-02-190146_モトケン（@motoken_tw）さんの返信があるツイート　／　Twitter.jpg https://t.co/y8KsK06tOF
▶▶▶　　　　　End　　　　　▶▶▶

　スクリーンショットの記録自体を忘れていたかもしれません。見当たらなかったので新たにスクリーンショットを作成しました。モトケンこと矢部善朗弁護士（京都弁護士会）のツイートは6時間前として表示され、投稿時刻は本日午前9時20分となっていました。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-10-03 16:02／2019/10/03 16:00 URL： https://twitter.com/kk_hirono/status/1179652968078987264 https://twitter.com/s_hirono/status/1179652500124647426
> 2019-10-03-160009_モトケンさんはTwitterを使っています：　「客観的事実関係は明白なので、副検事に担当させてサクッと起訴すれば東京地検もなかなかやるな、と思うけど、そう.jpg https://t.co/9CMLL3aUmE
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-10-03 16:02／2019/10/03 16:00 URL： https://twitter.com/kk_hirono/status/1179652954837512193 https://twitter.com/s_hirono/status/1179652427991023616
> 2019-10-03-155940_モトケン@motoken_tw·6h客観的事実関係は明白なので、副検事に担当させてサクッと起訴すれば東京地検もなかなかやるな、と思うけど、そうはならないだ.jpg https://t.co/8yQRQr3EuR
▶▶▶　　　　　End　　　　　▶▶▶

〈〈〈：Emacs： 2019-10-03（木曜日）16：02 　〈〈〈

