#+TITLE: "牧野雅子　『痴漢とはなにか　被害と冤罪をめぐる社会学』"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-11-30 07:44:13 +0900
FILE_NAME: 2019-11-30-074413_牧野雅子　『痴漢とはなにか　被害と冤罪をめぐる社会学』.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 太田啓子弁護士,性犯罪,被害者,冤罪,痴漢
記事タイトル名の文字数：27　保存ファイル名の文字数：49
#+STARTUP: showeverything


* 2019年11月29日、太田啓子弁護士のタイムラインで発見：牧野雅子　『痴漢とはなにか　被害と冤罪をめぐる社会学』
  CLOCK: [2019-11-30 土 07:46]--[2019-11-30 土 08:17] =>  0:31

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 太田啓子弁護士,性犯罪,被害者,冤罪,痴漢

〉〉〉：Emacs： 2019-11-30（土曜日）07：46　 〉〉〉

katepanda2 ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW katepanda2（弁護士 太田啓子） 日時：2019/11/29 17:50 URL： https://twitter.com/katepanda2/status/1200336306527592448
> 「「スレスレ痴漢法」の一部。5ページにわたって痴漢の多い路線や「感謝の気持でさわること」などが指南されていた。人気コピーライターが表紙コピーを担当するなど話題雑誌だった」実際の性暴力をこんな風に娯楽にしてたんですよね。こういうこと… https://t.co/mDsH8zG7DC
▷▷▷　　　　　End　　　　　▷▷▷

　上記の太田啓子弁護士のツイートは、投稿時刻が昨日の17時50分となっていました。牧野雅子という名前も初めて見たように思いましたが、Twilogに痕跡がないのかまだ確認はしていません。

　次がここ最近、10月16日以降の太田啓子弁護士のツイートの記録になります。単純な検索であるので太田という文字を含むだけの違った記事が交じる可能性もあります。

[link:] 2019年10月16日15時24分の登録： ＼モトケン　@motoken_tw＼太田弁護士に直接質問してみました。 http://hirono2014sk.blogspot.com/2019/10/motokentw_16.html
[link:] 2019年10月16日15時26分の登録： ＼弁護士 太田啓子　@katepanda2＼こういうテーマでは毎回いくつかを理解できていないリプライが飛び交うけれど、①胸などを性的に強調した描写が常にダメなわけではなく http://hirono2014sk.blogspot.com/2019/10/katepanda2.html
[link:] 2019年10月16日15時54分の登録： ＼松本ときひろ 弁護士 品川区議会議員　@matsumoto_toki＼宇崎ちゃんの件、太田弁護士の言説を肯定すれば彼らは次は放送自体に同じクレームをあげる。その次は更に http://hirono2014sk.blogspot.com/2019/10/matsumototoki.html
[link:] 2019年10月17日13時33分の登録： ＼弁護士 太田啓子　@katepanda2＼「判決前の取材に『ばれないしいけると思った、万引きと一緒』」性暴力加害者の認識って往々にして本当にこれくらい軽いと思う。被害者 http://hirono2014sk.blogspot.com/2019/10/katepanda2_17.html
[link:] 2019年10月17日23時57分の登録： ＼hznf　@_hznf_＼今回の献血ポスターの件で、さらにリベラルが支持を減らすことになっただろう。太田弁護士、実はリベラルを壊滅させるためにわざとやってるんじゃないの http://hirono2014sk.blogspot.com/2019/10/hznfhznf_17.html
[link:] 2019年10月18日09時43分の登録： ＼弁護士 吉峯耕平（「カンママル」撲滅委員会）　@kyoshimine＼太田弁護士の追加コメントが出てます（私がミュートされているせいで一部非表示になったり見にくいので、 http://hirono2014sk.blogspot.com/2019/10/kyoshimine_18.html
[link:] 2019年10月23日10時39分の登録： ％@kumaemon9　くまえもん％太田弁護士が以前と違って集団的なクレームを煽らなくなったのは手段の相当性を意識してのことだろうし、そこは一応評価している。だからといって太田弁護士の主張を批判しないということにはならないが。 http://hirono2014sk.blogspot.com/2019/10/kumaemon9_23.html
[link:] 2019年10月23日10時40分の登録： ＼hznf　@_hznf_＼太田弁護士のお友達の神原弁護士に余命一派からの不当懲戒請求が殺到したことに対して神原弁護士が慰謝料請求訴訟を始めたことが影響している，自分の抗 http://hirono2014sk.blogspot.com/2019/10/hznfhznf_23.html
[link:] 2019年10月24日22時37分の登録： ＼高橋雄一郎　@kamatatylaw＼シュナムル御大，太田啓子先生、神原元先生は，それぞれ，男性優位社会の変革，女性の道具化の忌避，ヘイトスピーチ撲滅，といった明確な目 http://hirono2014sk.blogspot.com/2019/10/kamatatylaw_24.html
[link:] 2019年10月25日18時01分の登録： ＼hznf　@_hznf_＼太田弁護士にとっては話題になった時点で勝利宣言，というのは，キズナアイのときに「なんだこの私のアジェンダセッティング力ｗ」ととても嬉しそう自画 http://hirono2014sk.blogspot.com/2019/10/hznfhznf_66.html
[link:] 2019年10月27日08時53分の登録： ＼山口貴士 aka無駄に感じが悪いヤマベン　@otakulawyer＼宇崎ちゃんの献血ポスターの件で太田弁護士を懲戒請求した場合、不当な懲戒請求を理由に不法行為で訴えられ http://hirono2014sk.blogspot.com/2019/10/akaotakulawyer_27.html
[link:] 2019年11月06日01時28分の登録： ＼モトケン　@motoken_tw＼太田弁護士からブロックされた。\n私の批判なんかおとなしいほうだと思うんだけどな。 http://hirono2014sk.blogspot.com/2019/11/motokentw_6.html
[link:] 2019年11月25日11時57分の登録： ＃弁護士 太田啓子　@katepanda2＃のツイート／2019-11-22_2133〜2019-11-25_0901／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年11月25日11時57分 http://hirono2014sk.blogspot.com/2019/11/katepanda22019-11-2221332019-11.html
[link:] 2019年11月29日23時09分の登録： ＼弁護士 太田啓子　@katepanda2＼録音したこと自体をネガティブに評価したのか、、？ひどいな http://hirono2014sk.blogspot.com/2019/11/katepanda2.html

　ざっとみたところ、少なくとも10月16日の時点で、日本赤十字社だったと思いますが、宇崎ちゃん、という献血ポスターが法クラの弁護士らの間で話題となり、断片的なツイートの情報を見ていた程度ですが、太田啓子弁護士に炎上的な火元の発生源があったようです。

　太田啓子弁護士や伊藤和子弁護士は、女性の権利を守るため闘っているという印象が強いのですが、論理的な破綻性というのもしばしば法クラの弁護士らの指摘されているようです。しかし、その指摘する側の法クラの弁護士にも濃度の高い異常成分が検知されることもあります。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-30 08:08／2019/11/30 07:52 URL： https://twitter.com/kk_hirono/status/1200552256229142529 https://twitter.com/s_hirono/status/1200548235242131456
> 2019-11-29-232027_牧野雅子　『痴漢とはなにか　被害と冤罪をめぐる社会学』（@mhmakino）さん　／　Twitter.jpg https://t.co/FwVk42yGY2
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-30 08:08／2019/11/30 07:53 URL： https://twitter.com/kk_hirono/status/1200552237094731776 https://twitter.com/s_hirono/status/1200548308189466624
> 2019-11-29-232056_LOVE　PIECE　CLUB　ラブグッズ＆マガジン.jpg https://t.co/gymDihHJpp
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-11-30 08:08／2019/11/30 07:53 URL： https://twitter.com/kk_hirono/status/1200552207138951168 https://twitter.com/s_hirono/status/1200548380360921089
> 2019-11-29-232742_痴漢とはなにか　｜　book　｜　エトセトラブックス　／　フェミニズムにかかわる様々な本を届ける出版社.jpg https://t.co/YX7BhbSQ1i
▶▶▶　　　　　End　　　　　▶▶▶

　太田啓子弁護士のタイムラインで、牧野雅子氏のツイートを公式引用したツイートの発見時のスクリーンショットの記録というのは作成をしていなかったようです。当初はさほど重視をしていなかったということでしょう。

　この太田啓子弁護士についても余り調べていなかったかもしれず、Twitterのタイムラインの方も余り見ていませんでした。深澤諭史弁護士を主軸にした観察と記録がメインでもありました。弁護士観察日記の様相もありますが、重要さ参考資料として記録と公開を行っています。

　この後、コタツの方に移動をして、久しぶりにノートパソコンで作業を行いたいと思います。

〈〈〈：Emacs： 2019-11-30（土曜日）08：17 　〈〈〈

